OfficeDev/teams-toolkit

- packages/sdk/package-lock.json
- packages/sdk/package.json
node-fetch https://dev.azure.com/mseng/VSIoT/_componentGovernance/721/alert/79900?typeId=136119
simple-get https://dev.azure.com/mseng/VSIoT/_componentGovernance/721/alert/80298?typeId=136119
> chore(sdk): upgrade dependencies to fix vulnerabilities

- packages/fx-core/src/plugins/resource/apim/answer.ts
- packages/fx-core/src/plugins/resource/apim/config.ts
- packages/fx-core/src/plugins/resource/apim/constants.ts
- packages/fx-core/src/plugins/resource/apim/error.ts
- packages/fx-core/src/plugins/resource/apim/factory.ts
- packages/fx-core/src/plugins/resource/apim/index.ts
- packages/fx-core/src/plugins/resource/apim/interfaces/IApimResource.ts
- packages/fx-core/src/plugins/resource/apim/managers/apimManager.ts
- packages/fx-core/src/plugins/resource/apim/managers/questionManager.ts
- packages/fx-core/src/plugins/resource/apim/questions/cliQuestion.ts
- packages/fx-core/src/plugins/resource/apim/questions/vscodeQuestion.ts
- packages/fx-core/src/plugins/resource/apim/services/apimService.ts
- packages/fx-core/src/plugins/resource/apim/utils/commonUtils.ts
- packages/fx-core/src/plugins/resource/apim/utils/namingRules.ts
- packages/fx-core/src/plugins/resource/apim/v2/index.ts
- packages/fx-core/tests/plugins/resource/apim/apimService.test.ts
- packages/fx-core/tests/plugins/resource/apim/config.test.ts
- packages/fx-core/tests/plugins/resource/apim/index.test.ts
Detail: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/12962436/
> refactor(apim): remove useless code in apim plugin

- packages/fx-core/src/plugins/resource/frontend/dotnet/enum.ts
- packages/fx-core/src/plugins/resource/frontend/dotnet/ops/deploy.ts
Maybe we need such a tool to help check copyright header.
> chore(frontend): copyright header

- packages/fx-core/src/plugins/solution/fx-solution/debug/scaffolding.ts
- packages/fx-core/src/plugins/solution/fx-solution/debug/util/tasks.ts
- packages/fx-core/src/plugins/solution/fx-solution/debug/util/tasksNext.ts
- packages/fx-core/tests/plugins/solution/debug/solution.debug.scaffolding.test.ts
- packages/fx-core/tests/plugins/solution/debug/util/tasksNext.test.ts
Adjust `tasks.json` to use new workflow and task definitions.
(Since old project may still call `scaffold`, separate new tasks into `tasksNext.ts`)
> feat(local debug): use new local debug tasks

- packages/cli/src/cmds/preview/preview.ts
E2E TEST: https://github.com/OfficeDev/TeamsFx-UI-Test/blob/6c550e68ea28f5685959fd7f04a54316fbae5bc0/src/ui-test/localdebug/localdebug-function.test.ts#L7
> fix(cli preview): correct deps type

- packages/fx-core/tests/plugins/solution/debug/solution.debug.scaffolding.test.ts
Unit test logic mismatch between https://github.com/OfficeDev/TeamsFx/pull/3844 and https://github.com/OfficeDev/TeamsFx/pull/3845
> chore: fix unit test on dev branch

- packages/api/review/teamsfx-api.api.md
- packages/api/src/v3/types.ts
- packages/fx-core/src/plugins/resource/appstudio/constants.ts
- packages/fx-core/src/plugins/resource/appstudio/manifestTemplate.ts
- packages/fx-core/src/plugins/resource/appstudio/v3/index.ts
- packages/fx-core/src/plugins/solution/fx-solution/v2/executeUserTask.ts
1. Define type ManifestCapability
2. Provide different manifest template for existing tab/bot.
> refactor: existing app manifest template

- packages/vscode-extension/package.json
- packages/vscode-extension/src/debug/prerequisitesHandler.ts
- packages/vscode-extension/src/debug/teamsfxTaskHandler.ts
- add automatic npm install setting and set default value to false
- let prerequisitesHandler to wait current running npm install tasks
> chore(vsc): enable automatic npm install

- packages/fx-core/src/common/deps-checker/depsManager.ts
- packages/fx-core/tests/common/deps-checker/cases/node.it.ts
- packages/vscode-extension/src/debug/depsChecker/doctorConstant.ts
- packages/vscode-extension/src/debug/prerequisitesHandler.ts
Rollback cert part and follow xiaofu's  [PR](https://github.com/OfficeDev/TeamsFx/pull/3864)
> chore: improve doctor ui of new f5

- packages/fx-core/src/plugins/solution/fx-solution/arm.ts
activeResourcePlugins will maintained by plugin instead of solution
> chore(arm): solution not change activeResourcePlugins

- packages/vscode-extension/src/handlers.ts
To fix https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/13143216.
> chore: add auto npm install error handling for adding resource/cap

- packages/fx-core/src/plugins/resource/frontend/v2/index.ts
E2E TEST: Will add e2e test later
> fix(vs): activate frontend plugin in VS

- packages/fx-core/src/plugins/solution/fx-solution/v2/deploy.ts
- packages/fx-core/src/plugins/solution/fx-solution/v2/getQuestions.ts
- packages/fx-core/tests/plugins/solution/solution.deploy.test.ts
Related task: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_sprints/taskboard/Teams%20Extensibility%20E2E%20Team/Microsoft%20Teams%20Extensibility/CY22-2.1?workitem=13249401
E2E TEST: not available.
> feat(solution): do not let users select plugins to to deploy on VS

- packages/fx-core/src/common/local/localEnvProvider.ts
Fix case-sensitive issue on Linux/MacOS.
> fix(local debug): fix port env case

- packages/fx-core/src/common/local/localCertificateManager.ts
> chore(localdebug): change cert cancel message

- packages/fx-core/src/common/deps-checker/internal/dotnetChecker.ts
- packages/fx-core/src/common/deps-checker/internal/ngrokChecker.ts
- packages/vscode-extension/src/debug/depsChecker/doctorConstant.ts
- packages/vscode-extension/src/debug/prerequisitesHandler.ts
> chore: improve doctor ui

- packages/fx-core/.gitignore
- packages/fx-core/templates/plugins/resource/webapp/bicep/webappConfiguration.template.bicep
- packages/fx-core/tests/plugins/resource/dotnet/unit/arm.test.ts
> fix(dotnet): remove configs of simple auth

- packages/fx-core/src/core/index.ts
add a new interface to avoid existing functions' middleware, like project setting loader.
> refactor: add interface to core to provision teams app with user provided app package

- templates/tab/js/default/src/components/sample/AzureFunctions.jsx
- templates/tab/ts/default/src/components/sample/AzureFunctions.tsx
> fix(template): hint to authorize before calling function

- packages/fx-core/src/common/local/taskDefinition.ts
Fix https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/13321911/
> fix: fix potential ngrok start error on windows git bash

- packages/vscode-extension/src/debug/teamsfxTaskHandler.ts
Do not show npm install error message for prerequite check and auto npm install
> chore(localdebug): do not show npm install error message for prerequite check and auto npm install

- packages/vscode-extension/src/debug/prerequisitesHandler.ts
End the progress of nodejs according to deps type
Do not fast fail the deps checker
> chore(localdebug): end the progress of nodejs and not fast fail the deps checker

- packages/vscode-extension/package.json
- packages/vscode-extension/src/extension.ts
- packages/vscode-extension/src/handlers.ts
- packages/vscode-extension/src/utils/commonUtils.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/13133622
> chore(vsc): auto open walkthrough

- packages/vscode-extension/src/controls/webviewPanel.ts
E2E TEST: https://github.com/OfficeDev/TeamsFx/blob/38f0986eb6e7f646011001d7aac5c019b91618f0/packages/vscode-extension/test/unit/extension/handlers.test.ts#L91
> fix: apply telemetry lost fix to download sample

- packages/vscode-extension/src/debug/depsChecker/doctorConstant.ts
- packages/vscode-extension/src/debug/prerequisitesHandler.ts
> chore(localdebug): change prerequisite log / progress message

- docs/fx-core/bot-help.md
- docs/fx-core/config.md
bot-help.md and config.md are out of date for the bot part, so update them.
1. remove useless section in bot-help.md since it's repeated in config.md.
2. remove out of date fields in config.md and add new ones.
to finish https://dev.azure.com/msazure/Microsoft%20Teams%20Extensibility/_workitems/edit/13234893
> chore: update bot schema

- packages/vscode-extension/package.json
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/13371130
> chore: remove sign in in walk through

- packages/fx-core/src/plugins/solution/fx-solution/debug/scaffolding.ts
- packages/fx-core/src/plugins/solution/fx-solution/debug/util/launchNext.ts
- packages/fx-core/src/plugins/solution/fx-solution/debug/util/tasksNext.ts
- packages/fx-core/tests/plugins/solution/debug/solution.debug.scaffolding.test.ts
- packages/fx-core/tests/plugins/solution/debug/util/tasksNext.test.ts
- packages/vscode-extension/package.json
- remove launch configuration preLaunchTask: Start Frontend/Backend/Bot
- move Start Frontend/Backend/Bot to compound preLaunchTask
- update the endsPattern of bot problem matcher and show the bot problem
matcher details in tasks.json
- update corresponding unit tests
To fix https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/13134061
> chore(localdebug): remove launch configuration preLaunchTask

- packages/api/src/error.ts
- packages/fx-core/src/core/error.ts
- packages/sdk/README.md
- packages/vscode-extension/package.json
command strings, `teamsfx toolkit` typos
> fix: strings

- .github/scripts/template-zip-autogen.sh
- .github/workflows/cd.yml
This pr revert https://github.com/OfficeDev/TeamsFx/pull/3933
> chore(cd): revert generate zip to temporary folder in cd

- templates/tab/js/default/public/auth-end.html
- templates/tab/ts/default/public/auth-end.html
Fix bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/13352125?src=WorkItemMention&src-action=artifact_link
> perf(template): update tab template

- templates/tab/js/default/package.json
- templates/tab/ts/default/package.json
Fix: https://github.com/OfficeDev/TeamsFx/issues/3929
E2E TEST: https://github.com/OfficeDev/TeamsFx/blob/18b21fa3a87246067e07f9761899954c29555477/packages/cli/tests/e2e/frontend/TestCreateTab.tests.ts#L36
> fix(tab): react app hangs after hot reload

- packages/vscode-extension/src/handlers.ts
- packages/vscode-extension/src/resources/Strings.json
ADO: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/13142681
E2E TEST: only update wording
> fix: refine view state file error

- packages/vscode-extension/src/debug/teamsfxTaskProvider.ts
> fix(localdebug): change backend problem watcher

- packages/fx-core/src/plugins/solution/fx-solution/debug/util/launch.ts
- packages/fx-core/src/plugins/solution/fx-solution/debug/util/launchNext.ts
- packages/fx-core/src/plugins/solution/fx-solution/debug/util/tasks.ts
- packages/fx-core/src/plugins/solution/fx-solution/debug/util/tasksNext.ts
- packages/fx-core/tests/plugins/solution/debug/util/tasksNext.test.ts
- refactor lanuch(Next).ts for better maintenance
- remove cascadeTerminateToConfigurations in launch configurations
because stopAll in compound is enough
- add backend launch configuration and task when adding function resource
To fix https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/13370300/
> fix(localdebug): allow local debug for bot+backend project

- packages/vscode-extension/src/qm/vsc_ui.ts
- packages/vscode-extension/src/resources/Strings.json
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/13354035
> docs(vsc): remove description

- packages/fx-core/src/plugins/resource/spfx/index.ts
- packages/fx-core/src/plugins/resource/spfx/utils/constants.ts
- packages/fx-core/src/plugins/resource/spfx/utils/progress-helper.ts
- packages/fx-core/src/plugins/resource/spfx/utils/questions.ts
- packages/fx-core/src/plugins/resource/spfx/v3/error.ts
- packages/fx-core/src/plugins/resource/spfx/v3/index.ts
- packages/fx-core/src/plugins/resource/spfx/v3/plugin.ts
- packages/fx-core/tests/plugins/resource/spfx/helper.ts
- packages/fx-core/tests/plugins/resource/spfx/unit/v2lifecycle.test.ts
- packages/fx-core/tests/plugins/resource/spfx/unit/v3.test.ts
E2E TEST: https://github.com/OfficeDev/TeamsFx/blob/dev/packages/cli/tests/e2e/spfx/CreateSPFxProject.tests.ts
> refactor: spfx plugin v3

- packages/vscode-extension/package.json
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/13410027
> chore(vsc): update the minimum version of vsc

- packages/fx-core/src/plugins/solution/fx-solution/v2/scaffolding.ts
- packages/fx-core/src/plugins/solution/fx-solution/v2/utils.ts
> fix(dotnet): remove create readme logic in solution for dotnet project

- packages/vscode-extension/src/userInput.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/13298133
> chore(vsc): add open folder comment

- packages/vscode-extension/package.json
- packages/vscode-extension/src/debug/depsChecker/doctorConstant.ts
- packages/vscode-extension/src/debug/prerequisitesHandler.ts
Detail: [Bug 13440785](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/13440785): [Sample][Faq-plus] local debug -[Error]-code:Solution.InvalidLocalBotEndpointFormat
> chore(localdebug): change ngrok settings wording

- packages/cli/src/cmds/preview/constants.ts
- packages/cli/src/cmds/preview/preview.ts
- packages/cli/src/cmds/preview/task.ts
- use dev:teamsfx script in package.json to start services
> chore(cli-preview): use dev:teamsfx to start services

- packages/vscode-extension/package.json
- packages/vscode-extension/src/extension.ts
- packages/vscode-extension/src/handlers.ts
- packages/vscode-extension/src/utils/commonUtils.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/13371055
vsc 1.64.2 
vsc 1.65.0-insider
> chore(vsc): detect if vs code support walk through

- packages/fx-core/src/plugins/resource/bot/index.ts
- packages/fx-core/src/plugins/resource/frontend/index.ts
- packages/fx-core/src/plugins/solution/fx-solution/debug/scaffolding.ts
- packages/fx-core/src/plugins/solution/fx-solution/v2/scaffolding.ts
- packages/fx-core/src/plugins/solution/fx-solution/v2/utils.ts
- packages/fx-core/tests/plugins/resource/bot/unit/generateArmTemplates.test.ts
- packages/fx-core/tests/plugins/resource/dotnet/unit/arm.test.ts
- packages/fx-core/tests/plugins/resource/dotnet/unit/deploy.test.ts
- templates/blazor-base/csharp/default/Properties/launchSettings.json
> fix(dotnet): add local settings when project is dotnet

- packages/fx-core/src/plugins/resource/aad/index.ts
- packages/fx-core/src/plugins/resource/identity/index.ts
remove migrate v1 in aad plugin and identity plugin
> refactor: remove migrate v1 in aad plugin and identity plugin

- packages/fx-core/src/plugins/resource/apim/managers/questionManager.ts
Detail: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/13468454
> fix(apim): add condition to cli deploy question

- packages/cli/src/cmds/new.ts
- packages/cli/src/telemetry/cliTelemetryEvents.ts
chore: add new-project-id property for CLI
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/13475000
> chore: add new-project-id property for CLI

- packages/fx-core/src/plugins/resource/bot/constants.ts
- packages/fx-core/src/plugins/resource/bot/dotnet/plugin.ts
- packages/fx-core/src/plugins/resource/bot/errors.ts
- packages/fx-core/src/plugins/resource/bot/index.ts
- packages/fx-core/src/plugins/resource/bot/interface.ts
- packages/fx-core/src/plugins/resource/bot/plugin.ts
- packages/fx-core/src/plugins/resource/bot/resources/messages.ts
- packages/fx-core/src/plugins/resource/bot/resources/strings.ts
Remove migrate v1 in bot plugin
> refactor(bot): remove migrate v1 in bot plugin

- packages/fx-core/src/plugins/resource/appstudio/appStudio.ts
- packages/fx-core/src/plugins/resource/appstudio/utils/telemetry.ts
1) fix published teams app id
2) add tenant id for app studio telemetry
> chore: app studio telemetry

- packages/vscode-extension/package.json
- packages/vscode-extension/src/handlers.ts
- packages/vscode-extension/src/resources/Strings.json
ADO: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/13468718
teamsfx project:
non-teamsfx project:
> chore(vsc): show notification if open readme in non-teamfx project

- packages/fx-core/tests/plugins/resource/apim/questionManager.test.ts
add test case for apim question
> test(apim): add test case for apim question

- packages/vscode-extension/package.json
- packages/vscode-extension/src/debug/prerequisitesHandler.ts
- packages/vscode-extension/src/debug/teamsfxTaskHandler.ts
- packages/vscode-extension/src/handlers.ts
- block debugging if there is already a debugging session
- terminate teamsfx tasks before validating local prerequisites
> chore(localdebug): improve local debug experience

- packages/fx-core/src/plugins/solution/fx-solution/commonQuestions.ts
- packages/fx-core/src/plugins/solution/fx-solution/solution.ts
- packages/fx-core/src/plugins/solution/fx-solution/v2/deploy.ts
- packages/fx-core/src/plugins/solution/fx-solution/v2/provision.ts
- packages/fx-core/tests/plugins/solution/solution.deploy.test.ts
Fixes bug https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_sprints/taskboard/Teams%20Extensibility%20E2E%20Team/Microsoft%20Teams%20Extensibility/CY22-2.2?workitem=13441379
E2E TEST: not needed.
> fix(solution): add m365 and azure account checking in v2 deploy

- packages/fx-core/src/core/index.ts
Closes https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_sprints/taskboard/Teams%20Extensibility%20E2E%20Team/Microsoft%20Teams%20Extensibility/CY22-2.2?workitem=13505778
> chore(core): add appsettings.Development.json to gitignore on VS

- packages/fx-core/src/plugins/resource/bot/dotnet/plugin.ts
- packages/fx-core/src/plugins/resource/frontend/constants.ts
- packages/fx-core/src/plugins/resource/frontend/dotnet/constants.ts
- packages/fx-core/src/plugins/resource/frontend/dotnet/plugin.ts
- packages/fx-core/src/plugins/resource/frontend/index.ts
- packages/fx-core/src/plugins/resource/frontend/interface.ts
- packages/fx-core/src/plugins/resource/frontend/plugin.ts
- packages/fx-core/src/plugins/resource/frontend/v2/index.ts
- packages/fx-core/src/plugins/solution/fx-solution/debug/provisionLocal.ts
- packages/fx-core/tests/plugins/resource/dotnet/unit/localDebug.test.ts
E2E TEST: cli does not support DotNet scenario yet.
When trigger local debug in VS platform, setup local setting and update appsetting.development.json file in .NET project.
> feat(dotnet): support local debug for DotNet

- packages/fx-core/src/plugins/resource/frontend/dotnet/constants.ts
- packages/fx-core/src/plugins/resource/frontend/dotnet/plugin.ts
- packages/fx-core/src/plugins/resource/frontend/dotnet/resources/errors.ts
- packages/fx-core/tests/plugins/resource/dotnet/unit/localDebug.test.ts
E2E TEST: cli does not support dotnet scenario yet.
Fix some comments from https://github.com/OfficeDev/TeamsFx/pull/4011
> refactor(dotnet): refactor on dotnet plugin local debug

- packages/fx-core/src/common/localSettingsProvider.ts
- packages/fx-core/src/core/middleware/localSettingsLoader.ts
- packages/fx-core/src/plugins/solution/fx-solution/debug/provisionLocal.ts
- packages/fx-core/tests/plugins/solution/debug/solution.debug.provisionLocal.test.ts
fix bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_sprints/taskboard/AuthAndData/Microsoft%20Teams%20Extensibility/CY22-2.2?workitem=13523054
> fix(aad): add aad object when loading local settings

- packages/fx-core/src/core/middleware/projectMigrator.ts
Fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/13468124
> fix(migrate): move write file outof config

- packages/vscode-extension/package.json
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/13133620
> chore: integrate with prerequiest checker

- packages/fx-core/package-lock.json
- packages/fx-core/package.json
- packages/fx-core/src/plugins/solution/fx-solution/debug/scaffolding.ts
- packages/fx-core/tests/plugins/solution/debug/solution.debug.scaffolding.test.ts
- packages/vscode-extension/src/debug/npmInstallHandler.ts
> refactor(localdebug): remove useless script insallAll

- packages/fx-core/src/core/middleware/projectMigrator.ts
> fix: migrate provision with identity

- packages/vscode-extension/package.json
- packages/vscode-extension/src/envTree.ts
For the minimized teamsfx project (no solution settings), update the local debug button in env tree with the preview button.
> chore(env-tree): support local preview for minimized app in env tree

- packages/vscode-extension/package.json
- packages/vscode-extension/src/extension.ts
- packages/vscode-extension/src/handlers.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/13698981
> chore: update open deployment command

- packages/vscode-extension/package.json
- packages/vscode-extension/src/extension.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/13700079
> chore: merge create project command

- packages/fx-core/src/core/FxCore.ts
- packages/fx-core/src/plugins/resource/utils4v2.ts
1. Add ```isLocalDebug``` for manifest merge.
> chore: add is localDebug flag

- packages/cli/src/cmds/preview/preview.ts
To fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/13700941
> fix(cli-preview): fix backend start task missing env

- packages/fx-core/src/plugins/resource/appstudio/manifestTemplate.ts
- packages/fx-core/tests/plugins/resource/appstudio/unit/build.test.ts
- packages/fx-core/tests/plugins/resource/appstudio/unit/validate.test.ts
valiate/build should not call appstudio api.
> chore: add ut for 13071386 and 13487561

- packages/fx-core/src/plugins/resource/sql/plugin.ts
fix bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/13699168
> fix(sql): fix db count error

- packages/server/package-lock.json
- packages/server/package.json
- packages/server/src/providers/token/azure.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/13523043
E2E TEST: no need.
> fix: cannot webpack server if use the package dependency

- packages/vscode-extension/package.json
- packages/vscode-extension/src/extension.ts
- packages/vscode-extension/src/handlers.ts
- packages/vscode-extension/src/telemetry/extTelemetryEvents.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/13699837
> chore: add walk through telemetry

- packages/fx-core/src/core/middleware/envInfoLoader.ts
- packages/fx-core/src/plugins/resource/utils4v2.ts
1. Add local environment for old projects.
2. Fix non envInfo problem.
> chore: add local env for old projects

- packages/fx-core/src/core/FxCore.ts
1. Update ```.gitignore``` file for local debug files.
> chore: add gitignore for local configs

- packages/fx-core/src/plugins/resource/appstudio/index.ts
- packages/vscode-extension/src/handlers.ts
validate manifest command: select local/remote env
> refactor: validate local manifest

- packages/vscode-extension/src/handlers.ts
> refactor: edit manifest template

- packages/fx-core/src/common/constants.ts
- packages/fx-core/src/core/globalVars.ts
- packages/fx-core/src/plugins/resource/spfx/plugin.ts
- packages/fx-core/src/plugins/resource/spfx/utils/questions.ts
- packages/fx-core/src/plugins/resource/spfx/utils/utils.ts
- packages/fx-core/src/plugins/solution/fx-solution/debug/util/launch.ts
E2E TEST: only affect vsc extension
> feat: remove local workbench for spfx

- packages/vscode-extension/src/handlers.ts
> chore: update manifest preview file codelens for unified template

- packages/fx-core/src/common/constants.ts
- packages/fx-core/src/common/tools.ts
Detail: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/13762945
> chore(notification): add notification feature flag

- packages/vscode-extension/media/ok.svg
- packages/vscode-extension/src/qm/vsc_ui.ts
checkmark is duplicated and should be removed.
Multi-select:
Single-select:
Input:
Related work item: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/13655460/
> chore(vsc): remove checkmark on QuickPick

- packages/vscode-extension/scripts/vsce_locally.ts
Remove `env` parameter and use `process.env` instead.
> chore(vsc): fix env issue of vsce locally script on windows

- packages/fx-core/src/plugins/resource/bot/constants.ts
- packages/fx-core/src/plugins/resource/bot/utils/telemetry-helper.ts
Detail: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/13776534
> chore(bot):  Ensure bot related event have property 'bot-host-type'

- packages/cli/tests/commonlib/sqlValidator.ts
- packages/fx-core/src/plugins/resource/sql/sqlClient.ts
- packages/sdk/test/e2e/node/sqlConnector.spec.ts
> fix: adaptation tedious v14

- packages/fx-core/tests/plugins/resource/appstudio/unit/publish.test.ts
Test case for https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/12941918
> test: add a unit test for bug 12941918

- packages/fx-core/src/plugins/solution/fx-solution/v2/provision.ts
> fix: provision success notice for existing app

- templates/bot/ts/notification-function-base/.funcignore
- templates/bot/ts/notification-function-base/.gitignore
- templates/bot/ts/notification-function-base/host.json
- templates/bot/ts/notification-function-base/local.settings.json
- templates/bot/ts/notification-function-base/package.json
- templates/bot/ts/notification-function-base/src/adaptiveCardBuider.ts
- templates/bot/ts/notification-function-base/src/adaptiveCards/notification-default.json
- templates/bot/ts/notification-function-base/src/httpTrigger.ts
- templates/bot/ts/notification-function-base/src/internal/initialize.ts
- templates/bot/ts/notification-function-base/src/internal/messageHandler.ts
- templates/bot/ts/notification-function-base/src/sdk/context.ts
- templates/bot/ts/notification-function-base/src/sdk/fileStorage.ts
- templates/bot/ts/notification-function-base/src/sdk/middleware.ts
- templates/bot/ts/notification-function-base/src/sdk/notification.ts
- templates/bot/ts/notification-function-base/src/sdk/store.ts
- templates/bot/ts/notification-function-base/src/timerTrigger.ts
- templates/bot/ts/notification-function-base/tsconfig.json
add function base template (without trigger files)
template source code is based on dev branch of this repo: https://github.com/qinezh/mybotapp/tree/dev
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/13776366/
> feat: add bot notification base template of function hosted trigger

- packages/cli/src/cmds/preview/depsChecker/cliChecker.ts
- packages/cli/src/cmds/preview/preview.ts
- packages/fx-core/src/common/local/constants.ts
- packages/fx-core/src/common/local/localEnvManager.ts
- packages/fx-core/src/common/local/projectSettingsHelper.ts
- packages/fx-core/tests/common/local/localEnvManager.test.ts
- packages/vscode-extension/src/debug/depsChecker/vscodeChecker.ts
- packages/vscode-extension/test/unit/localdebug/depsChecker.test.ts
Detail: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/13776371
> feat(deps-checker): check func core tool for function hosted bot

- packages/cli/src/cmds/init.ts
- packages/cli/src/telemetry/cliTelemetryEvents.ts
- packages/cli/tests/unit/cmds/init.tests.ts
- packages/fx-core/src/core/FxCore.ts
- packages/fx-core/src/core/middleware/questionModel.ts
related PR: https://github.com/OfficeDev/TeamsFx/pull/4175, https://github.com/OfficeDev/TeamsFx/pull/4179/
work item: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/13725446/
Please note, the output message after running this command will be added in another separated PR.
> chore(cli): implement the init command

- packages/cli/tests/e2e/manifest/addCapability.tests.ts
- packages/fx-core/src/plugins/resource/appstudio/manifestTemplate.ts
E2E TEST: addCapability.tests.ts
E2E TEST pass: https://github.com/OfficeDev/TeamsFx/actions/runs/1968011155
> fix: local manifest template not updated after add capability 

- packages/fx-core/resource/package.nls.json
- packages/fx-core/src/core/FxCore.ts
> chore: add output info for init command

- packages/fx-core/src/plugins/resource/appstudio/plugin.ts
- add localhost:port to local manifest valid domains to support m365 apps
> chore(local-debug): add localhost:port to manifest valid domains

- packages/fx-core/resource/package.nls.json
- packages/fx-core/src/common/constants.ts
- packages/fx-core/src/core/error.ts
- packages/fx-core/src/plugins/solution/fx-solution/v2/getQuestions.ts
Add help link (placeholder) and update the error message when:
* try to deploy a minimal app.
* try to add resources for a minimal app.
> chore: update error message for mini app

- packages/fx-core/src/plugins/solution/fx-solution/debug/scaffolding.ts
- packages/fx-core/src/plugins/solution/fx-solution/debug/util/tasksNext.ts
- packages/fx-core/tests/plugins/solution/debug/util/tasksNext.test.ts
- packages/vscode-extension/src/debug/teamsfxTaskHandler.ts
- templates/bot/ts/notification-function-base/package.json
Detail: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/13776382/
> feat(bot): support localdebug for func hosted bot

- packages/vscode-extension/src/debug/commonUtils.ts
- packages/vscode-extension/src/debug/prerequisitesHandler.ts
- packages/vscode-extension/src/handlers.ts
- packages/vscode-extension/src/telemetry/extTelemetryEvents.ts
add project components to debug-envcheck-start and debug-prerequisites-start
> chore(localdebug): improve local debug telemetry

- packages/fx-core/src/core/question.ts
- packages/fx-core/tests/core/question.test.ts
Add validation logic to the capability question
https://user-images.githubusercontent.com/9698542/158328323-b1a8c844-c7ce-41f6-80b1-2a07c8795088.mp4
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/13777227/
> chore: add validation logic to capability question

- packages/fx-core/templates/plugins/resource/cicd/azdo/README.md
- packages/fx-core/templates/plugins/resource/cicd/github/README.md
- packages/fx-core/templates/plugins/resource/cicd/jenkins/README.md
- packages/vscode-extension/package.json
to finish https://dev.azure.com/msazure/Microsoft%20Teams%20Extensibility/_workitems/edit/13838883
> chore: polish cicd scaffold readmes

- packages/vscode-extension/src/handlers.ts
Need to showError(), rather than only returning it.
> fix: need to show error

- packages/vscode-extension/package.json
> fix(vsc): env view shows if no project opened

- packages/cli/src/cmds/preview/preview.ts
Support local preview for minimal app by CLI:
* register Teams app with `core.localDebug`.
* no need to check dependency as there's no app code.
* launch the browser.
> chore(cli): support local preview for minimal app

- packages/fx-core/src/plugins/resource/bot/constants.ts
- packages/fx-core/src/plugins/resource/bot/functionsHostedBot/plugin.ts
- packages/fx-core/src/plugins/resource/bot/plugin.ts
- packages/fx-core/templates/plugins/resource/bot/bicep/funcHostedBotProvision.template.bicep
- packages/fx-core/tests/plugins/resource/bot/unit/expectedBicepFiles/botProvision.result.bicep
- packages/fx-core/tests/plugins/resource/bot/unit/expectedBicepFiles/botProvisionOfFuncHosted.result.bicep
- packages/fx-core/tests/plugins/resource/bot/unit/expectedBicepFiles/provisionOfFuncHosted.result.bicep
- packages/fx-core/tests/plugins/resource/bot/unit/generateArmTemplates.test.ts
Detail: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/13776394/
> feat(bot): provision func hosted bot

- packages/fx-core/src/plugins/solution/fx-solution/debug/constants.ts
- packages/fx-core/src/plugins/solution/fx-solution/debug/util/launchNext.ts
- packages/fx-core/tests/plugins/solution/debug/solution.debug.scaffolding.test.ts
- packages/vscode-extension/src/debug/teamsfxDebugProvider.ts
- add launch remote configurations for m365
- update m365 launch url
- let tenant in account-hint only applies for teams
> chore(m365): add launch remote configurations for m365 

- packages/fx-core/src/common/globalState.ts
- packages/fx-core/tests/common/globalState.test.ts
- packages/vscode-extension/src/controls/openWelcomePage.ts
- packages/vscode-extension/src/controls/webviewPanel.ts
- packages/vscode-extension/src/debug/npmInstallHandler.ts
- packages/vscode-extension/src/handlers.ts
- packages/vscode-extension/src/utils/survey.ts
ADO:
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/13862621
E2E TEST: not 100% reproducible
> fix: invalid state file when create spfx project

- packages/vscode-extension/src/debug/prerequisitesHandler.ts
Fix [bug](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/13880216)
> chore: remove account check from walk through

- packages/fx-core/resource/package.nls.json
- packages/fx-core/src/plugins/resource/appstudio/plugin.ts
> refactor: add progress for provision

- packages/adaptivecards-tools-sdk/package-lock.json
- packages/api/package-lock.json
- packages/cli/package-lock.json
- packages/failpoint-ts/package-lock.json
- packages/fx-core/package-lock.json
- packages/manifest/package-lock.json
- packages/sdk-react/package-lock.json
- packages/sdk/package-lock.json
- packages/server/package-lock.json
- packages/vscode-extension/package-lock.json
- templates/package-lock.json
commit after run `npx lerna-audit`
> chore: fix vulnerabilities

- packages/cli/src/cmds/new.ts
- packages/cli/src/constants.ts
- packages/cli/src/helpParamGenerator.ts
- packages/cli/src/telemetry/cliTelemetryEvents.ts
- packages/cli/tests/unit/cmds/new.tests.ts
- add teamsfx new m365 command if m365 feature flag enabled
> feat(m365): add teamsfx new m365 command

- packages/vscode-extension/src/envTree.ts
> fix(env-tree): incorrect condition to expand env tree

- packages/fx-core/src/core/FxCore.ts
- packages/fx-core/src/core/middleware/envInfoLoader.ts
- packages/fx-core/src/core/middleware/envInfoWriter.ts
- packages/vscode-extension/package.json
- packages/vscode-extension/src/constants.ts
- packages/vscode-extension/src/utils/commonUtils.ts
> chore(vsc): add extension settings for experimental features flags

- packages/cli/tests/e2e/commonUtils.ts
- packages/cli/tests/e2e/multienv/TestRemoteHappyPath.tests.ts
- packages/cli/tests/e2e/multienv/TestRemoteHappyPathSPFx.tests.ts
1. Will enable publish when 12615502 resolved or new tenant configured.
2. fix SPFx e2e test (user data not exist)
> chore: temporarily disable publish

- packages/fx-core/src/plugins/resource/spfx/error.ts
- packages/vscode-extension/package.nls.json
- packages/vscode-extension/src/commonlib/appStudioLogin.ts
- packages/vscode-extension/src/commonlib/azureLogin.ts
- packages/vscode-extension/src/commonlib/codeFlowLogin.ts
- packages/vscode-extension/src/commonlib/graphLogin.ts
- packages/vscode-extension/src/commonlib/sharepointLogin.ts
- packages/vscode-extension/src/debug/prerequisitesHandler.ts
- packages/vscode-extension/src/debug/runIconHandler.ts
- packages/vscode-extension/src/extension.ts
- packages/vscode-extension/src/handlers.ts
- packages/vscode-extension/src/qm/vsc_ui.ts
- packages/vscode-extension/src/utils/localizeUtils.ts
- packages/vscode-extension/src/utils/survey.ts
Partial fix of https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/13863083
> refactor: update errors to get default string for telemetry

- packages/vscode-extension/src/handlers.ts
ADO: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/13900320
E2E TEST: will add UT later
> fix: add back projectId property for create-project event

- packages/fx-core/src/plugins/resource/spfx/depsChecker/generatorChecker.ts
- packages/fx-core/src/plugins/resource/spfx/plugin.ts
- packages/fx-core/src/plugins/resource/spfx/utils/telemetryEvents.ts
1. add sharepoint yeoman generator checker
2. use yeoman cli for scafffolding
> feat: add sharepoint generator checker and use yeoman for scaffolding

- packages/vscode-extension/src/commonlib/graphLogin.ts
- packages/vscode-extension/src/debug/teamsAppInstallation.ts
- packages/vscode-extension/src/debug/teamsfxDebugProvider.ts
- packages/vscode-extension/src/handlers.ts
- prompt window to let user install app in Teams for launching remote in
Outlook/Office
- add retrying logic for calling graph api to get internal id
- reload cache in graph getStatus
> chore(m365): prompt window to install app for remote

- packages/fx-core/src/plugins/resource/aad/constants.ts
- packages/fx-core/src/plugins/resource/aad/index.ts
- packages/fx-core/src/plugins/resource/aad/plugin.ts
- packages/fx-core/src/plugins/resource/aad/v2/index.ts
- packages/fx-core/tests/plugins/resource/aad/helper.ts
- packages/fx-core/tests/plugins/resource/aad/unit/index.test.ts
Add scaffold functon in aad plugin:
1. Add aad.template.json file to templates/appPackage/aad.template.json
> perf(aad-manifest): support scaffold aad manifest

- packages/vscode-extension/package.json
- packages/vscode-extension/package.nls.json
- packages/vscode-extension/src/extension.ts
- packages/vscode-extension/src/handlers.ts
- packages/vscode-extension/src/telemetry/extTelemetryEvents.ts
Add 'add sso' command in command palette, will trigger 'add sso' in fx-core
> perf(extension): add 'add sso' command

- packages/fx-core/templates/core/README-auto-generated.md
Preview: https://github.com/OfficeDev/TeamsFx/blob/qinezh/readme/packages/fx-core/templates/core/README-auto-generated.md
> docs: add README for init command

- packages/fx-core/src/core/FxCore.ts
- packages/fx-core/src/plugins/solution/fx-solution/v2/executeUserTask.ts
1. keep idempotency of .gitignore file update
2. reset provision state after add capability/resource
> chore(core): idempotency of .gitignore file update

- packages/fx-core/templates/plugins/resource/sql/bicep/sqlProvision.template.bicep
- packages/fx-core/tests/plugins/resource/sql/unit/expectedBicepFiles/sqlProvision.result.bicep
add tls 1.2 limitation in sql template
> chore(sql): add tls limitation in template

- templates/tab/csharp/default/wwwroot/js/TeamsJsBlazorInterop.js
> chore(blazor-template): fix inTeams check function

- packages/fx-core/src/plugins/resource/appstudio/constants.ts
- packages/fx-core/src/plugins/resource/appstudio/plugin.ts
- packages/fx-core/tests/plugins/resource/appstudio/unit/scaffold.test.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/13206351
> chore: scaffold command and response bot manifest

- packages/fx-core/resource/package.nls.json
- packages/fx-core/src/plugins/resource/bot/azureOps.ts
- packages/fx-core/src/plugins/resource/bot/constants.ts
- packages/fx-core/src/plugins/resource/bot/errors.ts
- packages/fx-core/src/plugins/resource/bot/functionsHostedBot/constants.ts
- packages/fx-core/src/plugins/resource/bot/functionsHostedBot/deployMgr.ts
- packages/fx-core/src/plugins/resource/bot/functionsHostedBot/plugin.ts
- packages/fx-core/src/plugins/resource/bot/plugin.ts
- packages/fx-core/src/plugins/resource/bot/resources/messages.ts
- packages/fx-core/tests/plugins/resource/bot/unit/funcHostedDeployMgr.test.ts
- packages/fx-core/tests/plugins/resource/bot/unit/index.test.ts
Detail: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/13776517/
> feat(bot): deploy func hosted bot

- packages/fx-core/src/plugins/resource/bot/constants.ts
- packages/fx-core/src/plugins/resource/bot/utils/telemetry-helper.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/13908646/
> chore: send bot-capabilites in telemetry

- packages/fx-core/src/plugins/resource/aad/constants.ts
- packages/fx-core/src/plugins/resource/aad/index.ts
- packages/fx-core/src/plugins/resource/aad/plugin.ts
- packages/fx-core/src/plugins/resource/aad/v2/index.ts
- packages/fx-core/src/plugins/solution/fx-solution/v2/getQuestions.ts
- packages/fx-core/tests/plugins/solution/solution.getQuestions.test.ts
> perf(aad-manifest): add aad item in drop down list when deploy

- packages/vscode-extension/src/handlers.ts
Refresh env tree automatically after new capabilities added.
> chore(env-tree): refresh env tree after capabilities added

- packages/vscode-extension/package.json
- packages/vscode-extension/src/constants.ts
- packages/vscode-extension/src/utils/commonUtils.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/13929911
> chore: add notification command response bot vsc settings

- templates/package.json
> fix: fix missing command and response template

- packages/fx-core/src/common/local/localEnvManager.ts
- packages/fx-core/src/common/local/localStateHelper.ts
- packages/fx-core/src/common/localStateConstants.ts
- packages/fx-core/src/common/localStateProvider.ts
- packages/fx-core/src/plugins/resource/localdebug/v2/index.ts
- packages/fx-core/src/plugins/resource/simpleauth/plugin.ts
- packages/fx-core/src/plugins/resource/simpleauth/v2/index.ts
- packages/fx-core/src/plugins/solution/fx-solution/debug/provisionLocal.ts
- packages/fx-core/tests/common/local/localStateHelper.test.ts
- packages/vscode-extension/src/debug/teamsfxTaskProvider.ts
1.Support ```simpleAuth``` for consolidate project.
2.Add task provider read local environment feature.
> chore: add support simpleAuth for consolidate

- packages/fx-core/src/plugins/solution/fx-solution/debug/scaffolding.ts
- packages/fx-core/src/plugins/solution/fx-solution/debug/util/settings.ts
- packages/fx-core/tests/plugins/solution/debug/solution.debug.scaffolding.test.ts
> fix: also generate .vscode/settings.json for func hosted bot

- packages/cli/src/cmds/preview/preview.ts
> fix(cli-m365): fix typo

- packages/api/src/qm/question.ts
- packages/api/tests/qm.visitor.test.ts
- packages/fx-core/src/core/middleware/questionModel.ts
- packages/fx-core/src/plugins/solution/fx-solution/v2/getQuestions.ts
- fix a bug which was worked around in solution (should not skip getQuestionsForScaffolding for command bot)
- fix qm condition overwritten issue
> fix: condition overwitten in solution/bot plugin

- packages/vscode-extension/package.json
- packages/vscode-extension/src/treeview/treeViewManager.ts
Remove the feature flag for tamsfx init support, as well as the entry points for teamsfx init.
> chore(init): remove the feature flag for teamsfx init

- templates/bot/ts/notification-function-base/.funcignore
Update the .funcignore file to avoid deploy development folder into Azure
> chore(bot): update .funcignore for func hosted bot

- packages/vscode-extension/package.json
- packages/vscode-extension/src/utils/commonUtils.ts
This reverts commit d8a246ed32d9345a60679817f2159c8a1d0ac0ea.
Add back settings because rc release is postponed
> revert: revert: chore: add notification command response bot vsc settings

- packages/cli/src/cmds/deploy.ts
- packages/cli/src/cmds/index.ts
- packages/cli/src/cmds/manifest.ts
- packages/cli/tests/e2e/multienv/TestRemoteHappyPath.tests.ts
- packages/cli/tests/unit/cmds/deploy.tests.ts
- packages/cli/tests/unit/cmds/index.tests.ts
- packages/cli/tests/unit/cmds/manifest.tests.ts
- packages/cli/tests/unit/cmds/provision.tests.ts
- packages/cli/tests/unit/utils.tests.ts
- packages/fx-core/src/plugins/resource/appstudio/constants.ts
- packages/fx-core/src/plugins/resource/appstudio/index.ts
- packages/fx-core/src/plugins/resource/appstudio/plugin.ts
- packages/fx-core/src/plugins/resource/appstudio/utils/telemetry.ts
- packages/fx-core/src/plugins/resource/appstudio/v2/index.ts
Reverts OfficeDev/TeamsFx#4200
> chore: Revert "feat(cli): change `teamsfx manifest update` to `teamsfx deploy manifest`"

- templates/bot/js/notification-restify/.gitignore
- templates/bot/js/notification-restify/package.json
- templates/bot/js/notification-restify/src/adaptiveCard.js
- templates/bot/js/notification-restify/src/adaptiveCards/notification-default.json
- templates/bot/js/notification-restify/src/index.js
- templates/bot/js/notification-restify/src/internal/initialize.js
- templates/bot/js/notification-restify/src/internal/server.js
- templates/bot/ts/notification-restify/package.json
tested locally
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/13791043
> chore: add js restify notification template

- packages/cli/src/cmds/preview/preview.ts
> fix: fix cli preview for non-m365 app

- packages/fx-core/resource/package.nls.json
- packages/fx-core/src/plugins/resource/spfx/depsChecker/generatorChecker.ts
- packages/fx-core/src/plugins/resource/spfx/depsChecker/yoChecker.ts
> fix: extend the timeout duration

- templates/bot/js/command-and-response/.gitignore
- templates/bot/js/command-and-response/README.md
- templates/bot/js/command-and-response/package.json
- templates/bot/js/command-and-response/src/adaptiveCards/helloworldCommand.json
- templates/bot/js/command-and-response/src/helloworldCommandHandler.js
- templates/bot/js/command-and-response/src/index.js
- templates/bot/js/command-and-response/src/internal/initialize.js
tested locally
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/13883818/
> chore: add js command response template

- packages/cli/src/cmds/preview/commonUtils.ts
1. Add cli local envs for local debug.
> chore: add cli local env

- packages/vscode-extension/package.json
- packages/vscode-extension/src/utils/commonUtils.ts
This reverts commit e0a18f995872a470c040925816ad1db0e5b7fbdf.
> revert: revert: revert: chore: add notification command response bot vsc settings

- packages/vscode-extension/src/telemetry/extTelemetry.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/13978366
E2E TEST: treeview-build.test.ts
> fix: cannot activate extension without folder open

- packages/fx-core/src/plugins/resource/spfx/depsChecker/generatorChecker.ts
- packages/fx-core/src/plugins/resource/spfx/depsChecker/yoChecker.ts
- packages/fx-core/src/plugins/resource/spfx/plugin.ts
ADO:
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/13976934
Already generated vsix locally(https://microsoft-my.sharepoint.com/:u:/p/huihuiwu/Ed4IoazX72ZPv5l1TJJ2mXMBVpZCXu3DWXoO7Bn2yB5FKg?e=KMkXoK) and works well after Helly's test.
> fix: spfx scaffold fail

- packages/vscode-extension/test/unit/extension/handlers.test.ts
Add  test for https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/13506162?src=WorkItemMention&src-action=artifact_link
> test: only register azure account change notify for teamsfx project

- packages/vscode-extension/src/accountTree.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/13955298
E2E TEST: will add ut later
> fix: refresh env tree when m365 account change

- packages/fx-core/src/plugins/solution/fx-solution/debug/util/launchNext.ts
- packages/fx-core/tests/plugins/solution/debug/solution.debug.scaffolding.test.ts
- packages/vscode-extension/src/debug/teamsfxDebugProvider.ts
- remove launch remote configurations for m365 app
- fix account hint not set issue for m365 messaging extension
> chore(m365): remove launch remote configurations

- packages/vscode-extension/test/unit/extension/handlers.test.ts
Add test for https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/13900320
> test: add test to make sure create project event always has project id

- packages/fx-core/src/plugins/resource/appstudio/appStudio.ts
- packages/fx-core/src/plugins/resource/appstudio/plugin.ts
- packages/fx-core/src/plugins/resource/appstudio/v3/plugin.ts
1. Need to assign uuid for new teams app
2. Enhance error message
> fix: assign uuid

- packages/cli/tests/e2e/collaboration/Permission.tests.ts
- packages/cli/tests/e2e/collaboration/PermissionSPFX.tests.ts
- packages/cli/tests/e2e/commonUtils.ts
e2e test passed:
https://github.com/OfficeDev/TeamsFx/runs/5846468241?check_suite_focus=true
> test(e2e): fix permissionSPFX test failed due to project path exist

- packages/fx-core/resource/package.nls.json
Fix the string not closing issue raised from Localization team
E2E TEST: not needed
> fix: update string

- packages/fx-core/src/plugins/solution/fx-solution/v2/getQuestions.ts
When notification bot is enabled, remove bot in add capability question.
> chore: remove bot in add capability

- packages/fx-core/src/core/middleware/consolidateLocalRemote.ts
1.Fix backup, local debug configs to ```.gitignore``` logic.
> chore: update unify config project ignore

- packages/vscode-extension/src/handlers.ts
revert https://github.com/OfficeDev/TeamsFx/pull/4553
> chore: revert fix to unblock unit test

- packages/fx-core/src/plugins/solution/fx-solution/v2/executeUserTask.ts
- packages/fx-core/tests/plugins/solution/solution.usertask.test.ts
fix bug:
1. show correct error message
2. add correct auth files according to capability
3. scaffold aad plugin when adding sso tab
> perf: fix bug in add sso

- packages/vscode-extension/src/handlers.ts
- packages/vscode-extension/test/unit/extension/handlers.test.ts
> fix: add missing await

- packages/fx-core/resource/unify-config-change-logs.md
Update upgrade change log for config unify.
> chore(docs): Update unify-config-change-logs.md

- packages/fx-core/src/common/projectSettingsHelper.ts
- packages/fx-core/src/plugins/solution/fx-solution/v2/provision.ts
- packages/fx-core/tests/plugins/solution/solution.provision.test.ts
1. Update hasAzureResource function logic
2. Skip create resource group when no Azure resource
3. Update test case
> perf(aad-manifest): skip create resource group when no Azure resource

- .github/workflows/e2e-test.yml
> fix: fix e2e test shell escape

- packages/cli/src/questionUtils.ts
- packages/cli/tests/unit/questionUtils.tests.ts
This is for removing some hardcode in `resource add` and `capability add` commands.
> chore: filter QTreeNode by a fixed key/value

- packages/fx-core/resource/package.nls.json
[update wordings](https://microsoftapc.sharepoint.com/teams/DevDivTeamsDevXProductTeam/_layouts/OneNote.aspx?id=%2Fteams%2FDevDivTeamsDevXProductTeam%2FShared%20Documents%2FService%20infrastructure%20Team%2FInfra%20team&wd=target%28Infra.one%7C54126BB5-B660-493E-ABC2-5CDF1390B13A%2FUX%7C45A09606-1E4A-43D5-8624-D8E137A2833B%2F%29)
> chore: update existing app wordings

- packages/fx-core/src/plugins/resource/frontend/constants.ts
- packages/fx-core/src/plugins/resource/frontend/dotnet/plugin.ts
- packages/fx-core/src/plugins/resource/frontend/env.ts
- packages/fx-core/src/plugins/resource/frontend/ops/deploy.ts
- packages/fx-core/src/plugins/resource/frontend/plugin.ts
- packages/fx-core/src/plugins/resource/frontend/resources/errors.ts
- packages/fx-core/src/plugins/resource/frontend/utils/progress-helper.ts
- packages/fx-core/src/plugins/resource/frontend/v3/index.ts
- packages/fx-core/tests/plugins/resource/frontend/unit/index.test.ts
- templates/tab/js/default/package.json
- templates/tab/js/m365/package.json
- templates/tab/js/non-sso/package.json
- templates/tab/ts/default/package.json
- templates/tab/ts/m365/package.json
- templates/tab/ts/non-sso/package.json
E2E TEST: https://github.com/OfficeDev/TeamsFx/actions/runs/2032521640
> feat(frontend): support customize install command

- packages/fx-core/resource/package.nls.json
- packages/fx-core/src/plugins/resource/aad/errors.ts
- packages/fx-core/src/plugins/resource/aad/plugin.ts
Remove validate redirect URL when deploy Aad app to support existing app
Extract loadAndBuildManifest function
> perf(aad-manifest): update aad deploy to support existing app

- packages/cli/src/telemetry/telemetryReporter.ts
chore: fix polynomial regex
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/14060054
> chore: fix polynomial regex

- packages/cli/src/cmds/add.ts
- packages/cli/tests/commonlib/cliHelper.ts
- packages/cli/tests/e2e/clean.ts
- packages/cli/tests/e2e/command/argumentCheck.tests.ts
- packages/cli/tests/e2e/command/helpInfo.tests.ts
- packages/cli/tests/unit/cmds/addCICD.tests.ts
Task: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/14034053
E2E TEST: ["./*"]
> feat: use teamsFx add instead of teamsfx resource add and teamsfx capability add

- Localize/loc/cs/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/cs/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/de/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/de/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/es/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/es/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/fr/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/fr/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/it/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/it/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/ja/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/ja/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/ko/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/ko/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/pl/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/pl/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/pt-BR/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/pt-BR/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/ru/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/ru/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/tr/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/tr/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/zh-Hans/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/zh-Hans/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/zh-Hant/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/zh-Hant/packages/vscode-extension/package.nls.json.lcl
- packages/cli/package-lock.json
- packages/fx-core/package-lock.json
- packages/server/package-lock.json
- packages/vscode-extension/package-lock.json
LEGO: Pull request from juno/hb_fd34cb3d-1ea5-4a7c-8a66-721a44a97af3_20220408084946703 to hotfix/3.6.2 with localized lcls
> chore: [LEGO] Pull request from juno/hb_fd34cb3d-1ea5-4a7c-8a66-721a44a97af3_20220408084946703 to hotfix/3.6.2

- Localize/loc/fr/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/fr/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/ja/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/ja/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/ko/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/ko/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/zh-Hant/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/zh-Hant/packages/vscode-extension/package.nls.json.lcl
LEGO: Pull request from juno/hb_fd34cb3d-1ea5-4a7c-8a66-721a44a97af3_20220408204849574 to hotfix/3.6.2 with localized lcls
> chore: [LEGO] Pull request from juno/hb_fd34cb3d-1ea5-4a7c-8a66-721a44a97af3_20220408204849574 to hotfix/3.6.2

- packages/fx-core/templates/plugins/resource/apiconnector/sample/js/custom.template
- packages/fx-core/templates/plugins/resource/apiconnector/sample/ts/custom.template
- packages/fx-core/tests/plugins/resource/apiconnector/expectedFiles/js/custom.js
- packages/fx-core/tests/plugins/resource/apiconnector/expectedFiles/ts/custom.ts
- packages/fx-core/tests/plugins/resource/apiconnector/generateSampleCode.test.ts
- packages/fx-core/tests/plugins/resource/apiconnector/utils.ts
Here is the custom auth provider sample code.
Will add other content after the sample code is confirmed.
> chore(apicon): add custom auth sample

- packages/fx-core/src/plugins/solution/fx-solution/question.ts
> chore: fix question model for CLI

- packages/fx-core/resource/unify-config-change-logs.md
> chore(docs): Fix typos in unify config change log

- packages/fx-core/src/plugins/resource/aad/plugin.ts
Fix e2e test: tests/e2e/solution/AddCapabilities_MEAddTab.tests.ts
> fix: add missing me check in aad plugin

- packages/fx-core/src/plugins/solution/fx-solution/v2/getQuestions.ts
Fix https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/14101904/
> fix: should not add me for notification bot

- packages/api/review/teamsfx-api.api.md
- packages/api/src/qm/question.ts
- packages/api/src/qm/ui.ts
- packages/api/src/qm/visitor.ts
- packages/fx-core/resource/package.nls.json
- packages/fx-core/src/common/samples-config.json
- packages/fx-core/src/core/question.ts
- packages/vscode-extension/src/qm/vsc_ui.ts
UX design:
https://www.figma.com/file/qqVegbnWWBsqHhR8Qijs4O/Teams-Toolkit---GA?node-id=1802%3A214823
ADO:
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/13726073
Screenshot:
E2E TEST: n/a
> feat: ux enhancement for create from sample

- packages/cli/tests/e2e/bot/ProvisionCommandAndResponseBot.tests.ts
related to pr: https://github.com/OfficeDev/TeamsFx/pull/4637/files
> test(bot): update command and response cli capability name

- packages/fx-core/src/plugins/resource/appstudio/constants.ts
- packages/fx-core/src/plugins/resource/appstudio/plugin.ts
- packages/fx-core/tests/plugins/resource/appstudio/unit/scaffold.test.ts
- remove sharing message, creating card, link unfurling and keep search only for m365 messaging extension
> chore(m365): keep search only for m365 messaging extension

- packages/fx-core/src/plugins/resource/appstudio/index.ts
TASK: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/14113893
E2E TEST:
> fix: cli publish successful message

- packages/cli/tests/commonlib/constants.ts
- packages/cli/tests/e2e/commonUtils.ts
- packages/cli/tests/e2e/solution/AddSso_Bot.tests.ts
- packages/cli/tests/e2e/solution/AddSso_ExistingApp.tests.ts
- packages/cli/tests/e2e/solution/AddSso_Tab.tests.ts
successfully run: https://github.com/OfficeDev/TeamsFx/actions/runs/2159729816
> test: add e2e test for add sso

- packages/fx-core/src/common/constants.ts
- packages/fx-core/src/common/tools.ts
- packages/fx-core/src/plugins/solution/fx-solution/v2/getQuestions.ts
TASK: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/14113895
> chore: hide azure resource question when GA Preview feature flag opens

- templates/tab/js/default/package.json
- templates/tab/js/default/src/components/sample/AzureFunctions.jsx
- templates/tab/ts/default/package.json
- templates/tab/ts/default/src/components/sample/AzureFunctions.tsx
The latest SDK can help create API client. Update sample code to use this feature to call function api.
> chore: update call function sample code

- docs/sdk/teamsfx.apikeyprovider._constructor_.md
- docs/sdk/teamsfx.apikeyprovider.addauthenticationinfo.md
- docs/sdk/teamsfx.basicauthprovider._constructor_.md
- docs/sdk/teamsfx.basicauthprovider.addauthenticationinfo.md
- packages/sdk/src/apiClient/apiKeyProvider.browser.ts
- packages/sdk/src/apiClient/basicAuthProvider.browser.ts
- packages/sdk/src/apiClient/certificateAuthProvider.browser.ts
- packages/sdk/src/index.browser.ts
> feat: add auth provider in browser

- packages/cli/src/prompts/customizedCheckboxPrompt.ts
- packages/cli/src/prompts/customizedListPrompt.ts
- packages/cli/src/prompts/index.ts
- packages/cli/src/userInteraction.ts
- packages/cli/tests/unit/prompts/customizedCheckboxPrompt.tests.ts
- packages/cli/tests/unit/prompts/customizedListPrompt.tests.ts
Task: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/14103231
E2E TEST: https://github.com/OfficeDev/TeamsFx/actions/runs/2166344315
> chore: use id instead of label when asking users to select in CLI

- docs/fx-core/localdebug-help.md
- docs/vscode-extension/collaborating.md
- docs/vscode-extension/envchecker-help.md
- packages/fx-core/templates/plugins/solution/v1/README.md
- templates/bot/js/default/README.md
- templates/bot/js/m365/README.md
- templates/bot/ts/default/README.md
- templates/bot/ts/m365/README.md
- templates/function-base/js/default/README.md
- templates/function-base/ts/default/README.md
- templates/tab/js/default/README.md
- templates/tab/js/m365/README.md
- templates/tab/js/non-sso/README.md
- templates/tab/ts/default/README.md
- templates/tab/ts/m365/README.md
1.Update readme doc to support unify config.
> chore: update readme to support unify config

- packages/vscode-extension/package-lock.json
- packages/vscode-extension/package.json
WIT:
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/14060234
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/14060239
> chore(vsc): upgrade dependencies

- packages/cli/src/index.ts
TASK: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/14126128
> chore: init GA feature before running commands

- packages/fx-core/resource/package.nls.json
- packages/fx-core/src/plugins/solution/fx-solution/v2/getQuestions.ts
> chore(m365): block teamsfx capability add for m365 project

- packages/fx-core/src/plugins/resource/apiconnector/envHandler.ts
- packages/fx-core/src/plugins/resource/apiconnector/index.ts
- packages/fx-core/src/plugins/resource/apiconnector/plugin.ts
- packages/fx-core/src/plugins/resource/apiconnector/telemetry.ts
- packages/fx-core/src/plugins/resource/sql/constants.ts
- packages/fx-core/src/plugins/resource/sql/index.ts
- packages/fx-core/src/plugins/resource/sql/plugin.ts
- packages/fx-core/src/plugins/resource/sql/utils/dialogUtils.ts
- packages/fx-core/tests/plugins/resource/apiconnector/envHandler.test.ts
- packages/fx-core/tests/plugins/resource/apiconnector/utils.ts
- packages/fx-core/tests/plugins/resource/sql/helper.ts
1. add sql telemetry
2. add api-connector telemetry
3. update api-connector env
> chore(apicon): add telemetry

- packages/fx-core/src/common/local/localStateHelper.ts
- packages/fx-core/src/core/middleware/consolidateLocalRemote.ts
1.Update consolidate telemetry.
2.Add ```localEnvs.HTTPS=true``` when it is undefined.
> chore: update consolidate telemetry and frontend debug

- packages/fx-core/src/core/middleware/consolidateLocalRemote.ts
Fix SPFx project show Azure account problem.
E2E TEST: N/A
> fix: spfx project account tree item

- packages/cli/src/cmds/capability.ts
- packages/cli/src/cmds/preview/npmInstallHandler.ts
- packages/fx-core/src/plugins/solution/fx-solution/index.ts
TASK: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/14150991
E2E TEST: https://github.com/OfficeDev/TeamsFx/actions/runs/2182128516
> refactor(cli): re-organize capability commands

- docs/fx-core/spfx-help.md
- packages/fx-core/src/plugins/resource/spfx/depsChecker/yoChecker.ts
> chore: add help link for wrong npm version

- packages/fx-core/src/plugins/resource/sql/sqlClient.ts
> chore(sql): update sql message

- packages/cli/src/commonlib/codeFlowLogin.ts
- packages/cli/src/commonlib/codeFlowTenantLogin.ts
1.Fix open login page in vscode terminal.
> chore: fix vscode terminal open login page break

- packages/vscode-extension/src/extension.ts
- packages/vscode-extension/src/handlers.ts
Bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/13918737
E2E TEST: N/A
> fix(vsc): auto open readme shoud not be invoked in another project

- packages/vscode-extension/package.json
Unblock daily build.
E2E TEST: N/A
> fix(vsc): upgrade lowest vscode engine version

- packages/fx-core/templates/plugins/resource/apiconnector/package.json
- packages/fx-core/templates/plugins/resource/apiconnector/sample/headerComment.template
- packages/fx-core/templates/plugins/resource/apiconnector/sample/js/apikey.template
- packages/fx-core/templates/plugins/resource/apiconnector/sample/ts/aad.template
- packages/fx-core/templates/plugins/resource/apiconnector/sample/ts/apikey.template
- packages/fx-core/tests/plugins/resource/apiconnector/expectedFiles/js/aad-existing-app
- packages/fx-core/tests/plugins/resource/apiconnector/expectedFiles/js/api-key
- packages/fx-core/tests/plugins/resource/apiconnector/expectedFiles/ts/aad
- packages/fx-core/tests/plugins/resource/apiconnector/expectedFiles/ts/aad-existing-app
- packages/fx-core/tests/plugins/resource/apiconnector/expectedFiles/ts/api-key
1. ENV name incorrect
2. Missing steps for custom AAD auth
3. Update comments of AAD auth
> chore: fix problems in connect api template

- packages/fx-core/src/common/samples-config.json
1.Update sample tag to support unify config and new local debug.
> chore: update sample tag to support unify config and new local debug

- packages/fx-core/src/plugins/solution/fx-solution/debug/util/tasksNext.ts
- packages/vscode-extension/package.json
Localdebug failed because of error problem watcher.
Detail: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/14122966/
> fix(bot): fix func + func hosted bot localdebug

- packages/fx-core/src/plugins/solution/fx-solution/v2/executeUserTask.ts
- packages/fx-core/templates/plugins/resource/aad/auth/bot/README.md
- packages/fx-core/templates/plugins/resource/aad/auth/tab/README.md
Fix bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_sprints/taskboard/AuthAndData/Microsoft%20Teams%20Extensibility/CY22-4.2?workitem=14171934
> perf: fix typo and update doc link

- packages/fx-core/resource/package.nls.json
- packages/fx-core/src/plugins/resource/apiconnector/checker.ts
- packages/fx-core/src/plugins/resource/apiconnector/plugin.ts
- packages/fx-core/src/plugins/resource/apiconnector/questions.ts
- packages/fx-core/templates/plugins/resource/apiconnector/sample/js/aad.template
- packages/fx-core/templates/plugins/resource/apiconnector/sample/js/apikey.template
- packages/fx-core/templates/plugins/resource/apiconnector/sample/js/basic.template
- packages/fx-core/templates/plugins/resource/apiconnector/sample/js/cert.template
- packages/fx-core/templates/plugins/resource/apiconnector/sample/js/custom.template
- packages/fx-core/tests/plugins/resource/apiconnector/expectedFiles/js/aad
- packages/fx-core/tests/plugins/resource/apiconnector/expectedFiles/js/aad-existing-app
- packages/fx-core/tests/plugins/resource/apiconnector/expectedFiles/js/api-key
- packages/fx-core/tests/plugins/resource/apiconnector/expectedFiles/js/basic
- packages/fx-core/tests/plugins/resource/apiconnector/expectedFiles/js/cert
- packages/fx-core/tests/plugins/resource/apiconnector/expectedFiles/js/custom
- packages/fx-core/tests/plugins/resource/apiconnector/generateSampleCode.test.ts
1. update the export syntax of js template
2. add api name validation
3. fix the aad auth question when no aad is enabled
> chore(apicon): update

- packages/cli/src/cmds/preview/preview.ts
- packages/vscode-extension/src/debug/prerequisitesHandler.ts
Fix [bug](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/14124691)
> chore: check cert only for tabs

- packages/fx-core/resource/package.nls.json
- packages/fx-core/src/plugins/resource/apiconnector/envHandler.ts
- packages/fx-core/src/plugins/resource/apiconnector/errors.ts
- packages/fx-core/tests/plugins/resource/apiconnector/envHandler.test.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/14171493
> perf: validate env exist

- packages/fx-core/src/plugins/resource/apiconnector/depsHandler.ts
two prerelease scenarios
1. old toolkit scaffold new templates, local deps version newer than config deps
2. new toolkit add api to old project, local deps version older than config deps
> perf: deps ver checker

- docs/vscode-extension/envchecker-help.md
Fix [bug](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/13943305)
> chore: add sideloading faq to env helper doc

- packages/vscode-extension/package.json
> fix: update filter for navigation button

- packages/server/.nycrc
- packages/server/.prettierrc.js
- packages/server/.vscode/launch.json
- packages/server/package.json
- packages/server/tests/utils.test.ts
chore: setup UT for server package
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/14173960
> chore: setup UT for server package

- packages/fx-core/src/plugins/solution/fx-solution/debug/util/launchNext.ts
> chore(m365): group m365 launch configurations by hub

- templates/tab/js/default/src/components/sample/AzureFunctions.jsx
- templates/tab/ts/default/src/components/sample/AzureFunctions.tsx
> refactor(tab): avoid global variable

- packages/cli/deletePS1.js
- packages/cli/package-lock.json
- packages/cli/package.json
Bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/13976918
E2E TEST: N/A
> fix(cli): support windows powershell to ga

- packages/fx-core/src/common/tools.ts
- packages/fx-core/src/plugins/solution/fx-solution/v2/executeUserTask.ts
1. Fix canAddSso
2. Add canAddSso in tool.ts. @tecton Please help to use this function to decide whether SSO needs to be included in `add Features`.
> perf: update can add sso

- packages/vscode-extension/webpack.config.js
Fix bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/14171552
> perf(add sso): skip minify template files

- packages/vscode-extension/src/codeLensProvider.ts
- packages/vscode-extension/src/extension.ts
> perf(aad-manifest): add deprecated codelens for permissions file

- packages/cli/package-lock.json
- packages/fx-core/resource/package.nls.json
- packages/fx-core/src/plugins/solution/fx-solution/v2/deploy.ts
- packages/fx-core/src/plugins/solution/fx-solution/v2/utils.ts
Show message and action button for bot trouble shooting after deploy.
https://dev.azure.com/msazure/Microsoft%20Teams%20Extensibility/_workitems/edit/13321566
> chore: add bot troubleshooting

- packages/cli/src/userInteraction.ts
Bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/14211052
E2E TEST:
> fix(cli): show message error

- packages/server/.nycrc
- packages/server/tests/customizedFuncAdapter.test.ts
- packages/server/tests/providers/logger.test.ts
- packages/server/tests/providers/telemetry.test.ts
- packages/server/tests/providers/userInteraction.test.ts
- packages/server/tests/serverConnections.test.ts
- packages/server/tests/utils.test.ts
chore: server package UT coverage to 60%
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/14173960
> chore: server package UT coverage to 60%

- packages/cli/src/cmds/preview/commonUtils.ts
- packages/cli/src/cmds/preview/constants.ts
- packages/cli/src/cmds/preview/preview.ts
- packages/cli/src/cmds/preview/teamsAppInstallation.ts
- show 'Configure Outlook' option for remote preview for m365 messaging
extension app
> chore(m365): show configure outlook option for remote preview

- packages/cli/src/userInteraction.ts
Reverts OfficeDev/TeamsFx#4804
E2E TEST:
> revert(cli): show message error

- packages/server/.nycrc
- packages/server/tests/providers/token/appStudio.test.ts
- packages/server/tests/providers/token/azure.test.ts
- packages/server/tests/providers/token/graph.test.ts
- packages/server/tests/providers/token/memoryCache.test.ts
- packages/server/tests/providers/token/sharepoint.test.ts
- packages/server/tests/providers/userInteraction.test.ts
chore: add more UT for server package
UT coverage up to 95%
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/14173960
> chore: add more UT for server package

- Localize/loc/cs/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/de/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/es/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/fr/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/it/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/ja/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/ko/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/pl/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/pt-BR/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/ru/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/tr/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/zh-Hans/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/zh-Hant/packages/fx-core/resource/package.nls.json.lcl
LEGO: Pull request from juno/hb_fd34cb3d-1ea5-4a7c-8a66-721a44a97af3_20220424144114947 to hotfix/3.6.2 with localized lcls
> chore(LEGO): pull request from juno/hb_fd34cb3d-1ea5-4a7c-8a66-721a44a97af3_20220424144114947 to hotfix/3.6.2

- packages/cli/src/cmds/preview/preview.ts
- packages/fx-core/src/common/projectSettingsHelper.ts
- packages/fx-core/src/core/FxCore.ts
- packages/fx-core/src/plugins/resource/appstudio/v3/index.ts
- packages/fx-core/src/plugins/resource/cicd/index.ts
- packages/fx-core/src/plugins/solution/fx-solution/v2/provision.ts
- packages/fx-core/src/plugins/solution/fx-solution/v2/provisionLocal.ts
- packages/fx-core/src/plugins/solution/fx-solution/v2/publish.ts
- packages/vscode-extension/src/utils/commonUtils.ts
Update the condition to check existing tab app after SSO is added.
E2E TEST: https://github.com/OfficeDev/TeamsFx/blob/01d6a9fb35d8418a3cec89a96949325bcbbea968/packages/cli/tests/e2e/existingapp/TestCreateExistingTab.tests.ts#L17
> fix(existing-tab): update the condition to check existing tab app

- packages/vscode-extension/test/unit/extension/extTelemetry.test.ts
chore: update telemetry UT to check localized string
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/12982810
> chore: update telemetry UT to check localized string

- packages/fx-core/templates/plugins/resource/aad/auth/tab/js/sso/GetUserProfile.jsx
- packages/fx-core/templates/plugins/resource/aad/auth/tab/js/sso/InitTeamsFx.jsx
- packages/fx-core/templates/plugins/resource/aad/auth/tab/ts/sso/GetUserProfile.tsx
- packages/fx-core/templates/plugins/resource/aad/auth/tab/ts/sso/InitTeamsFx.tsx
Fix bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_sprints/taskboard/AuthAndData/Microsoft%20Teams%20Extensibility/CY22-4.2?workitem=14225465
> docs(add sso): update add sso tab template

- packages/fx-core/src/plugins/resource/cicd/index.ts
Skip env question in single env case for Teams Toolkit.
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/14104788
> chore: align env question cicd

- packages/fx-core/src/plugins/resource/bot/question.ts
Bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/14246730
> fix(vsc): condition of time trigger question

- packages/cli/tests/e2e/bot/ProvisionAppServiceNotificationBot.tests.ts
- packages/cli/tests/e2e/bot/ProvisionCommandAndResponseBot.tests.ts
- packages/cli/tests/e2e/bot/ProvisionFuncHostedNotificationBot.tests.ts
Use beta template to test GA branch
> test: update ga e2e test case to beta template

- packages/vscode-extension/package.nls.json
- packages/vscode-extension/src/codeLensProvider.ts
- packages/vscode-extension/src/extension.ts
> fix: add codelens to remind user not modifying it

- packages/fx-core/resource/package.nls.json
- packages/fx-core/src/core/question.ts
- packages/fx-core/tests/core/question.test.ts
> fix: validate app name length

- packages/vscode-extension/src/handlers.ts
ADO:
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/14234188
E2E TEST: NA
> fix: failed to open readme for spfx project

- packages/vscode-extension/src/debug/teamsfxDebugProvider.ts
- packages/vscode-extension/src/debug/teamsfxTaskHandler.ts
To fix https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/14252955.
E2E TEST: N/A
> fix(m365): fix task not terminated after stopping F5

- packages/fx-core/src/common/samples-config.json
Add imcoming webhook sample into create sample question options
> chore(bot): add incoming webhook sample

- packages/fx-core/resource/package.nls.json
- packages/fx-core/src/plugins/solution/fx-solution/debug/error.ts
> chore(localdebug): update skip ngrok error message

- packages/fx-core/src/common/tools.ts
- packages/fx-core/src/plugins/solution/fx-solution/v2/executeUserTask.ts
- packages/fx-core/src/plugins/solution/fx-solution/v2/getQuestions.ts
- packages/vscode-extension/package.json
Related bug:
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/14263279
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/14263279
E2E TEST: N/A
> fix(vsc+core): addFeature bug in existing tab app

- packages/fx-core/src/core/environment.ts
- packages/fx-core/src/core/middleware/envInfoLoader.ts
1. Add auto generate local config for existing app feature.
Fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/14246812/
> fix: add auto generate local config for existing app

- templates/tab/js/default/src/components/sample/AzureFunctions.jsx
Bug: https://dev.azure.com/msazure/Microsoft%20Teams%20Extensibility/_workitems/edit/14245348
> chore: remove unused vars

- packages/fx-core/resource/package.nls.json
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/14225786
> chore(core): improve provision prompt

- packages/cli/tests/e2e/command/deployWithWrongPluginName.tests.ts
E2E TEST: https://github.com/OfficeDev/TeamsFx/actions/runs/2237293216
> fix(cli): deploy with wrong plugin name test case

- packages/fx-core/src/plugins/solution/fx-solution/v2/provision.ts
Fix E2E test case: tests/e2e/solution/AddSso_ExistingApp.tests.ts
E2E TEST: https://github.com/OfficeDev/TeamsFx/actions/runs/2233547262
> fix(e2e): fix e2e test case when SSO is added to existing app

- packages/api/review/teamsfx-api.api.md
- packages/api/src/types.ts
- packages/fx-core/resource/package.nls.json
- packages/fx-core/src/plugins/solution/fx-solution/question.ts
- packages/vscode-extension/src/extension.ts
- packages/vscode-extension/src/qm/vsc_ui.ts
- packages/vscode-extension/src/telemetry/extTelemetryEvents.ts
- packages/vscode-extension/src/utils/commonUtils.ts
Screenshot:
ADO:
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/14250162
UX design:
https://www.figma.com/proto/qqVegbnWWBsqHhR8Qijs4O/Teams-Toolkit---GA?page-id=2139%3A266609&node-id=2503%3A263080&viewport=394%2C48%2C0.07&scaling=contain&starting-point-node-id=2503%3A263080
E2E TEST: NA
> feat: add tutorial button on capability list

- templates/bot/ts/command-and-response/package.json
- templates/bot/ts/default/package.json
- templates/bot/ts/m365/package.json
- templates/bot/ts/notification-restify/package.json
Detail: [Bug 14264065](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/14264065): Update adaptive card doesn't get refreshed in hot reload
> fix(localdebug): hot reload when json file changed

- packages/fx-core/resource/package.nls.json
- packages/fx-core/src/plugins/solution/fx-solution/v2/executeUserTask.ts
Fix bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_sprints/taskboard/AuthAndData/Microsoft%20Teams%20Extensibility/CY22-4.2?workitem=14263322
> perf: remove notification in existing app scenario

- docs/sdk/teamsfx.teamsfxbotcommandhandler.handlecommandreceived.md
- packages/sdk/review/teamsfx.api.md
- packages/sdk/src/conversation/interface.ts
- packages/sdk/src/conversation/middleware.ts
- packages/sdk/test/unit/node/conversation/testUtils.ts
- templates/bot/ts/command-and-response/src/helloworldCommandHandler.ts
Resolve [Bug 14264354](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/14264354): Am I able to return nothing in bot command handler?
> chore(command-bot): allow no return value in handleCommandReceived API

- packages/fx-core/src/core/question.ts
- packages/fx-core/src/plugins/solution/fx-solution/v2/getQuestions.ts
- packages/fx-core/tests/core/core.test.ts
Adding feature like "SSO" should not ask programming language question.
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/14273639
E2E TEST: N/A
> fix(core): programming language question condition

- packages/cli/tests/e2e/sql/ProvisionMultiDatabase.tests.ts
- packages/cli/tests/e2e/sql/ProvisionReactAppWithAzureFunctionAndSQL.tests.ts
As the command of creating SQL has changed, update e2e test.
> chore(sql): update e2e test

- packages/fx-core/src/core/middleware/errorHandler.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/14274066
> chore(core): refine log for error handler middleware

- packages/fx-core/templates/core/README.md
Use the consolidated aka link for embed existing app.
> docs(existing-app): consolidate the aka link

- .github/scripts/lerna.sh
- .github/scripts/lernaDeps.json
- .github/workflows/cd.yml
CD support release specific releases with inputs as following picture. 
1. if empty will release all the pkgs.
2. if inputs with space, will release the specific pkgs. 
The inputs only contain sdk, cli, vscode, cli, server and template
the following picture will only release sdk, vscode and cli.
> chore: separate pkgs to release

- packages/fx-core/src/plugins/resource/apiconnector/index.ts
- packages/fx-core/src/plugins/resource/apiconnector/plugin.ts
- packages/fx-core/src/plugins/resource/apiconnector/result.ts
- packages/fx-core/src/plugins/solution/fx-solution/constants.ts
- packages/fx-core/tests/plugins/resource/apiconnector/scaffold.test.ts
- packages/vscode-extension/src/handlers.ts
https://dev.azure.com/msazure/Microsoft%20Teams%20Extensibility/_workitems/edit/14276715
> perf(api-connector): open scaffold files once user task done

- .github/workflows/cd.yml
update the cd schedule policy
dev branch only release alpha.
ga branch only release beta.
> chore: fix schedule error

- .github/scripts/lerna.sh
- .github/scripts/lernaDeps.json
- .github/workflows/cd.yml
cherry-pick from dev branch:
44ac039f154b6480cc0b54d55fb14b41baf4e309
11e9ca73a47615fc7d09f11c72ecc1f7622a8179
this CD pipeline already success run as following
https://github.com/OfficeDev/TeamsFx/actions/runs/2273606385
> chore: support separate release pkgs

- packages/cli/src/cmds/add.ts
- packages/cli/src/cmds/capability.ts
- packages/fx-core/src/plugins/solution/fx-solution/v2/getQuestions.ts
Fix the manifest_addCapability e2e test fail
Successfully job run: https://github.com/OfficeDev/TeamsFx/actions/runs/2279566574
> test: fix manifest e2e test

- packages/cli/tests/e2e/multienv/TestRemoteHappyPath.tests.ts
Fix e2e/multienv/TestRemoteHappyPath.tests.ts for GA
E2E TEST: https://github.com/OfficeDev/TeamsFx/actions/runs/2279850131
> test: fix multienv test case

- packages/fx-core/src/plugins/solution/fx-solution/v2/executeUserTask.ts
Fix bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/14344454
> perf(aad manifest): scaffold aad arm template when add sso tab

- packages/fx-core/templates/plugins/resource/aad/auth/bot/README.md
- packages/fx-core/templates/plugins/resource/aad/auth/tab/README.md
> docs(readme): Update README for Add SSO

- packages/fx-core/src/plugins/solution/fx-solution/v2/getQuestions.ts
- packages/fx-core/tests/plugins/solution/solution.getQuestions.test.ts
Fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/14342538/
E2E TEST: n/a covered by UT
> fix: should be able to add ME with old bot

- templates/bot/ts/command-and-response/tsconfig.json
- templates/bot/ts/default/tsconfig.json
- templates/bot/ts/m365/tsconfig.json
- templates/bot/ts/notification-function-base/tsconfig.json
- templates/bot/ts/notification-restify/tsconfig.json
- templates/function-base/ts/default/tsconfig.json
Detail: [Bug 14359904](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/14359904): [stable] typescript function project deploy failed
> fix: add "skipLibCheck" in "tsconfig.json"

- packages/fx-core/src/core/FxCore.ts
ADO: 
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/14264621
E2E TEST: NA
> fix: dont show azure related notification for spfx scaffolding

- packages/cli/src/cmds/preview/constants.ts
- packages/cli/src/cmds/preview/preview.ts
- packages/vscode-extension/package.nls.json
- packages/vscode-extension/src/debug/constants.ts
- packages/vscode-extension/src/debug/teamsfxDebugProvider.ts
- packages/vscode-extension/src/debug/teamsfxTaskHandler.ts
- templates/bot/js/m365/README.md
- templates/bot/ts/m365/README.md
- templates/tab/js/m365/README.md
- templates/tab/ts/m365/README.md
- add setting up dev environment to prerequisites in README
- show m365 tenant hint message when sideloading
> chore(m365): add m365 tenant hint message

- .github/scripts/lernaDeps.json
support release adaptive card separate.
> chore: add adaptive card to separate release

- packages/fx-core/templates/plugins/resource/aad/auth/bot/README.md
- packages/fx-core/templates/plugins/resource/aad/auth/tab/README.md
> docs: update add sso readme

- templates/bot/ts/command-and-response/package.json
- templates/bot/ts/notification-function-base/package.json
- templates/bot/ts/notification-restify/package.json
Fix [Bug 14369953](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/14369953): [GA Bug Bash] Bot App tsconfig.ts not aligned with compilation behavior.
E2E TEST: covered by UI test
> chore(template): update npm build script to copy adaptiveCards folder

- packages/sdk/src/conversation/middleware.ts
- packages/sdk/src/conversation/notification.ts
- packages/sdk/src/conversation/utils.ts
- packages/sdk/test/unit/node/conversation/middleware.spec.ts
- packages/sdk/test/unit/node/conversation/utils.spec.ts
- Add missing `await`
- Use deep clone
- Able to handle mention message for channel
E2E TEST: covered by UI test
> fix: add missing await and handle mention message for channel

- packages/fx-core/src/plugins/solution/fx-solution/question.ts
ADO:
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/14361655
E2E TEST: na
> fix: tutorial link for api-connect and add-sso

- templates/bot/ts/m365/package.json
To fix https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/14359623.
E2E TEST: N/A
> fix(m365): fix bot ts building error

- packages/cli/src/cmds/config.ts
- packages/cli/src/cmds/preview/commonUtils.ts
- packages/vscode-extension/package.json
- packages/vscode-extension/src/debug/npmInstallHandler.ts
- packages/vscode-extension/test/unit/localdebug/npmInstallHandler.test.ts
To fix https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/14370028.
> chore: hide automatic npm install

- packages/fx-core/src/common/deps-checker/constant/telemetry.ts
- packages/fx-core/src/common/deps-checker/internal/nodeChecker.ts
- Add node version telemetry for localdebug and getStarted
E2E TEST: N/A
> chore: add node version telemetry

- packages/server/src/apis.ts
- packages/server/src/serverConnection.ts
- packages/server/tests/serverConnections.test.ts
> chore: add api to deploy manifest

- packages/vscode-extension/src/handlers.ts
This reverts commit 1ed140698556a58830bc44eef324e2669a09d0a7.
> Revert "fix: failed to open readme for spfx project"

- packages/cli/tests/e2e/bot/ProvisionResourceProjectWithNewBot.tests.ts
https://dev.azure.com/msazure/Microsoft%20Teams%20Extensibility/_workitems/edit/14414450
> chore: fix bot e2e case

- packages/fx-core/resource/package.nls.json
- packages/fx-core/src/plugins/resource/appstudio/plugin.ts
work item: 14290560
differentiate log string and info window string
> fix: enhance log

- packages/cli/src/cmds/new.ts
- packages/cli/src/cmds/preview/preview.ts
- packages/cli/src/telemetry/cliTelemetry.ts
- packages/cli/src/telemetry/cliTelemetryEvents.ts
- packages/cli/src/utils.ts
- packages/fx-core/src/common/local/constants.ts
- packages/fx-core/src/common/local/projectSettingsHelper.ts
- packages/fx-core/src/plugins/solution/fx-solution/debug/provisionLocal.ts
- packages/fx-core/src/plugins/solution/fx-solution/debug/scaffolding.ts
- packages/vscode-extension/src/debug/commonUtils.ts
- packages/vscode-extension/src/handlers.ts
- packages/vscode-extension/src/telemetry/extTelemetry.ts
- packages/vscode-extension/src/telemetry/extTelemetryEvents.ts
Reverts OfficeDev/TeamsFx#4978
> chore: Revert add m365 and bot capability telemetry property

- .github/CODEOWNERS
- packages/dotnet-sdk/src/TeamsFx.Test/Conversation/ConversationReferenceExtensionsTest.cs
- packages/dotnet-sdk/src/TeamsFx/Conversation/ActivityType.cs
- packages/dotnet-sdk/src/TeamsFx/Conversation/Channel.cs
- packages/dotnet-sdk/src/TeamsFx/Conversation/ConversationBot.cs
- packages/dotnet-sdk/src/TeamsFx/Conversation/ConversationOptions.cs
- packages/dotnet-sdk/src/TeamsFx/Conversation/ConversationReferenceExtensions.cs
- packages/dotnet-sdk/src/TeamsFx/Conversation/INotificationTarget.cs
- packages/dotnet-sdk/src/TeamsFx/Conversation/INotificationTargetStorage.cs
- packages/dotnet-sdk/src/TeamsFx/Conversation/ITurnContextExtensions.cs
- packages/dotnet-sdk/src/TeamsFx/Conversation/LocalFileStorage.cs
- packages/dotnet-sdk/src/TeamsFx/Conversation/Member.cs
- packages/dotnet-sdk/src/TeamsFx/Conversation/NotificationBot.cs
- packages/dotnet-sdk/src/TeamsFx/Conversation/NotificationMiddleware.cs
- packages/dotnet-sdk/src/TeamsFx/Conversation/NotificationOptions.cs
- packages/dotnet-sdk/src/TeamsFx/Conversation/NotificationTargetType.cs
- packages/dotnet-sdk/src/TeamsFx/Conversation/TeamsBotInstallation.cs
- packages/dotnet-sdk/src/TeamsFx/Credential/TeamsUserCredential.cs
- packages/dotnet-sdk/src/TeamsFx/Microsoft.TeamsFx.csproj
- packages/dotnet-sdk/src/TeamsFx/Model/AccessToken.cs
- packages/dotnet-sdk/src/TeamsFx/MsGraphAuthProvider.cs
- Add notification dotnet sdk to /packages/dotnet-sdk/src/TeamsFx/Conversation
- Update code owners as well
- Code comment added
- UT will be added in later PR
E2E TEST: N/A
> feat: add notification dotnet sdk

- templates/bot/ts/command-and-response/src/cardModels.ts
- templates/bot/ts/command-and-response/src/helloworldCommandHandler.ts
- templates/bot/ts/command-and-response/src/index.ts
- templates/bot/ts/notification-function-base/src/cardModels.ts
- templates/bot/ts/notification-restify/src/cardModels.ts
- templates/bot/ts/notification-restify/src/index.ts
- templates/bot/ts/notification-trigger-http/src/httpTrigger.ts
- templates/bot/ts/notification-trigger-timer/src/timerTrigger.ts
Update the default template comments.
> docs(comments): Update template comments.

- packages/cli/src/cmds/new.ts
- packages/cli/src/cmds/preview/preview.ts
- packages/cli/src/telemetry/cliTelemetry.ts
- packages/cli/src/telemetry/cliTelemetryEvents.ts
- packages/cli/src/utils.ts
- packages/cli/tests/unit/utils.tests.ts
- packages/fx-core/src/common/local/constants.ts
- packages/fx-core/src/common/local/projectSettingsHelper.ts
- packages/fx-core/src/plugins/solution/fx-solution/debug/provisionLocal.ts
- packages/fx-core/src/plugins/solution/fx-solution/debug/scaffolding.ts
- packages/vscode-extension/src/debug/commonUtils.ts
- packages/vscode-extension/src/handlers.ts
- packages/vscode-extension/src/telemetry/extTelemetry.ts
- packages/vscode-extension/src/telemetry/extTelemetryEvents.ts
Detail: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/14378265/
add bot-capabilities and bot-host-type to localdebug telemetry
add is-m365 to all cli/vscode telemetry
> chore: add m365 and bot capability telemetry property

- packages/cli/src/cmds/preview/launch.ts
- packages/cli/tests/unit/cmds/preview/launch.tests.ts
- packages/vscode-extension/src/debug/launch.ts
To fix https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/14423884.
E2E TEST: N/A
> fix(m365): fix opening outlook channel config page no response

- docs/sdk/teamsfx.channel._constructor_.md
- docs/sdk/teamsfx.channel.md
- docs/sdk/teamsfx.commandmessage.md
- docs/sdk/teamsfx.md
- docs/sdk/teamsfx.member._constructor_.md
- docs/sdk/teamsfx.member.md
- docs/sdk/teamsfx.notificationtargetstorage.delete.md
- docs/sdk/teamsfx.notificationtargetstorage.md
- docs/sdk/teamsfx.teamsfxbotcommandhandler.handlecommandreceived.md
- packages/sdk/src/conversation/interface.ts
- packages/sdk/src/conversation/notification.browser.ts
- packages/sdk/src/conversation/notification.ts
Fix typos in conversation sdk code comment.
> chore: fix comment typos

- packages/fx-core/templates/plugins/resource/aad/auth/bot/js/sso/showUserInfo.js
- packages/fx-core/templates/plugins/resource/aad/auth/bot/ts/sso/showUserInfo.ts
task: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_sprints/taskboard/AuthAndData/Microsoft%20Teams%20Extensibility/CY22-5.1?workitem=14434487
> docs: update comment in teamsSsoBot

- docs/sdk/teamsfx.messagebuilder.attachadaptivecard.md
- docs/sdk/teamsfx.messagebuilder.attachadaptivecardwithoutdata.md
- packages/sdk/review/teamsfx.api.md
- packages/sdk/src/conversation/messageBuilder.ts
Add type constraint to the `TData` for adaptive card builder API.
E2E TEST: covered by UI test
> fix(sdk): fix adaptive card builder API

- packages/dotnet-sdk/src/TeamsFx.Test/Conversation/ConversationReferenceExtensionsTest.cs
- packages/dotnet-sdk/src/TeamsFx.Test/Conversation/ITurnContextExtensionsTest.cs
- packages/dotnet-sdk/src/TeamsFx.Test/Conversation/InMemoryStorage.cs
- packages/dotnet-sdk/src/TeamsFx.Test/Conversation/NotificationMiddlewareTest.cs
- packages/dotnet-sdk/src/TeamsFx/Conversation/INotificationTargetStorage.cs
- packages/dotnet-sdk/src/TeamsFx/Conversation/Member.cs
- Fix typo in code comment
- Add unit tests for notification part
> chore: add ut and fix typo

- packages/cli/src/cmds/preview/depsChecker/cliUtils.ts
- packages/cli/src/cmds/preview/preview.ts
- packages/cli/tests/unit/cmds/preview/depsChecker.test.ts
- packages/fx-core/src/common/deps-checker/constant/telemetry.ts
- packages/vscode-extension/src/debug/depsChecker/vscodeHelper.ts
> chore: add telemerty for skipping node and func checker

- templates/bot/js/notification-restify/src/index.js
- templates/bot/js/notification-restify/src/internal/initialize.js
- templates/bot/ts/notification-restify/src/index.ts
- templates/bot/ts/notification-restify/src/internal/initialize.ts
Move server init to `index.js/ts` to align with command bot.
> chore: relocate server init

- packages/cli/src/cmds/preview/commonUtils.ts
- packages/vscode-extension/src/debug/commonUtils.ts
- handle resourceBaseName with suffix placeholder in samples
> chore(m365): handle resourceBaseName with suffix placeholder

- packages/vscode-extension/src/handlers.ts
ADO: 
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/14431825
E2E TEST: will add ut later
> fix: cannot open readme from quick start for spfx sample

- docs/vscode-extension/envchecker-help.md
- packages/fx-core/src/common/deps-checker/constant/helpLink.ts
See [envchecker-help doc](https://github.com/OfficeDev/TeamsFx/blob/pengfei/update-envchecker-help/docs/vscode-extension/envchecker-help.md)
E2E TEST: N/A
> chore: update envchecker-help and fix helplink

- packages/fx-core/src/common/telemetry.ts
- packages/fx-core/src/core/middleware/aadManifestMigration.ts
Already have test plan for migration
> perf(aad-migration): telemetry typo

- packages/cli/tests/e2e/existingapp/TestCreateExistingTab.tests.ts
E2E TEST: https://github.com/OfficeDev/TeamsFx/actions/runs/2335730815
> chore(test): remove useless environment variable for E2E

- packages/manifest/tsconfig.json
Fixes bug https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/14446086
E2E TEST: Not needed.
> fix: remove includeHelper

- packages/server/src/serverConnection.ts
- packages/server/tests/serverConnections.test.ts
chore: add request to get sideloading status
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/14473098
> chore: add request to get sideloading status

- templates/tab/ts/non-sso/src/components/App.tsx
fix bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/14464852
> perf: remove useless import in non sso tab template

- templates/bot/js/command-and-response/README.md
- templates/bot/js/notification-function-base/README.md
- templates/bot/js/notification-restify/README.md
- templates/bot/ts/command-and-response/README.md
- templates/bot/ts/notification-function-base/README.md
- templates/bot/ts/notification-restify/README.md
Fix https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/14434681
> docs(README): Fix links in README

- packages/vscode-extension/src/controls/SampleGallery.scss
ADO:
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/14431385
Before:
After:
E2E TEST: NA
> fix(accessibility): add shadow for sample card to satisfy conmpliance

- templates/function-base/js/default/extensions.csproj
- templates/function-base/ts/default/extensions.csproj
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/14377950
> chore: bump up extension version in templates

- packages/dotnet-sdk/src/TeamsFx.Test/Conversation/CommandBotTest.cs
- packages/dotnet-sdk/src/TeamsFx.Test/Conversation/CommandResponseMiddlewareTest.cs
- packages/dotnet-sdk/src/TeamsFx.Test/Conversation/TestCommandHandler.cs
- packages/dotnet-sdk/src/TeamsFx/Conversation/CommandBot.cs
- packages/dotnet-sdk/src/TeamsFx/Conversation/CommandResponseMiddleware.cs
- packages/dotnet-sdk/src/TeamsFx/Conversation/ITeamsCommandHandler.cs
- Add unit tests for command bot dotnet SDK
- Fix bugs in command bot SDK
E2E TEST: N/A
> chore: add unit test for command-response dotnet sdk and tweak the sdk

- packages/fx-core/resource/package.nls.json
- packages/fx-core/src/plugins/resource/bot/errors.ts
- packages/fx-core/src/plugins/resource/bot/languageStrategy.ts
- packages/fx-core/src/plugins/resource/bot/resources/messages.ts
E2E TEST: https://github.com/OfficeDev/TeamsFx/blob/dev/packages/cli/tests/e2e/bot/CommandExecutionIsUserError.ts#L35
> fix(bot): suggest user run failed command

- packages/fx-core/src/plugins/resource/apiconnector/index.ts
https://dev.azure.com/msazure/Microsoft%20Teams%20Extensibility/_workitems/edit/14483689/
> perf: active judge

- packages/fx-core/templates/plugins/resource/aad/auth/bot/js/public/auth-end.html
- packages/fx-core/templates/plugins/resource/aad/auth/bot/ts/public/auth-end.html
Fix codeql issue: https://github.com/OfficeDev/TeamsFx/security/code-scanning?query=is%3Aopen+branch%3Adev+severity%3Ahigh
> fix: fix codeql issue

- packages/vscode-extension/package.nls.json
- templates/bot/js/m365/README.md
- templates/bot/ts/m365/README.md
> fix(m365): fix typo

- README.md
> chore: add code quality badge to readme

- packages/fx-core/src/plugins/solution/fx-solution/constants.ts
- packages/fx-core/src/plugins/solution/fx-solution/v2/provision.ts
Fixes bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_sprints/taskboard/Teams%20Extensibility%20E2E%20Team/Microsoft%20Teams%20Extensibility/CY22-5.2?workitem=14483877
> chore(solution): add subscription-id in telemetry

- packages/fx-core/src/core/question.ts
Fixes https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_sprints/taskboard/Teams%20Extensibility%20E2E%20Team/Microsoft%20Teams%20Extensibility/CY22-5.2?workitem=14497582
> chore: change capability question for dotnet to singleSelect

- packages/fx-core/src/common/local/microsoftTunnelingManager.ts
- packages/fx-core/src/common/local/microsoftTunnelingService.ts
- packages/fx-core/tests/common/local/microsoftTunnelingManager.test.ts
- add checkOnboarded method for prereqs check logic to use
- UT added
E2E TEST: n/a covered by UT
> chore: add checkOnboarded for pre-reqs check

- packages/cli/src/cmds/preview/constants.ts
- packages/cli/src/cmds/preview/preview.ts
- packages/fx-core/src/common/deps-checker/internal/funcToolChecker.ts
- packages/fx-core/src/plugins/solution/fx-solution/debug/util/tasksNext.ts
- packages/vscode-extension/src/debug/depsChecker/doctorConstant.ts
- packages/vscode-extension/src/debug/prerequisitesHandler.ts
- packages/vscode-extension/src/handlers.ts
E2E TEST: https://github.com/OfficeDev/TeamsFx/actions/runs/2359510927
> fix: fix get-func-path command

- packages/cli/tests/e2e/bot/CanDeployToCustomizedRg.tests.ts
- packages/cli/tests/e2e/commonUtils.ts
E2E test result: https://github.com/OfficeDev/TeamsFx/actions/runs/2368621745
> test(e2e): fix e2e test customize resource group

- packages/fx-core/templates/plugins/resource/aad/auth/bot/README.md
Fix bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/14511645
> docs: update add sso readme for bot

- packages/fx-core/src/common/projectSettingsHelper.ts
- packages/fx-core/src/plugins/resource/frontend/dotnet/constants.ts
- packages/fx-core/src/plugins/resource/frontend/dotnet/plugin.ts
- packages/fx-core/src/plugins/solution/fx-solution/v3/constants.ts
- packages/fx-core/src/plugins/solution/fx-solution/v3/userTask.ts
- packages/fx-core/tests/plugins/resource/dotnet/unit/localDebug.test.ts
> fix: migrate dotnet plugin into frontend

- templates/bot/csharp/command-and-response/Commands/HelloWorldCommandHandler.cs.tpl
- templates/bot/csharp/command-and-response/Controllers/BotController.cs.tpl
- templates/bot/csharp/command-and-response/ProjectName.csproj.tpl
- templates/package.json
- Update command bot template to align with the [latest conversation SDK](https://github.com/OfficeDev/TeamsFx/tree/dev/packages/dotnet-sdk/src/TeamsFx/Conversation)
- Display `.fx` folder & files in command bot project
- Enable command bot template
> chore: update and enable command bot template

- packages/fx-core/src/plugins/resource/bot/constants.ts
- packages/fx-core/src/plugins/resource/bot/index.ts
- packages/fx-core/src/plugins/resource/bot/question.ts
- packages/fx-core/src/plugins/resource/bot/v2/common.ts
- packages/fx-core/src/plugins/resource/bot/v2/mapping.ts
E2E TEST: will add e2e test after feature done.
> feat(bot): support scaffold csharp template

- templates/bot/js/command-and-response/README.md
- templates/bot/ts/command-and-response/README.md
> docs: fix readme typos in main

- packages/fx-core/src/plugins/resource/frontend/dotnet/constants.ts
E2E TEST: will add e2e test after feature complete.
> fix(frontend): plugin name is wrong

- ROADMAP.md
- SUPPORT.md
Add product support policy and version mapping
> docs: Adding support policy and version mapping

- packages/fx-core/src/plugins/resource/frontend/dotnet/constants.ts
- packages/fx-core/src/plugins/resource/frontend/dotnet/plugin.ts
- packages/fx-core/tests/plugins/resource/dotnet/unit/localDebug.test.ts
E2E TEST: will add e2e test after feature complete.
> fix: get teams app id from solution

- packages/fx-core/src/common/template-utils/templatesUtils.ts
E2E TEST: https://github.com/OfficeDev/TeamsFx/blob/7d53f9c8ae3d0d0cb212d242e48b5785994084d3/packages/cli/tests/e2e/scaffold/AzureAppScaffold.tests.ts#L36
> fix(scaffold): do not overwrite existing git ignore

- packages/fx-core/src/plugins/resource/bot/v2/plugin.ts
- packages/fx-core/templates/plugins/resource/hosting/bicep/webapp/webappProvision.template.bicep
* use zip deploy need set SCM_SCRIPT_GENERATOR_ARGS
* insert enableAlwaysOn to bicep context
> chore: use zip deploy need set SCM_SCRIPT_GENERATOR_ARGS

- packages/api/review/teamsfx-api.api.md
- packages/api/src/utils/login.ts
1. Solving cd problems through `api` release of new version.
> chore: trigger cd pipeline

- packages/fx-core/src/plugins/resource/bot/v2/enum.ts
- packages/fx-core/src/plugins/resource/bot/v2/mapping.ts
- packages/fx-core/src/plugins/resource/bot/v2/plugin.ts
- packages/fx-core/templates/plugins/resource/hosting/bicep/botFunction/botFunctionProvision.template.bicep
E2E TEST: will add e2e test after feature complete.
> fix(bot): support deploying dotnet project

- packages/fx-core/src/common/azure-hosting/azureHosting.ts
- packages/fx-core/src/plugins/resource/bot/errors.ts
- packages/fx-core/src/plugins/resource/bot/index.ts
- packages/fx-core/src/plugins/resource/bot/v2/index.ts
- packages/fx-core/src/plugins/resource/bot/v2/plugin.ts
1. Need deploy does not work right.
2. Log message should be with component name.
3. Reuse v1 error handling and telemetry helper.
E2E TEST: no need
> fix(bot): fix some issue in bot plugin

- templates/bot/csharp/command-and-response/.gitignore
- templates/bot/csharp/notification-webapi/.gitignore
Add vs-style .gitignore.
For notification bot, ignore `.notification.localstore.json` as well.
> chore: add .gitignore

- packages/cli/tests/commonlib/m365Validator.ts
E2E TEST: https://github.com/OfficeDev/TeamsFx/actions/runs/2388916714
> fix(m365): fix manifest validator

- templates/bot/csharp/command-and-response/ProjectName.csproj.tpl
- templates/bot/csharp/default/ProjectName.csproj.tpl
- templates/bot/csharp/notification-webapi/ProjectName.csproj.tpl
- templates/tab/csharp/default/ProjectName.csproj.tpl
> chore: exclude build folder in dotnet project

- packages/vscode-extension/src/debug/prerequisitesHandler.ts
- packages/vscode-extension/src/telemetry/extTelemetryEvents.ts
Send all the check result when prerequisites check failed.
> fix(localdebug): send prerequisites check result when it failed

- packages/fx-core/src/plugins/resource/bot/plugin.ts
Remove duplicated messages.
https://dev.azure.com/msazure/Microsoft%20Teams%20Extensibility/_workitems/edit/14521921
> chore: update messages

- packages/vscode-extension/src/debug/prerequisitesHandler.ts
**Normal :** 
**Disable Node.js :**
**Disable Node.js + Azure Functons Core Tools :**
E2E TEST: N/A
> chore: fix order of prerequisite check

- packages/vscode-extension/src/commonlib/telemetry.ts
- packages/vscode-extension/src/telemetry/extTelemetry.ts
- packages/vscode-extension/test/unit/extension/extTelemetry.test.ts
Related bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/14583710
E2E TEST: N/A
> fix(vsc): missing correlation-id in deactivate event

- .azure-pipelines/apiscan.yml
> chore: add API scan for .NET SDK

- packages/fx-core/src/plugins/resource/appstudio/interfaces/IAppDefinition.ts
- packages/fx-core/src/plugins/resource/appstudio/plugin.ts
- packages/fx-core/src/plugins/resource/appstudio/utils/utils.ts
- packages/manifest/src/manifest.ts
- packages/manifest/test/index.test.ts
> fix: update graphconnector to app studio

- packages/vscode-extension/src/treeview/account/azureNode.ts
- packages/vscode-extension/src/treeview/account/subscriptionNode.ts
It happens when user has only 1 Azure subscription and it's auto selected.
Related: #5199
E2E TEST: N/A
> fix(vsc): infinite loop in treeview subscription display

- packages/fx-core/src/plugins/resource/bot/v2/mapping.ts
- packages/fx-core/tests/samples/migration/.fx/settings.json
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/14561201/
> chore(bot): convert get map method to throw error

- Localize/loc/cs/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/cs/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/de/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/de/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/es/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/es/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/fr/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/fr/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/it/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/it/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/ja/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/ja/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/ko/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/ko/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/pl/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/pl/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/pt-BR/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/pt-BR/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/ru/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/ru/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/tr/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/tr/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/zh-Hans/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/zh-Hans/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/zh-Hant/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/zh-Hant/packages/vscode-extension/package.nls.json.lcl
LEGO: Pull request from juno/hb_fd34cb3d-1ea5-4a7c-8a66-721a44a97af3_20220601152919218 to dev with localized lcls
> chore(localization): [LEGO] Pull request from juno/hb_fd34cb3d-1ea5-4a7c-8a66-721a44a97af3_20220601152919218 to dev

- packages/fx-core/src/common/tools.ts
- packages/fx-core/src/common/utils.ts
- packages/fx-core/src/core/FxCore.ts
- packages/fx-core/src/core/globalVars.ts
- packages/fx-core/src/core/middleware/projectSettingsLoader.ts
- packages/fx-core/src/plugins/resource/appstudio/constants.ts
- packages/fx-core/src/plugins/resource/appstudio/plugin.ts
- packages/fx-core/src/plugins/resource/appstudio/v3/index.ts
- packages/fx-core/src/plugins/solution/fx-solution/arm.ts
- packages/fx-core/tests/plugins/resource/appstudio/unit/scaffold.test.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/13874540
> chore(core): templates folder name upper case for VS

- packages/vscode-extension/package.json
E2E TEST: Already add test plan for this
> fix: hide preview aad when aad is not enabled, fix typo

- packages/fx-core/templates/plugins/resource/hosting/bicep/function/functionProvision.template.bicep
- packages/fx-core/tests/common/hosting/azureHosting.test.ts
- packages/fx-core/tests/common/hosting/expectedBicep/botFunctionProvisionModule.bicep
> fix(bot): support dotnet function

- packages/fx-core/src/plugins/resource/appstudio/index.ts
chore: change build package message to log
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/14668253
> chore: change build package message to log

- templates/bot/csharp/command-and-response/Commands/HelloWorldCommandHandler.cs.tpl
- templates/bot/csharp/command-and-response/Models/HelloWorldModel.cs.tpl
- templates/bot/csharp/notification-function-base/Models/NotificationDefaultModel.cs.tpl
- templates/bot/csharp/notification-trigger-http/NotifyHttpTrigger.cs.tpl
- templates/bot/csharp/notification-trigger-timer/NotifyTimerTrigger.cs.tpl
- templates/bot/csharp/notification-webapi/Controllers/NotificationController.cs.tpl
- templates/bot/csharp/notification-webapi/Models/NotificationDefaultModel.cs.tpl
Fix https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/14585055/
.NET bot template content change and NO breaking change to toolkit.
> chore: move card model to models folder

- packages/fx-core/src/plugins/resource/appstudio/interfaces/messagingExtensionCommand.ts
- packages/fx-core/src/plugins/resource/appstudio/interfaces/messagingExtensionCommandTaskInfo.ts
- packages/fx-core/src/plugins/resource/appstudio/utils/utils.ts
> fix: optional task info

- packages/fx-core/templates/plugins/resource/aad/auth/bot/README.md
fix bot crashing bug in node 16: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/14688021
> docs: add error hanlding for bot sso

- packages/cli/src/yargsCommand.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/14677485
E2E TEST:
> fix: duplicated env question

- packages/cli/src/cmds/preview/localTelemetryReporter.ts
- packages/fx-core/src/common/local/index.ts
- packages/fx-core/src/common/local/localTelemetryReporter.ts
- packages/fx-core/tests/common/local/localTelemetryReporter.test.ts
- packages/vscode-extension/src/debug/localTelemetryReporter.ts
- add telemetry utility in fx-core
> chore: add local debug telemetry utillity

- .github/workflows/lint-pr.yml
this action to add feature commits history once there any branch merge to main.
CLI feat commits: 
feat: check compatibility of Node.js and Azure Functions Core Tools (#5153) ad658149c
feat: use teamsFx add instead of teamsfx resource add and teamsfx capability add (#4610) 71159133a
feat(cli): support add capability for notification/command response bot (#4570) 445181843
feat: impl teamsfx add cicd (#4417) cacf4eae3
feat(m365): add teamsfx preview --m365-host for m365 app (#4389) 76ef8d3a1
feat(m365): add teamsfx new m365 command (#4331) 671202749
feat(notification): add cli preview for func hosted bot (#4326) ba10d0695
feat(cli): change `teamsfx manifest update` to `teamsfx deploy manifest` (#4200) e328214a7
feat(deps-checker): check func core tool for function hosted bot (#4183) …
> chore: display the feature history

- .github/workflows/lint-pr.yml
@microsoft/adaptivecards-tools	v1.0.1-rc.0
@microsoft/teamsfx-api	v0.20.1-rc.0
@microsoft/teamsfx-cli	v1.1.0-rc.0
@microsoft/teamsfx-core	v1.11.0-rc.0
@microsoft/teams-manifest	v0.0.5-rc.0
@microsoft/teamsfx	v1.0.1-rc.0
@microsoft/teamsfx-react	v1.0.1-rc.0
ms-teams-vscode-extension	v4.1.0-rc.0
CLI feat commits: 
feat: check compatibility of Node.js and Azure Functions Core Tools (#5153) ad658149c
feat: use teamsFx add instead of teamsfx resource add and teamsfx capability add (#4610) 71159133a
feat(cli): support add capability for notification/command response bot (#4570) 445181843
feat: impl teamsfx add cicd (#4417) cacf4eae3
feat(m365): add teamsfx preview --m365-host for m365 app (#4389) 76ef8d3a1
feat(m365): add teamsfx new m365 command (#4331) 671202749
feat(notification): add cli …
> chore: get prerelease version info merge to main

- packages/vscode-extension/src/commonlib/azureLogin.ts
- packages/vscode-extension/src/extension.ts
- packages/vscode-extension/src/globalVariables.ts
- packages/vscode-extension/src/handlers.ts
Save subscription information when user specifies subscription.
Related bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/14716183
E2E TEST: N/A
> fix(vsc): persistence of subscription info

- Localize/loc/cs/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/cs/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/de/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/es/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/es/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/fr/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/it/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/it/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/ja/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/ko/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/ko/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/pl/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/pl/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/pt-BR/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/ru/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/ru/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/tr/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/tr/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/zh-Hans/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/zh-Hant/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/zh-Hant/packages/vscode-extension/package.nls.json.lcl
- packages/fx-core/.nycrc
LEGO: Pull request from juno/hb_fd34cb3d-1ea5-4a7c-8a66-721a44a97af3_20220615144444045 to dev with localized lcls
> chore(localization): [LEGO] Pull request from juno/hb_fd34cb3d-1ea5-4a7c-8a66-721a44a97af3_20220615144444045 to dev

- packages/vscode-extension/src/debug/teamsfxTaskHandler.ts
- packages/vscode-extension/src/error.ts
Related bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/14483282/
E2E TEST: n/a
> fix: send error using sendTelemetryErrorEvent

- .azure-pipelines/CredScanSuppressions.json
- packages/server/src/apis.ts
- packages/server/src/providers/token/m365.ts
1.Update VS getStatus method.
2.Add cred white list.
> chore: update vs m365 getStatus

- .github/workflows/cd.yml
enable artifactErrorsFailBuild as true to fail the pipeline if bits not exist or upload fail
> chore: check artifact exists before uploading

- packages/fx-core/src/component/connection/azureFunctionConfig.ts
- packages/fx-core/src/component/connection/azureResourceConfig.ts
- packages/fx-core/src/component/connection/azureWebAppConfig.ts
- packages/fx-core/src/component/resource/azureFunction.ts
- packages/fx-core/src/component/resource/azureResource.ts
- packages/fx-core/src/component/resource/azureWebApp.ts
> chore(v3): deploy function hosting bot

- packages/fx-core/package-lock.json
- packages/fx-core/src/common/telemetry.ts
- packages/fx-core/src/component/projectSettingsManager.ts
- packages/fx-core/src/core/middleware/projectSettingsLoader.ts
Add telemetry to track the root cause of decryption error.
> chore(core): add telemetry when project id is filled

- packages/cli/src/yargsCommand.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/14704209
E2E TEST:
> fix: use getProjectConfigV3 instead

- packages/fx-core/src/component/resource/appManifest/appManifest.ts
- packages/fx-core/src/component/resource/appManifest/appStudio.ts
- packages/fx-core/src/component/workflow.ts
1. Hide confirm dialog when running action
2. Remove dialog show after create teams app
> chore(v3): refine UX

- packages/dotnet-sdk/CHANGELOG.md
- packages/dotnet-sdk/src/TeamsFx/Microsoft.TeamsFx.csproj
Related WIT: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/14786735
> chore(dotnet-sdk): bump version to 1.0.0

- packages/fx-core/src/common/utils.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/14778562
> chore(core): handle the case when fail to rename templates folder

- packages/server/package-lock.json
- packages/server/package.json
work item: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/14786741
> chore(server): upgrade server version to 1.0.0

- Localize/loc/cs/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/cs/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/de/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/de/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/es/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/es/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/fr/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/fr/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/it/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/it/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/ja/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/ja/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/ko/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/ko/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/pl/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/pl/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/pt-BR/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/pt-BR/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/ru/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/ru/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/tr/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/tr/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/zh-Hans/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/zh-Hans/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/zh-Hant/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/zh-Hant/packages/vscode-extension/package.nls.json.lcl
LEGO: Pull request from juno/hb_fd34cb3d-1ea5-4a7c-8a66-721a44a97af3_20220622144505480 to dev with localized lcls
> chore(localization): [LEGO] Pull request from juno/hb_fd34cb3d-1ea5-4a7c-8a66-721a44a97af3_20220622144505480 to dev

- Localize/loc/cs/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/de/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/es/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/fr/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/it/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/ja/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/ko/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/pl/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/pt-BR/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/ru/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/tr/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/zh-Hans/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/zh-Hant/packages/fx-core/resource/package.nls.json.lcl
LEGO: Pull request from juno/hb_fd34cb3d-1ea5-4a7c-8a66-721a44a97af3_20220626144249266 to dev with localized lcls
> chore(localization): [LEGO] Pull request from juno/hb_fd34cb3d-1ea5-4a7c-8a66-721a44a97af3_20220626144249266 to dev

- packages/fx-core/templates/plugins/resource/spfx/solution/README.md
This is to fix this bug https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/12664738
> docs: update spfx README to simplify sharepoint site construct

- packages/vscode-extension/package-lock.json
- packages/vscode-extension/package.json
- packages/vscode-extension/src/commonlib/telemetry.ts
- packages/vscode-extension/test/unit/extension/telemetry.test.ts
chore: upgrade vscode telemetry reporter to 0.6.2
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/14843052
> chore: upgrade vscode telemetry reporter to 0.6.2

- templates/bot/csharp/command-and-response/GettingStarted.txt
- templates/bot/csharp/default/GettingStarted.txt
- templates/bot/csharp/notification-function-base/GettingStarted.txt
- templates/bot/csharp/notification-webapi/GettingStarted.txt
- templates/tab/csharp/default/GettingStarted.txt
Update the target branch of this PR on behave of @zyxiaoyuer : https://github.com/OfficeDev/TeamsFx/pull/5404
work item: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/14827335
> docs: fix path for template folder in get started file

- packages/fx-core/resource/package.nls.json
- packages/fx-core/src/plugins/resource/apiconnector/depsHandler.ts
- packages/fx-core/src/plugins/resource/apiconnector/plugin.ts
- packages/fx-core/src/plugins/resource/apiconnector/questions.ts
- packages/fx-core/src/plugins/resource/apiconnector/telemetry.ts
- packages/fx-core/src/plugins/resource/apiconnector/utils.ts
- packages/fx-core/tests/plugins/resource/apiconnector/depsHandler.test.ts
Bug issue: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/14786815
> chore(api-connector): udpate the UI warning on version check

- packages/fx-core/src/plugins/resource/bot/resources/strings.ts
- packages/fx-core/src/plugins/resource/bot/v2/common.ts
Add ME to bot capabilities so that it can be found in telemetry.
BUG: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/14842386/
> chore(bot): add ME to bot capabilities

- packages/vscode-extension/src/handlers.ts
> fix: open readme for walkthrough app

- .github/workflows/cd.yml
- .github/workflows/cicd_test_trigger.yml
cherry-pick from dev branch d72020572e86cc78625e93ecf58866d87e5f7973
> chore: always notification server pipeline (#5411)

- packages/fx-core/src/plugins/resource/appstudio/plugin.ts
- packages/fx-core/tests/plugins/resource/appstudio/resources-multi-env/templates/appPackage/manifest.template.json
- packages/fx-core/tests/plugins/resource/appstudio/unit/build.test.ts
> chore: remove local settings and add siteEndpoint in render

- packages/function-extension/src/Microsoft.Azure.WebJobs.Extensions.TeamsFx.csproj
- packages/function-extension/src/TeamsFxBinding.cs
- packages/function-extension/tests/Microsoft.Azure.WebJobs.Extensions.TeamsFx.Tests/Microsoft.Azure.WebJobs.Extensions.TeamsFx.Tests.csproj
issue bug: 
https://dev.azure.com/mseng/VSIoT/_componentGovernance/721/alert/87122?typeId=129269
https://dev.azure.com/mseng/VSIoT/_componentGovernance/721/alert/87121?typeId=129269
> chore: upgrade deps version to fix Vulnerabilities issue

- packages/fx-core/src/core/downloadSample.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/14775825
> chore: add more context in error message for fetchSampleError

- packages/fx-core/src/plugins/resource/appstudio/constants.ts
- packages/fx-core/src/plugins/resource/appstudio/manifestTemplate.ts
- packages/fx-core/src/plugins/resource/appstudio/plugin.ts
Add placeholder for tab/bot valid domains, which is more transparent for user.
Test case:
1) Existing tab project, provision & debug
2) Existing bot project, provision & debug
3) Existing tab project, add bot feature
4) Create new tab app, provision & debug
5) Create new bot app, provision & debug
> fix: valid domain

- packages/vscode-extension/media/itp/itp.md
- packages/vscode-extension/package-lock.json
- packages/vscode-extension/src/handlers.ts
Related bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/14000411
> chore(vsc): fix doc link and ITP content

- packages/vscode-extension/src/progressHandler.ts
Related bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/14907278
> chore(vsc): support concurrent next operation in progress bar

- packages/cli/tests/e2e/manifest/provision.tests.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_sprints/taskboard/Teams%20Extensibility%20E2E%20Team/Microsoft%20Teams%20Extensibility/CY22-6.2?workitem=14916953
E2E test case passes: https://github.com/OfficeDev/TeamsFx/actions/runs/2634200524
> test: fix e2e case of provisioning manifest

- packages/fx-core/templates/plugins/resource/aad/auth/bot/README.md
@microsoft/teamsfx-cli	v1.0.2-rc.1
@microsoft/teamsfx-core	v1.12.1-rc.1
ms-teams-vscode-extension	v4.0.2-rc.1
> docs: update sample code for bot sso

- templates/bot/ts/default/package.json
- templates/bot/ts/m365/package.json
CLI BREAKING CHANGE: None
Extension-toolkit BREAKING CHANGE:  None
CLI feat commits: None
Extension-toolkit feat commits: None
Detail: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/14926169
Fix the watch script in PR https://github.com/OfficeDev/TeamsFx/pull/4872
E2E TEST: https://github.com/OfficeDev/TeamsFx-UI-Test/blob/328a68696f5a62d43251318c5fc46490bf44aad3/src/ui-test/localdebug/preview%40localdebug-notification-restify.test.ts#L12
> fix(bot): remove watch folder src in dev script

- packages/vscode-extension/CHANGELOG.md
- packages/vscode-extension/WHATISNEW.md
ms-teams-vscode-extension	v4.0.2-rc.1
> docs: Update Changelog

- packages/fx-core/src/plugins/resource/apiconnector/depsHandler.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/14916942
E2E TEST:
> fix: use sync functions in api-connection question

- packages/fx-core/templates/plugins/resource/aad/auth/bot/README.md
@microsoft/teamsfx-cli	v1.0.2-rc.2
@microsoft/teamsfx-core	v1.12.1-rc.2
ms-teams-vscode-extension	v4.0.2-rc.2
> docs: update sample code in bot sso readme

- packages/function-extension/src/Microsoft.Azure.WebJobs.Extensions.TeamsFx.csproj
- packages/function-extension/src/TeamsFxBinding.cs
This change fixes [this](https://dev.azure.com/mseng/VSIoT/_componentGovernance/721/alert/88758?typeId=158182) cg issue
> chore: revert JWT version to fix cg issue

- packages/fx-core/src/component/resource/appManifest/appStudio.ts
fixes https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/14926993
> chore: add log when provisioning manifest

- packages/server/src/serverConnection.ts
- packages/server/tests/client.ts
- packages/server/tests/serverConnections.test.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/14907141
> chore(server): add get question api

- templates/bot/ts/notification-function-base/messageHandler/function.json
- templates/bot/ts/notification-function-base/package.json
- templates/bot/ts/notification-function-base/tsconfig.json
- templates/bot/ts/notification-trigger-http/notifyHttpTrigger/function.json
- templates/bot/ts/notification-trigger-timer/notifyTimerTrigger/function.json
Fix: https://dev.azure.com/msazure/Microsoft%20Teams%20Extensibility/_workitems/edit/14959311
Add `rootDir` to tsconfig to make the output path fixed.
E2E TEST: N/A (covered by UI test)
> fix: add rootDir to func bot

- packages/fx-core/src/plugins/resource/cicd/utils/telemetry-helper.ts
https://dev.azure.com/msazure/Microsoft%20Teams%20Extensibility/_workitems/edit/14949173
> chore: use sendError for error telemetry cicd

- packages/fx-core/src/component/constants.ts
- packages/fx-core/src/component/core.ts
- packages/fx-core/src/component/resource/aadApp/actions/configure.ts
- packages/fx-core/src/component/resource/aadApp/actions/provision.ts
- packages/fx-core/src/component/resource/aadApp/actions/setApplication.ts
- packages/fx-core/src/component/resource/azureSql/actions/configure.ts
- packages/fx-core/src/component/resource/azureSql/actions/provision.ts
- packages/fx-core/src/plugins/resource/aad/aadAppManifestManager.ts
- packages/fx-core/templates/components/aadApp/manifest/aadApp.template.json
- packages/fx-core/tests/component/resource/azureSql/index.test.ts
- packages/fx-core/tests/component/workflow.test.ts
update aad for provision/setContext/configure
> chore(component): update aad

- packages/fx-core/src/common/deps-checker/internal/nodeChecker.ts
- packages/fx-core/src/plugins/resource/spfx/depsChecker/generatorChecker.ts
- packages/fx-core/src/plugins/resource/spfx/depsChecker/yoChecker.ts
- packages/fx-core/src/plugins/resource/spfx/utils/constants.ts
- packages/fx-core/templates/plugins/resource/spfx/solution/README.md
> feat: upgrade spfx version to 1.15

- packages/fx-core/src/component/constants.ts
- packages/fx-core/src/component/core.ts
- packages/fx-core/src/component/feature/keyVault.ts
- packages/fx-core/src/component/feature/sql.ts
- packages/fx-core/src/component/resource/keyVault.ts
- packages/fx-core/templates/bicep/keyVault.provision.orchestration.bicep
> chore(component): update key vault

- packages/cli/tests/e2e/multienv/TestRemoteHappyPathSPFx.tests.ts
- packages/cli/tests/e2e/spfx/CreateSPFxProject.tests.ts
- packages/cli/tests/e2e/spfx/CreateSPFxProjectMinimalFramework.tests.ts
- packages/cli/tests/e2e/spfx/CreateSPFxProjectWithoutFramework.tests.ts
Fix e2e test fail https://github.com/OfficeDev/TeamsFx/runs/7375396587?check_suite_focus=true
> test: fix e2e test fail due to spfx upgrade to 1.15

- packages/vscode-extension/src/commonlib/azureLogin.ts
- packages/vscode-extension/src/commonlib/codeFlowLogin.ts
- packages/vscode-extension/src/commonlib/m365Login.ts
> chore: fix login telemetry type

- packages/fx-core/src/plugins/solution/fx-solution/debug/util/telemetry.ts
- packages/fx-core/src/plugins/solution/fx-solution/utils/depsChecker/bicepChecker.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/14949205
> chore(core): send telemetry api fix

- packages/fx-core/src/index.ts
- packages/vscode-extension/src/codeLensProvider.ts
- packages/vscode-extension/src/hoverProvider.ts
fix: 12615502
The state has been converted to v3, but the key is not. So cannot find corresponding value.
> fix: codelens with v3 key and state

- packages/fx-core/src/component/resource/appManifest/appManifest.ts
> fix(v3): notification bot should not have command

- packages/fx-core/tests/common/deps-checker/cases/all.it.ts
- packages/fx-core/tests/common/deps-checker/cases/dotnet.it.ts
- packages/fx-core/tests/common/deps-checker/cases/funcTool.it.ts
- packages/fx-core/tests/common/deps-checker/utils/dotnet.ts
The Environment Checker Integration Test was failed.
Failed case: https://github.com/OfficeDev/TeamsFx/runs/6620959276?check_suite_focus=true
> test(deps-checker): fix deps checker test case

- packages/fx-core/src/plugins/resource/appstudio/plugin.ts
> fix: local debug failed for the first time

- packages/vscode-extension/src/controls/SampleGallery.scss
- packages/vscode-extension/src/controls/SampleGallery.tsx
- packages/vscode-extension/src/controls/sampleDetailPage.scss
ADO: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/13738156
Before:
After:
ADO: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/14431408
After:
> chore: update sample gallery styles

- packages/fx-core/src/plugins/resource/frontend/dotnet/plugin.ts
- packages/fx-core/src/plugins/resource/frontend/dotnet/resources/templateInfo.ts
- templates/package.json
1. add non sso tab template for dotnet in package.json in template/
2. update fe plugin to enable scaffold non sso tab template for dotnet
> perf: enable non sso tab template for dotnet

- packages/vscode-extension/src/handlers.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/14925421
> chore(localdebug): show output channel when provisioning

- packages/vscode-extension/src/extension.ts
- packages/vscode-extension/src/telemetry/extTelemetryEvents.ts
ms-teams-vscode-extension	v4.0.3-rc.1
> chore(vsc): revert changes of adding telemetry for activation (#5545)

- .github/fabricbot.json
update message when adding no-activity label.
> chore(fabricbot): update

- Localize/loc/cs/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/cs/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/de/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/de/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/es/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/es/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/fr/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/fr/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/it/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/it/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/ja/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/ja/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/ko/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/ko/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/pl/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/pl/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/pt-BR/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/pt-BR/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/ru/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/ru/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/tr/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/tr/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/zh-Hans/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/zh-Hans/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/zh-Hant/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/zh-Hant/packages/vscode-extension/package.nls.json.lcl
LEGO: Pull request from juno/hb_fd34cb3d-1ea5-4a7c-8a66-721a44a97af3_20220727203202443 to dev with localized lcls
> chore(localization): [LEGO] Pull request from juno/hb_fd34cb3d-1ea5-4a7c-8a66-721a44a97af3_20220727203202443 to dev

- Localize/loc/cs/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/cs/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/de/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/de/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/es/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/es/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/fr/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/fr/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/it/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/it/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/ja/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/ja/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/ko/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/ko/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/pl/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/pl/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/pt-BR/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/pt-BR/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/ru/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/ru/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/tr/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/tr/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/zh-Hans/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/zh-Hans/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/zh-Hant/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/zh-Hant/packages/vscode-extension/package.nls.json.lcl
LEGO: Pull request from juno/hb_fd34cb3d-1ea5-4a7c-8a66-721a44a97af3_20220727211715608 to dev with localized lcls
> chore(localization): [LEGO]Pull request from juno/hb_fd34cb3d-1ea5-4a7c-8a66-721a44a97af3_20220727211715608 to dev

- packages/cli/package.json
- packages/cli/tests/e2e/solution/ProvisionWithLoggedOutSubscriptionInfo.tests.ts
E2E TEST: https://github.com/OfficeDev/TeamsFx/runs/7553664121?check_suite_focus=true
subscriptionInfo.json will only be created after selecting a subscription.
> chore: fix e2e test

- packages/fx-core/src/plugins/solution/fx-solution/constants.ts
- packages/fx-core/src/plugins/solution/fx-solution/v2/executeUserTask.ts
- packages/server/src/apis.ts
- packages/server/src/serverConnection.ts
- packages/server/tests/serverConnections.test.ts
1. Allow language == csharp in add sso checks
2. Add api in server to support add sso command in VS
> perf: support add sso in core and server

- templates/bot/ts/command-and-response/package.json
- templates/bot/ts/command-and-response/tsconfig.json
- templates/bot/ts/default/package.json
- templates/bot/ts/default/tsconfig.json
- templates/bot/ts/m365/package.json
- templates/bot/ts/m365/tsconfig.json
- templates/bot/ts/notification-function-base/package.json
- templates/bot/ts/notification-function-base/tsconfig.json
- templates/bot/ts/notification-restify/package.json
- templates/bot/ts/notification-restify/tsconfig.json
- templates/function-base/ts/default/package.json
- templates/function-base/ts/default/tsconfig.json
[https://github.com/OfficeDev/TeamsFx/issues/4953#issuecomment-1120979504](https://github.com/OfficeDev/TeamsFx/issues/4953#issuecomment-1120979504)
Update typescript and ts-node version, and remove skip lib check.
> chore: update ts and ts-node version

- packages/fx-core/src/component/debug.ts
> fix: generate watch bot task

- packages/fx-core/src/component/debug.ts
- packages/fx-core/src/component/feature/bot.ts
- packages/fx-core/src/component/feature/tab.ts
- packages/fx-core/src/component/resource/appManifest/appManifest.ts
- packages/fx-core/templates/bicep/azureWebApp.provision.module.bicep
- packages/fx-core/templates/bicep/azureWebApp.provision.orchestration.bicep
1. Restore bot id and password to local env file
2. Add valid domain to app manifest for both bot and tab
> chore(v3): fix bot local debug

- packages/fx-core/src/plugins/solution/fx-solution/v3/provision.ts
- packages/fx-core/tests/component/workflow.test.ts
- packages/fx-core/tests/plugins/solutionv3/solution.provision.test.ts
Keep switching subscription in this release.
> chore: enable feature back for switching subscription

- packages/fx-core/src/component/feature/keyVault.ts
- packages/fx-core/src/component/feature/sso.ts
- packages/fx-core/src/component/middleware/actionExecutionMW.ts
1. update key-vault telemetry
2. update sso auth files condition
> chore(componentize): update key-vault telemetry

- .github/workflows/cicd_test_trigger.yml
- packages/cli/package-lock.json
- packages/cli/package.json
- packages/vscode-extension/package-lock.json
- packages/vscode-extension/package.json
@microsoft/teamsfx-cli	v1.0.4-rc.0
ms-teams-vscode-extension	v4.0.4-rc.0
> chore(release): update release versions

- packages/cli/.nycrc
- packages/cli/package-lock.json
- packages/cli/src/activate.ts
- packages/cli/src/cmds/FeatureAddBase.ts
- packages/cli/src/cmds/capability.ts
- packages/cli/src/cmds/index.ts
- packages/cli/src/cmds/resource.ts
- packages/cli/src/utils.ts
- packages/cli/tests/unit/cmds/capability.tests.ts
- packages/cli/tests/unit/cmds/resource.tests.ts
- packages/cli/tests/unit/utils.tests.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/15132712
E2E TEST: https://github.com/OfficeDev/TeamsFx/actions/runs/2793898799 the failures are same with before.
> refactor(cli): resource add part

- packages/fx-core/resource/package.nls.json
- packages/fx-core/src/plugins/resource/aad/permissions/permissions.json
- Update permissions.json file to address these bugs: 
- [Bug 15127844](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/15127844)
- https://github.com/OfficeDev/TeamsFx/issues/4514
- Update error message to tell user to use uuid instead
> perf: sync and update permissions.json file

- packages/dotnet-sdk/src/TeamsFx.Test/Microsoft.TeamsFx.Test.csproj
- packages/dotnet-sdk/src/TeamsFx/Microsoft.TeamsFx.csproj
Related issue: 
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/14948214
> chore(dotnet-sdk): upgrade dependencies

- templates/bot/js/command-and-response/README.md
- templates/bot/js/notification-function-base/README.md
- templates/bot/js/notification-restify/README.md
- templates/bot/ts/command-and-response/README.md
- templates/bot/ts/notification-function-base/README.md
- templates/bot/ts/notification-restify/README.md
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/15115214/
To provide guidance link to *Installation and Uninstallation*. Wiki is already updated.
> chore: adjust command and notification readme

- packages/vscode-extension/package.nls.json
- packages/vscode-extension/src/handlers.ts
@microsoft/teamsfx-cli	v1.0.4-rc.1
ms-teams-vscode-extension	v4.0.4-rc.1
> fix(vsc): create project experiment blocked issue

- docs/sdk/teamsfx.md
- docs/sdk/teamsfx.notificationtargettype.md
- packages/sdk/review/teamsfx.api.md
- packages/sdk/src/conversation/interface.ts
- packages/sdk/src/conversation/notification.browser.ts
- packages/sdk/src/conversation/notification.ts
- packages/sdk/src/conversation/utils.ts
- packages/sdk/test/unit/node/conversation/notification.spec.ts
- packages/sdk/test/unit/node/conversation/utils.spec.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/15116479/
This is the SDK changes.
Template changes will in later PR after this is merged (new SDK version generated)
> chore: expose notification target type as enum

- packages/adaptivecards-tools-sdk/package.json
fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/15204137/
E2E TEST: none
> fix: move @type/react to devDependencies

- packages/adaptivecards-tools-sdk/package.json
Reverts OfficeDev/TeamsFx#5756
E2E TEST: none
> fix: Revert "fix: move @type/react to devDependencies"

- packages/api/review/teamsfx-api.api.md
- packages/api/src/schemas/envConfig.json
- packages/api/src/schemas/envConfig.ts
- packages/fx-core/src/component/resource/appManifest/constants.ts
- packages/fx-core/src/core/environment.ts
- packages/fx-core/src/plugins/resource/appstudio/constants.ts
- packages/fx-core/tests/core/environment.test.ts
for bug: 15132432
Extend config to include following value customization for manifest:
manifest.description.short 
manifest.description.full 
manifest.icon.color 
manifest.icon.outline
> chore: update manifest config

- packages/fx-core/src/common/local/localEnvManager.ts
- packages/fx-core/src/common/local/projectSettingsHelper.ts
- packages/fx-core/src/component/core.ts
- packages/fx-core/src/component/debug.ts
- packages/fx-core/src/component/envManager.ts
- packages/fx-core/src/component/migrate.ts
- packages/fx-core/src/core/FxCore.ts
- packages/fx-core/src/core/middleware/projectSettingsLoader.ts
- packages/fx-core/src/plugins/solution/fx-solution/debug/provisionLocal.ts
- packages/fx-core/src/plugins/solution/fx-solution/debug/scaffolding.ts
- packages/fx-core/tests/common/local/localEnvManager.test.ts
- packages/fx-core/tests/component/debug.test.ts
- packages/fx-core/tests/plugins/solution/debug/solution.debug.provisionLocal.test.ts
1. unify project settings loader entry
2. create local env when init a project
3. unify setupLocalEnvironment, confLocalEnvironment, scaffoldLocalDebugSettings
> chore(v3): fix and improve debug

- packages/fx-core/src/plugins/resource/bot/errors.ts
> chore(bot): print detailed App studio error msg from response

- packages/fx-core/resource/package.nls.json
- packages/fx-core/src/component/core.ts
- packages/fx-core/src/core/middleware/envInfoWriter.ts
- packages/fx-core/src/plugins/solution/fx-solution/arm.ts
- packages/fx-core/src/plugins/solution/fx-solution/constants.ts
- packages/fx-core/src/plugins/solution/fx-solution/utils/backupFiles.ts
- packages/fx-core/src/plugins/solution/fx-solution/utils/util.ts
- packages/fx-core/src/plugins/solution/fx-solution/v2/provision.ts
- packages/fx-core/src/plugins/solution/fx-solution/v2/utils.ts
- packages/fx-core/tests/component/workflow.test.ts
- packages/fx-core/tests/constants.ts
- packages/fx-core/tests/plugins/solution/solution.backupFiles.test.ts
- packages/fx-core/tests/plugins/solution/solution.provision.test.ts
- packages/fx-core/tests/plugins/solution/solution.util.test.ts
- Backup files that will be update when switch accounts.
- Reset last deployment time if switching subscription.
> chore: backup file

- packages/fx-core/src/plugins/solution/fx-solution/constants.ts
- packages/fx-core/src/plugins/solution/fx-solution/v2/executeUserTask.ts
- packages/fx-core/templates/plugins/resource/aad/auth/tab/README.txt
- packages/fx-core/templates/plugins/resource/aad/auth/tab/csharp/GetUserProfile.razor
- packages/fx-core/tests/plugins/solution/solution.usertask.test.ts
- templates/tab/csharp/non-sso/appsettings.Development.json
- templates/tab/csharp/non-sso/appsettings.json
Add sso step and sample: https://github.com/KennethBWSong/AddSsoDotnet/pull/1
> perf: add sample code and readme for add sso in c# tab projects

- packages/fx-core/src/common/telemetry.ts
- packages/fx-core/src/component/core.ts
- packages/fx-core/src/plugins/solution/fx-solution/constants.ts
- packages/fx-core/src/plugins/solution/fx-solution/solution.ts
- packages/fx-core/src/plugins/solution/fx-solution/utils/util.ts
- packages/fx-core/src/plugins/solution/fx-solution/v2/provision.ts
- packages/fx-core/src/plugins/solution/fx-solution/v2/provisionLocal.ts
- packages/fx-core/src/plugins/solution/fx-solution/v2/utils.ts
- packages/fx-core/tests/plugins/solution/solution.provision.test.ts
- telemetry for checking tenant when local debugging
- telemetry for confirming provision result
> chore: telemetry when switch accounts

- packages/cli/src/prompts/customizedCheckboxPrompt.ts
- packages/cli/src/prompts/customizedListPrompt.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/15171682
E2E TEST: This can only be tested manually.
> fix: prompt issue

- packages/fx-core/src/plugins/resource/apiconnector/questions.ts
- packages/vscode-extension/package-lock.json
1. https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/15116458
2. update the vscode-extension package-lock.json
> chore: forget last value in question

- packages/vscode-extension/src/commonlib/m365Login.ts
- packages/vscode-extension/src/telemetry/extTelemetryEvents.ts
add telemetry for this event:
for bug: 15153444
> chore: add telemetry event for sign in popup

- packages/fx-core/src/common/constants.ts
- packages/fx-core/src/core/globalVars.ts
- packages/fx-core/src/plugins/solution/fx-solution/v2/provision.ts
- packages/fx-core/src/plugins/solution/fx-solution/v2/utils.ts
- packages/fx-core/tests/component/workflow.test.ts
- packages/fx-core/tests/plugins/solution/solution.provision.test.ts
- Remove feature flag of switch account for local debug
> chore: remove feature flag

- templates/bot/js/notification-function-base/README.md
- templates/bot/js/notification-function-base/src/internal/messageHandler.js
- templates/bot/js/notification-function-base/src/internal/responseWrapper.js
- templates/bot/js/notification-restify/README.md
- templates/bot/js/notification-restify/src/index.js
- templates/bot/js/notification-trigger-http/src/httpTrigger.js
- templates/bot/js/notification-trigger-timer/src/timerTrigger.js
- templates/bot/ts/notification-function-base/README.md
- templates/bot/ts/notification-function-base/src/internal/messageHandler.ts
- templates/bot/ts/notification-function-base/src/internal/responseWrapper.ts
- templates/bot/ts/notification-restify/README.md
- templates/bot/ts/notification-restify/src/index.ts
- templates/bot/ts/notification-trigger-http/src/httpTrigger.ts
- templates/bot/ts/notification-trigger-timer/src/timerTrigger.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/15116479/
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/15204244/
- Adjust NotificationTargetType as enum to follow latest SDK
- Fix error log to keep compatibility with latest Azure Functions Core Tools
> chore: polish notification bot template

- packages/fx-core/src/component/code/spfxTabCode.ts
- packages/fx-core/src/component/core.ts
- packages/fx-core/src/plugins/solution/fx-solution/v2/executeUserTask.ts
- packages/fx-core/src/plugins/solution/fx-solution/v2/getQuestions.ts
- packages/fx-core/tests/plugins/solution/solution.usertask.test.ts
> feat: run yeoman cli to add webpart when user select spfx for add feature

- packages/sdk/CONTRIBUTING.md
E2E: NA
Add more comments to the contribute.md when preparing SDK_INTEGRATION_TEST_API_CERTPROVIDER.
> docs(sdk): update sdk contribute.md

- packages/fx-core/src/component/resource/appManifest/appManifest.ts
> chore: success message for build

- packages/fx-core/src/component/debug.ts
Fix bug: 
15245147
15246797
Introduced by v3 refactor
> fix: site endpoint and domain key

- packages/fx-core/src/component/migrate.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/15279352
> chore(v3): project settings migration

- packages/fx-core/src/common/deps-checker/constant/telemetry.ts
- packages/vscode-extension/src/debug/depsChecker/vscodeHelper.ts
- packages/vscode-extension/test/extension/handlers.test.ts
send checker skipped info in the telemetry
> chore: send checker skipped info in the telemetry

- packages/cli/src/cmds/preview/constants.ts
- packages/fx-core/src/plugins/solution/fx-solution/v2/provision.ts
- packages/vscode-extension/src/debug/prerequisitesHandler.ts
The doc (https://github.com/OfficeDev/TeamsFx/pull/5798) is still in review by PM but the aka.ms link has been created. updating the link now.
> chore: update link

- docs/fx-core/spfx-help.md
- docs/vscode-extension/envchecker-help.md
- packages/fx-core/src/common/deps-checker/internal/nodeChecker.ts
- packages/fx-core/src/plugins/resource/spfx/utils/constants.ts
- packages/fx-core/templates/plugins/resource/spfx/solution/README.md
ADO: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/15263893?src=WorkItemMention&src-action=artifact_link
> chore: update supported node version for spfx

- packages/cli/package-lock.json
- packages/cli/package.json
- packages/server/package.json
- packages/vscode-extension/package-lock.json
- packages/vscode-extension/package.json
@microsoft/teamsfx-cli	v1.0.5-rc.0
ms-teams-vscode-extension	v4.0.5-rc.0
> chore(release): manual bump up version

- packages/fx-core/templates/plugins/resource/hosting/bicep/webapp/webappConfiguration.template.bicep
- packages/fx-core/tests/common/hosting/azureAppServiceHosting.test.ts
- packages/fx-core/tests/common/hosting/expectedBicep/webAppConfigModuleForVS.bicep
@microsoft/teamsfx-cli	v1.0.5-rc.1
@microsoft/teamsfx-core	v1.15.0-rc.1
ms-teams-vscode-extension	v4.0.5-rc.1
> perf: fix bot bicep

- packages/fx-core/src/component/core.ts
- packages/fx-core/tests/component/core.test.ts
> fix(v3): deploy failed with message Working directory is missing

- packages/fx-core/src/common/local/localEnvManager.ts
- packages/fx-core/src/common/localStateProvider.ts
- packages/fx-core/src/component/debug.ts
- packages/fx-core/src/component/resource/appManifest/appStudio.ts
- packages/fx-core/src/core/environment.ts
- packages/fx-core/src/core/middleware/envInfoLoader.ts
- packages/fx-core/src/core/middleware/envInfoLoaderV3.ts
- packages/fx-core/tests/common/local/localEnvManager.test.ts
- packages/fx-core/tests/component/resource/appManifest/index.test.ts
- packages/fx-core/tests/core/core.test.ts
- packages/fx-core/tests/core/environment.test.ts
- packages/fx-core/tests/core/hooks.test.ts
- packages/fx-core/tests/core/middleware/EnvInfoMW.test.ts
- packages/fx-core/tests/core/other.test.ts
@microsoft/teamsfx-cli	v1.0.5-rc.2
@microsoft/teamsfx-core	v1.15.0-rc.2
ms-teams-vscode-extension	v4.0.5-rc.2
> chore(debug): hotfix debug on main

- packages/fx-core/src/component/code/spfxTabCode.ts
ADO: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/15323744
E2E TEST:  will add UT later
> fix: update readme file in spfx

- packages/fx-core/src/plugins/solution/fx-solution/utils/backupFiles.ts
- packages/fx-core/tests/plugins/solution/solution.backupFiles.test.ts
- add .backup folder in gitignore
E2E TEST: N/A
> fix: add .backup folder in gitignore

- packages/vscode-extension/CHANGELOG.md
- packages/vscode-extension/WHATISNEW.md
@microsoft/teamsfx-cli	v1.0.5-rc.2
@microsoft/teamsfx-core	v1.15.0-rc.2
ms-teams-vscode-extension	v4.0.5-rc.2
> docs: update changelog and whatsnew

- packages/cli/src/cmds/account.ts
- packages/cli/src/cmds/preview/constants.ts
- packages/cli/src/cmds/preview/errors.ts
- packages/cli/src/cmds/preview/preview.ts
- packages/cli/src/commonlib/common/constant.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/15346029
E2E TEST: only change the strings.
> fix(cli): replace m365 to Microsoft 365

- templates/bot/ts/command-and-response/package.json
> fix: update version of botbuilder for command bot

- packages/fx-core/src/component/resource/botService.ts
- packages/fx-core/src/plugins/resource/bot/errors.ts
- packages/fx-core/tests/component/resource/botService.test.ts
> fix(v3): bot plugin error is wrapped twice in v3

- packages/server/package-lock.json
- packages/server/package.json
> chore: bump up server version to trigger release

- packages/fx-core/src/component/feature/bot.ts
- packages/fx-core/tests/component/feature/bot.test.ts
> fix: add message extension over bot project 

- packages/fx-core/src/component/provisionUtils.ts
- packages/fx-core/src/plugins/solution/fx-solution/utils/ResourceGroupHelper.ts
- packages/fx-core/src/plugins/solution/fx-solution/v2/provision.ts
- packages/fx-core/tests/component/provisionUtils.test.ts
- packages/fx-core/tests/component/workflow.test.ts
- packages/fx-core/tests/plugins/solution/solution.provision.test.ts
- provision with config file containing azure parameters 
- if provision with cli parameters, we will take the value provided here
- if not, then we will first take the value provided in the config file.
E2E TEST: https://github.com/OfficeDev/TeamsFx/actions/runs/2946235954
> feat: provsion with config

- packages/fx-core/templates/plugins/resource/aad/auth/bot/README.txt
- packages/fx-core/templates/plugins/resource/webapp/bicep/webappConfiguration.template.bicep
- packages/fx-core/tests/plugins/resource/dotnet/unit/arm.test.ts
@microsoft/teamsfx-cli	v1.0.6-rc.0
@microsoft/teamsfx-core	v1.15.1-rc.0
ms-teams-vscode-extension	v4.0.6-rc.0
> fix(sso): update bicep for tab for dotnet

- .github/scripts/sync-version.js
> chore: match teamsfx-react version pattern in sync-version.js

- packages/cli/tests/e2e/commonUtils.ts
Bot bicep parameter changed, update test case to set SKU correctly
> test: fix max free quota error for bot related test cases

- packages/cli/tests/e2e/apim/CanDeployToCustomizedRg.tests.ts
- packages/cli/tests/e2e/bot/CanDeployToCustomizedRg.tests.ts
- packages/cli/tests/e2e/commonUtils.ts
- packages/cli/tests/e2e/frontend/CanDeployToCustomizedRg.tests.ts
- packages/cli/tests/e2e/function/CanDeployToCustomizedRg.tests.ts
Some bicep file name and content was changed, fix custom bicep test cases.
> test: fix custom bicep test cases due to bicep content change

- packages/cli/src/cmds/preview/preview.ts
- packages/fx-core/src/common/local/index.ts
- packages/fx-core/src/common/local/localSettingsHelper.ts
- packages/fx-core/tests/common/local/localSettingsHelper.test.ts
- packages/server/src/serverConnection.ts
- packages/vscode-extension/src/debug/commonUtils.ts
Part of https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/15369970
Tested in VS
> refactor: prepare utility for VS localdebug telemetry fix

- packages/cli/tests/e2e/command/deployWithWrongPluginName.tests.ts
E2E TEST: https://github.com/OfficeDev/TeamsFx/actions/runs/2960790230
> test: deploy name test case

- packages/cli/tests/e2e/aad/aadGetAppError.tests.ts
Success run: https://github.com/OfficeDev/TeamsFx/actions/runs/2961113227
> test: fix e2e test

- packages/vscode-extension/package-lock.json
- packages/vscode-extension/package.json
related issue: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/15395521
E2E TEST: N/A
> fix(vsc): remove node-sass

- Localize/loc/cs/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/cs/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/de/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/de/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/es/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/es/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/fr/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/fr/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/it/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/it/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/ja/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/ja/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/pl/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/pl/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/pt-BR/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/pt-BR/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/ru/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/ru/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/tr/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/tr/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/zh-Hant/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/zh-Hant/packages/vscode-extension/package.nls.json.lcl
LEGO: Pull request from juno/hb_fd34cb3d-1ea5-4a7c-8a66-721a44a97af3_20220831144255220 to dev with localized lcls
> chore(localization): [LEGO] Pull request from juno/hb_fd34cb3d-1ea5-4a7c-8a66-721a44a97af3_20220831144255220 to dev

- packages/fx-core/src/component/debug.ts
- packages/fx-core/tests/component/debug.test.ts
E2E TEST: no e2e test for local debug
> fix: update bot state key in local debug

- packages/vscode-extension/package.nls.json
- packages/vscode-extension/src/debug/constants.ts
- packages/vscode-extension/src/debug/prerequisitesHandler.ts
- packages/vscode-extension/src/debug/taskTerminal/baseTaskTerminal.ts
- packages/vscode-extension/src/debug/taskTerminal/prerequisiteTaskTerminal.ts
- packages/vscode-extension/src/handlers.ts
show task error in output and notification
Updated:
> chore(localdebug): show task error in output and notification

- packages/fx-core/templates/bicep/azureFunction.provision.module.bicep
- packages/fx-core/templates/bicep/azureWebApp.provision.module.bicep
E2E TEST: https://github.com/OfficeDev/TeamsFx/blob/9a3dcccb95e84cb4102dae62d267851ded615702/packages/cli/tests/e2e/bot/NotificationBotHappyPathCommon.v3.ts#L21
> fix: web app should be always on when hosting bot

- packages/fx-core/src/common/constants.ts
- packages/fx-core/src/common/featureFlags.ts
- packages/fx-core/src/component/questionV3.ts
- packages/fx-core/src/core/question.ts
- packages/fx-core/tests/component/questionv3.test.ts
- packages/fx-core/tests/core/question.test.ts
> chore: add workflow bot feature flag

- packages/fx-core/src/component/code/spfxTabCode.ts
- packages/fx-core/src/component/feature/spfx.ts
- packages/fx-core/src/component/questionV3.ts
- packages/fx-core/tests/component/feature/spfx.test.ts
- packages/fx-core/tests/plugins/resource/spfx/unit/scaffold.test.ts
When 'template' persisted in .yo-rc.json, don't ask for framework when add feature;
When 'template' not persisted in .yo-rc.json, ask for framework when add feature;
> chore: ask user for framework when add feature if no yo-rc.json

- packages/fx-core/tests/common/local/localEnvManager.test.ts
Mock `waitSeconds` to reduce test time in *localEnvManager*.
> chore: local test time

- packages/fx-core/src/component/questionV3.ts
- packages/fx-core/tests/component/debugHandler/localEnvProvider.test.ts
- packages/fx-core/tests/component/questionv3.test.ts
> fix: make features order and condition consistent with v2

- Localize/loc/cs/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/cs/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/de/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/de/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/fr/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/fr/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/it/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/it/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/ja/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/ja/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/ko/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/ko/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/pl/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/pl/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/pt-BR/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/pt-BR/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/ru/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/ru/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/tr/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/tr/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/zh-Hans/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/zh-Hans/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/zh-Hant/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/zh-Hant/packages/vscode-extension/package.nls.json.lcl
LEGO: Pull request from juno/hb_fd34cb3d-1ea5-4a7c-8a66-721a44a97af3_20220904144633561 to dev with localized lcls
> chore(localization): [LEGO] Pull request from juno/hb_fd34cb3d-1ea5-4a7c-8a66-721a44a97af3_20220904144633561 to dev

- packages/fx-core/src/component/core.ts
- packages/fx-core/src/component/feature/apiconnector/apiConnector.ts
- packages/fx-core/tests/component/components.test.ts
- move apiConnector.ts to ./apiconnector folder
E2E TEST: https://github.com/OfficeDev/TeamsFx/actions/runs/2990736017
> chore: move api connector file

- templates/bot/js/workflow/.gitignore
- templates/bot/js/workflow/README.md
- templates/bot/js/workflow/package.json
- templates/bot/js/workflow/src/adaptiveCards/doStuffActionResponse.json
- templates/bot/js/workflow/src/adaptiveCards/helloworldCommandResponse.json
- templates/bot/js/workflow/src/cardActions/doStuffActionHandler.js
- templates/bot/js/workflow/src/commands/helloworldCommandHandler.js
- templates/bot/js/workflow/src/index.js
- templates/bot/js/workflow/src/internal/initialize.js
- templates/bot/ts/workflow/README.md
- templates/bot/ts/workflow/src/index.ts
- templates/package.json
Added and enabled JavaScript workflow flow bot for both VSC/CLI.
E2E TEST: N/A
> chore: add workflow bot js template

- packages/vscode-extension/src/extension.ts
- packages/vscode-extension/src/handlers.ts
- packages/vscode-extension/test/extension/handlers.test.ts
Get dotnet path for azure function binding installation.
> chore(localdebug): add command:fx-extension.get-dotnet-path

- packages/fx-core/src/component/resource/appManifest/appManifest.ts
- packages/fx-core/src/plugins/resource/appstudio/utils/telemetry.ts
App studio client will send telemetry for API failure.
> fix: app studio telemetry v3

- templates/package.json
> chore: fix workflow bot js template path

- packages/fx-core/src/component/resource/botService.ts
Respect existing bot add in config first.
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/15457044
> chore: fix existing bot add for v3

- packages/fx-core/resource/package.nls.json
- packages/fx-core/src/component/code/appSettingUtils.ts
- packages/fx-core/src/component/provisionUtils.ts
- packages/fx-core/src/component/utils.ts
- packages/fx-core/src/plugins/solution/fx-solution/constants.ts
- packages/fx-core/src/plugins/solution/fx-solution/solution.ts
- packages/fx-core/src/plugins/solution/fx-solution/utils/backupFiles.ts
- packages/fx-core/src/plugins/solution/fx-solution/utils/util.ts
- packages/fx-core/src/plugins/solution/fx-solution/v2/provision.ts
- packages/fx-core/src/plugins/solution/fx-solution/v2/provisionLocal.ts
- packages/fx-core/src/plugins/solution/fx-solution/v2/utils.ts
- packages/fx-core/tests/component/code/appSettingsUtils.test.ts
- packages/fx-core/tests/plugins/solution/solution.backupFiles.test.ts
- packages/fx-core/tests/plugins/solution/solution.util.test.ts
- back up the old appsettings.development.json
- update bot related and aad related values in appsettings.development.json
E2E TEST: N/A
> fix: update appsettings.development.json if switch m365 tenant

- Localize/loc/ru/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/ru/packages/vscode-extension/package.nls.json.lcl
LEGO: Pull request from juno/hb_fd34cb3d-1ea5-4a7c-8a66-721a44a97af3_20220907144326096 to dev with localized lcls
> chore(localization): [LEGO] Pull request from juno/hb_fd34cb3d-1ea5-4a7c-8a66-721a44a97af3_20220907144326096 to dev

- packages/fx-core/src/component/resource/botService.ts
save bot aad configs during post provision.
> chore: fix existing bot aad remote

- packages/fx-core/src/component/debug.ts
Fix https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/15484873
> chore(localdebug): fix tab missing envs

- Localize/loc/cs/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/cs/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/de/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/de/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/es/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/es/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/fr/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/fr/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/it/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/it/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/ja/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/ja/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/ko/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/ko/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/pl/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/pl/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/pt-BR/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/pt-BR/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/tr/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/tr/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/zh-Hans/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/zh-Hans/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/zh-Hant/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/zh-Hant/packages/vscode-extension/package.nls.json.lcl
LEGO: Pull request from juno/hb_fd34cb3d-1ea5-4a7c-8a66-721a44a97af3_20220911144241934 to dev with localized lcls
> chore(localization): [LEGO] Pull request from juno/hb_fd34cb3d-1ea5-4a7c-8a66-721a44a97af3_20220911144241934 to dev

- packages/fx-core/src/component/code/tabCode.ts
> fix: tab component should not generate local env file & run build:teamsfx script when env file exists

- packages/vscode-extension/src/debug/constants.ts
- packages/vscode-extension/src/debug/taskTerminal/localTunnelTaskTerminal.ts
> chore(localdebug): add output and progress bar to local tunnel task

- templates/bot/js/command-and-response/README.md
- templates/bot/ts/command-and-response/README.md
To Fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/14867432
> docs: Update Command Bot README to Include Customize Trigger Pattern

- Localize/loc/ko/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/ko/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/ru/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/ru/packages/vscode-extension/package.nls.json.lcl
LEGO: Pull request from juno/hb_fd34cb3d-1ea5-4a7c-8a66-721a44a97af3_20220914144255711 to dev with localized lcls
> chore(localization): [LEGO] Pull request from juno/hb_fd34cb3d-1ea5-4a7c-8a66-721a44a97af3_20220914144255711 to dev

- packages/vscode-extension/package.json
Revert "chore: hide tasks (#6074)" to add tasks back.
> chore: add tasks back

- packages/fx-core/resource/package.nls.json
- packages/fx-core/src/plugins/resource/appstudio/appStudio.ts
- packages/fx-core/src/plugins/resource/appstudio/errors.ts
- packages/fx-core/tests/plugins/resource/appstudio/unit/appstudio.test.ts
Have a clear error message, rather than raw error.
> fix: app id conflict with published app

- packages/cli/package-lock.json
- packages/cli/src/cmds/add.ts
- packages/cli/src/cmds/capability.ts
- packages/cli/tests/unit/cmds/addApiConnection.tests.ts
- packages/cli/tests/unit/cmds/addCICD.tests.ts
- packages/cli/tests/unit/cmds/addSso.tests.ts
- packages/cli/tests/unit/cmds/capability.tests.ts
- packages/fx-core/src/component/questionV3.ts
> chore: teamsfx add spfx-tab

- templates/bot/csharp/command-and-response/AdapterWithErrorHandler.cs.tpl
- templates/bot/csharp/notification-function-base/AdapterWithErrorHandler.cs.tpl
- templates/bot/csharp/notification-webapi/AdapterWithErrorHandler.cs.tpl
- templates/bot/csharp/workflow/.gitignore
- templates/bot/csharp/workflow/AdapterWithErrorHandler.cs.tpl
- templates/bot/csharp/workflow/CardActions/DoStuffActionHandler.cs.tpl
- templates/bot/csharp/workflow/Commands/HelloWorldCommandHandler.cs.tpl
- templates/bot/csharp/workflow/Controllers/BotController.cs.tpl
- templates/bot/csharp/workflow/GettingStarted.txt
- templates/bot/csharp/workflow/Models/HelloWorldModel.cs.tpl
- templates/bot/csharp/workflow/Program.cs.tpl
- templates/bot/csharp/workflow/ProjectName.csproj.tpl
- templates/bot/csharp/workflow/Properties/launchSettings.json.tpl
- templates/bot/csharp/workflow/Resources/DoStuffActionResponse.json
- templates/bot/csharp/workflow/Resources/HelloWorldCommandResponse.json
- templates/bot/csharp/workflow/TeamsBot.cs.tpl
- templates/bot/csharp/workflow/appsettings.json
- templates/bot/csharp/workflow/{{SafeProjectName}}.csproj.tpl
- templates/package.json
> feat(template): add workflow bot csharp template

- packages/fx-core/src/common/constants.ts
- packages/fx-core/src/common/tools.ts
- packages/fx-core/tests/common/tools.test.ts
- packages/vscode-extension/package.json
- packages/vscode-extension/src/constants.ts
- packages/vscode-extension/src/utils/commonUtils.ts
> chore: add setting for spfx version

- packages/vscode-extension/package.json
- packages/vscode-extension/package.nls.json
- packages/vscode-extension/src/debug/constants.ts
- packages/vscode-extension/src/debug/taskTerminal/localTunnelTaskTerminal.ts
- packages/vscode-extension/src/debug/teamsfxTaskHandler.ts
- packages/vscode-extension/src/debug/teamsfxTaskProvider.ts
detail: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_dashboards/dashboard/b7e7b190-a7fb-4c70-89f1-e63796c991c5
> chore(localdebug): add reuse arg into local tunnel task

- packages/vscode-extension/package.json
ms-teams-vscode-extension	v4.0.6-rc.1
> fix(vsc): remove command disable restriction

- packages/cli/src/cmds/preview/preview.ts
@microsoft/teamsfx-cli	v1.0.6-rc.1
ms-teams-vscode-extension	v4.0.6-rc.1
> fix(cli): fix cli preview for spfx remote

- .github/fabricbot.json
- .github/workflows/duplicate-app-studio-service-issue.yml
1. fix github action name
2. remove edit trigger
> chore(fabric): update

- packages/fx-core/tests/component/code/appSettingsUtils.test.ts
[Bug 15568129](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/15568129): Security Issue in fx-core test
> chore: update test mock secret

- packages/fx-core/src/component/code/tabCode.ts
- packages/fx-core/tests/component/code/tabCode.test.ts
@microsoft/teamsfx-cli	v1.0.6-rc.1
@microsoft/teamsfx-core	v1.16.0-rc.1
ms-teams-vscode-extension	v4.0.6-rc.1
> chore(v3): simpleauth compatible

- packages/fx-core/src/component/resource/appManifest/utils.ts
@microsoft/teamsfx-cli	v1.0.6-rc.1
@microsoft/teamsfx-core	v1.16.0-rc.1
ms-teams-vscode-extension	v4.0.6-rc.1
> chore(v3): sample manifest compatible process

- templates/bot/js/workflow/src/cardActions/doStuffActionHandler.js
- templates/bot/ts/workflow/src/cardActions/doStuffActionHandler.ts
Fix [bug 15567131](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/15567131)
ETE TEST: N/A
> chore(template): fix action response card message

- Localize/loc/cs/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/cs/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/de/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/de/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/es/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/es/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/fr/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/fr/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/it/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/it/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/ja/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/ja/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/pl/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/pl/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/pt-BR/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/pt-BR/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/tr/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/tr/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/zh-Hans/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/zh-Hans/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/zh-Hant/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/zh-Hant/packages/vscode-extension/package.nls.json.lcl
LEGO: Pull request from juno/hb_fd34cb3d-1ea5-4a7c-8a66-721a44a97af3_20220918144219418 to dev with localized lcls
> chore(localization): [LEGO] Pull request from juno/hb_fd34cb3d-1ea5-4a7c-8a66-721a44a97af3_20220918144219418 to dev

- packages/fx-core/src/component/debugHandler/bot.ts
- packages/fx-core/src/component/debugHandler/sso.ts
- packages/fx-core/src/component/debugHandler/tab.ts
- adding client id for bot and sso
- improve wording
> chore(debug): improve debug handler output message

- templates/function-base/js/default/package.json
- templates/function-base/ts/default/package.json
Fix issue: https://github.com/OfficeDev/TeamsFx/issues/6127
E2E TEST: N/A
> fix(template): lock adaptive card dependency version for function templates

- packages/fx-core/src/component/debug.ts
- packages/fx-core/src/plugins/solution/fx-solution/debug/scaffolding.ts
- packages/fx-core/templates/debug/ngrok.yml
- packages/fx-core/tests/plugins/solution/debug/solution.debug.scaffolding.test.ts
Add `ngrok.yml` unser `.fx/configs/`
> chore(localdebug): scaffold ngrok config file

- packages/adaptivecards-tools-sdk/package.json
Fix issue: https://github.com/OfficeDev/TeamsFx/issues/6127
E2E TEST: N/A
> fix(adaptive card): hotfix stick adaptive cards version

- packages/fx-core/resource/package.nls.json
- packages/fx-core/src/component/error.ts
- packages/fx-core/src/component/questionV3.ts
- packages/fx-core/tests/component/components.test.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/15554342
E2E TEST:
> fix(cli): show error when cannot add some feature

- packages/adaptivecards-tools-sdk/package-lock.json
- packages/adaptivecards-tools-sdk/package.json
This reverts commit 9b684385f40ae252ec2ee99fedf1674e41464d5c.
> chore: revert publish

- packages/fx-core/resource/package.nls.json
> chore: fix typo

- packages/adaptivecards-tools-sdk/package-lock.json
- packages/adaptivecards-tools-sdk/package.json
- packages/sdk/package.json
> chore: merge hotfix/1.0.4 to main

- docs/sdk/teamsfx.invokeresponsefactory.adaptivecard.md
- docs/sdk/teamsfx.invokeresponsefactory.md
- packages/sdk/package-lock.json
- packages/sdk/package.json
- packages/sdk/review/teamsfx.api.md
- packages/sdk/src/conversation/invokeResponseFactory.ts
- packages/sdk/test/unit/node/conversation/cardAction.spec.ts
- packages/sdk/test/unit/node/conversation/testUtils.ts
> chore: remove adaptivecards deps in teamsfx sdk

- packages/fx-core/src/core/generateAadManifestTemplate.ts
- packages/fx-core/src/core/middleware/consolidateLocalRemote.ts
@microsoft/teamsfx-cli	v1.0.6-rc.2
> chore(v3): fix consolidate upgrade migration bug

- packages/fx-core/src/component/core.ts
@microsoft/teamsfx-cli	v1.0.6-rc.2
> chore(v3): deduplicate provision message

- packages/cli/src/cmds/preview/preview.ts
- packages/fx-core/src/component/migrate.ts
- packages/fx-core/src/core/FxCore.ts
- packages/fx-core/tests/component/migrate.test.ts
@microsoft/teamsfx-cli	v1.1.0-rc.0
feat: up fd24e4bd8
feat: up 02aab09c1 
> chore(v3): get project config migration

- packages/fx-core/src/component/resource/botService.ts
@microsoft/teamsfx-cli	v1.1.0-rc.0
feat: up 9716235ec 
> chore: fix by using botId && botPassword

- Localize/loc/cs/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/cs/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/de/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/es/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/fr/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/it/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/ja/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/ko/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/pl/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/pt-BR/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/ru/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/tr/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/zh-Hans/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/zh-Hant/packages/fx-core/resource/package.nls.json.lcl
LEGO: Pull request from juno/hb_fd34cb3d-1ea5-4a7c-8a66-721a44a97af3_20220921144439602 to dev with localized lcls
> chore(localization): [LEGO] Pull request from juno/hb_fd34cb3d-1ea5-4a7c-8a66-721a44a97af3_20220921144439602 to dev

- packages/vscode-extension/CHANGELOG.md
- packages/vscode-extension/WHATISNEW.md
@microsoft/teamsfx-cli	v1.1.0-rc.0
feat: up 9716235ec 
> chore: update changelog & wahtsnew

- packages/vscode-extension/src/utils/commonUtils.ts
- packages/vscode-extension/test/extension/commonUtils.test.ts
> chore: add user selected spfx version setting in telemetry

- packages/vscode-extension/src/debug/commonUtils.ts
- packages/vscode-extension/src/debug/teamsfxDebugProvider.ts
- packages/vscode-extension/src/handlers.ts
Fix https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/15599929.
E2E TEST: N/A
> fix(debug): fix debug provider when app id is empty

- packages/fx-core/src/component/resource/simpleAuth.ts
@microsoft/teamsfx-cli	v1.1.1-rc.0
@microsoft/teamsfx-core	v1.16.1-rc.0
ms-teams-vscode-extension	v4.0.7-rc.0
> chore(v3): simple auth configure bug

- packages/vscode-extension/WHATISNEW.md
ms-teams-vscode-extension	v4.0.8-rc.0
> chore: fix whatsnew link

- packages/fx-core/src/component/feature/bot.ts
- packages/fx-core/src/component/resource/appManifest/appManifest.ts
- packages/fx-core/src/component/resource/appManifest/constants.ts
- packages/fx-core/src/component/resource/appManifest/utils.ts
@microsoft/teamsfx-cli	v1.1.2-rc.0
@microsoft/teamsfx-core	v1.16.2-rc.0
ms-teams-vscode-extension	v4.0.8-rc.0
> chore(v3): fix m365 app manifest

- packages/vscode-extension/package.json
ms-teams-vscode-extension	v4.0.6-rc.3
> chore: re-release 4.0.6 vscode extension

- packages/vscode-extension/package.json
> fix(debug): stop debugging immediately when starting local tunnel fails

- Localize/loc/de/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/de/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/es/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/es/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/fr/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/fr/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/it/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/it/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/ja/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/ja/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/ko/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/ko/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/pl/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/pl/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/pt-BR/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/pt-BR/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/ru/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/ru/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/tr/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/tr/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/zh-Hans/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/zh-Hans/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/zh-Hant/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/zh-Hant/packages/vscode-extension/package.nls.json.lcl
LEGO: Pull request from juno/hb_fd34cb3d-1ea5-4a7c-8a66-721a44a97af3_20220925144727507 to dev with localized lcls
> chore(localization): [LEGO] Pull request from juno/hb_fd34cb3d-1ea5-4a7c-8a66-721a44a97af3_20220925144727507 to dev

- packages/fx-core/src/core/question.ts
- packages/fx-core/tests/core/question.test.ts
- not allow "&"since it will break npm https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/15568225/
E2E TEST: N/A
> fix: not allow '&'

- packages/vscode-extension/src/debug/teamsfxTaskHandler.ts
> fix(debug): fix killing tunnel crashes on MacOS

- packages/cli/src/cmds/preview/depsChecker/cliChecker.ts
- packages/cli/src/cmds/preview/preview.ts
- packages/cli/tests/unit/cmds/preview/depsChecker.test.ts
- packages/fx-core/src/common/deps-checker/checkerFactory.ts
- packages/fx-core/src/common/deps-checker/depsChecker.ts
- packages/fx-core/src/common/deps-checker/depsManager.ts
- packages/fx-core/src/common/deps-checker/internal/nodeChecker.ts
- packages/fx-core/src/common/local/localEnvManager.ts
- packages/fx-core/src/common/tools.ts
- packages/fx-core/src/component/debug.ts
- packages/fx-core/src/plugins/solution/fx-solution/debug/util/tasksTransparency.ts
- packages/fx-core/tests/common/deps-checker/cases/node.it.ts
- packages/fx-core/tests/common/local/localEnvManager.test.ts
- packages/fx-core/tests/common/tools.test.ts
- packages/vscode-extension/src/debug/depsChecker/vscodeChecker.ts
- packages/vscode-extension/src/debug/prerequisitesHandler.ts
- packages/vscode-extension/src/handlers.ts
- packages/vscode-extension/test/extension/handlers.test.ts
- packages/vscode-extension/test/localdebug/depsChecker.test.ts
1. add spfx v1.16 node checker
2. remove func node checker
3. Scaffold transparency tasks for SPFx project
> chore(localdebug): add spfx v1.16 node checker

- packages/fx-core/templates/plugins/resource/aad/auth/bot/README.txt
bug: https://dev.azure.com/msazure/Microsoft%20Teams%20Extensibility/_workitems/edit/15637033
> docs: fix typo

- packages/fx-core/src/component/migrate.ts
E2E TEST: N/A
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/15639172
> fix(bot): migrate bot lost provision config

- packages/fx-core/templates/bicep/azureWebApp.config.module.bicep
E2E TEST: N/A
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/15639153/
> fix(bot): sso bot bicep compile error

- packages/fx-core/templates/bicep/azureWebApp.provision.module.bicep
E2E TEST: N/A
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/15625913
> fix(bot): dotnet bot cannot run from package

- packages/cli/src/cmds/preview/constants.ts
- packages/cli/src/cmds/preview/preview.ts
Node 16 & Global Azure Func Core Tool V3
Node 18
> chore(localdebug): make node error to warning in cli

- packages/fx-core/src/component/migrate.ts
E2E TEST: N/A
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/15637282/
> fix(tab): migrate vs tab project lost provision

- packages/fx-core/src/component/migrate.ts
- packages/fx-core/templates/bicep/azureWebApp.config.module.bicep
- packages/fx-core/templates/bicep/azureWebApp.provision.module.bicep
- templates/bot/csharp/default/GettingStarted.txt
@microsoft/teamsfx-cli	v1.1.3-rc.0
@microsoft/teamsfx-core	v1.16.3-rc.0
ms-teams-vscode-extension	v4.0.7-rc.0
> chore: Hotfix/cy22 9.2 to main

- packages/cli/src/commonlib/azureLoginCI.ts
1.Fix service principal get user data problem.
> chore: update service principal get json method

- .github/CODEOWNERS
- packages/cli/package.json
- packages/server/src/serverConnection.ts
- packages/server/tests/serverConnections.test.ts
- packages/vscode-extension/package.json
@microsoft/teamsfx-cli	v1.1.3-rc.0
ms-teams-vscode-extension	v4.0.7-rc.0
> fix: return empty object for updateManifest

- packages/fx-core/src/common/constants.ts
- packages/fx-core/src/common/featureFlags.ts
- packages/fx-core/src/plugins/solution/fx-solution/debug/scaffolding.ts
- packages/fx-core/src/plugins/solution/fx-solution/debug/util/launchTransparency.ts
- packages/fx-core/src/plugins/solution/fx-solution/debug/util/tasksTransparency.ts
- packages/fx-core/tests/plugins/solution/debug/solution.debug.scaffolding.test.ts
Fix "install app in Teams" typo by the way.
> chore(debug): remove transparency feature flag

- packages/fx-core/src/component/resource/azureAppService/azureWebApp.ts
> fix: forward compatible state key

- packages/fx-core/src/component/resource/appManifest/utils.ts
> fix: state value may be empty string

- packages/vscode-extension/package.nls.json
- packages/vscode-extension/src/handlers.ts
> feat(vsc): add tutorial for card action response

- packages/fx-core/src/core/FxCore.ts
ADO: 
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_sprints/taskboard/Teams%20Extensibility%20E2E%20Team/Microsoft%20Teams%20Extensibility/CY22-9.2
Before:
After:
E2E TEST: NA
> fix: create env failed in spfx project

- packages/vscode-extension/package-lock.json
- packages/vscode-extension/package.json
- packages/vscode-extension/src/commonlib/azure-account.api.d.ts
- packages/vscode-extension/src/commonlib/azureLogin.ts
- packages/vscode-extension/src/handlers.ts
1.Add back old azure credential for vs code.
> chore: add back old azure credential

- templates/bot/ts/default/.env.teamsfx.local
- templates/bot/ts/default/config.ts
- templates/bot/ts/default/index.ts
- templates/bot/ts/default/package.json
- Add config.ts to include all the configs
- Add .env.teamsfx.local to include all the configs
This PR is part of `app settings improvement` feature. Will update more templates.
Previous PR for ts sso-tab: https://github.com/OfficeDev/TeamsFx/pull/6249
> chore(app-setting): app settings for ts bot

- templates/bot/js/command-and-response/README.md
- templates/bot/js/notification-function-base/README.md
- templates/bot/js/notification-restify/README.md
- templates/bot/ts/command-and-response/README.md
- templates/bot/ts/notification-function-base/README.md
- templates/bot/ts/notification-restify/README.md
> docs: add readme section for how to add card actions

- templates/bot/js/workflow/README.md
- templates/bot/js/workflow/src/cardActions/doStuffActionHandler.js
- templates/bot/ts/workflow/README.md
- templates/bot/ts/workflow/src/cardActions/doStuffActionHandler.ts
- Show look and feel of the app
- Add link for how to create user-specific view
- Add link for how to add more command
- Highlight the usage of the action `verb`
E2E TEST: N/A
> chore: update workflow bot readme

- templates/bot/ts/default/.env.teamsfx.local
- templates/bot/ts/default/config.ts
- templates/bot/ts/default/index.ts
Reverts OfficeDev/TeamsFx#6288
> chore(app-setting): revert app settings for ts bot

- packages/vscode-extension/src/debug/constants.ts
- packages/vscode-extension/src/debug/taskTerminal/baseTaskTerminal.ts
- packages/vscode-extension/src/debug/taskTerminal/localTunnelTaskTerminal.ts
- packages/vscode-extension/src/debug/taskTerminal/npmInstallTaskTerminal.ts
- packages/vscode-extension/src/debug/taskTerminal/prepareManifestTaskTerminal.ts
- packages/vscode-extension/src/debug/taskTerminal/prerequisiteTaskTerminal.ts
- packages/vscode-extension/src/debug/taskTerminal/setUpBotTaskTerminal.ts
- packages/vscode-extension/src/debug/taskTerminal/setUpSSOTaskTerminal.ts
- packages/vscode-extension/src/debug/taskTerminal/setUpTabTaskTerminal.ts
Output task duration when the task is success
Success:
Failed:
> chore(localdebug): output local debug task duration

- packages/api/review/teamsfx-api.api.md
- packages/api/src/qm/ui.ts
- packages/fx-core/src/component/provisionUtils.ts
- packages/fx-core/src/plugins/solution/fx-solution/utils/backupFiles.ts
- packages/fx-core/src/plugins/solution/fx-solution/utils/util.ts
- packages/fx-core/src/plugins/solution/fx-solution/v2/utils.ts
- packages/fx-core/tests/component/provisionUtils.test.ts
- packages/fx-core/tests/plugins/solution/solution.backupFiles.test.ts
- packages/fx-core/tests/plugins/solution/solution.util.test.ts
- packages/server/src/apis.ts
- packages/server/src/providers/userInteraction.ts
- packages/server/tests/providers/userInteraction.test.ts
- open change-log file in VS once created. Related PR on VS: https://devdiv.visualstudio.com/InternalTools/_git/VSProject/pullrequest/428438
> chore: open read me once created in VS

- packages/fx-core/resource/package.nls.json
- packages/fx-core/src/component/resource/appManifest/errors.ts
- packages/fx-core/src/component/resource/appManifest/utils/ManifestUtils.ts
- packages/fx-core/tests/component/resource/appManifest/manifestUtils.test.ts
After: 
ADO:
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/15577951
E2E TEST: NA
> fix: dont ask user to provision when local debug failed

- templates/bot/js/notification-function-base/README.md
- templates/bot/ts/notification-function-base/README.md
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/15774489/
Add explanations in function-based notification readme.
> chore: update func notification readme

- packages/vscode-extension/package.json
- packages/vscode-extension/package.nls.json
- packages/vscode-extension/src/extension.ts
Related feature: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/14775898
Effect Preview:
E2E TEST: N/A
> feat(vsc): add support for untrusted workspace

- templates/bot/js/command-and-response/README.md
- templates/bot/js/workflow/README.md
- templates/bot/ts/command-and-response/README.md
- templates/bot/ts/workflow/README.md
Fix https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/15790172/
> fix: readme file for workflow & command bot

- packages/fx-core/src/common/constants.ts
- packages/fx-core/src/common/featureFlags.ts
- packages/fx-core/tests/common/featureFlags.test.ts
- packages/vscode-extension/src/extension.ts
- packages/vscode-extension/src/uriHandler.ts
- packages/vscode-extension/test/extension/commonUtils.test.ts
- packages/vscode-extension/test/extension/uriHandler.test.ts
- Add a simple uri handler behind feature flag for now.
> chore: add uri handler behind feature flag

- packages/vscode-extension/src/debug/constants.ts
- packages/vscode-extension/src/debug/teamsfxDebugProvider.ts
> chore(debug): improve sideloading display message

- packages/fx-core/src/core/question.ts
Related bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/15803293
> chore(vsc): fix question order

- templates/bot/csharp/command-and-response/GettingStarted.txt
- templates/bot/csharp/default/GettingStarted.txt
- templates/bot/csharp/notification-function-base/GettingStarted.txt
- templates/bot/csharp/notification-webapi/GettingStarted.txt
- templates/tab/csharp/default/GettingStarted.txt
- templates/tab/csharp/non-sso/GettingStarted.txt
> fix: naming and typo in getstarted file of csharp templates

- templates/bot/js/notification-function-base/README.md
- templates/bot/js/notification-restify/README.md
- templates/bot/ts/notification-function-base/README.md
- templates/bot/ts/notification-restify/README.md
> docs: refine notification readme

- templates/bot/js/command-and-response/README.md
- templates/bot/ts/command-and-response/README.md
@microsoft/adaptivecards-tools	v1.1.0-rc.0
@microsoft/teamsfx-api	v0.20.7-rc.0
@microsoft/teamsfx-cli	v1.1.3-rc.0
@microsoft/teamsfx-core	v1.17.0-rc.0
@microsoft/teams-manifest	v0.0.8-rc.0
@microsoft/metrics-ts	v0.0.2-rc.0
@microsoft/teamsfx	v1.2.1-rc.0
@microsoft/teamsfx-react	v1.0.6-rc.0
ms-teams-vscode-extension	v4.1.0-rc.0
feat: up (#5677) f4b2f935a
feat: prompt user to upgrade spfx project or toolkit to match spfx ve… (#5642) 0f8ca327c 
feat(vsc): add support for untrusted workspace (#6279) 540807041
feat(vsc): add tutorial for card action …
> docs: refine command response readme

- packages/fx-core/src/plugins/solution/fx-solution/question.ts
@microsoft/teamsfx-cli	v1.1.3-rc.1
@microsoft/teamsfx-core	v1.17.0-rc.1
ms-teams-vscode-extension	v4.1.0-rc.1
> chore: fix tutorial link for workflow bot

- templates/bot/js/default/.env.teamsfx.local
- templates/bot/js/default/config.js
- templates/bot/js/default/index.js
- templates/bot/ts/default/.env.teamsfx.local
- templates/bot/ts/default/config.ts
- templates/bot/ts/default/index.ts
- templates/function-base/js/default/.env.teamsfx.local
- templates/function-base/js/default/config.js
- templates/function-triggers/js/HTTPTrigger/entryname/index.js
- templates/tab/js/default/.env
- templates/tab/js/default/.env.teamsfx.local
- templates/tab/js/default/src/components/App.jsx
- templates/tab/js/default/src/components/Tab.jsx
- templates/tab/js/default/src/components/sample/AzureFunctions.jsx
- templates/tab/js/default/src/components/sample/EditCode.jsx
- templates/tab/js/default/src/components/sample/lib/config.js
- templates/tab/ts/default/.env
- templates/tab/ts/default/.env.teamsfx.local
- templates/tab/ts/default/src/components/App.tsx
- templates/tab/ts/default/src/components/Tab.tsx
- templates/tab/ts/default/src/components/sample/AzureFunctions.tsx
- templates/tab/ts/default/src/components/sample/EditCode.tsx
- templates/tab/ts/default/src/components/sample/lib/config.ts
- Add config.ts to include all the configs
- Add .env.teamsfx.local to include all the configs
This PR is part of `app settings improvement` feature. Will update more templates.
Changed templates in this PR:
- sso-tab (js, ts)
- bot (js, ts)
- function (js)
Previous PR for ts sso-tab: https://github.com/OfficeDev/TeamsFx/pull/6249
Previous PR for ts bot: https://github.com/OfficeDev/TeamsFx/pull/6288
Previous PR for ts function: https://github.com/OfficeDev/TeamsFx/pull/6303
> chore(app-setting): app settings for sso-tab, bot, function

- packages/sdk/CHANGELOG.md
> docs(sdk): update CHNAGELOG

- templates/bot/js/command-and-response/README.md
- templates/bot/js/workflow/README.md
- templates/bot/ts/command-and-response/README.md
- templates/bot/ts/workflow/README.md
> docs: fix readme issue

- packages/fx-core/src/component/debugHandler/appManifest.ts
- packages/fx-core/src/component/debugHandler/bot.ts
- packages/fx-core/src/component/debugHandler/sso.ts
- packages/fx-core/src/component/debugHandler/tab.ts
- packages/fx-core/src/component/debugHandler/utils.ts
- packages/fx-core/tests/component/debugHandler/appManifest.test.ts
- packages/fx-core/tests/component/debugHandler/bot.test.ts
- packages/fx-core/tests/component/debugHandler/sso.test.ts
- packages/fx-core/tests/component/debugHandler/tab.test.ts
- packages/fx-core/tests/component/debugHandler/utils.test.ts
- packages/vscode-extension/src/debug/taskTerminal/prepareManifestTaskTerminal.ts
- packages/vscode-extension/src/debug/taskTerminal/setUpBotTaskTerminal.ts
- packages/vscode-extension/src/debug/taskTerminal/setUpSSOTaskTerminal.ts
- packages/vscode-extension/src/debug/taskTerminal/setUpTabTaskTerminal.ts
@microsoft/teamsfx-cli	v1.1.3-rc.2
@microsoft/teamsfx-core	v1.17.0-rc.2
ms-teams-vscode-extension	v4.1.0-rc.2
> fix(debug): allow debug after m365 account swtiched

- packages/cli/src/cmds/preview/preview.ts
@microsoft/teamsfx-cli	v1.1.3-rc.2
@microsoft/teamsfx-core	v1.17.0-rc.2
ms-teams-vscode-extension	v4.1.0-rc.2
> chore(cli): fix cli preview

- docs/sdk/teamsfx.notificationbot.findallchannels.md
- docs/sdk/teamsfx.notificationbot.findchannel.md
- docs/sdk/teamsfx.notificationbot.md
- packages/sdk/src/conversation/notification.browser.ts
- packages/sdk/src/conversation/notification.ts
- packages/sdk/src/conversation/utils.ts
- packages/sdk/test/unit/node/conversation/utils.spec.ts
@microsoft/teamsfx-cli	v1.1.3-rc.2
@microsoft/teamsfx-core	v1.17.0-rc.2
@microsoft/teamsfx	v1.2.1-rc.1
@microsoft/teamsfx-react	v1.0.6-rc.1
ms-teams-vscode-extension	v4.1.0-rc.2
> fix(sdk): fix the fallback logic to get teams id

- templates/scenarios/notification-http-timer-trigger-js/bot/.env.teamsfx.local
- templates/scenarios/notification-http-timer-trigger-js/bot/src/internal/config.js
- templates/scenarios/notification-http-timer-trigger-js/bot/src/internal/initialize.js
- templates/scenarios/notification-http-timer-trigger-ts/bot/.env.teamsfx.local
- templates/scenarios/notification-http-timer-trigger-ts/bot/src/internal/config.ts
- templates/scenarios/notification-http-timer-trigger-ts/bot/src/internal/initialize.ts
- templates/scenarios/notification-http-trigger-js/bot/.env.teamsfx.local
- templates/scenarios/notification-http-trigger-js/bot/src/internal/config.js
- templates/scenarios/notification-http-trigger-js/bot/src/internal/initialize.js
- templates/scenarios/notification-http-trigger-ts/bot/.env.teamsfx.local
- templates/scenarios/notification-http-trigger-ts/bot/src/internal/config.ts
- templates/scenarios/notification-http-trigger-ts/bot/src/internal/initialize.ts
- templates/scenarios/notification-restify-js/bot/.env.teamsfx.local
- templates/scenarios/notification-restify-js/bot/src/internal/config.js
- templates/scenarios/notification-restify-js/bot/src/internal/initialize.js
- templates/scenarios/notification-restify-ts/bot/.env.teamsfx.local
- templates/scenarios/notification-restify-ts/bot/src/internal/config.ts
- templates/scenarios/notification-restify-ts/bot/src/internal/initialize.ts
- templates/scenarios/notification-timer-trigger-js/bot/.env.teamsfx.local
- templates/scenarios/notification-timer-trigger-js/bot/src/internal/config.js
- templates/scenarios/notification-timer-trigger-js/bot/src/internal/initialize.js
- templates/scenarios/notification-timer-trigger-ts/bot/.env.teamsfx.local
- templates/scenarios/notification-timer-trigger-ts/bot/src/internal/config.ts
- templates/scenarios/notification-timer-trigger-ts/bot/src/internal/initialize.ts
Synchronize from https://github.com/OfficeDev/TeamsFx/pull/6376
> chore: sync template changes

- packages/fx-core/src/component/deployUtils.ts
- packages/fx-core/src/component/resource/aadApp/aadApp.ts
- packages/fx-core/src/component/resource/aadApp/aadAppForTeamsImpl.ts
- packages/fx-core/src/component/resource/aadApp/constants.ts
- packages/fx-core/src/core/FxCore.ts
- packages/fx-core/tests/component/resource/aadApp/unit/aadApp.test.ts
bug 1:
trigger "Deploy AAD App Manifest" for local no need to pop up 'select a subscription':
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/15874384
bug 2:
Build AAD manifest file failed with error: Method not implemented: buildAadManifest
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/15874052
> fix: aad related bugs

- packages/fx-core/src/component/resource/appManifest/appStudioClient.ts
status-code should be string type.
> fix: telemetry properties

- .github/scripts/sync-version.js
> chore: remove m365 template skip-sync

- templates/bot/csharp/command-and-response/ProjectName.csproj.tpl
- templates/bot/csharp/notification-function-base/ProjectName.csproj.tpl
- templates/bot/csharp/notification-webapi/ProjectName.csproj.tpl
- templates/bot/csharp/workflow/ProjectName.csproj.tpl
> chore(template): upgrade bot builder package version

- templates/bot/ts/workflow/src/cardActions/doStuffActionHandler.ts
- templates/bot/ts/workflow/src/internal/initialize.ts
Fix [Bug 15904647](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/15904647): [workflow bot] issue in readme.
E2E TEST: N/A
> chore: rename action handler name to keep consistency with js template

- packages/fx-core/resource/package.nls.json
- packages/fx-core/src/component/driver/deploy/spfx/deployDriver.ts
- packages/fx-core/src/component/driver/deploy/spfx/error/createAppCatalogFailedError.ts
- packages/fx-core/src/component/driver/deploy/spfx/error/getGraphTokenFailedError.ts
- packages/fx-core/src/component/driver/deploy/spfx/error/getSPOTokenFailedError.ts
- packages/fx-core/src/component/driver/deploy/spfx/error/getTenantFailedError.ts
- packages/fx-core/src/component/driver/deploy/spfx/error/insufficientPermissionError.ts
- packages/fx-core/src/component/driver/deploy/spfx/error/noSPPackageError.ts
- packages/fx-core/src/component/driver/deploy/spfx/error/noValidAppCatelogError.ts
- packages/fx-core/src/component/driver/deploy/spfx/error/uploadAppPackageFailedError.ts
- packages/fx-core/src/component/driver/deploy/spfx/interface/deployArgs.ts
- packages/fx-core/src/component/driver/deploy/spfx/utility/constants.ts
- packages/fx-core/src/component/driver/deploy/spfx/utility/sleep.ts
- packages/fx-core/src/component/driver/deploy/spfx/utility/spoClient.ts
- packages/fx-core/src/component/utils/common.ts
- packages/fx-core/tests/component/drivers/deploy/spfx/deployDriver.test.ts
- packages/fx-core/tests/component/drivers/deploy/spfx/spoClient.test.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/15785071
> chore: add spfx deploy driver

- packages/fx-core/src/component/debugHandler/sso.ts
- packages/fx-core/src/component/resource/aadApp/aadAppForTeamsImpl.ts
- packages/fx-core/src/component/resource/aadApp/utils/configs.ts
- packages/fx-core/tests/component/debugHandler/sso.test.ts
Fix https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/15596143.
E2E TEST: N/A
> fix(sso): add port to application id uri

- templates/bot/js/workflow/.env.teamsfx.local
- templates/bot/js/workflow/src/internal/config.js
- templates/bot/js/workflow/src/internal/initialize.js
- templates/bot/ts/workflow/src/.env.teamsfx.local
- templates/bot/ts/workflow/src/internal/config.ts
- templates/bot/ts/workflow/src/internal/initialize.ts
- Add config.ts to include all the configs
- Add .env.teamsfx.local to include all the configs
Previous PR for ts sso-tab: https://github.com/OfficeDev/TeamsFx/pull/6249
Previous PR for ts bot: https://github.com/OfficeDev/TeamsFx/pull/6288
Previous PR for ts function: https://github.com/OfficeDev/TeamsFx/pull/6303
Previous PR for scenario-based bot, m365 tab, non-sso tab: https://github.com/OfficeDev/TeamsFx/pull/6376
> chore(app-setting): app settings for workflow bot

- packages/fx-core/src/component/driver/deploy/spfx/deployDriver.ts
- packages/fx-core/src/component/driver/deploy/spfx/interface/deployArgs.ts
- packages/fx-core/src/component/driver/deploy/spfx/utility/constants.ts
- packages/fx-core/tests/component/drivers/deploy/spfx/deployDriver.test.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/15890373
> chore: add telemetry and progress in spfx deploy driver

- packages/sdk-react/package.json
> fix: update sdk react peer dependency

- packages/fx-core/templates/plugins/resource/cicd/azdo/cd.yml
- packages/fx-core/templates/plugins/resource/cicd/azdo/provision.yml
- packages/fx-core/templates/plugins/resource/cicd/azdo/publish.yml
- packages/fx-core/templates/plugins/resource/cicd/github/cd.yml
- packages/fx-core/templates/plugins/resource/cicd/github/provision.yml
- packages/fx-core/templates/plugins/resource/cicd/github/publish.yml
- packages/fx-core/templates/plugins/resource/cicd/jenkins/Jenkinsfile.cd
- packages/fx-core/templates/plugins/resource/cicd/jenkins/Jenkinsfile.provision
- packages/fx-core/templates/plugins/resource/cicd/jenkins/Jenkinsfile.publish
To remove package.json from root:
1. Update CI/CD pipeline templates.
2. Update GitHub Action in another repo.
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/15800635
> chore: update cicd templates

- packages/sdk-react/CHANGELOG.md
> docs: update sdk react CHNAGELOG

- packages/cli/src/cmds/publish.ts
- packages/cli/src/constants.ts
- packages/cli/tests/unit/cmds/publish.tests.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/15988349
https://github.com/OfficeDev/TeamsFx/actions/runs/3318859113
> chore(cli): remove unused code of publish

- templates/scenarios/command-and-response-js/.fx/appPackage/manifest.template.json
- templates/scenarios/command-and-response-ts/templates/appPackage/manifest.template.json
- templates/scenarios/m365-tab-js/templates/appPackage/manifest.template.json
- templates/scenarios/m365-tab-ts/templates/appPackage/manifest.template.json
- templates/scenarios/non-sso-tab-ts/templates/appPackage/manifest.template.json
- templates/scenarios/notification-http-timer-trigger-js/templates/appPackage/manifest.template.json
- templates/scenarios/notification-http-timer-trigger-ts/templates/appPackage/manifest.template.json
- templates/scenarios/notification-http-trigger-js/templates/appPackage/manifest.template.json
- templates/scenarios/notification-http-trigger-ts/templates/appPackage/manifest.template.json
- templates/scenarios/notification-restify-js/.fx/appPackage/manifest.template.json
- templates/scenarios/notification-restify-ts/templates/appPackage/manifest.template.json
- templates/scenarios/notification-timer-trigger-js/templates/appPackage/manifest.template.json
- templates/scenarios/notification-timer-trigger-ts/templates/appPackage/manifest.template.json
- templates/scenarios/sso-tab-ts/templates/appPackage/manifest.template.json
> chore: bad url values in manifest in scenarios templates

- docs/sdk/teamsfx.appcredential._constructor_.md
- docs/sdk/teamsfx.appcredential._constructor__1.md
- docs/sdk/teamsfx.appcredential.md
- docs/sdk/teamsfx.botssoexecutiondialog._constructor_.md
- docs/sdk/teamsfx.botssoexecutiondialog._constructor__1.md
- docs/sdk/teamsfx.botssoexecutiondialog.md
- docs/sdk/teamsfx.msgraphauthprovider._constructor__1.md
- docs/sdk/teamsfx.msgraphauthprovider.md
- docs/sdk/teamsfx.onbehalfofusercredential._constructor_.md
- docs/sdk/teamsfx.onbehalfofusercredential._constructor__1.md
- docs/sdk/teamsfx.onbehalfofusercredential.md
- docs/sdk/teamsfx.teamsbotssoprompt._constructor__1.md
- docs/sdk/teamsfx.teamsbotssoprompt.md
- packages/sdk/src/bot/teamsBotSsoPrompt.ts
- packages/sdk/src/conversation/sso/botSsoExecutionDialog.browser.ts
- packages/sdk/src/conversation/sso/botSsoExecutionDialog.ts
- packages/sdk/src/core/msGraphAuthProvider.ts
- packages/sdk/src/credential/appCredential.ts
- packages/sdk/src/credential/onBehalfOfUserCredential.ts
- packages/sdk/src/credential/teamsUserCredential.browser.ts
- packages/sdk/test/e2e/browser/msGraphAuthProvider.browser.spec.ts
- packages/sdk/test/e2e/browser/msGraphClientProvider.browser.spec.ts
- packages/sdk/test/e2e/node/appCredential.spec.ts
- packages/sdk/test/e2e/node/msGraphAuthProvider.spec.ts
- packages/sdk/test/e2e/node/msGraphClientProvider.spec.ts
- packages/sdk/test/e2e/node/onBehalfOfUserCredential.spec.ts
- packages/sdk/test/e2e/node/teamsBotSsoPrompt.spec.ts
This PR update the sdk comments which is used to generate API docs, and add some e2e test for new API.
E2E test result:
https://github.com/OfficeDev/TeamsFx/actions/runs/3318442264
> perf(sdk): update comments and e2e test cases

- packages/cli/src/cmds/permission.ts
- packages/fx-core/src/core/collaborator.ts
- packages/vscode-extension/src/handlers.ts
1. remove dependency on env in core
2. will not show help message after grant permission in corei and vsc
3. throw error if --env not specified in cli
> perf(collaboration): update collaboration

- .github/detect/excludes.txt
- packages/fx-core/src/component/feature/cicd/provider/provider.ts
- packages/fx-core/templates/plugins/resource/cicd_v2/azdo/README.md
- packages/fx-core/templates/plugins/resource/cicd_v2/azdo/cd.yml
- packages/fx-core/templates/plugins/resource/cicd_v2/azdo/ci.yml
- packages/fx-core/templates/plugins/resource/cicd_v2/azdo/provision.yml
- packages/fx-core/templates/plugins/resource/cicd_v2/azdo/publish.yml
- packages/fx-core/templates/plugins/resource/cicd_v2/github/README.md
- packages/fx-core/templates/plugins/resource/cicd_v2/github/cd.yml
- packages/fx-core/templates/plugins/resource/cicd_v2/github/ci.yml
- packages/fx-core/templates/plugins/resource/cicd_v2/github/provision.yml
- packages/fx-core/templates/plugins/resource/cicd_v2/github/publish.yml
- packages/fx-core/templates/plugins/resource/cicd_v2/jenkins/Jenkinsfile.cd
- packages/fx-core/templates/plugins/resource/cicd_v2/jenkins/Jenkinsfile.ci
- packages/fx-core/templates/plugins/resource/cicd_v2/jenkins/Jenkinsfile.provision
- packages/fx-core/templates/plugins/resource/cicd_v2/jenkins/Jenkinsfile.publish
- packages/fx-core/templates/plugins/resource/cicd_v2/jenkins/README.md
- packages/fx-core/tests/component/feature/cicd/verifyGeneratedTemplates.test.ts
Apply v3 feature flag for cicd.
> chore: apply v3 feature flag

- templates/bot/js/command-and-response/src/internal/config.js
- templates/bot/js/command-and-response/src/internal/initialize.js
- templates/bot/js/default/config.js
- templates/bot/js/default/index.js
- templates/bot/js/m365/config.js
- templates/bot/js/m365/index.js
- templates/bot/js/notification-function-base/src/internal/config.js
- templates/bot/js/notification-function-base/src/internal/initialize.js
- templates/bot/js/notification-restify/src/internal/config.js
- templates/bot/js/notification-restify/src/internal/initialize.js
- templates/bot/js/workflow/src/internal/config.js
- templates/bot/js/workflow/src/internal/initialize.js
Fix https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/15988519
> chore(app-setting): change from ES6 Modules to CommonJS for JS Bot

- packages/cli/src/cmds/package.ts
- packages/cli/src/constants.ts
- packages/cli/tests/unit/cmds/package.tests.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/15972986
> chore(cli): teamsfx package for V3

- packages/fx-core/src/component/generator/generator.ts
- packages/fx-core/src/component/generator/utils.ts
> refactor(generator): fix circular dependency

- packages/cli/src/cmds/deploy.ts
- packages/cli/src/cmds/provision.ts
- packages/cli/src/cmds/publish.ts
- packages/cli/src/utils.ts
- packages/cli/tests/unit/cmds/deploy.tests.ts
- packages/cli/tests/unit/cmds/provision.tests.ts
- packages/cli/tests/unit/cmds/publish.tests.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/15988565
> chore(cli): ask env in lifecycle apis

- templates/tab/csharp/default/Config.cs.tpl
- templates/tab/csharp/default/Program.cs.tpl
- Add Config.cs to include all the configs
This PR is part of `app settings improvement` feature. Will update more templates
> chore(app-setting): app settings for csharp sso-tab

- packages/fx-core/src/component/debugHandler/bot.ts
- packages/fx-core/src/component/debugHandler/error.ts
- packages/fx-core/src/component/resource/botService/appStudio/appStudioClient.ts
- packages/fx-core/src/component/resource/botService/botRegistration/botRegistration.ts
- packages/fx-core/src/component/resource/botService/botRegistration/localBotRegistration.ts
- packages/fx-core/src/component/resource/botService/botRegistration/remoteBotRegistration.ts
- packages/fx-core/src/component/resource/botService/botService.ts
- packages/fx-core/src/component/resource/botService/errors.ts
- packages/fx-core/tests/component/debugHandler/bot.test.ts
- packages/fx-core/tests/component/resource/botService/appStudioClient.test.ts
- packages/fx-core/tests/component/resource/botService/botService.test.ts
- packages/fx-core/tests/component/resource/botService/telemetryHelper.test.ts
- have already added error message for the new local debug handler. Adding it also in the old provision code.
> chore: error message for old bot code

- templates/scenarios/sso-tab-js/.fx/teamsfx.yml
- templates/scenarios/sso-tab-js/templates/appPackage/manifest.template.json
> fix: publish failed for invalid package

- packages/fx-core/templates/plugins/resource/aad/auth/bot/README.md
@microsoft/teamsfx-cli	v1.1.4-rc.1
@microsoft/teamsfx-core	v1.18.0-rc.1
ms-teams-vscode-extension	v4.1.1-rc.1
> chore: update me sso readme file

- templates/scenarios/sso-tab-js/.vscode/launch.json
- templates/scenarios/sso-tab-js/.vscode/tasks.json
- templates/scenarios/sso-tab-js/teamsfx/.env.local
- templates/scenarios/sso-tab-js/teamsfx/app.local.yml
Add debug into tab sso v3 template
> chore(localdebug): add debug config file into tab sso v3 template

- packages/cli/src/cmds/deploy.ts
- packages/cli/src/cmds/package.ts
- packages/cli/src/cmds/provision.ts
- packages/cli/src/cmds/publish.ts
- packages/cli/src/utils.ts
- packages/cli/tests/unit/cmds/deploy.tests.ts
- packages/cli/tests/unit/cmds/provision.tests.ts
- packages/cli/tests/unit/cmds/publish.tests.ts
- packages/vscode-extension/src/handlers.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/16108033
> chore(cli+vscode): env update for V3

- templates/scenarios/notification-webapi-csharp/Config.cs.tpl
- templates/scenarios/notification-webapi-csharp/Program.cs.tpl
- Add Config.cs to include all the configs
This PR is part of `app settings improvement` feature. Will update more templates
> chore(app-setting): app settings for csharp notification-webapi-bot

- packages/fx-core/src/component/debugHandler/appManifest.ts
- packages/fx-core/src/component/debugHandler/bot.ts
- packages/fx-core/src/component/debugHandler/sso.ts
- packages/fx-core/src/component/debugHandler/tab.ts
- packages/fx-core/tests/component/debugHandler/appManifest.test.ts
- packages/fx-core/tests/component/debugHandler/bot.test.ts
- packages/fx-core/tests/component/debugHandler/sso.test.ts
- packages/fx-core/tests/component/debugHandler/tab.test.ts
@microsoft/teamsfx-cli	v1.1.4-rc.2
@microsoft/teamsfx-core	v1.18.0-rc.2
ms-teams-vscode-extension	v4.1.1-rc.2
> fix(debug): save project settings in debug handler

- packages/cli/src/cmds/index.ts
- packages/cli/src/cmds/init.ts
- packages/cli/src/telemetry/cliTelemetryEvents.ts
- packages/cli/tests/unit/cmds/init.tests.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/16034192
> chore(cli): teamsfx init infra

- packages/fx-core/resource/package.nls.json
- packages/fx-core/src/component/driver/deploy/azure/azureDeployDriver.ts
- packages/fx-core/src/component/driver/deploy/azure/azureStorageDeployDriver.ts
- packages/fx-core/src/component/driver/deploy/azure/baseDeployDriver.ts
- packages/fx-core/src/component/driver/interface/baseDeployStepDriver.ts
- packages/fx-core/src/component/driver/interface/buildAndDeployArgs.ts
- packages/fx-core/src/component/driver/script/baseBuildDriver.ts
- packages/fx-core/src/component/error/componentError.ts
- packages/fx-core/src/component/error/deployError.ts
- packages/fx-core/src/component/messages.ts
- packages/fx-core/src/component/utils/fileOperation.ts
Allow empty working directory
Allow absolute path in distribution
Check folder exists before all operation
Check zip file is empty before uploading
> chore: add more log output when using VS in v3

- .github/scripts/sync-version.js
- packages/vscode-extension/package-lock.json
- packages/vscode-extension/package.json
- templates/function-base/js/default/package.json
- templates/function-base/ts/default/package.json
ms-teams-vscode-extension	v4.1.1-rc.4
> chore: revert visx version

- packages/vscode-extension/src/debug/teamsfxTaskHandler.ts
Add `node teamsfx/script/run.js teamsfx/.env.local` to the teamsfx task.
> chore(localdebug): stop the start service task after debug stoped

- packages/fx-core/resource/package.nls.json
- packages/fx-core/src/component/configManager/error.ts
- packages/fx-core/src/component/configManager/interface.ts
- packages/fx-core/src/component/configManager/lifecycle.ts
- packages/fx-core/src/component/configManager/parser.ts
- packages/fx-core/tests/component/configManager/lifecycle.test.ts
- packages/fx-core/tests/component/configManager/parser.test.ts
- packages/fx-core/tests/component/configManager/testing_data/app.yml
- packages/fx-core/tests/component/configManager/testing_data/invalid_env_field_array.yml
- packages/fx-core/tests/component/configManager/testing_data/invalid_env_field_string.yml
- packages/fx-core/tests/component/configManager/testing_data/valid_env_field.yml
https://dev.azure.com/msazure/Microsoft%20Teams%20Extensibility/_workitems/edit/16139966
> chore: support env field in yaml engine

- packages/fx-core/src/component/driver/botAadApp/create.ts
- packages/fx-core/src/component/driver/botAadApp/interface/createBotAadAppOutput.ts
- packages/fx-core/tests/component/driver/botAadApp/create.test.ts
- templates/scenarios/notification-restify-js/.appserviceIgnore
- templates/scenarios/notification-restify-js/.vscode/launch.json
- templates/scenarios/notification-restify-js/teamsfx/app.yml
- templates/scenarios/sso-tab-js/teamsfx/app.yml
1. botAadApp/create should output `SECRET_BOT_PASSWORD`
2. update sso-tab-js deploy folder
3. update notification-restify-js launch.json
> chore: fix V3 js templates and action

- templates/scenarios/command-and-response-csharp/Commands/HelloWorldCommandHandler.cs.tpl
- templates/scenarios/command-and-response-csharp/Resources/HelloWorldCard.json
- templates/scenarios/command-and-response-js/bot/README.md
- templates/scenarios/command-and-response-js/bot/src/adaptiveCards/helloworldCommand.json
- templates/scenarios/command-and-response-js/bot/src/helloworldCommandHandler.js
- templates/scenarios/command-and-response-js/bot/src/index.js
- templates/scenarios/command-and-response-js/bot/src/internal/initialize.js
- templates/scenarios/command-and-response-ts/bot/README.md
- templates/scenarios/command-and-response-ts/bot/src/adaptiveCards/helloworldCommand.json
- templates/scenarios/command-and-response-ts/bot/src/helloworldCommandHandler.ts
- templates/scenarios/command-and-response-ts/bot/src/index.ts
- templates/scenarios/command-and-response-ts/bot/src/internal/initialize.ts
- templates/scenarios/notification-restify-js/src/index.js
- templates/scenarios/notification-restify-js/src/internal/initialize.js
- templates/scenarios/notification-restify-ts/bot/src/index.ts
- templates/scenarios/notification-restify-ts/bot/src/internal/initialize.ts
Based on Tim's feedback to our sample project
> chore: update wordings in bot template

- packages/vscode-extension/src/debug/teamsfxDebugProvider.ts
Fix https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/16140326.
> chore(debug): add v3 feature flag to debug provider

- templates/scenarios/command-and-response-csharp/Config.cs.tpl
- templates/scenarios/command-and-response-csharp/Program.cs.tpl
- templates/scenarios/message-extension-csharp/Config.cs.tpl
- templates/scenarios/message-extension-csharp/Program.cs.tpl
- templates/scenarios/notification-http-timer-trigger-csharp/Config.cs.tpl
- templates/scenarios/notification-http-timer-trigger-csharp/Startup.cs.tpl
- templates/scenarios/notification-http-trigger-csharp/Config.cs.tpl
- templates/scenarios/notification-http-trigger-csharp/Startup.cs.tpl
- templates/scenarios/notification-timer-trigger-csharp/Config.cs.tpl
- templates/scenarios/notification-timer-trigger-csharp/Startup.cs.tpl
- Add Config.cs to include all the configs
> chore(app-setting): app settings for csharp ME and Bot

- packages/fx-core/src/component/driver/aad/utility/aadAppClient.ts
- packages/fx-core/tests/component/driver/aad/aadAppClient.test.ts
aadApp/update may also meet errors due to AAD app data sync issue, add retry to it
Also limit the retry status code to 404 as it's the most likely error. Can update the retry conditions later if we find other errors.
> chore: retry 404 error during AAD app update

- packages/dotnet-sdk/CHANGELOG.md
- packages/dotnet-sdk/README.md
- packages/dotnet-sdk/src/TeamsFx/Credential/TeamsUserCredential.cs
- packages/dotnet-sdk/src/TeamsFx/Microsoft.TeamsFx.csproj
- packages/dotnet-sdk/src/TeamsFx/Pages/AuthorizeEndPage.cshtml
- packages/dotnet-sdk/src/TeamsFx/Pages/AuthorizeStartPage.cshtml
- packages/dotnet-sdk/src/TeamsFx/wwwroot/jsInterop.js
- templates/bot/csharp/workflow/ProjectName.csproj.tpl
- templates/tab/csharp/default/ProjectName.csproj.tpl
- templates/tab/csharp/default/wwwroot/js/TeamsJsBlazorInterop.js
- templates/tab/csharp/non-sso/ProjectName.csproj.tpl
- templates/tab/csharp/non-sso/wwwroot/js/TeamsJsBlazorInterop.js
> feat: update .NET SDK to use Teams JS V2

- packages/dotnet-sdk/src/TeamsFx/Pages/AuthorizeEndPage.cshtml
- packages/dotnet-sdk/src/TeamsFx/Pages/AuthorizeStartPage.cshtml
> fix: update start & end page

- docs/fx-core/switch-tenant-v3.md
- add doc for tenant mismatch error in v3.
> chore: doc update

- .github/scripts/sync-version.js
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_sprints/taskboard/AuthAndData/Microsoft%20Teams%20Extensibility/CY22-10.3?workitem=16128196
> chore: add detect version change

- packages/vscode-extension/package.json
Remove v3 arguements in the task definition.
> chore(localdebug): remove v3 task args in the task definition

- packages/fx-core/templates/plugins/resource/aad/auth/bot/README.md
- packages/fx-core/templates/plugins/resource/aad/auth/bot/js/sso/handleMessageExtensionQueryWithToken.js
- packages/fx-core/templates/plugins/resource/aad/auth/bot/js/sso/profileSsoCommandHandler.js
- packages/fx-core/templates/plugins/resource/aad/auth/bot/ts/sso/handleMessageExtensionQueryWithToken.ts
- packages/fx-core/templates/plugins/resource/aad/auth/bot/ts/sso/profileSsoCommandHandler.ts
- templates/function-triggers/js/HTTPTrigger/entryname/index.js
- templates/function-triggers/ts/HTTPTrigger/entryname/index.ts
Update template to use latest sdk function and class: use credentials instead of teamsfx class
> perf: update template to use latest sdk function/class

- packages/vscode-extension/src/controls/webviewPanel.ts
ADO: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/16182033
Screenshot:
E2E TEST: NA
> fix: sample gallery is broken

- packages/cli/src/cmds/env.ts
- packages/cli/tests/unit/cmds/env.tests.ts
- packages/fx-core/src/component/driver/deploy/spfx/deployDriver.ts
https://dev.azure.com/msazure/Microsoft%20Teams%20Extensibility/_workitems/edit/16127927
> chore(cli): show log and start the progress bar

- templates/scenarios/csharp/workflow-bot/Config.cs.tpl
- templates/scenarios/csharp/workflow-bot/Program.cs.tpl
- Add Config.cs to include all the configs
> chore(app-setting): app settings for csharp workflow bot

- packages/fx-core/src/component/generator/spfxGenerator.ts
- packages/fx-core/src/component/generator/utils.ts
> fix: create spfx results in unexpected folder structure

- packages/vscode-extension/src/controls/webviewPanel.ts
> fix: sample gallery is broken (#6695)

- packages/cli/src/cmds/config.ts
- packages/cli/src/utils.ts
- packages/cli/tests/unit/cmds/config.tests.ts
https://dev.azure.com/msazure/Microsoft%20Teams%20Extensibility/_workitems/edit/16127868
> chore(cli): config for V3
