OfficeDev/teams-toolkit

- templates/bot/csharp/notification-function-base/ProjectName.csproj.tpl
- Use `Microsoft.NET.Sdk` since it's a func project.
- Align `Include` section with webapi notification project.
E2E TEST: N/A
> fix: fix dotnet notification func template

- templates/tab/js/default/src/components/sample/AzureFunctions.jsx
- templates/tab/ts/default/src/components/sample/AzureFunctions.tsx
Use API client with BearerTokenAuthProvider to call functions, so users do not need to manually get token and set to header for every request.
> chore: use createApiClient to call function API

- templates/tab/js/m365/src/components/sample/AzureFunctions.jsx
- templates/tab/ts/m365/src/components/sample/AzureFunctions.tsx
Use API client with BearerTokenAuthProvider to call functions, so users do not need to manually get token and set to header for every request.
> chore: use createApiClient in M365 tab template

- packages/fx-core/src/common/local/localCertificateManager.ts
- packages/vscode-extension/src/debug/prerequisitesHandler.ts
- packages/vscode-extension/src/telemetry/extTelemetryEvents.ts
Add property `debug-dev-cert-status` to make cert telemetry more clear
Test (timestamp is in reverse order):
- first event is cancel in first dialog,
- second event is cancel in the second dialog
- third event is disable in vscode settings
- fourth event is confirm trust
- fourth event is second time local debug
E2E TEST: https://github.com/OfficeDev/TeamsFx-UI-Test/blob/76b1d9c8ea6d3d74fb9dbdbeddc28b3afd4259f6/src/ui-test/localdebug/localdebug-bot.test.ts
> fix: make local debug dev cert properties more clear

- packages/fx-core/src/common/local/localTelemetryReporter.ts
- packages/fx-core/tests/common/local/localTelemetryReporter.test.ts
- packages/vscode-extension/src/debug/prerequisitesHandler.ts
- packages/vscode-extension/src/error.ts
- packages/vscode-extension/src/telemetry/extTelemetryEvents.ts
Fix local debug telemetry bugs:
- npm install error code was `PrerequisiteValidationError` and contains no useful information
- env checker does not send error-code for telemetry
- `checkResults` should be included in `errorProps` because it includes error message.
test env checker error:
test npm install error:
E2E TEST: https://github.com/OfficeDev/TeamsFx-UI-Test/blob/76b1d9c8ea6d3d74fb9dbdbeddc28b3afd4259f6/src/ui-test/localdebug/localdebug-bot.test.ts#L11
> fix: fix missing error code for npm install & env checker

- packages/vscode-extension/src/debug/commonUtils.ts
- packages/vscode-extension/src/debug/prerequisitesHandler.ts
- packages/vscode-extension/src/telemetry/extTelemetryEvents.ts
- fix: `debug-check-results` are redacted sometimes
- add `debug-check-results` to `debug-all` event
Previous:
Now:
E2E TEST: https://github.com/OfficeDev/TeamsFx-UI-Test/blob/76b1d9c8ea6d3d74fb9dbdbeddc28b3afd4259f6/src/ui-test/localdebug/localdebug-bot.test.ts
> fix: debug-check-results are redacted sometimes

- templates/bot/csharp/command-and-response/ProjectName.csproj.tpl
- templates/bot/csharp/notification-function-base/ProjectName.csproj.tpl
- templates/bot/csharp/notification-webapi/ProjectName.csproj.tpl
Workitem: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/14786691
Upgrade dotnet bot templates to use [Microsoft.TeamsFx 1.0.0](https://www.nuget.org/packages/Microsoft.TeamsFx/1.0.0)
> chore: dotnet bot uses latest dotnet sdk

- packages/fx-core/src/plugins/resource/bot/appStudio/appStudio.ts
- packages/fx-core/src/plugins/resource/bot/index.ts
- packages/fx-core/src/plugins/resource/bot/utils/retryHandler.ts
404 was treated as Exception in Axios, so extract it out as a normal response to represent nonexistence.
https://dev.azure.com/msazure/Microsoft%20Teams%20Extensibility/_workitems/edit/14727888
E2E TEST: None
> fix: retry exclude 404

- packages/fx-core/src/plugins/resource/bot/constants.ts
- packages/fx-core/src/plugins/resource/bot/utils/telemetry-helper.ts
- packages/fx-core/src/plugins/resource/bot/v2/common.ts
- packages/fx-core/src/plugins/resource/bot/v2/plugin.ts
fix https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/14786120.
E2E TEST: N/A
In this PR the projectSettings.json looks like below, the same as 4.0.0.
> fix(bot): add bot capabilities into projectsettings.json

- packages/cli/src/cmds/preview/errors.ts
- packages/cli/src/cmds/preview/launch.ts
- packages/cli/src/cmds/preview/localTelemetryReporter.ts
- packages/cli/src/cmds/preview/preview.ts
- packages/cli/src/cmds/preview/task.ts
- packages/cli/src/telemetry/cliTelemetryEvents.ts
- unify handling of start/end events for preview stages (use localTelemetryReporter so `duration` is automatically added)
- align telemetry with vsc
- separate PrerequisiteValidationError for account check and node check
- `preview` event will contain `preview-last-event-name` and `preview-check-results`
- add `preview-dev-cert-status` for cert event
- remove `PreviewPrerequisitesCheckTime` because every end events contains `duration` now
Test:
"teamsfx-cli/preview" event
> chore: improve cli preview telemetry

- packages/fx-core/src/common/utils.ts
- packages/fx-core/src/core/generateAadManifestTemplate.ts
- packages/fx-core/src/core/middleware/consolidateLocalRemote.ts
- packages/fx-core/tests/plugins/resource/aad/unit/index.test.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_sprints/taskboard/Teams%20Extensibility%20E2E%20Team/Microsoft%20Teams%20Extensibility/CY22-6.2?workitem=14776287
E2E TEST: already covered by packages/cli/tests/e2e/bot/ProvisionAppServiceNotificationBot.dotnet.tests.ts
> fix: template path for aad manifest on .net scenario

- packages/fx-core/src/common/local/localTelemetryReporter.ts
- packages/fx-core/tests/common/local/localTelemetryReporter.test.ts
- packages/vscode-extension/src/debug/commonUtils.ts
- packages/vscode-extension/src/debug/localTelemetryReporter.ts
- packages/vscode-extension/src/telemetry/extTelemetryEvents.ts
- calculate the duration that vscode is in control and send in debug-all event
- refactor `LocalDebugSession`
> chore: send gap duration for local debug

- packages/fx-core/src/common/localizeUtils.ts
This is to avoid empty UI before strings are localized as reported in this GitHub issue: https://github.com/OfficeDev/TeamsFx/issues/5352
> chore: use default string when string is not localized

- templates/bot/csharp/command-and-response/GettingStarted.txt
- templates/bot/csharp/default/Bot/TeamsMessageExtension.cs.tpl
- templates/bot/csharp/default/GettingStarted.txt
- templates/bot/csharp/notification-function-base/GettingStarted.txt
- templates/bot/csharp/notification-webapi/GettingStarted.txt
- templates/tab/csharp/default/GettingStarted.txt
Make the getting started doc simpler. 
The helpful content in this document will be moved to documentation where we can provide visuals, better formatting, code samples, and other helpful links.
> docs: Trim the volume of instructions to get started

- packages/vscode-extension/src/debug/localTelemetryReporter.ts
- packages/vscode-extension/src/debug/prerequisitesHandler.ts
- packages/vscode-extension/src/debug/teamsfxTaskHandler.ts
- packages/vscode-extension/src/telemetry/extTelemetryEvents.ts
- add `debug-prereqs-check-npm-install` to track whether npm install is already installed
- add `duration` to `debug-npm-install`
First time:
Second time:
> chore: improve npm install telemetry

- templates/bot/csharp/command-and-response/Commands/HelloWorldCommandHandler.cs.tpl
Fix [Bug 14865241](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/14865241): [VS Bug Bash] Command handler code path not hit in default template
E2E TEST: N/A
> fix(template): command bot unable to be triggerred in R0 Teams client

- packages/fx-core/src/plugins/resource/appstudio/index.ts
- packages/fx-core/src/plugins/resource/appstudio/utils/telemetry.ts
There is a question for publish, which only build the package. Update telemetry to treat it as build event.
> fix: differentiate manual publish

- packages/fx-core/src/plugins/resource/bot/dotnet/plugin.ts
- packages/fx-core/src/plugins/resource/frontend/dotnet/plugin.ts
Fix https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/14869344
In case `appsettings.development.json` is git ignored so let F5 to generate one. Fix both Tab and Bot projects.
E2E TEST: N/A
> fix: able to f5 .net project without appsettings.development.json

- packages/vscode-extension/src/debug/localTelemetryReporter.ts
- packages/vscode-extension/src/debug/teamsfxDebugProvider.ts
- packages/vscode-extension/src/debug/teamsfxTaskHandler.ts
- packages/vscode-extension/src/handlers.ts
Remove `remote` property because only local debug sends these events.
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/14549235
> chore: remove redundant is-remote from "debug-all"

- packages/vscode-extension/src/debug/localTelemetryReporter.ts
- packages/vscode-extension/src/extension.ts
- packages/vscode-extension/src/handlers.ts
- packages/vscode-extension/src/telemetry/extTelemetryEvents.ts
Handle concurrent F5 telemetry (user stops debugging in preLaunchTasks and hits F5 again immediately).
Send `debug-concurrent-correlation-id` so we can check whether this property is empty in BI to determine concurrent cases.
> chore: improve concurrent localdebug telemetry

- templates/bot/csharp/command-and-response/AdapterWithErrorHandler.cs.tpl
- templates/bot/csharp/command-and-response/Commands/HelloWorldCommandHandler.cs.tpl
- templates/bot/csharp/command-and-response/Controllers/BotController.cs.tpl
- templates/bot/csharp/command-and-response/TeamsBot.cs.tpl
- templates/bot/csharp/notification-function-base/AdapterWithErrorHandler.cs.tpl
- templates/bot/csharp/notification-function-base/MessageHandler.cs.tpl
- templates/bot/csharp/notification-function-base/TeamsBot.cs.tpl
- templates/bot/csharp/notification-trigger-http/NotifyHttpTrigger.cs.tpl
- templates/bot/csharp/notification-trigger-timer/NotifyTimerTrigger.cs.tpl
- templates/bot/csharp/notification-webapi/AdapterWithErrorHandler.cs.tpl
- templates/bot/csharp/notification-webapi/Controllers/BotController.cs.tpl
- templates/bot/csharp/notification-webapi/Controllers/NotificationController.cs.tpl
- templates/bot/csharp/notification-webapi/TeamsBot.cs.tpl
Work item - https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/14865259/
To keep consistency with VS C# templates, move `using` statements out of namespace.
> chore: move using out of namespace

- packages/vscode-extension/src/debug/teamsfxTaskHandler.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/14549235
> fix: missing await for local debug telemetry

- packages/fx-core/src/component/code/apiCode.ts
- packages/fx-core/src/component/code/tabCode.ts
- packages/fx-core/src/component/constants.ts
- packages/fx-core/src/component/core.ts
- packages/fx-core/src/component/feature/api.ts
- packages/fx-core/src/component/migrate.ts
- packages/fx-core/src/component/resource/azureAppService/azureAppService.ts
- packages/fx-core/src/component/resource/azureAppService/azureFunction.ts
- packages/fx-core/src/core/FxCore.ts
- packages/fx-core/src/core/middleware/questionModelV3.ts
A tab + api function project's component list will be like:
```
"components": [
{
"name": "teams-tab",
"hosting": "azure-storage",
"build": true,
"provision": true,
"folder": "tabs",
"connections": [
"teams-api"
],
"artifactFolder": "tabs\\build"
},
{
"name": "azure-storage",
"connections": [
"teams-tab"
],
"provision": true
},
{
"name": "teams-api",
"hosting": "azure-function",
"functionNames": [
"getUserProfile"
],
"build": true,
"folder": "api",
"artifactFolder": "api"
},
{
"name": "azure-function",
"connections": [
"teams-api"
]
}
],
```
> chore(v3): add, provision and deploy function api 

- templates/bot/csharp/command-and-response/GettingStarted.txt
- templates/bot/js/command-and-response/README.md
- templates/bot/js/command-and-response/src/index.js
- templates/bot/ts/command-and-response/src/index.ts
Fix bugs:
- [(P1) Out-of-date comments in Teams Toolkit bot example](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/14897457)
- [(P2) [VS Bug Bash] helloWorld command is inconsistently defined](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/14865374)
E2E TEST: N/A
> fix: fix wording in bot template

- packages/fx-core/src/plugins/resource/bot/appStudio/appStudio.ts
- packages/fx-core/src/plugins/resource/bot/utils/telemetry-helper.ts
1. The url property is recognized as a user file path.
2. To avoid dependency cycle, use the `getAppStudioEndpoint()` in common
> fix(bot): mask url in api error event

- packages/fx-core/src/plugins/resource/officeaddin/config/projectsJsonData.ts
Using `path.join` instead of `+` to make it work on other OS
Tested the extension by creating an Office-Addin.
> fix: making path concatenations work on other OS

- packages/fx-core/src/component/code/spfxTabCode.ts
- packages/fx-core/tests/component/workflow.test.ts
- packages/fx-core/tests/plugins/resource/spfx/unit/scaffold.test.ts
Fix this issue: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/14937377
E2E TEST: tests/e2e/spfx/CreateSPFxProject.tests.ts
> fix: more than 1 configurable tab after spfx scaffolding

- .github/workflows/teamsjs-released.yml
A basic pipeline that will be triggered by @microsoft/teams-js releases.
Tasks like sending notification email and update dependency version of templates will be added later.
> chore: add pipeline that is triggered by teams-js repo

- packages/cli/package-lock.json
- packages/cli/src/cmds/capability.ts
- packages/cli/src/constants.ts
- packages/cli/src/helpParamGenerator.ts
- packages/cli/src/questionUtils.ts
- packages/cli/src/yargsCommand.ts
- packages/cli/tests/e2e/bot/TabAddCommandBot.ts
- packages/cli/tests/unit/cmds/capability.tests.ts
- packages/fx-core/.nycrc
- packages/fx-core/package-lock.json
- packages/fx-core/src/plugins/solution/fx-solution/v2/getQuestions.ts
- packages/fx-core/tests/plugins/solution/solution.getQuestions.test.ts
- packages/vscode-extension/package-lock.json
1. Refine the `add-feature` question generator in `fx-core` to support the `CLI_HELP` platform.
2. Use the `add-feature` stage in `fx-cli` instead of the `add-capability` stage.
3. Directly get questions in the `teamsfx add [capability]` builder function, not use `helpParamGenerator`.
4. Modify an E2E test case for the bug 14924542.
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/14924542
E2E TEST: https://github.com/OfficeDev/TeamsFx/actions/runs/2654421779
> fix(cli): use add-feature instead of add-capability

- packages/fx-core/src/plugins/solution/fx-solution/v2/getQuestions.ts
E2E TEST: N/A
Fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/14959889/
> fix(bot): fix message extension cannot add default bot

- packages/fx-core/resource/package.nls.json
- packages/fx-core/src/component/fx/preDeployAction.ts
- packages/fx-core/src/component/fx/preProvisionAction.ts
- packages/fx-core/src/plugins/resource/utils4v2.ts
- packages/fx-core/src/plugins/solution/fx-solution/arm.ts
- packages/fx-core/src/plugins/solution/fx-solution/constants.ts
- packages/fx-core/src/plugins/solution/fx-solution/v2/provision.ts
- packages/fx-core/src/plugins/solution/fx-solution/v3/deploy.ts
- packages/fx-core/src/plugins/solution/fx-solution/v3/provision.ts
- packages/fx-core/tests/component/workflow.test.ts
- packages/fx-core/tests/plugins/solutionv3/solution.provision.test.ts
This PR is to allow users to reprovision azure resources in the new sub after switching sub since last provision. Previously, we will always use the subscription info from state so that users won't be able to provision resources in the new sub.
In this PR, we will
- Compare subscription from output (state file) with the sub id from user input. If different, we will ask users to confirm whether they will provision all resources in new sub. 
- To make sure reprovision can work successfully, we need new resource suffix and base name. We need a new aad app for bot service.
pass existing e2e test: https://github.com/OfficeDev/TeamsFx/actions/runs/2668858700
E2E TEST: NA
> feat: allow reprovision in new sub 

- packages/fx-core/src/plugins/resource/spfx/utils/telemetry-helper.ts
Fix https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/14949183
> chore: use sendErrorTelemetry for error events in spfx plugin

- packages/fx-core/src/core/middleware/envInfoWriter.ts
- packages/fx-core/src/core/middleware/envInfoWriterV3.ts
Users may cancel provision when selecting sub or rg before we ask for the provision consent. We should skip write env info in such cases.
E2E TEST: N/A
run e2e tests: https://github.com/OfficeDev/TeamsFx/actions/runs/2687957529
> fix: env info writer

- packages/fx-core/src/component/code/spfxTabCode.ts
> fix: run yeoman by generator name when checker disabled

- packages/fx-core/src/plugins/resource/bot/configs/localDebugConfig.ts
- packages/fx-core/src/plugins/resource/bot/plugin.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/14937591
Bot plugin didn't respect existing bot aads in local debug stage.
> chore: respect existing bot aad for localdebug

- packages/vscode-extension/src/handlers.ts
Move the port checker from `pre-debug-check` to `validate-dependencies`. So the port checker will be called once in both 2.x.x and 3.x.x, 4.x.x TeamsFx project.
Detail: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/14924654
> chore(localdebug): remove duplicate port checker

- packages/cli/src/activate.ts
- packages/cli/src/cmds/provision.ts
- packages/cli/tests/e2e/solution/ProvisionWithInvalidSubscriptionInfoJsonContent.tests.ts
- packages/cli/tests/e2e/solution/ProvisionWithLoggedOutSubscriptionInfo.tests.ts
- packages/cli/tests/unit/cmds/provision.tests.ts
Fix cli provision issue. 
Bug: if user signed into account A and set subscription sub1, and then logged out and logged in with account B, provision will fail since we will check whether user has access to sub1.
E2E TEST: https://github.com/OfficeDev/TeamsFx/runs/7534887528?check_suite_focus=true
https://github.com/OfficeDev/TeamsFx/runs/7534999345?check_suite_focus=true (new case)
> fix: logout and reprovision in cli

- packages/fx-core/resource/package.nls.json
- packages/fx-core/src/component/core.ts
- packages/fx-core/src/plugins/solution/fx-solution/solution.ts
- packages/fx-core/src/plugins/solution/fx-solution/v2/provisionLocal.ts
- packages/fx-core/src/plugins/solution/fx-solution/v2/utils.ts
- packages/fx-core/src/plugins/solution/fx-solution/v3/provision.ts
- packages/fx-core/tests/component/workflow.test.ts
- packages/vscode-extension/src/debug/depsChecker/doctorConstant.ts
- packages/vscode-extension/src/debug/prerequisitesHandler.ts
- Allow to switch m365 tenant when local debugging. 
- Updated vscode output when we found users switch m365 tenant. (words may be updated later.)
E2E TEST: https://github.com/OfficeDev/TeamsFx/actions/runs/2751657861
> feat: enable switch tenant for local debug

- packages/fx-core/src/core/question.ts
Keep consistent sequence of capability options when creating a new project.
Related bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/15067351
E2E TEST: N/A
> fix(core): order of capability question options

- packages/fx-core/src/common/telemetry.ts
- packages/fx-core/src/common/template-utils/templatesActions.ts
1. Add central telemetry for code templates scaffolding.
2. Add telemetry property to detect fallback cases.
https://dev.azure.com/msazure/Microsoft%20Teams%20Extensibility/_workitems/edit/15066484
> chore: add telemetry for code templates

- docs/sdk/teamsfx.channel.sendadaptivecard.md
- docs/sdk/teamsfx.channel.sendmessage.md
- docs/sdk/teamsfx.member.sendadaptivecard.md
- docs/sdk/teamsfx.member.sendmessage.md
- docs/sdk/teamsfx.notificationtarget.sendadaptivecard.md
- docs/sdk/teamsfx.notificationtarget.sendmessage.md
- docs/sdk/teamsfx.sendadaptivecard.md
- docs/sdk/teamsfx.sendmessage.md
- docs/sdk/teamsfx.teamsbotinstallation.sendadaptivecard.md
- docs/sdk/teamsfx.teamsbotinstallation.sendmessage.md
- packages/dotnet-sdk/src/TeamsFx/Conversation/Channel.cs
- packages/dotnet-sdk/src/TeamsFx/Conversation/INotificationTarget.cs
- packages/dotnet-sdk/src/TeamsFx/Conversation/Member.cs
- packages/dotnet-sdk/src/TeamsFx/Conversation/MessageResponse.cs
- packages/dotnet-sdk/src/TeamsFx/Conversation/TeamsBotInstallation.cs
- packages/sdk/review/teamsfx.api.md
- packages/sdk/src/conversation/interface.ts
- packages/sdk/src/conversation/notification.browser.ts
- packages/sdk/src/conversation/notification.ts
- packages/sdk/test/unit/node/conversation/notification.spec.ts
- packages/sdk/test/unit/node/conversation/testUtils.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/15087878/
Add `MessageResponse` to represent the return value of `sendMessage` and `sendAdaptiveCard` calls.
Applied to both Node.js and .NET SDKs.
> chore: adjust return value of notification APIs

- packages/vscode-extension/src/controls/openWelcomePage.ts
Related bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/15127861
E2E TEST: N/A
> fix(vsc): trigger-from when welcome page is shown after installation

- packages/vscode-extension/src/controls/SampleGallery.tsx
- packages/vscode-extension/src/controls/sampleDetailPage.tsx
- packages/vscode-extension/src/telemetry/extTelemetryEvents.ts
Add following telemetry events:
1> When user click sample app card with app id attached
2> When user click 'View in GitHub' button in sample detail page with app id attached
> chore: add telemetry for sample gallery

- packages/dotnet-sdk/src/TeamsFx.Test/Conversation/CommandResponseMiddlewareTest.cs
- packages/dotnet-sdk/src/TeamsFx/Conversation/RegExpTrigger.cs
The command trigger should return `false` if the input is `null`.
E2E TEST: N/A (covered by UI test)
> fix(command-bot): shouldTrigger should return false if input is null

- packages/fx-core/src/common/deps-checker/internal/funcToolChecker.ts
fix bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/15204559/
> fix: set error to warning when func v3 and node 16

- packages/fx-core/src/common/constants.ts
- packages/fx-core/src/common/featureFlags.ts
- packages/fx-core/src/component/questionV3.ts
- packages/fx-core/src/plugins/resource/spfx/index.ts
- packages/fx-core/src/plugins/resource/spfx/utils/constants.ts
- packages/fx-core/src/plugins/resource/spfx/v2/index.ts
- packages/fx-core/src/plugins/solution/fx-solution/v2/executeUserTask.ts
- packages/fx-core/src/plugins/solution/fx-solution/v2/getQuestions.ts
1. Add feature flag for spfx multi-tab support feature: TEAMSFX_SPFX_MULTI_TAB
2. Allow users to add spfx tab when clicking 'Add feature' button for spfx project
Screenshot:
1. v3: off + spfx_multi_tab: off + azure project
2. v3: off + spfx_multi_tab: on+ azure project
3. v3: on+ spfx_multi_tab: on+ azure project
1. v3: off + spfx_multi_tab: on+ spfx project
2. v3: on+ spfx_multi_tab: on+ spfx project
1. v3: off + spfx_multi_tab: off + spfx project
E2E TEST: only for vsc extension
> feat: allow user to add spfx feature for spfx project

- packages/vscode-extension/package.nls.json
- packages/vscode-extension/src/debug/depsChecker/doctorConstant.ts
- packages/vscode-extension/src/debug/prerequisitesHandler.ts
- packages/vscode-extension/src/telemetry/extTelemetryEvents.ts
Show notification in VS Code if user chooses to use another account for local debug.
E2E TEST: N/A
> feat: notification when switch account for local debug in vs code

- packages/dotnet-sdk/src/TeamsFx/Configuration/ConfigurationMethods.cs
Temporary remove BotAuthenticationOption from AddTeamsFx() method.
This method requires RazorPages service so we may need further discussion on whether we should let users call AddTeamsFx() for every projects that uses TeamsFx SDK. The major concern is user might not use RazorPages and cause error during initialization.
We can add BotAuthenticationOption back if that's OK after discussion.
> chore: remove BotAuthenticationOption from AddTeamsFx() method

- packages/fx-core/src/component/code/tabCode.ts
E2E TEST: https://github.com/OfficeDev/TeamsFx/blob/38aaa61289701fdc85c7f7d725ac0d4862488520/packages/cli/tests/e2e/frontend/BlazorAppHappyPath.v3.tests.ts#L34
> fix(v3): wrong build output path

- docs/fx-core/arm/arm-help.md
Didn't find this as Windows is case insensitive. Update the path to ensure GitHub can display the image correctly.
> docs: fix image path in doc

- packages/fx-core/templates/bicep/azureFunction.provision.module.bicep
- packages/fx-core/templates/bicep/azureWebApp.provision.module.bicep
Just realize we also need to add app service provision failure workaround to V3 code.
> chore: workaround app service provision failure in V3 api

- templates/tab/js/m365/package.json
- templates/tab/ts/m365/package.json
E2E TEST: N/A
Similar issue here: https://github.com/OfficeDev/TeamsFx-Samples/pull/402
> fix: add back dependencies to support npm version under 6

- packages/fx-core/resource/package.nls.json
- packages/fx-core/src/component/feature/bot.ts
- packages/fx-core/src/component/questionV3.ts
- packages/fx-core/src/component/resource/appManifest/utils.ts
- packages/fx-core/src/core/question.ts
- packages/fx-core/src/plugins/resource/appstudio/manifestTemplate.ts
- packages/fx-core/src/plugins/resource/bot/constants.ts
- packages/fx-core/src/plugins/resource/bot/enums/pluginActRoles.ts
- packages/fx-core/src/plugins/resource/bot/resources/strings.ts
- packages/fx-core/src/plugins/resource/bot/v2/common.ts
- packages/fx-core/src/plugins/solution/fx-solution/question.ts
- packages/fx-core/src/plugins/solution/fx-solution/v2/executeUserTask.ts
- packages/fx-core/src/plugins/solution/fx-solution/v2/getQuestions.ts
- packages/fx-core/src/plugins/solution/fx-solution/v2/utils.ts
- packages/fx-core/tests/component/feature/bot.test.ts
- packages/fx-core/tests/component/questionv3.test.ts
- packages/fx-core/tests/component/resource/appManifest/manifestUtils.test.ts
- packages/fx-core/tests/core/question.test.ts
- packages/fx-core/tests/plugins/resource/bot/unit/configs/scaffoldConfig.test.ts
- packages/fx-core/tests/plugins/resource/bot/unit/question.test.ts
- packages/fx-core/tests/plugins/resource/bot/unit/v2/common.test.ts
- packages/fx-core/tests/plugins/solution/solution.getQuestions.test.ts
- Support create a workflow bot project in VSC
- Also, `Add Features` is supported to add a workflow bot to an existing TeamsFx project (e.g. tab)
Note: currently only `TypeScript` is supported, and `JavaScript` project will be supported in the upcoming pr.
E2E TEST: N/A
> feat: support create and add workflow bot in VSC toolkit

- packages/fx-core/src/component/feature/tab.ts
- packages/fx-core/templates/bicep/azureWebApp.provision.orchestration.bicep
- packages/fx-core/tests/component/feature/tab.test.ts
E2E TEST: https://github.com/OfficeDev/TeamsFx/blob/dev/packages/cli/tests/e2e/frontend/BlazorAppHappyPath.tests.ts#L46
> fix: missing tab state configs in vs

- templates/bot/ts/workflow/package.json
Set the `@microsoft/teamsfx` package version to `1.1.2-alpha`, will change to official version when it is ready for public release.
> chore: set teamsfx sdk to alpha version in workflow bot

- packages/fx-core/src/component/telemetry.ts
- packages/fx-core/templates/bicep/azureFunction.provision.module.bicep
- packages/fx-core/tests/component/resource/botService.test.ts
E2E TEST: https://github.com/OfficeDev/TeamsFx/blob/a60ccbd7382893af421723268230b21ca45d0482/packages/cli/tests/e2e/bot/ProvisionFuncHostedNotificationBot.dotnet.tests.ts#L9
> fix: missing app setting in bot bicep

- packages/cli/tests/e2e/frontend/BlazorAppHappyPath.v3.tests.ts
Auth endpoint app setting has been removed by this PR: https://github.com/OfficeDev/TeamsFx/pull/5984
> test: remove auth endpoint in blazor app setting

- .github/workflows/e2e-test.yml
The test case `tests/e2e/bot/ProvisionAppServiceNotificationBot.tests.ts` needs more than 900s.
Increare the timeout.
Success run: https://github.com/OfficeDev/TeamsFx/runs/8182676137?check_suite_focus=true
E2E TEST: https://github.com/OfficeDev/TeamsFx/blob/aafbd90da64e10da018013ab6d8cb4e85ad51b35/packages/cli/tests/e2e/bot/ProvisionAppServiceNotificationBot.v3.tests.ts#L11
> fix(e2e): increase the e2e test case timeout to 1200s

- packages/fx-core/resource/package.nls.json
- packages/fx-core/src/common/telemetry.ts
- packages/fx-core/src/component/provisionUtils.ts
- packages/fx-core/src/core/middleware/envInfoWriter.ts
- packages/fx-core/src/plugins/solution/fx-solution/constants.ts
- packages/fx-core/tests/component/provisionUtils.test.ts
- return error if user just specify rg name in config file but miss subscription id of the resource group.
- add telemetry for subscription type
> chore: error result when only resource group name is provided in config file

- docs/sdk/teamsfx.teamsfx._constructor_.md
- packages/sdk/review/teamsfx.api.md
- packages/sdk/src/core/teamsfx.browser.ts
- packages/sdk/src/core/teamsfx.ts
E2E TEST: N/A
Add an AuthenticatonConfiguration to customConfig in constructor of TeamsFx, so that user can get some property prompts of configurations while creating an instance of TeamsFx class.
> feat(sdk): add AuthenticatonConfiguration to customConfig

- packages/fx-core/src/component/provisionUtils.ts
- packages/fx-core/tests/component/provisionUtils.test.ts
- use selected subscription id if user is passing resource group name from cli parameter
> chore: should not use subscription id from config if user just pass resource group through cli

- packages/vscode-extension/package-lock.json
- packages/vscode-extension/package.json
- packages/vscode-extension/src/debug/taskTerminal/localTunnelTaskTerminal.ts
In windows, if a child process in Node.js spawn their own child processes, `kill()` method will not kill the child process’s own child processes. e.g. `this.childProc?.kill()` only kill the child process `cmd` bit not kill the grand child process `ngrok`.
Use `tree-kill` package to kill all the sub process.
Detail: https://stackoverflow.com/questions/32705857/cant-kill-child-process-on-windows
E2E TEST: none
> fix(localdebug): kill the child process of ngrok task

- packages/vscode-extension/package.json
- packages/vscode-extension/src/debug/constants.ts
- packages/vscode-extension/src/debug/taskTerminal/baseTaskTerminal.ts
- packages/vscode-extension/src/debug/taskTerminal/localTunnelTaskTerminal.ts
- packages/vscode-extension/src/extension.ts
1. Use `$teamsfx-local-tunnel-watch` instead of `$teamsfx-ngrok-watch`
2. Both `${teamsfx:workspaceFolder}` and `${workspaceFolder}` can work. PS: vscode will auto resolve the  `${workspaceFolder}` when `isBackground = false`
3. Both `${command:fx-extension.get-ngrok-path}` and `${teamsfx:ngrokBinFolder}` can work
4. Add new command `${command:fx-extension.get-local-tunnel-endpoint}`
> chore(localdebug): add new localdebug task variables

- packages/dotnet-sdk/src/TeamsFx.Test/Conversation/CardActionBotTest.cs
- packages/dotnet-sdk/src/TeamsFx.Test/Conversation/CardActionMiddlewareTest.cs
- packages/dotnet-sdk/src/TeamsFx.Test/Microsoft.TeamsFx.Test.csproj
- packages/dotnet-sdk/src/TeamsFx/Conversation/AdaptiveCardResponse.cs
- packages/dotnet-sdk/src/TeamsFx/Conversation/CardActionBot.cs
- packages/dotnet-sdk/src/TeamsFx/Conversation/CardActionMiddleware.cs
- packages/dotnet-sdk/src/TeamsFx/Conversation/CardActionOptions.cs
- packages/dotnet-sdk/src/TeamsFx/Conversation/CommandBot.cs
- packages/dotnet-sdk/src/TeamsFx/Conversation/ConversationBot.cs
- packages/dotnet-sdk/src/TeamsFx/Conversation/ConversationOptions.cs
- packages/dotnet-sdk/src/TeamsFx/Conversation/IAdaptiveCardActionHandler.cs
- packages/dotnet-sdk/src/TeamsFx/Conversation/InvokeResponseContentType.cs
- packages/dotnet-sdk/src/TeamsFx/Conversation/InvokeResponseErrorCode.cs
- packages/dotnet-sdk/src/TeamsFx/Conversation/InvokeResponseFactory.cs
Sample card action handler with the SDK:
```csharp
using AdaptiveCards.Templating;
using Microsoft.Bot.Builder;
using Microsoft.TeamsFx.Conversation;
using Newtonsoft.Json;
using VSWorkflowBot.Models;
namespace VSWorkflowBot.CardActions
{
public class DoStuffActionHandler : IAdaptiveCardActionHandler
{
private string _triggerVerb = "doStuff";
private AdaptiveCardResponse _adaptiveCardResponse = AdaptiveCardResponse.ReplaceForInteractor;
private readonly string _responseCardFilePath = Path.Combine(".", "Resources", "DoStuffActionResponse.json");
public string TriggerVerb
{
get => _triggerVerb;
set => _triggerVerb = value;
}
public AdaptiveCardResponse AdaptiveCardResponse
{
get => _adaptiveCardResponse;
set => _adaptiveCardResponse = value;
}
public async Task<InvokeResponse> …
```
> feat(sdk): add dotnet sdk for adaptive card actions

- packages/vscode-extension/src/debug/prerequisitesHandler.ts
- in case solution.teamsAppTenantId is undefined, get tenant id from aad and appstudio
Mainly for local debug transparency, since there will be no solution states.
> chore(debug): improve switching m365 tenant

- packages/vscode-extension/src/debug/prerequisitesHandler.ts
- packages/vscode-extension/src/debug/taskTerminal/npmInstallTaskTerminal.ts
Support relative path in `cwd` of npm install task
E2E TEST: none
> fix(localdebug): support relative path in npm install task

- packages/vscode-extension/src/debug/prerequisitesHandler.ts
Use different node checker according to project settings
E2E TEST: none
> fix(localdebug): get node version from project settings

- packages/fx-core/src/plugins/solution/fx-solution/debug/util/launch.ts
- packages/fx-core/src/plugins/solution/fx-solution/debug/util/launchNext.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/15525732/
Hide debug console for all browser "launch" sessions. (Keep debug console for bot/backend services).
E2E TEST: N/A (covered by UI test)
> fix: hide debug console for teams web client

- packages/fx-core/src/plugins/solution/fx-solution/debug/util/ngrok.ts
- packages/fx-core/tests/plugins/solution/debug/util/ngrok.test.ts
Remove the trailing slash for `config.addr`.
E2E TEST: none
> fix: remove trailing slash for source addr and dist addr

- packages/dotnet-sdk/src/TeamsFx/Conversation/NotificationBot.cs
- packages/dotnet-sdk/src/TeamsFx/Conversation/SearchScope.cs
- packages/dotnet-sdk/src/TeamsFx/Conversation/TeamsBotInstallation.cs
Work item: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/15344675/
Add following methods to notification bot:
* `FindMemberAsync`
* `FindAllMembersAsync`
* `FindChannelAsync`
* `FindAllChannelsAsync`
E2E TEST: N/A
> feat(sdk): add methods to find member/channel

- templates/bot/csharp/command-and-response/AdapterWithErrorHandler.cs.tpl
- templates/bot/csharp/notification-function-base/AdapterWithErrorHandler.cs.tpl
- templates/bot/csharp/notification-webapi/AdapterWithErrorHandler.cs.tpl
- templates/bot/csharp/workflow/AdapterWithErrorHandler.cs.tpl
Fix  [Bug 15565115](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/15565115): [VisualStudio] If card is not found, bot fails with no good exception.
The bot will send an message activity with the error message if encounter an unhandled error. This is also align with the TS/JS template.
E2E TEST: N/A
> chore(template): send error message for unhandled error in bot adapter

- packages/vscode-extension/src/handlers.ts
- packages/vscode-extension/test/extension/handlers.test.ts
Fix the bug of installing Azure Functions binding extension.
E2E TEST: https://github.com/OfficeDev/TeamsFx-UI-Test/blob/b9efaf1b8fb1da058ef01a8f08e2d0f390de2239/src/ui-test/localdebug/localdebug-function.test.ts#L11
> fix(localdebug): return dotnet bin folder dir

- packages/sdk-react/src/useGraph.ts
When UIRequiredError occurs, needConsent is set to true so it calls teamsfx.login() at the next reload to ask for user consent. So far so good. The problem is: after the user gives the necessary consent, needConsent flag is not cleared, so subsequent reloads will keep calling teamsfx.login and showing popup window that will automatically disappear.
This change fixes the issue - when consent is granted, login function won't be called.
> Clear needConsent flag after successful login

- packages/fx-core/src/plugins/solution/fx-solution/debug/util/launch.ts
- packages/fx-core/src/plugins/solution/fx-solution/debug/util/launchNext.ts
Totally hide debug console.
There's a corner case that due to sequence, the browser debug console still shows when bot debug console is activated, so hide bot debug console as well to avoid such case.
> chore: hide debug console for bot

- packages/vscode-extension/src/debug/commonUtils.ts
Hide core log "start task:getProjectConfigV3" during F5.
> chore: hide core log for local debug

- packages/fx-core/src/component/utils/common.ts
- packages/fx-core/tests/component/utils.test.ts
Add utility to expand environment variables for V3's new placeholder syntax.
It doesn't support escaping for now. We can enrich the functionality in the future if there's explicit requirement.
> chore: add utility to expand environment variables

- templates/bot/js/command-and-response/src/helloworldCommandHandler.js
- templates/bot/js/workflow/src/commands/helloworldCommandHandler.js
- templates/bot/ts/command-and-response/src/helloworldCommandHandler.ts
- templates/bot/ts/workflow/src/commands/helloworldCommandHandler.ts
Replace `MessageBuilder` API with `MessageFactory` and `CardFactory` which is provided by the official bot-builder SDK.
E2E TEST: N/A
> chore: remove MessageBuilder from bot template

- packages/fx-core/src/component/code/utils.ts
* Error message is logged twice. Stop logging `error.message` in execute method.
* Npm pushes error message to standard output, log it to output channel as error message error occurs.
https://github.com/OfficeDev/TeamsFx/issues/6202
E2E TEST: no need
> fix: print standard output to error channel when error occurs

- packages/sdk/src/credential/appCredential.ts
- packages/sdk/test/unit/node/appCredential.spec.ts
appCredential needs authorityHost URL,, however, currently implementation do not check whether authorityHost exists, this PR fix this issue
> perf: appCredential add missing authorityHost check

- packages/vscode-extension/src/qm/vsc_ui.ts
- packages/vscode-extension/test/extension/userInterface.test.ts
- packages/vscode-extension/test/mocks/vscode-mock.ts
Related bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/15772677
E2E TEST: N/A
> fix(vsc): select workspace folder canceled in WSL

- packages/vscode-extension/src/debug/taskTerminal/baseTaskTerminal.ts
detail: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/15801223
E2E TEST: https://github.com/OfficeDev/TeamsFx-UI-Test/blob/64c2a05105bba54198d6c4e2f1372d7fecbdb8d7/src/ui-test/localdebug/localdebug-bot.test.ts#L29
> fix(localdebug): add missing import in baseTaskTerminal

- templates/bot/csharp/notification-function-base/Properties/serviceDependencies.json
- templates/bot/csharp/notification-function-base/Properties/serviceDependencies.local.json
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/15789527/
Remove appinsights from VS notification bot, since we do not provision app insights instance, and local debug does not require it as well.
> chore: remove appinsights service dependency

- packages/fx-core/package-lock.json
- packages/fx-core/package.json
- packages/server/package-lock.json
- packages/server/package.json
@microsoft/adaptivecards-tools	v1.1.0-rc.0
@microsoft/teamsfx-api	v0.20.7-rc.0
@microsoft/teamsfx-cli	v1.1.3-rc.0
@microsoft/teamsfx-core	v1.17.0-rc.0
@microsoft/teamsfx	v1.2.1-rc.0
@microsoft/teamsfx-react	v1.0.6-rc.0
ms-teams-vscode-extension	v4.1.0-rc.0
feat(vsc): add support for untrusted workspace (#6279) 540807041
feat(vsc): add tutorial for card action response (#6261) 242e92b52
feat: support both spfx 1.15 and 1.16 beta  (#6150) 0d532389e
> chore: merge back to main

- packages/vscode-extension/src/handlers.ts
ADO:
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/15833260/
Screenshot:
Before:
After:
After Azure sign in and sign out, the account displays correctly
E2E TEST: NA
> fix: azure display name empty when sign out and sign in again

- packages/sdk/test/e2e/node/teamsBotSsoPrompt.spec.ts
E2E TEST: https://github.com/OfficeDev/TeamsFx/actions/runs/3247829129
`tokenExchangeResource.uri` is not used any more for sso bot, so remove this check to fix e2e test failed
> fix: teamsBotSsoPrompt e2e test failed

- packages/vscode-extension/package.nls.json
- packages/vscode-extension/src/commonlib/azureLogin.ts
- packages/vscode-extension/src/error.ts
Add display message when encountering Azure account cache problem.
Fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_dashboards/dashboard/b7e7b190-a7fb-4c70-89f1-e63796c991c5
> chore: add display message when encountering login cache error

- docs/sdk/teamsfx.gettediousconnectionconfig.md
- packages/sdk/CHANGELOG.md
- packages/sdk/review/teamsfx.api.md
- packages/sdk/src/core/defaultTediousConnectionConfiguration.browser.ts
- packages/sdk/src/core/defaultTediousConnectionConfiguration.ts
Since SDK 2.0 wants to keep backward compatibility to let users easily upgrade the package, will deprecate SQL support instead of remove it in SDK 2.0.
> chore: deprecate getTediousConnectionConfig

- packages/fx-core/src/component/core.ts
- packages/fx-core/tests/component/core.test.ts
@microsoft/teamsfx-cli	v1.1.3-rc.2
@microsoft/teamsfx-core	v1.17.0-rc.2
ms-teams-vscode-extension	v4.1.0-rc.2
E2E TEST: N/A
> fix(core): use projectId in inputs if available

- packages/fx-core/src/component/feature/bot/bot.ts
Related bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/15874934
E2E TEST: N/A
> fix(core): show success notification when adding bot + me

- packages/dotnet-sdk/CHANGELOG.md
- packages/dotnet-sdk/README.md
- packages/dotnet-sdk/src/TeamsFx/Conversation/CardActionMiddleware.cs
- packages/dotnet-sdk/src/TeamsFx/Conversation/IAdaptiveCardActionHandler.cs
- packages/dotnet-sdk/src/TeamsFx/Microsoft.TeamsFx.csproj
- templates/bot/csharp/workflow/CardActions/DoStuffActionHandler.cs.tpl
- templates/bot/csharp/workflow/ProjectName.csproj.tpl
Changes:
1. Add usage document for adaptive card actions dotnet SDK.
2. Update dotnet SDK change log to prepare `1.2.0-rc` release
3. Simplify `IAdaptiveCardActionHandler` interface and update template accordingly
E2E TEST: N/A
> chore: tweak dotnet workflow bot SDK and template

- packages/fx-core/src/component/resource/appManifest/utils/utils.ts
- packages/fx-core/tests/component/resource/appManifest/utils.test.ts
- if personal/group tab, we will scaffold tab capability
- if bot/message extension, we will scaffold bot capability
- if meeting extension, we will just have manifest.
> chore: check app capability code to scaffold based on app definition

- packages/fx-core/src/common/tools.ts
- packages/vscode-extension/src/debug/localTelemetryReporter.ts
- packages/vscode-extension/src/debug/prerequisitesHandler.ts
- packages/vscode-extension/src/debug/taskTerminal/localTunnelTaskTerminal.ts
- packages/vscode-extension/src/debug/taskTerminal/npmInstallTaskTerminal.ts
- packages/vscode-extension/src/debug/taskTerminal/prerequisiteTaskTerminal.ts
- packages/vscode-extension/src/debug/taskTerminal/setUpBotTaskTerminal.ts
- packages/vscode-extension/src/telemetry/extTelemetryEvents.ts
- packages/vscode-extension/test/localdebug/data/oldTab/.vscode/tasks.json
- packages/vscode-extension/test/localdebug/localTelemetryReporter.test.ts
1. Add `method` and `status-code` of check sideloading permission api into event `CheckSideloading`
2. Update the condition of `debug-is-transparent-task`  (task.json includes any teamsfx command)
3. Add `debug-task-args` and `task-id` into prerequisite check events
4. Add `debug-task-args` to `debug-start-local-tunnel-task-started` event
5. Add `debug-ngrok-log` (error message in the terminal) to the `debug-start-local-tunnel-task-started` error event
5. remove `bot-password` in the `debug-task-args`
> chore(localdebug): add more properties in localdebug telemetry

- packages/fx-core/src/component/debugHandler/appManifest.ts
- packages/fx-core/src/component/resource/appManifest/appStudio.ts
- packages/fx-core/tests/component/debugHandler/appManifest.test.ts
- packages/fx-core/tests/component/resource/appManifest/appstudio.test.ts
- We used to generate a new Teams app id if local debug with a different account from same tenant. Add this logic back to the new local debug workflow.
E2E TEST: https://github.com/OfficeDev/TeamsFx/actions/runs/3317743455
> fix: create new teams app if account in same tenant

- packages/fx-core/src/common/samples-config.json
sample gallery has breaking change with this PR
https://github.com/OfficeDev/TeamsFx-Samples/pull/515
Next sprint release will release v1.1.0 tag.
> chore: sample gallery release v1.1.0

- packages/vscode-extension/package.json
Update `args` schema to make it can be empty
E2E TEST: none
> fix(localdebug): make local debug task args can be empty

- packages/fx-core/resource/package.nls.json
- packages/fx-core/src/common/constants.ts
- packages/fx-core/src/component/debugHandler/bot.ts
- packages/fx-core/src/component/resource/appManifest/appStudioClient.ts
- packages/fx-core/tests/component/debugHandler/bot.test.ts
- Add error message when get bot failed but the bot id is from env
- Also created a new aka.ms link which pointed to the same help doc while keeping the old aka.ms link valid also.
TODO: update doc
> chore: add bot get failed error message

- packages/fx-core/src/plugins/resource/appstudio/constants.ts
- packages/fx-core/src/plugins/resource/appstudio/devPreviewManifest.ts
- packages/fx-core/src/plugins/resource/officeaddin/config/projectProperties.json
- packages/fx-core/src/plugins/resource/officeaddin/index.ts
- packages/manifest/src/manifest.ts
Add code to put in content into the extensions section of the manifest template based on the office-addin template (currently only json case one available).
> chore: add extensions content to manifest generation

- packages/fx-core/src/component/driver/aad/update.ts
- packages/fx-core/src/component/driver/aad/utility/aadAppClient.ts
1. Create single tenant AAD app by default. This can be changed by manifest later.
2. Output actual manifest first when update AAD app for better troubleshooting experience.
> chore: imporve UX for AAD drivers

- templates/bot/csharp/workflow/ProjectName.csproj.tpl
Fix [Bug 16102416](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/16102416): Workflow bot template in VS doesn't work
E2E TEST: N/A
> chore(template): fix workflow bot project csproj

- packages/fx-core/src/common/telemetry.ts
- packages/fx-core/src/core/downloadSample.ts
ADO: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/16110752
E2E TEST: NA
> chore: fix the telemetry property to new-project-id when download sample

- packages/cli/tests/e2e/cicd/VerifyGeneratedTemplates.v3.tests.ts
Adapt e2e case for v3.
E2E TEST: https://github.com/OfficeDev/TeamsFx/blob/c2ab6f418e38a877956cb9e429c0a6fadd924b51/packages/cli/tests/e2e/cicd/VerifyGeneratedTemplates.v3.tests.ts#L28
> fix: adapt cicd case for v3

- packages/dotnet-sdk/src/TeamsFx/Conversation/ITurnContextExtensions.cs
- packages/dotnet-sdk/src/TeamsFx/Conversation/NotificationBot.cs
- packages/dotnet-sdk/src/TeamsFx/Conversation/TeamsBotInstallation.cs
Fix the fallback logic to get teams id, related fix for node SDK: https://github.com/OfficeDev/TeamsFx/pull/6393
> chore(dotnet-sdk): tweak the notification bot sdk

- packages/fx-core/src/component/driver/env/appsettingsGenerate.ts
- packages/fx-core/src/component/driver/env/interface/generateAppsettingsArgs.ts
- packages/fx-core/tests/component/driver/env/generateAppsettings.test.ts
Add generate appsettings driver for VS local debug.
Examples
- TAB
No need to add appsettings/generate
- SSO TAB
```
- uses: appsettings/generate
with:
target: <project-name>/appsettings.Development.json
appsettings:
TeamsFx:
Authentication:
ClientId: ${{Client_Id}}
ClientSecret: ${{Client_Secret}}
OAuthAuthority: ${{OAuth_Authority}}
```
- SSO BOT
```
- uses: appsettings/generate
with:
target: <project-name>/appsettings.Development.json
appsettings:
BOT_ID: ${{BOT_ID}}
BOT_PASSWORD: ${{BOT_PASSWORD}}
TeamsFx:
Authentication:
ClientId: ${{Client_Id}}
ClientSecret: ${{Client_Secret}}
OAuthAuthority: ${{OAuth_Authority}}
ApplicationIdUri: ${{Application_Id_Uris}}
Bot:
InitiateLoginEndpoint: ${{Bot_Endpoint}}/bot-auth-start
```
This part has not been fully tested; I will test it in the VS …
> chore: add generate appsettings driver

- packages/fx-core/src/component/middleware/envMW.ts
- packages/fx-core/tests/component/envUtil.test.ts
An improvement for https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/16198497 to restore env vars that exist before execution.
> chore: restore existing env var's value

- templates/scenarios/js/sso-tab/.appserviceIgnore
- templates/scenarios/js/sso-tab/teamsfx/app.yml
The Teams app / AAD app output folder is same with tab app, ignore their output
> chore: ignore manifest file and app package in tab build output folder

- packages/cli/src/cmds/m365/m365.ts
- packages/cli/src/cmds/m365/packageService.ts
- packages/cli/tests/unit/cmds/m365/m365.tests.ts
- packages/cli/tests/unit/cmds/m365/packageService.tests.ts
Package service has updated the API to support retrieving title id by manifest id.
So update our logic as well, to reduce API calls.
> chore: get title id by manifest id

- packages/fx-core/resource/package.nls.json
- packages/fx-core/src/component/driver/aad/update.ts
- packages/fx-core/tests/component/driver/aad/testAssets/manifestWithMissingEnv.json
- packages/fx-core/tests/component/driver/aad/update.test.ts
Tell user a environment variable required by the manifest is missing to help better understand the error:
> chore: validate aad manifest before update

- packages/manifest/src/manifest.ts
- packages/manifest/test/index.test.ts
- packages/vscode-extension/src/hoverProvider.ts
1) upgrade manifest version to 1.15
2) Remove command from local hover, as the previous command is deprecated.
> chore: remove uri from hover message

- templates/scenarios/js/m365-tab/package.json.tpl
- templates/scenarios/js/sso-tab/package.json.tpl
- templates/scenarios/ts/m365-tab/package.json.tpl
- templates/scenarios/ts/sso-tab/package.json.tpl
This workaround is introduced by https://github.com/OfficeDev/TeamsFx/pull/4893
Latest `teamsfx-react` has resolved the issue.
> chore: revoke workaround: source map not found

- packages/fx-core/src/common/deps-checker/internal/funcToolChecker.ts
- packages/fx-core/src/common/deps-checker/internal/ngrokChecker.ts
Update ngrok version to support node 18.
node 18 is preview in Azure Function Core Tools. 
Node 18, global installed Azure Function Core Tools v3
PS: If ngrok has been installed, we will not upgrade the existing ngrok.
> chore(localdebug): support node 18 in deps checker

- packages/fx-core/src/component/resource/spfx/depsChecker/generatorChecker.ts
ADO: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/16270913
E2E TEST: NA
> fix: spfx fail when space exist in directory

- packages/fx-core/resource/package.nls.json
- packages/fx-core/src/common/tools.ts
- packages/fx-core/src/core/FxCore.ts
- packages/fx-core/src/core/error.ts
- packages/fx-core/src/core/middleware/videoFilterAppBlocker.ts
- packages/fx-core/tests/common/tools.test.ts
- packages/fx-core/tests/core/middleware/VideoFilterAppBlockerMW.test.ts
- packages/vscode-extension/src/handlers.ts
The list of blocked commands:
* Provision in the cloud
* Zip Teams metadata package
* Deploy to the cloud
* Publish to Teams
* Add features
* Validate manifest file
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/16037816/
> chore: block unsupport commands for video filter

- templates/scenarios/csharp/command-and-response/appPackage/manifest.template.json.tpl
- templates/scenarios/csharp/message-extension/appPackage/manifest.template.json.tpl
- templates/scenarios/csharp/non-sso-tab/appPackage/manifest.template.json.tpl
- templates/scenarios/csharp/notification-http-timer-trigger/appPackage/manifest.template.json.tpl
- templates/scenarios/csharp/notification-http-trigger/appPackage/manifest.template.json.tpl
- templates/scenarios/csharp/notification-timer-trigger/appPackage/manifest.template.json.tpl
- templates/scenarios/csharp/notification-webapi/appPackage/manifest.template.json.tpl
- templates/scenarios/csharp/sso-tab/appPackage/manifest.template.json.tpl
- templates/scenarios/csharp/workflow/appPackage/manifest.template.json.tpl
downgrade to v1.14, as app with 1.15 manifest cannot be found in Outlook/Office.
> chore: rollback to 1.14 for outlook/office

- packages/fx-core/src/component/resource/appManifest/constants.ts
- packages/fx-core/src/component/resource/appManifest/utils/ManifestUtils.ts
- packages/fx-core/tests/component/resource/appManifest/manifestUtils.test.ts
1) Only set default developer when placeholder exists and without endpoint.
2) V3 do not need this logic, as samples/templates don't have placeholders for developer.
> fix: bot only project developer

- packages/vscode-extension/src/handlers.ts
- packages/vscode-extension/test/extension/handlers.test.ts
Fix this bug: 
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_sprints/taskboard/AuthAndData/Microsoft%20Teams%20Extensibility/CY22-11.1?workitem=16341439
E2E TEST: N/A
> fix: local state file not found message is incorrect

- packages/vscode-extension/package.json
For work item: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/15553173
> chore: disable icon for v3 manifest

- packages/fx-core/src/component/resource/appManifest/utils/utils.ts
- packages/fx-core/src/core/FxCore.ts
- packages/fx-core/src/core/telemetry.ts
- packages/fx-core/tests/component/resource/appManifest/utils.test.ts
- packages/vscode-extension/src/commonlib/codeFlowLogin.ts
- packages/vscode-extension/src/commonlib/m365Login.ts
- packages/vscode-extension/src/handlers.ts
- packages/vscode-extension/test/extension/handlers.test.ts
- When given loginHint (currently there should be only two scenarios, 1. user clicks a button on developer portal. 2. user is from ITP), we will redirect user to sign in with that account directly    
- If we could find account in msal cache, will get token silently first and then acquire token interactively
- If we could not find the account in msal cache, we will redirect to "login" page with the loginHint rather than "select-account"
- Move telemetry of features of teams app from Develop Portal from vscode-extension to core, so it will be reusable when we later work on VS.
> chore: sign in with loginHint

- packages/fx-core/src/component/constants.ts
- packages/fx-core/src/component/coordinator/index.ts
- packages/fx-core/src/component/developerPortalScaffoldUtils.ts
- packages/fx-core/src/component/resource/appManifest/utils/utils.ts
- packages/fx-core/src/core/middleware/questionModel.ts
- packages/fx-core/tests/component/coordinator.test.ts
- packages/fx-core/tests/component/developerPortalScaffoldUtils.test.ts
- Since we have removed source code not required for bot from default-bot template, and removed code not needed for message extension from me template, we have added another template for a project with both bot and message extension capabilities. [chore: bot with me template by yuqizhou77 · Pull Request #7020 · OfficeDev/TeamsFx (github.com](https://github.com/OfficeDev/TeamsFx/pull/7020)
- This PR is to add this new template in code.
> chore: scaffold bot with message extension when from TDP

- packages/fx-core/src/component/question.ts
- packages/vscode-extension/src/handlers.ts
Keep consistent behavior for `Add feature` and `Scaffold` naming AB test.
work item: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/16370676/
> chore(abtest): update template wording for add feature

- packages/cli/src/cmds/m365/packageService.ts
- packages/cli/tests/unit/cmds/m365/m365.tests.ts
- packages/cli/tests/unit/cmds/m365/packageService.tests.ts
According to package service, need to call `/config/v1/environment` to detect service url by tenant.
> chore: detect env for package service

- .github/workflows/cd.yml
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
> chore: change github action output to env

- packages/cli/src/cmds/preview/preview.ts
- packages/fx-core/src/common/local/constants.ts
- packages/fx-core/src/common/local/localEnvManager.ts
- packages/fx-core/src/component/debugHandler/localEnvProvider.ts
- packages/fx-core/tests/common/local/localEnvManager.test.ts
- packages/vscode-extension/src/debug/prerequisitesHandler.ts
Previously after F5, `.env.teamsfx.local` will be generated in `tabs` folder which should be in `app` folder for video filter. This will cause ssl cert not loaded in Vite which cause video filter failing to load.
Tested on Windows
> fix: .env.teamsfx.local path for video filter app for cert

- packages/fx-core/src/common/deps-checker/internal/vxTestAppChecker.ts
The executable file path of test app is different on macOS. [Also](https://www.electronjs.org/docs/latest/tutorial/application-distribution#with-prebuilt-binaries)
> chore: fix macOS executable name for vxTestApp checker

- packages/vscode-extension/src/handlers.ts
Since the user can't see the entrance of the dashboard tab in v3, it would be a bit strange if can still see the tutorial entrance.
For this reason, I would like to remove the dashboard tutorial entry in v3.
- In V2:
- In V3
E2E TEST: N/A
> chore: remove the dashboard tutorial entry in V3

- packages/vscode-extension/webpack.config.js
Video filter test app will get stuck when first run in a clean environment.
It is because Electron has [special logic](https://www.electronjs.org/docs/latest/tutorial/asar-archives#node-api) for *.asar files when calling `fs` APIs like `fs.stat`, `fs.writeFile`. So when extracting a zip which contains files like app.asar, Adm Zip library fails on `fs.stat` and it doesn't handle the error so the promise never resolves or rejects. So it get stuck.
This issue can be solved by using `original-fs` (a Electron builtin package) instead of `fs` from [Electron document](https://www.electronjs.org/docs/latest/tutorial/asar-archives#treating-an-asar-archive-as-a-normal-file). 
AdmZip has already [added support](https://github.com/cthackers/adm-zip/pull/153) for this specific scenario. It will …
> fix: stuck when extracting files with .asar suffix

- .github/detect/excludes.txt
- docs/cicd/azdo/cd.azure.yml
- docs/cicd/azdo/cd.spfx.yml
- docs/cicd/azdo/ci.yml
- docs/cicd/azdo/provision.azure.yml
- docs/cicd/azdo/provision.spfx.yml
- docs/cicd/azdo/publish.yml
- docs/cicd/github/cd.azure.yml
- docs/cicd/github/cd.spfx.yml
- docs/cicd/github/ci.yml
- docs/cicd/github/provision.azure.yml
- docs/cicd/github/provision.spfx.yml
- docs/cicd/github/publish.yml
- docs/cicd/jenkins/Jenkinsfile.azure.cd
- docs/cicd/jenkins/Jenkinsfile.azure.provision
- docs/cicd/jenkins/Jenkinsfile.ci
- docs/cicd/jenkins/Jenkinsfile.publish
- docs/cicd/jenkins/Jenkinsfile.spfx.cd
- docs/cicd/jenkins/Jenkinsfile.spfx.provision
- docs/cicd/others/cd.azure.sh
- docs/cicd/others/cd.spfx.sh
- docs/cicd/others/ci.sh
- docs/cicd/others/provision.azure.sh
- docs/cicd/others/provision.spfx.sh
- docs/cicd/others/publish.sh
**Split cicd templates into four categories:**
1. GitHub
2. Azure DevOps
3. Jenkins
4. Others (Based on scripts)
In each category, **split provsion and cd by azure and spfx** making two copies.
CICD Howto Guides will reference these templates directly.
> chore: prepare templates for cicd how to guides

- packages/fx-core/src/component/driver/botFramework/createOrUpdateBot.ts
- packages/fx-core/src/component/driver/botFramework/interface/createOrUpdateBotFrameworkBotArgs.ts
- packages/fx-core/src/component/resource/botService/appStudio/interfaces/IBotRegistration.ts
- packages/fx-core/src/component/resource/botService/botRegistration/utils.ts
- packages/fx-core/tests/component/driver/botFramework/createOrUpdateBot.test.ts
```yml
- uses: botFramework/create # Create or update the bot registration on dev.botframework.com
with:
botId: ${{BOT_ID}}
name: bot
messagingEndpoint: ${{BOT_ENDPOINT}}/api/messages
description: ""
channels:
- name: msteams
- name: outlook
```
> chore(debug): support configuring channels when creating or updating bot

- packages/fx-core/templates/core/v3Migration/js.ts.app.local.yml
- packages/fx-core/tests/core/middleware/testAssets/v3Migration/debug/transparent-sso-tab/expected/app.local.yml
- packages/fx-core/tests/core/middleware/testAssets/v3Migration/debug/transparent-tab-bot-func/expected/app.local.yml
- packages/fx-core/tests/core/middleware/testAssets/v3Migration/debug/transparent-tab/expected/app.local.yml
This reverts commit 19856c41b8661c4c4f5037491fd846aa4593b1cd.
Revert this change because `#` in `.env` is well handled by #7244.
> chore(debug-migration): revert wrap indexPath with quotes

- packages/fx-core/src/core/middleware/projectMigratorV3.ts
- packages/fx-core/src/core/middleware/utils/debug/taskMigrator.ts
- packages/fx-core/tests/core/middleware/debug/taskMigrator.test.ts
- packages/fx-core/tests/core/middleware/testAssets/v3Migration/debug/V3.5.0-V4.0.6-command/expected/tasks.json
- packages/fx-core/tests/core/middleware/testAssets/v3Migration/debug/V3.5.0-V4.0.6-notification-trigger/expected/tasks.json
- packages/fx-core/tests/core/middleware/testAssets/v3Migration/debug/V3.5.0-V4.0.6-tab-bot-func/expected/tasks.json
- packages/fx-core/tests/core/middleware/testAssets/v3Migration/debug/beforeV3.4.0-bot/expected/tasks.json
- packages/fx-core/tests/core/middleware/testAssets/v3Migration/debug/beforeV3.4.0-tab-bot-func/expected/tasks.json
V4.0.6 Source
```
{
"label": "start ngrok",
"dependsOn": "teamsfx: ngrok start"
},
```
V4.0.6 Target
```
{
"label": "start ngrok",
"dependsOn": [
"Start local tunnel"
]
},
{
// Start the local tunnel service to forward public ngrok URL to local port and inspect traffic.
// See https://aka.ms/teamsfx-local-tunnel-task for the detailed args definitions,
// as well as samples to:
//   - use your own ngrok command / configuration / binary
//   - use your own tunnel solution
//   - provide alternatives if ngrok does not work on your dev machine
"label": "Start local tunnel",
"type": "teamsfx",
"command": "debug-start-local-tunnel",
"args": {
"ngrokArgs": "http 3978 --log=stdout --log-format=logfmt",
"env": "local",
"output": {
// Keep consistency with migrated configuration.
"endpoint": …
```
> chore(localdebug): migrate teamsfx:ngrok-start to v3

- .github/workflows/cd.yml
- packages/fx-core/scripts/download-templates-zip.js
https://github.com/OfficeDev/TeamsFx/actions/runs/3709042721/jobs/6287239111
https://github.com/OfficeDev/TeamsFx/actions/runs/3690487224/jobs/6247536027
Downloading templates in cd pipeline sometimes failed for 403 error, which may cause by [GitHub API rate limit](https://docs.github.com/en/rest/overview/resources-in-the-rest-api?apiVersion=2022-11-28#requests-from-github-actions).
Adding authorization header to the request may fix the issue.
> chore: authenticate downloading template

- templates/bot/js/command-and-response/package.json
- templates/bot/js/default/package.json
- templates/bot/js/m365/package.json
- templates/bot/js/notification-restify/package.json
- templates/bot/js/workflow/package.json
- templates/bot/ts/command-and-response/package.json
- templates/bot/ts/default/package.json
- templates/bot/ts/m365/package.json
- templates/bot/ts/notification-restify/package.json
- templates/bot/ts/workflow/package.json
- templates/scenarios/js/command-and-response/package.json.tpl
- templates/scenarios/js/default-bot-message-extension/package.json.tpl
- templates/scenarios/js/default-bot/package.json.tpl
- templates/scenarios/js/m365-message-extension/package.json.tpl
- templates/scenarios/js/message-extension/package.json.tpl
- templates/scenarios/js/non-sso-tab-default-bot/bot/package.json.tpl
- templates/scenarios/js/notification-restify/package.json.tpl
- templates/scenarios/js/workflow/package.json.tpl
- templates/scenarios/ts/command-and-response/package.json.tpl
- templates/scenarios/ts/default-bot-message-extension/package.json.tpl
- templates/scenarios/ts/default-bot/package.json.tpl
- templates/scenarios/ts/m365-message-extension/package.json.tpl
- templates/scenarios/ts/message-extension/package.json.tpl
- templates/scenarios/ts/non-sso-tab-default-bot/bot/package.json.tpl
- templates/scenarios/ts/notification-restify/package.json.tpl
- templates/scenarios/ts/workflow/package.json.tpl
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/16598471/
https://github.com/restify/node-restify/releases/tag/v10.0.0
Update all bot templates to use `restify:10` which supports node 18
> chore: upgrate restify to support node 18

- packages/fx-core/scripts/download-templates-zip.js
- packages/fx-core/src/common/templates-config.json
Setup project may fail for 403 error because the API request over rate limit.
https://github.com/OfficeDev/TeamsFx/actions/runs/3709042721/jobs/6287239111
> chore: download templates 403 for GitHub API rate limit

- templates/bot/ts/command-and-response/tsconfig.json
- templates/bot/ts/default/tsconfig.json
- templates/bot/ts/m365/tsconfig.json
- templates/bot/ts/notification-restify/tsconfig.json
- templates/bot/ts/workflow/tsconfig.json
- templates/scenarios/ts/command-and-response/tsconfig.json
- templates/scenarios/ts/default-bot-message-extension/tsconfig.json
- templates/scenarios/ts/default-bot/tsconfig.json
- templates/scenarios/ts/m365-message-extension/tsconfig.json
- templates/scenarios/ts/message-extension/tsconfig.json
- templates/scenarios/ts/non-sso-tab-default-bot/bot/tsconfig.json
- templates/scenarios/ts/notification-restify/tsconfig.json
- templates/scenarios/ts/workflow/tsconfig.json
Related to https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/16598471/
Use `es2017` in ts bot templates to ensure `async function` is kept during building, which is required by `restify:10`.
Otherwise it throws:
E2E TEST: N/A
> fix: fix compatibility issue with restify

- packages/fx-core/src/core/middleware/utils/appYmlGenerator.ts
- packages/fx-core/templates/core/v3Migration/csharp.app.yml
- packages/fx-core/tests/core/middleware/testAssets/v3Migration/csharpNonSsoTab/expectedResult/app.yml
- packages/fx-core/tests/core/middleware/testAssets/v3Migration/csharpSsoTab/expectedResult/app.yml
@microsoft/teamsfx-cli	v1.2.1-rc.0
@microsoft/teamsfx-core	v1.22.0-rc.1
@microsoft/teamsfx-react	v2.1.1-rc.0
ms-teams-vscode-extension	v4.2.1-rc.0
> fix: add hardcoded vs tab indexpath to migrated project

- packages/vscode-extension/src/handlers.ts
- packages/vscode-extension/test/extension/handlers.test.ts
Since the dashboard scenario was only supported in v2, and the tutorial portal was not visible in v3, but now that the dashboard v3 migration has been completed, the dashboard tutorial entry can be exposed.
E2E TEST: N/A
> chore: expose dashboard tutorial entry in v3

- packages/fx-core/src/common/tools.ts
- packages/fx-core/src/component/resource/appManifest/appStudioClient.ts
- packages/fx-core/src/component/resource/appManifest/authSvcClient.ts
- packages/fx-core/src/component/resource/botService/appStudio/appStudioClient.ts
- packages/fx-core/tests/plugins/resource/appstudio/unit/authSvcClient.test.ts
Get region from AuthSvc API, response.data.regionGtms.teamsDevPortal
Set base url for:
1) AppStudioClient of app manifest
2) AppStudioClient of bot
3) getSideloadingStatus api
> chore: use regional api

- packages/run-utils/package-lock.json
- packages/run-utils/package.json
- packages/run-utils/src/index.ts
Make run-utils to support new folder structure.
Follow the same logic as #7321 to load `projectId` as key.
> chore: run.js supports new structure

- packages/cli/tests/commonlib/appStudioValidator.ts
- packages/cli/tests/e2e/commonUtils.ts
- packages/cli/tests/e2e/function/TestAddFunction.tests.ts
- packages/cli/tests/e2e/multienv/TestRemoteHappyPath.tests.ts
- packages/cli/tests/e2e/multienv/TestRemoteHappyPathSPFx.tests.ts
Enable publish test case, clean up stagged app from Teams app catalog to avoid BadRequest error.
> chore: delete published app

- packages/fx-core/resource/package.nls.json
- packages/fx-core/src/component/configManager/error.ts
- packages/fx-core/src/component/configManager/interface.ts
- packages/fx-core/src/component/configManager/parser.ts
- packages/fx-core/tests/component/configManager/parser.test.ts
- packages/fx-core/tests/component/configManager/testing_data/invalid_env_folder_path.yml
- packages/fx-core/tests/component/configManager/testing_data/valid_env_folder_path.yml
Fixes https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_sprints/taskboard/Teams%20Extensibility%20E2E%20Team/Microsoft%20Teams%20Extensibility/CY22-12.2?workitem=16624820
> chore: add environmentFolderPath support to parser

- packages/vscode-extension/src/debug/taskTerminal/localTunnelTaskTerminal.ts
Fix issue: https://github.com/OfficeDev/TeamsFx/issues/7354
E2E TEST: https://github.com/OfficeDev/TeamsFx-UI-Test/blob/39cfd2d02c2d331930a7bb53325ec29e709ae781/src/ui-test/localdebug/localdebug-bot.test.ts#L13
> fix(localdebug): support whitespaces in the ngrok path

- packages/vscode-extension/src/debug/commonUtils.ts
Fix https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/16737880/.
> chore(debug-migration): throw exception to stop debugging if migration is cancelled

- templates/scenarios/common/init-debug-vsc-bot/{%dotVscodeFolderName%}/tasks.json
- templates/scenarios/common/init-debug-vsc-tab/{%dotVscodeFolderName%}/tasks.json
Use `.*` as endsPattern to not block F5.
More doc will be added to `init debug` wiki.
Help link will be added after wiki aka link is ready.
> chore: update endspattern for init debug

- packages/fx-core/src/core/middleware/projectMigratorV3.ts
- packages/vscode-extension/src/debug/teamsfxTaskProvider.ts
> chore(debug-migration): improve the experience of migration not enabled

- packages/vscode-extension/src/debug/teamsfxDebugProvider.ts
- templates/scenarios/js/m365-message-extension/.vscode/launch.json
- templates/scenarios/js/m365-tab/.vscode/launch.json
- templates/scenarios/ts/m365-message-extension/.vscode/launch.json
- templates/scenarios/ts/m365-tab/.vscode/launch.json
Fix https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/16740084.
> chore(debug-v3): support remote launch for m365 v3 templates

- packages/fx-core/src/component/coordinator/index.ts
- packages/fx-core/src/component/driver/index.ts
- Enable `m365Title/acquire` action.
- This requires m365 account so add to `M365Actions`
work item: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/16764452/
> chore: enable m365 action

- .github/workflows/graph-toolkit-released.yml
Related PR in graph toolkit repo can be found here: https://github.com/microsoftgraph/microsoft-graph-toolkit/pull/1994
> chore: add graph toolkit release notification workflow

- packages/adaptivecards-tools-sdk/package.json
- packages/adaptivecards-tools-sdk/src/AdaptiveCard.tsx
- packages/adaptivecards-tools-sdk/src/jsxExamples.tsx
E2E TEST: none
TypeScript infers HTML element to be `JSX.Element` from @types/react, so we have to export @types/react as a dependency, which may cause the issue [15204137](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/15204137/).
Use `any` to avoid the type inference.
Reference: https://github.com/OfficeDev/TeamsFx/pull/4783
> fix(adaptive-card): move @types/react to devDeps

- packages/fx-core/resource/package.nls.json
- packages/fx-core/src/component/driver/file/updateJson.ts
- packages/fx-core/src/component/driver/index.ts
- packages/fx-core/templates/core/v3Migration/csharp.app.local.yml
- packages/fx-core/templates/core/v3Migration/js.ts.app.local.yml
- packages/fx-core/tests/component/driver/file/generateAppsettings.test.ts
- packages/fx-core/tests/core/middleware/testAssets/v3Migration/debug/beforeV3.4.0-tab-bot-func/expected/app.local.yml
- packages/fx-core/tests/core/middleware/testAssets/v3Migration/debug/beforeV3.4.0-tab/expected/app.local.yml
- templates/scenarios/common/init-debug-vs-bot/teamsapp.local.yml
- templates/scenarios/csharp/command-and-response/teamsapp.local.yml.tpl
- templates/scenarios/csharp/message-extension/teamsapp.local.yml.tpl
- templates/scenarios/csharp/notification-http-timer-trigger/teamsapp.local.yml.tpl
- templates/scenarios/csharp/notification-http-trigger/teamsapp.local.yml.tpl
- templates/scenarios/csharp/notification-timer-trigger/teamsapp.local.yml.tpl
- templates/scenarios/csharp/notification-webapi/teamsapp.local.yml.tpl
- templates/scenarios/csharp/sso-tab/teamsapp.local.yml.tpl
- templates/scenarios/csharp/workflow/teamsapp.local.yml.tpl
Better name `file/updateAppSettings` to `file/updateJson` since it actually can output any settings to JSON format.
Then this action can be used by `init debug` for those Node.js projects which use JSON file as config (e.g., [app-hello-world](https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/app-hello-world/nodejs))
> chore: rename updateAppSettings to updateJson

- packages/fx-core/src/component/utils.ts
@microsoft/teamsfx-cli	v1.2.2-rc.1
@microsoft/teamsfx-core	v1.23.0-rc.1
ms-teams-vscode-extension	v4.2.2-rc.1
E2E TEST: N/A
Fix this bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/16986609
> fix: output bicep issue if there is no teamsfx folder

- .github/workflows/e2e-test.yml
- .github/workflows/graph-toolkit-released.yml
- .github/workflows/sdk-e2e-test.yml
- .github/workflows/teamsjs-released.yml
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
> chore: replace set-output with GITHUB_OUTPUT

- packages/cli/src/cmds/preview/previewEnv.ts
Add `--open-only` to directly open web client without running local code, to support existing app scenario.
> chore: tweak v3 preview option

- templates/bot/csharp/command-and-response/TeamsBot.cs.tpl
- templates/bot/csharp/notification-function-base/TeamsBot.cs.tpl
- templates/bot/csharp/notification-webapi/TeamsBot.cs.tpl
- templates/bot/csharp/workflow/TeamsBot.cs.tpl
- templates/scenarios/csharp/command-and-response/TeamsBot.cs.tpl
- templates/scenarios/csharp/notification-http-timer-trigger/TeamsBot.cs.tpl
- templates/scenarios/csharp/notification-http-trigger/TeamsBot.cs.tpl
- templates/scenarios/csharp/notification-timer-trigger/TeamsBot.cs.tpl
- templates/scenarios/csharp/notification-webapi/TeamsBot.cs.tpl
- templates/scenarios/csharp/workflow/TeamsBot.cs.tpl
Fix [Bug 16826718](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/16826718): VS Bot templates should inherit from TeamsActivityHandler instead of IBot.
E2E TEST: N/A
> chore: use TeamsActivityHandler in csharp bot templates

- packages/fx-core/src/component/developerPortalScaffoldUtils.ts
- packages/fx-core/src/core/FxCoreImplementV3.ts
- packages/fx-core/src/core/middleware/questionModel.ts
- packages/fx-core/tests/component/developerPortalScaffoldUtils.test.ts
- the default localhost URL for a tab project in C# is different from the value put in JS/TS project, so need to remove hard-code part and get the value from downloaded template.
E2E TEST: N/A
> fix: update tab localhost URL if app from TDP

- packages/vscode-extension/src/debug/teamsfxDebugProvider.ts
From practice, if debug configuration type is `msedge`, `resolveDebugConfiguration` will be called twice. The type of the configuration in first time is `msedge` but `pwa-msedge` in second time.
If `url` is not specified in the configuration, the `url` in first time is `undefined` but `null` in second time.
To fix https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/17147943.
E2E TEST: N/A
> fix(debug): fix resolving msedge configuration without url

- .github/CODEOWNERS
- packages/cli/.gitignore
- packages/cli/src/cmds/index.ts
- packages/cli/src/cmds/upgrade.ts
- packages/cli/src/error.ts
- packages/cli/src/resource/index.ts
- packages/cli/src/resource/strings.json
- packages/cli/src/telemetry/cliTelemetryEvents.ts
- packages/cli/src/userInteraction.ts
- packages/cli/tests/unit/cmds/index.tests.ts
- packages/cli/tests/unit/cmds/upgrade.tests.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/16625425
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/16625428
When `TEAMSFX_V3="true"`, `teamsfx -h` will show (`teamsfx upgrade` is added):
```bash
C:\Users\zhiyou\source\zhiyouTestTab>teamsfx -h
teamsfx <command>
Commands:
teamsfx account <action>               Manage cloud service accounts. The supported cloud services
are 'Azure' and 'Microsoft 365'.
teamsfx new                            Create a new Teams application.
teamsfx provision                      Provision the cloud resources in the current application.
teamsfx deploy                         Deploy the current application.
teamsfx package                        Build your Teams app into a package for …
```
> chore(cli): teamsfx upgrade

- packages/vscode-extension/package-lock.json
- packages/vscode-extension/package.json
- packages/vscode-extension/src/commonlib/log.ts
1. Upgrade to VS Code 1.66 to leverage new feature [Output channel with custom language ID](https://code.visualstudio.com/updates/v1_66#_output-channel-with-custom-language-id)
2. Remove activationEvents "onStartupFinished" so that our extension will be activated automatically in non-teamsfx project.
3. Remove languages/mimetypes to prevent auto-onLanguage activation.
Related task: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/17137840
> chore(vsc): lazy load in non-teamsfx project

- packages/fx-core/src/component/utils/depsChecker/bicepChecker.ts
- packages/fx-core/tests/component/util/deps-checker/bicepChecker.test.ts
- Add timeout to all HTTP requests in bicep checker
- Handle network error while downloading bicep
Tested by disconnect network after bicep downloading starts
https://dev.azure.com/msazure/Microsoft%20Teams%20Extensibility/_workitems/edit/16677224
> fix: bicep checker hang if network error happens during downloading

- .github/CODEOWNERS
- add code owners for command, notification, workflow bot, and m365 v3 templates
> chore: add v3 templates code owners

- packages/fx-core/src/component/developerPortalScaffoldUtils.ts
- packages/fx-core/tests/component/developerPortalScaffoldUtils.test.ts
- packages/vscode-extension/src/handlers.ts
- templates/scenarios/js/non-sso-tab-default-bot/appPackage/manifest.json.tpl
- templates/scenarios/ts/non-sso-tab-default-bot/appPackage/manifest.json.tpl
- remove valid domains if the template
-  also remove it when creating projects from TDP
- noticed an issue as we add telemetry for GET api, so run .init before calling the GET api if the request is from TDP
> chore: remove valid domains and fix 

- packages/cli/src/userInteraction.ts
- packages/cli/src/utils.ts
- packages/fx-core/resource/package.nls.json
- packages/fx-core/src/core/error.ts
- packages/fx-core/src/core/middleware/projectMigratorV3.ts
- packages/fx-core/tests/core/middleware/projectMigrationV3.test.ts
Move an upgrade string to core resource file and check non-interactive in core. Related PR: https://github.com/OfficeDev/TeamsFx/pull/7829
https://dev.azure.com/msazure/Microsoft%20Teams%20Extensibility/_workitems/edit/17332172
> chore(cli+core): check non-interactive in the migration v3 middleware

- templates/bot/ts/notification-function-base/package.json
- templates/scenarios/csharp/notification-http-timer-trigger/appPackage/manifest.json.tpl
- templates/scenarios/csharp/notification-http-trigger/appPackage/manifest.json.tpl
- templates/scenarios/csharp/notification-timer-trigger/appPackage/manifest.json.tpl
- templates/scenarios/csharp/notification-webapi/appPackage/manifest.json.tpl
- templates/scenarios/js/notification-http-timer-trigger/appPackage/manifest.json.tpl
- templates/scenarios/js/notification-http-trigger/appPackage/manifest.json.tpl
- templates/scenarios/js/notification-restify/appPackage/manifest.json.tpl
- templates/scenarios/js/notification-timer-trigger/appPackage/manifest.json.tpl
- templates/scenarios/ts/notification-http-timer-trigger/appPackage/manifest.json.tpl
- templates/scenarios/ts/notification-http-timer-trigger/package.json.tpl
- templates/scenarios/ts/notification-http-trigger/appPackage/manifest.json.tpl
- templates/scenarios/ts/notification-http-trigger/package.json.tpl
- templates/scenarios/ts/notification-restify/appPackage/manifest.json.tpl
- templates/scenarios/ts/notification-restify/infra/azure.parameters.json.tpl
- templates/scenarios/ts/notification-timer-trigger/appPackage/manifest.json.tpl
- templates/scenarios/ts/notification-timer-trigger/package.json.tpl
Notification templates:
- Clear `validDomains` from manifest
- Upgrade `@azure/functions` dev dependency
- Correct resource base name
workitems:
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/17278612/
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/17235462/
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/17304899/
> chore: update notification templates

- templates/scenarios/common/init-debug-vsc-bot/{%dotVscodeFolderName%}/tasks.json
- templates/scenarios/js/command-and-response/.vscode/tasks.json
- templates/scenarios/js/default-bot-message-extension/.vscode/tasks.json
- templates/scenarios/js/default-bot/.vscode/tasks.json
- templates/scenarios/js/m365-message-extension/.vscode/tasks.json
- templates/scenarios/js/message-extension/.vscode/tasks.json
- templates/scenarios/js/non-sso-tab-default-bot/.vscode/tasks.json
- templates/scenarios/js/notification-http-timer-trigger/.vscode/tasks.json
- templates/scenarios/js/notification-http-trigger/.vscode/tasks.json
- templates/scenarios/js/notification-restify/.vscode/tasks.json
- templates/scenarios/js/notification-timer-trigger/.vscode/tasks.json
- templates/scenarios/js/workflow/.vscode/tasks.json
- templates/scenarios/ts/command-and-response/.vscode/tasks.json
- templates/scenarios/ts/default-bot-message-extension/.vscode/tasks.json
- templates/scenarios/ts/default-bot/.vscode/tasks.json
- templates/scenarios/ts/m365-message-extension/.vscode/tasks.json
- templates/scenarios/ts/message-extension/.vscode/tasks.json
- templates/scenarios/ts/non-sso-tab-default-bot/.vscode/tasks.json
- templates/scenarios/ts/notification-http-timer-trigger/.vscode/tasks.json
- templates/scenarios/ts/notification-http-trigger/.vscode/tasks.json
- templates/scenarios/ts/notification-restify/.vscode/tasks.json
- templates/scenarios/ts/notification-timer-trigger/.vscode/tasks.json
- templates/scenarios/ts/workflow/.vscode/tasks.json
Detail: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/17382761/
PS: The projects migrated from V4 will still use ngrok.
> chore(template): change ngrok to basis in V5 templates

- .github/workflows/cd.yml
https://github.com/OfficeDev/TeamsFx/actions/runs/4309172174/jobs/7516246063 
FATAL ERROR: MarkCompactCollector: young object promotion failed Allocation failed - JavaScript heap out of memory
> chore: update node space size while pack visx on CD pipeline

- packages/fx-core/src/component/coordinator/index.ts
- this property was missing in VSC telemetry and looks like it need to be a string.
> chore: fix telemetry in VSC

- packages/fx-core/src/common/samples-config-v3.json
- packages/vscode-extension/src/controls/SampleGallery.tsx
The sample id (dev-assist-dashboard) is initially set according to https://github.com/aycabas/dev-assist-dashboard. But when the PR is raised against Teamsfx-sample repo, the id is set as 'developer-assist-dashboard' (https://github.com/OfficeDev/TeamsFx-Samples/pull/715). So need to update it to avoid download error
> chore: update dev-assist-dashboard id and time

- packages/fx-core/src/component/driver/botAadApp/create.ts
`timeResult.milliseconds` is not what we expected.
It's just part of the overall duration and the right number should be:
`... + 1000 * timeResult.seconds + timeResult.milliseconds`.
So change to use `perf_hooks` which has a more natural APIs.
To fix https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/17519958.
feat: …
> chore: adjust duration

- packages/fx-core/src/common/tools.ts
- packages/fx-core/tests/common/tools.test.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_sprints/taskboard/AuthAndData/Microsoft%20Teams%20Extensibility/CY23-3.1?workitem=17451165
> chore: turn on V5 feature flag by default

- packages/fx-core/src/component/driver/interface/stepDriver.ts
Update action interface to accept output environment variable names.
Responsibility of YmlConfigManager:
1. Pass content of `writeToEnviornmentFile` to action
2. Write action's env output to environment file
Responsibility of Action:
1. Read required information based on `outputEnvVarNames`
2. Define action's env output based on `outputEnvVarNames`
> chore: update interface to define output names

- packages/vscode-extension/src/handlers.ts
- packages/vscode-extension/src/treeview/treeViewManager.ts
- packages/vscode-extension/test/extension/handlers.test.ts
1> Only keep CI/CD in 'view how-to guide ' for SPFx projects
2> Move 'Add web part' above 'view how-to guide' item
E2E TEST: NA
> feat: remove useless how-to guide for spfx

- .github/workflows/cd.yml
currently the following packages update the version to latest alpha.
cli 2.0.0-alpha
fx-core 2.0.0-alpha
vscode-extension 4.99.0-alpha
server 2.0.0-alpha
from now on, prerelease branch only release production with preid as beta
> chore: update CD to release beta version from prerelease branch

- packages/fx-core/src/component/developerPortalScaffoldUtils.ts
work item: [Bug 17449612](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/17449612): Create project from TDP would fail in VS if using new prerelease of fxcore
need to init telemetry for appStudio API when calling for project scaffolding from TDP
> chore: init app studio telemetry if creating app from TDP in VS

- packages/vscode-extension/src/debug/localTelemetryReporter.ts
- packages/vscode-extension/src/debug/taskTerminal/prerequisiteTaskTerminal.ts
- packages/vscode-extension/test/localdebug/localTelemetryReporter.test.ts
- packages/vscode-extension/test/localdebug/testUtils.ts
Send manifest/yml metadata events at the first of local debug in case of preqrequisites check failure.
To determine project type/capabilities for V5 local debug:
- For happy path: use metadata events in the actual action
- For users blocked by prerequisites check: use this metadata events to determine project type 
tasks.json metadata event will be added in another PR.
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/17518368/
> chore: add metadata events at the start of debug

- packages/fx-core/src/component/driver/prerequisite/installDriver.ts
- packages/fx-core/tests/component/driver/tools/installDriver.test.ts
sslCertFile, sslKeyFile, funcPath, dotnetPath are all optional
> chore: support outputEnvVarNames in prerequisite action

- templates/scenarios/csharp/sso-tab/teamsapp.local.yml.tpl
- templates/scenarios/csharp/sso-tab/teamsapp.yml.tpl
- templates/scenarios/js/m365-tab/teamsapp.local.yml.tpl
- templates/scenarios/js/m365-tab/teamsapp.yml.tpl
- templates/scenarios/js/sso-tab/teamsapp.local.yml.tpl
- templates/scenarios/js/sso-tab/teamsapp.yml.tpl
- templates/scenarios/ts/m365-tab/teamsapp.local.yml.tpl
- templates/scenarios/ts/m365-tab/teamsapp.yml.tpl
- templates/scenarios/ts/sso-tab/teamsapp.local.yml.tpl
- templates/scenarios/ts/sso-tab/teamsapp.yml.tpl
1. declare outputs for aadApp/create in templates
2. mark it as breaking change to bump the major version of our templates
BREAKING CHANGE: the `writeToEnvironmentFile` property will be required in the future, and there will also be other breaking changes recently. So mark this PR as breaking change to bump the major version of our templates.
> chore!: declare outputs for aadApp/create in templates

- packages/vscode-extension/src/debug/taskTerminal/launchTeamsClientTerminal.ts
No longer use the hard-coded variable name `TEAMS_APP_ID` to retrieve the app id since the variable name can be changed by user. Instead, we read it from the manifest file.
[User Story 17633932](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/17633932): Update codespaces launch-web-client task to not hard code TEAMS_APP_ID
E2E TEST: N/A
> chore: update launch Teams client task to get app id from manifest

- packages/fx-core/src/common/m365/constants.ts
- packages/fx-core/src/common/m365/launchHelper.ts
- packages/fx-core/tests/common/m365/launchHelper.test.ts
This utility can then be used in vsc and cli, which can reduce the redundant codes.
> chore: add launchHelper in core to get launch url

- packages/vscode-extension/src/debug/taskTerminal/launchTeamsClientTerminal.ts
To provide consistent user experience for remote preview between Codespaces and local dev environment, we need to allow selecting env in the `teamsfx: launch-web-client` task.
E2E TEST: N/A
> chore: allow select env for remote preview in Codespaces

- packages/fx-core/src/common/local/constants.ts
- packages/fx-core/src/core/middleware/utils/debug/taskMigrator.ts
- packages/fx-core/tests/core/middleware/debug/taskMigrator.test.ts
- packages/fx-core/tests/core/middleware/testAssets/v3Migration/debug/V3.5.0-V4.0.6-command/expected/tasks.json
- packages/fx-core/tests/core/middleware/testAssets/v3Migration/debug/V3.5.0-V4.0.6-notification-trigger/expected/tasks.json
- packages/fx-core/tests/core/middleware/testAssets/v3Migration/debug/V3.5.0-V4.0.6-tab-bot-func/expected/tasks.json
- packages/fx-core/tests/core/middleware/testAssets/v3Migration/debug/beforeV3.4.0-bot/expected/tasks.json
- packages/fx-core/tests/core/middleware/testAssets/v3Migration/debug/beforeV3.4.0-tab-bot-func/expected/tasks.json
- packages/fx-core/tests/core/middleware/testAssets/v3Migration/debug/transparent-bot/expected/tasks.json
- packages/fx-core/tests/core/middleware/testAssets/v3Migration/debug/transparent-m365-me/expected/tasks.json
- packages/fx-core/tests/core/middleware/testAssets/v3Migration/debug/transparent-notification/expected/tasks.json
- packages/fx-core/tests/core/middleware/testAssets/v3Migration/debug/transparent-sso-bot/expected/tasks.json
- packages/fx-core/tests/core/middleware/testAssets/v3Migration/debug/transparent-tab-bot-func/expected/tasks.json
- packages/vscode-extension/package.json
- packages/vscode-extension/src/debug/taskTerminal/devTunnelTaskTerminal.ts
- packages/vscode-extension/src/debug/taskTerminal/ngrokTunnelTaskTerminal.ts
sample:
```
{
"label": "Start local tunnel",
"type": "teamsfx",
"command": "debug-start-local-tunnel",
"args": {
"ngrokArgs": "http 3978 --log=stdout --log-format=logfmt",
"type": "ngrok",
"env": "local",
"writeToEnvironmentFile": {
// Keep consistency with upgraded configuration.
"endpoint": "PROVISIONOUTPUT__AZUREWEBAPPBOTOUTPUT__SITEENDPOINT",
"domain": "PROVISIONOUTPUT__AZUREWEBAPPBOTOUTPUT__DOMAIN"
}
},
"isBackground": true,
"problemMatcher": "$teamsfx-local-tunnel-watch"
}
```
> chore(localdebug): rename output to writeToEnvironmentFile in ngrok task

- packages/fx-core/src/component/debug/util/ngrok.ts
detail: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/17665830
Node.js switched the lookup order of DNS resolution from v17. Explicitly using IPv4 127.0.0.1 instead of localhost. 
(https://github.com/axios/axios/issues/3821)
E2E TEST: https://github.com/devdiv-azure-service-dmitryr/TeamsFx-UI-Test/blob/20a9d90ec46f128857e0fb023f71f0e45edced6d/src/ui-test/localdebug/localdebug-bot.test.ts#L29
> fix(v2): use 127.0.0.1 instead of localhost for node 18 to get ngrok url

- packages/fx-core/src/component/resource/appManifest/utils/ManifestUtils.ts
- packages/fx-core/tests/component/resource/appManifest/manifestUtils.test.ts
1) Escape unresolved placeholder check for manifest.id
2) Assign uuid if manifest.id is not valid
> chore: dynamic output name for teams app id

- .github/scripts/sync-version.js
beta release will change version to "3.0.0-beta.timestamp.0" so the carot can cover this case
> chore: sync up templates version support beta with carot

- packages/fx-core/templates/core/v3Migration/csharp.app.local.yml
- packages/fx-core/templates/core/v3Migration/csharp.app.yml
- packages/fx-core/templates/core/v3Migration/js.ts.app.local.yml
- packages/fx-core/tests/core/middleware/testAssets/v3Migration/csharpNonSsoTab/expectedResult/app.yml
- packages/fx-core/tests/core/middleware/testAssets/v3Migration/csharpSsoTab/expectedResult/app.yml
- packages/fx-core/tests/core/middleware/testAssets/v3Migration/debug/V3.5.0-V4.0.6-tab-bot-func/expected/app.local.yml
- packages/fx-core/tests/core/middleware/testAssets/v3Migration/debug/V3.5.0-V4.0.6-tab/expected/app.local.yml
- packages/fx-core/tests/core/middleware/testAssets/v3Migration/debug/beforeV3.4.0-tab-bot-func/expected/app.local.yml
- packages/fx-core/tests/core/middleware/testAssets/v3Migration/debug/beforeV3.4.0-tab/expected/app.local.yml
- packages/fx-core/tests/core/middleware/testAssets/v3Migration/debug/transparent-m365-tab/expected/app.local.yml
- packages/fx-core/tests/core/middleware/testAssets/v3Migration/debug/transparent-sso-tab/expected/app.local.yml
- packages/fx-core/tests/core/middleware/testAssets/v3Migration/debug/transparent-tab-bot-func/expected/app.local.yml
- packages/fx-core/tests/core/middleware/testAssets/v3Migration/debug/transparent-tab/expected/app.local.yml
- templates/scenarios/csharp/non-sso-tab/teamsapp.local.yml.tpl
- templates/scenarios/csharp/sso-tab/teamsapp.local.yml.tpl
- templates/scenarios/js/dashboard-tab/teamsapp.local.yml.tpl
- templates/scenarios/js/m365-tab/teamsapp.local.yml.tpl
- templates/scenarios/js/non-sso-tab-default-bot/teamsapp.local.yml.tpl
- templates/scenarios/js/non-sso-tab/teamsapp.local.yml.tpl
- templates/scenarios/js/sso-tab/teamsapp.local.yml.tpl
- templates/scenarios/ts/dashboard-tab/teamsapp.local.yml.tpl
- templates/scenarios/ts/m365-tab/teamsapp.local.yml.tpl
- templates/scenarios/ts/non-sso-tab-default-bot/teamsapp.local.yml.tpl
- templates/scenarios/ts/non-sso-tab/teamsapp.local.yml.tpl
- templates/scenarios/ts/sso-tab/teamsapp.local.yml.tpl
Align with #8111 and [script wiki](https://github.com/OfficeDev/TeamsFx/wiki/Available-actions-in-Teams-Toolkit#script), use `set-teamsfx-env` instead of `::set-output`
> chore: use set-teamsfx-env instead of set-output

- packages/fx-core/src/component/provisionUtils.ts
bug: [Bug 17709375](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/17709375): [VS][V2]Switching tenant account does not work for notification bot with azure function
E2E TEST: N/A
We will only fix this for VS V2 only, so will merge the PR to dev branch.
> fix: new bot service if switching tenant for notification bot (func) (v2) 

- packages/fx-core/resource/yaml.schema.json
- Remove `file/updateEnv` and `file/updateJson` since they are deprecated. Code cleanup will be in another PR.
- Support `boolean` and `number` for `file/createOrUpdateEnvironmentFile` action
> chore: update file action schema

- .github/workflows/cd.yml
VSC extension copies local templates when webpack. So, we should make sure the local templates are up to date.
TEST: https://github.com/hund030/TeamsFx/actions/runs/4625258194/jobs/8180845521
> chore: sync up fallback template after new template released

- templates/scenarios/ts/workflow/.vscode/tasks.json
E2E TEST: https://github.com/devdiv-azure-service-dmitryr/TeamsFx-UI-Test/blob/ae8d6f145f7d4dc69f774eecd91eda021445c354/src/ui-test/localdebug/localdebug-workflow-bot-ts.test.ts#L38
> fix(localdebug): add label to the dev tunnel task in workflow bot

- packages/vscode-extension/package.json
Related bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/17759185
E2E TEST: N/A
> fix(vsc): support activation from F5

- packages/fx-core/resource/package.nls.json
- packages/fx-core/src/component/driver/aad/create.ts
- packages/fx-core/src/component/driver/error/outputEnvironmentVariableUndefinedError.ts
- packages/fx-core/tests/component/driver/aad/create.test.ts
Previously we kept the default output logic to avoid breaking existing templates immediately. Now all the templates/samples should have `writeToEnvironmentFile` and the schema validation is also enabled to ensure `writeToEnvironmentFile` is provided. So removing the backward compatibility logic.
E2E TEST: N/A. Covered by UT.
> refactor: clean up default output logic in aadApp/create action

- .github/workflows/cd.yml
Currently the conventional-commits not suit for the repo.
because the VS release need hold the branches for hotfix, and later the vsc ttk will release the v5.0.0, later 5.even.* is stable and 5.odd.* is prerelease.
After change, the version going to bump up is patch by default, but developers can also custom the version by modify the verison in package.json such as 5.0.0-rc
> chore: remove conventional-commit for cd

- packages/vscode-extension/package.json
- packages/vscode-extension/src/commandController.ts
- packages/vscode-extension/src/extension.ts
- packages/vscode-extension/src/handlers.ts
- packages/vscode-extension/src/treeview/treeViewManager.ts
- packages/vscode-extension/test/extension/handlers.test.ts
Reuse same local debug command.
Related bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/17885287
> chore(vsc): align the preview command UX with local debug

- packages/vscode-extension/src/debug/commonUtils.ts
- packages/vscode-extension/test/extension/commonUtils.test.ts
- packages/vscode-extension/test/localdebug/commonUtils.test.ts
Related bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/17902656
> chore(vsc): support custom Teams app id key

- packages/fx-core/src/component/resource/appManifest/appStudio.ts
- packages/fx-core/tests/component/resource/appManifest/index.test.ts
@microsoft/adaptivecards-tools	v1.3.1-beta.2023041305.0
@microsoft/teamsfx-api	v0.22.2-beta.2023041305.0
@microsoft/teamsfx-cli	v2.0.0-beta.2023041305.0
@microsoft/teamsfx-core	v2.0.0-beta.2023041305.0
@microsoft/teams-manifest	v0.0.10-beta.2023041305.0
@microsoft/metrics-ts	v0.0.4-beta.2023041305.0
@microsoft/teamsfx	v2.2.1-beta.2023041305.0
@microsoft/teamsfx-react	v3.0.0-beta.2023041305.0
ms-teams-vscode-extension	v4.99.0-beta.2023041305.0 …
> fix: view in developer portal with correct teams app id

- packages/cli/src/cmds/package.ts
- packages/cli/src/cmds/validate.ts
- packages/cli/src/constants.ts
- packages/fx-core/src/core/question.ts
- packages/fx-core/tests/core/collaborator.test.ts
ADO: https://dev.azure.com/msazure/Microsoft%20Teams%20Extensibility/_workitems/edit/17957099
Trigger validate and select default manifest.json(interactive mode):
Trigger validate(non-interactive mode):
Trigger validate and select customized manifest.json:
Trigger package:
> fix: manifest related commands behaves wrongly in cli

- packages/fx-core/resource/package.nls.json
- packages/fx-core/src/component/driver/aad/update.ts
- packages/fx-core/tests/component/driver/aad/update.test.ts
@microsoft/adaptivecards-tools	v1.3.1-beta.2023041407.0
@microsoft/teamsfx-api	v0.22.2-beta.2023041407.0
@microsoft/teamsfx-cli	v2.0.0-beta.2023041407.0
@microsoft/teamsfx-core	v2.0.0-beta.2023041407.0
@microsoft/teams-manifest	v0.0.10-beta.2023041407.0
@microsoft/metrics-ts	v0.0.4-beta.2023041407.0
@microsoft/teamsfx	v2.2.1-beta.2023041407.0
@microsoft/teamsfx-react	v3.0.0-beta.2023041407.0
ms-teams-vscode-extension	v4.99.0-beta.2023041407.0 …
> fix: add update aadApp success hint for cli

- .github/workflows/lint-pr.yml
lint-pr audit move to main for checking the vulnerability
> chore: only check audit on main branch

- packages/fx-core/src/component/utils/envUtil.ts
- packages/fx-core/tests/component/envUtil.test.ts
- packages/fx-core/tests/core/FxCore.test.ts
To fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_sprints/taskboard/Teams%20Extensibility%20E2E%20Team/Microsoft%20Teams%20Extensibility/CY23-4.2?workitem=17926448
E2T TEST: N/A
> fix(env): not persist .env.xxx.user if there is no secret variables

- packages/fx-core/src/core/middleware/utils/v3MigrationUtils.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_sprints/taskboard/AuthAndData/Microsoft%20Teams%20Extensibility/CY23-4.1?workitem=17969372
> fix(migrationV3): use 'capabilities' to identify project type

- packages/vscode-extension/src/debug/commonUtils.ts
- packages/vscode-extension/src/debug/constants.ts
- packages/vscode-extension/src/debug/teamsfxTaskProvider.ts
Retire provideTasks and trigger migration when resolving a teamsfx task.
This PR also fixes https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/17943725.
> refactor(debug): retire provideTasks in task provider

- packages/fx-core/templates/core/v3Migration/csharp.app.local.yml
- packages/fx-core/templates/core/v3Migration/js.ts.app.local.yml
- packages/fx-core/tests/core/middleware/testAssets/v3Migration/debug/V3.5.0-V4.0.6-tab-bot-func/expected/app.local.yml
- packages/fx-core/tests/core/middleware/testAssets/v3Migration/debug/V3.5.0-V4.0.6-tab/expected/app.local.yml
- packages/fx-core/tests/core/middleware/testAssets/v3Migration/debug/beforeV3.4.0-tab-bot-func/expected/app.local.yml
- packages/fx-core/tests/core/middleware/testAssets/v3Migration/debug/beforeV3.4.0-tab/expected/app.local.yml
- packages/fx-core/tests/core/middleware/testAssets/v3Migration/debug/transparent-m365-tab/expected/app.local.yml
- packages/fx-core/tests/core/middleware/testAssets/v3Migration/debug/transparent-sso-tab/expected/app.local.yml
- packages/fx-core/tests/core/middleware/testAssets/v3Migration/debug/transparent-tab-bot-func/expected/app.local.yml
- packages/fx-core/tests/core/middleware/testAssets/v3Migration/debug/transparent-tab/expected/app.local.yml
- templates/scenarios/csharp/non-sso-tab/teamsapp.local.yml.tpl
- templates/scenarios/csharp/sso-tab/teamsapp.local.yml.tpl
- templates/scenarios/js/dashboard-tab/teamsapp.local.yml.tpl
- templates/scenarios/js/m365-tab/teamsapp.local.yml.tpl
- templates/scenarios/js/non-sso-tab-default-bot/teamsapp.local.yml.tpl
- templates/scenarios/js/non-sso-tab/teamsapp.local.yml.tpl
- templates/scenarios/js/sso-tab/teamsapp.local.yml.tpl
- templates/scenarios/ts/dashboard-tab/teamsapp.local.yml.tpl
- templates/scenarios/ts/m365-tab/teamsapp.local.yml.tpl
- templates/scenarios/ts/non-sso-tab-default-bot/teamsapp.local.yml.tpl
- templates/scenarios/ts/non-sso-tab/teamsapp.local.yml.tpl
- templates/scenarios/ts/sso-tab/teamsapp.local.yml.tpl
Fix https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/17884838/
Merge multiple `::set-teamsfx-env` to one action to make template clearer.
The semicolon(`;`) works as separator in both pwsh and bash which are the default shell of script action.
E2E TEST: https://github.com/OfficeDev/TeamsFx/blob/dev/packages/cli/tests/e2e/debug/DebugSsoTab.tests.ts
> fix: set env better format

- templates/scenarios/ts/sso-tab/appPackage/manifest.json.tpl
- templates/scenarios/ts/sso-tab/src/components/App.tsx
It's recommended to display a loading indicator while the Teams app is loading. 
[Create a content page - Teams | Microsoft Learn](https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/content-page?tabs=teamsjs-v2#show-a-native-loading-indicator)
I will apply the change to other tab templates.
before:
after:
> refactor: show loading indicator for tab template

- packages/fx-core/src/component/coordinator/index.ts
- packages/fx-core/src/component/generator/generator.ts
- packages/fx-core/tests/component/coordinator.test.ts
[Bug 18299994](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/18299994): [VS] Deploy failed if project name has dot symbol
We should use SafeProjectName from VS
E2E TEST: N/A
> fix: use safe project name from vs

- templates/scenarios/js/dashboard-tab/appPackage/manifest.json.tpl
- templates/scenarios/js/dashboard-tab/src/App.css
- templates/scenarios/js/dashboard-tab/src/App.jsx
- templates/scenarios/js/m365-tab/appPackage/manifest.json.tpl
- templates/scenarios/js/m365-tab/src/components/App.jsx
- templates/scenarios/js/non-sso-tab-default-bot/appPackage/manifest.json.tpl
- templates/scenarios/js/non-sso-tab-default-bot/tab/src/components/App.jsx
- templates/scenarios/js/non-sso-tab/appPackage/manifest.json.tpl
- templates/scenarios/js/non-sso-tab/src/views/hello.html
- templates/scenarios/js/sso-tab/appPackage/manifest.json.tpl
- templates/scenarios/js/sso-tab/src/components/App.jsx
- templates/scenarios/ts/dashboard-tab/appPackage/manifest.json.tpl
- templates/scenarios/ts/dashboard-tab/src/App.css
- templates/scenarios/ts/dashboard-tab/src/App.tsx
- templates/scenarios/ts/m365-tab/appPackage/manifest.json.tpl
- templates/scenarios/ts/m365-tab/src/components/App.tsx
- templates/scenarios/ts/non-sso-tab-default-bot/appPackage/manifest.json.tpl
- templates/scenarios/ts/non-sso-tab-default-bot/tab/src/components/App.tsx
- templates/scenarios/ts/non-sso-tab/appPackage/manifest.json.tpl
- templates/scenarios/ts/non-sso-tab/src/views/hello.html
- templates/scenarios/ts/sso-tab/src/components/App.tsx
It's recommended to display a loading indicator while the Teams app is loading. 
[Create a content page - Teams | Microsoft Learn](https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/content-page?tabs=teamsjs-v2#show-a-native-loading-indicator)
before:
after:
> perf: enable loading indicator for all tab templates

- packages/fx-core/src/core/FxCoreImplementV3.ts
user task `getManifestTemplatePath ` is no longer used in v3
> refactor: clean up user task getManifestTemplatePath for v3

- templates/scenarios/js/notification-http-timer-trigger/.funcignore
- templates/scenarios/js/notification-http-timer-trigger/.gitignore
- templates/scenarios/js/notification-http-timer-trigger/.vscode/tasks.json
- templates/scenarios/js/notification-http-timer-trigger/teamsapp.local.yml.tpl
- templates/scenarios/js/notification-http-trigger/.funcignore
- templates/scenarios/js/notification-http-trigger/.gitignore
- templates/scenarios/js/notification-http-trigger/.vscode/tasks.json
- templates/scenarios/js/notification-http-trigger/teamsapp.local.yml.tpl
- templates/scenarios/js/notification-timer-trigger/.funcignore
- templates/scenarios/js/notification-timer-trigger/.gitignore
- templates/scenarios/js/notification-timer-trigger/.vscode/tasks.json
- templates/scenarios/js/notification-timer-trigger/teamsapp.local.yml.tpl
- templates/scenarios/ts/notification-http-timer-trigger/.funcignore
- templates/scenarios/ts/notification-http-timer-trigger/.gitignore
- templates/scenarios/ts/notification-http-timer-trigger/.vscode/tasks.json
- templates/scenarios/ts/notification-http-timer-trigger/teamsapp.local.yml.tpl
- templates/scenarios/ts/notification-http-trigger/.funcignore
- templates/scenarios/ts/notification-http-trigger/.gitignore
- templates/scenarios/ts/notification-http-trigger/.vscode/tasks.json
- templates/scenarios/ts/notification-http-trigger/teamsapp.local.yml.tpl
- templates/scenarios/ts/notification-timer-trigger/.funcignore
- templates/scenarios/ts/notification-timer-trigger/.gitignore
- templates/scenarios/ts/notification-timer-trigger/.vscode/tasks.json
- templates/scenarios/ts/notification-timer-trigger/teamsapp.local.yml.tpl
Detail: 
[Bug 17943760](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/17943760): [V3] Replace "command:get-func-path" with soft link after support versioning installation
[Bug 17920588](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/17920588): [V3] Support versioning install
Related tp PR: https://github.com/OfficeDev/TeamsFx/pull/8482
> fix(localdebug): update template to support versioning func installation

- packages/cli/src/cmds/account.ts
- packages/cli/src/colorize.ts
- packages/cli/src/commonlib/codeFlowLogin.ts
- packages/cli/src/commonlib/codeFlowTenantLogin.ts
- packages/cli/src/commonlib/log.ts
- packages/cli/src/console/progress.ts
- packages/cli/src/error.ts
- packages/cli/src/resource/strings.json
- packages/cli/src/yargsCommand.ts
- packages/cli/tests/unit/cmds/account.tests.ts
- packages/cli/tests/unit/cmds/env.tests.ts
- packages/cli/tests/unit/cmds/preview/previewEnv.tests.ts
- packages/cli/tests/unit/colorize.tests.ts
- packages/cli/tests/unit/commonlib/log.tests.ts
- packages/cli/tests/unit/yargsCommand.tests.ts
Fix the error message occurred in https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/17981062.
Discussed with Ellie, refactor the CLI color (success/error/warn/info/importance message).
> refactor(cli): log color and add a new log API

- packages/fx-core/src/core/middleware/projectMigratorV3.ts
- packages/fx-core/src/core/middleware/utils/debug/taskMigrator.ts
- packages/fx-core/tests/core/middleware/debug/taskMigrator.test.ts
- packages/fx-core/tests/core/middleware/testAssets/v3Migration/debug/V3.5.0-V4.0.6-notification-trigger/expected/tasks.json
- packages/fx-core/tests/core/middleware/testAssets/v3Migration/debug/V3.5.0-V4.0.6-tab-bot-func-node18/expected/tasks.json
- packages/fx-core/tests/core/middleware/testAssets/v3Migration/debug/V3.5.0-V4.0.6-tab-bot-func/expected/tasks.json
- packages/fx-core/tests/core/middleware/testAssets/v3Migration/debug/beforeV3.4.0-tab-bot-func-node18/expected/tasks.json
- packages/fx-core/tests/core/middleware/testAssets/v3Migration/debug/beforeV3.4.0-tab-bot-func/expected/tasks.json
- packages/fx-core/tests/core/middleware/testAssets/v3Migration/debug/transparent-notification-node18/expected/tasks.json
- packages/fx-core/tests/core/middleware/testAssets/v3Migration/debug/transparent-notification/expected/tasks.json
- packages/fx-core/tests/core/middleware/testAssets/v3Migration/debug/transparent-tab-bot-func/expected/tasks.json
- packages/vscode-extension/src/extension.ts
- packages/vscode-extension/src/handlers.ts
- packages/vscode-extension/test/extension/handlers.test.ts
related to https://github.com/OfficeDev/TeamsFx/pull/8482
migrate `${command:fx-extension.get-func-path}${env:PATH}` to be `${workspaceFolder}/devTools/func${command:fx-extension.get-path-delimiter}${env:PATH}`
> fix(localdebug): migrate fx-extension.get-func-path to func path + fx-extension.get-path-delimiter

- packages/fx-core/src/common/deps-checker/internal/funcToolChecker.ts
- packages/fx-core/tests/common/deps-checker/funcToolChecker.test.ts
Avoid return the global func version when query the portable func version.
> fix(localdebug): update query portable func version

- packages/dotnet-sdk/src/TeamsFx.Test/Conversation/DefaultConversationReferenceStoreTest.cs
- packages/dotnet-sdk/src/TeamsFx.Test/Conversation/InMemoryStorage.cs
- packages/dotnet-sdk/src/TeamsFx.Test/Conversation/LocalFileStorageTest.cs
- packages/dotnet-sdk/src/TeamsFx.Test/Conversation/NotificationMiddlewareTest.cs
- packages/dotnet-sdk/src/TeamsFx/Conversation/DefaultConversationReferenceStore.cs
- packages/dotnet-sdk/src/TeamsFx/Conversation/IConversationReferenceStore.cs
- packages/dotnet-sdk/src/TeamsFx/Conversation/IConversationReferenceStoreAddOptions.cs
- packages/dotnet-sdk/src/TeamsFx/Conversation/INotificationTargetStorage.cs
- packages/dotnet-sdk/src/TeamsFx/Conversation/LocalFileStorage.cs
- packages/dotnet-sdk/src/TeamsFx/Conversation/NotificationBot.cs
- packages/dotnet-sdk/src/TeamsFx/Conversation/NotificationMiddleware.cs
- packages/dotnet-sdk/src/TeamsFx/Conversation/NotificationOptions.cs
- packages/dotnet-sdk/src/TeamsFx/Conversation/PagedData.cs
- packages/dotnet-sdk/src/TeamsFx/Conversation/TeamsBotInstallation.cs
Work item: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/17902085/
Updates in this PR:
1. Add new interface `IConversationReferenceStore`.
2. Add new option `store` in `NotificationBot`.
3. Deprecate the interface `INotificationTargetStorage` and the option `storage` in `NotificationBot`.
4. Add new pagaination API `GetPagedInstallationsAsync`, `GetPagedMembersAsync`.
5. Deprecated API `GetMembersAsync`.
6. Add API `BuildTeamsBotInstallation`.
Incoming PR:
1. Bump new version. (after the 2.0.0 is released)
2. Update README and Change log.
3. Update templates.
> feat(sdk): notification sdk enhancement for .NET

- .github/workflows/e2e-test.yml
Fix the failure of DebugNotificationHttpTrigger e2e test case
https://github.com/OfficeDev/TeamsFx/actions/runs/4780617978/jobs/8499121943
Use `sudo npm install --unsafe-perm -g azure-functions-core-tools@4` can not correctly install func in github action.
The result of the test script
```
sudo npm install --unsafe-perm -g azure-functions-core-tools@4
which func
func --version
```
Use the func installation script used in UI test instead.
Updated script result:
Run: https://github.com/OfficeDev/TeamsFx/actions/runs/4785254229/jobs/8507886126
> fix(localdebug): fix DebugNotificationHttpTrigger e2e test case

- packages/dotnet-sdk/src/TeamsFx.Test/Conversation/LocalFileStorageTest.cs
- packages/dotnet-sdk/src/TeamsFx/Conversation/LocalFileStorage.cs
Error occurs when the same bot is added twice using the default local file storage in .NET SDK.
>
> The bot encountered an unhandled error: An item with the same key has already been added. Key: _7309892c-5bd2...
> fix(sdk): exception when the bot is added twice

- packages/fx-core/resource/package.nls.json
- packages/fx-core/src/component/driver/teamsApp/interfaces/ValidateManifestArgs.ts
- packages/fx-core/src/component/driver/teamsApp/validate.ts
- packages/fx-core/src/core/FxCoreImplementV3.ts
- packages/manifest/src/index.ts
- packages/manifest/test/index.test.ts
- packages/vscode-extension/syntaxes/teamsfx-toolkit-output.tmLanguage
1) Unify teamsApp/validateManifest output with teamsApp/validateAppPackge
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/17885306
2) Show all validation errors
Ajv only return first error by default: https://ajv.js.org/options.html#allerrors
> fix: unify /validateManifest output

- packages/vscode-extension/src/extension.ts
- packages/vscode-extension/src/globalVariables.ts
- packages/vscode-extension/src/utils/commonUtils.ts
- packages/vscode-extension/test/extension/commonUtils.test.ts
- packages/vscode-extension/test/extension/globalVariables.test.ts
1. Project name display bug.
2. Upgrade bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/19298436
> fix(vsc): not showing treeview when upgrade detects error

- packages/fx-core/src/component/generator/utils.ts
Fix downloading "stock-update-notification-bot" also downloads "stock-udate-notification-bot-dotnet"
> fix(generator): change filter sample path logic

- packages/fx-core/src/core/FxCore.ts
- packages/fx-core/src/core/FxCoreImplementV3.ts
- packages/fx-core/tests/component/coordinator.test.ts
add `getDotEnvs` API to replace the original `getDotEnv API` in FxCore
> refactor(core): add list all envs API

- packages/fx-core/src/common/deps-checker/internal/funcToolChecker.ts
- packages/fx-core/tests/common/deps-checker/funcToolChecker.test.ts
detail: [Bug 21448658](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/21448658): Failed to install func when home dir contains empty space
> fix(localdebug): support home dir with space

- packages/fx-core/src/component/developerPortalScaffoldUtils.ts
- packages/fx-core/src/core/question.ts
- packages/fx-core/tests/core/question.test.ts
> fix: not show outlook option if scaffolding from TDP

- packages/cli/src/resource/strings.json
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/21049380
Add the `or teamsapp.local.yml` in the provision/deploy help message.
> fix(cli): provision/deploy message

- packages/fx-core/templates/core/v3Migration/upgradeReport.md
@microsoft/teamsfx-cli	v2.0.0-rc.3
@microsoft/teamsfx-core	v2.0.0-rc.3
ms-teams-vscode-extension	v5.0.0-rc.3
> docs: update upgrade report

- packages/fx-core/src/component/utils/pathUtils.ts
- packages/fx-core/tests/component/envUtil.test.ts
to fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_sprints/taskboard/Teams%20Extensibility%20E2E%20Team/Microsoft%20Teams%20Extensibility/CY23-5.2?workitem=22491976
> fix(core): use default env folder path when read env

- packages/fx-core/src/common/deps-checker/internal/funcToolChecker.ts
- packages/fx-core/src/component/driver/devTool/error/dotnetInstallationUserError.ts
- packages/fx-core/src/component/driver/devTool/error/funcInstallationUserError.ts
- packages/fx-core/src/component/driver/devTool/installDriver.ts
1. Hook `addStartAndEndTelemetry` should be used in the `WrapDriverContext`.
1. Avoid the error code to be redacted. `error-code: <REDACTED: user-file-path>`
1. Avoid the install error message to be redacted. `install-func-error: <REDACTED: email>`
> fix(localdebug): fix the dev tool telemetry which are masked by GDPR

- packages/fx-core/src/common/deps-checker/internal/funcToolChecker.ts
In windows, `npm install azure-functions-core-tools@4 --prefix ${path} --no-audit` has a 256 character limit on file paths
To reduce the risk of exceeding the limit, shorten the temporary folder length.
Error message:
[Error: ENOENT: no such file or directory, realpath '${path}\\.fx\bin\azfunc\27eb88e2-dcde-4b00-9737-42b7a13c0c8d\node_modules\azure-functions-core-tools\bin\workers\python\3.10\WINDOWS\X64\azure_functions_worker-4.10.1-py3.10.egg-info'] {
errno: -4058,
code: 'ENOENT',
syscall: 'realpath',
path: '${path}\\.fx\\bin\\azfunc\\27eb88e2-dcde-4b00-9737-42b7a13c0c8d\\node_modules\\azure-functions-core-tools\\bin\\workers\\python\\3.10\\WINDOWS\\X64\\azure_functions_worker-4.10.1-py3.10.egg-info'
> fix(localdebug): shorter func installation tmp folder length

- packages/fx-core/src/component/driver/aad/create.ts
- packages/fx-core/src/component/driver/aad/update.ts
- packages/fx-core/tests/component/driver/aad/create.test.ts
- packages/fx-core/tests/component/driver/aad/update.test.ts
Bug: https://dev.azure.com/msazure/Microsoft%20Teams%20Extensibility/_workitems/edit/23074298
The message in axios error only includes the status code, which can not help users fix the actual problem. Return the response in axiosError.response.data to tell users more details about the error.
This can improve the troubleshooting experience in issue https://github.com/OfficeDev/TeamsFx/issues/8733
> fix: no detailed error message in AAD app actions

- packages/fx-core/src/component/utils/metadataUtil.ts
- packages/fx-core/tests/component/util/metadataUtil.test.ts
fix: add missing properties for metadata event
Add 'composeExtensions' property to metadata. this is useful for message extension project.
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/23517592
> fix: add missing properties for metadata event

- templates/scenarios/js/notification-http-timer-trigger/package.json.tpl
- templates/scenarios/js/notification-http-trigger/package.json.tpl
- templates/scenarios/js/notification-restify/package.json.tpl
- templates/scenarios/js/notification-timer-trigger/package.json.tpl
- templates/scenarios/ts/notification-http-timer-trigger/package.json.tpl
- templates/scenarios/ts/notification-http-trigger/package.json.tpl
- templates/scenarios/ts/notification-restify/package.json.tpl
- templates/scenarios/ts/notification-timer-trigger/package.json.tpl
work item: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/23286405/
Fix E2E test failure that TeamsFx SDK `2.1.0` will be installed instead of `2.2.0-alpha...` with `2.0.0-alpha` defined in package.json.
E2E TEST: https://github.com/OfficeDev/TeamsFx/actions/runs/5064753554
> fix(e2e): update sdk version to fix e2e test

- packages/cli/tests/e2e/debug/DebugNonSsoTab.tests.ts
There is no sso tab template now.
https://github.com/OfficeDev/TeamsFx/actions/runs/5075599609
> test(e2e): update DebugSsoTab to DebugNonSsoTab

- packages/vscode-extension/src/commonlib/codeFlowLogin.ts
- packages/vscode-extension/src/commonlib/m365Login.ts
Resolve the issue where login using dev tunnel scope or metaos scope returns a token that cannot be encoded by base64. In this scenario, we will return empty object and for UX we will try to get appStudio token.
[Bug 21597038: [Bug Bash] [v5.0.0] Dev Tunnel fails to start when running from "Tasks: Run Task" - Boards (visualstudio.com)](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/21597038)
> fix: convert token fail return empty object

- packages/sdk-react/src/BaseDashboard.tsx
- packages/sdk-react/src/BaseWidget.tsx
- packages/sdk-react/src/useData.ts
- packages/sdk-react/src/useGraph.ts
- packages/sdk-react/src/useTeamsFx.ts
- packages/sdk-react/src/useTeamsUserCredential.ts
- Add annotations to the protected methods in the SDK so that they can be recognized when the SDK reference is automatically generated on learn.microsoft site.
- Change all `@beta` annotations to `@public`.
> build: add annotations to SDK protected methods

- .github/scripts/fxcore-sync-up-version.js
- .github/scripts/template-zip-autogen-v3.sh
- packages/fx-core/src/common/templates-config.json
- packages/fx-core/src/component/generator/utils.ts
- packages/fx-core/tests/component/generator/generator.test.ts
1. Use beta tag for prerelease template.
2. Update generation script since scenario folder has been removed.
3. Add UseLocalTemplate flag in template config.
> refactor: update templates scripts to catch up CD changes

- .github/scripts/vsc-version.sh
- .github/workflows/cd.yml
- packages/vscode-extension/package.json
Set the vsc beta version as 5.odd.timestamp according to the release process design.
> build: set vsc version diff on beta and other

- packages/cli/tests/e2e/debug/DebugNonSsoTab.tests.ts
- packages/cli/tests/e2e/frontend/BasicTabHappyPath.tests.ts
- packages/cli/tests/e2e/frontend/CanDeployToCustomizedRg.tests.ts
- packages/cli/tests/e2e/frontend/TestCreateTab.tests.ts
- packages/cli/tests/e2e/multienv/TestRemoteHappyPathSPFx.tests.ts
- packages/cli/tests/e2e/samples/ProvisionDeveloperDashboard.tests.ts
- templates/ts/non-sso-tab/teamsapp.yml.tpl
`teamsApp/extendToM365` will be covered in `./m365/*`.
https://github.com/OfficeDev/TeamsFx/actions/runs/5130815186
> test(e2e): remove teamsApp/extendToM365 to unblock e2e

- packages/fx-core/src/component/driver/aad/create.ts
- packages/fx-core/src/component/driver/aad/update.ts
- packages/fx-core/tests/component/driver/aad/create.test.ts
- packages/fx-core/tests/component/driver/aad/update.test.ts
fix https://dev.azure.com/msazure/Microsoft%20Teams%20Extensibility/_workitems/edit/23074298
cherry pick related commit from dev branch to 5.0.1 hotfix branch
> fix: no detailed error message in AAD app actions (#8737)

- packages/fx-core/src/component/driver/botAadApp/create.ts
- packages/fx-core/tests/component/driver/botAadApp/create.test.ts
fix: https://dev.azure.com/msazure/Microsoft%20Teams%20Extensibility/_workitems/edit/24135231
> fix: no detail error message when botAadApp/create failed

- packages/vscode-extension/src/debug/prerequisitesHandler.ts
Detail: [Bug 24198255](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/24198255): [VSC] teamsfx project local debug "node.js check" failed
> fix: handler deps checker error when the error exist

- packages/vscode-extension/src/commonlib/codeFlowLogin.ts
- packages/vscode-extension/src/commonlib/m365Login.ts
Fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/21597038
cherry pick: https://github.com/OfficeDev/TeamsFx/pull/8809
> fix: convert token fail return empty object (#8809)

- packages/fx-core/src/component/utils/fileOperation.ts
fix: #8943 
also: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/24213431
> fix: fix zip path doesn't work properly under windows

- .github/CODEOWNERS
Add codeowners for botAadApp action.
Also remove extra space in the code owner file to ensure the github-codeowners can run successfully.
> refactor: add codeowners for botaadapp

- packages/fx-core/src/component/constants.ts
- packages/fx-core/src/component/utils/teamsFxTelemetryReporter.ts
- packages/fx-core/tests/component/driver/aad/create.test.ts
- packages/vscode-extension/src/commonlib/telemetry.ts
- packages/vscode-extension/src/telemetry/extTelemetryEvents.ts
- packages/vscode-extension/test/extension/telemetry.test.ts
Add error stack to help better troubleshoot system errors in our code
Also update vscode telemetry reporter to remove file path per suggestion.
> refactor: add error stack to action telemetries

- packages/fx-core/src/component/driver/teamsApp/configure.ts
- packages/fx-core/src/component/driver/teamsApp/utils/ManifestUtils.ts
- packages/fx-core/src/core/FxCoreImplementV3.ts
- packages/fx-core/src/index.ts
- packages/vscode-extension/src/treeview/treeViewManager.ts
- packages/vscode-extension/test/extension/treeview/treeViewManager.test.ts
Related task: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/21605701
> fix: hide developer portal in non-teams app

- packages/api/review/teamsfx-api.api.md
- packages/api/src/qm/question.ts
- packages/api/src/qm/ui.ts
- packages/fx-core/src/ui/visitor.ts
- packages/fx-core/tests/ui/qm.visitor.test.ts
- packages/vscode-extension/src/qm/vsc_ui.ts
- packages/vscode-extension/src/telemetry/extTelemetryEvents.ts
- packages/vscode-extension/test/extension/qm/vsc_ui.test.ts
- add a question type allowing user to select a file or input a value for the file. 
- add VSC implementation. Confirmed with designer that it is recommended to have two steps rather than combine inputting a value and picking an option together.
[Task 24305677](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/24305677): Question to select a file and enter Url
> feat: question to select a local file or enter value

- packages/fx-core/src/component/driver/teamsApp/utils/utils.ts
- packages/fx-core/tests/component/resource/appManifest/utils.test.ts
We previously check contentUrl to determine whether a personal tab is created by users or TDP. However, engineers from TDP mentioned that it is better to check entity id as content URL might be an optional field in the future.
This is similar to https://domoreexp.visualstudio.com/Teamspace/_git/teams-devapp/pullrequest/783679
[Bug 24318226](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/24318226): [TDP&TTK] Update to check tab using entityIds
> fix: check personal app from users

- packages/fx-core/src/component/driver/teamsApp/clients/appStudioClient.ts
- packages/fx-core/src/component/driver/teamsApp/utils/telemetry.ts
- packages/fx-core/tests/component/driver/teamsApp/appstudioclient.test.ts
For bug https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/24254022, add region property to check if it's caused by wrong regional API.
> fix: add region telemetry property

- .github/CODEOWNERS
detail: [Bug 24332668](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/24332668): Update codeowners
> chore: update the code owners of deps checker

- packages/fx-core/src/question/create.ts
- packages/fx-core/tests/question/create.test.ts
Ensure non-interactive cli command can create blazor non sso tab. This command is used in our E2E test:
teamsfx new --runtime dotnet --interactive false --app-name appName --capabilities tab-non-sso
> fix: cannot create blazor tab from cli in non-interactive mode

- packages/api/review/teamsfx-api.api.md
- packages/api/src/qm/question.ts
- packages/api/src/qm/ui.ts
- packages/fx-core/src/question/create.ts
- packages/fx-core/src/ui/visitor.ts
- We already have "filters" on SelectFileConfig today, also add it in "SingleFileOrInputConfig"
- "filters" will only take effect in VSC, but not in CLI. Also added this in comment in api.
> fix: add filters when selecting file for api spec

- packages/cli/src/constants.ts
- packages/fx-core/src/common/samples-config-v3.json
- packages/fx-core/src/common/samples.ts
- packages/fx-core/src/component/generator/generator.ts
- packages/fx-core/src/component/generator/utils.ts
- packages/fx-core/src/question/create.ts
- packages/fx-core/tests/common/samples.test.ts
- packages/fx-core/tests/component/generator/generator.test.ts
- packages/vscode-extension/src/controls/ISamples.ts
- packages/vscode-extension/src/controls/SampleGallery.tsx
- packages/vscode-extension/src/controls/sampleDetailPage.tsx
1. Remove `packageLink` and `relativePath` fields in sample config, cleanup related codes
2. Download/View sample per package version:
For alpha releases, download from dev branch;
For rc releases, download from v3 branch;
For beta and stable release, download from tag;
> refactor: cleanup sample codes and download according to package version

- packages/fx-core/src/question/create.ts
- packages/fx-core/src/question/questionNames.ts
- packages/fx-core/tests/plugins/resource/spfx/unit/utils.test.ts
- packages/fx-core/tests/question/create.test.ts
As confirmed with PM & UX, expose app name question in import SPFx solution flow and make solution name as default value for app name
E2E TEST: NA
> feat: expose app name question in import spfx flow

- packages/api/review/teamsfx-api.api.md
- packages/api/src/types.ts
- packages/fx-core/src/component/generator/spfx/depsChecker/generatorChecker.ts
- packages/fx-core/src/component/generator/spfx/spfxGenerator.ts
- packages/fx-core/src/question/create.ts
- packages/fx-core/tests/component/generator/spfxGenerator.test.ts
- packages/fx-core/tests/plugins/resource/spfx/depsChecker/generatorChecker.test.ts
- packages/fx-core/tests/plugins/resource/spfx/unit/utils.test.ts
- packages/fx-core/tests/question/create.test.ts
- packages/fx-core/tests/question/question.spfx.test.ts
- load package versions of installed SPFx generator and Yeoman and latest SPFx generator, and save these values in input for validation and scaffolding. Previously, we save these values as global variables.
> refactor: spfx package question

- packages/fx-core/src/component/utils/metadataUtil.ts
- packages/fx-core/tests/component/util/metadataUtil.test.ts
fix: change hash encoding to hex to avoid slash char in base64
This is because "base64" encoding have "/" charactor. It make GDPR treat the hash string as file path. So need to change encoding to "hex" to avoid this case.
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/24539488
> fix: change hash encoding to hex to avoid slash char in base64

- packages/api/review/teamsfx-api.api.md
- packages/api/src/qm/question.ts
- packages/api/src/qm/ui.ts
- packages/api/src/types.ts
- packages/fx-core/src/component/generator/copilotPlugin/constant.ts
- packages/fx-core/src/component/generator/copilotPlugin/helper.ts
- packages/fx-core/src/question/create.ts
- packages/fx-core/src/ui/visitor.ts
- packages/fx-core/tests/question/create.test.ts
- packages/fx-core/tests/ui/qm.visitor.test.ts
- packages/vscode-extension/package.nls.json
- packages/vscode-extension/src/qm/vsc_ui.ts
- packages/vscode-extension/test/extension/qm/vsc_ui.test.ts
- add additionalValidationOnAccept for input box. This validation will run when user accepts the input, which usually should be a check that will take some time that we should not run when user still inputs. 
- Ideally we will show busy state when validating, but due to issues on VSCode side, for now we will show "Validating..." indicating the progress
- If validation error, we will log the error and show validation message 
- add validation after user selects a file. 
- if validation failed, we will show notification and log the error (currently validationMessage is not an exposed property on quickpick https://github.com/microsoft/vscode/issues/121205). And user could try select another one (no need to start all over again)
**TODO**: 
- create item to track CLI ui update
- validation …
> refactor: show validation error in question related to copilot plugin

- packages/api/package.json
- packages/cli/package.json
- packages/extra-shot-mocha/package.json
- packages/failpoint-ts/package.json
- packages/fx-core/package.json
- packages/manifest/package.json
- packages/metrics-ts/package.json
- packages/server/package.json
- packages/tests/package.json
- packages/vscode-extension/package.json
- templates/package.json
will convert eslint as a config instead of package.
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_testPlans/define?planId=24569079&opId=5682&suiteId=24569087
> build: update the eslint version according to the version upgrade

- docs/sdk/teamsfx.createmicrosoftgraphclient.md
- packages/sdk/src/core/msGraphClientProvider.ts
Fix extraneous single quote in sample code, as reported here: https://github.com/MicrosoftDocs/msteams-docs/issues/8024
> docs: Fix typo in sample code

- packages/fx-core/package.json
- packages/fx-core/src/common/spec-parser/specParser.ts
- packages/fx-core/src/common/spec-parser/utils.ts
- packages/fx-core/tests/common/spec-parser/specParser.test.ts
- packages/fx-core/tests/common/spec-parser/utils.test.ts
- Save new OpenAPI spec file based on its original format
- Update filter logic:
- Only GET operation with 1 param without auth
- Doesn't support array/object type
- Only support parameter in query or path, and in header or cookie are not supported
> perf(specParser): save file with original format, only support get with 1 param without auth

- packages/fx-core/src/core/collaborator.ts
exec has a global internal lastIndex property which case the bug, and fix it using match instead:
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/24741853
> fix: list collaborator issue

- packages/fx-core/src/common/spec-parser/interfaces.ts
- packages/fx-core/src/common/spec-parser/manifestUpdater.ts
- packages/fx-core/src/component/generator/copilotPlugin/helper.ts
- packages/fx-core/tests/common/spec-parser/manifestUpdater.test.ts
- packages/fx-core/tests/component/generator/copilotPluginGenerator.test.ts
- templates/common/simplified-message-extension-existing-api/appPackage/manifest.json.tpl
- templates/csharp/simplified-message-extension-existing-api/appPackage/manifest.json.tpl
- no need to update name in manifest.json. We will use the appName entered by users during scaffolding.
> refactor: use app name entered during scaffolding for name field in manifest

- packages/fx-core/src/component/configManager/validator.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/24793298
The [failed case](https://github.com/OfficeDev/TeamsFx/actions/runs/5814509072/job/15768466891) succeeds now https://github.com/OfficeDev/TeamsFx/actions/runs/5816553382/job/15769935815
fix: set allUnionTypes to silence ajv's warnings e61b42186 
CLI fix …
> fix: set allowUnionTypes to silence ajv's warnings

- packages/cli/src/yargsCommand.ts
- packages/cli/tests/unit/yargsCommand.tests.ts
fix: cli error print 3077e25be 
> fix: cli error print on main

- packages/fx-core/src/component/driver/teamsApp/createAppPackage.ts
- packages/fx-core/tests/component/driver/teamsApp/createAppPackage.test.ts
For bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/24818129
VSC output:
Triggered by lifecycle commands:
Triggered by Zip app package Treeview command:
> fix: add log for zip app package vsc

- packages/fx-core/src/component/developerPortalScaffoldUtils.ts
- packages/fx-core/src/component/driver/teamsApp/utils/utils.ts
- packages/fx-core/tests/component/generator/copilotPluginGenerator.test.ts
- packages/fx-core/tests/component/resource/appManifest/utils.test.ts
- packages/manifest/src/ManifestCommonProperties.ts
- packages/manifest/src/index.ts
- packages/vscode-extension/src/codeLensProvider.ts
- packages/vscode-extension/test/extension/handlers.test.ts
- adjust checking app features based on appDefinition so that it will work with new TDP app definition response.
- block SME for now if TDP->TTK
> refactor: check app feature based on app definition

- packages/tests/src/ui-test/migration/4.0.0-notification-bot-restify/4.0.0-notification-bot-restify-debug-upgrade-debug-ts.test.ts
- packages/tests/src/ui-test/migration/4.0.0-notification-bot-restify/4.0.0-notification-bot-restify-debug-upgrade-debug.test.ts
- packages/tests/src/ui-test/migration/4.0.0-notification-bot-restify/4.0.0-notification-bot-restify-upgrade-debug-ts.test.ts
- packages/tests/src/ui-test/migration/4.0.0-notification-bot-restify/4.0.0-notification-bot-restify-upgrade-debug.test.ts
- packages/tests/src/ui-test/migration/bot/bot-debug-upgrade-debug-ts.test.ts
- packages/tests/src/ui-test/migration/bot/bot-upgrade-debug-ts.test.ts
- packages/tests/src/ui-test/migration/command-bot/command-bot-debug-upgrade-debug.test.ts
- packages/tests/src/ui-test/migration/command-bot/command-bot-provision-upgrade-provision-debug.test.ts
- packages/tests/src/ui-test/migration/command-bot/command-bot-upgrade-debug.test.ts
- packages/tests/src/ui-test/migration/command-bot/command-bot-upgrade-provision-debug.test.ts
- packages/tests/src/utils/commonUtils.ts
- packages/tests/src/utils/constants.ts
1. update bot validation string for migration command bot test cases
2. add two bot typescript local debug migration cases
3. update notification bot terminal task name for 4.0.0
4. replace manifest developer properties which is known issue with unrecognized variable.
> test: fix migration bot validation string

- packages/api/review/teamsfx-api.api.md
- packages/api/src/cli.ts
- packages/cli/src/commands/engine.ts
- packages/cli/src/commands/models/permissionGrant.ts
- packages/cli/src/commands/models/permissionStatus.ts
- packages/cli/src/commands/models/provision.ts
- packages/cli/src/userInteraction.ts
- packages/cli/tests/unit/commands.tests.ts
fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/24894372
1. provision add region option for e2e
2. remove prograss bar when loading options
3. reverve option values for interactive model (such as `teamsfx permission status`)
> fix: reserve option values for interactive mode

- packages/fx-core/src/common/spec-parser/constants.ts
- packages/fx-core/src/common/spec-parser/interfaces.ts
- packages/fx-core/src/common/spec-parser/specParser.ts
- packages/fx-core/src/common/spec-parser/utils.ts
- packages/fx-core/tests/common/spec-parser/specParser.test.ts
- packages/fx-core/tests/common/spec-parser/utils.test.ts
According to Josh's [OpenAPI Spec Rules doc](https://microsoft-my.sharepoint-df.com/:w:/p/jofri/EW-09UM7q8ZDu4Wfloi88bcBYKrOZQ4JXVygXfWtgaa6xQ?e=JoQhpS&clickparams=eyJBcHBOYW1lIjoiVGVhbXMtRGVza3RvcCIsIkFwcFZlcnNpb24iOiIyNy8yMzA4MDQwODYxMyIsIkhhc0ZlZGVyYXRlZFVzZXIiOmZhbHNlfQ%3D%3D), server url should also satisfy the following requirements:
1. should be https
2. should be absolute url
> perf(specParser): update server url validate logic

- packages/fx-core/src/component/generator/copilotPlugin/helper.ts
- packages/fx-core/src/core/FxCore.ts
- packages/fx-core/tests/core/FxCore.test.ts
- packages/fx-core/tests/question/create.test.ts
1) Filter operations with correct Id
2) Should include existing operations, otherwise it will be removed from manifest/openAPI spec.
> fix: filter operations

- packages/vscode-extension/src/codeLensProvider.ts
- packages/vscode-extension/src/handlers.ts
- packages/vscode-extension/test/extension/codeLensProvider.test.ts
- packages/vscode-extension/test/extension/handlers.test.ts
Fix: [Bug 24818861](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/24818861): Click "This file is auto-generated, click here to edit the manifest template file" doesn't response
> fix: aad manifest codelens not work issue

- templates/js/link-unfurling/src/adaptiveCards/helloWorldCard.json
- templates/js/m365-message-extension/package.json.tpl
- templates/js/m365-message-extension/src/adaptiveCards/helloWorldCard.json
- templates/js/m365-message-extension/src/searchApp.js
- templates/js/message-extension-action/package.json.tpl
- templates/js/message-extension-action/src/actionApp.js
- templates/js/message-extension-action/src/adaptiveCards/helloWorldCard.json
- templates/ts/link-unfurling/src/adaptiveCards/helloWorldCard.json
- templates/ts/m365-message-extension/package.json.tpl
- templates/ts/m365-message-extension/src/adaptiveCards/helloWorldCard.json
- templates/ts/m365-message-extension/src/searchApp.ts
- templates/ts/message-extension-action/package.json.tpl
- templates/ts/message-extension-action/src/actionApp.ts
- templates/ts/message-extension-action/src/adaptiveCards/helloWorldCard.json
1. format link unfurling adaptive card json file;
2. move adaptive card to json file for action and search template.
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/24869801/
> refactor: move adaptive cards to json file for ts/js message extension templates

- packages/adaptivecards-tools-sdk/.eslintrc.js
- packages/api/.eslintrc.js
- packages/cli/.eslintrc.js
- packages/eslint-plugin-teamsfx/config/promise.js
- packages/eslint-plugin-teamsfx/config/type.js
- packages/extra-shot-mocha/.eslintrc.js
- packages/fx-core/.eslintrc.js
- packages/manifest/.eslintrc.js
- packages/metrics-ts/.eslintrc.js
- packages/sdk-react/.eslintrc.js
- packages/sdk-react/package.json
- packages/sdk/.eslintrc.js
- packages/server/.eslintrc.js
- packages/tests/.eslintrc.js
- packages/vscode-extension/.eslintrc.js
- pnpm-lock.yaml
change the place of importing `typescript-eslint/parser` to make it compatible with typescript version
> refactor: update eslintrc

- packages/fx-core/resource/package.nls.json
- packages/fx-core/src/component/generator/error.ts
- packages/fx-core/src/component/generator/generator.ts
- packages/fx-core/src/component/generator/generatorAction.ts
- packages/fx-core/src/component/generator/utils.ts
- packages/fx-core/tests/component/feature/sso.test.ts
- packages/fx-core/tests/component/generator/generator.test.ts
1. Throw system error when there is no file scaffolded.
2. Add debug messages before each generator action.
> refactor: refine error handling and add debug messages for generator

- packages/fx-core/resource/package.nls.json
- packages/fx-core/src/question/create.ts
- packages/fx-core/src/question/inputs/CreateProjectInputs.ts
- packages/fx-core/src/question/inputs/SPFxAddWebpartInputs.ts
- packages/fx-core/src/question/options/DeployAadManifestOptions.ts
- packages/fx-core/src/question/options/PermissionGrantOptions.ts
- packages/fx-core/src/question/options/PermissionListOptions.ts
- packages/fx-core/src/question/options/PreviewTeamsAppOptions.ts
- packages/fx-core/src/question/options/SPFxAddWebpartOptions.ts
- packages/fx-core/src/question/options/SelectTeamsManifestOptions.ts
- packages/fx-core/src/question/options/ValidateTeamsAppOptions.ts
- packages/fx-core/src/question/other.ts
fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25000694
> fix: spfx questions

- packages/fx-core/src/common/spec-parser/constants.ts
- packages/fx-core/src/common/spec-parser/interfaces.ts
- packages/fx-core/src/common/spec-parser/manifestUpdater.ts
- packages/fx-core/src/common/spec-parser/utils.ts
- packages/fx-core/tests/common/spec-parser/manifestUpdater.test.ts
- packages/fx-core/tests/common/spec-parser/utils.test.ts
1. Each post body property should be a parameter
2. Optional parameter should not map to manifest
3. Resolve server url environment variables
> perf(spec-parser): only allow single parameter to manifest for post

- packages/vscode-extension/package.json
- packages/vscode-extension/src/treeview/account/common.ts
- packages/vscode-extension/src/treeview/account/sideloadingNode.ts
- packages/vscode-extension/test/extension/treeview/account/sideloadingNode.test.ts
Part of: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/24918417/
- Add info icon when sideloading disabled, including tooltip
- Adjust icon when check fails
Happy Path (unchanged):
Disable:
Unknown:
> refactor: adjust sideloading check icon

- templates/csharp/copilot-plugin-from-scratch/appPackage/adaptiveCards/repair.data.json
- templates/csharp/copilot-plugin-from-scratch/appPackage/apiSpecFiles/repair.yml
- templates/csharp/copilot-plugin-from-scratch/appPackage/manifest.json.tpl
- templates/csharp/copilot-plugin-from-scratch/infra/azure.bicep
- templates/js/copilot-plugin-from-scratch/.vscode/tasks.json
- templates/js/copilot-plugin-from-scratch/appPackage/adaptiveCards/repair.data.json
- templates/js/copilot-plugin-from-scratch/appPackage/apiSpecFiles/repair.yml
- templates/js/copilot-plugin-from-scratch/appPackage/manifest.json.tpl
- templates/js/copilot-plugin-from-scratch/infra/azure.bicep
- templates/ts/copilot-plugin-from-scratch/.vscode/tasks.json
- templates/ts/copilot-plugin-from-scratch/appPackage/adaptiveCards/repair.data.json
- templates/ts/copilot-plugin-from-scratch/appPackage/apiSpecFiles/repair.yml
- templates/ts/copilot-plugin-from-scratch/appPackage/manifest.json.tpl
- templates/ts/copilot-plugin-from-scratch/infra/azure.bicep
- Add relevant configurations to allow the URL in [openAPI yaml file](https://github.com/OfficeDev/TeamsFx/pull/9806/files#diff-81e2ba4c92c3a0bf9c08569ac24f2f5983197aeeedc2b76fb3e70fb2cdf134d5R6) to support multi envs.
- Add [repair.data.json](https://github.com/OfficeDev/TeamsFx/pull/9806/files#diff-4ffb9be6d6db1e9828fdd4cb8634e51db10360c4f9453ce9911dcf2b51b4e9c8R1-R8) file to allow users to load sample data when previewing adaptive cards.
> build: multi env support for the repair api url

- packages/cli/src/commands/models/package.ts
- packages/cli/src/commands/models/publish.ts
- packages/cli/src/commands/models/updateTeamsApp.ts
- packages/cli/src/commands/models/validate.ts
- packages/cli/tests/unit/commands.tests.ts
- packages/fx-core/src/component/driver/teamsApp/validate.ts
- packages/fx-core/tests/component/driver/teamsApp/validate.test.ts
1) Set default mode and examples
2) Update log:
3) Validate options:
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25051130
> refactor: update CLI with new ux

- packages/fx-core/resource/package.nls.json
- packages/fx-core/src/component/driver/aad/create.ts
- packages/fx-core/src/component/driver/aad/error/aadAppNameTooLongError.ts
- packages/fx-core/src/component/driver/botAadApp/create.ts
- packages/fx-core/tests/component/driver/aad/create.test.ts
- packages/fx-core/tests/component/driver/botAadApp/create.test.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25051224
Can't reuse `InvalidActionInputError` because it does not contain error details, which is important for this error to tell users how to fix it.
> refactor: add error class for AAD app name too long error

- packages/cli/src/commands/models/create.ts
- packages/cli/tests/unit/commands.tests.ts
- packages/fx-core/src/common/featureFlags.ts
- packages/fx-core/src/question/create.ts
- packages/fx-core/tests/core/FxCore.test.ts
- packages/fx-core/tests/question/create.test.ts
- packages/vscode-extension/src/extension.ts
COPILOT_PLUGIN: Bot Copilot plugin enabled
API_COPILOT_PLUGIN && COPILOT_PLUGIN: API Copilot Plugin enabled. 
API_COPILOT_PLUGIN - Default is true for now for Dogfood bits. Will update to false before Sept. prerelease.
> refactor: copilot plugin feature flags

- packages/fx-core/resource/yaml-schema/v1.3/yaml.schema.json
- packages/fx-core/src/common/constants.ts
- packages/fx-core/src/common/featureFlags.ts
- packages/fx-core/src/component/configManager/validator.ts
- packages/fx-core/tests/component/configManager/validator.test.ts
Add devTool/install argument schema for test tool 
Diff with version 1.2 for easier viewing:
> feat: add v1.3 schema for test tool

- packages/cli/package.json
fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25096039
revert rename
> fix: revert cli rename

- packages/fx-core/src/common/deps-checker/internal/testToolChecker.ts
- packages/fx-core/tests/common/deps-checker/testToolChecker.test.ts
If the tgz file path contains special characters, npm install will fail.
> fix: TestToolChecker special characters in file path

- packages/fx-core/src/common/deps-checker/constant/telemetry.ts
- packages/fx-core/src/common/deps-checker/internal/testToolChecker.ts
- packages/fx-core/tests/common/deps-checker/testToolChecker.test.ts
- if portable versions are installed in home, reuse the latest working version
- if globally installed, use global version
- change symbol link path from  `.fx/bin/testTool/1.2.3/node_modules/.bin` to `.fx/bin/testTool/1.2.3` to solve npm link issue on Windows
TODO: update PATH env variable for sample apps in TeamsAppTestTool repo.
> feat: test tool corner cases

- .github/scripts/fxcore-sync-up-version.js
- packages/fx-core/src/common/templates-config.json
- templates/package.json
We are going to release templates@3.0.4, which contains a new template for VS.
To avoid conflict, we have to upgrade template version to 4.0.0 in VSC release/5.2.0. 
This PR also update the version pattern so we can use the minor version for this kind of changes in the future.
```
> node .\.github\scripts\fxcore-sync-up-version.js
================== template version: 4.0.0 ==================
================== template version in fx-core configurate as 3.0.x ==================
================== template config version is not match with template latest release version, need bump up config version ^${templateVersion} ==================
```
> ci: bump up template version

- packages/fx-core/src/core/environment.ts
- packages/fx-core/tests/component/envUtil.test.ts
- packages/vscode-extension/package.json
- packages/vscode-extension/package.nls.json
- packages/vscode-extension/src/extension.ts
- packages/vscode-extension/src/handlers.ts
- packages/vscode-extension/src/telemetry/extTelemetryEvents.ts
- packages/vscode-extension/src/treeview/environmentTreeItem.ts
- packages/vscode-extension/test/extension/handlers.test.ts
- packages/vscode-extension/test/extension/treeview/environmentTreeItem.test.ts
Make testtool env similar to local env.
Only affects projects that have "testtool" env.
> feat: treat testtool env as a local env in treeview

- packages/fx-core/src/common/spec-parser/adaptiveCardWrapper.ts
- packages/fx-core/src/common/spec-parser/constants.ts
- packages/fx-core/src/common/spec-parser/interfaces.ts
- packages/fx-core/src/common/spec-parser/specParser.ts
- packages/fx-core/tests/common/spec-parser/adaptiveCardWrapper.test.ts
Wrap adaptive card as below for SME:
```
{
version: "devPreview",
$schema: "<URL_REFERENCE_TO_SCHEMA>",
responseLayout: "list",
responseCardTemplate: card,
previewCardTemplate: {
title: title,
subtitle: subtitle,
},
};
```
> perf(spec-parser): wrap adaptive card

- packages/cli/package.json
- packages/cli/src/commands/engine.ts
- packages/cli/src/commonlib/telemetry.ts
- packages/cli/src/error.ts
- packages/cli/src/telemetry/cliTelemetry.ts
- packages/cli/tests/unit/commands.tests.ts
- packages/cli/tests/unit/engine.tests.ts
- packages/cli/tests/unit/telemetry.tests.ts
fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25186195
> fix(cli): disable telemetry when the global option is turned off

- templates/csharp/copilot-plugin-existing-api/{{ProjectName}}.csproj.tpl
- templates/csharp/copilot-plugin-from-oai-plugin/{{ProjectName}}.csproj.tpl
- templates/csharp/copilot-plugin-from-scratch/{{ProjectName}}.csproj.tpl
For API ME projects, add capability as the feature flag for "Add API".
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25177849
> fix: add capability to templates

- .github/workflows/all-versions-upgrade-test.yml
- docs/cli/user-manual.md
- packages/tests/src/commonlib/cliHelper.ts
- packages/tests/src/e2e/README.md
- packages/tests/src/e2e/bot/BotHappyPathCommon.ts
- packages/tests/src/e2e/bot/CommandBotHappyPathCommon.ts
- packages/tests/src/e2e/bot/NotificationBotHappyPathCommon.ts
- packages/tests/src/e2e/bot/WorkflowBotHappyPathCommon.ts
- packages/tests/src/e2e/collaboration/Permission.tests.ts
- packages/tests/src/e2e/collaboration/PermissionSPFX.tests.ts
- packages/tests/src/e2e/multienv/TestRemoteHappyPath.tests.ts
- packages/tests/src/e2e/multienv/TestRemoteHappyPathSPFx.tests.ts
- packages/tests/src/e2e/spfx/CreateSPFxProjectMinimalFramework.tests.ts
- packages/tests/src/e2e/spfx/CreateSPFxProjectWithoutFramework.tests.ts
- packages/tests/src/ui-test/cliHelper.ts
- packages/tests/src/ui-test/localdebug/localdebugContext.ts
- packages/tests/src/utils/executor.ts
fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25204710
> fix: e2e test cli option capability

- packages/fx-core/src/common/spec-parser/adaptiveCardGenerator.ts
- packages/fx-core/tests/common/spec-parser/adaptiveCardGenerator.test.ts
[Bug 25150444](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25150444): [API ME] Better way to show value in the adaptive card when the value is missing in the response
For previewCardTemplate, we need further discussion before making changes
> perf(spec-parser): show N/A when value in AC is missing

- packages/fx-core/src/common/local/constants.ts
- packages/vscode-extension/src/debug/localTelemetryReporter.ts
- packages/vscode-extension/src/debug/teamsfxTaskHandler.ts
- packages/vscode-extension/src/error.ts
- packages/vscode-extension/src/telemetry/extTelemetryEvents.ts
- Test tool won't use vscode launch.json to launch browser, so old telemetry logic to send "debug-all" doesn't work
- Change to send "debug-all" in the "Launch Test Tool" task which is the final task for "Debug in Test Tool"
TODO: send test tool logs in telemetry
> feat: add telemetry for debug in test tool

- templates/common/copilot-plugin-existing-api/teamsapp.yml.tpl
- templates/common/copilot-plugin-from-oai-plugin/teamsapp.yml.tpl
- templates/constraints/yml/templates/common/copilot-plugin-existing-api/teamsapp.yml.tpl.mustache
- templates/constraints/yml/templates/common/copilot-plugin-from-oai-plugin/teamsapp.yml.tpl.mustache
- templates/constraints/yml/templates/csharp/copilot-plugin-existing-api/teamsapp.yml.tpl.mustache
- templates/constraints/yml/templates/csharp/copilot-plugin-from-oai-plugin/teamsapp.yml.tpl.mustache
- templates/constraints/yml/templates/csharp/copilot-plugin-from-scratch/teamsapp.local.yml.tpl.mustache
- templates/constraints/yml/templates/csharp/copilot-plugin-from-scratch/teamsapp.yml.tpl.mustache
- templates/constraints/yml/templates/js/copilot-plugin-from-scratch/teamsapp.local.yml.tpl.mustache
- templates/constraints/yml/templates/js/copilot-plugin-from-scratch/teamsapp.yml.tpl.mustache
- templates/constraints/yml/templates/ts/copilot-plugin-from-scratch/teamsapp.local.yml.tpl.mustache
- templates/constraints/yml/templates/ts/copilot-plugin-from-scratch/teamsapp.yml.tpl.mustache
- templates/csharp/copilot-plugin-existing-api/teamsapp.yml.tpl
- templates/csharp/copilot-plugin-from-oai-plugin/teamsapp.yml.tpl
- templates/csharp/copilot-plugin-from-scratch/teamsapp.local.yml.tpl
- templates/csharp/copilot-plugin-from-scratch/teamsapp.yml.tpl
- templates/js/copilot-plugin-from-scratch/teamsapp.local.yml.tpl
- templates/js/copilot-plugin-from-scratch/teamsapp.yml.tpl
- templates/ts/copilot-plugin-from-scratch/teamsapp.local.yml.tpl
- templates/ts/copilot-plugin-from-scratch/teamsapp.yml.tpl
Temporarily disable this action due to dev preview schema not released. Will bring it back when schema ready.
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25124059
> refactor: disable validate manifest action for unreleased dev preview schema

- packages/fx-core/src/common/spec-parser/manifestUpdater.ts
- packages/fx-core/src/common/spec-parser/utils.ts
- packages/fx-core/tests/common/spec-parser/manifestUpdater.test.ts
- packages/fx-core/tests/common/spec-parser/utils.test.ts
[Bug 25203352](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25203352): [API ME] Treat required + default parameter as optional when list supported apis
> perf(spec-parser): treat required + default parameter as optional parameter

- packages/vscode-extension/PRERELEASE.md
Changelog for 0926 Prerelease.
> docs: update changelog for 926 prerelease

- packages/api/review/teamsfx-api.api.md
- packages/api/src/cli.ts
- packages/cli/src/commands/engine.ts
- packages/cli/src/commands/models/m365Sideloading.ts
- packages/cli/src/commands/models/m365Unacquire.ts
- packages/cli/src/commands/models/permission.ts
- packages/cli/tests/unit/engine.tests.ts
fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25239178
1. command alias for m365 sideloading/install and unacuire/uninstall
2. command alias for permission/collaborator
> fix: command alias

- packages/fx-core/src/component/utils/envUtil.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25150410
> fix: avoid set process.env to local when env.local doesn't exist

- packages/fx-core/src/common/spec-parser/adaptiveCardGenerator.ts
- packages/fx-core/src/common/spec-parser/adaptiveCardWrapper.ts
- packages/fx-core/src/common/spec-parser/constants.ts
- packages/fx-core/src/common/spec-parser/specParser.ts
- packages/fx-core/src/common/spec-parser/utils.ts
- packages/fx-core/tests/common/spec-parser/adaptiveCardGenerator.test.ts
- packages/fx-core/tests/common/spec-parser/adaptiveCardWrapper.test.ts
- packages/fx-core/tests/common/spec-parser/utils.test.ts
[Bug 25216653](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25216653): jsonPath support
The code will attempt to identify if the array property in the root contains any of the well-known substrings below. If found, it will use the property as a JSON path:
```js
static readonly WellknownResultNames = [
"result",
"data",
"items",
"root",
"matches",
"queries",
"list",
"output",
];
```
Yuqi and I have[ an investigation](https://microsoft-my.sharepoint.com/personal/yuqzho_microsoft_com/_layouts/15/Doc.aspx?sourcedoc={41143a23-0931-4bf9-90be-f2e47ee91491}&action=edit&wd=target%28New%20Section%201.one%7C1ccf704e-b58b-4db3-aaa6-c39ee69bbe0d%2FAPI%20Spec%20Response%7Ce3279249-e16c-4ba0-ba6f-de1af41a5af4%2F%29&wdorigin=703) about the names in spec file.
TODO: …
> perf(spec-parser): add jsonPath support

- packages/cli/src/index.ts
fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25096039
> fix: update warning message for old cli name

- packages/fx-core/src/component/generator/officeAddin/helperMethods.ts
- packages/fx-core/tests/component/generator/officeAddinGenerator.test.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25239204
> fix: make import work when no appPackage folder exists

- packages/fx-core/src/common/templates-config.json
- templates/package.json
As a temporary solution to [this bug](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/24527017/?view=edit), we added a spfx-import template in [this PR](https://github.com/OfficeDev/TeamsFx/pull/9319).  Now SPFx v1.18 has been released and the outline icon is updated, so we removed the template in https://github.com/OfficeDev/TeamsFx/pull/10056 and bump template version here.
> ci: bump template version due to temporary spfx-import template removal

- templates/ts/copilot-plugin-from-scratch/.vscode/tasks.json
- templates/ts/copilot-plugin-from-scratch/package.json.tpl
Fix the issue of the task of watch backend not terminated after stopping local debug.
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25411618
> fix: the task of watch backend not termintated

- packages/vscode-extension/src/handlers.ts
[Bug 25283280](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25283280): unhandled error for show-scaffolding-warning-summary-error
> fix: show scaffolding summary unhandled error

- packages/vscode-extension/src/controls/sampleGallery/sampleCard.scss
- packages/vscode-extension/src/controls/sampleGallery/sampleCard.tsx
- packages/vscode-extension/src/controls/sampleGallery/sampleFilter.scss
- packages/vscode-extension/src/controls/sampleGallery/sampleFilter.tsx
- packages/vscode-extension/src/controls/sampleGallery/sampleListItem.scss
- packages/vscode-extension/src/controls/sampleGallery/sampleListItem.tsx
Related task: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25297871
- Use normal font size on unavailable sample card.
- Remove 'manual configuration required'.
- Refine search bar UI
- Support responsive sample list.
Effect:
> feat(vsc): update sample gallery UI

- packages/vscode-extension/src/constants.ts
- packages/vscode-extension/src/controls/Commands.ts
- packages/vscode-extension/src/controls/sampleGallery/ISamples.ts
- packages/vscode-extension/src/controls/sampleGallery/SampleGallery.tsx
- packages/vscode-extension/src/controls/sampleGallery/sampleCard.tsx
- packages/vscode-extension/src/controls/sampleGallery/sampleFilter.scss
- packages/vscode-extension/src/controls/sampleGallery/sampleFilter.tsx
- packages/vscode-extension/src/controls/webviewPanel.ts
- packages/vscode-extension/src/telemetry/extTelemetryEvents.ts
Task: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25415409
- Refactor filter logic.
- Store layout data in VS Code global state.
> feat(vsc): persist layout data in sample gallery

- packages/dotnet-sdk/CHANGELOG.md
- packages/dotnet-sdk/src/TeamsFx.Test/Conversation/NotificationMiddlewareTest.cs
- packages/dotnet-sdk/src/TeamsFx/Conversation/NotificationMiddleware.cs
- packages/dotnet-sdk/src/TeamsFx/Microsoft.TeamsFx.csproj
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25397717/
https://github.com/OfficeDev/TeamsFx/issues/10081
When adding to a Team, conversation reference key should use team id instead of conversation id.
E2E Test: N/A
> fix(dotnet-sdk): correct notification key generation

- packages/simpleauth/src/TeamsFxSimpleAuth.Tests/Microsoft.TeamsFx.SimpleAuth.Tests.csproj
CVE-2023-36414
Bumping to Azure.Identity >= 1.10.2 to fix the vulnerability
> fix: vulnerability in Azure.Identity dependency

- templates/common/copilot-plugin-existing-api/teamsapp.yml.tpl
- templates/common/copilot-plugin-from-oai-plugin/teamsapp.yml.tpl
- templates/constraints/yml/templates/common/copilot-plugin-existing-api/teamsapp.yml.tpl.mustache
- templates/constraints/yml/templates/common/copilot-plugin-from-oai-plugin/teamsapp.yml.tpl.mustache
- templates/constraints/yml/templates/csharp/copilot-plugin-existing-api/teamsapp.yml.tpl.mustache
- templates/constraints/yml/templates/csharp/copilot-plugin-from-oai-plugin/teamsapp.yml.tpl.mustache
- templates/constraints/yml/templates/csharp/copilot-plugin-from-scratch/teamsapp.local.yml.tpl.mustache
- templates/constraints/yml/templates/csharp/copilot-plugin-from-scratch/teamsapp.yml.tpl.mustache
- templates/constraints/yml/templates/js/copilot-plugin-from-scratch/teamsapp.local.yml.tpl.mustache
- templates/constraints/yml/templates/js/copilot-plugin-from-scratch/teamsapp.yml.tpl.mustache
- templates/constraints/yml/templates/ts/copilot-plugin-from-scratch/teamsapp.local.yml.tpl.mustache
- templates/constraints/yml/templates/ts/copilot-plugin-from-scratch/teamsapp.yml.tpl.mustache
- templates/csharp/copilot-plugin-existing-api/teamsapp.yml.tpl
- templates/csharp/copilot-plugin-from-oai-plugin/teamsapp.yml.tpl
- templates/csharp/copilot-plugin-from-scratch/teamsapp.local.yml.tpl
- templates/csharp/copilot-plugin-from-scratch/teamsapp.yml.tpl
- templates/js/copilot-plugin-from-scratch/teamsapp.local.yml.tpl
- templates/js/copilot-plugin-from-scratch/teamsapp.yml.tpl
- templates/ts/copilot-plugin-from-scratch/teamsapp.local.yml.tpl
- templates/ts/copilot-plugin-from-scratch/teamsapp.yml.tpl
Reverting change in PR: https://github.com/OfficeDev/TeamsFx/pull/10007
The manifest schema has been fixed, and teamsApp/validateManifest action can be added back.
Related work item: [25124059](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25124059)
> refactor: revert yaml change

- packages/fx-core/resource/package.nls.json
Related bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25526040
> fix: typo in tab detail description

- packages/fx-core/src/common/spec-parser/adaptiveCardGenerator.ts
- packages/fx-core/src/common/spec-parser/constants.ts
- packages/fx-core/src/common/spec-parser/index.browser.ts
- packages/fx-core/src/common/spec-parser/interfaces.ts
- packages/fx-core/src/common/spec-parser/manifestUpdater.ts
- packages/fx-core/src/common/spec-parser/specParser.browser.ts
- packages/fx-core/src/common/spec-parser/utils.ts
- packages/fx-core/tests/common/spec-parser/adaptiveCardGenerator.test.ts
- packages/fx-core/tests/common/spec-parser/manifestUpdater.test.ts
- packages/fx-core/tests/common/spec-parser/specParser.browser.test.ts
- packages/fx-core/tests/common/spec-parser/specParser.test.ts
- packages/fx-core/tests/common/spec-parser/utils.test.ts
- add browser api in specParser.browser.ts file
- replace node js api such as "path" and "util"
- truncate string
- test cases update
How to use browser api:
- Copy related files to your project: 
- specParser.browser.ts
- index.browser.ts
- constants.ts
- interfaces.ts
- utils.ts
- Install packages
- @apidevtools/swagger-parser
- "openapi-types"
- @microsoft/teams-manifest
- change below import in utils file
- import { IMessagingExtensionCommand } from "@microsoft/teamsfx-api"; 
->
- import { IMessagingExtensionCommand } from "@microsoft/teams-manifest"; 
- referece api from index.browser.ts file
> perf(spec-parser): add browser api, truncate string

- packages/fx-core/src/component/generator/copilotPlugin/helper.ts
- packages/fx-core/tests/component/generator/copilotPluginGenerator.test.ts
* refactor: rename
* test: ut
[Bug 25579499](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25579499): [API ME] Scaffolding warning summary
> fix: update suffix placeholder 

- templates/csharp/message-extension-action/Action/ActionApp.cs.tpl
- templates/js/message-extension-action/src/actionApp.js
- templates/ts/message-extension-action/src/actionApp.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25577750
> fix: use '' when input is empty

- packages/fx-core/resource/yaml-schema/v1.3/yaml.schema.json
- packages/fx-core/src/component/configManager/validator.ts
- packages/fx-core/src/component/driver/devTool/installDriver.ts
- packages/fx-core/src/component/driver/devTool/interfaces/InstallToolArgs.ts
- packages/fx-core/tests/component/configManager/validator.test.ts
- packages/fx-core/tests/component/driver/devTool/installDriver.test.ts
- Disable test tool install logic because YAML 1.3 release is before test tool release. This is to prevent from accidentally using test tool driver between 1.3 schema release and test tool release
- remove feature flag
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/16357625/
> feat: test tool install schema for 1.3

- packages/sdk/src/conversation/storage.ts
- packages/sdk/test/unit/node/conversation/storage.spec.ts
Support to set notification local store via environment variable, so Test Tool can save conversation reference in a separated file.
work item: [24320317](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/24320317)
> feat(sdk): support set notification localstore file name with env variable

- packages/fx-core/resource/yaml-schema/v1.3/yaml.schema.json
Because 
1. VS may well not use yaml to install test tool so no need to consider schema for VS
2. func install has optional symlinkDir because of historic version so no need to keep consistent with it
3. If use manually delete symlinkDir property, start test tool will fail.
As a result, change symlinkDir to required.
> fix: symlinkDir for testTool doesn't need to be optional

- packages/fx-core/src/common/spec-parser/interfaces.ts
- packages/fx-core/src/common/spec-parser/specParser.browser.ts
- packages/fx-core/src/common/spec-parser/specParser.ts
- packages/fx-core/src/component/generator/copilotPlugin/helper.ts
- packages/fx-core/src/core/FxCore.ts
- packages/fx-core/src/question/create.ts
- packages/fx-core/tests/common/spec-parser/specParser.browser.test.ts
- packages/fx-core/tests/common/spec-parser/specParser.test.ts
- packages/fx-core/tests/core/FxCore.test.ts
- packages/fx-core/tests/question/create.test.ts
- Update list function to have operationId property
- Use list function instead of listOperationMap when add new api, remove listOperationMap api
- Fix update teams manifest doesn't contain auth property
- Fix domain check
> perf(spec-parser): update add new api logic to use list function

- packages/fx-core/src/common/deps-checker/internal/testToolChecker.ts
- packages/fx-core/src/common/featureFlags.ts
- packages/fx-core/src/component/driver/devTool/installDriver.ts
- packages/fx-core/src/component/driver/devTool/interfaces/InstallToolArgs.ts
- packages/fx-core/src/component/generator/generator.ts
- packages/fx-core/tests/common/deps-checker/testToolChecker.test.ts
- packages/fx-core/tests/component/generator/generator.test.ts
- templates/ts/notification-restify/.gitignore
- templates/ts/notification-restify/.localConfigs.testTool
- templates/ts/notification-restify/.vscode/launch.json.tpl
- templates/ts/notification-restify/.vscode/tasks.json
- templates/ts/notification-restify/env/.env.testtool
- templates/ts/notification-restify/package.json.tpl
- templates/ts/notification-restify/teamsapp.testtool.yml
- if `enableTestToolByDefault` set to true, F5 will launch debug in test tool by default, otherwise, debug in test tool launch profile will still be scaffolded but not the default launch profile.
- `enableTestToolByDefault` is enabled by default
- update test tool driver to match new package name
TODO: README and other bot templates
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/16357625/
> feat: update templates to support test tool

- templates/ts/notification-restify/README.md.tpl
When test tool is enabled by default (prerelease version), prerequisites and instructions in README will be for debug in test tool. Otherwise, README will be the same previously.
> docs: update template readme for test tool

- packages/fx-core/src/common/deps-checker/internal/testToolChecker.ts
- packages/fx-core/tests/common/deps-checker/testToolChecker.test.ts
Fix the bug: if there is only one version released on npm, every F5 will cause reinstall of test tool.
> fix: corner cases for npm view command

- packages/cli/tests/unit/utils.tests.ts
- packages/fx-core/src/common/samples.ts
- packages/fx-core/tests/common/samples-config-v3.json
- packages/fx-core/tests/common/samples.test.ts
- packages/vscode-extension/src/controls/sampleGallery/ISamples.ts
- packages/vscode-extension/src/controls/sampleGallery/SampleGallery.tsx
- packages/vscode-extension/src/controls/sampleGallery/sampleFilter.tsx
- packages/vscode-extension/src/controls/sampleGallery/sampleListItem.scss
- packages/vscode-extension/src/controls/sampleGallery/sampleListItem.tsx
Effect:
Related PR:
https://github.com/OfficeDev/TeamsFx-Samples/pull/1073
Also fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25663359
> refactor: rename filter options

- packages/fx-core/resource/package.nls.json
- packages/fx-core/src/component/driver/teamsApp/createAppPackage.ts
- packages/fx-core/src/error/teamsApp.ts
- packages/fx-core/tests/component/driver/teamsApp/createAppPackage.test.ts
Bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/24879976
1) Files outside directory is not allowed:
2) Deal with "../", this cannot be the filename in zip directly
> fix: relative path check

- packages/fx-core/src/common/samples.ts
- packages/fx-core/tests/common/samples.test.ts
- packages/fx-core/tests/component/generator/generator.test.ts
Related task: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25518911
Sample config has breaking change.
'v2.4.0' tag will be published before next RC & stable TTK release.
> feat(core): bump sample tag version

- templates/js/notification-http-timer-trigger/package.json.tpl
- templates/js/notification-http-trigger/package.json.tpl
- templates/js/notification-restify/package.json.tpl
- templates/js/notification-timer-trigger/package.json.tpl
- templates/ts/notification-http-timer-trigger/package.json.tpl
- templates/ts/notification-http-trigger/package.json.tpl
- templates/ts/notification-restify/package.json.tpl
- templates/ts/notification-timer-trigger/package.json.tpl
Manually update notification tempaltes to beta version so that CD pipeline will update these templates to the latest beta version
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25757321/
> fix: change notification templates to use new SDK

- packages/fx-core/src/question/other.ts
- packages/fx-core/tests/question/other.test.ts
Test tool is pure local and doesn't support manifest so it is meaningless to zip manifest / validate application / etc. It will always fail. Hide testtool env in env selection UI because only entrypoint for deploy in testtool env is tasks.json.
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25758411
> fix: should not zip manifest / validation app /etc. for test tool

- packages/vscode-extension/src/controls/sampleGallery/sampleCard.scss
- packages/vscode-extension/src/controls/sampleGallery/sampleCard.tsx
- packages/vscode-extension/src/controls/sampleGallery/sampleFilter.scss
- packages/vscode-extension/src/controls/sampleGallery/sampleFilter.tsx
Related bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25858387
Effect:
> fix(vsc): color of search box and sample card shadow

- templates/csharp/copilot-plugin-from-scratch/Models/RepairModel.cs.tpl
- templates/csharp/copilot-plugin-from-scratch/Program.cs
- templates/csharp/copilot-plugin-from-scratch/Repair.cs.tpl
- templates/csharp/copilot-plugin-from-scratch/RepairData.cs.tpl
- templates/csharp/copilot-plugin-from-scratch/host.json
- templates/csharp/copilot-plugin-from-scratch/infra/azure.bicep
- templates/csharp/copilot-plugin-from-scratch/local.settings.json
- templates/csharp/copilot-plugin-from-scratch/{{ProjectName}}.csproj.tpl
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25770678
- Migrating .NET apps from the in-process model to the [isolated worker model](https://learn.microsoft.com/en-us/azure/azure-functions/migrate-dotnet-to-isolated-model?tabs=net8). Currently, our Azure Function runtime uses the in-process model, but .NET 8 is not yet supported on the in-process model.
- Change the data type of the "Id" field in the repair data model to `string` for consistency with VSC.
> fix: api me from scratch cannot debug after upgrading to .net 8

- templates/csharp/notification-http-timer-trigger/{{ProjectName}}.csproj.tpl
- templates/csharp/notification-http-trigger/{{ProjectName}}.csproj.tpl
- templates/csharp/notification-timer-trigger/{{ProjectName}}.csproj.tpl
Fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25944655/
E2E Test: N/A
Fix the package downgrade issue by adding the empty `Microsoft.NETCore.Targets` package to remove the legacy `runtime.json` file. More details can be found from https://stackoverflow.com/questions/74453395/serilog-net-7-error-nu1605-detected-package-downgrade-and-microsoft-netco
> fix: .net function-based notification package downgrade

- packages/fx-core/src/component/generator/generator.ts
- packages/fx-core/src/component/generator/generatorAction.ts
- packages/fx-core/src/component/generator/utils.ts
- packages/fx-core/tests/component/generator/generator.test.ts
- packages/fx-core/tests/component/generator/generatorAction.test.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25860181/
1.	Generate template and generate sample should only do below:
-	Construct generator context
-	Loop over generate actions
-	Merge telemetry
2.	Errors should only be thrown in action and utils
3.	If catched error is already BaseComponentError, throw the error;
If not, classify error according to action name
> refactor: improve error handling for generator

- packages/fx-core/src/common/spec-parser/interfaces.ts
- packages/fx-core/src/common/spec-parser/specFilter.ts
- packages/fx-core/src/common/spec-parser/specParser.browser.ts
- packages/fx-core/src/common/spec-parser/specParser.ts
- packages/fx-core/src/common/spec-parser/utils.ts
- packages/fx-core/src/component/driver/apiKey/create.ts
- packages/fx-core/src/component/generator/copilotPlugin/helper.ts
- packages/fx-core/src/core/FxCore.ts
- packages/fx-core/tests/common/spec-parser/specFilter.test.ts
- packages/fx-core/tests/common/spec-parser/utils.test.ts
Add support to list APIs with below auth type:
```
authSchema.type === "oauth2" ||
authSchema.type === "openIdConnect" ||
(authSchema.type === "http" && authSchema.scheme === "bearer")
```
> perf(spec-parser): allow list oauth2 api

- packages/fx-core/resource/package.nls.json
- packages/fx-core/src/question/create.ts
- packages/fx-core/tests/question/create.test.ts
Related bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/24965003
> fix(core): show warning when app name length is 24

- packages/fx-core/src/common/deps-checker/coreDepsLoggerAdapter.ts
- packages/fx-core/src/common/deps-checker/coreDepsTelemetryAdapter.ts
- packages/fx-core/src/common/deps-checker/index.ts
- packages/fx-core/tests/common/deps-checker/coreDepsLoggerAdapter.test.ts
- packages/fx-core/tests/common/deps-checker/coreDepsTelemetryAdapter.test.ts
- packages/server/src/apis.ts
- packages/server/src/serverConnection.ts
- packages/server/tests/serverConnection.test.ts
In server, expose testToolChecker logic from core, for VS test tool automatic installation feature.
> feat: expose test tool checker for VS

- packages/fx-core/resource/package.nls.json
- packages/fx-core/src/component/driver/aad/error/aadManifestError.ts
- packages/fx-core/src/component/driver/aad/utility/aadAppClient.ts
- packages/fx-core/src/component/driver/aad/utility/constants.ts
- packages/fx-core/tests/component/driver/aad/aadAppClient.test.ts
If `aadApp/update` action failed with HostNameNotOnVerifiedDomain error, it means user is trying to update a multi tenant AAD app but not using a verified domain in application id uri. Throw a specific error with multi tenant SSO help link to guide users how to enable SSO for a multi tenant AAD app.
https://dev.azure.com/msazure/Microsoft%20Teams%20Extensibility/_workitems/edit/25053148
> feat: provide multi tenant SSO help link when related error happens

- packages/fx-core/resource/package.nls.json
- packages/fx-core/src/component/driver/aad/error/aadManifestError.ts
- packages/fx-core/src/component/driver/aad/utility/aadManifestHelper.ts
- packages/fx-core/tests/component/driver/aad/aadManifestHelper.test.ts
https://dev.azure.com/msazure/Microsoft%20Teams%20Extensibility/_workitems/edit/25519522
The expected AAD manifest snippet should look like this:
``` js
requiredResourceAccess: [
{
resourceAppId: "Microsoft Graph",
resourceAccess: [
{
id: "User.Read",
type: "Scope",
},
],
},
],
```
If the AAD manifest misses `resourceAppId` property, the error would be: Some item(s) in requiredResourceAccess misses resourceAppId property.
If the AAD manifest misses `id` proerty, the error would be: Some item(s) in resourceAccess misses id property.
> fix: expected a string but received a undefined error when AAD manifest misses required id

- packages/fx-core/src/component/generator/spfx/spfxGenerator.ts
- packages/fx-core/src/component/generator/spfx/utils/utils.ts
- packages/fx-core/tests/component/generator/spfxGenerator.test.ts
[Bug 26162235](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/26162235): Variable {{APP_NAME_SUFFIX}} will cut to be a string for the app name (> 10 characters) when importing SPFx project
> fix: import spfx truncate app name

- packages/fx-core/src/common/spec-parser/constants.ts
- packages/fx-core/src/common/spec-parser/generateTeamsAiMaterial.ts
- packages/fx-core/src/common/spec-parser/interfaces.ts
- packages/fx-core/src/common/spec-parser/manifestUpdater.ts
- packages/fx-core/src/common/spec-parser/specParser.ts
- packages/fx-core/src/common/spec-parser/utils.ts
```ts
async function test() {
const specParser = new SpecParser(__dirname + "/teamsai.yaml", { allowMultipleParameters: true });
const validationRes = await specParser.validate();
const apiResultList = await specParser.list();
const [actionJson, configJson, prompt, actionCode] = await specParser.updateTeamsAiApp(
[
"GET /pet/{petId}",
"GET /pet/findByTags",
"GET /store/order/{orderId}",
"GET /user/login",
"GET /user/{username}",
],
__dirname + "/teamsai.spec.yaml"
);
console.log(JSON.stringify(actionJson, null, 2));
console.log(JSON.stringify(configJson, null, 2));
console.log(JSON.stringify(prompt, null, 2));
console.log(JSON.stringify(actionCode, null, 2));
}
```
result:
actionJson
```json
{
"name": "getPetById",
"description": "Returns a single pet",
"parameters": {
"type": "object", …
```
> perf(spec-parser): add teams ai app support

- packages/server/src/apis.ts
- packages/server/src/serverConnection.ts
- packages/server/tests/serverConnection.test.ts
Because `Error` object lacks `message` when serialized by RPC server, the end result is output will contain an empty error message. Now convert Error to pure JSON object to avoid that issue.
> fix: empty error message if failed to install test tool

- templates/csharp/ai-assistant-bot/GettingStarted.md
- templates/csharp/ai-bot/GettingStarted.md
Add instructions to debug in Test Tool in GettingStarted.md for AI chat bot and Assistant bot template.
Preview:
1. AI chat bot‘s GettingStarted.md: https://github.com/OfficeDev/TeamsFx/blob/qinezh/doc/templates/csharp/ai-bot/GettingStarted.md
2.Assistant bot's GettingStarted.md: https://github.com/OfficeDev/TeamsFx/blob/qinezh/doc/templates/csharp/ai-assistant-bot/GettingStarted.md
> fix: add instructions to debug in Test Tool in GettingStarted.md

- packages/fx-core/src/error/teamsApp.ts
fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/26254996
> fix: set api name as categories for TDP error

- templates/csharp/link-unfurling/appPackage/manifest.json.tpl
- templates/js/link-unfurling/appPackage/manifest.json.tpl
- templates/ts/link-unfurling/appPackage/manifest.json.tpl
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/26265585
> fix: remove commands from link unfurling manifest

- packages/fx-core/src/component/generator/spfx/error.ts
- packages/fx-core/src/component/generator/spfx/spfxGenerator.ts
- packages/fx-core/src/component/generator/spfx/utils/constants.ts
- packages/fx-core/src/component/generator/spfx/utils/telemetryEvents.ts
- packages/fx-core/tests/component/generator/spfxGenerator.test.ts
- templates/ts/spfx-tab/package.json.tpl
[Bug 26215868](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/26215868): Update node version in SPFx templates
Get node versions from SPFx project rather than hardcode the value in the template.
> fix: get node version from spfx solution

- .github/workflows/e2e-test.yml
https://github.com/OfficeDev/TeamsFx/pull/10620
if execute-cases or e2e-coverage skipped, the tear-down should always skipped
> ci: update tear down condition

- packages/vscode-extension/src/controls/sampleGallery/offlinePage.scss
- packages/vscode-extension/src/controls/sampleGallery/offlinePage.tsx
Related bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/26207252
Effect:
> fix(vsc): description of sample gallery offline page

- docs/vscode-extension/envchecker-help.md
- packages/cli/src/cmds/preview/constants.ts
- packages/cli/src/resource/strings.json
- packages/fx-core/src/common/deps-checker/constant/helpLink.ts
- packages/vscode-extension/src/debug/depsChecker/doctorConstant.ts
Update node.js installation link from `https://nodejs.org/about/releases/` to `https://nodejs.org`.
work item: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/26243007
> fix: update nodejs installation link

- templates/csharp/ai-assistant-bot/{{ProjectName}}.csproj.tpl
- templates/csharp/ai-bot/{{ProjectName}}.csproj.tpl
- templates/csharp/command-and-response/{{ProjectName}}.csproj.tpl
- templates/csharp/copilot-plugin-existing-api-api-key/{{ProjectName}}.csproj.tpl
- templates/csharp/copilot-plugin-existing-api/{{ProjectName}}.csproj.tpl
- templates/csharp/copilot-plugin-from-oai-plugin/{{ProjectName}}.csproj.tpl
- templates/csharp/copilot-plugin-from-scratch/{{ProjectName}}.csproj.tpl
- templates/csharp/default-bot/{{ProjectName}}.csproj.tpl
- templates/csharp/link-unfurling/{{ProjectName}}.csproj.tpl
- templates/csharp/message-extension-action/{{ProjectName}}.csproj.tpl
- templates/csharp/message-extension-copilot/{{ProjectName}}.csproj.tpl
- templates/csharp/message-extension-search/{{ProjectName}}.csproj.tpl
- templates/csharp/message-extension/{{ProjectName}}.csproj.tpl
- templates/csharp/non-sso-tab-ssr/{{ProjectName}}.csproj.tpl
- templates/csharp/non-sso-tab/{{ProjectName}}.csproj.tpl
- templates/csharp/notification-http-timer-trigger/{{ProjectName}}.csproj.tpl
- templates/csharp/notification-http-trigger/{{ProjectName}}.csproj.tpl
- templates/csharp/notification-timer-trigger/{{ProjectName}}.csproj.tpl
- templates/csharp/notification-webapi/{{ProjectName}}.csproj.tpl
- templates/csharp/sso-tab-ssr/{{ProjectName}}.csproj.tpl
- templates/csharp/sso-tab/{{ProjectName}}.csproj.tpl
- templates/csharp/workflow/{{ProjectName}}.csproj.tpl
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/26259922
`build` folder has no files and it has been placed under `appPackage` by `fx-core`. It will make the json as content files and copy them to output folder automatically.
`dotnet8` seems to lock the `manifest.dev.json` file. It will try to copy this file when building the project, so the lock will return the error. After setting it as non-content file, the issue will be worked around.
> fix: replace build to appPackage folder

- packages/manifest/src/index.ts
For bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/26399801
Opened an issue to improve dev preview schema: 
https://github.com/microsoft/json-schemas/issues/173
> fix: disable strictTypes for dev preview schema

- packages/fx-core/src/component/utils/pathUtils.ts
fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/26461634
> fix: use default yaml file when env is not provided

- packages/fx-core/src/component/coordinator/index.ts
[Bug 26530843](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/26530843): no need confirmation button when run local debug from test tool(preview)
> fix: not show deploy dialog if testtool

- packages/cli/src/commands/engine.ts
fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/26509430
> fix: restore value split rule

- packages/fx-core/src/core/middleware/projectMigratorV3.ts
- packages/fx-core/tests/core/middleware/migration/projectMigrationV3.test.ts
[readdirSync returns deleted folder · Issue #4760 · nodejs/node (github.com)](https://github.com/nodejs/node/issues/4760)
Add double confirm for file existing
> refactor: update migration for azure parameters file not existing

- packages/fx-core/src/common/wrappedAxiosClient.ts
- packages/fx-core/tests/common/wrappedAxiosClient.test.ts
For some CLI commands, TOOLS may be undefined without initialization, cause following error:
```
(×) Error: m365.UnhandledError: An unexpected error has occurred while performing the m365 task. {"stack":"TypeError: Cannot read properties of undefined (reading 'method')\n    at
onRejected (C:\\DevDiv\\Microsoft.Teams.Extensibility\\TeamsFx\\packages\\fx-core\\build\\common\\wrappedAxiosClient.js:73:38)\
n   
```
> refactor: tools may not be initialized for some CLI commands

- packages/fx-core/src/common/wrappedAxiosClient.ts
- packages/fx-core/tests/common/wrappedAxiosClient.test.ts
1) Use arrow function to solve `this context` in callback.
https://stackoverflow.com/questions/20279484/how-to-access-the-correct-this-inside-a-callback/20279485#20279485
2) Request body may have buffer file, cannot be parsed as JSON object.
> refactor: use arrow function

- packages/fx-core/src/common/m365/packageService.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/26568238/
Show warning log if the input package is not a zip, in case the service error is not clear.
> fix: check zip package format before sideloading

- packages/spec-parser/package.json
- packages/spec-parser/src/utils.ts
- packages/spec-parser/test/utils.test.ts
[Bug 25973952](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25973952): Should not allow API if response body and request body has type other than "application/json"
> perf: not allow res/req body has type other than json

- templates/js/sso-tab-with-obo-flow/api/README.md
- templates/ts/sso-tab-with-obo-flow/api/README.md
- AzFunc project README references old & no-longer available TeamsFx CLI command ... this removes it
- see #10795 for discussion & confirmation
- fixes #10795
> fix: remove outdated docs from template README

- packages/fx-core/src/component/generator/generator.ts
- packages/fx-core/tests/component/generator/generator.test.ts
templateName should be 'scenario-language', for example 'non-sso-tab-js'
> fix: generator telemetry sends wrong templateName

- packages/vscode-extension/.vscode/settings.json
- packages/vscode-extension/src/controls/Commands.ts
- packages/vscode-extension/src/controls/sampleGallery/SampleGallery.tsx
- packages/vscode-extension/src/controls/sampleGallery/sampleDetailPage.tsx
- packages/vscode-extension/src/controls/webviewPanel.ts
- packages/vscode-extension/src/handlers.ts
- packages/vscode-extension/src/telemetry/extTelemetryEvents.ts
- packages/vscode-extension/src/uriHandler.ts
- packages/vscode-extension/src/utils/commonUtils.ts
- packages/vscode-extension/test/extension/handlers.test.ts
- packages/vscode-extension/test/extension/uriHandler.test.ts
Support using Uri to launch TTK and open designated sample detail page in sample gallery.
feature link: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/26879784
example link: [vscode://TeamsDevApp.ms-teams-vscode-extension?referrer=officedoc&sampleId=hello-world-teams-tab-and-outlook-add-in](url)
> feat: open sample from url support

- packages/fx-core/src/component/driver/aad/utility/aadAppClient.ts
- packages/fx-core/tests/component/driver/aad/aadAppClient.test.ts
Fix bug: https://dev.azure.com/msazure/Microsoft%20Teams%20Extensibility/_workitems/edit/26897313
Tested against bot-sso sample with a local build
The 180 days lifetime is recommended by Azure Portal
> fix: credential invalid lifetime error when create AAD app

- packages/fx-core/src/common/samples.ts
- packages/fx-core/tests/common/samples.test.ts
- packages/fx-core/tests/component/generator/generator.test.ts
- packages/vscode-extension/src/controls/sampleGallery/ISamples.ts
- packages/vscode-extension/src/controls/sampleGallery/sampleCard.tsx
Related bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/26625207
LFS image has a different URL with raw content.
> fix(vsc): sample gallery support LFS image in GitHub repo

- templates/csharp/notification-http-timer-trigger-isolated/{{ProjectName}}.csproj.tpl
- templates/csharp/notification-http-trigger-isolated/{{ProjectName}}.csproj.tpl
- templates/csharp/notification-timer-trigger-isolated/{{ProjectName}}.csproj.tpl
Fix the function notification name with '.'. If you do not add '<RootNamespace>{{SafeProjectName}}</RootNamespace>', the azure-functions-dotnet-worker will use the unsafe project name as the namespace.
Fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/26897390/
> fix: function project name

- packages/fx-core/src/component/generator/utils.ts
- packages/fx-core/tests/component/generator/generator.test.ts
- packages/vscode-extension/src/controls/sampleGallery/sampleCard.tsx
Related bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/27041735
> fix: github lfs file download in samples

- packages/tests/src/commonlib/appStudioValidator.ts
- packages/tests/src/e2e/bot/CommandBotHappyPathCommon.ts
There are 4 test cases with publish command, only one doesn't clean up the stagged app due to undefined app id:
After fix, it will be cleaned:
https://github.com/OfficeDev/TeamsFx/actions/runs/8136634546/job/22233947472
Related bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/27001733
> fix: clean staggged app

- packages/fx-core/src/common/samples.ts
- packages/fx-core/src/component/generator/utils.ts
- packages/fx-core/tests/common/samples.test.ts
- packages/fx-core/tests/component/generator/generator.test.ts
- packages/vscode-extension/src/controls/sampleGallery/ISamples.ts
- packages/vscode-extension/src/controls/sampleGallery/sampleCard.tsx
Cherry picked following PRs:
* https://github.com/OfficeDev/TeamsFx/pull/10908
* https://github.com/OfficeDev/TeamsFx/pull/10973
Bump sample tag to v2.5.0 to prevent showing blank thumbnail of teams-chef-bot.
> fix(vsc): sample gallery support LFS image in GitHub rep

- packages/sdk/src/conversationWithCloudAdapter/conversation.ts
- packages/sdk/test/unit/node/conversationWithCloudAdapter/conversation.spec.ts
- templates/js/ai-assistant-bot/src/index.js
- templates/js/ai-bot/src/index.js
- templates/js/command-and-response/package.json.tpl
- templates/js/default-bot/index.js
- templates/js/non-sso-tab-default-bot/bot/index.js
- templates/js/notification-http-timer-trigger/package.json.tpl
- templates/js/notification-http-trigger/package.json.tpl
- templates/js/notification-restify/package.json.tpl
- templates/js/notification-timer-trigger/package.json.tpl
- templates/js/workflow/package.json.tpl
- templates/ts/ai-assistant-bot/src/index.ts
- templates/ts/ai-bot/src/index.ts
- templates/ts/command-and-response/package.json.tpl
- templates/ts/default-bot/index.ts
- templates/ts/non-sso-tab-default-bot/bot/index.ts
- templates/ts/notification-http-timer-trigger/package.json.tpl
- templates/ts/notification-http-trigger/package.json.tpl
- templates/ts/notification-restify/package.json.tpl
- templates/ts/notification-timer-trigger/package.json.tpl
- templates/ts/workflow/package.json.tpl
Update bot templates and SDK to send a message on error only when the activity is a message directed to it.
This PR covers:
* Update the error handling part in ConversationBot of TeamsFx SDK
* Update the error handling part in Bot app JS/TS template if TeamsFx SDK is not used.
* Update the SDK version in Bot app JS/TS template if Teams SDK is used.
The updates to .NET version of TeamsFx SDK and bot template will be covered in another separated PR, as it's not related to the 5.6.0 release.
work item: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/27024570/
related issue: https://github.com/OfficeDev/TeamsFx/issues/10865
> fix: bot app error handling in template and SDK

- packages/spec-parser/package.json
- packages/spec-parser/src/constants.ts
- packages/spec-parser/src/interfaces.ts
- packages/spec-parser/src/manifestUpdater.ts
- packages/spec-parser/src/specFilter.ts
- packages/spec-parser/src/specParser.browser.ts
- packages/spec-parser/src/specParser.ts
- packages/spec-parser/src/utils.ts
- packages/spec-parser/test/browser/specParser.browser.test.ts
- packages/spec-parser/test/manifestUpdater.test.ts
- packages/spec-parser/test/specFilter.test.ts
- packages/spec-parser/test/specParser.test.ts
- packages/spec-parser/test/utils.test.ts
Example:
Code sample:
```ts
const testFolder = path.resolve("../", path.dirname(__dirname), "test-material");
const manifest = testFolder + "/manifest.json";
const spec = testFolder + "/petstore.yaml";
const parser = new SpecParser(spec, {
allowMultipleParameters: true,
isCopilot: true,
});
const list = await parser.list();
const validate = await parser.validate();
const apis = list.map((item) => item.api);
const result = await parser.generateForCopilot(manifest, apis, testFolder + "/" + "result.yaml", "ai-plugin.json");
```
OpenAPI spec file:
```yaml
openapi: 3.0.0
info:
title: Phone Service
description: >-
http service to operate phone via http request, such as send message, get
contacts, etc
version: 1.0.2
servers:
- url: https://dcg.microsoft.com
paths: …
```
> perf(spec-parser): update to support type b ai-plugin

- packages/cli/src/commands/models/accountLoginAzure.ts
fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/27055736
Default `--interactive` option for `teamsapp auth login azure` is `true` if user not specified. The examples are updated accordingly.
> fix: default interactive is true for azure login

- packages/fx-core/src/component/driver/teamsApp/createAppPackage.ts
- packages/fx-core/src/component/driver/teamsApp/utils/ManifestUtils.ts
- packages/fx-core/src/component/generator/copilotPlugin/generator.ts
- packages/fx-core/src/question/create.ts
- packages/fx-core/tests/component/driver/teamsApp/createAppPackage.test.ts
- packages/fx-core/tests/component/driver/teamsApp/pluginManifestUtils.test.ts
- packages/fx-core/tests/component/generator/copilotPluginGenerator.test.ts
- packages/fx-core/tests/core/FxCore.test.ts
- packages/manifest/src/ManifestCommonProperties.ts
- packages/manifest/src/index.ts
- packages/manifest/src/manifest.ts
- packages/spec-parser/src/manifestUpdater.ts
- packages/spec-parser/test/manifestUpdater.test.ts
- packages/vscode-extension/src/codeLensProvider.ts
- packages/vscode-extension/test/extension/codeLensProvider.test.ts
- packages/vscode-extension/test/extension/handlers.test.ts
- rename "apiPlugins" to "plugins" as what has been finalized in schema.
> refactor: rename apiPlugin to plugin

- packages/fx-core/src/common/constants.ts
- packages/fx-core/src/common/featureFlags.ts
- packages/fx-core/src/component/coordinator/index.ts
- packages/fx-core/src/component/generator/copilotPlugin/generator.ts
- packages/fx-core/src/component/generator/generator.ts
- packages/fx-core/tests/component/generator/generator.test.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/26963508
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/27130362
Use `placeProjectFileInSolutionDir` to adjust whether users want to scaffold project in the solution root folder. It means the `.csproj` is placed with `.sln` in the same directory.
Use `TEAMSFX_NEW_PROJECT_TYPE` for easy callback. If we want to hide this feature, we can turn it off.
> feat: add placePTInSln and new project type feature flag

- templates/csharp/ai-assistant-bot/AdapterWithErrorHandler.cs.tpl
- templates/csharp/ai-bot/AdapterWithErrorHandler.cs.tpl
- templates/csharp/command-and-response/AdapterWithErrorHandler.cs.tpl
- templates/csharp/default-bot/AdapterWithErrorHandler.cs.tpl
- templates/csharp/notification-http-timer-trigger-isolated/AdapterWithErrorHandler.cs.tpl
- templates/csharp/notification-http-timer-trigger/AdapterWithErrorHandler.cs.tpl
- templates/csharp/notification-http-trigger-isolated/AdapterWithErrorHandler.cs.tpl
- templates/csharp/notification-http-trigger/AdapterWithErrorHandler.cs.tpl
- templates/csharp/notification-timer-trigger-isolated/AdapterWithErrorHandler.cs.tpl
- templates/csharp/notification-timer-trigger/AdapterWithErrorHandler.cs.tpl
- templates/csharp/notification-webapi/AdapterWithErrorHandler.cs.tpl
- templates/csharp/workflow/AdapterWithErrorHandler.cs.tpl
Update .NET bot templates to send a message on error only when the activity is a message directed to it.
related PR: https://github.com/OfficeDev/TeamsFx/pull/10979
related issue: https://github.com/OfficeDev/TeamsFx/issues/10865
work item: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/27024570/
> fix: (.NET) bot app error handling in template

- packages/tests/src/e2e/scaffold/OfficeAddinScaffold.tests.ts
fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/27147616
> fix: temporarily comment e2e scaffold case for office addin

- packages/fx-core/src/component/driver/deploy/spfx/utility/spoClient.ts
[Bug 27213689](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/27213689): SPFx deploy error due to large request body
> fix: spfx post request body limit

- packages/fx-core/src/core/FxCore.ts
- packages/fx-core/tests/core/FxCore.test.ts
fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/27192083
> fix: missing property value when `create env`

- templates/js/custom-copilot-assistant-new/README.md.tpl
- templates/js/custom-copilot-basic/README.md.tpl
- templates/ts/custom-copilot-assistant-assistants-api/package.json.tpl
- templates/ts/custom-copilot-assistant-new/README.md.tpl
- templates/ts/custom-copilot-assistant-new/package.json.tpl
- templates/ts/custom-copilot-basic/README.md.tpl
- templates/ts/custom-copilot-basic/package.json.tpl
Cherry-pick from https://github.com/OfficeDev/TeamsFx/pull/11109
> fix: custom copilot templates

- packages/fx-core/src/component/driver/teamsApp/validateTestCases.ts
As test cases may run several minutes, return the submission result immediately.
The test cases are running, and show progress/pop up for the final result.
> refactor: return result after submission, avoid blocking other lifecycles

- packages/fx-core/src/component/driver/aad/utility/aadManifestHelper.ts
- packages/fx-core/tests/component/driver/aad/aadManifestHelper.test.ts
fix validation error when AAD manifest does not contain accessToken property in optionalClaims
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/27212864
> fix: validation error when AAD manifest does not contain accessToken property

- packages/fx-core/src/common/projectSettingsHelper.ts
- packages/fx-core/tests/common/officeAddInProjectSetting.test.ts
- packages/fx-core/tests/core/other.test.ts
For office metaos add in project, all of the manifest.xml, mainfest.json and teamsapp.yml exist. It should be recognized as TeamsApp project and the TTK treeview should show. 
Bug link: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/27180052%22%20created
> fix: metaos addin should be recognized as teamsapp project

- packages/vscode-extension/src/handlers.ts
- packages/vscode-extension/test/extension/handlers.test.ts
Related bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/27192758
> fix: azure sign out from command palette

- packages/vscode-extension/src/controls/webviewPanel.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/27194270
> fix: update replaced image path

- packages/fx-core/resource/package.nls.json
- packages/fx-core/src/common/featureFlags.ts
- packages/fx-core/src/component/generator/officeAddin/generator.ts
- packages/fx-core/src/question/create.ts
- packages/fx-core/src/question/inputs/CreateProjectInputs.ts
- packages/fx-core/tests/component/generator/officeAddinGenerator.test.ts
- packages/manifest/devPreviewSchema.json
- [PM Spec](https://microsoft.sharepoint.com/:w:/t/OfficePlatform/EQTzlom9CSFGgAOIro3-sDsBTsmVkXxz6IWCUoJVLp6L9w?e=vW0Dla)
- [ADO Link](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/27130363)
-
When isOfficeJSONAddinEnabled(default false) is true: 
This change is to import existing add-in for Office add-in(json).
> feat: [minor]import existing Office Addin[MetaOS]

- .github/scripts/chat-participant-disabled.sh
- .github/workflows/cd.yml
- packages/fx-core/src/common/constants.ts
- packages/fx-core/src/common/featureFlags.ts
- packages/vscode-extension/src/chat/consts.ts
- packages/vscode-extension/src/extension.ts
- packages/vscode-extension/src/utils/commonUtils.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/26624499
Add `TEAMSFX_CHAT_PARTICIPANT` flag and set it to `true` in the code. When releasing `rc/stable`, change it to false for hiding other entries of chat participant.
Set `contributes.chatParticipants` to `[]` to hide chat participant when releasing `rc/stable`.
Use `fx-extension.isChatParticipantEnabled` in `package.json` to control the welcome page content and webview content.
Test in https://github.com/OfficeDev/TeamsFx/actions/runs/8462480742.
> feat: add flag for controlling chat participant and disable it when release rc/beta

- packages/fx-core/src/component/driver/teamsApp/createAppPackage.ts
- packages/fx-core/src/component/driver/teamsApp/utils/utils.ts
- packages/fx-core/tests/component/driver/teamsApp/createAppPackage.test.ts
- packages/fx-core/tests/component/driver/teamsApp/utils.test.ts
- When building zip package, keep the path delimiter consistent with what user defined in manifest.
> fix: use consistent path delimiter when building package

- packages/spec-parser/src/manifestUpdater.ts
- packages/spec-parser/src/specParser.browser.ts
- packages/spec-parser/src/utils.ts
- packages/spec-parser/test/browser/specParser.browser.test.ts
- packages/spec-parser/test/manifestUpdater.test.ts
Fix this: [Bug 27275488](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/27275488): [Ask from TDP] Spec-parser list all parameters rather than just required or the first optional parameter
> perf(spec-parser-tdp): list all params rather than just one

- packages/fx-core/src/component/generator/copilotPlugin/helper.ts
- packages/fx-core/src/core/FxCore.ts
- packages/fx-core/tests/component/generator/copilotPluginGenerator.test.ts
- packages/server/src/serverConnection.ts
- packages/server/tests/serverConnection.test.ts
Format validation error in fx-core rather than server so that server will get a consistent error format.
> refactor: error if listOpenAPISpecOperationsRequest

- templates/js/m365-message-extension/.gitignore
- templates/js/m365-message-extension/.vscode/launch.json
- templates/js/m365-message-extension/.vscode/tasks.json
- templates/js/m365-message-extension/.webappignore
- templates/js/m365-message-extension/env/.env.testtool
- templates/js/m365-message-extension/package.json.tpl
- templates/js/m365-message-extension/teamsapp.testtool.yml
Update search message extension js template to add default test tool launch profile.
For now, the test tool version is alpha version. This allows for testing before test tool beta is released. Before TTK RC release, I will change to beta version.
TODO: other bot based message extension templates, README
Test:
https://github.com/OfficeDev/TeamsFx/assets/9698542/9eab1820-67f8-49a9-a2ed-413bd42cf3d6
Similar changes for bot templates: #10270 
> feat: update search message extension template for test tool

- templates/js/office-xml-addin-excel-cf/README.md
- templates/js/office-xml-addin-excel-manifest-only/manifest.xml
- templates/js/office-xml-addin-powerpoint-manifest-only/manifest.xml
- templates/js/office-xml-addin-word-manifest-only/manifest.xml
- templates/ts/office-xml-addin-excel-cf/README.md
This PR fix the following BUGS:
* [27333350](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/27333350): The validate manifest should works now.
* [27333404](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/27333404): Replace the 404 link with another link in README.
> fix: fix office xml addin related static templates bug

- packages/fx-core/src/common/constants.ts
- packages/fx-core/src/common/featureFlags.ts
- packages/fx-core/src/component/generator/generator.ts
- packages/fx-core/tests/component/generator/generator.test.ts
- templates/js/m365-message-extension/.vscode/launch.json.tpl
Add feature flag to control whether test tool is the default launch profile in ME templates. In preview version enable it by default.
> feat: add feature flag for ME test tool

- packages/vscode-extension/src/chat/commands/create/helper.ts
- packages/vscode-extension/src/chat/prompts.ts
- packages/vscode-extension/test/chat/commands/create/helper.test.ts
1. Prevent token exceeds limitation (3K) when we have more and more samples.
2. Improve system prompt to include a score in response, it helps to sort matched ones and find most related templates/samples.
> feat(chat): split match requests under 3K token limitation

- templates/js/m365-message-extension/README.md.tpl
- templates/ts/m365-message-extension/README.md.tpl
Preview:
To be consistent with previous bot template changes, when test tool is enabled by default, only the instructions about debug in test tool will be displayed (debug in Teams instruction will not be generated).
> feat: update README for search message extension templates

- packages/fx-core/resource/package.nls.json
- packages/fx-core/src/common/deps-checker/constant/message.ts
- packages/fx-core/src/common/deps-checker/util/fileHelper.ts
work item: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/27470834/
Added the symlink path and instructions when the error occurs.
> fix: update error message when symlink exist

- templates/js/message-extension-action/.vscode/launch.json.tpl
- templates/ts/message-extension-action/.vscode/launch.json.tpl
Currently, even if TEAMSFX_ME_TEST_TOOL is enabled, this template won't use test tool as default launch profile.
Fix action ME group name. Other ME templates doesn't have this issue because they are already in this format.
> fix: launch group name for action ME template

- README.md
update privacy link in Readme according Privacy Review feedback.
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/27503595
> fix: update privacy link

- packages/fx-core/src/component/generator/copilotPlugin/helper.ts
[Bug 27569010](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/27569010): No parameter api not work in teams ai generator
> perf: fix teamsai generator api call not work for empty parameters

- packages/fx-core/src/component/generator/copilotPlugin/helper.ts
[Bug 27622836](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/27622836): action.json should contain information of summary
> perf: use summary for action description if it not exist

- packages/fx-core/src/common/m365/launchHelper.ts
- packages/fx-core/tests/common/m365/launchHelper.test.ts
- packages/manifest/src/ManifestCommonProperties.ts
- packages/manifest/src/index.ts
- packages/vscode-extension/src/codeLensProvider.ts
- packages/vscode-extension/test/extension/handlers.test.ts
[Bug 27604780](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/27604780): [Pre-Release]The preview in cli and vscode does not display consistently in Teams browser for Copilot Plugin project
> fix: preview Copilot plugin in CLI

- packages/spec-parser/src/manifestUpdater.ts
- packages/spec-parser/test/manifestUpdater.test.ts
- templates/js/api-plugin-from-scratch/README.md
- templates/js/api-plugin-from-scratch/appPackage/ai-plugin.json.tpl
- templates/ts/api-plugin-from-scratch/README.md
- templates/ts/api-plugin-from-scratch/appPackage/ai-plugin.json.tpl
[Bug 27673808](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/27673808): [VSC]local debug and provison for Copilot Plugin project not work
[Bug 27673792](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/27673792): update readme content for copilot plugin of scratch template
> fix: update manifest based on latest schema and readme update

- packages/spec-parser/src/validators/validator.ts
- packages/spec-parser/test/validator.test.ts
[Bug 27676642](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/27676642): Allow empty response for type b copilot
> perf(spec-parser): allow empty json response for type b copilot

- packages/spec-parser/src/manifestUpdater.ts
- packages/spec-parser/test/manifestUpdater.test.ts
[Bug 27707952](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/27707952): [spec-parser] should not include "format" in plugin manifest
> perf(spec-parser): only keep type b supported property in parameters

- packages/cli/.vscode/launch.json
- packages/fx-core/src/component/coordinator/index.ts
- packages/fx-core/src/component/driver/teamsApp/utils/CopilotGptManifestUtils.ts
- packages/fx-core/src/component/generator/copilotPlugin/generator.ts
- packages/fx-core/src/component/generator/templates/templateNames.ts
- packages/fx-core/src/question/create.ts
- packages/fx-core/tests/component/driver/teamsApp/copilotGptManifest.test.ts
- packages/fx-core/tests/component/generator/copilotPluginGenerator.test.ts
- packages/fx-core/tests/question/create.test.ts
- packages/spec-parser/src/interfaces.ts
- packages/spec-parser/src/manifestUpdater.ts
- packages/spec-parser/src/specParser.browser.ts
- packages/spec-parser/src/specParser.ts
- scaffold basic GPT and GPT with plugin from scratch 
- generate basic GPT + plugin from existing API spec.
> refactor: generate customize gpt and GPT plugin

- packages/spec-parser/src/manifestUpdater.ts
- packages/spec-parser/test/manifestUpdater.test.ts
[Bug 27787556](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/27787556): Don't generate response_semantics when response is empty
> perf(spec-parser): do not generate response_semantics when response is empty

- packages/fx-core/src/component/generator/generatorProvider.ts
- packages/fx-core/src/component/generator/officeAddin/generator.ts
- packages/fx-core/src/component/generator/templates/ssrTabGenerator.ts
- packages/fx-core/src/component/generator/templates/templateGenerator.ts
- packages/fx-core/src/component/generator/templates/templateInfo.ts
- packages/fx-core/src/component/generator/templates/templateNames.ts
- packages/fx-core/tests/component/generator/templateGenerator.test.ts
1. Mapping inputs to template names. Templates onboarding process is simplified to registering new item in the map.
2. Customizing generator for ASP.NET SSR tab templates to keep default template generator simple.
> refactor(generator): mapping user inputs to template names

- packages/fx-core/src/common/samples.ts
Need to bump version because of new image URL support: https://github.com/OfficeDev/TeamsFx/pull/11160
Related: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/27194270
> fix(core): bump sample tag version

- packages/fx-core/src/common/m365/launchHelper.ts
- packages/fx-core/src/core/FxCore.ts
- packages/fx-core/tests/common/m365/launchHelper.test.ts
- templates/common/copilot-plugin-existing-api-api-key/.vscode/launch.json
- templates/common/copilot-plugin-existing-api-api-key/README.md
- templates/common/copilot-plugin-existing-api/.vscode/launch.json
- templates/common/copilot-plugin-existing-api/README.md
- templates/js/api-message-extension-sso/.vscode/launch.json
- templates/js/api-message-extension-sso/README.md
- templates/js/copilot-plugin-from-scratch-api-key/.vscode/launch.json
- templates/js/copilot-plugin-from-scratch-api-key/README.md
- templates/js/copilot-plugin-from-scratch/.vscode/launch.json
- templates/js/copilot-plugin-from-scratch/README.md
- templates/ts/api-message-extension-sso/.vscode/launch.json
- templates/ts/api-message-extension-sso/README.md
- templates/ts/copilot-plugin-from-scratch-api-key/.vscode/launch.json
- templates/ts/copilot-plugin-from-scratch-api-key/README.md
- templates/ts/copilot-plugin-from-scratch/.vscode/launch.json
- templates/ts/copilot-plugin-from-scratch/README.md
[Bug 27777602](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/27777602): Debugging API ME shouldn't go to the home page of Teams
> fix: api me launch url

- templates/csharp/api-message-extension-sso/.{{NewProjectTypeName}}/launchSettings.json.tpl
- templates/csharp/api-message-extension-sso/GettingStarted.md
- templates/csharp/api-message-extension-sso/Properties/launchSettings.json.tpl
- templates/csharp/api-message-extension-sso/teamsapp.local.yml.tpl
- templates/csharp/copilot-plugin-existing-api-api-key/GettingStarted.md
- templates/csharp/copilot-plugin-existing-api/GettingStarted.md
- templates/csharp/copilot-plugin-from-scratch-api-key/.{{NewProjectTypeName}}/launchSettings.json.tpl
- templates/csharp/copilot-plugin-from-scratch-api-key/GettingStarted.md
- templates/csharp/copilot-plugin-from-scratch-api-key/Properties/launchSettings.json.tpl
- templates/csharp/copilot-plugin-from-scratch-api-key/teamsapp.local.yml.tpl
- templates/csharp/copilot-plugin-from-scratch/.{{NewProjectTypeName}}/launchSettings.json.tpl
- templates/csharp/copilot-plugin-from-scratch/GettingStarted.md
- templates/csharp/copilot-plugin-from-scratch/Properties/launchSettings.json.tpl
- templates/csharp/copilot-plugin-from-scratch/teamsapp.local.yml.tpl
[Bug 27777602](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/27777602): Debugging API ME shouldn't go to the home page of Teams
> fix: API ME Launch url in VS

- .azure-pipelines/apiscan.yml
https://dev.azure.com/mseng/VSIoT/_build/results?buildId=28026916&view=results
> ci: enable api scan pipeline

- packages/cli/src/prompts/utils.ts
- packages/cli/tests/unit/prompts/customizedListPrompt.tests.ts
[Bug 27955155](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/27955155): [CLI] Scroll down will error when single select an item of large index from a list
choices.length could be smaller than page size, leading to pageStarter <0.
After fix:
> fix: cli cannot scroll down if multiple selections

- packages/fx-core/src/common/m365/packageService.ts
- packages/fx-core/src/common/projectTypeChecker.ts
- packages/fx-core/src/component/driver/teamsApp/createAppPackage.ts
- packages/fx-core/src/component/driver/teamsApp/utils/CopilotGptManifestUtils.ts
- packages/fx-core/src/component/driver/teamsApp/utils/ManifestUtils.ts
- packages/fx-core/src/core/FxCore.ts
- packages/fx-core/src/question/other.ts
- packages/fx-core/tests/common/projectTypeChecker.test.ts
- packages/fx-core/tests/component/driver/teamsApp/copilotGptManifest.test.ts
- packages/fx-core/tests/component/driver/teamsApp/createAppPackage.test.ts
- packages/fx-core/tests/component/driver/teamsApp/pluginManifestUtils.test.ts
- packages/fx-core/tests/component/generator/copilotPluginGenerator.test.ts
- packages/fx-core/tests/core/FxCore.test.ts
- packages/manifest/src/declarativeCopilotManifest.ts
- packages/manifest/src/index.ts
- packages/manifest/src/manifest.ts
- packages/spec-parser/src/manifestUpdater.ts
- packages/spec-parser/test/manifestUpdater.test.ts
- packages/vscode-extension/test/extension/codeLensProvider.test.ts
- packages/vscode-extension/test/extension/handlers.test.ts
[Bug 27976898](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/27976898): Restructuring and renaming for GPT and plugin nodes in manifest
> fix: manifest update for copilot extensions (non-template part)

- templates/python/custom-copilot-assistant-new/.vscode/launch.json
- templates/python/custom-copilot-assistant-new/teamsapp.local.yml.tpl
- templates/python/custom-copilot-assistant-new/teamsapp.yml.tpl
- templates/python/custom-copilot-basic/.vscode/launch.json
- templates/python/custom-copilot-basic/teamsapp.local.yml.tpl
- templates/python/custom-copilot-basic/teamsapp.yml.tpl
- templates/python/custom-copilot-rag-azure-ai-search/.vscode/launch.json
- templates/python/custom-copilot-rag-azure-ai-search/teamsapp.local.yml.tpl
- templates/python/custom-copilot-rag-azure-ai-search/teamsapp.yml.tpl
- templates/python/custom-copilot-rag-customize/.vscode/launch.json
- templates/python/custom-copilot-rag-customize/teamsapp.local.yml.tpl
- templates/python/custom-copilot-rag-customize/teamsapp.yml.tpl
workitem: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/27894013
E2E TEST: N/A
PR: https://github.com/OfficeDev/TeamsFx/pull/11554 is merged into main branch, while this fix needs to be merged into release branch. Need your review again.
> fix: hot fix for Python templates to remove Test Tool from the default debug choice

- packages/spec-parser/src/specParser.ts
[Bug 27996070](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/27996070): Inconsistent space when writing manifest
> fix: space in spec-parser

- templates/csharp/api-message-extension-sso/.{{NewProjectTypeName}}/launchSettings.json.tpl
- templates/csharp/api-message-extension-sso/GettingStarted.md
- templates/csharp/api-message-extension-sso/Properties/launchSettings.json.tpl
- templates/csharp/api-message-extension-sso/teamsapp.local.yml.tpl
- templates/js/api-message-extension-sso/.vscode/launch.json
- templates/js/api-message-extension-sso/README.md
- templates/ts/copilot-plugin-from-scratch-api-key/.vscode/launch.json
- templates/ts/copilot-plugin-from-scratch-api-key/README.md
[[VSC]local debug and remote debug for API Message Extension with Microsoft Entra auth get something went wrong ](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/27997549)
Roll back the change from [this PR](https://github.com/OfficeDev/TeamsFx/pull/11461), once the TDP is ready, we'll update the launch url again.
> fix: roll back the launch url in API ME SSO template

- packages/spec-parser/src/manifestUpdater.ts
- packages/spec-parser/src/specParser.ts
- packages/spec-parser/test/manifestUpdater.test.ts
- packages/spec-parser/test/specParser.test.ts
[Bug 28037301](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/28037301): Gracefully handle when AC creation fails
> perf(type-b): warning instead error when generate AC failed

- templates/common/api-plugin-existing-api/appPackage/manifest.json.tpl
- templates/common/copilot-gpt-basic/appPackage/manifest.json.tpl
- templates/common/copilot-plugin-existing-api-api-key/appPackage/manifest.json.tpl
- templates/common/copilot-plugin-existing-api/appPackage/manifest.json.tpl
- templates/common/copilot-plugin-from-oai-plugin/appPackage/manifest.json.tpl
- templates/csharp/api-message-extension-sso/appPackage/manifest.json.tpl
- templates/csharp/api-plugin-existing-api/appPackage/manifest.json.tpl
- templates/csharp/api-plugin-from-scratch/appPackage/manifest.json.tpl
- templates/csharp/copilot-plugin-existing-api-api-key/appPackage/manifest.json.tpl
- templates/csharp/copilot-plugin-existing-api/appPackage/manifest.json.tpl
- templates/csharp/copilot-plugin-from-oai-plugin/appPackage/manifest.json.tpl
- templates/csharp/copilot-plugin-from-scratch-api-key/appPackage/manifest.json.tpl
- templates/csharp/copilot-plugin-from-scratch/appPackage/manifest.json.tpl
- templates/csharp/message-extension-copilot/appPackage/manifest.json.tpl
- templates/js/api-message-extension-sso/appPackage/manifest.json.tpl
- templates/js/api-plugin-from-scratch/appPackage/manifest.json.tpl
- templates/js/copilot-gpt-from-scratch-plugin/appPackage/manifest.json.tpl
- templates/js/copilot-plugin-from-scratch-api-key/appPackage/manifest.json.tpl
- templates/js/copilot-plugin-from-scratch/appPackage/manifest.json.tpl
- templates/js/message-extension-copilot/appPackage/manifest.json.tpl
- templates/ts/api-message-extension-sso/appPackage/manifest.json.tpl
- templates/ts/api-plugin-from-scratch/appPackage/manifest.json.tpl
- templates/ts/copilot-gpt-from-scratch-plugin/appPackage/manifest.json.tpl
- templates/ts/copilot-plugin-from-scratch-api-key/appPackage/manifest.json.tpl
- templates/ts/copilot-plugin-from-scratch/appPackage/manifest.json.tpl
- templates/ts/message-extension-copilot/appPackage/manifest.json.tpl
[Bug 28026372](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/28026372): PackageName property in manifest is deprecated
> fix: remove packageName

- packages/fx-core/src/core/FxCore.ts
- packages/fx-core/tests/core/FxCore.test.ts
[Bug 27986092](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/27986092): Generate Copilot Plugin manifest & OpenAPI desc files names uniquely
> fix: add suffix for files generated when add plugin

- packages/vscode-extension/src/chat/handlers.ts
- packages/vscode-extension/test/chat/handlers.test.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/28055577
> fix: show error when @teams with empty prompt

- packages/spec-parser/src/specParser.ts
- packages/spec-parser/test/specParser.test.ts
[Bug 28107119](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/28107119): [AUTOBUG] ui - remotedebug-msg-openapi-win-only failed - 25270433
> perf(spec-parser): fixed issue where generated SME commands include non-selected APIs

- packages/fx-core/src/component/driver/teamsApp/utils/CopilotGptManifestUtils.ts
- packages/fx-core/tests/component/driver/teamsApp/copilotGptManifest.test.ts
[Bug 28045219](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/28045219): Action validation error details are not print if Declarative Copilot has action only
> fix: action validation result should be printed out

- packages/fx-core/src/component/generator/copilotPlugin/helper.ts
- packages/fx-core/src/core/FxCore.ts
- packages/fx-core/tests/core/FxCore.test.ts
- packages/spec-parser/src/manifestUpdater.ts
- packages/spec-parser/test/manifestUpdater.test.ts
[Bug 28107119](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/28107119): [AUTOBUG] ui - remotedebug-msg-openapi-win-only failed - 25270433
> perf(spec-parser): fix issue that OperationOnlyContainsOptionalParam doesn't display

- packages/fx-core/resource/package.nls.json
fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/28085285
> fix: cli naming in string

- packages/fx-core/src/component/generator/generatorAction.ts
- packages/fx-core/src/component/generator/utils.ts
- packages/fx-core/tests/component/generator/generator.test.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/28066566
The expected behavior is:
1. If `TEAMSFX_TEMPLATE_PRERELEASE` has value, typically is `rc`, TTK downloads prerelease templates from GitHub releases.
2. Else if, `useLocalTemplate` config is false, TTK gets latest templates version who matches the version pattern in the config file, only download templates from GitHub releases when its version is greater than local template version.
3. Else, TTK uses the templates snapshot in TTK for scaffolding.
> fix: generator download rc templates for test

- .github/workflows/vscode-marketplace.yml
https://github.com/ipfs/js-ipfs/issues/4019
according to this doc: https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2204-Readme.md
the node.js version is 18 and npm is 10
> ci: update publish ci with node 18

- packages/fx-core/src/component/generator/templates/templateNames.ts
- packages/fx-core/tests/component/coordinator/coordinator.create.test.ts
feat: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/27822940
> feat: add scaffolding logic for copliot plugin template

- packages/vscode-extension/src/extension.ts
- packages/vscode-extension/src/handlers.ts
- packages/vscode-extension/src/handlers/activate.ts
- packages/vscode-extension/test/extension/handlers.test.ts
- packages/vscode-extension/test/extension/treeview/account/copilotNode.test.ts
- packages/vscode-extension/test/handlers/activate.test.ts
- packages/vscode-extension/test/mocks/mockCore.ts
- packages/vscode-extension/test/mocks/vscode-mock.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/28240424
> refactor: split activate() from handlers

- packages/spec-parser/src/specFilter.ts
- packages/spec-parser/src/specOptimizer.ts
- packages/spec-parser/test/specOptimizer.test.ts
Original file [Github API OpenAPI spec file](https://raw.githubusercontent.com/github/rest-api-description/main/descriptions/api.github.com/api.github.com.yaml): 7.77M
Testing select 7 search API with/without optimization:
without optimization:  7.09M 
[openapi.yaml.txt](https://github.com/user-attachments/files/15922005/openapi.yaml.txt)
with optimization:  126K
[openapi.yaml.txt](https://github.com/user-attachments/files/15922032/openapi.yaml.txt)
> perf(spec-parser): remove unused properties when filtering

- packages/vscode-extension/src/officeChat/commands/create/officeSamples.ts
- packages/vscode-extension/src/officeChat/common/planner.ts
- packages/vscode-extension/src/officeChat/common/skills/codeGenerator.ts
- packages/vscode-extension/src/officeChat/common/skills/printer.ts
- packages/vscode-extension/test/officeChat/commands/create/officeSamples.test.ts
- packages/vscode-extension/test/officeChat/common/skills/codeGenerator.test.ts
- packages/vscode-extension/test/officeChat/common/skills/printer.test.ts
- packages/vscode-extension/test/officeChat/utils.test.ts
This PR is to enable Office agent to output in different skills to improve the user experience
> refactor: add streaming output to office agent

- packages/vscode-extension/src/utils/releaseNote.ts
- packages/vscode-extension/test/utils/releaseNote.test.ts
Related bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/28574492
> fix: not show the changelog prompt on a fresh install

- packages/api/src/qm/ui.ts
- packages/fx-core/src/common/constants.ts
- packages/fx-core/src/common/featureFlags.ts
- packages/fx-core/src/component/driver/teamsApp/validateAppPackage.ts
- packages/vscode-extension/src/extension.ts
- packages/vscode-extension/src/globalVariables.ts
- packages/vscode-extension/src/qm/vsc_ui.ts
- packages/vscode-extension/test/mocks/vscode-mock.ts
- packages/vscode-extension/test/qm/vsc_ui.test.ts
- add API to show diagnostics in editor. We are going to show validation errors as diagnostics later.
[Feature 28307640](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/28307640): [PartnerFeatureAsk] Custom validation rules display in the editor for apps and plugins
> feat: show diagnostics

- packages/fx-core/src/component/generator/apiSpec/helper.ts
Discussed with Junjie, add detailed error message when spec is not valid
> perf: add spec-not-valid-details in validate-api-spec telemetry

- packages/fx-core/tests/core/middleware/testAssets/v3Migration/happyPath/.fx/configs/config.dev.json
- packages/fx-core/tests/core/middleware/testAssets/v3Migration/happyPath/.fx/configs/config.local.json
remove https://aka.ms/teamsfx-env-config since this link is invalid
> test: remove invalid link from migration assets

- packages/fx-core/src/question/create.ts
Add icon. This item will only be used in VSC.
[Bug 28665783](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/28665783): Missing icon for "Enter OpenAPI Description Document"
> fix: add icon

- templates/python/custom-copilot-assistant-assistants-api/.gitignore
- templates/python/custom-copilot-assistant-assistants-api/.webappignore
- templates/python/custom-copilot-assistant-assistants-api/README.md
- templates/python/custom-copilot-assistant-new/.gitignore
- templates/python/custom-copilot-assistant-new/.webappignore
- templates/python/custom-copilot-assistant-new/README.md.tpl
- templates/python/custom-copilot-basic/.gitignore
- templates/python/custom-copilot-basic/.webappignore
- templates/python/custom-copilot-basic/README.md.tpl
- templates/python/custom-copilot-rag-azure-ai-search/.gitignore
- templates/python/custom-copilot-rag-azure-ai-search/.webappignore
- templates/python/custom-copilot-rag-azure-ai-search/README.md.tpl
- templates/python/custom-copilot-rag-azure-ai-search/src/indexers/delete.py
- templates/python/custom-copilot-rag-azure-ai-search/src/indexers/setup.py.tpl
- templates/python/custom-copilot-rag-customize/.gitignore
- templates/python/custom-copilot-rag-customize/.webappignore
- templates/python/custom-copilot-rag-customize/README.md.tpl
workitem: 
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/28695369/
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/28695292/
remove bad .env loading from testtool when the TTK is pre-release
remove bad testtool relative files
> fix: fix bad loading from testtool and remove bad files

- templates/python/custom-copilot-assistant-assistants-api/.vscode/launch.json
- templates/python/custom-copilot-assistant-assistants-api/.vscode/tasks.json
- templates/python/custom-copilot-assistant-new/.vscode/launch.json
- templates/python/custom-copilot-assistant-new/.vscode/tasks.json
- templates/python/custom-copilot-basic/.vscode/launch.json
- templates/python/custom-copilot-basic/.vscode/tasks.json
- templates/python/custom-copilot-rag-azure-ai-search/.vscode/launch.json
- templates/python/custom-copilot-rag-azure-ai-search/.vscode/tasks.json
- templates/python/custom-copilot-rag-customize/.vscode/launch.json
- templates/python/custom-copilot-rag-customize/.vscode/tasks.json
workitem: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/28711326
> feat: add desktop launch option for python custom-copilot templates

- packages/fx-core/src/question/constants.ts
- packages/fx-core/src/question/create.ts
- packages/vscode-extension/test/officeChat/utils.test.ts
E2E: https://github.com/OfficeDev/teams-toolkit/actions/runs/9969559504
- Fix issue that user cannot create project in VS if TEAMSFX_CLI_DOTNET flag is enabled
- [Bug 28682942](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/28682942): [Cli]Display all project types when creating projects in . Net core
> fix: wrong capabilities if .NET flag is enabled

- templates/csharp/api-plugin-existing-api/{{ProjectName}}.csproj.tpl
- templates/csharp/api-plugin-from-scratch-bearer/.{{NewProjectTypeName}}/{{NewProjectTypeName}}.{{NewProjectTypeExt}}.tpl
- templates/csharp/api-plugin-from-scratch-bearer/{{ProjectName}}.csproj.tpl
- templates/csharp/api-plugin-from-scratch-oauth/.{{NewProjectTypeName}}/{{NewProjectTypeName}}.{{NewProjectTypeExt}}.tpl
- templates/csharp/api-plugin-from-scratch-oauth/{{ProjectName}}.csproj.tpl
- templates/csharp/api-plugin-from-scratch/.{{NewProjectTypeName}}/{{NewProjectTypeName}}.{{NewProjectTypeExt}}.tpl
- templates/csharp/api-plugin-from-scratch/{{ProjectName}}.csproj.tpl
- templates/csharp/copilot-gpt-basic/{{ProjectName}}.csproj.tpl
- templates/csharp/copilot-gpt-from-scratch-plugin/.{{NewProjectTypeName}}/{{NewProjectTypeName}}.{{NewProjectTypeExt}}.tpl
- templates/csharp/copilot-gpt-from-scratch-plugin/{{ProjectName}}.csproj.tpl
- Official called as API plugin in doc rather than Copilot plugin
> refactor: csharp templates with api plugin capability

- templates/csharp/default-bot/appPackage/manifest.json.tpl
- templates/csharp/link-unfurling/appPackage/manifest.json.tpl
- templates/js/default-bot/appPackage/manifest.json.tpl
- templates/js/link-unfurling/appPackage/manifest.json.tpl
- templates/ts/default-bot/appPackage/manifest.json.tpl
- templates/ts/link-unfurling/appPackage/manifest.json.tpl
Upgrade basic bot template (js ts csharp version) and message extension link unfurling template (js ts csharp verison)
You must list at least one valid bot command in the items.commands.title section of the app manifest and add a suitable description that gives clarity to the user on the bot command and its usage. Bot commands listed in the commandLists section of the app manifest surface as prepopulated commands in the bot command menu and provide a way forward for the new user to interact with the bot. 
Search based message extensions must provide text that helps the users to search effectively.
> fix: upgrade basic bot and link base on store policy

- packages/fx-core/src/common/globalState.ts
- packages/fx-core/src/core/middleware/concurrentLocker.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/28823899
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/28823901
> fix: change hash algorithm

- templates/csharp/command-and-response/Commands/GenericCommandHandler.cs.tpl
- templates/csharp/command-and-response/Program.cs.tpl
- templates/csharp/command-and-response/TeamsBot.cs.tpl
- templates/js/command-and-response/src/genericCommandHandler.js
- templates/js/command-and-response/src/internal/initialize.js
- templates/js/command-and-response/src/teamsBot.js
- templates/ts/command-and-response/src/genericCommandHandler.ts
- templates/ts/command-and-response/src/internal/initialize.ts
- templates/ts/command-and-response/src/teamsBot.ts
Upgrade command bot template (js ts csharp version)
All commands that your bot supports must work correctly, including generic commands such as Hi, Hello, and Help. [Mandatory Fix]
Bot commands mustn't lead a user to a dead end, the commands must always provide a way forward. [Mandatory Fix]
Bots must always provide a valid response to a user input even if the input is irrelevant or improper. [Mandatory Fix]
Bots must provide a valid response to invalid user commands. Bots mustn't dead-end the user or display an error if a user sends an invalid bot command. [Mandatory Fix]
Welcome message must auto trigger on …
> fix: upgrade command bot template based on Teams store policy

- templates/csharp/command-and-response/Commands/GenericCommandHandler.cs.tpl
- templates/csharp/workflow/Commands/GenericCommandHandler.cs.tpl
- templates/csharp/workflow/Program.cs.tpl
- templates/csharp/workflow/TeamsBot.cs.tpl
- templates/js/workflow/src/commands/genericCommandHandler.js
- templates/js/workflow/src/internal/initialize.js
- templates/js/workflow/src/teamsBot.js
- templates/ts/workflow/src/commands/genericCommandHandler.ts
- templates/ts/workflow/src/internal/initialize.ts
- templates/ts/workflow/src/teamsBot.ts
Upgrade workflow bot template (js ts csharp version)
All commands that your bot supports must work correctly, including generic commands such as Hi, Hello, and Help. [Mandatory Fix]
Bot commands mustn't lead a user to a dead end, the commands must always provide a way forward. [Mandatory Fix]
Bots must always provide a valid response to a user input even if the input is irrelevant or improper. [Mandatory Fix]
Bots must provide a valid response to invalid user commands. Bots mustn't dead-end the user or display an error if a user sends an invalid bot command. [Mandatory Fix]
Welcome message must auto trigger …
> fix: upgrade workflow bot template based on Teams store policy

- templates/csharp/notification-http-timer-trigger-isolated/TeamsBot.cs.tpl
- templates/csharp/notification-http-timer-trigger/TeamsBot.cs.tpl
- templates/csharp/notification-http-trigger-isolated/TeamsBot.cs.tpl
- templates/csharp/notification-http-trigger/TeamsBot.cs.tpl
- templates/csharp/notification-timer-trigger-isolated/TeamsBot.cs.tpl
- templates/csharp/notification-timer-trigger/TeamsBot.cs.tpl
- templates/csharp/notification-webapi/TeamsBot.cs.tpl
- templates/js/notification-http-timer-trigger/src/teamsBot.js
- templates/js/notification-http-trigger/src/teamsBot.js
- templates/js/notification-restify/src/teamsBot.js
- templates/js/notification-timer-trigger/src/teamsBot.js
- templates/ts/notification-http-timer-trigger/src/teamsBot.ts
- templates/ts/notification-http-trigger/src/teamsBot.ts
- templates/ts/notification-restify/src/teamsBot.ts
- templates/ts/notification-timer-trigger/src/teamsBot.ts
Upgrade notification bot template (js ts csharp version)
Notification only bots must send a welcome message that clarifies that the bot is a notification only bot and users won't be able to interact with the bot. [Mandatory Fix]
> fix: upgrade notification bot template based on Teams store policy

- packages/cli/src/commands/models/add.ts
- packages/cli/src/commands/models/create.ts
- packages/fx-core/src/common/featureFlags.ts
- packages/fx-core/src/index.ts
- packages/fx-core/src/question/constants.ts
- packages/fx-core/src/question/create.ts
- packages/tests/src/e2e/scaffold/CopilotPluginFromExistingApi.tests.ts
- packages/tests/src/e2e/scaffold/CopilotPluginFromScratch.tests.ts
- packages/vscode-extension/package.json
- packages/vscode-extension/src/config.ts
- packages/vscode-extension/src/constants.ts
- schemas/pluginSchema.json
E2E: https://github.com/OfficeDev/teams-toolkit/actions/runs/10211006649
- Rename the feature flag name to "DEVELOP_COPILOT_EXTENSION". For backward combability, keep the old envs.
- Did not change the config key, since otherwise user who has already enabled the setting in VSC need to re-enable the feature again.
- Feature flags will be removed once the feature is in public preview
> refactor: rename feature flag name

- packages/fx-core/src/component/generator/spfx/depsChecker/generatorChecker.ts
- packages/fx-core/src/component/generator/spfx/depsChecker/yoChecker.ts
- packages/fx-core/src/component/generator/spfx/spfxGenerator.ts
- packages/fx-core/src/component/generator/spfx/utils/utils.ts
- packages/fx-core/tests/component/generator/spfxGenerator.test.ts
[Bug 28940400](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/28940400): create SPFx project failed - test case 11042969
Fix issue https://github.com/OfficeDev/teams-toolkit/issues/12143
> fix: spfx scaffolding

- packages/vscode-extension/src/handlers/controlHandlers.ts
- packages/vscode-extension/test/handlers/controlHandlers.test.ts
Related bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/28855389
> fix(vsc): show build intelligent getting started page for copilot apps

- packages/cli/src/userInteraction.ts
- packages/cli/tests/unit/ui.tests.ts
[Bug 29015679](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/29015679): CLI UI missing "preview" tag
> fix: cli description

- packages/vscode-extension/src/controls/sampleGallery/offlinePage.tsx
- packages/vscode-extension/src/controls/sampleGallery/sampleCard.tsx
Related bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/29034975
Effect:
> fix(vsc): svg not shown in react app

- packages/vscode-extension/src/handlers/autoOpenProjectHandler.ts
- packages/vscode-extension/test/handlers/autoOpenProjectHandler.test.ts
The walkthrough will remain open so it's not necessary to open it again.
Related bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/29050508
> fix(vsc): avoid opening walkthrough again

- templates/common/api-plugin-existing-api/.vscode/launch.json.tpl
- templates/csharp/api-plugin-from-scratch-bearer/.{{NewProjectTypeName}}/launchSettings.json.tpl
- templates/csharp/api-plugin-from-scratch-bearer/Properties/launchSettings.json.tpl
- templates/csharp/api-plugin-from-scratch-bearer/teamsapp.local.yml.tpl
- templates/csharp/api-plugin-from-scratch-oauth/.{{NewProjectTypeName}}/launchSettings.json.tpl
- templates/csharp/api-plugin-from-scratch-oauth/Properties/launchSettings.json.tpl
- templates/csharp/api-plugin-from-scratch-oauth/teamsapp.local.yml.tpl
- templates/csharp/api-plugin-from-scratch/.{{NewProjectTypeName}}/launchSettings.json.tpl
- templates/csharp/api-plugin-from-scratch/Properties/launchSettings.json.tpl
- templates/csharp/api-plugin-from-scratch/teamsapp.local.yml.tpl
- templates/js/api-plugin-from-scratch-bearer/.vscode/launch.json.tpl
- templates/js/api-plugin-from-scratch-oauth/.vscode/launch.json.tpl
- templates/js/api-plugin-from-scratch/.vscode/launch.json.tpl
- templates/ts/api-plugin-from-scratch-bearer/.vscode/launch.json.tpl
- templates/ts/api-plugin-from-scratch-oauth/.vscode/launch.json.tpl
- templates/ts/api-plugin-from-scratch/.vscode/launch.json.tpl
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/29118124
Updated the launch profile for API Plugin templates, added office.com to the launch profile, and set it as the default.|
> fix: the launch profile for API Plugin templates

- .cursorignore
- packages/fx-core/src/component/generator/copilotExtension/generator.ts
- packages/fx-core/src/question/create.ts
- packages/fx-core/tests/component/generator/copilotExtensionGenerator.test.ts
- packages/fx-core/tests/question/create.test.ts
- templates/csharp/api-plugin-from-scratch-oauth/aad.manifest.json.tpl
- templates/csharp/api-plugin-from-scratch-oauth/appPackage/ai-plugin.dev.json.tpl
- templates/csharp/api-plugin-from-scratch-oauth/appPackage/apiSpecificationFile/repair.dev.yml.tpl
- templates/csharp/api-plugin-from-scratch-oauth/infra/azure.bicep.tpl
- templates/csharp/api-plugin-from-scratch-oauth/infra/azure.parameters.json.tpl
- templates/csharp/api-plugin-from-scratch-oauth/teamsapp.yml.tpl
- templates/js/api-plugin-from-scratch-oauth/README.md.tpl
- templates/js/api-plugin-from-scratch-oauth/aad.manifest.json.tpl
- templates/js/api-plugin-from-scratch-oauth/appPackage/ai-plugin.dev.json.tpl
- templates/js/api-plugin-from-scratch-oauth/appPackage/apiSpecificationFile/repair.dev.yml.tpl
- templates/js/api-plugin-from-scratch-oauth/infra/azure.bicep.tpl
- templates/js/api-plugin-from-scratch-oauth/infra/azure.parameters.json.tpl
- templates/js/api-plugin-from-scratch-oauth/teamsapp.yml.tpl
- templates/ts/api-plugin-from-scratch-oauth/README.md.tpl
- templates/ts/api-plugin-from-scratch-oauth/aad.manifest.json.tpl
- templates/ts/api-plugin-from-scratch-oauth/appPackage/ai-plugin.dev.json.tpl
- templates/ts/api-plugin-from-scratch-oauth/appPackage/apiSpecificationFile/repair.dev.yml.tpl
- templates/ts/api-plugin-from-scratch-oauth/infra/azure.bicep.tpl
- templates/ts/api-plugin-from-scratch-oauth/infra/azure.parameters.json.tpl
- templates/ts/api-plugin-from-scratch-oauth/teamsapp.yml.tpl
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/29077441
- Add a new `Microsoft Entra` authentication option when scaffolding an API Plugin project.
- Since the AAD template is similar to the OAuth one, I would reuse the the `api-plugin-from-scratch-oauth` template folder.
- Based on the OAuth template, add some placeholders to distinguish the different configurations of OAuth and AAD.
> feat: support AAD for API Plugin from scratch templates

- packages/fx-core/src/common/featureFlags.ts
- packages/fx-core/src/component/driver/teamsApp/utils/ManifestUtils.ts
- packages/fx-core/src/component/generator/apiSpec/generator.ts
- packages/fx-core/src/component/generator/apiSpec/helper.ts
- packages/fx-core/src/component/utils/fileOperation.ts
- packages/fx-core/src/core/FxCore.ts
- packages/fx-core/tests/component/generator/apiSpecGenerator.test.ts
- packages/fx-core/tests/core/FxCore.test.ts
E2E: https://github.com/OfficeDev/teams-toolkit/actions/runs/10507081159
Moved some common parts of generating from api spec into a new common function so that the behavior and telemetry will be consistent whenever need to generate from an OpenAPI spec.
Also include a small change to enable FILE feature flag in this PR.
> refactor: generate from api spec

- templates/csharp/command-and-response/{{ProjectName}}.csproj.tpl
- templates/csharp/default-bot/{{ProjectName}}.csproj.tpl
- templates/csharp/link-unfurling/{{ProjectName}}.csproj.tpl
- templates/csharp/message-extension-action/{{ProjectName}}.csproj.tpl
- templates/csharp/message-extension-copilot/{{ProjectName}}.csproj.tpl
- templates/csharp/message-extension-search/{{ProjectName}}.csproj.tpl
- templates/csharp/message-extension/{{ProjectName}}.csproj.tpl
- templates/csharp/non-sso-tab-ssr/{{ProjectName}}.csproj.tpl
- templates/csharp/non-sso-tab/{{ProjectName}}.csproj.tpl
- templates/csharp/notification-http-timer-trigger-isolated/{{ProjectName}}.csproj.tpl
- templates/csharp/notification-http-timer-trigger/{{ProjectName}}.csproj.tpl
- templates/csharp/notification-http-trigger-isolated/{{ProjectName}}.csproj.tpl
- templates/csharp/notification-http-trigger/{{ProjectName}}.csproj.tpl
- templates/csharp/notification-timer-trigger-isolated/{{ProjectName}}.csproj.tpl
- templates/csharp/notification-timer-trigger/{{ProjectName}}.csproj.tpl
- templates/csharp/notification-webapi/{{ProjectName}}.csproj.tpl
- templates/csharp/sso-tab-ssr/{{ProjectName}}.csproj.tpl
- templates/csharp/sso-tab/{{ProjectName}}.csproj.tpl
- templates/csharp/workflow/{{ProjectName}}.csproj.tpl
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/29181693
Some templates need to upgrade the NuGet packages to avoid vulnerabilities:
1. https://github.com/advisories/GHSA-3fx3-85r4-8j3w
2. https://github.com/advisories/GHSA-59j7-ghrg-fj52
3. https://github.com/advisories/GHSA-hh2w-p6rv-4g7w
It is worth mentioning that different NET version (env) will install different versions of NuGet packages.
Adding new packages to solve is because `Microsoft.TeamsFx` or some packages use some vulnerable dependencies. Newest versions cannot solve vulnerabilities.
> fix: vulnerabilities of csharp templates

- .azure-pipelines/localization.yml
Success run: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=10123018&view=results
1. Migrate pipeline to 1ES to fix security alert
2. Migrate to persistCredential(use system.accessToken) instead of PAT to fix auth broken
I'll disable the legacy pipeline https://devdiv.visualstudio.com/DevDiv/_build?definitionId=18482 for now and delete after the PR merged
> ci: update localization pipeline to use persistCredential instead of PAT

- packages/api/src/types.ts
- packages/cli/src/commands/common.ts
- packages/cli/src/commands/models/teamsapp/package.ts
- packages/cli/src/commands/models/teamsapp/publish.ts
- packages/cli/src/commands/models/teamsapp/update.ts
- packages/cli/src/commands/models/teamsapp/validate.ts
- packages/fx-core/resource/yaml-schema/v1.7/yaml.schema.json
- packages/fx-core/src/component/configManager/validator.ts
- packages/fx-core/src/component/driver/teamsApp/createAppPackage.ts
- packages/fx-core/src/component/driver/teamsApp/interfaces/CreateAppPackageArgs.ts
- packages/fx-core/src/component/driver/teamsApp/teamsappMgr.ts
- packages/fx-core/src/core/FxCore.ts
- packages/fx-core/src/question/constants.ts
- packages/fx-core/tests/component/driver/teamsApp/createAppPackage.test.ts
- packages/server/src/serverConnection.ts
- packages/vscode-extension/.vscode/launch.json
E2E https://github.com/OfficeDev/teams-toolkit/actions/runs/10634799412
[Feature 29038072](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/29038072): [PartnerFeatureAsk] I noticed that when I use TTK to provision a declarative copilot I only see - ETA 2024-08-30
- Upgrade schema version to 1.7 by replacing "outputJsonPath"with "outputFolder" so that all resolved manifests will be put in the folder when zipping appPackage.
- Non-liftcycle command. Use the new parameter "outputFolder"
TODO: upgrade templates
> feat: zip app pacakge outputFolder

- packages/fx-core/src/component/driver/apiKey/utility/utility.ts
- packages/fx-core/src/component/driver/oauth/utility/utility.ts
- packages/fx-core/tests/component/driver/apiKey/create.test.ts
- packages/fx-core/tests/component/driver/oauth/create.test.ts
bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_sprints/taskboard/AuthAndData/Microsoft%20Teams%20Extensibility/Dilithium/CY24Q3/2Wk/2Wk11%20(Aug%2025%20-%20Sep%2007)?workitem=29102467
> fix: skip spec validation for apikey and oauth driver

- packages/cli/src/userInteraction.ts
- packages/fx-core/src/component/utils/envFunctionUtils.ts
- packages/fx-core/src/core/FxCore.ts
- packages/vscode-extension/src/telemetry/vscodeTelemetryReporter.ts
- packages/vscode-extension/test/extTelemetry/vscodeTelemetryReporter.test.ts
- several improvement and telemetry fix for add plugin
> refactor: add plugin improvement

- packages/vscode-extension/src/controls/webviewPanel.ts
Related bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/29288541
> fix(vsc): repetitive images in sample detail page

- packages/fx-core/src/question/create.ts
workitem: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/29321496
Removing `Preview` tag for Python CEC templates as the dependency was already public.
> refactor: remove preview tag for Python templates

- packages/fx-core/src/common/featureFlags.ts
- packages/fx-core/src/question/create.ts
- packages/fx-core/tests/question/create.test.ts
[Bug 29362457](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/29362457): Add a new feature flag to hide the API Plugin with AAD template
> fix: hide the AAD in copilot extensions

- packages/vscode-extension/package.json
[Bug 29397812](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/29397812): Add Plugin is not available as a command
> fix: add plugin in command palette

- packages/spec-parser/src/constants.ts
- templates/csharp/api-plugin-from-scratch-bearer/appPackage/ai-plugin.json.tpl
- templates/csharp/api-plugin-from-scratch-oauth/appPackage/ai-plugin.dev.json.tpl
- templates/csharp/api-plugin-from-scratch-oauth/appPackage/ai-plugin.local.json.tpl
- templates/csharp/api-plugin-from-scratch/appPackage/ai-plugin.json.tpl
- templates/csharp/copilot-gpt-from-scratch-plugin/appPackage/ai-plugin.json.tpl
- templates/csharp/copilot-gpt-from-scratch-plugin/appPackage/repairDeclarativeAgent.json.tpl
- templates/js/api-plugin-from-scratch-bearer/appPackage/ai-plugin.json.tpl
- templates/js/api-plugin-from-scratch-bearer/appPackage/repairDeclarativeAgent.json.tpl
- templates/js/api-plugin-from-scratch-oauth/appPackage/ai-plugin.dev.json.tpl
- templates/js/api-plugin-from-scratch-oauth/appPackage/ai-plugin.local.json.tpl
- templates/js/api-plugin-from-scratch-oauth/appPackage/repairDeclarativeAgent.json.tpl
- templates/js/api-plugin-from-scratch/appPackage/ai-plugin.json.tpl
- templates/js/api-plugin-from-scratch/appPackage/repairDeclarativeAgent.json.tpl
- templates/js/copilot-gpt-from-scratch-plugin/appPackage/ai-plugin.json.tpl
- templates/js/copilot-gpt-from-scratch-plugin/appPackage/repairDeclarativeAgent.json.tpl
- templates/ts/api-plugin-from-scratch-bearer/appPackage/ai-plugin.json.tpl
- templates/ts/api-plugin-from-scratch-bearer/appPackage/repairDeclarativeAgent.json.tpl
- templates/ts/api-plugin-from-scratch-oauth/appPackage/ai-plugin.dev.json.tpl
- templates/ts/api-plugin-from-scratch-oauth/appPackage/ai-plugin.local.json.tpl
- templates/ts/api-plugin-from-scratch-oauth/appPackage/repairDeclarativeAgent.json.tpl
- templates/ts/api-plugin-from-scratch/appPackage/ai-plugin.json.tpl
- templates/ts/api-plugin-from-scratch/appPackage/repairDeclarativeAgent.json.tpl
- templates/ts/copilot-gpt-from-scratch-plugin/appPackage/ai-plugin.json.tpl
- templates/ts/copilot-gpt-from-scratch-plugin/appPackage/repairDeclarativeAgent.json.tpl
Change the schema URL to the following link:
- Declarative Copilot: https://aka.ms/json-schemas/copilot/declarative-agent/v1.0/schema.json
- Plugin: https://aka.ms/json-schemas/copilot/plugin/v2.1/schema.json
Involving the following templates:
- API Plugin from scratch (None auth, API Key, AAD, OAuth).
- API Plugin from existing API.
- Basic Declarative Copilot.
- Declarative Copilot with a plugin (None auth, API Key, AAD, OAuth).
- Declarative Copilot with a plugin from existing API.
> refactor: update the schema link for copilot extensions

- packages/fx-core/src/common/wrappedAxiosClient.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/29548065
> fix: process url path to avoid being redacted in mos api telemetry

- packages/vscode-extension/src/controls/sampleGallery/sampleCard.tsx
ADO: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/29506356
Before:
After:
> fix: sample app tags are not read

- templates/python/custom-copilot-assistant-assistants-api/appPackage/manifest.json.tpl
- templates/python/custom-copilot-assistant-assistants-api/src/bot.py.tpl
- templates/python/custom-copilot-assistant-new/appPackage/manifest.json.tpl
- templates/python/custom-copilot-assistant-new/src/bot.py.tpl
- templates/python/custom-copilot-rag-azure-ai-search/appPackage/manifest.json.tpl
- templates/python/custom-copilot-rag-azure-ai-search/src/bot.py.tpl
- templates/python/custom-copilot-rag-custom-api/appPackage/manifest.json.tpl
- templates/python/custom-copilot-rag-custom-api/src/bot.py.tpl
- templates/python/custom-copilot-rag-customize/appPackage/manifest.json.tpl
- templates/python/custom-copilot-rag-customize/src/bot.py.tpl
workitem: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/29613578
> feat: add zero prompts to python CEC

- packages/manifest/src/index.ts
- packages/manifest/test/index.test.ts
- packages/spec-parser/src/manifestUpdater.ts
- packages/spec-parser/test/manifestUpdater.test.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/29662104
> fix: copilot spec parser

- packages/vscode-extension/package.nls.json
ADO: 
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/29640658
Root cause:
This issue is introduced in [this PR](https://github.com/OfficeDev/teams-toolkit/pull/10955). As the content design stated: 'This change is recommended only if this content for CTA button.'. Since this is used as error source and will not be a CTA button, so revert this change.
> fix: remove space in login error source

- packages/fx-core/src/component/generator/officeAddin/generator.ts
- packages/fx-core/tests/component/generator/officeAddinGenerator.test.ts
fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/29792240
> fix: reset env after import outlook addin (#12494)

- packages/cli/src/commonlib/telemetry.ts
- packages/vscode-extension/src/debug/depsChecker/common.ts
- packages/vscode-extension/src/telemetry/vscodeTelemetryReporter.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/29830127
1. output telemetry log when use set loglevel=debug in vscode extension
2. Refine refine prerequisite checker error message
> fix: refine prerequisite checker error message

- packages/tests/src/ui-test/localdebug/localdebug-dashboard-tab-ts.test.ts
- packages/tests/src/ui-test/localdebug/localdebug-dashboard-tab.test.ts
- packages/tests/src/utils/constants.ts
fix auto test for dashboard template
> test: update local debug task result

- packages/fx-core/src/common/featureFlags.ts
- packages/fx-core/src/component/generator/generator.ts
workitem: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/29844771
> feat: add feature flag for Custom Engine Agent(CEA) templates

- packages/fx-core/src/component/driver/oauth/update.ts
- packages/fx-core/src/component/driver/oauth/utility/utility.ts
- packages/fx-core/tests/component/driver/oauth/update.test.ts
bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_sprints/taskboard/AuthAndData/Microsoft%20Teams%20Extensibility/Selenium/CY24Q4/2Wk/2Wk01%20(Oct%2006%20-%20Oct%2019)?workitem=29858551
> fix(oauth): update all auth info in spec in oauth/update action

- templates/js/copilot-plugin-from-scratch-api-key/appPackage/apiSpecificationFile/repair.yml
[Bug 29903473](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/29903473): [daily release] API Message Extension with API key auth js project provision failed
> fix: api spec issue

- templates/csharp/custom-copilot-rag-custom-api/OpenAPIClient/RequestParams.cs
[Bug 29971535](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/29971535): [VS][Rag Custom API Bot] Local debug failed for dotnet 6.0
> perf: replace primary constructors with standard constructors for .NET 6 compatibility

- packages/fx-core/src/component/driver/teamsApp/utils/telemetry.ts
- packages/fx-core/src/component/driver/teamsApp/validate.ts
- packages/fx-core/tests/component/driver/teamsApp/validate.test.ts
- packages/fx-core/tests/plugins/resource/appstudio/resources-multi-env/templates/appPackage/resources/en.invalid.json
- packages/fx-core/tests/plugins/resource/appstudio/resources-multi-env/templates/appPackage/v3.invalid.default.localization.manifest.json
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/29904765
Also added telemetry for localization errors
> feat: add schema validation for default language file

- packages/fx-core/src/component/generator/generator.ts
- packages/fx-core/src/component/generator/templates/templateReplaceMap.ts
- packages/fx-core/tests/component/generator/generator.test.ts
- templates/python/custom-copilot-assistant-assistants-api/appPackage/manifest.json.tpl
- templates/python/custom-copilot-assistant-assistants-api/teamsapp.local.yml.tpl
- templates/python/custom-copilot-assistant-assistants-api/teamsapp.yml.tpl
- templates/python/custom-copilot-assistant-new/appPackage/manifest.json.tpl
- templates/python/custom-copilot-assistant-new/teamsapp.local.yml.tpl
- templates/python/custom-copilot-assistant-new/teamsapp.yml.tpl
- templates/python/custom-copilot-basic/appPackage/manifest.json.tpl
- templates/python/custom-copilot-basic/teamsapp.local.yml.tpl
- templates/python/custom-copilot-basic/teamsapp.yml.tpl
- templates/python/custom-copilot-rag-azure-ai-search/appPackage/manifest.json.tpl
- templates/python/custom-copilot-rag-azure-ai-search/teamsapp.local.yml.tpl
- templates/python/custom-copilot-rag-azure-ai-search/teamsapp.yml.tpl
- templates/python/custom-copilot-rag-custom-api/appPackage/manifest.json.tpl
- templates/python/custom-copilot-rag-custom-api/teamsapp.local.yml.tpl
- templates/python/custom-copilot-rag-custom-api/teamsapp.yml.tpl
- templates/python/custom-copilot-rag-customize/appPackage/manifest.json.tpl
- templates/python/custom-copilot-rag-customize/teamsapp.local.yml.tpl
- templates/python/custom-copilot-rag-customize/teamsapp.yml.tpl
workitem: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/29830998
> refactor: modify manifests for PY templates, add CEAEnabled consume logic and add test case

- templates/js/custom-copilot-assistant-assistants-api/appPackage/manifest.json.tpl
- templates/js/custom-copilot-assistant-new/appPackage/manifest.json.tpl
- templates/js/custom-copilot-basic/appPackage/manifest.json.tpl
- templates/js/custom-copilot-rag-azure-ai-search/appPackage/manifest.json.tpl
- templates/js/custom-copilot-rag-customize/appPackage/manifest.json.tpl
- templates/js/custom-copilot-rag-microsoft365/appPackage/manifest.json.tpl
- templates/ts/custom-copilot-assistant-assistants-api/appPackage/manifest.json.tpl
- templates/ts/custom-copilot-assistant-new/appPackage/manifest.json.tpl
- templates/ts/custom-copilot-basic/appPackage/manifest.json.tpl
- templates/ts/custom-copilot-rag-azure-ai-search/appPackage/manifest.json.tpl
- templates/ts/custom-copilot-rag-customize/appPackage/manifest.json.tpl
- templates/ts/custom-copilot-rag-microsoft365/appPackage/manifest.json.tpl
update CEA schema url and version base on blackchoey's comments in https://github.com/OfficeDev/teams-toolkit/pull/12512
> fix: update CEA schema url and version(js/ts)

- templates/ts/custom-copilot-rag-azure-ai-search/src/app/customSayCommand.ts
- templates/ts/custom-copilot-rag-customize/src/app/customSayCommand.ts
- templates/ts/custom-copilot-rag-microsoft365/src/app/customSayCommand.ts
fix bug https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/30017009
reference path was changed due to teams.ai 1.5.3 upgrade: https://github.com/microsoft/teams-ai/pull/2120
so update relate template to fix this bug
> fix: update reference path base on teams.ai 1.5.3

- packages/vscode-extension/src/debug/teamsfxTaskHandler.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/30076176
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/30076176
> fix: end local debug session when launch test tool to avoid sending incorrect debug-all event

- templates/python/custom-copilot-basic/appPackage/manifest.json.tpl
workitem: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/30132551
> fix: bad zero prompt for Python basic chat CEA

- packages/fx-core/src/component/utils/envFunctionUtils.ts
- packages/fx-core/tests/component/util/envFunctionUtils.test.ts
Two fixes included in this PR:
- [Bug 29887497](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/29887497): Allow ".md" in $[file({filepath})] function
- Replace "\r\n" with "\n"
> fix: env func

- packages/fx-core/src/component/utils/envFunctionUtils.ts
[Bug 30149474](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/30149474): file() function used in manifest.json should replace '\r\n' with '\n'
> fix: replace \r\n with \n

- packages/manifest/src/index.ts
* fix: add format
[Bug 30033654](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/30033654): Validating a project with an API plugin using the manifest schema causes an error
> fix: validation manifest format

- templates/python/custom-copilot-assistant-assistants-api/src/bot.py.tpl
- templates/python/custom-copilot-assistant-assistants-api/src/requirements.txt
- templates/python/custom-copilot-assistant-new/src/bot.py.tpl
- templates/python/custom-copilot-assistant-new/src/requirements.txt
- templates/python/custom-copilot-rag-azure-ai-search/README.md.tpl
- templates/python/custom-copilot-rag-azure-ai-search/src/bot.py.tpl
- templates/python/custom-copilot-rag-azure-ai-search/src/requirements.txt
- templates/python/custom-copilot-rag-customize/src/bot.py.tpl
- templates/python/custom-copilot-rag-customize/src/requirements.txt
workitem: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/30173015
Along with some import fixes
> fix: need to upgrade version of team-ai sdk

- packages/vscode-extension/package.json
- packages/vscode-extension/pnpm-lock.yaml
- packages/vscode-extension/src/debug/depsChecker/common.ts
- packages/vscode-extension/src/debug/depsChecker/taskChecker.ts
- packages/vscode-extension/src/debug/teamsfxDebugProvider.ts
- packages/vscode-extension/src/debug/teamsfxTaskHandler.ts
- packages/vscode-extension/src/utils/processUtil.ts
- packages/vscode-extension/test/utils/processUtil.test.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/30162620
The root cause of this bug is that TTK check ports immediately after killing the process that occupies the ports and the killing is not finished. So the kill process behavior should be executed in a sync mode to avoid this issue.
> fix: kill process tree sync

- packages/vscode-extension/src/controls/sampleGallery/sampleDetailPage.tsx
Related bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/29825293
> fix(vsc): blank sample detail page on codespaces

- packages/cli/src/cmds/preview/constants.ts
[Bug 30091455](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/30091455): [CLI] sample "teams central dashboard" use "preview" command will stuck in progress
After migrating to Vite from react-script, the ready signal output indicating that the service is launched should also be updated.
The output while using vite:
```
> team-central-dashboard@0.1.0 dev:teamsfx
> env-cmd --silent -f .localConfigs npm run start
> team-central-dashboard@0.1.0 start
> vite
Port 53000 is in use, trying another one...
VITE v5.4.11  ready in 567 ms
➜  Local:   https://localhost:53001/
➜  Network: use --host to expose
➜  press h + enter to show help
```
So, we should add a new state string 'ready'.
> fix: update running pattern to include 'ready' status

- packages/fx-core/tests/component/generator/apiSpecGenerator.test.ts
- packages/spec-parser/src/constants.ts
- packages/spec-parser/src/utils.ts
- packages/spec-parser/src/validators/validator.ts
- packages/spec-parser/test/adaptiveCardGenerator.test.ts
- packages/spec-parser/test/adaptiveCardWrapper.test.ts
- packages/spec-parser/test/manifestUpdater.test.ts
- packages/spec-parser/test/specParser.test.ts
- packages/spec-parser/test/utils.test.ts
Also update adaptive card schema to https: [Task 30229843](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/30229843): response_semantics in api plugin file schema is not https
> perf(da): allow http server for declarative agent

- templates/csharp/api-plugin-from-scratch-oauth/aad.manifest.json.tpl
- templates/csharp/api-plugin-from-scratch-oauth/infra/azure.bicep.tpl
- templates/js/api-plugin-from-scratch-oauth/aad.manifest.json.tpl
- templates/js/api-plugin-from-scratch-oauth/infra/azure.bicep.tpl
- templates/ts/api-plugin-from-scratch-oauth/aad.manifest.json.tpl
- templates/ts/api-plugin-from-scratch-oauth/infra/azure.bicep.tpl
Fix: [Bug 30266021](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/30266021): [stable hotfix]Remote debug will get 403 forbidden for declarative/api plugin Microsoft Entra project
Cherry-pick https://github.com/OfficeDev/teams-toolkit/pull/12415
> fix: remote debug 403 error in API Plugin with AAD template

- packages/fx-core/src/component/m365/launchHelper.ts
- packages/fx-core/src/component/provisionUtils.ts
- packages/fx-core/src/core/collaborator.ts
- packages/fx-core/tests/component/m365/launchHelper.test.ts
- packages/fx-core/tests/component/provisionUtils.test.ts
- packages/vscode-extension/src/commonlib/codeFlowLogin.ts
- packages/vscode-extension/src/debug/teamsfxDebugProvider.ts
- packages/vscode-extension/src/utils/envTreeUtils.ts
- packages/vscode-extension/test/utils/envTreeUtils.test.ts
1> append `tenantId` parameter in debug & preview launch url
2> fallback to displayName when collaborator upn is null
3> fallback to unique_name when upn is null to avoid undefined display name for m365 account in provision confirm dialog
4> read m365 tenant id from env file instead of state.env.json file
ADO:
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/29860159
> feat: e2e support for multi-tenant

- packages/vscode-extension/src/debug/depsChecker/common.ts
- packages/vscode-extension/src/utils/processUtil.ts
- packages/vscode-extension/test/utils/processUtil.test.ts
fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/30344887
> fix: kill process silently

- packages/vscode-extension/src/debug/common/debugConstants.ts
- packages/vscode-extension/src/debug/common/types.ts
- packages/vscode-extension/src/debug/teamsfxDebugProvider.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/30207172
I'm adding a placeholder(`${agent-hint}`) in the launch URL of the declarative agents to enable deep linking for agents.
The template changes will be in a separate PR.
> feat: deep link for declarative agents
