- Localize/loc/cs/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/cs/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/de/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/de/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/es/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/es/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/fr/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/fr/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/it/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/it/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/ja/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/ja/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/ko/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/ko/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/pl/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/pl/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/pt-BR/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/pt-BR/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/ru/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/ru/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/tr/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/tr/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/zh-Hans/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/zh-Hans/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/zh-Hant/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/zh-Hant/packages/vscode-extension/package.nls.json.lcl
LEGO: Pull request from juno/hb_fd34cb3d-1ea5-4a7c-8a66-721a44a97af3_20221109154416035 to dev with localized lcls
> chore(localization): [LEGO] Pull request from juno/hb_fd34cb3d-1ea5-4a7c-8a66-721a44a97af3_20221109154416035 to dev

- packages/vscode-extension/src/debug/teamsfxTaskHandler.ts
- packages/vscode-extension/src/exp/treatmentVariables.ts
- packages/vscode-extension/src/extension.ts
- packages/vscode-extension/src/qm/vsc_ui.ts
- packages/vscode-extension/src/treeview/treeViewManager.ts
- packages/vscode-extension/src/utils/survey.ts
- packages/vscode-extension/test/extension/treeview/treeViewManager.test.ts
chore: cleanup embedded survey ab test
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/16200632
> chore: cleanup embedded survey ab test

- packages/fx-core/src/component/middleware/envMW.ts
- packages/fx-core/tests/component/envUtil.test.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/16198497
> chore: fix envMW by modifying process.env in place

- packages/fx-core/resource/package.nls.json
- packages/fx-core/src/common/telemetry.ts
- packages/fx-core/src/component/constants.ts
- packages/fx-core/src/component/coordinator/index.ts
- packages/fx-core/src/component/developerPortalScaffoldUtils.ts
- packages/fx-core/src/component/provisionUtils.ts
- packages/fx-core/src/component/resource/appManifest/appStudioClient.ts
- packages/fx-core/src/component/utils/ResourceGroupHelper.ts
- packages/fx-core/src/core/middleware/questionModel.ts
- packages/fx-core/src/core/question.ts
- packages/fx-core/tests/component/coordinator.test.ts
- packages/fx-core/tests/component/developerPortalScaffoldUtils.test.ts
- update project files (appPackage, .env.local) when scaffolding based on a teams app from Developer Portal
> chore: update files for scaffolding based on app from TDP

- packages/vscode-extension/src/debug/commonUtils.ts
> fix(debug): do not load to process when reading env

- packages/vscode-extension/package.json
Manually update extension version since tag failed
> chore: update extension version

- packages/vscode-extension/package.nls.json
- packages/vscode-extension/src/debug/constants.ts
- packages/vscode-extension/src/debug/taskTerminal/localTunnelTaskTerminal.ts
- packages/vscode-extension/src/error.ts
Install ngrok and start local tunnel
Use global installed ngrok
Ngrok Installation error:
> chore(localdebug): install ngrok in local tunnel task for v3

- packages/fx-core/resource/package.nls.json
- packages/fx-core/src/common/deps-checker/depsManager.ts
- packages/fx-core/src/common/deps-checker/depsTelemetry.ts
- packages/fx-core/src/component/driver/tools/error/funcInstallationUserError.ts
- packages/fx-core/src/component/driver/tools/installDriver.ts
- packages/fx-core/tests/component/driver/tools/installDriver.test.ts
Success:
Warning:
Error:
TODO: install the target version of Azure Functions Core Tools
E2E TEST: none
> feat(localdebug): add func to tools/install driver

- packages/cli/src/cmds/preview/preview.ts
- packages/fx-core/src/common/deps-checker/checkerFactory.ts
- packages/fx-core/src/common/deps-checker/depsChecker.ts
- packages/fx-core/src/common/deps-checker/depsManager.ts
- packages/fx-core/src/common/deps-checker/internal/vxTestAppChecker.ts
- packages/fx-core/src/common/local/constants.ts
- packages/vscode-extension/src/debug/prerequisitesHandler.ts
- packages/vscode-extension/src/debug/taskTerminal/prerequisiteTaskTerminal.ts
* parse `installOptions` argument for prerequisite check task 
* add an empty VxTestAppChecker 
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/16037812/
> feat(video-filter): add VxTestAppChecker boilerplate code

- packages/fx-core/src/component/debugHandler/bot.ts
- packages/fx-core/src/component/driver/botAadApp/create.ts
- packages/fx-core/src/component/driver/m365Bot/createOrUpdate.ts
- packages/fx-core/src/component/resource/botService/appStudio/appStudioClient.ts
- packages/fx-core/src/component/resource/botService/botRegistration/botRegistration.ts
- packages/fx-core/src/component/resource/botService/botRegistration/localBotRegistration.ts
- packages/fx-core/src/component/resource/botService/botRegistration/remoteBotRegistration.ts
- packages/fx-core/src/component/resource/botService/botService.ts
- packages/fx-core/src/component/resource/botService/constants.ts
- packages/fx-core/src/component/resource/botService/errors.ts
- packages/fx-core/tests/component/debugHandler/bot.test.ts
- packages/fx-core/tests/component/resource/botService/appStudioClient.test.ts
- packages/fx-core/tests/component/resource/botService/botService.test.ts
- Refactor bot error message for create error
> chore: create bot error message

- packages/vscode-extension/package-lock.json
- packages/vscode-extension/src/commonlib/azureLogin.ts
> fix(vsc): provison select subscription failed in v3

- Localize/loc/cs/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/cs/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/de/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/de/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/es/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/es/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/fr/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/fr/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/it/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/it/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/ja/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/ja/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/ko/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/ko/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/pl/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/pl/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/pt-BR/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/pt-BR/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/ru/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/ru/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/tr/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/tr/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/zh-Hans/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/zh-Hans/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/zh-Hant/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/zh-Hant/packages/vscode-extension/package.nls.json.lcl
LEGO: Pull request from juno/hb_fd34cb3d-1ea5-4a7c-8a66-721a44a97af3_20221113154421054 to dev with localized lcls
> chore(localization): [LEGO] Pull request from juno/hb_fd34cb3d-1ea5-4a7c-8a66-721a44a97af3_20221113154421054 to dev

- packages/vscode-extension/src/handlers.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/16111911
> chore(vsc): remove isM365 in V3

- packages/vscode-extension/src/debug/teamsfxDebugProvider.ts
ms-teams-vscode-extension	v4.1.3-rc.2
> fix: fix teamsAppId placeholder not resolved for remote preview

- templates/scenarios/js/notification-restify/teamsfx/app.local.yml
add `BOT_DOMAIN` env to` teamsApp/validate` driver
E2E TEST: none
> fix(localdebug): add BOT_DOMAIN env to teamsApp/validate driver

- packages/fx-core/resource/package.nls.json
- packages/fx-core/src/component/coordinator/index.ts
- packages/fx-core/src/component/driver/botFramework/createOrUpdateBot.ts
- packages/fx-core/src/component/driver/botFramework/error/invalidParameterUserError.ts
- packages/fx-core/src/component/driver/botFramework/error/unhandledError.ts
- packages/fx-core/src/component/driver/botFramework/interface/createOrUpdateBotFrameworkBotArgs.ts
- packages/fx-core/src/component/provisionUtils.ts
- packages/fx-core/src/core/FxCore.ts
- packages/fx-core/tests/component/driver/botFramework/createOrUpdateBot.test.ts
- packages/fx-core/tests/component/provisionUtils.test.ts
- templates/scenarios/js/notification-restify/teamsfx/app.local.yml
- m365Bot/createOrUpdate -> botFramework/createOrUpdateBot
- remove iconUrl in app.local.yaml
- fix bot password typo in app.local.yaml
> chore(debug): rename bot driver

- packages/sdk-react/src/useGraph.ts
@microsoft/teamsfx-react	v2.0.1-rc.1
ms-teams-vscode-extension	v4.1.3-rc.2
> perf: update teamsfx-react sdk to align with Tab usage

- packages/vscode-extension/src/extension.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/16229720
> chore(vsc): fix welcome view display bug

- packages/vscode-extension/package.json
- packages/vscode-extension/src/treeview/environmentTreeViewProvider.ts
Feature: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/15906480
E2E TEST: N/A
> feat(vsc): remove env tree in v3

- packages/fx-core/src/component/feature/apiconnector/depsHandler.ts
- packages/fx-core/templates/plugins/resource/apiconnector/package.json
- packages/fx-core/tests/component/feature/apiconnector/sampleFiles/package-teamsfx-included.json
@microsoft/teamsfx-cli	v1.1.5-rc.1
@microsoft/teamsfx-core	v1.19.0-rc.1
@microsoft/teamsfx-react	v2.0.1-rc.1
ms-teams-vscode-extension	v4.1.3-rc.2
> chore: upgrade the api connector sdk version to 2.0.0

- templates/scenarios/csharp/command-and-response/{%ProjectName%}.csproj.tpl
- templates/scenarios/csharp/message-extension/{%ProjectName%}.csproj.tpl
- templates/scenarios/csharp/non-sso-tab/{%ProjectName%}.csproj.tpl
- templates/scenarios/csharp/notification-http-timer-trigger/{%ProjectName%}.csproj.tpl
- templates/scenarios/csharp/notification-http-trigger/{%ProjectName%}.csproj.tpl
- templates/scenarios/csharp/notification-timer-trigger/{%ProjectName%}.csproj.tpl
- templates/scenarios/csharp/notification-webapi/{%ProjectName%}.csproj.tpl
- templates/scenarios/csharp/sso-tab/{%ProjectName%}.csproj.tpl
- templates/scenarios/csharp/workflow/{%ProjectName%}.csproj.tpl
- templates/scenarios/js/command-and-response/appPackage/manifest.template.json.tpl
- templates/scenarios/js/default-bot/appPackage/manifest.template.json.tpl
- templates/scenarios/js/m365-message-extension/appPackage/manifest.template.json.tpl
- templates/scenarios/js/m365-tab/appPackage/manifest.template.json.tpl
- templates/scenarios/js/message-extension/appPackage/manifest.template.json.tpl
- templates/scenarios/js/non-sso-tab/appPackage/manifest.template.json.tpl
- templates/scenarios/js/notification-http-timer-trigger/appPackage/manifest.template.json.tpl
- templates/scenarios/js/notification-timer-trigger/appPackage/manifest.template.json.tpl
- templates/scenarios/ts/command-and-response/appPackage/manifest.template.json.tpl
- templates/scenarios/ts/default-bot/appPackage/manifest.template.json.tpl
- templates/scenarios/ts/m365-message-extension/appPackage/manifest.template.json.tpl
- templates/scenarios/ts/message-extension/appPackage/manifest.template.json.tpl
- templates/scenarios/ts/non-sso-tab/appPackage/manifest.template.json.tpl
- templates/scenarios/ts/notification-http-timer-trigger/appPackage/manifest.template.json.tpl
- templates/scenarios/ts/notification-http-trigger/appPackage/manifest.template.json.tpl
- templates/scenarios/ts/notification-timer-trigger/appPackage/manifest.template.json.tpl
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/16283304
> chore: update manifest appname and remove .fx in vs

- packages/fx-core/package-lock.json
- packages/fx-core/package.json
@microsoft/teamsfx-cli	v1.1.5-rc.2
@microsoft/teamsfx-core	v1.19.0-rc.2
ms-teams-vscode-extension	v4.1.3-rc.3
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/16267153/
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/16285595
> fix: create resource maxPageSize error

- packages/cli/src/cmds/init.ts
- packages/cli/src/telemetry/cliTelemetryEvents.ts
- packages/cli/src/utils.ts
- packages/cli/tests/unit/cmds/init.tests.ts
https://dev.azure.com/msazure/Microsoft%20Teams%20Extensibility/_workitems/edit/16254297
> chore(cli): init debug for V3

- packages/cli/src/cmds/index.ts
- packages/cli/tests/unit/cmds/index.tests.ts
https://dev.azure.com/msazure/Microsoft%20Teams%20Extensibility/_workitems/edit/16285988
> chore(cli): hide add command when V3 flag is open

- packages/fx-core/src/component/resource/aadApp/aadAppManifestManager.ts
- packages/fx-core/tests/component/resource/aadApp/unit/aadManifestManager.test.ts
Fix this bug: https://github.com/OfficeDev/TeamsFx/issues/5997
E2E TEST: already added unit test
> fix: add support for msal redirect URL in aad template

- packages/vscode-extension/CHANGELOG.md
- packages/vscode-extension/WHATISNEW.md
ms-teams-vscode-extension	v4.1.3-rc.4
> docs: update changelog for 1117 release

- packages/vscode-extension/src/handlers.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/16267128
E2E TEST: N/A
> fix(vsc): enable the click of QuickPick icon button

- templates/scenarios/js/m365-message-extension/teamsfx/app.local.yml.tpl
- templates/scenarios/js/m365-message-extension/teamsfx/app.yml.tpl
- templates/scenarios/js/m365-tab/aad.manifest.template.json.tpl
- templates/scenarios/js/m365-tab/teamsfx/app.local.yml.tpl
- templates/scenarios/js/m365-tab/teamsfx/app.yml.tpl
- templates/scenarios/ts/m365-message-extension/teamsfx/app.local.yml.tpl
- templates/scenarios/ts/m365-message-extension/teamsfx/app.yml.tpl
- templates/scenarios/ts/m365-tab/aad.manifest.template.json.tpl
- templates/scenarios/ts/m365-tab/teamsfx/app.local.yml.tpl
- templates/scenarios/ts/m365-tab/teamsfx/app.yml.tpl
- use appname placeholder in m365 tab and message extension templates
> chore: use appname placeholder in templates

- packages/fx-core/templates/plugins/resource/spfx/solution/manifest_multi_env.json
ADO: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/16270543
E2E TEST: NA
> fix: update manifest template version to v1.14 in spfx project

- packages/fx-core/src/component/generator/spfxGenerator.ts
- packages/fx-core/tests/component/generator/spfxGenerator.test.ts
ADO: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/16214605
E2E TEST: NA
> fix: use app name as spfx solution name

- packages/fx-core/src/component/configManager/error.ts
Fixes https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_sprints/taskboard/Teams%20Extensibility%20E2E%20Team/Microsoft%20Teams%20Extensibility/CY22-11.1?workitem=16269149
> chore: add help link for config manager

- Localize/loc/cs/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/cs/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/de/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/de/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/es/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/es/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/fr/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/fr/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/it/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/it/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/ja/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/ja/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/ko/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/ko/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/pl/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/pl/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/pt-BR/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/pt-BR/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/ru/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/ru/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/tr/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/tr/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/zh-Hans/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/zh-Hans/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/zh-Hant/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/zh-Hant/packages/vscode-extension/package.nls.json.lcl
LEGO: Pull request from juno/hb_fd34cb3d-1ea5-4a7c-8a66-721a44a97af3_20221117114022832 to dev with localized lcls
> chore(localization): [LEGO] Pull request from juno/hb_fd34cb3d-1ea5-4a7c-8a66-721a44a97af3_20221117114022832 to dev

- lerna.json
- packages/run-utils/package-lock.json
- packages/run-utils/package.json
- add missing fs-extra dependency
> chore: add back teamsfx-run-utils to lerna.json

- templates/scenarios/csharp/non-sso-tab/Components/AddSSO.razor
- templates/scenarios/csharp/non-sso-tab/Program.cs.tpl
Remove addTeamsFx since no teamsfx config exists
> chore(vs): remove addTeamsFx in non sso tab template

- templates/bot/js/default/package.json
- templates/bot/ts/default/package.json
- templates/scenarios/js/default-bot/package.json.tpl
- templates/scenarios/ts/default-bot/package.json.tpl
Remove isomorphic-fetch package from package.json since it's not used anymore.
> perf: update default bot template

- packages/fx-core/templates/plugins/resource/aad/auth/V3/README.txt
Bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_sprints/taskboard/AuthAndData/Microsoft%20Teams%20Extensibility/CY22-11.1?workitem=16338192
Task: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_sprints/taskboard/AuthAndData/Microsoft%20Teams%20Extensibility/CY22-11.1?workitem=16338228
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_sprints/taskboard/AuthAndData/Microsoft%20Teams%20Extensibility/CY22-11.1?workitem=16338229
> docs(sso): update doc for add sso for v3

- templates/scenarios/csharp/command-and-response/.gitignore
- templates/scenarios/csharp/message-extension/.gitignore
- templates/scenarios/csharp/non-sso-tab/.gitignore
- templates/scenarios/csharp/notification-http-timer-trigger/.gitignore
- templates/scenarios/csharp/notification-http-trigger/.gitignore
- templates/scenarios/csharp/notification-timer-trigger/.gitignore
- templates/scenarios/csharp/notification-webapi/.gitignore
- templates/scenarios/csharp/sso-tab/.gitignore
- templates/scenarios/csharp/workflow/.gitignore
chore: correct gitignore for vs templates
https://dev.azure.com/msazure/Microsoft%20Teams%20Extensibility/_workitems/edit/16338860
> chore: correct gitignore for vs templates

- packages/cli/src/cmds/account.ts
https://dev.azure.com/msazure/Microsoft%20Teams%20Extensibility/_workitems/edit/16313076
> chore(cli): fix account undefined for V3

- packages/cli/src/cmds/permission.ts
fix bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_sprints/taskboard/AuthAndData/Microsoft%20Teams%20Extensibility/CY22-11.1?workitem=16338492
> perf(collaborattion): allow user use interactive mode to input env in cli

- packages/fx-core/src/component/generator/utils.ts
- packages/fx-core/tests/component/generator/generator.test.ts
> fix(generator): sample relative path

- templates/scenarios/csharp/command-and-response/Properties/launchSettings.json.tpl
- templates/scenarios/csharp/message-extension/Properties/launchSettings.json.tpl
- templates/scenarios/csharp/non-sso-tab/Properties/launchSettings.json.tpl
- templates/scenarios/csharp/notification-http-timer-trigger/Properties/launchSettings.json.tpl
- templates/scenarios/csharp/notification-http-trigger/Properties/launchSettings.json.tpl
- templates/scenarios/csharp/notification-timer-trigger/Properties/launchSettings.json.tpl
- templates/scenarios/csharp/notification-webapi/Properties/launchSettings.json.tpl
- templates/scenarios/csharp/sso-tab/Properties/launchSettings.json.tpl
- templates/scenarios/csharp/workflow/Properties/launchSettings.json.tpl
Improve VS 'launchSettings' templates.
> chore: update vs launchSettings templates

- packages/fx-core/src/component/middleware/envMW.ts
- packages/fx-core/src/core/FxCore.ts
- packages/fx-core/src/core/middleware/envInfoLoaderV3.ts
- packages/fx-core/tests/component/envUtil.test.ts
provision, deploy and publish:
validate/zip:
> chore: do not list local env for provision, deploy and publish

- packages/fx-core/src/component/configManager/interface.ts
- packages/fx-core/src/component/configManager/lifecycle.ts
Fixes https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_sprints/taskboard/Teams%20Extensibility%20E2E%20Team/Microsoft%20Teams%20Extensibility/CY22-11.1?workitem=16301878 
and 
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_sprints/taskboard/Teams%20Extensibility%20E2E%20Team/Microsoft%20Teams%20Extensibility/CY22-11.1?workitem=16341560
> chore: add telemetry and improve logging

- packages/fx-core/src/component/constants.ts
- packages/fx-core/src/component/coordinator/index.ts
- packages/fx-core/src/component/developerPortalScaffoldUtils.ts
- packages/fx-core/src/component/resource/appManifest/utils/utils.ts
- packages/fx-core/src/core/middleware/questionModel.ts
- packages/fx-core/src/core/question.ts
- packages/fx-core/tests/component/coordinator.test.ts
- Update to scaffold based on the new template introduced in https://github.com/OfficeDev/TeamsFx/pull/6917
- Fix some issues I found during testing TDP to TTK
- TODO: add ts template
> chore: scaffold project with the new template for TDP

- packages/fx-core/src/component/coordinator/index.ts
- packages/fx-core/tests/component/coordinator.test.ts
> perf(core): fix the provision successful message

- templates/scenarios/common/init-debug-vsc-bot/teamsfx/app.local.yml
- templates/scenarios/common/init-debug-vsc-tab/teamsfx/app.local.yml
> fix: fix init debug typo

- packages/fx-core/src/component/driver/teamsApp/copyAppPackageForSPFx.ts
- templates/scenarios/ts/spfx-tab-pre/teamsfx/.env.dev
- templates/scenarios/ts/spfx-tab-pre/teamsfx/app.yml
- templates/scenarios/ts/spfx-tab/teamsfx/.env.dev
- templates/scenarios/ts/spfx-tab/teamsfx/app.yml
ADO: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/16371263
E2E TEST: NA
> fix: spfx v3 e2e broken and env.dev missing

- Localize/loc/cs/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/cs/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/de/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/de/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/es/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/es/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/it/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/it/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/ja/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/ja/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/ko/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/ko/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/pl/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/pl/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/pt-BR/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/pt-BR/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/tr/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/tr/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/zh-Hans/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/zh-Hans/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/zh-Hant/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/zh-Hant/packages/vscode-extension/package.nls.json.lcl
LEGO: Pull request from juno/hb_fd34cb3d-1ea5-4a7c-8a66-721a44a97af3_20221123160250059 to dev with localized lcls
> chore(localization): [LEGO] Pull request from juno/hb_fd34cb3d-1ea5-4a7c-8a66-721a44a97af3_20221123160250059 to dev

- packages/cli/src/cmds/index.ts
- packages/cli/src/cmds/preview/constants.ts
- packages/cli/src/cmds/preview/previewEnv.ts
- packages/cli/tests/unit/cmds/preview/previewEnv.tests.ts
V3 preview has different behavior so prepare entrypoint for v3 preview.
> chore: prepare v3 preview cmd

- .github/workflows/e2e-test.yml
This reverts commit 5565ec110d33a21c874b2c5a583c8f24e3798f0a.
> chore: revert v3 e2e testing

- packages/cli/src/cmds/preview/errors.ts
- packages/cli/src/cmds/preview/previewEnv.ts
- packages/cli/tests/unit/cmds/preview/previewEnv.tests.ts
- Check m365 account
- Set run-command if not provided
- PR comments from #6962
> chore: add v3 preview steps

- Localize/loc/cs/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/cs/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/de/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/de/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/fr/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/fr/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/it/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/it/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/ja/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/ja/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/ko/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/ko/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/pl/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/pl/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/pt-BR/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/pt-BR/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/ru/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/ru/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/tr/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/tr/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/zh-Hans/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/zh-Hans/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/zh-Hant/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/zh-Hant/packages/vscode-extension/package.nls.json.lcl
LEGO: Pull request from juno/hb_fd34cb3d-1ea5-4a7c-8a66-721a44a97af3_20221127154523514 to dev with localized lcls
> chore(localization): [LEGO] Pull request from juno/hb_fd34cb3d-1ea5-4a7c-8a66-721a44a97af3_20221127154523514 to dev

- packages/fx-core/src/component/coordinator/index.ts
- packages/fx-core/src/component/provisionUtils.ts
- packages/fx-core/tests/component/coordinator.test.ts
[Bug 16357453](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/16357453): [VS 17.5][Bug Bash]Cancel "Provision on Azure" will be created resource group in the Azure portal
E2E TEST: N/A
> fix: create resource group after user confirmation

- .github/workflows/e2e-test.yml
- packages/cli/tests/commonlib/aadValidate.ts
- packages/cli/tests/commonlib/botValidator.ts
- packages/cli/tests/commonlib/constants.ts
- packages/cli/tests/commonlib/frontendValidator.ts
- packages/cli/tests/e2e/bot/BotHappyPathCommon.ts
- packages/cli/tests/e2e/bot/CommandBotHappyPathCommon.ts
- packages/cli/tests/e2e/commonUtils.ts
- packages/cli/tests/e2e/frontend/TestCreateTab.tests.ts
the e2e test run on current branch
https://github.com/OfficeDev/TeamsFx/actions/runs/3547323664
> chore: enable e2e base test case for v3

- packages/vscode-extension/src/debug/constants.ts
- packages/vscode-extension/src/debug/depsChecker/doctorConstant.ts
- packages/vscode-extension/src/debug/prerequisitesHandler.ts
- packages/vscode-extension/src/debug/taskTerminal/prerequisiteTaskTerminal.ts
> chore(localdebug): update v3 prerequisite message

- packages/vscode-extension/package.nls.json
- packages/vscode-extension/src/handlers.ts
Related issue: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/16386793
1. change group.
2. remove obsolete option.
> chore(vsc): change tutorial option group

- packages/api/review/teamsfx-api.api.md
- packages/api/src/constants.ts
- packages/cli/src/cmds/update.ts
- packages/cli/src/constants.ts
- packages/cli/src/utils.ts
- packages/cli/tests/unit/cmds/update.tests.ts
- packages/fx-core/resource/package.nls.json
- packages/fx-core/src/component/driver/teamsApp/configure.ts
- packages/fx-core/src/component/resource/appManifest/appManifest.ts
- packages/fx-core/src/component/resource/appManifest/appStudio.ts
- packages/fx-core/src/core/FxCore.ts
- packages/vscode-extension/package.json
- packages/vscode-extension/src/handlers.ts
non interactive mode, will continue update:
> chore: add param to update teams-app

- templates/bot/csharp/workflow/Commands/HelloWorldCommandHandler.cs.tpl
- templates/bot/js/workflow/src/commands/helloworldCommandHandler.js
- templates/scenarios/csharp/workflow/Commands/HelloWorldCommandHandler.cs.tpl
- templates/scenarios/js/workflow/src/commands/helloworldCommandHandler.js
> chore: fix wording in workflow app adaptive card

- packages/vscode-extension/package.nls.json
- packages/vscode-extension/src/constants.ts
- packages/vscode-extension/src/uriHandler.ts
- packages/vscode-extension/test/extension/uriHandler.test.ts
- check whether v3 feature flag is enabled or not if the link is from TDP. If not, ask user to switch to pre-release version.
> chore: tdp v3 feature flag check

- packages/cli/src/constants.ts
https://dev.azure.com/msazure/Microsoft%20Teams%20Extensibility/_workitems/edit/16427567/?triage=true
> perf: update the cli update aad folder descrption

- packages/cli/src/commonlib/azureLogin.ts
- packages/cli/src/index.ts
https://dev.azure.com/msazure/Microsoft%20Teams%20Extensibility/_workitems/edit/16303292
> chore(cli): not detect locale and fix set subscription for V2

- Localize/loc/cs/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/cs/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/de/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/de/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/es/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/es/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/fr/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/fr/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/it/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/it/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/ja/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/ja/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/ko/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/ko/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/pl/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/pl/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/pt-BR/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/pt-BR/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/ru/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/ru/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/tr/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/tr/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/zh-Hans/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/zh-Hans/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/zh-Hant/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/zh-Hant/packages/vscode-extension/package.nls.json.lcl
LEGO: Pull request from juno/hb_fd34cb3d-1ea5-4a7c-8a66-721a44a97af3_20221130154407824 to dev with localized lcls
> chore(localization): [LEGO] Pull request from juno/hb_fd34cb3d-1ea5-4a7c-8a66-721a44a97af3_20221130154407824 to dev

- packages/cli/src/cmds/preview/previewEnv.ts
- packages/cli/tests/unit/cmds/preview/previewEnv.tests.ts
Reuse existing preview events.
> chore: v3 cli preview telemetry

- .github/workflows/cd.yml
- .github/workflows/vscode-marketplace.yml
- packages/fx-core/src/common/tools.ts
- packages/vscode-extension/config/dev.env.js
- packages/vscode-extension/config/index.js
- packages/vscode-extension/webpack.config.js
change contains:
1. release preview TTK with version such as 3.2.2022112008
2. The daily release is brought forward to 8 am
3. webpack define the preview/other build
> chore: support release v3 preview TTK

- packages/fx-core/src/component/utils/ResourceGroupHelper.ts
- packages/fx-core/src/core/question.ts
[Bug 15066282](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/15066282): [Cli]provision some steps need press enter twice then work
> chore: check resource group from list

- packages/fx-core/src/component/driver/tools/installDriver.ts
- packages/fx-core/tests/component/driver/tools/installDriver.test.ts
Output func path in the tools/install driver.
> chore(localdebug): Output func path in the tools/install driver

- packages/vscode-extension/package.nls.json
- packages/vscode-extension/src/handlers.ts
- packages/vscode-extension/test/extension/handlers.test.ts
> feat: add tutorial entry for dashboard scenario

- Localize/loc/cs/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/cs/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/de/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/de/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/es/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/es/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/fr/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/fr/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/it/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/it/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/ja/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/ja/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/ko/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/ko/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/pl/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/pl/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/pt-BR/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/pt-BR/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/ru/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/tr/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/tr/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/zh-Hans/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/zh-Hans/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/zh-Hant/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/zh-Hant/packages/vscode-extension/package.nls.json.lcl
LEGO: Pull request from juno/hb_fd34cb3d-1ea5-4a7c-8a66-721a44a97af3_20221204154443833 to dev with localized lcls
> chore(localization): [LEGO] Pull request from juno/hb_fd34cb3d-1ea5-4a7c-8a66-721a44a97af3_20221204154443833 to dev

- templates/scenarios/js/command-and-response/README.md
- templates/scenarios/js/default-bot-message-extension/README.md
- templates/scenarios/js/default-bot/README.md
- templates/scenarios/js/m365-message-extension/README.md
- templates/scenarios/js/m365-tab/README.md
- templates/scenarios/js/message-extension/README.md
- templates/scenarios/js/non-sso-tab/README.md
- templates/scenarios/js/notification-http-timer-trigger/README.md
- templates/scenarios/js/notification-http-trigger/README.md
- templates/scenarios/js/notification-restify/README.md
- templates/scenarios/js/notification-timer-trigger/README.md
- templates/scenarios/js/sso-tab/README.md
- templates/scenarios/js/workflow/README.md
- templates/scenarios/ts/command-and-response/README.md
- templates/scenarios/ts/default-bot-message-extension/README.md
- templates/scenarios/ts/default-bot/README.md
- templates/scenarios/ts/m365-message-extension/README.md
- templates/scenarios/ts/m365-tab/README.md
- templates/scenarios/ts/message-extension/README.md
- templates/scenarios/ts/non-sso-tab/README.md
- templates/scenarios/ts/notification-http-timer-trigger/README.md
- templates/scenarios/ts/notification-http-trigger/README.md
- templates/scenarios/ts/notification-restify/README.md
- templates/scenarios/ts/notification-timer-trigger/README.md
- templates/scenarios/ts/sso-tab/README.md
- templates/scenarios/ts/workflow/README.md
- remove "Known issue" section from m365-message-extension
- update the usage of teamsfx preview in all templates except non-sso-tab-default-bot
- update folder structure description in notification, command-and-response, workflow
> chore(debug): update templates readme

- packages/cli/tests/e2e/command/argumentCheck.tests.ts
- packages/cli/tests/e2e/command/deployWithWrongPluginName.tests.ts
- packages/cli/tests/e2e/command/helpInfo.tests.ts
- packages/cli/tests/e2e/command/template.tests.ts
E2E TEST: https://github.com/OfficeDev/TeamsFx/actions/runs/3616385037
> test(cli): command e2e tests

- packages/fx-core/src/component/driver/teamsApp/configure.ts
- packages/fx-core/src/component/driver/teamsApp/create.ts
- packages/fx-core/src/component/driver/teamsApp/createAppPackage.ts
- packages/fx-core/src/component/driver/teamsApp/publishAppPackage.ts
- packages/fx-core/src/component/driver/teamsApp/validate.ts
wiki has been updated: https://github.com/OfficeDev/TeamsFx/wiki/Available-actions-in-Teams-Toolkit#teamsappcreate
> chore: add help link for teams app drivers

- packages/fx-core/resource/package.nls.json
Forgot committing this file change in #7049.
> chore: add env/generate description string

- packages/cli/src/cmds/preview/depsChecker/cliChecker.ts
- packages/cli/src/cmds/preview/preview.ts
- packages/cli/src/constants.ts
- packages/cli/tests/unit/cmds/preview/depsChecker.test.ts
- packages/fx-core/src/common/deps-checker/checkerFactory.ts
- packages/fx-core/src/common/deps-checker/depsChecker.ts
- packages/fx-core/src/common/deps-checker/depsManager.ts
- packages/fx-core/src/common/deps-checker/internal/nodeChecker.ts
- packages/fx-core/src/common/local/localEnvManager.ts
- packages/fx-core/src/component/resource/spfx/utils/constants.ts
- packages/fx-core/templates/plugins/resource/spfx/solution/README.md
- packages/fx-core/tests/common/local/localEnvManager.test.ts
- packages/fx-core/tests/plugins/resource/spfx/depsChecker/generatorChecker.test.ts
- packages/vscode-extension/src/constants.ts
- packages/vscode-extension/src/debug/depsChecker/vscodeChecker.ts
- packages/vscode-extension/src/debug/prerequisitesHandler.ts
- packages/vscode-extension/test/localdebug/depsChecker.test.ts
- templates/scenarios/ts/spfx-tab/src/README.md
> feat: upgrade SPFx version to 1.16

- packages/fx-core/src/component/driver/botAadApp/create.ts
- packages/fx-core/src/component/resource/botService/botRegistration/botRegistration.ts
- packages/fx-core/src/component/resource/botService/botRegistration/localBotRegistration.ts
- packages/fx-core/src/component/resource/botService/botRegistration/remoteBotRegistration.ts
- packages/fx-core/src/component/resource/botService/botService.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/16112058
> chore: adjust param order to remove explict undefined

- packages/fx-core/templates/plugins/resource/aad/manifest/bot/aad.manifest.template.json
- packages/fx-core/templates/plugins/resource/aad/manifest/tab/aad.manifest.template.json
Will reference in how-to guide for SSO
> docs(sso): add aad manifest template for tab & bot

- packages/vscode-extension/package.json
- packages/vscode-extension/src/extension.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/16520586
E2E TEST: N/A
> fix(vsc): disable "add feature" from command palette in v3

- packages/cli/tests/commonlib/cliHelper.ts
- packages/cli/tests/e2e/commonUtils.ts
- packages/cli/tests/e2e/solution/ProvisionWithLoggedOutSubscriptionInfo.tests.ts
- packages/cli/tests/e2e/solution/SSOTabE2ETestWithAADManifestEnabled.tests.ts
E2E TEST: https://github.com/OfficeDev/TeamsFx/actions/runs/3627850767
> test: update aad manifest e2e case suite for v3

- .github/workflows/cd.yml
- packages/fx-core/src/common/tools.ts
- packages/vscode-extension/config/dev.env.js
- packages/vscode-extension/webpack.config.js
tried on this pipeline
https://github.com/OfficeDev/TeamsFx/actions/runs/3629220926
> chore: restore preview release both on v2 and v3

- packages/vscode-extension/src/codeLensProvider.ts
- packages/vscode-extension/src/extension.ts
- packages/vscode-extension/test/extension/codeLensProvider.test.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/16504418
E2E TEST: N/A
> feat(vsc): codelens crypto support for v3

- packages/vscode-extension/package.nls.json
- packages/vscode-extension/src/handlers.ts
- packages/vscode-extension/test/extension/handlers.test.ts
> chore: add how-to guide for add Key Vault

- packages/cli/tests/commonlib/aadValidate.ts
- packages/cli/tests/commonlib/botValidator.ts
- packages/cli/tests/commonlib/constants.ts
- packages/cli/tests/commonlib/frontendValidator.ts
- packages/cli/tests/e2e/frontend/BlazorAppHappyPath.tests.ts
- packages/cli/tests/e2e/frontend/TestCreateTab.tests.ts
- packages/cli/tests/e2e/scaffold/AzureAppScaffold.tests.ts
["./scaffold/AzureAppScaffold.tests.ts", "./frontend/BlazorAppHappyPath.tests.ts"]
Two test cases passed.
https://github.com/OfficeDev/TeamsFx/actions/runs/3635638695
> test: migrate e2e test to v3

- packages/fx-core/src/common/deps-checker/internal/vxTestAppChecker.ts
> chore: replace with github release url

- templates/bot/csharp/command-and-response/Properties/launchSettings.json.tpl
- templates/bot/csharp/default/Properties/launchSettings.json.tpl
- templates/bot/csharp/notification-webapi/Properties/launchSettings.json.tpl
- templates/bot/csharp/workflow/Properties/launchSettings.json.tpl
- templates/scenarios/csharp/command-and-response/Properties/launchSettings.json.tpl
- templates/scenarios/csharp/message-extension/Properties/launchSettings.json.tpl
- templates/scenarios/csharp/non-sso-tab/Properties/launchSettings.json.tpl
- templates/scenarios/csharp/notification-webapi/Properties/launchSettings.json.tpl
- templates/scenarios/csharp/sso-tab/Properties/launchSettings.json.tpl
- templates/scenarios/csharp/workflow/Properties/launchSettings.json.tpl
- templates/tab/csharp/default/Properties/launchSettings.json.tpl
- templates/tab/csharp/non-sso/Properties/launchSettings.json.tpl
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/16512410
Uncomment project debug profile.
> chore: update vs launch comment

- packages/cli/tests/e2e/collaboration/PermissionSPFX.tests.ts
E2E test passed: 
https://github.com/OfficeDev/TeamsFx/actions/runs/3644497546/jobs/6153944885
> test: update PermissionSPFX.tests.ts to support v3

- packages/vscode-extension/src/qm/vsc_ui.ts
- packages/vscode-extension/test/extension/userInterface.test.ts
- packages/vscode-extension/test/mocks/vscode-mock.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/16536306
E2E TEST: N/A
> feat(vsc): support openFile API

- packages/vscode-extension/src/debug/prerequisitesHandler.ts
Detail: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/16537940/
E2E TEST: none
> fix(localdebug): fix get started prerequisite check in v3

- templates/scenarios/ts/message-extension/package.json.tpl
> chore(template): fix build script for message extension template

- packages/cli/tests/e2e/frontend/CanDeployToCustomizedRg.tests.ts
https://github.com/OfficeDev/TeamsFx/actions/runs/3646555043
> test: customize resource group in v3

- packages/vscode-extension/src/debug/teamsfxDebugProvider.ts
Fix https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/16553454.
> chore(debug): do not print hot reloading hint for remote launch

- packages/fx-core/src/common/samples-config-v3.json
Currently there're 8 samples ready for v3:
> chore: exclude samples that are not ready for v3

- packages/fx-core/templates/core/v3Migration/js.ts.app.local.yml
- packages/fx-core/tests/core/middleware/debug/appLocalYmlGenerator.test.ts
- packages/fx-core/tests/core/middleware/testAssets/v3Migration/debug/transparent-bot/expected/app.local.yml
- packages/fx-core/tests/core/middleware/testAssets/v3Migration/debug/transparent-notification/expected/app.local.yml
- packages/fx-core/tests/core/middleware/testAssets/v3Migration/debug/transparent-sso-bot/expected/app.local.yml
- packages/fx-core/tests/core/middleware/testAssets/v3Migration/debug/transparent-sso-tab/expected/app.local.yml
- packages/fx-core/tests/core/middleware/testAssets/v3Migration/debug/transparent-tab-bot-func/expected/app.local.yml
- packages/fx-core/tests/core/middleware/testAssets/v3Migration/debug/transparent-tab/expected/app.local.yml
- teamsApp/createAppPackage -> teamsApp/zipAppPackage
- npm/command -> cli/runNpmCommand
> chore(debug-migration): rename actions in yml template

- packages/cli/src/cmds/index.ts
- packages/cli/tests/unit/cmds/index.tests.ts
- packages/cli/tests/unit/cmds/preview/errors.tests.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_sprints/taskboard/Teams%20Extensibility%20E2E%20Team/Microsoft%20Teams%20Extensibility/CY22-12.1?workitem=16125440
> chore: remove teamsfx apply

- packages/fx-core/src/component/feature/tab.ts
> chore: remove sso from dashboard tab

- packages/fx-core/src/component/resource/appManifest/appStudioClient.ts
> fix: keep error pattern

- templates/scenarios/js/command-and-response/teamsfx/app.local.yml.tpl
- templates/scenarios/js/command-and-response/teamsfx/app.yml.tpl
- templates/scenarios/js/default-bot-message-extension/teamsfx/app.local.yml.tpl
- templates/scenarios/js/default-bot/teamsfx/app.local.yml.tpl
- templates/scenarios/js/message-extension/teamsfx/app.local.yml.tpl
- templates/scenarios/js/non-sso-tab-default-bot/teamsfx/app.local.yml.tpl
- templates/scenarios/js/notification-http-timer-trigger/teamsfx/app.local.yml.tpl
- templates/scenarios/js/notification-http-timer-trigger/teamsfx/app.yml.tpl
- templates/scenarios/js/notification-restify/teamsfx/app.local.yml.tpl
- templates/scenarios/js/notification-restify/teamsfx/app.yml.tpl
- templates/scenarios/js/notification-timer-trigger/teamsfx/app.local.yml.tpl
- templates/scenarios/js/notification-timer-trigger/teamsfx/app.yml.tpl
- templates/scenarios/ts/command-and-response/teamsfx/app.local.yml.tpl
- templates/scenarios/ts/command-and-response/teamsfx/app.yml.tpl
- templates/scenarios/ts/default-bot-message-extension/teamsfx/app.local.yml.tpl
- templates/scenarios/ts/default-bot/teamsfx/app.local.yml.tpl
- templates/scenarios/ts/message-extension/teamsfx/app.local.yml.tpl
- templates/scenarios/ts/non-sso-tab-default-bot/teamsfx/app.local.yml.tpl
- templates/scenarios/ts/notification-http-timer-trigger/teamsfx/app.local.yml.tpl
- templates/scenarios/ts/notification-http-timer-trigger/teamsfx/app.yml.tpl
- templates/scenarios/ts/notification-http-trigger/teamsfx/app.local.yml.tpl
- templates/scenarios/ts/notification-http-trigger/teamsfx/app.yml.tpl
- templates/scenarios/ts/notification-restify/teamsfx/app.yml.tpl
- templates/scenarios/ts/notification-timer-trigger/teamsfx/app.local.yml.tpl
- templates/scenarios/ts/notification-timer-trigger/teamsfx/app.yml.tpl
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/16585315/
> chore: use dynamic appname in local yml

- packages/fx-core/src/core/middleware/projectMigratorV3.ts
- packages/fx-core/tests/core/middleware/projectMigrationV3.test.ts
> fix: judge 'components' exists and iterable

- packages/fx-core/src/core/middleware/utils/appYmlGenerator.ts
- packages/fx-core/templates/core/v3Migration/js.ts.app.yml
- packages/fx-core/tests/core/middleware/projectMigrationV3.test.ts
- packages/fx-core/tests/core/middleware/testAssets/v3Migration/jsFunctionBot/.fx/configs/projectSettings.json
- packages/fx-core/tests/core/middleware/testAssets/v3Migration/jsFunctionBot/appPackage/manifest.template.json
- packages/fx-core/tests/core/middleware/testAssets/v3Migration/jsFunctionBot/expectedResult/js.app.yml
- packages/fx-core/tests/core/middleware/testAssets/v3Migration/jsFunctionBot/expectedResult/ts.app.yml
- packages/fx-core/tests/core/middleware/testAssets/v3Migration/jsFunctionBot/templates/azure/provision.bicep
- packages/fx-core/tests/core/middleware/testAssets/v3Migration/jsNonSsoTab/.fx/configs/projectSettings.json
- packages/fx-core/tests/core/middleware/testAssets/v3Migration/jsNonSsoTab/appPackage/manifest.template.json
- packages/fx-core/tests/core/middleware/testAssets/v3Migration/jsNonSsoTab/expectedResult/js.app.yml
- packages/fx-core/tests/core/middleware/testAssets/v3Migration/jsNonSsoTab/expectedResult/ts.app.yml
- packages/fx-core/tests/core/middleware/testAssets/v3Migration/jsNonSsoTab/templates/azure/provision.bicep
- packages/fx-core/tests/core/middleware/testAssets/v3Migration/jsSsoTab/.fx/configs/projectSettings.json
- packages/fx-core/tests/core/middleware/testAssets/v3Migration/jsSsoTab/aad.manifest.template.json
- packages/fx-core/tests/core/middleware/testAssets/v3Migration/jsSsoTab/appPackage/manifest.template.json
- packages/fx-core/tests/core/middleware/testAssets/v3Migration/jsSsoTab/expectedResult/js.app.yml
- packages/fx-core/tests/core/middleware/testAssets/v3Migration/jsSsoTab/expectedResult/ts.app.yml
- packages/fx-core/tests/core/middleware/testAssets/v3Migration/jsSsoTab/templates/azure/provision.bicep
- packages/fx-core/tests/core/middleware/testAssets/v3Migration/jsTabWithApi/.fx/configs/projectSettings.json
- packages/fx-core/tests/core/middleware/testAssets/v3Migration/jsTabWithApi/aad.manifest.template.json
- packages/fx-core/tests/core/middleware/testAssets/v3Migration/jsTabWithApi/appPackage/manifest.template.json
- packages/fx-core/tests/core/middleware/testAssets/v3Migration/jsTabWithApi/expectedResult/js.app.yml
- packages/fx-core/tests/core/middleware/testAssets/v3Migration/jsTabWithApi/expectedResult/ts.app.yml
- packages/fx-core/tests/core/middleware/testAssets/v3Migration/jsTabWithApi/templates/azure/provision.bicep
- packages/fx-core/tests/core/middleware/testAssets/v3Migration/jsWebappBot/.fx/configs/projectSettings.json
- packages/fx-core/tests/core/middleware/testAssets/v3Migration/jsWebappBot/appPackage/manifest.template.json
- packages/fx-core/tests/core/middleware/testAssets/v3Migration/jsWebappBot/expectedResult/js.app.yml
- packages/fx-core/tests/core/middleware/testAssets/v3Migration/jsWebappBot/expectedResult/ts.app.yml
- packages/fx-core/tests/core/middleware/testAssets/v3Migration/jsWebappBot/templates/azure/provision.bicep
migrate webapp bot, function bot and function api projects
> chore: migrate js/ts project

- packages/cli/src/cmds/preview/previewEnv.ts
- packages/vscode-extension/src/debug/commonUtils.ts
- packages/vscode-extension/src/debug/teamsAppInstallation.ts
- templates/scenarios/js/m365-message-extension/README.md
- templates/scenarios/ts/m365-message-extension/README.md
- remove configuring outlook channel from install app in teams prompt
- update m365-message-extension README
> chore(debug): remove configuring outlook channel from prompt 

- templates/scenarios/js/default-bot-message-extension/index.js
- templates/scenarios/js/default-bot/index.js
- templates/scenarios/js/m365-message-extension/index.js
- templates/scenarios/js/message-extension/index.js
- templates/scenarios/js/non-sso-tab-default-bot/bot/index.js
- templates/scenarios/ts/default-bot-message-extension/index.ts
- templates/scenarios/ts/default-bot-message-extension/package.json.tpl
- templates/scenarios/ts/default-bot/index.ts
- templates/scenarios/ts/default-bot/package.json.tpl
- templates/scenarios/ts/m365-message-extension/index.ts
- templates/scenarios/ts/m365-message-extension/package.json.tpl
- templates/scenarios/ts/message-extension/index.ts
- templates/scenarios/ts/message-extension/package.json.tpl
- templates/scenarios/ts/non-sso-tab-default-bot/bot/index.ts
- templates/scenarios/ts/non-sso-tab-default-bot/bot/package.json.tpl
Reverts OfficeDev/TeamsFx#7048
> Revert "chore: use cloud adapter for v3 bot templates"

- Localize/loc/cs/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/cs/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/de/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/de/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/es/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/es/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/fr/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/fr/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/it/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/it/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/ja/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/ja/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/ko/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/ko/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/pl/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/pl/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/pt-BR/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/pt-BR/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/ru/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/ru/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/tr/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/tr/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/zh-Hans/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/zh-Hans/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/zh-Hant/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/zh-Hant/packages/vscode-extension/package.nls.json.lcl
LEGO: Pull request from juno/hb_fd34cb3d-1ea5-4a7c-8a66-721a44a97af3_20221214154504551 to dev with localized lcls
> chore(localization): [LEGO] Pull request from juno/hb_fd34cb3d-1ea5-4a7c-8a66-721a44a97af3_20221214154504551 to dev

- Localize/loc/cs/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/cs/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/de/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/de/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/es/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/es/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/fr/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/fr/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/it/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/it/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/ja/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/ja/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/ko/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/ko/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/pl/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/pl/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/pt-BR/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/pt-BR/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/ru/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/ru/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/tr/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/tr/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/zh-Hans/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/zh-Hans/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/zh-Hant/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/zh-Hant/packages/vscode-extension/package.nls.json.lcl
LEGO: Pull request from juno/hb_fd34cb3d-1ea5-4a7c-8a66-721a44a97af3_20221218154420081 to dev with localized lcls
> chore(localization): [LEGO] Pull request from juno/hb_fd34cb3d-1ea5-4a7c-8a66-721a44a97af3_20221218154420081 to dev

- packages/vscode-extension/src/debug/prerequisitesHandler.ts
- packages/vscode-extension/src/telemetry/extTelemetryEvents.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/16605049
E2E TEST: N/A
> chore: add telemetry for sdk version

- packages/dotnet-sdk/src/TeamsFx/Microsoft.TeamsFx.csproj
> chore: update dotnet-sdk version

- packages/fx-core/src/component/resource/spfx/depsChecker/yoChecker.ts
ADO: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/16608511
E2E TEST: NA
> fix: upgrade yo to 4.3.1 to avoid the break on macos

- packages/fx-core/src/core/FxCoreImplementV3.ts
- packages/vscode-extension/src/handlers.ts
- packages/vscode-extension/test/extension/handlers.test.ts
@microsoft/teamsfx-cli	v1.2.0-rc.2
@microsoft/teamsfx-core	v1.21.0-rc.2
ms-teams-vscode-extension	v4.2.0-rc.2
> fix(vsc): guides entries and add environment

- packages/fx-core/src/core/error.ts
- packages/fx-core/src/core/middleware/projectMigratorV3.ts
- packages/fx-core/tests/core/middleware/projectMigrationV3.test.ts
TODO: discuss error message and error code with PM
> perf(migrationv3): update error

- packages/fx-core/templates/plugins/resource/aad/auth/tab/ts/sso/InitTeamsFx.tsx
@microsoft/teamsfx-cli	v1.2.0-rc.2
@microsoft/teamsfx-core	v1.21.0-rc.2
ms-teams-vscode-extension	v4.2.0-rc.2
> perf(sso): add ! for ts sample code (#7275)

- packages/vscode-extension/CHANGELOG.md
- packages/vscode-extension/WHATISNEW.md
ms-teams-vscode-extension	v4.2.0-rc.2
> docs: update whatsnew and changelog for 1220 release

- templates/scenarios/ts/notification-timer-trigger/teamsfx/app.local.yml.tpl
Correct action name to "prerequisite/install"
(https://github.com/OfficeDev/TeamsFx/pull/7187/files#diff-683c16dd4a795751c4e693bbaa94995fc8f677df969d0fd9f6b19aac07b9a92c)
E2E TEST: N/A
> fix: fix func bot template

- packages/fx-core/templates/core/v3Migration/csharp.app.local.yml
1.Support func/web bot during migration.
> chore: update local yml for migration

- packages/vscode-extension/src/debug/constants.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/16638684
> chore: better f5 wording

- packages/fx-core/src/component/developerPortalScaffoldUtils.ts
- packages/fx-core/src/core/FxCoreImplementV3.ts
- packages/fx-core/src/core/middleware/questionModel.ts
- packages/vscode-extension/package.json
- packages/vscode-extension/package.nls.json
- packages/vscode-extension/src/commonlib/m365Login.ts
- packages/vscode-extension/src/constants.ts
- packages/vscode-extension/src/handlers.ts
- fxcore: add checking platform to avoid overwriting values of input from VS
- vscode: add learn more link and icon for "publish in developer portal", and update description
- m365login: tolowercase()
> chore: improve TDP & VSC

- packages/cli/package.json
- packages/sdk-react/package-lock.json
- packages/vscode-extension/package.json
- templates/bot/csharp/command-and-response/ProjectName.csproj.tpl
- templates/bot/csharp/default/ProjectName.csproj.tpl
- templates/bot/csharp/notification-function-base/ProjectName.csproj.tpl
- templates/bot/csharp/notification-webapi/ProjectName.csproj.tpl
- templates/bot/csharp/workflow/ProjectName.csproj.tpl
- templates/scenarios/csharp/command-and-response/{%ProjectName%}.csproj.tpl
- templates/scenarios/csharp/message-extension/{%ProjectName%}.csproj.tpl
- templates/scenarios/csharp/notification-http-timer-trigger/{%ProjectName%}.csproj.tpl
- templates/scenarios/csharp/notification-http-trigger/{%ProjectName%}.csproj.tpl
- templates/scenarios/csharp/notification-timer-trigger/{%ProjectName%}.csproj.tpl
- templates/scenarios/csharp/notification-webapi/{%ProjectName%}.csproj.tpl
- templates/scenarios/csharp/workflow/{%ProjectName%}.csproj.tpl
@microsoft/teamsfx-cli	v1.2.1-rc.0
@microsoft/teamsfx-react	v2.1.1-rc.0
ms-teams-vscode-extension	v4.2.1-rc.0
E2E TEST: N/A
> fix: fix dependency conflict for botbuilder

- templates/scenarios/common/init-debug-vs-bot/teamsfx/app.local.yml
- templates/scenarios/common/init-debug-vs-tab/teamsfx/app.local.yml
1. Update init debug local yml content.
Fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/16650759/
> chore: update init vs debug local yml

- templates/scenarios/common/init-debug-vs-bot/teamsfx/app.local.yml
- templates/scenarios/common/init-debug-vs-tab/teamsfx/app.local.yml
1. Change appName to a fixed name.
> chore: update init debug local yml

- packages/fx-core/src/component/resource/appManifest/appStudioClient.ts
@microsoft/teamsfx-cli	v1.2.1-rc.0
@microsoft/teamsfx-core	v1.22.0-rc.1
@microsoft/teamsfx-react	v2.1.1-rc.0
ms-teams-vscode-extension	v4.2.1-rc.0
> fix: do not use regional api

- packages/server/src/serverConnection.ts
- packages/server/tests/serverConnections.test.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/16665767
> chore: migration return value

- packages/fx-core/src/component/driver/botAadApp/create.ts
- packages/fx-core/tests/component/driver/botAadApp/create.test.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_sprints/taskboard/Compute%20Team/Microsoft%20Teams%20Extensibility/CY22-12.1?workitem=16458879
E2E TEST: N/A
> chore: add telemetry

- packages/fx-core/src/core/FxCoreImplementV3.ts
- packages/fx-core/tests/core/FxCore.test.ts
@microsoft/teamsfx-cli	v1.2.2-rc.0
@microsoft/teamsfx-core	v1.22.0-rc.2
ms-teams-vscode-extension	v4.2.2-rc.0
> fix: add sso for bot not work in VS

- packages/vscode-extension/src/debug/teamsfxTaskProvider.ts
Fix https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/16639774.
> chore(debug-migration): trigger migration for prerequisites task

- packages/fx-core/src/component/coordinator/index.ts
- packages/fx-core/src/core/question.ts
Support for scaffolding a dashboard tab app in v3.
E2E TEST: N/A
> chore: support for dashboard tab app in v3

- templates/scenarios/common/init-infra-vs-tab/teamsfx/app.yml
- templates/scenarios/common/init-infra-vsc-tab/teamsfx/app.yml
- templates/scenarios/csharp/sso-tab/teamsfx/app.local.yml.tpl
- templates/scenarios/csharp/sso-tab/teamsfx/app.yml.tpl
- templates/scenarios/js/m365-tab/teamsfx/app.local.yml.tpl
- templates/scenarios/js/m365-tab/teamsfx/app.yml.tpl
- templates/scenarios/js/sso-tab/teamsfx/app.local.yml.tpl
- templates/scenarios/js/sso-tab/teamsfx/app.yml.tpl
- templates/scenarios/ts/m365-tab/teamsfx/app.local.yml.tpl
- templates/scenarios/ts/m365-tab/teamsfx/app.yml.tpl
- templates/scenarios/ts/sso-tab/teamsfx/app.local.yml.tpl
- templates/scenarios/ts/sso-tab/teamsfx/app.yml.tpl
teamsApp actions will use manifestPath as param name,
aadApp/update action will use manifestTemplatePath
> fix: aadApp/update should keep manifestTemplatePath param nmae

- Localize/loc/cs/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/de/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/es/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/fr/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/it/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/ja/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/ko/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/pl/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/pt-BR/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/ru/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/tr/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/zh-Hans/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/zh-Hant/packages/fx-core/resource/package.nls.json.lcl
LEGO: Pull request from juno/hb_fd34cb3d-1ea5-4a7c-8a66-721a44a97af3_20221228184437728 to dev with localized lcls
> chore(localization): [LEGO] Pull request from juno/hb_fd34cb3d-1ea5-4a7c-8a66-721a44a97af3_20221228184437728 to dev

- packages/fx-core/src/common/samples-config-v3.json
todo-list-spfx sample has been adapted to v3 in https://github.com/OfficeDev/TeamsFx-Samples/pull/584
> chore: add back todo-list-spfx sample in v3

- packages/fx-core/src/component/configManager/lifecycle.ts
Fixes https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_sprints/taskboard/Teams%20Extensibility%20E2E%20Team/Microsoft%20Teams%20Extensibility/CY22-12.2?workitem=16680746
> chore: remove ConfigManager from logs

- templates/bot/csharp/command-and-response/ProjectName.csproj.tpl
- templates/bot/csharp/notification-function-base/ProjectName.csproj.tpl
- templates/bot/csharp/notification-webapi/ProjectName.csproj.tpl
- templates/bot/csharp/workflow/ProjectName.csproj.tpl
- templates/scenarios/csharp/command-and-response/{%ProjectName%}.csproj.tpl
- templates/scenarios/csharp/non-sso-tab/{%ProjectName%}.csproj.tpl
- templates/scenarios/csharp/notification-http-timer-trigger/{%ProjectName%}.csproj.tpl
- templates/scenarios/csharp/notification-http-trigger/{%ProjectName%}.csproj.tpl
- templates/scenarios/csharp/notification-timer-trigger/{%ProjectName%}.csproj.tpl
- templates/scenarios/csharp/notification-webapi/{%ProjectName%}.csproj.tpl
- templates/scenarios/csharp/sso-tab/{%ProjectName%}.csproj.tpl
- templates/scenarios/csharp/workflow/{%ProjectName%}.csproj.tpl
- templates/tab/csharp/default/ProjectName.csproj.tpl
- templates/tab/csharp/non-sso/ProjectName.csproj.tpl
> chore: update templates to use correct range of sdk

- packages/fx-core/src/core/middleware/utils/debug/debugV3MigrationUtils.ts
- packages/fx-core/src/core/middleware/utils/debug/taskMigrator.ts
- packages/fx-core/tests/core/middleware/debug/taskMigrator.test.ts
- packages/fx-core/tests/core/middleware/testAssets/v3Migration/debug/V3.5.0-V4.0.6-command/expected/tasks.json
- packages/fx-core/tests/core/middleware/testAssets/v3Migration/debug/V3.5.0-V4.0.6-notification-trigger/expected/tasks.json
- packages/fx-core/tests/core/middleware/testAssets/v3Migration/debug/V3.5.0-V4.0.6-tab-bot-func/expected/tasks.json
- packages/fx-core/tests/core/middleware/testAssets/v3Migration/debug/V3.5.0-V4.0.6-tab/expected/tasks.json
- packages/fx-core/tests/core/middleware/testAssets/v3Migration/debug/beforeV3.4.0-bot/expected/tasks.json
- packages/fx-core/tests/core/middleware/testAssets/v3Migration/debug/beforeV3.4.0-tab-bot-func/expected/tasks.json
- packages/fx-core/tests/core/middleware/testAssets/v3Migration/debug/beforeV3.4.0-tab/expected/tasks.json
- packages/fx-core/tests/core/middleware/testAssets/v3Migration/debug/transparent-bot/expected/tasks.json
- packages/fx-core/tests/core/middleware/testAssets/v3Migration/debug/transparent-notification/expected/tasks.json
- packages/fx-core/tests/core/middleware/testAssets/v3Migration/debug/transparent-sso-bot/expected/tasks.json
- packages/fx-core/tests/core/middleware/testAssets/v3Migration/debug/transparent-sso-tab/expected/tasks.json
- packages/fx-core/tests/core/middleware/testAssets/v3Migration/debug/transparent-tab-bot-func/expected/tasks.json
- packages/fx-core/tests/core/middleware/testAssets/v3Migration/debug/transparent-tab/expected/tasks.json
- use label "Install tools and Build project" for teamsfx:deploy task
Related: https://github.com/OfficeDev/TeamsFx/pull/7259
> chore(debug-migration): polish task label

- packages/fx-core/templates/core/v3Migration/js.ts.app.local.yml
- packages/fx-core/tests/core/middleware/testAssets/v3Migration/debug/V3.5.0-V4.0.6-command/expected/app.local.yml
- packages/fx-core/tests/core/middleware/testAssets/v3Migration/debug/V3.5.0-V4.0.6-notification-trigger/expected/app.local.yml
- packages/fx-core/tests/core/middleware/testAssets/v3Migration/debug/V3.5.0-V4.0.6-tab-bot-func/expected/app.local.yml
- packages/fx-core/tests/core/middleware/testAssets/v3Migration/debug/V3.5.0-V4.0.6-tab/expected/app.local.yml
- packages/fx-core/tests/core/middleware/testAssets/v3Migration/debug/beforeV3.4.0-bot/expected/app.local.yml
- packages/fx-core/tests/core/middleware/testAssets/v3Migration/debug/beforeV3.4.0-tab-bot-func/expected/app.local.yml
- packages/fx-core/tests/core/middleware/testAssets/v3Migration/debug/beforeV3.4.0-tab/expected/app.local.yml
- packages/fx-core/tests/core/middleware/testAssets/v3Migration/debug/transparent-bot/expected/app.local.yml
- packages/fx-core/tests/core/middleware/testAssets/v3Migration/debug/transparent-notification/expected/app.local.yml
- packages/fx-core/tests/core/middleware/testAssets/v3Migration/debug/transparent-sso-bot/expected/app.local.yml
- packages/fx-core/tests/core/middleware/testAssets/v3Migration/debug/transparent-sso-tab/expected/app.local.yml
- packages/fx-core/tests/core/middleware/testAssets/v3Migration/debug/transparent-tab-bot-func/expected/app.local.yml
- packages/fx-core/tests/core/middleware/testAssets/v3Migration/debug/transparent-tab/expected/app.local.yml
- manifestTemplatePath -> manifestPath
Fix https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/16692916/.
> chore(debug-migration): rename teamsApp action arg

- packages/fx-core/src/component/resource/apim/services/apimService.ts
Fix bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/16643864/
E2E TEST: https://github.com/OfficeDev/TeamsFx/blob/0b0f8f190520fb554ea908f5b292f77c07abd2ec/packages/cli/tests/e2e/apim/TabAddApim.tests.ts#L27
> fix(apim): remove dupliate api call in apimService.listApi

- packages/vscode-extension/src/qm/vsc_ui.ts
related bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/16688492
> chore(vsc): wait 1 second before reloading

- templates/bot/csharp/workflow/.gitignore
- templates/bot/csharp/workflow/AdapterWithErrorHandler.cs.tpl
- templates/bot/csharp/workflow/CardActions/DoStuffActionHandler.cs.tpl
- templates/bot/csharp/workflow/Commands/HelloWorldCommandHandler.cs.tpl
- templates/bot/csharp/workflow/Controllers/BotController.cs.tpl
- templates/bot/csharp/workflow/GettingStarted.txt
- templates/bot/csharp/workflow/Models/HelloWorldModel.cs.tpl
- templates/bot/csharp/workflow/Program.cs.tpl
- templates/bot/csharp/workflow/ProjectName.csproj.tpl
- templates/bot/csharp/workflow/Properties/launchSettings.json.tpl
- templates/bot/csharp/workflow/Resources/DoStuffActionResponse.json
- templates/bot/csharp/workflow/Resources/HelloWorldCommandResponse.json
- templates/bot/csharp/workflow/TeamsBot.cs.tpl
- templates/bot/csharp/workflow/appsettings.json
- templates/package.json
Add workflow bot template for the fallback solution of VS 17.5 (based on the bits of 17.4) stable release.
E2E TEST: N/A
> feat: add workflow bot template based for 17.5 fallback solution

- .github/workflows/e2e-test.yml
- .github/workflows/rerun.yml
> chore: auto rerun failed e2e cases

- .github/workflows/e2e-test.yml
- packages/cli/tests/e2e/scaffold/ScaffoldFromSourceCode.tests.ts
E2E TEST: https://github.com/OfficeDev/TeamsFx/actions/runs/3879749433
> chore: e2e test use template source code for scaffolding

- templates/bot/js/default/teamsBot.js
- templates/bot/ts/default/teamsBot.ts
- templates/scenarios/js/default-bot-message-extension/teamsBot.js
- templates/scenarios/js/message-extension/teamsBot.js
- templates/scenarios/js/non-sso-tab-default-bot/bot/teamsBot.js
- templates/scenarios/ts/default-bot-message-extension/teamsBot.ts
- templates/scenarios/ts/message-extension/teamsBot.ts
- templates/scenarios/ts/non-sso-tab-default-bot/bot/teamsBot.ts
> fix(template): fix bug in message extension share message

- packages/fx-core/src/component/developerPortalScaffoldUtils.ts
- packages/fx-core/tests/component/developerPortalScaffoldUtils.test.ts
- also need to update web application info if sso.
> chore: update manifest 

- packages/dotnet-sdk/src/TeamsFx/Credential/TeamsUserCredential.cs
- packages/dotnet-sdk/src/TeamsFx/Microsoft.TeamsFx.csproj
- packages/dotnet-sdk/src/TeamsFx/Pages/AuthorizeEndPage.cshtml
- packages/dotnet-sdk/src/TeamsFx/Pages/AuthorizeStartPage.cshtml
- packages/fx-core/templates/plugins/resource/aad/auth/V3/Bot/Pages/BotAuthorizeEndPage.cshtml
- packages/fx-core/templates/plugins/resource/aad/auth/bot/csharp/Pages/BotAuthorizeEndPage.cshtml
- templates/scenarios/csharp/non-sso-tab/Interop/InteropModuleBase.cs.tpl
- templates/scenarios/csharp/sso-tab/Interop/InteropModuleBase.cs.tpl
- templates/tab/csharp/default/Interop/InteropModuleBase.cs.tpl
- templates/tab/csharp/non-sso/Interop/InteropModuleBase.cs.tpl
> chore: update to use latest version of teams-js

- packages/fx-core/src/common/samples-config.json
ADO: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/16535237
E2E TEST: only for vsc extension
> feat: remove hello world app and refine titles for v2

- packages/vscode-extension/src/debug/teamsfxDebugProvider.ts
- packages/vscode-extension/src/debug/teamsfxTaskProvider.ts
> chore(debug-migration): trigger migration for debug provider

- packages/fx-core/src/component/coordinator/index.ts
- packages/fx-core/tests/component/coordinator.test.ts
ADO: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/16752031
E2E TEST: NA
> fix: fix provision spfx project not show success notification issue

- packages/sdk-react/package-lock.json
- packages/sdk/CHANGELOG.md
- packages/sdk/package-lock.json
- packages/sdk/package.json
- packages/vscode-extension/package-lock.json
> chore: update version and changelog

- packages/vscode-extension/scripts/verdaccio.yaml
- packages/vscode-extension/scripts/vsce_locally.ts
> chore: refine local pack vsix script

- packages/fx-core/resource/package.nls.json
- packages/fx-core/src/component/driver/aad/interface/updateAadAppArgs.ts
- packages/fx-core/src/component/driver/aad/update.ts
- packages/fx-core/src/component/driver/aad/utility/buildAadManifest.ts
- packages/fx-core/src/core/FxCoreImplementV3.ts
- packages/fx-core/templates/plugins/resource/aad/auth/bot/README.md
- packages/fx-core/templates/plugins/resource/aad/auth/bot/ts/sso/profileSsoCommandHandler.ts
- packages/fx-core/tests/core/FxCore.test.ts
- packages/vscode-extension/src/extension.ts
- packages/vscode-extension/src/handlers.ts
Fix below issues:
Fix aad codelens doesn't show for v3
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/16740671
Fix aad codelens preview not work issue:
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/16750883
Fix bot sso template issue:
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/16750839
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/16750875
E2E TEST: N/A
> fix: codelens doesn't show for V3, bot template issue

- packages/vscode-extension/src/debug/teamsfxDebugProvider.ts
> chore(debug): filter local env from selection for remote launch

- packages/fx-core/src/component/developerPortalScaffoldUtils.ts
- packages/fx-core/src/component/resource/appManifest/utils/utils.ts
- packages/fx-core/tests/component/resource/appManifest/utils.test.ts
- also need to convert scope of Group Chat to all lowercase for appDefinition.
> chore: group chat

- packages/vscode-extension/src/extension.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/16775334
E2E TEST: N/A
> fix(vsc): popup upgrade prompt for v2 projects

- packages/vscode-extension/src/debug/commonUtils.ts
- packages/vscode-extension/src/debug/teamsfxDebugProvider.ts
Try get `M365_TITLE_ID` first from new m365 action.
> chore: support m365 title in vsc launch url

- packages/fx-core/templates/plugins/resource/aad/auth/bot/README.md
- packages/fx-core/templates/plugins/resource/aad/auth/bot/README.txt
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/16607755
> chore: upgrade the sdk to 2.2.0

- templates/scenarios/js/default-bot-message-extension/README.md
- templates/scenarios/js/default-bot/README.md
- templates/scenarios/js/message-extension/README.md
- templates/scenarios/js/non-sso-tab-default-bot/bot/README.md
- templates/scenarios/js/non-sso-tab-default-bot/tab/README.md
- templates/scenarios/js/non-sso-tab/README.md
- templates/scenarios/js/sso-tab/README.md
- templates/scenarios/ts/default-bot-message-extension/README.md
- templates/scenarios/ts/default-bot/README.md
- templates/scenarios/ts/message-extension/README.md
- templates/scenarios/ts/non-sso-tab-default-bot/bot/README.md
- templates/scenarios/ts/non-sso-tab-default-bot/tab/README.md
- templates/scenarios/ts/non-sso-tab/README.md
- templates/scenarios/ts/sso-tab/README.md
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/16774250
> docs: align commands with tree view in readme

- packages/fx-core/src/component/developerPortalScaffoldUtils.ts
- packages/fx-core/src/component/resource/appManifest/utils/utils.ts
- packages/fx-core/tests/component/developerPortalScaffoldUtils.test.ts
- packages/fx-core/tests/component/resource/appManifest/utils.test.ts
- not allow meeting extension if from TDP as we have a plan for meeting extension template later
> chore: not allow meeting extension

- packages/sdk/package-lock.json
- packages/sdk/package.json
- packages/sdk/test/unit/node/appCredential.spec.ts
- packages/sdk/test/unit/node/core/onBehalfOfUserCredential.spec.ts
E2E TEST: N/A
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/16805859
> chore: update msal-node version

- .github/workflows/sdk-e2e-test.yml
> fix: remove sync to TeamsFx portal

- templates/scenarios/csharp/workflow/Commands/HelloWorldCommandHandler.cs.tpl
> fix: typo in v3 workflow app

- .github/CODEOWNERS
add @sffamily  as package.nls.json code owner
> chore(codeowner): update

- templates/bot/csharp/workflow/Properties/launchSettings.json.tpl
> chore: comment out project profile in workflow bot

- packages/fx-core/src/component/coordinator/index.ts
- packages/fx-core/src/component/coordinator/summary.ts
- packages/fx-core/src/component/middleware/envMW.ts
- packages/fx-core/src/component/utils/envUtil.ts
- packages/fx-core/src/component/utils/pathUtils.ts
- packages/fx-core/src/core/FxCoreImplementV3.ts
- packages/fx-core/tests/component/coordinator.test.ts
- packages/fx-core/tests/component/envUtil.test.ts
- packages/vscode-extension/src/debug/taskTerminal/lifecycleTaskTerminal.ts
1. auto generate .env file if it does not exist for F5 command
2. EnvLoaderMW/EnvWriterMW can pass when .env file does not exist
> chore(core): env related change

- packages/fx-core/templates/plugins/resource/aad/auth/bot/README.txt
fix bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/16824290 by removing previous command handler
> docs(sso): update vs add sso doc for command bot

- packages/fx-core/src/component/resource/appManifest/utils.ts
Pick fix from [#6305](https://github.com/OfficeDev/TeamsFx/pull/6305) 
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/16809273
> chore: fix get manifest error for VS local debug

- packages/cli/tests/e2e/bot/NotificationBotHappyPathCommon.ts
- templates/bot/js/command-and-response/package.json
- templates/bot/js/notification-function-base/package.json
- templates/bot/js/notification-restify/package.json
- templates/bot/js/workflow/package.json
- templates/bot/ts/command-and-response/package.json
- templates/bot/ts/notification-function-base/package.json
- templates/bot/ts/notification-restify/package.json
- templates/bot/ts/workflow/package.json
> fix: update bot template package.json

- templates/bot/js/notification-restify/src/index.js
- templates/bot/js/notification-trigger-http/src/httpTrigger.js
- templates/bot/js/notification-trigger-timer/src/timerTrigger.js
- templates/bot/ts/notification-restify/src/index.ts
- templates/bot/ts/notification-trigger-http/src/httpTrigger.ts
- templates/bot/ts/notification-trigger-timer/src/timerTrigger.ts
- templates/scenarios/js/notification-http-timer-trigger/src/httpTrigger.js
- templates/scenarios/js/notification-http-timer-trigger/src/timerTrigger.js
- templates/scenarios/js/notification-http-trigger/src/httpTrigger.js
- templates/scenarios/js/notification-restify/src/index.js
- templates/scenarios/js/notification-timer-trigger/src/timerTrigger.js
- templates/scenarios/ts/notification-http-timer-trigger/src/httpTrigger.ts
- templates/scenarios/ts/notification-http-timer-trigger/src/timerTrigger.ts
- templates/scenarios/ts/notification-http-trigger/src/httpTrigger.ts
- templates/scenarios/ts/notification-restify/src/index.ts
- templates/scenarios/ts/notification-timer-trigger/src/timerTrigger.ts
Add code snippet samples to template comments about notifying individual person.
Include all notification-related templates.
Workitem: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/16937564/
> chore(template): add comment about notifying individual person

- templates/scenarios/js/m365-message-extension/web.config
E2E TEST: N/A
Manually tested.
> fix(m365-me): fix server not started after deployment

- packages/fx-core/src/component/developerPortalScaffoldUtils.ts
- packages/fx-core/src/core/FxCoreImplementV3.ts
- packages/fx-core/src/core/environment.ts
- packages/fx-core/tests/component/developerPortalScaffoldUtils.test.ts
- update folder/file name to match latest template
> chore: update folder/file name to match latest template

- packages/sdk/README.md
> docs(sdk): fix syntax error

- packages/fx-core/tests/common/deps-checker/cases/vxTestApp.it.ts
Fix test case on macOS for this PR: https://github.com/OfficeDev/TeamsFx/pull/7209
> chore: fix vxTestApp test on macOS

- packages/fx-core/src/component/driver/file/updateEnv.ts
> fix(debug): fix file/updateEnv handling boolean args

- packages/fx-core/templates/core/v3Migration/js.ts.app.yml
- packages/fx-core/tests/core/middleware/testAssets/v3Migration/jsFunctionBot/expectedResult/js.app.yml
- packages/fx-core/tests/core/middleware/testAssets/v3Migration/jsFunctionBot/expectedResult/ts.app.yml
- packages/fx-core/tests/core/middleware/testAssets/v3Migration/jsNonSsoTab/expectedResult/js.app.yml
- packages/fx-core/tests/core/middleware/testAssets/v3Migration/jsNonSsoTab/expectedResult/ts.app.yml
- packages/fx-core/tests/core/middleware/testAssets/v3Migration/jsSsoTab/expectedResult/js.app.yml
- packages/fx-core/tests/core/middleware/testAssets/v3Migration/jsSsoTab/expectedResult/ts.app.yml
- packages/fx-core/tests/core/middleware/testAssets/v3Migration/jsTabWithApi/expectedResult/js.app.yml
- packages/fx-core/tests/core/middleware/testAssets/v3Migration/jsTabWithApi/expectedResult/ts.app.yml
- packages/fx-core/tests/core/middleware/testAssets/v3Migration/jsWebappBot/expectedResult/js.app.yml
- packages/fx-core/tests/core/middleware/testAssets/v3Migration/jsWebappBot/expectedResult/ts.app.yml
- packages/fx-core/tests/core/middleware/testAssets/v3Migration/jsWebappBotId/expectedResult/js.app.yml
- packages/fx-core/tests/core/middleware/testAssets/v3Migration/jsWebappBotId/expectedResult/ts.app.yml
> fix: wrong arm help link in migrated yaml

- packages/vscode-extension/src/debug/teamsfxDebugProvider.ts
@microsoft/teamsfx-cli	v1.2.2-rc.1
@microsoft/teamsfx-core	v1.23.0-rc.1
ms-teams-vscode-extension	v4.2.2-rc.1
> fix(m365): fix m365 v2 launch

- packages/fx-core/src/core/middleware/utils/v3MigrationUtils.ts
> fix: fix upgrade dialog message as no args

- packages/vscode-extension/src/extension.ts
Related bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/16846121
E2E TEST: N/A
> fix(vsc): upgrade detection registration

- packages/vscode-extension/src/handlers.ts
Fix https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/17061743/.
E2E TEST: N/A
> fix(debug): fix get-func-path empty if funcCoreTools settings unchecked

- packages/fx-core/templates/core/v3Migration/upgradeReport.md
The changes to `aad.manifest.template.json` only happens when this file exists
> docs: mention AAD changes only happens when manifest exists

- packages/vscode-extension/PRERELEASE.md
This will appear after the user installed pre-release in VSCode.
> docs: pre-release changelog

- packages/fx-core/src/common/samples-config-v3.json
ADO: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/17060945
E2E TEST: NA
> fix: download sample fail with PathNotExistError

- templates/scenarios/js/default-bot-message-extension/index.js
- templates/scenarios/js/default-bot/index.js
- templates/scenarios/js/m365-message-extension/index.js
- templates/scenarios/js/message-extension/index.js
- templates/scenarios/js/non-sso-tab-default-bot/bot/index.js
- templates/scenarios/ts/default-bot-message-extension/index.ts
- templates/scenarios/ts/default-bot/index.ts
- templates/scenarios/ts/m365-message-extension/index.ts
- templates/scenarios/ts/message-extension/index.ts
- templates/scenarios/ts/non-sso-tab-default-bot/bot/index.ts
sync with https://github.com/OfficeDev/TeamsFx/pull/7274
> chore(template): update bot template to use cloudadapter

- templates/bot/js/notification-function-base/src/internal/responseWrapper.js
- templates/bot/ts/notification-function-base/src/internal/responseWrapper.ts
- templates/scenarios/js/notification-http-timer-trigger/src/internal/responseWrapper.js
- templates/scenarios/js/notification-http-trigger/src/internal/responseWrapper.js
- templates/scenarios/js/notification-timer-trigger/src/internal/responseWrapper.js
- templates/scenarios/ts/notification-http-timer-trigger/src/internal/responseWrapper.ts
- templates/scenarios/ts/notification-http-trigger/src/internal/responseWrapper.ts
- templates/scenarios/ts/notification-timer-trigger/src/internal/responseWrapper.ts
Fix [Bug 17059077](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/17059077): Notification Bot - Card Action does not replace Adaptive Card
E2E TEST: N/A
> fix: function bot response wrapper

- packages/fx-core/src/component/debugHandler/bot.ts
- packages/fx-core/src/component/resource/botService/appStudio/appStudioClient.ts
> chore: remove double get

- packages/fx-core/src/component/coordinator/index.ts
chore: fix capabilities telemetry
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/16536623
> chore: fix capabilities telemetry

- packages/fx-core/resource/package.nls.json
- packages/fx-core/src/component/driver/deploy/spfx/error/noValidAppCatelogError.ts
ADO: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/16987765
E2E TEST: NA
> fix: update wording to avoid outdated yml file string

- packages/fx-core/templates/core/v3Migration/upgradeReport.md
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/17061452
Some users do not notice there're some changes to the development flow, move what's changed section above and explicitly tell users to read the content when meet errors.
> chore: make changes to existing dev flow more visible

- Localize/loc/cs/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/cs/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/de/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/de/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/es/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/es/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/fr/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/fr/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/it/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/it/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/ja/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/ja/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/ko/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/ko/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/pl/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/pl/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/pt-BR/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/pt-BR/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/ru/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/ru/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/tr/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/tr/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/zh-Hans/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/zh-Hans/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/zh-Hant/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/zh-Hant/packages/vscode-extension/package.nls.json.lcl
LEGO: Pull request from juno/hb_fd34cb3d-1ea5-4a7c-8a66-721a44a97af3_20230212154554763 to dev with localized lcls
> chore(localization): [LEGO] Pull request from juno/hb_fd34cb3d-1ea5-4a7c-8a66-721a44a97af3_20230212154554763 to dev

- packages/cli/src/constants.ts
- packages/cli/src/utils.ts
- packages/cli/tests/e2e/commonUtils.ts
- packages/cli/tests/e2e/solution/SSOTabE2ETestWithAADManifestEnabled.tests.ts
- packages/cli/tests/unit/cmds/update.tests.ts
E2E TEST: https://github.com/OfficeDev/TeamsFx/actions/runs/4141994970
> test: update cli command with aad manifest file path

- packages/vscode-extension/package.json
As isConfigUnifyEnabled feature flag has been removed from https://github.com/OfficeDev/TeamsFx/pull/5401
Need to update context menu condition
For issue: https://github.com/OfficeDev/TeamsFx/issues/7410
> fix: update teams app context menu

- packages/fx-core/src/component/driver/teamsApp/publishAppPackage.ts
try-catch-finally to make sure the progress always be stopped.
For p1 bug: 17146251
> fix: stop publish progress

- packages/vscode-extension/src/handlers.ts
- packages/vscode-extension/test/extension/handlers.test.ts
bug: https://dev.azure.com/msazure/Microsoft%20Teams%20Extensibility/_workitems/edit/17116425
E2E TEST: N/A
> fix(vsc): handle upgrade error

- packages/fx-core/src/component/driver/teamsApp/configure.ts
- packages/fx-core/src/component/driver/teamsApp/create.ts
- packages/fx-core/tests/component/driver/teamsApp/create.test.ts
> chore: remove summary

- packages/cli/package-lock.json
- packages/fx-core/package-lock.json
- packages/fx-core/package.json
Remove the deprecated package (@types/jwt-decode).
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/17072551
> chore: audit and remove deprecated

- templates/scenarios/js/m365-message-extension/package.json.tpl
- templates/scenarios/ts/m365-message-extension/package.json.tpl
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/17170408
> chore: upgrade botbuilder version in m365 me template

- packages/fx-core/src/component/driver/teamsApp/createAppPackage.ts
aka link name should be updated to zipAppPackage, as this action name has been changed.
> fix: update link name

- packages/sdk/README.md
- templates/bot/js/notification-function-base/src/internal/responseWrapper.js
- templates/bot/ts/notification-function-base/src/internal/responseWrapper.ts
- templates/scenarios/js/notification-http-trigger/src/internal/responseWrapper.js
- templates/scenarios/js/notification-timer-trigger/src/internal/responseWrapper.js
- templates/scenarios/ts/notification-http-timer-trigger/src/internal/responseWrapper.ts
- templates/scenarios/ts/notification-http-trigger/src/internal/responseWrapper.ts
- templates/scenarios/ts/notification-timer-trigger/src/internal/responseWrapper.ts
> docs: update README and comments in templates

- packages/fx-core/src/common/samples.ts
- packages/fx-core/tests/common/samples.test.ts
ADO: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/17094401
E2E TEST: UT added
> fix: sample url is wrong for external samples in v3

- packages/fx-core/src/core/middleware/projectMigratorV3.ts
- packages/fx-core/tests/core/middleware/projectMigrationV3.test.ts
- packages/vscode-extension/src/extension.ts
1. Set upgrade button to default
2. Remove migration v3 flag, using v3 flag instead.
> chore(migration): update notification

- packages/fx-core/src/component/debugHandler/bot.ts
- packages/fx-core/src/component/resource/botService/appStudio/appStudioClient.ts
- packages/fx-core/src/component/resource/botService/botRegistration/localBotRegistration.ts
@microsoft/teamsfx-cli	v1.2.2-rc.1
@microsoft/teamsfx-core	v1.23.0-rc.1
ms-teams-vscode-extension	v4.2.2-rc.1
> chore(debug): add teams channel to create/update bot request body

- packages/vscode-extension/package.json
- packages/vscode-extension/src/extension.ts
Fix https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/16555275.
> chore(m365): expose upgrade command for non-teamsfx project

- .github/workflows/cd.yml
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/17202975
commit an issue to vsce team
https://github.com/microsoft/vscode-vsce/issues/834
> chore: update version number before vsce package

- .github/workflows/cd.yml
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/17214765
> chore: set daily v5 bits keep test aikey

- templates/scenarios/ts/spfx-tab/src/README.md
ADO: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/17169395
E2E TEST: NA
> fix: launch.json directory is not updated for v3

- templates/scenarios/js/m365-message-extension/.vscode/launch.json
- templates/scenarios/js/m365-message-extension/.vscode/tasks.json
- templates/scenarios/js/m365-message-extension/teamsapp.local.yml.tpl
- templates/scenarios/js/m365-message-extension/teamsapp.yml.tpl
- templates/scenarios/js/m365-tab/.vscode/launch.json
- templates/scenarios/js/m365-tab/.vscode/tasks.json
- templates/scenarios/js/m365-tab/teamsapp.local.yml.tpl
- templates/scenarios/js/m365-tab/teamsapp.yml.tpl
- templates/scenarios/ts/m365-message-extension/.vscode/launch.json
- templates/scenarios/ts/m365-message-extension/.vscode/tasks.json
- templates/scenarios/ts/m365-message-extension/teamsapp.local.yml.tpl
- templates/scenarios/ts/m365-message-extension/teamsapp.yml.tpl
- templates/scenarios/ts/m365-tab/.vscode/launch.json
- templates/scenarios/ts/m365-tab/.vscode/tasks.json
- templates/scenarios/ts/m365-tab/teamsapp.local.yml.tpl
- templates/scenarios/ts/m365-tab/teamsapp.yml.tpl
- add m365Title/acquire in yml template
- remove install in teams task
> chore(m365): use m365Title/acquire action

- templates/scenarios/js/command-and-response/README.md
- templates/scenarios/js/notification-http-timer-trigger/README.md
- templates/scenarios/js/notification-http-trigger/README.md
- templates/scenarios/js/notification-restify/README.md
- templates/scenarios/js/notification-timer-trigger/README.md
- templates/scenarios/js/workflow/README.md
- templates/scenarios/ts/command-and-response/README.md
- templates/scenarios/ts/notification-http-timer-trigger/README.md
- templates/scenarios/ts/notification-http-trigger/README.md
- templates/scenarios/ts/notification-restify/README.md
- templates/scenarios/ts/notification-timer-trigger/README.md
- templates/scenarios/ts/workflow/README.md
Fix [Bug 17067763](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/17067763): [V5] bot readme:
- Update folder structure
- Update aka link
E2E TEST: N/A
> docs: update readme for v5 node bot templates

- packages/fx-core/src/component/resource/appManifest/appManifest.ts
bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_sprints/taskboard/AuthAndData/Microsoft%20Teams%20Extensibility/CY23-2.2?workitem=17260385
> perf(collaboration): update logic for 404 error

- packages/vscode-extension/src/handlers.ts
- packages/vscode-extension/test/extension/handlers.test.ts
bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_sprints/taskboard/AuthAndData/Microsoft%20Teams%20Extensibility/CY23-2.2?workitem=17259927
> perf(collaboration): show error message only once in collaboration

- packages/fx-core/src/component/generator/utils.ts
- packages/fx-core/tests/component/generator/generator.test.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_sprints/taskboard/Compute%20Team/Microsoft%20Teams%20Extensibility/CY23-2.2?workitem=17264435
> chore: polish generator utils and tests

- packages/fx-core/src/component/constant/commonConstant.ts
- packages/fx-core/src/component/driver/script/dotnetBuildDriver.ts
- packages/fx-core/src/component/driver/script/npmBuildDriver.ts
- packages/fx-core/src/component/driver/script/npxBuildDriver.ts
- packages/fx-core/src/component/driver/script/scriptDriver.ts
> chore: add telemetry for script driver and change component name 

- packages/vscode-extension/src/handlers.ts
- packages/vscode-extension/test/extension/handlers.test.ts
Related bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/17214673
E2E TEST: N/A
> fix(vsc): aka links

- packages/vscode-extension/package-lock.json
- packages/vscode-extension/package.json
- packages/vscode-extension/src/constants.ts
- packages/vscode-extension/src/utils/commonUtils.ts
- packages/vscode-extension/test/extension/commonUtils.test.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/17061759
E2E TEST: N/A
> fix(vsc): app name not displayed in v3

- packages/fx-core/src/component/driver/teamsApp/publishAppPackage.ts
> fix: end progress handler

- Localize/loc/zh-Hant/packages/vscode-extension/package.nls.json.lcl
LEGO: Pull request from juno/hb_fd34cb3d-1ea5-4a7c-8a66-721a44a97af3_20230226154738748 to dev with localized lcls
> chore(localization): [LEGO] Pull request from juno/hb_fd34cb3d-1ea5-4a7c-8a66-721a44a97af3_20230226154738748 to dev

- packages/vscode-extension/package-lock.json
- packages/vscode-extension/package.json
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/17293497
> chore(vsc): upgrade jscodeshift

- packages/fx-core/templates/plugins/resource/aad/auth/bot/README.txt
fix bug
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/17335183
> docs: revert sdk for vs to 1.1.0

- packages/fx-core/src/core/middleware/projectMigratorV3.ts
- packages/fx-core/src/core/middleware/utils/debug/debugV3MigrationUtils.ts
- packages/fx-core/tests/core/middleware/testAssets/v3Migration/happyPath/.fx/configs/projectSettings.json
Fix https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/17220116.
> chore(debug-upgrade): add remote launch for m365 projects

- templates/scenarios/js/default-bot-message-extension/README.md
- templates/scenarios/js/default-bot/README.md
- templates/scenarios/js/message-extension/README.md
- templates/scenarios/js/non-sso-tab-default-bot/bot/README.md
- templates/scenarios/js/non-sso-tab-default-bot/tab/README.md
- templates/scenarios/js/non-sso-tab/README.md
- templates/scenarios/js/sso-tab/README.md
- templates/scenarios/ts/default-bot-message-extension/README.md
- templates/scenarios/ts/default-bot/README.md
- templates/scenarios/ts/message-extension/README.md
- templates/scenarios/ts/non-sso-tab-default-bot/bot/README.md
- templates/scenarios/ts/non-sso-tab-default-bot/tab/README.md
- templates/scenarios/ts/non-sso-tab/README.md
- templates/scenarios/ts/sso-tab/README.md
- add provision and deploy for preview local
- remove "teamsfx account set --subscription"
- add --env for provision and deploy remote
Fix https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/17169740.
> chore(v3): update cli section in templates README

- templates/scenarios/js/m365-message-extension/README.md
- templates/scenarios/js/m365-tab/README.md
- templates/scenarios/ts/m365-message-extension/README.md
- templates/scenarios/ts/m365-tab/README.md
- remove manual steps of installing app in teams
> chore(v3): update m365 templates readme

- packages/fx-core/src/component/resource/appManifest/utils/ManifestUtils.ts
For bug 17335561
Related PR: https://github.com/OfficeDev/TeamsFx/pull/5454
> chore: remove hard-code logic for valid domains

- packages/cli/src/cmds/provision.ts
- packages/cli/tests/e2e/manifest/provision.tests.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/17224596
> chore(cli): hide provision manifest in V3

- templates/scenarios/common/init-debug-vsc-bot/{%dotVscodeFolderName%}/tasks.json
- templates/scenarios/js/command-and-response/.vscode/tasks.json
- templates/scenarios/js/default-bot-message-extension/.vscode/tasks.json
- templates/scenarios/js/default-bot/.vscode/tasks.json
- templates/scenarios/js/m365-message-extension/.vscode/tasks.json
- templates/scenarios/js/message-extension/.vscode/tasks.json
- templates/scenarios/js/non-sso-tab-default-bot/.vscode/tasks.json
- templates/scenarios/js/notification-http-timer-trigger/.vscode/tasks.json
- templates/scenarios/js/notification-http-trigger/.vscode/tasks.json
- templates/scenarios/js/notification-restify/.vscode/tasks.json
- templates/scenarios/js/notification-timer-trigger/.vscode/tasks.json
- templates/scenarios/js/workflow/.vscode/tasks.json
- templates/scenarios/ts/command-and-response/.vscode/tasks.json
- templates/scenarios/ts/default-bot-message-extension/.vscode/tasks.json
- templates/scenarios/ts/default-bot/.vscode/tasks.json
- templates/scenarios/ts/m365-message-extension/.vscode/tasks.json
- templates/scenarios/ts/message-extension/.vscode/tasks.json
- templates/scenarios/ts/non-sso-tab-default-bot/.vscode/tasks.json
- templates/scenarios/ts/notification-http-timer-trigger/.vscode/tasks.json
- templates/scenarios/ts/notification-http-trigger/.vscode/tasks.json
- templates/scenarios/ts/notification-restify/.vscode/tasks.json
- templates/scenarios/ts/notification-timer-trigger/.vscode/tasks.json
- templates/scenarios/ts/workflow/.vscode/tasks.json
Reverts OfficeDev/TeamsFx#7915
> chore(template): Revert "change ngrok to basis in V5 templates"

- packages/fx-core/src/component/driver/botAadApp/create.ts
- packages/fx-core/tests/component/driver/botAadApp/create.test.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/17292555
> chore: fix wrong boolean exp

- packages/vscode-extension/package.json
This is only the UI change. Code cleanup is a hard work and will be considered in the future.
Fix https://msazure.visualstudio.com/9660fff2-2363-48b0-9e15-64df2283e932/_workitems/edit/16587559.
> chore: remove prerequisite extension settings

- Localize/loc/cs/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/cs/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/de/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/de/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/es/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/es/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/fr/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/fr/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/it/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/it/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/ja/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/ja/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/ko/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/ko/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/pl/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/pl/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/pt-BR/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/pt-BR/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/ru/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/ru/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/tr/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/tr/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/zh-Hans/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/zh-Hans/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/zh-Hant/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/zh-Hant/packages/vscode-extension/package.nls.json.lcl
LEGO: Pull request from juno/hb_fd34cb3d-1ea5-4a7c-8a66-721a44a97af3_20230301154720286 to dev with localized lcls
> chore(localization): [LEGO] Pull request from juno/hb_fd34cb3d-1ea5-4a7c-8a66-721a44a97af3_20230301154720286 to dev

- packages/fx-core/src/component/resource/spfx/depsChecker/generatorChecker.ts
- packages/fx-core/src/component/resource/spfx/depsChecker/yoChecker.ts
- packages/fx-core/src/component/resource/spfx/error.ts
- packages/fx-core/src/component/resource/spfx/utils/utils.ts
- packages/fx-core/tests/plugins/resource/spfx/depsChecker/generatorChecker.test.ts
- packages/fx-core/tests/plugins/resource/spfx/depsChecker/yoChecker.test.ts
- add npm commands to find latest version and currently installed version globally.
> chore: npm related commands for spfx scaffolding

- packages/fx-core/resource/package.nls.json
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/17278356?src=WorkItemMention&src-action=artifact_link
> chore(ui): rename SPFx description

- packages/cli/src/cmds/preview/constants.ts
- packages/cli/src/cmds/preview/previewEnv.ts
- packages/cli/tests/unit/cmds/preview/previewEnv.tests.ts
- packages/fx-core/src/common/m365/packageService.ts
- packages/fx-core/src/component/driver/m365/acquire.ts
- packages/fx-core/tests/common/m365/packageService.test.ts
- packages/fx-core/tests/component/driver/m365/acquire.test.ts
- packages/vscode-extension/src/debug/commonUtils.ts
- packages/vscode-extension/src/debug/teamsfxDebugProvider.ts
- templates/scenarios/js/m365-message-extension/teamsapp.local.yml.tpl
- templates/scenarios/js/m365-message-extension/teamsapp.yml.tpl
- templates/scenarios/js/m365-tab/teamsapp.local.yml.tpl
- templates/scenarios/js/m365-tab/teamsapp.yml.tpl
- templates/scenarios/ts/m365-message-extension/teamsapp.local.yml.tpl
- templates/scenarios/ts/m365-message-extension/teamsapp.yml.tpl
- templates/scenarios/ts/m365-tab/teamsapp.local.yml.tpl
- templates/scenarios/ts/m365-tab/teamsapp.yml.tpl
- remove calling launchInfo api in sideloading
- get title id and app id from status api in sideloading
- persist M365_APP_ID in m365Title/acquire action
- use M365_APP_ID to launch office
- update templates comment
- update cli preview to use title
> chore(m365): update m365 sideloading

- packages/cli/src/cmds/preview/errors.ts
- packages/cli/src/cmds/preview/previewEnv.ts
Fix https://msazure.visualstudio.com/9660fff2-2363-48b0-9e15-64df2283e932/_workitems/edit/17169550.
> chore: improve cli preview error message for not provisioned

- packages/fx-core/src/component/generator/utils.ts
ADO: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/17357958
E2E TEST: ProvisionTodoListM365.tests.ts
> fix: download sample fail

- packages/fx-core/src/common/local/constants.ts
- packages/vscode-extension/src/debug/taskTerminal/baseTunnelTaskTerminal.ts
- packages/vscode-extension/src/debug/taskTerminal/devTunnelTaskTerminal.ts
- packages/vscode-extension/src/debug/taskTerminal/lifecycleTaskTerminal.ts
- packages/vscode-extension/src/debug/taskTerminal/ngrokTunnelTaskTerminal.ts
Detail: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_dashboards/dashboard/b7e7b190-a7fb-4c70-89f1-e63796c991c5
> chore(localdebug): add telemetry to basis tasks

- Localize/loc/cs/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/cs/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/de/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/de/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/es/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/es/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/fr/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/fr/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/it/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/it/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/ja/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/ja/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/ko/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/ko/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/pl/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/pl/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/pt-BR/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/pt-BR/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/ru/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/ru/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/tr/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/tr/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/zh-Hans/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/zh-Hans/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/zh-Hant/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/zh-Hant/packages/vscode-extension/package.nls.json.lcl
LEGO: Pull request from juno/hb_fd34cb3d-1ea5-4a7c-8a66-721a44a97af3_20230305154631792 to dev with localized lcls
> chore(localization): [LEGO] Pull request from juno/hb_fd34cb3d-1ea5-4a7c-8a66-721a44a97af3_20230305154631792 to dev

- packages/fx-core/src/common/telemetry.ts
- packages/fx-core/src/component/coordinator/index.ts
- packages/fx-core/src/component/utils/envUtil.ts
- packages/fx-core/src/component/utils/metadataUtil.ts
- packages/fx-core/tests/component/coordinator.test.ts
- packages/fx-core/tests/component/envUtil.test.ts
- packages/fx-core/tests/component/util/metadataUtil.test.ts
- packages/fx-core/tests/core/collaborator.test.ts
- packages/fx-core/tests/core/utils.ts
chore: add metadata event
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/17169360
> chore: add metadata event

- packages/vscode-extension/src/debug/taskTerminal/baseTunnelTaskTerminal.ts
- packages/vscode-extension/src/debug/taskTerminal/devTunnelTaskTerminal.ts
detail: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/17358463
> chore(localdebug): delete the dev tunnel if it is not deleted in the last F5

- .github/workflows/cd.yml
prerelease now release the alpha pkgs, should publish after update AI key
> chore: publish prerelease alpha pkgs with production AI key

- packages/fx-core/src/common/samples-config-v3.json
ADO: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/17451070
After:
> fix: remove duplicated sample config for org user sample

- packages/vscode-extension/src/debug/teamsfxDebugProvider.ts
- remove v2 logic
- resolve "teamsAppId" and "teamsAppInternalId"
Fix https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/17180728.
Templates change: https://github.com/OfficeDev/TeamsFx/pull/7982
Samples change: https://github.com/OfficeDev/TeamsFx-Samples/pull/716
> chore(debug): simplify debug provider

- Localize/loc/cs/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/cs/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/de/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/de/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/es/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/es/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/fr/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/fr/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/it/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/it/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/ja/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/ja/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/ko/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/ko/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/pl/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/pl/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/pt-BR/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/pt-BR/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/ru/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/ru/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/tr/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/tr/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/zh-Hans/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/zh-Hans/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/zh-Hant/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/zh-Hant/packages/vscode-extension/package.nls.json.lcl
LEGO: Pull request from juno/hb_fd34cb3d-1ea5-4a7c-8a66-721a44a97af3_20230308154604546 to dev with localized lcls
> chore(localization): [LEGO] Pull request from juno/hb_fd34cb3d-1ea5-4a7c-8a66-721a44a97af3_20230308154604546 to dev

- packages/cli/tests/e2e/debug/DebugCommandAndResponse.tests.ts
- packages/cli/tests/e2e/debug/DebugSsoTab.tests.ts
- packages/cli/tests/e2e/debug/utility.ts
- packages/cli/tests/e2e/m365/DebugM365MessageExtension.tests.ts
- packages/cli/tests/e2e/m365/DeployM365MessageExtension.tests.ts
- packages/cli/tests/e2e/m365/DeployM365Tab.tests.ts
- add tests for m365 remote deployment
- add debug test for command-and-response
- add more validations
- add author
E2E TEST: https://github.com/OfficeDev/TeamsFx/actions/runs/4370827999
> test(e2e-v3): add tests for m365 remote deployment

- packages/cli/tests/e2e/spfx/CreateSPFxProject.tests.ts
> fix: spfx e2e test fail

- .github/workflows/e2e-test.yml
- .github/workflows/sdk-e2e-test.yml
> chore: update sdk-e2e workflow

- templates/scenarios/js/sso-tab/README.md
- templates/scenarios/ts/sso-tab/README.md
- templates/tab/js/default/README.md
- templates/tab/ts/default/README.md
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/17403430
> docs: add note for auth code flow limitations on mobile

- packages/vscode-extension/package.json
- packages/vscode-extension/src/extension.ts
- packages/vscode-extension/src/handlers.ts
- packages/vscode-extension/src/treeview/treeViewManager.ts
- packages/vscode-extension/test/extension/handlers.test.ts
- packages/vscode-extension/test/extension/treeview/treeViewManager.test.ts
add manage collaborator button in env tree and remove command in development
> chore(migration): update UI for collaboration v3

- packages/fx-core/templates/core/v3Migration/spfx.app.yml
- packages/fx-core/tests/core/middleware/testAssets/v3Migration/spfxTab/expectedResult/app.yml
ADO:
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/17497981
E2E TEST: NA
> fix: publish failed with migrated spfx project

- packages/fx-core/src/component/generator/error.ts
- packages/fx-core/src/component/generator/generator.ts
- packages/fx-core/src/component/generator/generatorAction.ts
- packages/fx-core/src/component/generator/utils.ts
- packages/fx-core/tests/component/generator/generator.test.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/17420379/
> chore: no error message for cancel downloading

- Localize/loc/cs/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/cs/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/de/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/de/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/es/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/es/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/fr/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/fr/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/it/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/it/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/ja/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/ja/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/ko/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/ko/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/pl/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/pl/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/pt-BR/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/pt-BR/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/ru/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/ru/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/tr/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/tr/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/zh-Hans/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/zh-Hans/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/zh-Hant/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/zh-Hant/packages/vscode-extension/package.nls.json.lcl
LEGO: Pull request from juno/hb_fd34cb3d-1ea5-4a7c-8a66-721a44a97af3_20230312144639450 to dev with localized lcls
> chore(localization): [LEGO] Pull request from juno/hb_fd34cb3d-1ea5-4a7c-8a66-721a44a97af3_20230312144639450 to dev

- packages/fx-core/package.json
- packages/fx-core/src/component/generator/officeAddin/generator.ts
- packages/fx-core/src/component/generator/officeAddin/helperMethods.ts
- packages/fx-core/tests/component/generator/officeAddinGenerator.test.ts
- templates/scenarios/ts/office-addin/README.md
> chore: move manifest.json to appPackage folder

- templates/scenarios/js/m365-tab/appPackage/manifest.json.tpl
- templates/scenarios/ts/m365-tab/appPackage/manifest.json.tpl
> fix(templates): remove "./" from icon path in manifest

- packages/vscode-extension/PRERELEASE.md
> docs: Changelog0314

- packages/vscode-extension/package.nls.json
- packages/vscode-extension/src/handlers.ts
- packages/vscode-extension/test/extension/handlers.test.ts
> feat: remove spfx guide in how-to-guide list

- packages/fx-core/src/component/generator/spfxGenerator.ts
- packages/fx-core/src/component/resource/spfx/depsChecker/generatorChecker.ts
- packages/fx-core/src/component/resource/spfx/depsChecker/yoChecker.ts
- packages/fx-core/src/component/resource/spfx/utils/question-helper.ts
- packages/fx-core/src/component/resource/spfx/utils/telemetryEvents.ts
- packages/fx-core/tests/component/generator/spfxGenerator.test.ts
- packages/fx-core/tests/plugins/resource/spfx/depsChecker/generatorChecker.test.ts
- packages/fx-core/tests/plugins/resource/spfx/depsChecker/yoChecker.test.ts
- packages/fx-core/tests/plugins/resource/spfx/unit/question-helper.test.ts
- install latest yeoman and sp generator package if user selects to let TTK install packages for them.
- TODO: error handling
> chore: spfx install local pacakges and scaffold using local pacakges

- packages/fx-core/src/component/generator/officeAddin/generator.ts
- packages/fx-core/tests/common/featureFlags.test.ts
- packages/fx-core/tests/common/local/localEnvManager.test.ts
- packages/fx-core/tests/common/tools.test.ts
- packages/fx-core/tests/component/components.test.ts
- packages/fx-core/tests/component/driver/arm/deploy.test.ts
- packages/fx-core/tests/component/driver/script/scriptDriver.test.ts
- packages/fx-core/tests/component/exisingTab.test.ts
- packages/fx-core/tests/component/feature/sql.test.ts
- packages/fx-core/tests/component/feature/sso.test.ts
- packages/fx-core/tests/component/feature/tab.test.ts
- packages/fx-core/tests/component/generator/officeAddinGenerator.test.ts
- packages/fx-core/tests/component/migrate.test.ts
- packages/fx-core/tests/component/questionv3.test.ts
- packages/fx-core/tests/component/resource/aadApp/unit/aadAppForTeamsImpl.test.ts
- packages/fx-core/tests/component/resource/appManifest/manifestUtils.test.ts
- packages/fx-core/tests/core/FxCore.test.ts
- packages/fx-core/tests/core/collaborator.test.ts
- packages/fx-core/tests/core/environment.test.ts
- packages/fx-core/tests/core/hooks.test.ts
- packages/fx-core/tests/core/middleware/EnvInfoMW.test.ts
- packages/fx-core/tests/core/middleware/ProjectSettingsLoaderMW.test.ts
- packages/fx-core/tests/core/middleware/ProjectSettingsWriterMW.test.ts
- packages/fx-core/tests/core/middleware/VideoFilterAppBlockerMW.test.ts
- packages/fx-core/tests/core/middleware/projectVersionChecker.test.ts
- packages/fx-core/tests/core/sample.test.ts
- packages/fx-core/tests/plugins/resource/appstudio/unit/buildv3.test.ts
- packages/fx-core/tests/plugins/solution/debug/solution.debug.scaffolding.test.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_sprints/taskboard/AuthAndData/Microsoft%20Teams%20Extensibility/CY23-3.1?workitem=17481819
> test: set v2 test cases with v3 flag turn off on fx-core

- .github/workflows/FunctionExtensionCI.yml
- .github/workflows/cd.yml
- .github/workflows/cd_trigger.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/docs.yml
- .github/workflows/dotnetsdk-ci.yml
- .github/workflows/e2e-test.yml
- .github/workflows/env-checker-ci-pr.yml
- .github/workflows/graph-toolkit-released.yml
- .github/workflows/lint-pr.yml
- .github/workflows/sdk-ci.yml
- .github/workflows/sdk-e2e-test.yml
- .github/workflows/simpleauthCI.yml
- .github/workflows/teamsjs-released.yml
- .github/workflows/unit-test.yml
- .github/workflows/vscode-marketplace.yml
> chore: fix github action warining

- packages/fx-core/src/component/provisionUtils.ts
Update switch tenant error message.
Fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/17470201/
> chore: switch tenant

- packages/fx-core/src/common/local/constants.ts
- packages/fx-core/src/component/debug/util/launchNext.ts
- packages/vscode-extension/src/debug/constants.ts
Fix masked label and refine constants.
After:
Before:
Fix https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/17535346/
> fix: masked task label for v3

- templates/scenarios/common/office-addin/teamsapp.yml
> chore: add environmentFolderPath to common office add-in template

- packages/fx-core/src/common/constants.ts
- packages/fx-core/src/common/featureFlags.ts
- packages/fx-core/src/common/tools.ts
- packages/fx-core/src/component/code/spfxTabCode.ts
- packages/fx-core/src/component/feature/spfx.ts
- packages/fx-core/src/component/generator/spfxGenerator.ts
- packages/fx-core/src/component/resource/spfx/depsChecker/generatorChecker.ts
- packages/fx-core/src/component/resource/spfx/depsChecker/yoChecker.ts
- packages/fx-core/tests/component/feature/spfx.test.ts
- packages/fx-core/tests/component/generator/spfxGenerator.test.ts
- packages/fx-core/tests/plugins/resource/spfx/depsChecker/generatorChecker.test.ts
- packages/fx-core/tests/plugins/resource/spfx/depsChecker/yoChecker.test.ts
- packages/vscode-extension/package.json
- packages/vscode-extension/src/constants.ts
- packages/vscode-extension/src/utils/commonUtils.ts
- enable spfx decouple feature flag
- E2E TEST: https://github.com/OfficeDev/TeamsFx/actions/runs/4422747591
> feat: enable spfx decouple

- .github/workflows/e2e-test.yml
E2E TEST: https://github.com/OfficeDev/TeamsFx/actions/runs/4423193242
> fix(cli): e2e test pipeline

- packages/cli/src/cmds/add.ts
- packages/cli/src/cmds/capability.ts
- packages/cli/src/cmds/index.ts
- packages/cli/src/telemetry/cliTelemetryEvents.ts
- packages/cli/tests/unit/cmds/capability.tests.ts
CLI help:
Add web part:
E2E TEST: will add in another PR
> feat: enable add spfx web part in cli

- packages/fx-core/resource/package.nls.json
- packages/fx-core/src/component/resource/spfx/error.ts
- update message based on feedback from PM and UI
-
> chore: update spfx msg

- packages/fx-core/resource/package.nls.json
- packages/fx-core/src/core/collaborator.ts
- packages/fx-core/src/core/question.ts
- packages/fx-core/tests/core/collaborator.test.ts
Snapshot:
According discussion with Ellie, confirm window will not show if is default value
> chore(collaboration): add confirm manifest window

- packages/cli/src/cmds/permission.ts
- packages/cli/tests/e2e/collaboration/Permission.tests.ts
- packages/cli/tests/e2e/collaboration/PermissionSPFX.tests.ts
- packages/cli/tests/unit/cmds/permission.tests.ts
E2E Success run: https://github.com/OfficeDev/TeamsFx/actions/runs/4459646581
> chore(collaborator): update cli for v3 collaboration

- Localize/loc/cs/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/cs/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/de/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/de/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/es/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/es/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/fr/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/fr/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/it/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/it/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/ja/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/ja/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/ko/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/ko/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/pl/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/pl/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/pt-BR/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/pt-BR/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/ru/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/ru/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/tr/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/tr/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/zh-Hans/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/zh-Hans/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/zh-Hant/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/zh-Hant/packages/vscode-extension/package.nls.json.lcl
LEGO: Pull request from juno/hb_fd34cb3d-1ea5-4a7c-8a66-721a44a97af3_20230319144716468 to dev with localized lcls
> chore(localization): [LEGO] Pull request from juno/hb_fd34cb3d-1ea5-4a7c-8a66-721a44a97af3_20230319144716468 to dev

- packages/sdk-react/package-lock.json
- packages/sdk-react/package.json
> chore: update teamsfx-react version

- packages/cli/tests/e2e/spfx/CreateSPFxProject.tests.ts
- packages/cli/tests/utils/constants.ts
- packages/cli/tests/utils/executor.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/17534700
https://github.com/OfficeDev/TeamsFx/actions/runs/4434770400
> test(cli): add an e2e test executor

- packages/cli/src/cmds/index.ts
- packages/cli/tests/unit/cmds/index.tests.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/17564734
> chore(cli): hide teamsfx init command

- packages/fx-core/src/component/code/utils.ts
- packages/fx-core/src/component/provisionUtils.ts
- packages/fx-core/src/component/utils/envUtil.ts
- packages/fx-core/tests/component/envUtil.test.ts
1. adjust env priority:   `process.env` > `.env.dev` > `.env.dev.user`
2. script driver set env output command: `set-teamsfx-env key=value`
> chore(core): fix env priority issue

- packages/fx-core/src/component/resource/botService/botRegistration/localBotRegistration.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_sprints/taskboard/Compute%20Team/Microsoft%20Teams%20Extensibility/CY23-3.2?workitem=17602079
Reduce an unnecessary "Get Bot".
> chore: reduce an unnecessary get bot

- packages/fx-core/src/component/coordinator/index.ts
- packages/fx-core/tests/component/coordinator.test.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/17412232
> chore(vs): not show executed lifecycle deploy in vs

- templates/scenarios/ts/office-addin/README.md
ms-teams-vscode-extension	v4.2.5-rc.0 …
> chore: update Outlook version in add-in readme

- packages/vscode-extension/syntaxes/teamsfx-toolkit-output.tmLanguage
Related bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/17567115
E2E TEST: N/A
> fix(vsc): add rule for debug link

- packages/cli/src/yargsCommand.ts
- packages/cli/tests/unit/cmds/addApiConnection.tests.ts
- packages/cli/tests/unit/cmds/addCICD.tests.ts
- packages/cli/tests/unit/cmds/apply.tests.ts
- packages/cli/tests/unit/cmds/capability.tests.ts
- packages/cli/tests/unit/cmds/config.tests.ts
- packages/cli/tests/unit/cmds/deploy.tests.ts
- packages/cli/tests/unit/cmds/env.tests.ts
- packages/cli/tests/unit/cmds/init.tests.ts
- packages/cli/tests/unit/cmds/manifest.tests.ts
- packages/cli/tests/unit/cmds/new.tests.ts
- packages/cli/tests/unit/cmds/package.tests.ts
- packages/cli/tests/unit/cmds/permission.tests.ts
- packages/cli/tests/unit/cmds/preview/previewEnv.tests.ts
- packages/cli/tests/unit/cmds/provision.tests.ts
- packages/cli/tests/unit/cmds/publish.tests.ts
- packages/cli/tests/unit/cmds/resource.tests.ts
- packages/cli/tests/unit/cmds/update.tests.ts
- packages/cli/tests/unit/cmds/validate.tests.ts
- packages/cli/tests/unit/yargsCommand.tests.ts
- packages/fx-core/src/core/FxCoreImplementV3.ts
- packages/fx-core/src/core/middleware/utils/v3MigrationUtils.ts
- packages/fx-core/tests/core/middleware/projectMigrationV3.test.ts
- packages/server/package.json
- packages/vscode-extension/package.json
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/17619408
> chore: call version check in yargs command

- .github/workflows/cd.yml
ms-teams-vscode-extension	v4.2.5-rc.0 …
> chore: move file before check

- packages/cli/src/cmds/capability.ts
- packages/cli/tests/unit/cmds/capability.tests.ts
- packages/cli/tests/utils/executor.ts
- packages/fx-core/src/component/feature/spfx.ts
- packages/fx-core/src/component/generator/spfxGenerator.ts
- packages/fx-core/src/component/resource/spfx/utils/question-helper.ts
- packages/fx-core/src/component/resource/spfx/utils/questions.ts
- packages/fx-core/src/component/resource/spfx/utils/telemetryEvents.ts
- packages/fx-core/src/core/middleware/questionModel.ts
- packages/fx-core/tests/component/feature/spfx.test.ts
- packages/fx-core/tests/component/generator/spfxGenerator.test.ts
- packages/fx-core/tests/core/FxCore.test.ts
- packages/fx-core/tests/plugins/resource/spfx/unit/question-helper.test.ts
- fix cli help
- add telemetry if user using package lower than what we recommended
- E2E TEST: https://github.com/OfficeDev/TeamsFx/actions/runs/4507338268
> chore: spfx scaffolding cli help

- packages/fx-core/src/component/driver/botAadApp/create.ts
- packages/fx-core/src/component/driver/botAadApp/interface/createBotAadAppOutput.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_sprints/taskboard/Compute%20Team/Microsoft%20Teams%20Extensibility/CY23-3.2?workitem=17602832
Support new output interface.
> chore: botaad app output

- packages/cli/src/activate.ts
- packages/cli/src/cmds/deploy.ts
- packages/cli/src/cmds/provision.ts
- packages/cli/src/cmds/publish.ts
- packages/cli/src/resource/strings.json
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/17224596
> chore(cli): provision/deploy/publish strings

- templates/scenarios/common/init-debug-vsc-tab/teamsapp.local.yml
- templates/scenarios/js/dashboard-tab/teamsapp.local.yml.tpl
- templates/scenarios/js/m365-tab/teamsapp.local.yml.tpl
- templates/scenarios/js/non-sso-tab-default-bot/teamsapp.local.yml.tpl
- templates/scenarios/js/non-sso-tab/teamsapp.local.yml.tpl
- templates/scenarios/js/notification-http-timer-trigger/teamsapp.local.yml.tpl
- templates/scenarios/js/notification-http-trigger/teamsapp.local.yml.tpl
- templates/scenarios/js/notification-timer-trigger/teamsapp.local.yml.tpl
- templates/scenarios/js/sso-tab/teamsapp.local.yml.tpl
- templates/scenarios/ts/dashboard-tab/teamsapp.local.yml.tpl
- templates/scenarios/ts/m365-tab/teamsapp.local.yml.tpl
- templates/scenarios/ts/non-sso-tab-default-bot/teamsapp.local.yml.tpl
- templates/scenarios/ts/non-sso-tab/teamsapp.local.yml.tpl
- templates/scenarios/ts/notification-http-timer-trigger/teamsapp.local.yml.tpl
- templates/scenarios/ts/notification-http-trigger/teamsapp.local.yml.tpl
- templates/scenarios/ts/notification-timer-trigger/teamsapp.local.yml.tpl
- templates/scenarios/ts/sso-tab/teamsapp.local.yml.tpl
Related: https://github.com/OfficeDev/TeamsFx/pull/8156
Migration change will be in separate PR.
> chore(templates): use outputEnvVarNames in prerequisite/install

- packages/vscode-extension/src/utils/commonUtils.ts
- packages/vscode-extension/test/extension/commonUtils.test.ts
> chore(vsc): display preview icon on env node

- packages/cli/src/cmds/update.ts
- packages/cli/tests/unit/cmds/update.tests.ts
- packages/fx-core/src/core/FxCoreImplementV3.ts
- packages/fx-core/tests/core/FxCore.test.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_sprints/taskboard/AuthAndData/Microsoft%20Teams%20Extensibility/CY23-3.2?workitem=17630496
> chore(cli): implement update aad-app question model in cli

- .github/scripts/lint-pr.sh
- .github/workflows/lint-pr.yml
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_sprints/taskboard/AuthAndData/Microsoft%20Teams%20Extensibility/CY23-3.2?workitem=17630496
> chore: add yaml file lint in PR to check templates yaml file format

- packages/vscode-extension/package.json
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_sprints/taskboard/AuthAndData/Microsoft%20Teams%20Extensibility/CY23-3.2?workitem=17638552
> chore: ensure v3 only update aad app command pallate

- packages/fx-core/src/core/middleware/projectVersionChecker.ts
- packages/fx-core/tests/core/middleware/projectVersionChecker.test.ts
ms-teams-vscode-extension	v4.2.5-rc.0 …
> chore(versioncheck): update

- packages/vscode-extension/src/debug/taskTerminal/launchTeamsClientTerminal.ts
> chore: execute open teams web client without shell

- packages/vscode-extension/src/debug/taskTerminal/baseTaskTerminal.ts
- packages/vscode-extension/src/debug/taskTerminal/lifecycleTaskTerminal.ts
[Bug 17470111](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/17470111): [V3]error message no need show twice
E2E TEST: none
> fix(localdebug): avoid show error message twice

- packages/fx-core/src/component/driver/teamsApp/configure.ts
- packages/fx-core/src/component/resource/appManifest/appStudio.ts
only teamsApp/create action will output teams app id.
> chore: remove output of teamsApp/update action

- templates/scenarios/common/office-addin/env/.env.dev
- templates/scenarios/ts/office-addin/.gitignore
- templates/scenarios/ts/office-addin/env/.env.dev
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_sprints/taskboard/Teams%20Extensibility%20E2E%20Team/Microsoft%20Teams%20Extensibility/CY23-3.2?workitem=17754541
> chore: add gitignore to office addin template

- packages/fx-core/src/component/driver/teamsApp/validateAppPackage.ts
> chore: add full output logs to cli

- .github/scripts/fxcore-sync-up-version.js
- .github/scripts/pkg-version.sh
- .github/workflows/cd.yml
- packages/vscode-extension/PRERELEASE.md
- templates/scenarios/ts/office-addin/README.md
ms-teams-vscode-extension	v4.2.5-rc.0 …
> chore: update office addin readme

- packages/vscode-extension/src/debug/depsChecker/vscodeHelper.ts
detail: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/17533214
TODO: clean useless code in deps checker
E2E TEST: none
> fix(bi): remove activation event dotnet-check-skipped

- packages/dotnet-sdk/.gitignore
- packages/dotnet-sdk/src/TeamsFx.Test/Conversation/LocalFileStorageTest.cs
- packages/dotnet-sdk/src/TeamsFx/Conversation/LocalFileStorage.cs
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/17667257/
Ignore empty notification store. UT added.
E2E TEST: N/A
> fix: ignore empty notification store

- packages/vscode-extension/syntaxes/teamsfx-toolkit-output.tmLanguage
Related bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/17567115
E2E TEST: N/A
> fix(vsc): regex to match link

- packages/vscode-extension/src/debug/commonUtils.ts
- packages/vscode-extension/src/debug/teamsfxTaskProvider.ts
- packages/vscode-extension/src/handlers.ts
- packages/vscode-extension/test/extension/handlers.test.ts
To fix https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/17603544.
> chore(debug-upgrade): improve error message

- packages/cli/tests/commonlib/aadManager.ts
- packages/cli/tests/utils/azureHelper.ts
- packages/cli/tests/utils/cleaner.ts
- packages/cli/tests/utils/constants.ts
- packages/cli/tests/utils/m365TitleHelper.ts
- packages/cli/tests/utils/teamsAppHelper.ts
E2E TEST: https://github.com/OfficeDev/TeamsFx/actions/runs/4593486367
> refactor(cli): azure helper for clean up

- .github/workflows/lint-pr.yml
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_sprints/taskboard/AuthAndData/Microsoft%20Teams%20Extensibility/CY23-3.2?workitem=17433638
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_sprints/taskboard/AuthAndData/Microsoft%20Teams%20Extensibility/CY23-3.2?workitem=17433639
> docs: support list history for fix

- packages/server/src/serverConnection.ts
- packages/server/tests/serverConnections.test.ts
For bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/17711529
> chore: update server for build app package

- templates/scenarios/ts/sso-tab/teamsapp.local.yml.tpl
@microsoft/adaptivecards-tools	v1.3.1-beta.2023040704.0
@microsoft/teamsfx-api	v0.22.2-beta.2023040704.0
@microsoft/teamsfx-cli	v2.0.0-beta.2023040704.0
@microsoft/teamsfx-core	v2.0.0-beta.2023040704.0
@microsoft/teams-manifest	v0.0.10-beta.2023040704.0
@microsoft/metrics-ts	v0.0.4-beta.2023040704.0
@microsoft/teamsfx	v2.2.1-beta.2023040704.0
@microsoft/teamsfx-react	v3.0.0-beta.2023040704.0
ms-teams-vscode-extension	v4.99.0-beta.2023040704.0 …
> fix(template): fix writeToEnvironmentFile in sso-tab ts template

- templates/scenarios/ts/notification-restify/teamsapp.yml.tpl
@microsoft/adaptivecards-tools	v1.3.1-beta.2023041003.0
@microsoft/teamsfx-api	v0.22.2-beta.2023041003.0
@microsoft/teamsfx-cli	v2.0.0-beta.2023041003.0
@microsoft/teamsfx-core	v2.0.0-beta.2023041003.0
@microsoft/teams-manifest	v0.0.10-beta.2023041003.0
@microsoft/metrics-ts	v0.0.4-beta.2023041003.0
@microsoft/teamsfx	v2.2.1-beta.2023041003.0
@microsoft/teamsfx-react	v3.0.0-beta.2023041003.0
ms-teams-vscode-extension	v4.99.0-beta.2023041003.0 …
> fix: missing parameter in notification restify app yml

- templates/scenarios/js/default-bot-message-extension/README.md
- templates/scenarios/js/default-bot/README.md
- templates/scenarios/js/m365-message-extension/README.md
- templates/scenarios/js/message-extension/README.md
- templates/scenarios/js/non-sso-tab-default-bot/bot/README.md
- templates/scenarios/ts/default-bot-message-extension/README.md
- templates/scenarios/ts/default-bot/README.md
- templates/scenarios/ts/m365-message-extension/README.md
- templates/scenarios/ts/message-extension/README.md
- templates/scenarios/ts/non-sso-tab-default-bot/bot/README.md
@microsoft/adaptivecards-tools	v1.3.1-beta.2023041002.0
@microsoft/teamsfx-api	v0.22.2-beta.2023041002.0
@microsoft/teamsfx-cli	v2.0.0-beta.2023041002.0
@microsoft/teamsfx-core	v2.0.0-beta.2023041002.0
@microsoft/teams-manifest	v0.0.10-beta.2023041002.0
@microsoft/metrics-ts	v0.0.4-beta.2023041002.0
@microsoft/teamsfx	v2.2.1-beta.2023041002.0
@microsoft/teamsfx-react	v3.0.0-beta.2023041002.0
ms-teams-vscode-extension	v4.99.0-beta.2023041002.0 …
> docs(localdebug): add start local tunnel into cli preview steps

- packages/fx-core/src/component/driver/script/scriptDriver.ts
- packages/fx-core/src/core/middleware/questionModel.ts
@microsoft/adaptivecards-tools	v1.3.1-beta.2023041007.0
@microsoft/teamsfx-api	v0.22.2-beta.2023041007.0
@microsoft/teamsfx-cli	v2.0.0-beta.2023041007.0
@microsoft/teamsfx-core	v2.0.0-beta.2023041007.0
@microsoft/teams-manifest	v0.0.10-beta.2023041007.0
@microsoft/metrics-ts	v0.0.4-beta.2023041007.0
@microsoft/teamsfx	v2.2.1-beta.2023041007.0
@microsoft/teamsfx-react	v3.0.0-beta.2023041007.0
ms-teams-vscode-extension	v4.99.0-beta.2023041007.0 …
> chore(core): refine some logs

- packages/sdk-react/package-lock.json
- packages/sdk-react/package.json
> fix: deployment issues related to teamsfx-react

- packages/fx-core/resource/package.nls.json
- packages/fx-core/src/component/code/utils.ts
- packages/fx-core/src/error/script.ts
- packages/fx-core/tests/component/driver/script/scriptDriver.test.ts
@microsoft/adaptivecards-tools	v1.3.1-beta.2023041008.0
@microsoft/teamsfx-api	v0.22.2-beta.2023041008.0
@microsoft/teamsfx-cli	v2.0.0-beta.2023041008.0
@microsoft/teamsfx-core	v2.0.0-beta.2023041008.0
@microsoft/teams-manifest	v0.0.10-beta.2023041008.0
@microsoft/metrics-ts	v0.0.4-beta.2023041008.0
@microsoft/teamsfx	v2.2.1-beta.2023041008.0
@microsoft/teamsfx-react	v3.0.0-beta.2023041008.0
ms-teams-vscode-extension	v4.99.0-beta.2023041008.0 …
> fix(core): script driver error messasge on prerelease

- packages/vscode-extension/src/codeLensProvider.ts
- packages/vscode-extension/test/extension/codeLensProvider.test.ts
@microsoft/adaptivecards-tools	v1.3.1-beta.2023041103.0
@microsoft/teamsfx-api	v0.22.2-beta.2023041103.0
@microsoft/teamsfx-cli	v2.0.0-beta.2023041103.0
@microsoft/teamsfx-core	v2.0.0-beta.2023041103.0
@microsoft/teams-manifest	v0.0.10-beta.2023041103.0
@microsoft/metrics-ts	v0.0.4-beta.2023041103.0
@microsoft/teamsfx	v2.2.1-beta.2023041103.0
@microsoft/teamsfx-react	v3.0.0-beta.2023041103.0
ms-teams-vscode-extension	v4.99.0-beta.2023041103.0 …
> fix(vsc): regex of codelens

- packages/vscode-extension/src/debug/taskTerminal/devTunnelTaskTerminal.ts
detail: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/17920485
E2E TEST: none
> fix(localdebug): less log in basis terminal

- packages/fx-core/src/component/driver/script/scriptDriver.ts
To fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_sprints/taskboard/Teams%20Extensibility%20E2E%20Team/Microsoft%20Teams%20Extensibility/CY23-4.1?workitem=17940848
E2E TEST: N/A
> fix(script): script driver summary

- templates/scenarios/ts/office-addin/README.md
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/17636463
@microsoft/adaptivecards-tools	v1.3.1-beta.2023041204.0
@microsoft/teamsfx-api	v0.22.2-beta.2023041204.0
@microsoft/teamsfx-cli	v2.0.0-beta.2023041204.0
@microsoft/teamsfx-core	v2.0.0-beta.2023041204.0
@microsoft/teams-manifest	v0.0.10-beta.2023041204.0
@microsoft/metrics-ts	v0.0.4-beta.2023041204.0
@microsoft/teamsfx	v2.2.1-beta.2023041204.0
@microsoft/teamsfx-react	v3.0.0-beta.2023041204.0
ms-teams-vscode-extension	v4.99.0-beta.2023041204.0
feat: add …
> docs: update readme of outlook addin template

- packages/fx-core/src/component/coordinator/index.ts
- packages/fx-core/tests/component/coordinator.test.ts
> fix(core): resource group error name

- .github/CODEOWNERS
- packages/cli/tests/commonlib/cliHelper.ts
- packages/cli/tests/e2e/commonUtils.ts
- packages/cli/tests/e2e/template/ProvisionHelloWorldTabBackEnd.tests.ts
- packages/cli/tests/e2e/template/ProvisionIncomingWebhook.tests.ts
- packages/cli/tests/e2e/template/ProvisionMyFirstMetting.tests.ts
- packages/cli/tests/e2e/template/ProvisionNpmSearch.tests.ts
- packages/cli/tests/e2e/template/ProvisionOneProductivityHub.tests.ts
- packages/cli/tests/e2e/template/ProvisionProactiveMessaging.tests.ts
- packages/cli/tests/e2e/template/ProvisionShareNow.tests.ts
- packages/cli/tests/e2e/template/ProvisionStockUpdate.tests.ts
- packages/cli/tests/e2e/template/ProvisionTodoListBackend.tests.ts
- packages/cli/tests/e2e/template/ProvisionTodoListM365.tests.ts
- packages/cli/tests/e2e/template/ProvisionTodoListSpfx.tests.ts
- packages/cli/tests/e2e/template/ProvisionHelloWorldTabBackEnd.tests.ts
- packages/cli/tests/e2e/template/ProvisionIncomingWebhook.tests.ts
- packages/cli/tests/e2e/template/ProvisionMyFirstMetting.tests.ts
- packages/cli/tests/e2e/template/ProvisionNpmSearch.tests.ts
- packages/cli/tests/e2e/template/ProvisionOneProductivityHub.tests.ts
- packages/cli/tests/e2e/template/ProvisionProactiveMessaging.tests.ts
- packages/cli/tests/e2e/template/ProvisionShareNow.tests.ts
- packages/cli/tests/e2e/template/ProvisionStockUpdate.tests.ts
- packages/cli/tests/e2e/template/ProvisionTodoListBackend.tests.ts
- packages/cli/tests/e2e/template/ProvisionTodoListM365.tests.ts
> chore: enable some skip e2e cases

- packages/vscode-extension/PRERELEASE.md
@microsoft/adaptivecards-tools	v1.3.1-beta.2023041106.0
@microsoft/teamsfx-api	v0.22.2-beta.2023041106.0
@microsoft/teamsfx-cli	v2.0.0-beta.2023041106.0
@microsoft/teamsfx-core	v2.0.0-beta.2023041106.0
@microsoft/teams-manifest	v0.0.10-beta.2023041106.0
@microsoft/metrics-ts	v0.0.4-beta.2023041106.0
@microsoft/teamsfx	v2.2.1-beta.2023041106.0
@microsoft/teamsfx-react	v3.0.0-beta.2023041106.0
ms-teams-vscode-extension	v4.99.0-beta.2023041106.0 …
> docs: Changelog 0418

- packages/vscode-extension/package.json
@microsoft/adaptivecards-tools	v1.3.1-beta.2023041304.0
@microsoft/teamsfx-api	v0.22.2-beta.2023041304.0
@microsoft/teamsfx-cli	v2.0.0-beta.2023041304.0
@microsoft/teamsfx-core	v2.0.0-beta.2023041304.0
@microsoft/teams-manifest	v0.0.10-beta.2023041304.0
@microsoft/metrics-ts	v0.0.4-beta.2023041304.0
@microsoft/teamsfx	v2.2.1-beta.2023041304.0
@microsoft/teamsfx-react	v3.0.0-beta.2023041304.0
ms-teams-vscode-extension	v4.99.0-beta.2023041304.0 …
> fix(vsc): v4 project structure pattern

- packages/fx-core/src/component/resource/appManifest/appStudio.ts
Fixes https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/17957586
@microsoft/adaptivecards-tools	v1.3.1-beta.2023041310.0
@microsoft/teamsfx-api	v0.22.2-beta.2023041310.0
@microsoft/teamsfx-cli	v2.0.0-beta.2023041310.0
@microsoft/teamsfx-core	v2.0.0-beta.2023041310.0
@microsoft/teams-manifest	v0.0.10-beta.2023041310.0
@microsoft/metrics-ts	v0.0.4-beta.2023041310.0
@microsoft/teamsfx	v2.2.1-beta.2023041310.0
@microsoft/teamsfx-react	v3.0.0-beta.2023041310.0
ms-teams-vscode-extension	v4.99.0-beta.2023041310.0
feat: …
> fix: update teams app command

- packages/sdk/package-lock.json
Related issue: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/17902744
> chore(sdk): upgrade xml2js

- packages/cli/package-lock.json
- packages/cli/package.json
Related bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/17902744
E2E TEST: N/A
> fix(cli): bump xml2js version

- packages/api/package-lock.json
- packages/api/package.json
Related issue: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/17902744
E2E TEST: N/A
> fix(api): upgrade xml2js

- packages/cli/src/yargsCommand.ts
- packages/cli/tests/unit/cmds/account.tests.ts
- packages/cli/tests/unit/cmds/addApiConnection.tests.ts
- packages/cli/tests/unit/cmds/addCICD.tests.ts
- packages/cli/tests/unit/cmds/addSso.tests.ts
- packages/cli/tests/unit/cmds/apply.tests.ts
- packages/cli/tests/unit/cmds/capability.tests.ts
- packages/cli/tests/unit/cmds/config.tests.ts
- packages/cli/tests/unit/cmds/deploy.tests.ts
- packages/cli/tests/unit/cmds/env.tests.ts
- packages/cli/tests/unit/cmds/init.tests.ts
- packages/cli/tests/unit/cmds/m365/m365.tests.ts
- packages/cli/tests/unit/cmds/manifest.tests.ts
- packages/cli/tests/unit/cmds/new.tests.ts
- packages/cli/tests/unit/cmds/package.tests.ts
- packages/cli/tests/unit/cmds/permission.tests.ts
- packages/cli/tests/unit/cmds/preview/previewEnv.tests.ts
- packages/cli/tests/unit/cmds/provision.tests.ts
- packages/cli/tests/unit/cmds/publish.tests.ts
- packages/cli/tests/unit/cmds/resource.tests.ts
- packages/cli/tests/unit/cmds/update.tests.ts
- packages/cli/tests/unit/cmds/upgrade.tests.ts
- packages/cli/tests/unit/cmds/validate.tests.ts
- packages/cli/tests/unit/yargsCommand.tests.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/17957047
> fix(cli): exit the process if command has executed

- .husky/prepare-commit-msg
- package.json
> style: enable git cz in this repo

- packages/fx-core/templates/core/v3Migration/csharp.app.local.yml
@microsoft/adaptivecards-tools	v1.3.1-beta.2023041703.0
@microsoft/teamsfx-api	v0.22.2-beta.2023041703.0
@microsoft/teamsfx-cli	v2.0.0-beta.2023041703.0
@microsoft/teamsfx-core	v2.0.0-beta.2023041703.0
@microsoft/teams-manifest	v0.0.10-beta.2023041703.0
@microsoft/metrics-ts	v0.0.4-beta.2023041703.0
@microsoft/teamsfx	v2.2.1-beta.2023041703.0
@microsoft/teamsfx-react	v3.0.0-beta.2023041703.0
ms-teams-vscode-extension	v4.99.0-beta.2023041703.0 …
> fix: add bot domain for manifest

- packages/fx-core/src/component/coordinator/index.ts
- packages/fx-core/src/core/question.ts
- packages/fx-core/tests/component/coordinator.test.ts
- packages/fx-core/tests/component/questionv3.test.ts
- packages/server/src/serverConnection.ts
- packages/server/tests/serverConnection.test.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/17924560
E2E TEST: N/A
> fix(vs): not confirm manifest and fix the server api

- packages/server/src/providers/logger.ts
- packages/server/tests/providers/logger.test.ts
@microsoft/adaptivecards-tools	v1.3.1-beta.2023041902.0
@microsoft/teamsfx-api	v0.22.2-beta.2023041902.0
@microsoft/teamsfx-cli	v2.0.0-beta.2023041902.0
@microsoft/teamsfx-core	v2.0.0-beta.2023041902.0
@microsoft/teams-manifest	v0.0.10-beta.2023041902.0
@microsoft/metrics-ts	v0.0.4-beta.2023041902.0
@microsoft/teamsfx	v2.2.1-beta.2023041902.0
@microsoft/teamsfx-react	v3.0.0-beta.2023041902.0
ms-teams-vscode-extension	v4.99.0-beta.2023041902.0 …
> fix: write to log file for vs validation result

- templates/scenarios/js/non-sso-tab/teamsapp.local.yml.tpl
- templates/scenarios/js/non-sso-tab/teamsapp.yml.tpl
action name: m365Title/acquire -> teamsApp/extendToM365
> fix(template): action name

- packages/fx-core/templates/core/v3Migration/upgradeReport.md
E2E TEST: N/A
fix bug: https://dev.azure.com/msazure/Microsoft%20Teams%20Extensibility/_workitems/edit/17968894
> fix(upgrade): fix typo in report

- packages/fx-core/src/common/versionMetadata.ts
- packages/fx-core/src/core/middleware/projectMigratorV3.ts
- packages/fx-core/tests/core/middleware/testAssets/v3Migration/happyPath/expectedResult/userdataenv
- packages/fx-core/tests/core/middleware/testAssets/v3Migration/happyPath/testCaseFiles/.env.all.dev
- packages/fx-core/tests/core/middleware/testAssets/v3Migration/happyPath/testCaseFiles/.env.all.local
- packages/fx-core/tests/core/middleware/testAssets/v3Migration/happyPath/testCaseFiles/.env.config.dev
- packages/fx-core/tests/core/middleware/testAssets/v3Migration/happyPath/testCaseFiles/.env.config.local
- packages/fx-core/tests/core/middleware/testAssets/v3Migration/happyPath/testCaseFiles/.env.state.dev
- packages/fx-core/tests/core/middleware/testAssets/v3Migration/happyPath/testCaseFiles/.env.state.local
- packages/fx-core/tests/core/middleware/testAssets/v3Migration/happyPath/testCaseFiles/.env.userdata.dev
- packages/fx-core/tests/core/middleware/testAssets/v3Migration/happyPath/testCaseFiles/.env.userdata.local
E2E TEST: N/A
fix bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/17956993
> fix: add necessary comment in generated userdata files in migration

- templates/scenarios/csharp/sso-tab/teamsapp.local.yml.tpl
@microsoft/adaptivecards-tools	v1.3.1-beta.2023041906.0
@microsoft/teamsfx-api	v0.22.2-beta.2023041906.0
@microsoft/teamsfx-cli	v2.0.0-beta.2023041906.0
@microsoft/teamsfx-core	v2.0.0-beta.2023041906.0
@microsoft/teams-manifest	v0.0.10-beta.2023041906.0
@microsoft/metrics-ts	v0.0.4-beta.2023041906.0
@microsoft/teamsfx	v2.2.1-beta.2023041906.0
@microsoft/teamsfx-react	v3.0.0-beta.2023041906.0
ms-teams-vscode-extension	v4.99.0-beta.2023041906.0 …
> fix: fix yml bug

- packages/fx-core/src/core/FxCoreImplementV3.ts
- packages/fx-core/src/core/middleware/projectMigratorV3.ts
fix bug: https://dev.azure.com/msazure/Microsoft%20Teams%20Extensibility/_workitems/edit/17900027
> fix(upgrade): add invalid project condition

- packages/fx-core/tests/component/resource/aadApp/unit/aadApp.test.ts
update collaborator error case for v3
> test: update collaborator ut

- packages/fx-core/templates/core/v3Migration/js.ts.app.local.yml
- packages/fx-core/templates/core/v3Migration/js.ts.app.yml
- packages/fx-core/tests/core/middleware/testAssets/v3Migration/debug/transparent-m365-me/expected/app.local.yml
- packages/fx-core/tests/core/middleware/testAssets/v3Migration/debug/transparent-m365-tab/expected/app.local.yml
- packages/fx-core/tests/core/middleware/testAssets/v3Migration/ymlTemplates/m365Title.tpl
- templates/scenarios/js/dashboard-tab/teamsapp.local.yml.tpl
- templates/scenarios/js/dashboard-tab/teamsapp.yml.tpl
- templates/scenarios/js/m365-message-extension/teamsapp.local.yml.tpl
- templates/scenarios/js/m365-message-extension/teamsapp.yml.tpl
- templates/scenarios/js/m365-tab/teamsapp.local.yml.tpl
- templates/scenarios/js/m365-tab/teamsapp.yml.tpl
- templates/scenarios/js/non-sso-tab/teamsapp.local.yml.tpl
- templates/scenarios/js/non-sso-tab/teamsapp.yml.tpl
- templates/scenarios/ts/dashboard-tab/teamsapp.local.yml.tpl
- templates/scenarios/ts/dashboard-tab/teamsapp.yml.tpl
- templates/scenarios/ts/m365-message-extension/teamsapp.local.yml.tpl
- templates/scenarios/ts/m365-message-extension/teamsapp.yml.tpl
- templates/scenarios/ts/m365-tab/teamsapp.local.yml.tpl
- templates/scenarios/ts/m365-tab/teamsapp.yml.tpl
- templates/scenarios/ts/non-sso-tab/teamsapp.local.yml.tpl
- templates/scenarios/ts/non-sso-tab/teamsapp.yml.tpl
- templates/scenarios/ts/spfx-tab/teamsapp.local.yml.tpl
- templates/scenarios/ts/spfx-tab/teamsapp.yml.tpl
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/18522681
> style: lint teamsApp/extendToM365

- packages/fx-core/resource/package.nls.json
- packages/fx-core/src/component/utils/envUtil.ts
- packages/fx-core/src/error/common.ts
- packages/fx-core/tests/component/envUtil.test.ts
To fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_sprints/taskboard/Teams%20Extensibility%20E2E%20Team/Microsoft%20Teams%20Extensibility/CY23-4.2?workitem=18248523
> fix(core): refine MissingEnvironmentVariablesError error message

- packages/fx-core/src/component/resource/appManifest/appStudio.ts
- packages/fx-core/tests/component/resource/appManifest/index.test.ts
For p1 bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/17957586
> fix: file not found error for update Teams app

- packages/vscode-extension/package.json
- packages/vscode-extension/src/treeview/treeViewManager.ts
Related Feature: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/17884980
> feat(vsc): show help and feedback section on Treeview UI

- templates/scenarios/csharp/sso-tab/teamsapp.local.yml.tpl
- templates/scenarios/csharp/sso-tab/teamsapp.yml.tpl
- templates/scenarios/js/m365-tab/teamsapp.local.yml.tpl
- templates/scenarios/js/m365-tab/teamsapp.yml.tpl
- templates/scenarios/js/sso-tab/teamsapp.local.yml.tpl
- templates/scenarios/js/sso-tab/teamsapp.yml.tpl
- templates/scenarios/ts/m365-tab/teamsapp.local.yml.tpl
- templates/scenarios/ts/m365-tab/teamsapp.yml.tpl
- templates/scenarios/ts/sso-tab/teamsapp.local.yml.tpl
- templates/scenarios/ts/sso-tab/teamsapp.yml.tpl
1. Move every comment above related property
2. Split the comments to ensure each line does not exceed 80 characters
3. Remove quotes for `"AzureADMyOrg"`
> style(template): update yaml comments to satisfy lint rule

- packages/fx-core/templates/plugins/resource/aad/auth/V3/Bot/SSO/SsoOperations.cs
- packages/fx-core/templates/plugins/resource/aad/auth/V3/Tab/GetUserProfile.razor
@microsoft/adaptivecards-tools	v1.3.1-beta.2023042305.0
@microsoft/teamsfx-api	v0.22.2-beta.2023042305.0
@microsoft/teamsfx-cli	v2.0.0-beta.2023042305.0
@microsoft/teamsfx-core	v2.0.0-beta.2023042305.0
@microsoft/teams-manifest	v0.0.10-beta.2023042305.0
@microsoft/metrics-ts	v0.0.4-beta.2023042305.0
@microsoft/teamsfx	v2.2.1-beta.2023042305.0
@microsoft/teamsfx-react	v3.0.0-beta.2023042305.0
ms-teams-vscode-extension	v4.99.0-beta.2023042305.0 …
> docs(sso): update add sso sample code for V5

- templates/scenarios/js/m365-tab/src/components/sample/Welcome.css
- templates/scenarios/js/m365-tab/src/index.css
- templates/scenarios/js/non-sso-tab-default-bot/tab/src/components/sample/Welcome.css
- templates/scenarios/js/non-sso-tab-default-bot/tab/src/index.css
- templates/scenarios/js/sso-tab/src/components/sample/Welcome.css
- templates/scenarios/js/sso-tab/src/index.css
- templates/scenarios/ts/m365-tab/src/components/sample/Welcome.css
- templates/scenarios/ts/m365-tab/src/index.css
- templates/scenarios/ts/non-sso-tab-default-bot/tab/src/components/sample/Welcome.css
- templates/scenarios/ts/non-sso-tab-default-bot/tab/src/index.css
- templates/scenarios/ts/sso-tab/src/components/sample/Welcome.css
- templates/scenarios/ts/sso-tab/src/index.css
Bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_sprints/taskboard/Teams%20Extensibility%20E2E%20Team/Microsoft%20Teams%20Extensibility/CY23-4.2?workitem=18314836
> fix: fix ios display error

- packages/cli/src/cmds/update.ts
- packages/cli/src/cmds/validate.ts
- packages/cli/tests/unit/cmds/update.tests.ts
- packages/cli/tests/unit/cmds/validate.tests.ts
1) teamsfx update teams-app
2) teamsfx validate
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/18488521
> fix: update teams-app cli

- packages/fx-core/package.json
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/17990376
> fix: upgrade office-addin-manifest version

- packages/dotnet-sdk/CHANGELOG.md
- packages/dotnet-sdk/README.md
- packages/dotnet-sdk/src/TeamsFx/Microsoft.TeamsFx.csproj
Work item: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/17979745
Bump new version and update README & CHANGELOG for the changes in https://github.com/OfficeDev/TeamsFx/pull/8486.
> feat(sdk): bump .NET SDK version for notification sdk enhencement

- packages/cli/tests/e2e/multienv/TestRemoteHappyPath.tests.ts
> test: update multi env test to support v5

- packages/fx-core/src/component/developerPortalScaffoldUtils.ts
- packages/fx-core/src/component/resource/appManifest/utils/utils.ts
- packages/fx-core/src/core/middleware/questionModel.ts
- packages/fx-core/tests/component/coordinator.test.ts
- packages/fx-core/tests/component/developerPortalScaffoldUtils.test.ts
- packages/fx-core/tests/component/resource/appManifest/utils.test.ts
- fix [Bug 18684982](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/18684982): [VSCode]TDP: Personal app will be added together with bot feature if selected scopes
- also noticed that TDP feature will be broken with the new create project UI. Adjusted here.
> fix: tdp personal bot

- packages/fx-core/resource/package.nls.json
- packages/fx-core/src/component/coordinator/index.ts
- packages/fx-core/src/component/feature/apiconnector/errors.ts
- packages/fx-core/src/component/feature/bot/bot.ts
- packages/fx-core/src/component/feature/bot/question.ts
- packages/fx-core/src/component/resource/azureSql/errors.ts
- packages/fx-core/tests/component/feature/apiconnector/checker.test.ts
- packages/fx-core/tests/component/feature/bot.test.ts
- packages/fx-core/tests/component/resource/appManifest/manifestUtils.test.ts
1. To fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_sprints/taskboard/Teams%20Extensibility%20E2E%20Team/Microsoft%20Teams%20Extensibility/CY23-4.2?workitem=19464843
2. to better support automatic scanning of unused strings, avoid using dynamic strings for localized string key reference
> fix(core): correct usage of localized strings

- packages/vscode-extension/src/debug/prerequisitesHandler.ts
- packages/vscode-extension/src/debug/teamsfxTaskProvider.ts
related to PR: https://github.com/OfficeDev/TeamsFx-Samples/pull/872
Remove the v4 tasks
> fix(localdebug): retire old task command

- packages/fx-core/src/core/middleware/questionModel.ts
- packages/fx-core/tests/core/FxCore.create.test.ts
Related bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/19501664
> fix(core): create from sample flow

- templates/scenarios/ts/spfx-tab/src/README.md
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/19506164
> docs: update SPFx project template readme

- packages/fx-core/resource/package.nls.json
- packages/fx-core/src/core/FxCoreImplementV3.ts
- packages/fx-core/src/error/upgrade.ts
- packages/fx-core/tests/core/FxCore.test.ts
https://dev.azure.com/msazure/Microsoft%20Teams%20Extensibility/_workitems/edit/17793404
> fix: cli upgrade

- packages/cli/src/yargsCommand.ts
> fix(cli): preview exit issue

- packages/vscode-extension/src/handlers.ts
- packages/vscode-extension/test/extension/handlers.test.ts
https://dev.azure.com/msazure/Microsoft%20Teams%20Extensibility/_workitems/edit/17883527
> fix(upgrade): remove double confirm

- packages/fx-core/templates/core/v3Migration/upgradeReport.md
Add ngrok migration manual steps into upgrade report
Related PR: https://github.com/OfficeDev/TeamsFx/pull/8488
> docs(localdebug): add ngrok migration manual steps into upgrade report

- templates/scenarios/ts/office-addin/README.md
Fixes doc
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/19678266
> docs: add link for switching outlook update channels

- packages/cli/tests/e2e/debug/DebugCommandAndResponse.tests.ts
- packages/cli/tests/e2e/debug/DebugNotificationHttpTrigger.tests.ts
- packages/cli/tests/e2e/debug/DebugSsoTab.tests.ts
- packages/cli/tests/e2e/m365/DebugM365MessageExtension.tests.ts
- packages/cli/tests/e2e/m365/DeployM365MessageExtension.tests.ts
- packages/cli/tests/e2e/m365/DeployM365Tab.tests.ts
Sync with https://github.com/OfficeDev/TeamsFx/pull/8550
https://github.com/OfficeDev/TeamsFx/actions/runs/4815572243
> test(e2e): tweak usage of provisionProject and deployAll

- packages/fx-core/src/component/driver/deploy/azure/impl/AzureZipDeployImpl.ts
- packages/fx-core/src/component/driver/deploy/azure/impl/azureDeployImpl.ts
- packages/fx-core/src/component/driver/deploy/azure/impl/baseDeployImpl.ts
- packages/fx-core/tests/component/driver/deploy/azure/AzureDeployImpl.test.ts
- packages/fx-core/tests/component/driver/deploy/azure/azureAppServiceDeployDriver.test.ts
fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/19691043
> fix: using kudu REST endpoint with AAD Auth

- packages/vscode-extension/package-lock.json
- packages/vscode-extension/package.json
bump up vsc to 5.0.0 to release the stable version
> build: bump up vsc to 5.0.0

- templates/scenarios/js/non-sso-tab/.vscode/launch.json
- templates/scenarios/ts/non-sso-tab/.vscode/launch.json
Fix https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/19684269.
> style(template): remove trailing comma from launch.json

- Localize/loc/cs/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/cs/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/de/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/de/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/es/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/es/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/fr/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/fr/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/it/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/it/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/ja/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/ja/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/ko/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/ko/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/pl/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/pl/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/pt-BR/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/pt-BR/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/ru/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/ru/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/tr/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/tr/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/zh-Hans/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/zh-Hans/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/zh-Hant/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/zh-Hant/packages/vscode-extension/package.nls.json.lcl
LEGO: Pull request from juno/hb_fd34cb3d-1ea5-4a7c-8a66-721a44a97af3_20230430144625305 to dev with localized lcls
> chore(localization): [LEGO] Pull request from juno/hb_fd34cb3d-1ea5-4a7c-8a66-721a44a97af3_20230430144625305 to dev

- packages/fx-core/src/component/driver/deploy/azure/impl/azureDeployImpl.ts
- packages/fx-core/tests/component/driver/deploy/azure/AzureDeployImpl.test.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/19691043
> feat: add telemetry to AAD deployment, add E2E test flag

- packages/cli/tests/unit/cmds/capability.tests.ts
- packages/fx-core/src/component/question.ts
- packages/fx-core/src/core/FxCoreImplementV3.ts
> feat: remove SPFx selection from add web part flow

- templates/scenarios/csharp/command-and-response/{{ProjectName}}.csproj.tpl
- templates/scenarios/csharp/non-sso-tab/{{ProjectName}}.csproj.tpl
- templates/scenarios/csharp/notification-http-timer-trigger/NotifyHttpTrigger.cs.tpl
- templates/scenarios/csharp/notification-http-timer-trigger/NotifyTimerTrigger.cs.tpl
- templates/scenarios/csharp/notification-http-timer-trigger/{{ProjectName}}.csproj.tpl
- templates/scenarios/csharp/notification-http-trigger/NotifyHttpTrigger.cs.tpl
- templates/scenarios/csharp/notification-http-trigger/{{ProjectName}}.csproj.tpl
- templates/scenarios/csharp/notification-timer-trigger/NotifyTimerTrigger.cs.tpl
- templates/scenarios/csharp/notification-timer-trigger/{{ProjectName}}.csproj.tpl
- templates/scenarios/csharp/notification-webapi/Controllers/NotificationController.cs.tpl
- templates/scenarios/csharp/notification-webapi/{{ProjectName}}.csproj.tpl
- templates/scenarios/csharp/sso-tab/{{ProjectName}}.csproj.tpl
- templates/scenarios/csharp/workflow/{{ProjectName}}.csproj.tpl
Work item: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/17981913/
Related PR: https://github.com/OfficeDev/TeamsFx/pull/8486
> feat: update .NET template with latest SDK

- packages/fx-core/src/common/samples-config-v3.json
ADO: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/17957467
E2E TEST: NA
> feat: onboard bot proactive messaging sample

- packages/fx-core/src/component/driver/deploy/azure/impl/azureDeployImpl.ts
- packages/fx-core/src/error/deploy.ts
- packages/fx-core/tests/component/driver/deploy/azure/AzureDeployImpl.test.ts
- packages/fx-core/tests/component/driver/deploy/azure/azureFunctionDeployDriver.test.ts
fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/21015887
> fix: do not throw when remote deploy response failed, let user check it manually

- packages/vscode-extension/src/debug/taskTerminal/devTunnelTaskTerminal.ts
[Bug 21425420](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/21425420): Auto test use a different user-agent for dev tunnel
> fix(localdebug): use test user agent for auto test

- packages/fx-core/src/component/constants.ts
- packages/fx-core/src/component/driver/aad/update.ts
- packages/fx-core/src/core/FxCoreImplementV3.ts
- packages/fx-core/tests/component/driver/aad/update.test.ts
- packages/fx-core/tests/core/FxCore.test.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/19464021
> refactor(aad): success message move to update aad command

- packages/fx-core/src/component/developerPortalScaffoldUtils.ts
- packages/fx-core/src/component/resource/appManifest/constants.ts
- packages/fx-core/tests/component/developerPortalScaffoldUtils.test.ts
> fix: add default description value if scaffolding from TDP

- templates/scenarios/js/m365-tab/src/index.css
- templates/scenarios/js/non-sso-tab-default-bot/tab/src/index.css
- templates/scenarios/js/sso-tab/src/index.css
- templates/scenarios/ts/m365-tab/src/index.css
- templates/scenarios/ts/non-sso-tab-default-bot/tab/src/index.css
- templates/scenarios/ts/sso-tab/src/index.css
> fix: fix mobile tab app display error

- packages/vscode-extension/CHANGELOG.md
- packages/vscode-extension/WHATISNEW.md
> docs: changelog and whatsnew for 0515 release

- templates/scenarios/js/default-bot-message-extension/README.md
- templates/scenarios/js/default-bot/README.md
- templates/scenarios/js/message-extension/README.md
- templates/scenarios/js/non-sso-tab-default-bot/bot/README.md
- templates/scenarios/js/non-sso-tab-default-bot/tab/README.md
- templates/scenarios/js/non-sso-tab/README.md
- templates/scenarios/js/sso-tab/README.md
- templates/scenarios/ts/default-bot-message-extension/README.md
- templates/scenarios/ts/default-bot/README.md
- templates/scenarios/ts/message-extension/README.md
- templates/scenarios/ts/non-sso-tab-default-bot/bot/README.md
- templates/scenarios/ts/non-sso-tab-default-bot/tab/README.md
- templates/scenarios/ts/non-sso-tab/README.md
- templates/scenarios/ts/office-addin/README.md
- templates/scenarios/ts/spfx-tab/src/README.md
- templates/scenarios/ts/sso-tab/README.md
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/21324334
> docs: readme is out of date

- packages/vscode-extension/README.md
> docs: update vsc extension README

- templates/bot/csharp/notification-function-base/ProjectName.csproj.tpl
- templates/scenarios/csharp/notification-http-timer-trigger/{{ProjectName}}.csproj.tpl
- templates/scenarios/csharp/notification-http-trigger/{{ProjectName}}.csproj.tpl
- templates/scenarios/csharp/notification-timer-trigger/{{ProjectName}}.csproj.tpl
Rebuild codes when debugging csharp function projects.
This will solve environment problem (For example, debug function before preparing Teams app will cause debug always to fail)
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/21617846
> feat: rebuild function codes when debugging

- templates/scenarios/js/m365-tab/src/components/sample/AzureFunctions.jsx
- templates/scenarios/js/m365-tab/src/components/sample/Deploy.jsx
- templates/scenarios/js/non-sso-tab-default-bot/tab/src/components/sample/Deploy.jsx
- templates/scenarios/js/sso-tab/src/components/sample/AzureFunctions.jsx
- templates/scenarios/js/sso-tab/src/components/sample/Deploy.jsx
- templates/scenarios/ts/m365-tab/src/components/sample/AzureFunctions.tsx
- templates/scenarios/ts/m365-tab/src/components/sample/Deploy.tsx
- templates/scenarios/ts/non-sso-tab-default-bot/tab/src/components/sample/Deploy.tsx
- templates/scenarios/ts/sso-tab/src/components/sample/AzureFunctions.tsx
- templates/scenarios/ts/sso-tab/src/components/sample/Deploy.tsx
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/21425621
> fix: tab content should be consistent with VSC command palette

- packages/vscode-extension/src/progressHandler.ts
- packages/vscode-extension/test/extension/progressHandler.test.ts
> fix(vsc): progress bar implementation

- templates/scenarios/js/dashboard-tab/appPackage/manifest.json.tpl
- templates/scenarios/js/m365-tab/appPackage/manifest.json.tpl
- templates/scenarios/js/non-sso-tab-default-bot/appPackage/manifest.json.tpl
- templates/scenarios/js/non-sso-tab/appPackage/manifest.json.tpl
- templates/scenarios/js/sso-tab/appPackage/manifest.json.tpl
- templates/scenarios/ts/dashboard-tab/appPackage/manifest.json.tpl
- templates/scenarios/ts/m365-tab/appPackage/manifest.json.tpl
- templates/scenarios/ts/non-sso-tab-default-bot/appPackage/manifest.json.tpl
- templates/scenarios/ts/non-sso-tab/appPackage/manifest.json.tpl
- templates/scenarios/ts/sso-tab/appPackage/manifest.json.tpl
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/21444433/
> fix: using dev-tunnel in mobile conflict with loading indicator

- templates/scenarios/ts/spfx-tab/src/README.md
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/21455865
> docs: update SPFx readme

- packages/fx-core/src/component/driver/devTool/error/dotnetInstallationUserError.ts
- packages/fx-core/src/component/driver/devTool/error/funcInstallationUserError.ts
- packages/fx-core/src/component/driver/devTool/installDriver.ts
Detail: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/21425247/
> fix(localdebug): add help link to devTool/install error

- packages/fx-core/src/component/generator/officeAddin/question.ts
> fix(core): remove default value when selecting addin project manifest

- packages/fx-core/package-lock.json
- packages/sdk-react/package-lock.json
- packages/sdk/package-lock.json
- packages/vscode-extension/package-lock.json
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_sprints/taskboard/Teams%20Extensibility%20E2E%20Team/Microsoft%20Teams%20Extensibility/CY23-5.1?workitem=21775702
cherry-pick from dev https://github.com/OfficeDev/TeamsFx/pull/8662
> build: update the deps for audit

- packages/fx-core/src/component/driver/teamsApp/validate.ts
- packages/fx-core/tests/component/driver/teamsApp/validate.test.ts
For bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/21614411
> fix(cli): show detailed validation error

- packages/fx-core/src/common/local/constants.ts
- packages/vscode-extension/src/debug/taskTerminal/migrateTaskTerminal.ts
- packages/vscode-extension/src/debug/teamsfxTaskProvider.ts
@microsoft/teamsfx-cli	v2.0.0-rc.2
@microsoft/teamsfx-core	v2.0.0-rc.2
ms-teams-vscode-extension	v5.0.0-rc.2
> fix(upgrade): improve cancelling debug upgrade experience

- packages/server/src/apis.ts
- packages/server/src/serverConnection.ts
- packages/server/tests/serverConnection.test.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/17902471
> feat(server): add a new API - getLaunchUrlRequest

- packages/fx-core/templates/core/v3Migration/upgradeReport.md
@microsoft/teamsfx-cli	v2.0.0-rc.2
@microsoft/teamsfx-core	v2.0.0-rc.2
ms-teams-vscode-extension	v5.0.0-rc.2
> fix(upgrade): update report

- templates/package-lock.json
- templates/package.json
@microsoft/teamsfx-cli	v2.0.0-rc.2
@microsoft/teamsfx-core	v2.0.0-rc.2
ms-teams-vscode-extension	v5.0.0-rc.2
> build: bump major version for template

- packages/fx-core/src/component/utils/envUtil.ts
- packages/fx-core/tests/component/envUtil.test.ts
@microsoft/teamsfx-cli	v2.0.0-rc.2
@microsoft/teamsfx-core	v2.0.0-rc.2
ms-teams-vscode-extension	v5.0.0-rc.2
> fix: move TEAMS_APP_UPDATE_TIME to .user file

- packages/fx-core/src/common/samples.ts
- packages/fx-core/tests/common/samples.test.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/21810144
E2E TEST: NA
> fix: get sample config by release tag

- packages/cli/src/console/progress.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/21800121
> fix(cli): progress success icon

- packages/vscode-extension/syntaxes/teamsfx-toolkit-output.tmLanguage
Related bug:
1. https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/21424443
2. https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/21619050
> fix(vsc): syntax color rule

- packages/vscode-extension/src/utils/upgrade.ts
- packages/vscode-extension/test/extension/utils/upgrade.test.ts
ms-teams-vscode-extension	v5.0.0-rc.3
> fix: show what's new on v5

- packages/vscode-extension/CHANGELOG.md
- packages/vscode-extension/WHATISNEW.md
ms-teams-vscode-extension	v5.0.0-rc.3
> docs: fix changelog and whatsnew typo

- templates/scenarios/js/command-and-response/web.config
- templates/scenarios/js/default-bot-message-extension/web.config
- templates/scenarios/js/default-bot/web.config
- templates/scenarios/js/m365-message-extension/web.config
- templates/scenarios/js/message-extension/web.config
- templates/scenarios/js/non-sso-tab-default-bot/bot/web.config
- templates/scenarios/js/non-sso-tab/web.config
- templates/scenarios/js/notification-restify/web.config
- templates/scenarios/js/workflow/web.config
- templates/scenarios/ts/command-and-response/web.config
- templates/scenarios/ts/default-bot-message-extension/web.config
- templates/scenarios/ts/default-bot/web.config
- templates/scenarios/ts/m365-message-extension/web.config
- templates/scenarios/ts/message-extension/web.config
- templates/scenarios/ts/non-sso-tab-default-bot/bot/web.config
- templates/scenarios/ts/non-sso-tab/web.config
- templates/scenarios/ts/notification-restify/web.config
- templates/scenarios/ts/workflow/web.config
fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/21593945
> fix: fix broken link in web.config

- packages/fx-core/resource/package.nls.json
fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_sprints/taskboard/Teams%20Extensibility%20E2E%20Team/Microsoft%20Teams%20Extensibility/CY23-5.2?workitem=22202112
> fix: update error message for issue link statement

- packages/fx-core/resource/package.nls.json
- packages/fx-core/src/component/utils/envUtil.ts
- packages/fx-core/src/component/utils/pathUtils.ts
- packages/fx-core/src/error/common.ts
- packages/fx-core/tests/component/coordinator.test.ts
- packages/fx-core/tests/component/envUtil.test.ts
fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/22651915
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/22302675
> fix(core): default env write behavior when env folder path is not available

- packages/cli/tests/utils/executor.ts
https://github.com/OfficeDev/TeamsFx/actions/runs/4989005140
> test: fix spfx add web part e2e test

- templates/scenarios/js/notification-http-timer-trigger/package.json.tpl
- templates/scenarios/js/notification-http-timer-trigger/src/httpTrigger.js
- templates/scenarios/js/notification-http-timer-trigger/src/timerTrigger.js
- templates/scenarios/js/notification-http-trigger/package.json.tpl
- templates/scenarios/js/notification-http-trigger/src/httpTrigger.js
- templates/scenarios/js/notification-restify/package.json.tpl
- templates/scenarios/js/notification-restify/src/index.js
- templates/scenarios/js/notification-timer-trigger/package.json.tpl
- templates/scenarios/js/notification-timer-trigger/src/timerTrigger.js
- templates/scenarios/ts/notification-http-timer-trigger/package.json.tpl
- templates/scenarios/ts/notification-http-timer-trigger/src/httpTrigger.ts
- templates/scenarios/ts/notification-http-timer-trigger/src/timerTrigger.ts
- templates/scenarios/ts/notification-http-trigger/package.json.tpl
- templates/scenarios/ts/notification-http-trigger/src/httpTrigger.ts
- templates/scenarios/ts/notification-restify/package.json.tpl
- templates/scenarios/ts/notification-restify/src/index.ts
- templates/scenarios/ts/notification-timer-trigger/package.json.tpl
- templates/scenarios/ts/notification-timer-trigger/src/timerTrigger.ts
work item: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/17981916/
The following templates are updated:
* templates/scenarios/js
* notification-http-timer-trigger
* notification-http-trigger
* notification-timer-trigger
* notification-restify
* templates/scenarios/ts
* notification-http-timer-trigger
* notification-http-trigger
* notification-timer-trigger
* notification-restify
> feat: update js/ts template with latest SDK

- .github/CODEOWNERS
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/23113357
> ci: add code owners for yaml schema

- packages/cli/tests/unit/cmds/deploy.tests.ts
- packages/cli/tests/unit/cmds/index.tests.ts
- packages/cli/tests/unit/cmds/new.tests.ts
- packages/cli/tests/unit/cmds/package.tests.ts
- packages/cli/tests/unit/cmds/permission.tests.ts
- packages/cli/tests/unit/cmds/publish.tests.ts
- packages/cli/tests/unit/cmds/update.tests.ts
- packages/cli/tests/unit/cmds/upgrade.tests.ts
- packages/cli/tests/unit/cmds/validate.tests.ts
- packages/cli/tests/unit/help.tests.ts
- packages/cli/tests/unit/utils.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/17649026
> test(cli): refactor the unit test - part 2

- packages/cli/src/cmds/account.ts
- packages/cli/src/cmds/config.ts
- packages/cli/src/cmds/deploy.ts
- packages/cli/src/cmds/package.ts
- packages/cli/src/cmds/provision.ts
- packages/cli/src/cmds/publish.ts
- packages/cli/src/cmds/validate.ts
- packages/cli/tests/unit/cmds/account.tests.ts
- packages/cli/tests/unit/cmds/config.tests.ts
- packages/cli/tests/unit/cmds/deploy.tests.ts
- packages/cli/tests/unit/cmds/package.tests.ts
- packages/cli/tests/unit/cmds/provision.tests.ts
- packages/cli/tests/unit/cmds/validate.tests.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/23527910
> refactor(cli): remove V4 logic in the commands

- packages/cli/tests/e2e/m365/DeployM365MessageExtension.tests.ts
- packages/cli/tests/e2e/m365/DeployM365Tab.tests.ts
Fix:
- https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/23282648
- https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/23282942
E2E TEST: https://github.com/OfficeDev/TeamsFx/actions/runs/5043504383
> test(e2e): fix m365 deployment cases

- .github/workflows/api2teams_ci.yml
- packages/api2teams/package.json
success run in my fork branch: https://github.com/KennethBWSong/TeamsFx/actions/runs/5042653111/jobs/9043507489?pr=6
> ci(api2teams): add ci for api2teams

- packages/vscode-extension/src/utils/survey.ts
refactor: clean v4 code for survey
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/23703926
> refactor: clean v4 code for survey

- .github/workflows/cd_trigger.yml
- packages/eslint-plugin-teamsfx/package.json
@microsoft/adaptivecards-tools	v1.3.2-rc.0
@microsoft/teamsfx-api	v0.22.3-rc.0
@microsoft/teamsfx-cli	v2.0.1-rc.0
@microsoft/eslint-plugin-teamsfx	v0.0.3-rc.0
@microsoft/teamsfx-core	v2.0.1-rc.0
@microsoft/teams-manifest	v0.0.11-rc.0
@microsoft/teamsfx	v2.2.2-rc.0
@microsoft/teamsfx-react	v3.0.1-rc.0
ms-teams-vscode-extension	v5.0.1-rc.0
> ci: public eslint plugin

- packages/fx-core/resource/package.nls.json
- packages/fx-core/src/component/driver/aad/create.ts
- packages/fx-core/src/component/driver/aad/update.ts
- packages/fx-core/src/component/driver/botAadApp/create.ts
- packages/fx-core/src/error/common.ts
- packages/fx-core/tests/component/driver/aad/create.test.ts
- packages/fx-core/tests/component/driver/aad/update.test.ts
- packages/fx-core/tests/component/driver/botAadApp/create.test.ts
fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/23542042
> refactor: better error code for API failures

- templates/scenarios/ts/office-addin/README.md
Fixes https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/21818206
and https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/23284681
> docs: fix outlook add-in readme

- packages/cli/tests/e2e/collaboration/Permission.tests.ts
bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_sprints/taskboard/AuthAndData/Microsoft%20Teams%20Extensibility/CY23-5.2?workitem=23281504
success run: https://github.com/OfficeDev/TeamsFx/actions/runs/5074561796/jobs/9115288124
> test(e2e): update permission test

- Localize/loc/cs/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/cs/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/de/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/de/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/es/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/es/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/fr/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/fr/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/it/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/it/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/ja/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/ja/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/ko/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/ko/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/pl/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/pl/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/pt-BR/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/pt-BR/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/ru/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/ru/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/tr/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/tr/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/zh-Hans/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/zh-Hans/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/zh-Hant/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/zh-Hant/packages/vscode-extension/package.nls.json.lcl
LEGO: Pull request from juno/hb_fd34cb3d-1ea5-4a7c-8a66-721a44a97af3_20230524144649609 to dev with localized lcls
> chore(localization): [LEGO] Pull request from juno/hb_fd34cb3d-1ea5-4a7c-8a66-721a44a97af3_20230524144649609 to dev

- templates/scenarios/js/non-sso-tab/src/static/scripts/teamsapp.js
- templates/scenarios/ts/non-sso-tab/src/static/scripts/teamsapp.js
https://github.com/OfficeDev/TeamsFx/issues/8761
> fix: wait for microsoftTeams.app.initialize

- packages/fx-core/package-lock.json
- packages/sdk/package-lock.json
Fix dependabot security alert. (https://github.com/OfficeDev/TeamsFx/security/dependabot/396)
> fix: security alert

- packages/cli/src/commonlib/azureLogin.ts
- packages/cli/src/commonlib/azureLoginCI.ts
- packages/cli/src/utils.ts
- packages/cli/tests/unit/commonlib/azureLoginCI.tests.ts
- packages/cli/tests/unit/utils.tests.ts
- packages/cli/tests/unit/yargsCommand.tests.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/23530602
> refactor(cli): clean unused functions in utils.ts

- packages/api/package.json
- packages/manifest/devPreviewSchema.json
- packages/manifest/package-lock.json
- packages/manifest/package.json
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/17278602
@microsoft/adaptivecards-tools	v1.3.2-rc.0
@microsoft/teamsfx-api	v0.22.3-rc.1
@microsoft/teamsfx-cli	v2.0.1-rc.0
@microsoft/teamsfx-core	v2.0.1-rc.1
@microsoft/teams-manifest	v0.1.0-rc.0
@microsoft/teamsfx	v2.2.2-rc.0
@microsoft/teamsfx-react	v3.0.1-rc.0
ms-teams-vscode-extension	v5.0.1-rc.0
> feat: update devPreviewManifest for manifest package

- packages/fx-core/src/component/driver/deploy/azure/impl/AzureZipDeployImpl.ts
- packages/fx-core/src/component/driver/interface/buildAndDeployArgs.ts
- packages/fx-core/tests/component/driver/deploy/azure/azureAppServiceDeployDriver.test.ts
- packages/fx-core/tests/component/driver/deploy/azure/azureFunctionDeployDriver.test.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/24121377
> fix: sometimes the Azure API response contains null

- .github/workflows/botbuilder-released.yml
- .github/workflows/dependency-check.yml
- .github/workflows/graph-toolkit-released.yml
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/21998524
> feat: add email notification for botbuilder release

- packages/cli/tests/e2e/spfx/CreateSPFxProjectWithSpaceAppName.tests.ts
- packages/fx-core/src/component/generator/spfx/spfxGenerator.ts
ADO: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/23178499
E2E TEST: CreateSPFxProjectWithSpaceAppName.tests.ts
> fix: scaffold SPFx project failed with app name including space

- packages/cli/tests/e2e/collaboration/Permission.tests.ts
- packages/cli/tests/e2e/collaboration/PermissionSPFX.tests.ts
- packages/cli/tests/e2e/commonUtils.ts
success run: https://github.com/OfficeDev/TeamsFx/actions/runs/5130048074
> test(e2e): remove teamsapp/extendtom365 in e2e test

- packages/vscode-extension/src/commonlib/azureLogin.ts
- packages/vscode-extension/src/extension.ts
1. Remove v3 feature flag and subscription file logic in azure login.
> refactor: remove unused codes in azure login

- packages/fx-core/src/common/tools.ts
- packages/fx-core/tests/component/generator/generator.test.ts
- packages/fx-core/tests/core/FxCore.create.test.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_sprints/taskboard/Compute%20Team/Microsoft%20Teams%20Extensibility/CY23-5.2?workitem=23704990
> feat: turn on download directory feature flag

- docs/cicd/azdo/cd.azure.yml
- docs/cicd/azdo/cd.spfx.yml
- docs/cicd/azdo/ci.yml
- docs/cicd/azdo/provision.azure.yml
- docs/cicd/azdo/provision.spfx.yml
- docs/cicd/azdo/publish.yml
- docs/cicd/github-cd-template.yml
- docs/cicd/github-ci-template.yml
- docs/cicd/github/cd.azure.yml
- docs/cicd/github/cd.spfx.yml
- docs/cicd/github/ci.yml
- docs/cicd/github/provision.azure.yml
- docs/cicd/github/provision.spfx.yml
- docs/cicd/github/publish.yml
- docs/cicd/jenkins/Jenkinsfile.azure.cd
- docs/cicd/jenkins/Jenkinsfile.azure.provision
- docs/cicd/jenkins/Jenkinsfile.publish
- docs/cicd/jenkins/Jenkinsfile.spfx.cd
- docs/cicd/jenkins/Jenkinsfile.spfx.provision
- docs/cicd_insider/github-cd-template.yml
- packages/fx-core/templates/plugins/resource/cicd/github/publish.yml
- packages/fx-core/templates/plugins/resource/cicd_v2/github/publish.yml
- packages/vscode-extension/.vscode/launch.json
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/23271936/
> fix: update CLI version and node version for CI/CD pipe line

- .github/CODEOWNERS
- .github/workflows/code-cleanup-report.yml
Add workflow to detect code cleanup status, all checks should pass when code cleanup finished:
- There's no unused variables, functions, classes in source code
- There's no unused exports in source code
- All files should have a code owner
> ci: workflow to report code cleanup status

- packages/vscode-extension/src/handlers.ts
- packages/vscode-extension/test/extension/handlers.test.ts
[Bug 24133837](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/24133837): Set App Studio API Region when from TDP
> fix: set regional api when handling URL from TDP

- .github/workflows/vscode-marketplace.yml
run the action in personal repo:
https://github.com/wenytang-ms/TeamsFx/actions/runs/5152290175
> ci: update tag after publish

- packages/vscode-extension/src/handlers.ts
- packages/vscode-extension/test/extension/handlers.test.ts
Related bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/24172311/
> fix(vsc): azure login callback

- packages/vscode-extension/src/debug/commonUtils.ts
- packages/vscode-extension/src/qm/vsc_ui.ts
To fix https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/24133861.
> fix(upgrade): sleep 2s before reloading after upgade to send telemetry

- packages/vscode-extension/src/commonlib/telemetry.ts
fix: anonymize file path in error message
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/23269965
> fix: anonymize file path in error message

- packages/fx-core/src/core/middleware/projectMigratorV3.ts
- packages/fx-core/tests/core/middleware/migration/projectMigrationV3.test.ts
- packages/fx-core/tests/core/middleware/testAssets/v3Migration/happyPath/expectedResult/whenGitignoreExist
- packages/fx-core/tests/core/middleware/testAssets/v3Migration/happyPath/expectedResult/whenGitignoreNotExist
Fix: https://dev.azure.com/msazure/Microsoft%20Teams%20Extensibility/_workitems/edit/23537793
The bug of project-id missing in telemetry is fixed in https://github.com/OfficeDev/TeamsFx/pull/8907
> fix: add await for creating gitignore

- .github/renovate.json
- .github/workflows/dependency-check.yml
- .github/workflows/e2e-test.yml
- .github/workflows/sdk-e2e-test.yml
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_dashboards/dashboard/a9d3c597-e398-49d2-a5d4-2c1b23ea0025
> feat: add sdk dependency auto update & check pipeline

- packages/api/review/teamsfx-api.api.md
- packages/api/src/qm/ui.ts
- packages/cli/src/console/progress.ts
- packages/cli/src/userInteraction.ts
- packages/cli/tests/unit/ui.tests.ts
- packages/fx-core/package.json
- packages/fx-core/src/component/generator/spfx/utils/questions.ts
- packages/fx-core/src/component/question.ts
- packages/fx-core/src/ui/visitor.ts
- packages/fx-core/tests/plugins/resource/spfx/unit/utils.test.ts
- packages/fx-core/tests/ui/qm.visitor.test.ts
- packages/sdk-react/package-lock.json
- packages/vscode-extension/src/handlers.ts
- packages/vscode-extension/src/qm/vsc_ui.ts
For CLI experience:
loading:
loaded:
For VSC experience:
loading:
loaded:
> refactor: select option(s) ux support options loading callback function with progress bar

- .github/actions/create-milestone/action.yml
- .github/actions/create-milestone/index.ts
- .github/workflows/create-milestone.yml
https://dev.azure.com/msazure/Microsoft%20Teams%20Extensibility/_workitems/edit/21987041
> feat(github): add create-milestone action

- packages/vscode-extension/package.json
- packages/vscode-extension/src/handlers.ts
- packages/vscode-extension/test/extension/handlers.test.ts
https://dev.azure.com/msazure/Microsoft%20Teams%20Extensibility/_workitems/edit/24267289
> refactor(aad): remove v2 update aad manifest code

- docs/cicd/azdo/cd.spfx.yml
- docs/cicd/azdo/provision.spfx.yml
- docs/cicd/github/cd.spfx.yml
- docs/cicd/github/provision.spfx.yml
fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/24267028
> fix: SPFX only support node version 16

- packages/fx-core/package-lock.json
- packages/fx-core/package.json
- packages/fx-core/src/common/tools.ts
- packages/fx-core/tests/common/tools.test.ts
- packages/server/package-lock.json
- packages/server/package.json
- packages/server/src/apis.ts
- packages/server/src/serverConnection.ts
- packages/server/tests/serverConnection.test.ts
1. Add list dev tunnels API for VS.
> refactor: add list dev tunnels

- Localize/loc/de/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/de/packages/vscode-extension/package.nls.json.lcl
LEGO: Pull request from juno/hb_fd34cb3d-1ea5-4a7c-8a66-721a44a97af3_20230618144335626 to dev with localized lcls
> chore(localization): [LEGO] Pull request from juno/hb_fd34cb3d-1ea5-4a7c-8a66-721a44a97af3_20230618144335626 to dev

- packages/fx-core/src/component/driver/teamsApp/appStudio.ts
- packages/fx-core/src/component/driver/teamsApp/clients/appStudioClient.ts
- packages/fx-core/src/component/driver/teamsApp/utils/telemetry.ts
ADO work item: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/24267416
> fix: add telemetry to differentiate update and create

- packages/vscode-extension/src/qm/vsc_ui.ts
fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/24317687
> fix(vsc): auto skip question take effect for dynamic options

- packages/cli/src/console/progress.ts
- packages/cli/src/console/screen.ts
- packages/cli/tests/e2e/commonUtils.ts
- packages/cli/tests/unit/console/progress.tests.ts
- packages/cli/tests/unit/console/screen.tests.ts
expected:
un expected( 3 and 4 are loading option progress)
> fix: not show progress for loading option in scaffold flow

- packages/fx-core/src/component/generator/spfx/spfxGenerator.ts
- packages/fx-core/src/component/generator/spfx/utils/questions.ts
- packages/fx-core/src/core/middleware/questionModel.ts
- packages/fx-core/tests/core/question.test.ts
Interactive mode:
Non-interactive mode:
> feat: import existing SPFx solution under cli

- packages/fx-core/src/common/versionMetadata.ts
- packages/fx-core/src/core/middleware/utils/v3MigrationUtils.ts
- packages/fx-core/tests/core/middleware/migration/projectMigrationV3.test.ts
Fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/24306846
> fix: version state check

- packages/fx-core/src/component/driver/botFramework/interface/createOrUpdateBotFrameworkBotArgs.ts
- packages/fx-core/src/component/driver/devTool/constant.ts
- packages/fx-core/src/component/driver/file/interface/generateEnvArgs.ts
- packages/fx-core/src/component/driver/file/interface/generateJsonArgs.ts
Fix https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/24332442.
> style: fix unused exports

- packages/fx-core/src/component/driver/script/dotnetBuildDriver.ts
- packages/fx-core/src/component/driver/script/npmBuildDriver.ts
- packages/fx-core/src/component/driver/script/npxBuildDriver.ts
- packages/fx-core/tests/component/driver/script/npmBuildDriver.test.ts
- packages/fx-core/tests/component/driver/script/npxBuildDriver.test.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/24330803
> fix: fix npm&npx&dotnet driver telemetry data loss

- packages/fx-core/src/component/driver/util/wrapUtil.ts
- packages/fx-core/src/core/middleware/projectMigratorV3.ts
- packages/fx-core/tests/component/driver/arm/deploy.test.ts
- packages/fx-core/tests/core/middleware/migration/yml.test.ts
- packages/vscode-extension/src/migration/migrationTool/ts/importInfo.ts
> refactor: cleanup

- packages/fx-core/templates/core/v3Migration/csharp.app.yml
- packages/fx-core/tests/core/middleware/testAssets/v3Migration/csharpFunctionBot/expectedResult/app.yml
- packages/fx-core/tests/core/middleware/testAssets/v3Migration/csharpNonSsoTab/expectedResult/app.yml
- packages/fx-core/tests/core/middleware/testAssets/v3Migration/csharpSsoTab/expectedResult/app.yml
- packages/fx-core/tests/core/middleware/testAssets/v3Migration/csharpWebappBot/expectedResult/app.yml
Fix bug: https://dev.azure.com/msazure/Microsoft%20Teams%20Extensibility/_workitems/edit/24369773
> fix: upgrade csharp yml version 1.1.0

- .github/CODEOWNERS
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/24332688
> ci: update code owner

- packages/fx-core/templates/core/v3Migration/upgradeReport.md
@microsoft/teamsfx-cli	v2.0.2-rc.0
@microsoft/teamsfx-core	v2.0.3-rc.2
ms-teams-vscode-extension	v5.0.2-rc.0
> refactor: upgrade report

- packages/vscode-extension/src/commonlib/azure-account.api.d.ts
- packages/vscode-extension/src/commonlib/common/constant.ts
- packages/vscode-extension/src/commonlib/telemetry.ts
Remove unused codes in commonlib.
> refactor: update common lib codes

- Localize/loc/zh-Hans/packages/fx-core/resource/package.nls.json.lcl
LEGO: Pull request from juno/hb_fd34cb3d-1ea5-4a7c-8a66-721a44a97af3_20230628144400108 to dev with localized lcls
> chore(localization): [LEGO] Pull request from juno/hb_fd34cb3d-1ea5-4a7c-8a66-721a44a97af3_20230628144400108 to dev

- packages/fx-core/resource/package.nls.json
- packages/fx-core/src/component/driver/botFramework/createOrUpdateBot.ts
- packages/fx-core/src/component/driver/botFramework/error/invalidBotIdError.ts
- packages/fx-core/tests/component/driver/botFramework/createOrUpdateBot.test.ts
To fix https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/24277887.
E2E TEST: N/A
> fix: validate if bot id is guid in botFramework action

- Localize/loc/cs/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/cs/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/de/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/de/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/es/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/es/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/fr/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/fr/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/it/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/it/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/ja/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/ja/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/ko/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/ko/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/pl/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/pl/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/pt-BR/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/pt-BR/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/ru/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/ru/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/tr/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/tr/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/zh-Hans/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/zh-Hans/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/zh-Hant/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/zh-Hant/packages/vscode-extension/package.nls.json.lcl
LEGO: Pull request from juno/hb_fd34cb3d-1ea5-4a7c-8a66-721a44a97af3_20230629231748304 to dev with localized lcls
> chore(localization): [LEGO] Pull request from juno/hb_fd34cb3d-1ea5-4a7c-8a66-721a44a97af3_20230629231748304 to dev

- Localize/loc/cs/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/cs/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/es/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/fr/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/fr/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/it/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/ja/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/ja/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/ko/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/ko/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/pl/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/pt-BR/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/ru/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/tr/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/zh-Hans/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/zh-Hant/packages/fx-core/resource/package.nls.json.lcl
LEGO: Pull request from juno/hb_fd34cb3d-1ea5-4a7c-8a66-721a44a97af3_20230701144454852 to dev with localized lcls
> chore(localization): [LEGO] Pull request from juno/hb_fd34cb3d-1ea5-4a7c-8a66-721a44a97af3_20230701144454852 to dev

- .github/CODEOWNERS
ADO: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/24332672
> ci: update code owners for localization files and add web part

- packages/fx-core/src/question/create.ts
- packages/fx-core/tests/question/create.test.ts
- fix title of capability question
> fix: create question title

- Localize/loc/de/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/de/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/pl/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/tr/packages/fx-core/resource/package.nls.json.lcl
LEGO: Pull request from juno/hb_fd34cb3d-1ea5-4a7c-8a66-721a44a97af3_20230703144430642 to dev with localized lcls
> chore(localization): [LEGO] Pull request from juno/hb_fd34cb3d-1ea5-4a7c-8a66-721a44a97af3_20230703144430642 to dev

- packages/vscode-extension/package.nls.json
- packages/vscode-extension/src/handlers.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/24386015
> feat: change fallback app name when showing local debug/preview message

- packages/cli/src/resource/strings.json
- packages/cli/src/userInteraction.ts
- packages/cli/tests/unit/ui.tests.ts
fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/24464364
expected behavior:
> fix: cli invalid option error

- packages/fx-core/src/question/create.ts
- packages/fx-core/src/question/util.ts
- packages/fx-core/tests/question/create.test.ts
- packages/fx-core/tests/question/util.test.ts
E2E: https://github.com/OfficeDev/TeamsFx/actions/runs/5482204175/jobs/9987305831
> fix: import URL

- packages/fx-core/package-lock.json
- packages/fx-core/package.json
- packages/fx-core/src/common/spec-parser/constants.ts
- packages/fx-core/src/common/spec-parser/interfaces.ts
- packages/fx-core/src/common/spec-parser/specParser.ts
- packages/fx-core/src/common/spec-parser/specParserError.ts
- packages/fx-core/tests/common/spec-parser/specParser.test.ts
Add list function of spec parser
> perf: add spec parser list function

- packages/vscode-extension/src/codeLensProvider.ts
- packages/vscode-extension/src/extension.ts
- packages/vscode-extension/test/extension/treeview/treeViewManager.test.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_sprints/taskboard/Compute%20Team/Microsoft%20Teams%20Extensibility/CY23-6.2?workitem=21741056
> fix: adaptive cards code lens fit all folder

- Localize/loc/cs/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/cs/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/de/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/de/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/fr/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/fr/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/ja/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/ja/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/pt-BR/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/pt-BR/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/ru/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/ru/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/zh-Hans/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/zh-Hans/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/zh-Hant/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/zh-Hant/packages/vscode-extension/package.nls.json.lcl
LEGO: Pull request from juno/hb_fd34cb3d-1ea5-4a7c-8a66-721a44a97af3_20230707144558303 to dev with localized lcls
> chore(localization): [LEGO] Pull request from juno/hb_fd34cb3d-1ea5-4a7c-8a66-721a44a97af3_20230707144558303 to dev

- Localize/loc/es/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/es/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/it/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/it/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/ko/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/ko/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/pl/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/pl/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/tr/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/tr/packages/vscode-extension/package.nls.json.lcl
LEGO: Pull request from juno/hb_fd34cb3d-1ea5-4a7c-8a66-721a44a97af3_20230708144545217 to dev with localized lcls
> chore(localization): [LEGO] Pull request from juno/hb_fd34cb3d-1ea5-4a7c-8a66-721a44a97af3_20230708144545217 to dev

- packages/cli/src/userInteraction.ts
fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/24488836
> fix(cli): multiple select validation

- templates/js/link-unfurling/README.md
- templates/ts/link-unfurling/README.md
Reverts OfficeDev/TeamsFx#9174
> docs: revert readme change

- packages/cli/src/cmds/new.ts
- packages/cli/src/telemetry/cliTelemetry.ts
- packages/cli/src/telemetry/cliTelemetryEvents.ts
fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/24489826
> fix: add interactive property in cli telemetry

- packages/fx-core/src/error/deploy.ts
- packages/fx-core/tests/common/error/deployError.test.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/24489387/?view=edit
> fix: fix error message lost

- .github/CODEOWNERS
- packages/fx-core/resource/package.nls.json
- packages/fx-core/src/component/driver/interface/buildAndDeployArgs.ts
- packages/fx-core/src/component/error/componentError.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_sprints/taskboard/Compute%20Team/Microsoft%20Teams%20Extensibility/CY23-6.2?workitem=24332448
> refactor: code clean

- packages/eslint-plugin-teamsfx/config/header
- packages/eslint-plugin-teamsfx/config/shared.js
refine the header check to show notice in vscode
> refactor: update

- .github/workflows/code-cleanup-report.yml
- packages/api/tsconfig.eslint.json
- packages/cli/tsconfig.eslint.json
- packages/eslint-plugin-teamsfx/config/any-type.js
- packages/eslint-plugin-teamsfx/config/header
- packages/eslint-plugin-teamsfx/config/header.js
- packages/eslint-plugin-teamsfx/config/promise.js
- packages/eslint-plugin-teamsfx/config/shared.js
- packages/eslint-plugin-teamsfx/config/type.js
- packages/eslint-plugin-teamsfx/lib/calcHeader.js
- packages/fx-core/tsconfig.eslint.json
- packages/manifest/tsconfig.eslint.json
- packages/server/tsconfig.eslint.json
- packages/vscode-extension/tsconfig.eslint.json
https://github.com/OfficeDev/TeamsFx/actions/runs/5539692421/jobs/10110909508
> refactor: eslint type-checking

- templates/js/sso-tab-with-obo-flow/.vscode/tasks.json
- templates/ts/sso-tab-with-obo-flow/.vscode/tasks.json
- templates/ts/sso-tab-with-obo-flow/api/package.json
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/24524982
> fix: close terminal when stop debug

- .github/CODEOWNERS
- update codeowner of copilotPlugin
> ci: update codeowner

- packages/fx-core/package.json
- packages/fx-core/resource/package.nls.json
- packages/fx-core/src/component/error/componentError.ts
- packages/fx-core/src/core/middleware/errorHandler.ts
- packages/fx-core/src/error/common.ts
- packages/fx-core/tests/error/error.test.ts
fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/24514175
> fix: file permission error should be user error

- packages/fx-core/resource/package.nls.json
- packages/fx-core/src/component/generator/copilotPlugin/constant.ts
- packages/fx-core/src/component/generator/copilotPlugin/generator.ts
- packages/fx-core/src/component/generator/copilotPlugin/helper.ts
- packages/fx-core/src/question/create.ts
- packages/fx-core/tests/component/generator/copilotPluginGenerator.test.ts
- update scaffolded manifest based on open AI plugin manifest
> refactor: update manifest based on openAI plugin

- packages/tests/src/commonlib/cliHelper.ts
- packages/tests/src/e2e/upgrade/bot-sso-sample.tests.ts
- packages/tests/src/e2e/upgrade/happyPath.tests.ts
- packages/tests/src/e2e/upgrade/incoming-webhook-notification.tests.ts
- packages/tests/src/e2e/versionCheck/OpenV5ProjectByCli1.2.5.tests.ts
- packages/tests/src/utils/executor.ts
https://github.com/OfficeDev/TeamsFx/actions/runs/5572904856
https://github.com/OfficeDev/TeamsFx/actions/runs/5572641526
> refactor: upgrade e2e case

- packages/vscode-extension/src/migration/constants.ts
To fix https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/24551685.
> fix: upgrade version to 1.16 for upgrade command

- .github/workflows/lint-pr.yml
@microsoft/adaptivecards-tools	v1.3.2-rc.0
@microsoft/teamsfx-cli	v2.0.2-rc.0
@microsoft/eslint-plugin-teamsfx	v0.0.4-rc.0
@microsoft/teams-manifest	v0.1.1-rc.0
@microsoft/teamsfx-react	v3.0.1-rc.0
> ci: update the check version ci

- templates/js/non-sso-tab/README.md
- templates/ts/non-sso-tab/README.md
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/24567295
> docs: update non sso tab README

- packages/fx-core/src/core/FxCore.ts
- packages/fx-core/src/core/FxCoreImplementV3.ts
- packages/fx-core/tests/core/FxCore.test.ts
- packages/server/src/apis.ts
- packages/server/src/serverConnection.ts
- packages/server/tests/serverConnection.test.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/24569776
> feat: add Copilot related APIs for server usage

- packages/vscode-extension/src/utils/commonUtils.ts
- packages/vscode-extension/test/extension/commonUtils.test.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/24582700/?view=edit
> fix: outlook add-in app name

- packages/fx-core/resource/yaml-schema/1.1.1/yaml.schema.json
- packages/fx-core/src/common/telemetry.ts
- packages/fx-core/src/component/configManager/interface.ts
- packages/fx-core/src/component/configManager/parser.ts
- packages/fx-core/src/component/configManager/validator.ts
- packages/fx-core/src/component/generator/generator.ts
- packages/fx-core/src/component/utils/metadataUtil.ts
- packages/fx-core/tests/component/configManager/parser.test.ts
- packages/fx-core/tests/component/configManager/testing_data/bad_sample_tag.yml
- packages/fx-core/tests/component/configManager/testing_data/good_sample_tag.yml
- packages/fx-core/tests/component/configManager/validator.test.ts
- packages/fx-core/tests/component/util/metadataUtil.test.ts
feat: support sample tag in yaml schema and send sample tag telemetry
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/24585467
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/24585468
> feat: support sample tag in yaml schema and send sample tag telemetry

- templates/js/default-bot/README.md
- templates/js/m365-message-extension/README.md
- templates/js/message-extension/README.md
- templates/ts/default-bot/README.md
- templates/ts/m365-message-extension/README.md
- templates/ts/message-extension/README.md
> docs: Update App Template README

- packages/cli/src/activate.ts
- packages/cli/src/cmds/preview/commonUtils.ts
- packages/cli/src/index.ts
- packages/cli/src/telemetry/cliTelemetry.ts
- packages/cli/src/telemetry/cliTelemetryEvents.ts
- packages/cli/src/yargsCommand.ts
- packages/cli/tests/unit/cmds/index.tests.ts
- packages/cli/tests/unit/cmds/preview/commonUtils.tests.ts
- packages/cli/tests/unit/telemetry/cliTelemetry.tests.ts
- packages/cli/tests/unit/ui2.tests.ts
- packages/fx-core/tests/core/other.test.ts
fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/24599555
> fix(cli): add command usage telemetry

- packages/vscode-extension/src/codeLensProvider.ts
- packages/vscode-extension/src/extension.ts
- packages/vscode-extension/test/extension/codeLensProvider.test.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/24587069
> feat: add codelens to teamsapp.yml

- templates/js/sso-tab-with-obo-flow/infra/azure.bicep
- templates/js/sso-tab-with-obo-flow/src/components/sample/AzureFunctions.jsx
- templates/ts/sso-tab-with-obo-flow/infra/azure.bicep
fix typo: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_sprints/taskboard/AuthAndData/Microsoft%20Teams%20Extensibility/CY23-7.1?workitem=24572349
fix bug:
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/24598973
> fix(template): fix typo and add config in appsettings

- packages/fx-core/resource/yaml-schema/1.1.1/yaml.schema.json
fix: refine sample tag description
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/24599179
> fix: refine sample tag description

- packages/cli/src/cmds/preview/constants.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/24571805/
> refactor: add `listening` to default running pattern

- packages/vscode-extension/src/commonlib/cacheAccess.ts
- packages/vscode-extension/src/commonlib/common/constant.ts
1.Use secret storage API in VS Code extension login.
> refactor: use secret storage to replace keytar in vscode extension

- packages/cli/src/cmds/package.ts
- packages/cli/src/cmds/permission.ts
- packages/cli/src/cmds/update.ts
- packages/cli/src/cmds/validate.ts
- packages/cli/src/globals.ts
- packages/cli/src/questionUtils.ts
- packages/cli/src/userInteraction.ts
fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/24635238
> fix: throw error if required option is missing

- packages/vscode-extension/src/codeLensProvider.ts
- packages/vscode-extension/test/extension/codeLensProvider.test.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/24636355
> fix: add triggerFrom codelens to telemetry property

- .github/workflows/e2e-test.yml
- .github/workflows/ui-test.yml
This reverts commit 2c6db35b82d542074eb9026ae111e8bc5e09899c.
> revert: "ci: stop ui and e2e test according to compliance error (#9358)"

- packages/vscode-extension/src/qm/vsc_ui.ts
fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/24646689
> fix(vsc): ui quickpick for loading dynamic data

- packages/fx-core/src/component/coordinator/index.ts
Feature: [msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/23099199](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/23099199)
https://github.com/OfficeDev/TeamsFx/assets/107838226/eed66c05-e070-45c6-a3bc-92489a1c67db
> feat: onboarding the copilot plugin template

- packages/fx-core/resource/package.nls.json
- packages/fx-core/src/component/feature/collaboration.ts
- packages/fx-core/src/core/collaborator.ts
- packages/fx-core/src/core/error.ts
- packages/fx-core/tests/component/feature/collaboration.test.ts
- packages/fx-core/tests/core/collaborator.test.ts
- packages/tests/src/e2e/collaboration/Permission.tests.ts
bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/24539574
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/24597286
> fix: fix collaboration messages

- packages/cli/src/cmds/new.ts
- packages/cli/src/constants.ts
- packages/cli/src/utils.ts
- packages/cli/tests/unit/cmds/new.tests.ts
- packages/fx-core/src/question/create.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/24635300
> fix: teams Chef sample doesnt exist in cli template list

- packages/api/review/teamsfx-api.api.md
- packages/api/src/types.ts
- packages/fx-core/src/component/generator/copilotPlugin/helper.ts
- packages/fx-core/src/core/FxCore.ts
- packages/fx-core/src/core/FxCoreImplementV3.ts
- packages/fx-core/src/question/create.ts
- packages/fx-core/tests/core/FxCore.test.ts
- packages/fx-core/tests/question/create.test.ts
- packages/server/src/apis.ts
- packages/server/src/serverConnection.ts
- group API operations by HTTP method and sort alphabetically
> refactor: group and sort API operations

- packages/tests/src/scripts/m365Login.ts
Update m365 cache name in UI test.
> test: update test m365 cache name

- packages/fx-core/src/component/generator/copilotPlugin/generator.ts
- templates/common/simplified-message-extension-existing-api/appPackage/manifest.json.tpl
- templates/csharp/simplified-message-extension-existing-api/appPackage/manifest.json.tpl
- fix adaptive card path
- only full description will be LLM descriptor, so setting default value for others
> refactor: fix adaptive card path

- packages/fx-core/src/common/samples.ts
- packages/fx-core/tests/common/samples.test.ts
Related bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/24610139
> fix(core): remove dependency of base url in samples config

- packages/fx-core/src/component/generator/copilotPlugin/generator.ts
- packages/fx-core/src/component/generator/copilotPlugin/helper.ts
- packages/vscode-extension/src/uriHandler.ts
- packages/vscode-extension/test/extension/uriHandler.test.ts
[Task 24659850: eslint promise error for renlong - Boards (visualstudio.com)](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/24659850)
[Task 24659883](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/24659883): eslint promise error for yuqi
> refactor: eslint promise error

- .github/policies/issueCommentManagement.yml
- .github/policies/labelAdd.needsAttension.yml
- .github/policies/resourceManagement.yml
Fix: https://dev.azure.com/msazure/Microsoft%20Teams%20Extensibility/_workitems/edit/24690577
> fix: update github policy for adding attention label

- packages/fx-core/src/common/deps-checker/internal/dotnetChecker.ts
- packages/fx-core/src/common/deps-checker/internal/funcToolChecker.ts
- packages/fx-core/src/common/deps-checker/internal/nodeChecker.ts
- packages/fx-core/src/common/deps-checker/internal/vxTestAppChecker.ts
- packages/fx-core/src/common/local/localCertificateManager.ts
- packages/sdk/src/conversation/conversation.browser.ts
- packages/sdk/src/conversation/notification.browser.ts
- packages/sdk/src/conversation/notification.ts
- packages/vscode-extension/src/commonlib/cacheAccess.ts
- packages/vscode-extension/src/debug/depsChecker/vscodeLogger.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/24659827/
> refactor: depscheck, debug, notification eslint promise checks

- .github/workflows/cd_trigger.yml
> build: series should be non-empty string

- packages/vscode-extension/src/debug/launch.ts
- packages/vscode-extension/src/debug/teamsfxDebugProvider.ts
- packages/vscode-extension/src/migration/migrationHandler.ts
- packages/vscode-extension/src/migration/migrationTool/replaceSDK.ts
- packages/vscode-extension/src/migration/migrationTool/ts/importInfo.ts
- packages/vscode-extension/src/migration/migrationTool/ts/replaceEnum.ts
- packages/vscode-extension/src/migration/migrationTool/ts/replaceFunction.ts
- packages/vscode-extension/src/migration/migrationTool/ts/replaceTsImport.ts
- packages/vscode-extension/src/migration/migrationTool/ts/replaceTsInterface.ts
- packages/vscode-extension/src/migration/migrationTool/ts/replaceTsSDK.ts
- packages/vscode-extension/src/migration/migrationTool/ts/replacement.ts
- packages/vscode-extension/src/migration/migrationTool/ts/replacementsGenerator.ts
- packages/vscode-extension/test/migration/migrationHandler.test.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/24659834
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/24659974
> style: match eslint rules for debug provider, upgrade tool

- packages/cli/src/userInteraction.ts
- packages/cli/tests/unit/ui2.tests.ts
feature link: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/23777944
> feat: cli support selecFileOrInput UI

- packages/sdk/src/messageExtension/executeWithSSO.browser.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/24659857
> style: match eslint rule

- packages/fx-core/src/core/collaborator.ts
- packages/fx-core/tests/core/collaborator.test.ts
fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_sprints/taskboard/AuthAndData/Microsoft%20Teams%20Extensibility/CY23-7.2?workitem=24659851
> refactor: fix eslint error for collaboration

- packages/fx-core/package.json
- packages/fx-core/src/common/spec-parser/adaptiveCardGenerator.ts
- packages/fx-core/src/common/spec-parser/constants.ts
- packages/fx-core/src/common/spec-parser/interfaces.ts
- packages/fx-core/src/common/spec-parser/specParser.ts
- packages/fx-core/src/common/spec-parser/utils.ts
- packages/fx-core/tests/common/spec-parser/adaptiveCardGenerator.test.ts
- packages/fx-core/tests/common/spec-parser/specParser.test.ts
- packages/fx-core/tests/common/spec-parser/utils.test.ts
- Generate adaptive card support
- Add period at the end of the message: https://github.com/OfficeDev/TeamsFx/pull/9455#discussion_r1280316026
- Fix validate remote reference does not work
> perf(specParser): generate adaptive card support

- packages/fx-core/src/question/create.ts
- packages/fx-core/tests/question/create.test.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/24740863
> fix: add copilot capabilities for VS

- packages/api/review/teamsfx-api.api.md
- packages/api/src/cli.ts
- packages/api/src/index.ts
- packages/api/src/qm/question.ts
- packages/api/src/types.ts
feature link: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/24539544
sub PR of this: #9499
> feat(api): improve api to support cli new feature

- packages/fx-core/src/component/driver/devTool/installDriver.ts
- packages/vscode-extension/src/debug/commonUtils.ts
- packages/vscode-extension/src/debug/constants.ts
- packages/vscode-extension/src/debug/depsChecker/vscodeLogger.ts
- packages/vscode-extension/src/debug/prerequisitesHandler.ts
- packages/vscode-extension/src/debug/runIconHandler.ts
- packages/vscode-extension/src/debug/taskTerminal/baseTaskTerminal.ts
- packages/vscode-extension/src/debug/taskTerminal/baseTunnelTaskTerminal.ts
- packages/vscode-extension/src/debug/taskTerminal/devTunnelTaskTerminal.ts
- packages/vscode-extension/src/debug/taskTerminal/launchTeamsClientTerminal.ts
- packages/vscode-extension/src/debug/taskTerminal/prerequisiteTaskTerminal.ts
- packages/vscode-extension/src/debug/taskTerminal/utils/devTunnelStateManager.ts
- packages/vscode-extension/src/debug/teamsfxDebugProvider.ts
- packages/vscode-extension/src/debug/teamsfxTaskHandler.ts
- packages/vscode-extension/src/debug/teamsfxTaskProvider.ts
- packages/vscode-extension/src/extension.ts
- packages/vscode-extension/test/localdebug/devTunnelTaskTerminal.test.ts
Detail: 
[Task 24659964](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/24659964): Fix eslint error in vscode-extension package debug
[Task 24659838](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/24659838): eslint promise error for xiaofu
> refactor(localdebug): fix eslint error in localdebug

- docs/sdk/teamsfx.createmicrosoftgraphclient.md
- docs/sdk/teamsfx.createmicrosoftgraphclientwithcredential.md
- docs/sdk/teamsfx.msgraphauthprovider.md
- packages/fx-core/templates/plugins/resource/aad/auth/bot/README.md
- packages/fx-core/templates/plugins/resource/aad/auth/bot/js/sso/handleMessageExtensionQueryWithToken.js
- packages/fx-core/templates/plugins/resource/aad/auth/bot/js/sso/profileSsoCommandHandler.js
- packages/fx-core/templates/plugins/resource/aad/auth/bot/ts/sso/handleMessageExtensionQueryWithToken.ts
- packages/fx-core/templates/plugins/resource/aad/auth/bot/ts/sso/profileSsoCommandHandler.ts
- packages/sdk-react/src/useGraph.ts
- packages/sdk/README.md
- packages/sdk/review/teamsfx.api.md
- packages/sdk/src/core/msGraphAuthProvider.ts
- packages/sdk/src/core/msGraphClientProvider.ts
- templates/js/sso-tab-with-obo-flow/api/getUserProfile/index.js
- templates/js/sso-tab-with-obo-flow/api/package.json
- templates/ts/sso-tab-with-obo-flow/api/getUserProfile/index.ts
- templates/ts/sso-tab-with-obo-flow/api/package.json
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/24568370
> feat: migrate to use msgraph client TokenCredentialAuthenticationProvider

- packages/fx-core/src/component/driver/add/addWebPart.ts
- packages/fx-core/src/component/driver/botAadApp/create.ts
- packages/fx-core/src/component/driver/botFramework/createOrUpdateBot.ts
- packages/fx-core/src/component/driver/deploy/azure/azureStorageStaticWebsiteConfigDriver.ts
- packages/fx-core/src/component/driver/deploy/spfx/deployDriver.ts
- packages/fx-core/src/component/driver/devTool/installDriver.ts
- packages/fx-core/src/component/driver/file/createOrUpdateEnvironmentFile.ts
- packages/fx-core/src/component/driver/file/createOrUpdateJsonFile.ts
- packages/fx-core/src/component/driver/m365/acquire.ts
- packages/fx-core/src/component/driver/teamsApp/copyAppPackageToSPFx.ts
- packages/fx-core/src/component/error/componentError.ts
- packages/fx-core/src/component/generator/error.ts
- packages/fx-core/src/component/generator/generator.ts
- packages/fx-core/src/component/utils/common.ts
- packages/fx-core/tests/component/error/componentError.test.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/24541371
> fix: add error detail in inner error, fix error source confuse.

- packages/fx-core/src/component/configManager/lifecycle.ts
- packages/fx-core/src/component/generator/officeAddin/helperMethods.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/24659861
> fix: eslint error

- packages/vscode-extension/src/handlers.ts
- packages/vscode-extension/test/extension/handlers.test.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_sprints/taskboard/Teams%20Extensibility%20E2E%20Team/Microsoft%20Teams%20Extensibility/CY23-7.2?workitem=24659892
> fix: eslint promise error

- docs/sdk/teamsfx.authenticationconfiguration.md
- docs/sdk/teamsfx.handlemessageextensionquerywithtoken.md
- docs/sdk/teamsfx.teamsfx.md
- packages/fx-core/package-lock.json
- packages/sdk/review/teamsfx.api.md
- packages/sdk/src/core/teamsfx.browser.ts
- packages/sdk/src/core/teamsfx.ts
- packages/sdk/src/messageExtension/executeWithSSO.browser.ts
- packages/sdk/src/messageExtension/executeWithSSO.ts
- packages/sdk/src/models/configuration.ts
- packages/sdk/src/models/teamsfxConfiguration.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/24511951
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/24511938
> feat: deprecate TeamsFx, AuthenticationConfiguration, and handleMessageExtensionQuery with SSO

- packages/api/package.json
- packages/fx-core/package.json
- packages/fx-core/src/common/featureFlags.ts
- packages/fx-core/src/ui/visitor.ts
- packages/fx-core/tests/common/featureFlags.test.ts
- packages/fx-core/tests/ui/qm.visitor.test.ts
fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/24767022
> fix: question visitor bug

- packages/vscode-extension/src/constants.ts
- packages/vscode-extension/src/controls/webviewPanel.ts
- packages/vscode-extension/src/extension.ts
- packages/vscode-extension/src/handlers.ts
- packages/vscode-extension/test/extension/handlers.test.ts
clean up useless logic to show local preview message.
> refactor: clean up logic to show local preview message

- packages/fx-core/src/question/create.ts
- packages/fx-core/tests/question/create.test.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/24753258
> fix: capabilities for vs

- packages/fx-core/resource/package.nls.json
> refactor: update placeholder for selection api operation question

- packages/vscode-extension/src/controls/openWelcomePage.ts
- packages/vscode-extension/src/extension.ts
- packages/vscode-extension/src/globalVariables.ts
- packages/vscode-extension/src/handlers.ts
- packages/vscode-extension/src/utils/upgrade.ts
- packages/vscode-extension/test/extension/controls/openWelcomePage.test.ts
- packages/vscode-extension/test/extension/globalVariables.test.ts
- packages/vscode-extension/test/extension/handlers.test.ts
Related bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/24568693
> fix(vsc): activation sync tasks and background jobs

- packages/fx-core/src/question/create.ts
- packages/tests/src/commonlib/constants.ts
- packages/tests/src/e2e/bot/MessageExtensionHappyPath.dotnet.tests.ts
- packages/tests/src/e2e/bot/MessageExtensionHappyPath.tests.ts
fix e2e: https://github.com/OfficeDev/TeamsFx/actions/runs/5791997132
> test: fix message-extension e2e test case

- packages/fx-core/src/common/featureFlags.ts
- packages/fx-core/src/core/FxCoreImplementV3.ts
- packages/fx-core/src/question/create.ts
- packages/fx-core/tests/core/FxCore.test.ts
- packages/fx-core/tests/question/create.test.ts
- packages/vscode-extension/src/handlers.ts
> refactor: use pre-defined key name

- packages/tests/src/ui-test/migration/3.x-sso-tab-bot-function/3.x-sso-tab-bot-function-debug-upgrade-debug.test.ts
- packages/tests/src/ui-test/migration/3.x-sso-tab-bot-function/3.x-sso-tab-bot-function-provision-upgrade-provision-debug.test.ts
- packages/tests/src/ui-test/migration/3.x-sso-tab-bot-function/3.x-sso-tab-bot-function-upgrade-debug.test.ts
- packages/tests/src/ui-test/migration/3.x-sso-tab-bot-function/3.x-sso-tab-bot-function-upgrade-provision-debug.test.ts
- packages/tests/src/ui-test/migration/4.0.0-sso-tab-bot-function/4.0.0-sso-tab-bot-function-debug-upgrade-debug.test.ts
- packages/tests/src/ui-test/migration/4.0.0-sso-tab-bot-function/4.0.0-sso-tab-bot-function-provision-upgrade-provision-debug.test.ts
- packages/tests/src/ui-test/migration/4.0.0-sso-tab-bot-function/4.0.0-sso-tab-bot-function-upgrade-debug.test.ts
- packages/tests/src/ui-test/migration/4.0.0-sso-tab-bot-function/4.0.0-sso-tab-bot-function-upgrade-provision-debug.test.ts
- packages/tests/src/ui-test/migration/migrationContext.ts
- packages/tests/src/ui-test/migration/sso-tab-bot-function/sso-tab-bot-function-debug-upgrade-debug.test.ts
- packages/tests/src/ui-test/migration/sso-tab-bot-function/sso-tab-bot-function-provision-upgrade-provision-debug.test.ts
- packages/tests/src/ui-test/migration/sso-tab-bot-function/sso-tab-bot-function-upgrade-debug.test.ts
- packages/tests/src/ui-test/migration/sso-tab-bot-function/sso-tab-bot-function-upgrade-provision-debug.test.ts
- packages/tests/src/ui-test/migration/sso-tab-func/sso-tab-function-debug-upgrade-debug.test.ts
- packages/tests/src/ui-test/migration/sso-tab-func/sso-tab-function-provision-upgrade-provision-debug.test.ts
- packages/tests/src/ui-test/migration/sso-tab-func/sso-tab-function-upgrade-debug.test.ts
- packages/tests/src/ui-test/migration/sso-tab-func/sso-tab-function-upgrade-provision-debug.test.ts
- packages/tests/src/ui-test/testContext.ts
- packages/tests/src/utils/commonUtils.ts
Fix: https://dev.azure.com/msazure/Microsoft%20Teams%20Extensibility/_workitems/edit/24704852
> fix: easy auth issue for function.bicep

- packages/cli/src/cmds/validate.ts
- packages/cli/tests/unit/cmds/validate.tests.ts
fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/24704915
> fix: cli validation inputs for non-interactive mode

- packages/vscode-extension/src/handlers.ts
- packages/vscode-extension/test/extension/handlers.test.ts
Fix eslint issue: [Task 24767116](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/24767116): Fix VSC eslint error in handlers.ts
> refactor: fix eslint issue in handler related to rentu

- packages/vscode-extension/package.nls.json
- packages/vscode-extension/src/handlers.ts
- packages/vscode-extension/src/telemetry/extTelemetryEvents.ts
- packages/vscode-extension/test/extension/handlers.test.ts
Feature: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/24450777
Effect:
> feat(vsc): add similar issues button

- packages/fx-core/src/core/FxCoreImplementV3.ts
Related bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/24778787
> fix(core): incorrect import

- packages/sdk/src/conversation/sso/defaultBotSsoExecutionActivityHandler.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_sprints/taskboard/AuthAndData/Microsoft%20Teams%20Extensibility/CY23-7.2?workitem=24753428
> perf(sdk): remove deprecated teamsfx class in DefaultBotSsoExecutionActivityHandler

- packages/fx-core/resource/yaml-schema/v1.2/yaml.schema.json
- packages/fx-core/src/component/configManager/interface.ts
- packages/fx-core/src/component/configManager/lifecycle.ts
- packages/fx-core/src/component/configManager/parser.ts
- packages/fx-core/src/component/configManager/validator.ts
- packages/fx-core/src/component/generator/officeAddin/helperMethods.ts
- packages/fx-core/src/component/utils/metadataUtil.ts
- packages/fx-core/src/core/middleware/utils/v3MigrationUtils.ts
- packages/fx-core/tests/component/configManager/parser.test.ts
- packages/fx-core/tests/component/configManager/testing_data/bad_sample_tag.yml
- packages/fx-core/tests/component/configManager/testing_data/good_sample_tag.yml
- packages/fx-core/tests/component/configManager/validator.test.ts
- packages/fx-core/tests/component/util/metadataUtil.test.ts
- packages/fx-core/tests/core/middleware/migration/projectMigrationV3.test.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/24705240
> feat: support additionalMetadata and sampleTag

- packages/fx-core/resource/package.nls.json
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/24705240
Fix string issue in https://github.com/OfficeDev/TeamsFx/pull/9533
> fix: fix error message when suggesting upgrading to the latest TTK

- packages/tests/src/ui-test/localdebug/localdebugContext.ts
> test: update message command

- packages/api/review/teamsfx-api.api.md
- packages/api/src/qm/question.ts
- packages/cli/src/commands/common.ts
- packages/cli/src/commands/models/validate.ts
- packages/cli/src/resource/strings.json
- packages/fx-core/src/question/create.ts
- packages/fx-core/src/question/generator.ts
- packages/fx-core/src/question/inputs/CreateProjectInputs.ts
- packages/fx-core/src/question/options/CreateProjectOptions.ts
feature link: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/24539544
improvement question model support hidden CLI option
> feat: improve question model for run-time node

- packages/api/review/teamsfx-api.api.md
- packages/api/src/qm/question.ts
- packages/cli/src/cmds/new.ts
- packages/cli/src/commands/models/create.ts
- packages/cli/src/commands/models/createSample.ts
- packages/cli/src/questionUtils.ts
- packages/fx-core/src/error/common.ts
- packages/fx-core/src/question/create.ts
- packages/fx-core/src/ui/validationUtils.ts
- packages/fx-core/src/ui/visitor.ts
- packages/fx-core/tests/core/FxCore.test.ts
- packages/fx-core/tests/question/create.test.ts
- packages/fx-core/tests/ui/qm.visitor.test.ts
- packages/fx-core/tests/ui/validationUtils.test.ts
fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/24794530
1. Remove "func" type question
2. Fix questionVisitor function for non-interactive mode (validation and auto skip logic)
> fix: cli create flow

- packages/cli/src/commands/common.ts
- packages/cli/src/commands/models/create.ts
- packages/cli/src/commands/models/createSample.ts
- packages/fx-core/src/question/create.ts
- packages/fx-core/src/question/generator.ts
- packages/fx-core/src/question/options/CreateProjectOptions.ts
- packages/fx-core/src/question/options/CreateSampleProjectOptions.ts
- packages/fx-core/tests/question/create.test.ts
fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/17099417
> fix: cli default folder

- packages/cli/src/userInteraction.ts
- packages/cli/tests/unit/ui2.tests.ts
- packages/fx-core/src/question/create.ts
- packages/fx-core/tests/question/create.test.ts
E2E TEST: https://github.com/OfficeDev/TeamsFx/actions/runs/5818423372 provision failed due to quota.
- add validation support for selectFileOrInput
- add additionalValidationOnAccept in CLI
> feat: cli supports selectFileOrInput with additionalValidationOnAccept

- packages/cli/src/index.ts
fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/24792747
> fix: cli version

- packages/fx-core/src/component/driver/teamsApp/appStudio.ts
fix(core): unblock "update manifest" UI interaction e7ad3d8d4 
> fix(core): unblock "update manifest" UI interaction

- packages/tests/scripts/pvt.json
- packages/tests/src/ui-test/migration/notification-bot-func-http/notification-bot-func-debug-upgrade-debug-ts.test.ts
- packages/tests/src/ui-test/migration/notification-bot-func-http/notification-bot-func-debug-upgrade-debug.test.ts
- packages/tests/src/ui-test/migration/notification-bot-func-http/notification-bot-func-upgrade-debug-ts.test.ts
- packages/tests/src/ui-test/migration/notification-bot-func-http/notification-bot-func-upgrade-debug.test.ts
- packages/tests/src/ui-test/migration/notification-bot-restify/notification-bot-restify-debug-upgrade-debug-ts.test.ts
- packages/tests/src/ui-test/migration/notification-bot-restify/notification-bot-restify-debug-upgrade-debug.test.ts
- packages/tests/src/ui-test/migration/notification-bot-restify/notification-bot-restify-upgrade-debug-ts.test.ts
- packages/tests/src/ui-test/migration/notification-bot-restify/notification-bot-restify-upgrade-debug.test.ts
- packages/tests/src/utils/constants.ts
test: extend total test case running time for some migrating test cases,
test: update case name in pvt file list
> test: extend total test case running time for some migrating test cases

- packages/dotnet-sdk/src/TeamsFx/Conversation/NotificationBot.cs
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/24780695
Related bug:
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/23949699
> feat(dotnet-sdk): add validationEnabled param to getPagedInstallationAsync

- packages/cli/src/cmds/provision.ts
- packages/cli/src/constants.ts
- packages/cli/tests/unit/cmds/provision.tests.ts
- packages/fx-core/src/component/coordinator/index.ts
- packages/fx-core/src/component/provisionUtils.ts
- packages/fx-core/src/component/utils/ResourceGroupHelper.ts
- packages/fx-core/tests/component/provisionUtils.test.ts
- packages/fx-core/tests/component/resourceGroupHelper.test.ts
fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/24807442
> fix: cli support region option

- packages/vscode-extension/src/debug/taskTerminal/launchTeamsClientTerminal.ts
fix: launch Teams  web client in codespace ea41f32f2 
> fix: launch Teams web client in codespace

- packages/cli/src/commands/engine.ts
- packages/cli/src/yargsCommand.ts
- packages/cli/tests/unit/engine.tests.ts
- packages/cli/tests/unit/yargsCommand.tests.ts
fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/24832468
> fix: cli error print

- packages/vscode-extension/src/handlers.ts
fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/24767119
> fix(vsc): eslint for showError()

- packages/fx-core/src/core/FxCore.ts
- packages/fx-core/tests/core/FxCore.test.ts
fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/24846318
> fix: get questions

- packages/dotnet-sdk/CHANGELOG.md
- packages/dotnet-sdk/README.md
- packages/dotnet-sdk/src/TeamsFx/Microsoft.TeamsFx.csproj
- packages/dotnet-sdk/src/TeamsFx/MsGraphAuthProvider.cs
- packages/dotnet-sdk/src/TeamsFx/TeamsFx.cs
- packages/fx-core/templates/plugins/resource/aad/auth/V3/Tab/GetUserProfile.razor
- packages/fx-core/templates/plugins/resource/aad/auth/tab/csharp/GetUserProfile.razor
- templates/csharp/sso-tab/Components/Graph.razor
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/24511911
> feat(sdk): migrate to use GraphServiceClient and deprecate MsGraphAuthProviders

- packages/fx-core/src/component/generator/spfx/depsChecker/yoChecker.ts
- packages/fx-core/tests/plugins/resource/spfx/depsChecker/yoChecker.test.ts
ADO: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/24818168
> fix: extend timeout to avoid latest package fetch failure

- packages/cli/src/activate.ts
- packages/cli/tests/unit/engine.tests.ts
featlink: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/24539544
Display info level log in CLI
> feat: new logger for new ux

- packages/api/review/teamsfx-api.api.md
- packages/api/src/qm/ui.ts
- packages/cli/src/userInteraction.ts
- packages/cli/tests/unit/ui2.tests.ts
- packages/fx-core/src/component/generator/copilotPlugin/helper.ts
- packages/fx-core/src/question/create.ts
- packages/fx-core/src/ui/visitor.ts
- packages/fx-core/tests/question/create.test.ts
- packages/vscode-extension/src/qm/vsc_ui.ts
- update selectFileOrInput. "validation" will be the property used to do final validation after user confirm the input, which could possibly be a local file path or remote URL.
> refactor: select file or input validation

- packages/cli/src/commands/engine.ts
- packages/cli/src/error.ts
- packages/cli/src/resource/strings.json
- packages/cli/tests/unit/engine.tests.ts
fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/24868704
> fix(cli): unknown cmd error message

- packages/fx-core/src/component/configManager/lifecycle.ts
feature link: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/24878271
> feat: config manager log

- packages/fx-core/src/component/driver/script/scriptDriver.ts
- packages/fx-core/tests/component/driver/script/scriptDriver.test.ts
feature link: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/24878298
> feat: script driver log

- templates/js/sso-tab-with-obo-flow/README.md
fix bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_sprints/taskboard/AuthAndData/Microsoft%20Teams%20Extensibility/Gallium/CY23Q3/2Wk/2Wk11%20(Aug%2013%20-%20Aug%2026)?workitem=24816752
> docs: update readme for obo template

- packages/cli/src/commands/engine.ts
- packages/cli/src/commands/models/create.ts
- packages/cli/src/commands/models/createSample.ts
- packages/cli/tests/unit/engine.tests.ts
fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/24879122
> fix: skip folder question for interactive mode

- packages/fx-core/src/component/configManager/interface.ts
- packages/fx-core/src/component/configManager/lifecycle.ts
- packages/fx-core/src/component/driver/interface/stepDriver.ts
- packages/fx-core/tests/component/configManager/lifecycle.test.ts
- packages/fx-core/tests/component/coordinator/coordinator.deploy.test.ts
- packages/fx-core/tests/component/coordinator/coordinator.provision.test.ts
- packages/fx-core/tests/component/coordinator/coordinator.publish.test.ts
- packages/fx-core/tests/component/coordinator/coordinator.test.ts
- packages/fx-core/tests/component/middleware/helper.ts
- packages/fx-core/tests/component/middleware/middleware.test.ts
- packages/fx-core/tests/component/util/metadataUtil.test.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/24599186
> refactor: remove deprecated run() from Driver interface

- packages/cli/src/commands/engine.ts
- packages/cli/src/commands/models/envAdd.ts
- packages/cli/src/commands/models/m365LaunchInfo.ts
- packages/cli/src/commands/models/m365Sideloading.ts
- packages/cli/src/commands/models/m365Unacquire.ts
- packages/cli/src/commands/models/permissionGrant.ts
- packages/cli/src/commands/models/permissionStatus.ts
- packages/cli/src/commands/models/preview.ts
- packages/cli/src/commands/models/publish.ts
- packages/cli/src/commands/models/updateAadApp.ts
- packages/cli/src/commands/models/updateTeamsApp.ts
- packages/cli/src/commands/models/validate.ts
- packages/fx-core/src/ui/visitor.ts
- packages/fx-core/tests/ui/qm.visitor.test.ts
fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/24894304
> fix: cli cmds with default interactive mode false

- .github/policies/issueCommentManagement.yml
Fix bug: https://dev.azure.com/msazure/Microsoft%20Teams%20Extensibility/_workitems/edit/24856177
> fix: add need attention label for PR

- packages/fx-core/src/component/driver/script/scriptDriver.ts
fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/24895521
> fix: script action has no run

- packages/tests/src/e2e/collaboration/Permission.tests.ts
test faiiled due to quota issue in central us. Provision to east us instead.
bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/24880037
success run: https://github.com/OfficeDev/TeamsFx/actions/runs/5923849741/job/16060403680
> test: fix failed e2e for collaboration

- packages/tests/scripts/pvt.json
- packages/tests/src/ui-test/localdebug/localdebug-bot-ts.test.ts
- packages/tests/src/ui-test/localdebug/localdebug-bot-twice.test.ts
- packages/tests/src/ui-test/localdebug/localdebug-bot.test.ts
- packages/tests/src/ui-test/localdebug/localdebug-msg-ts.test.ts
- packages/tests/src/ui-test/localdebug/localdebug-msg.test.ts
- packages/tests/src/ui-test/localdebug/localdebug-tab-regen-appid.test.ts
- packages/tests/src/utils/playwrightOperation.ts
1. update the debug item name for bot and msg project
2. try send a message to notification bot if no response
3. using node 16 to run local debug of tab regen appid
> test: update the debug item name

- packages/cli/src/commands/models/permissionGrant.ts
- packages/cli/tests/unit/commands.tests.ts
- packages/fx-core/src/question/other.ts
fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/24897495
> fix: permission grant input validation for question model and non-interactive mode

- packages/fx-core/src/component/coordinator/index.ts
- packages/fx-core/src/component/middleware/envMW.ts
- packages/fx-core/src/ui/visitor.ts
- packages/fx-core/tests/core/utils.ts
- packages/fx-core/tests/plugins/solution/util.ts
- packages/fx-core/tests/ui/qm.visitor.test.ts
fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/24878278
> fix: add debug log in core

- packages/cli/src/commands/models/m365LaunchInfo.ts
- packages/cli/src/commands/models/m365Sideloading.ts
- packages/cli/src/commands/models/m365Unacquire.ts
- packages/fx-core/src/common/m365/packageService.ts
- packages/fx-core/src/component/driver/botFramework/createOrUpdateBot.ts
- packages/fx-core/src/component/driver/devTool/installDriver.ts
- packages/fx-core/src/component/driver/file/createOrUpdateEnvironmentFile.ts
- packages/fx-core/src/component/driver/m365/acquire.ts
- packages/fx-core/src/component/resource/botService/botRegistration/botFrameworkRegistration.ts
- packages/fx-core/tests/common/m365/packageService.test.ts
- packages/fx-core/tests/component/driver/botFramework/createOrUpdateBot.test.ts
- packages/fx-core/tests/component/driver/devTool/installDriver.test.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/24878293/
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/24878290/
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/24878286/
> refactor: add debug and verbose log to m365, bot, file, devtool drivers

- packages/tests/src/e2e/frontend/BasicTabHappyPath.tests.ts
- packages/tests/src/e2e/frontend/BlazorAppHappyPath.tests.ts
- packages/tests/src/e2e/frontend/TestCreateTab.tests.ts
E2E tests passed: https://github.com/OfficeDev/TeamsFx/actions/runs/5936297926/job/16097893840
> test: change region for quota issue

- packages/fx-core/src/component/driver/script/scriptDriver.ts
fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/24895069
> fix: script stderr shown as warning log

- packages/server/src/serverConnection.ts
> fix(server): preview options

- packages/cli/src/colorize.ts
- packages/cli/src/commonlib/log.ts
- packages/cli/src/commonlib/logger.ts
- packages/cli/src/resource/strings.json
fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/24906340
> fix(cli): successful figures

- docs/sdk/teamsfx.botssoexecutionactivityhandler.handleteamssignintokenexchange.md
- docs/sdk/teamsfx.invokeresponsefactory.md
- docs/sdk/teamsfx.teamsfxadaptivecardactionhandler.handleactioninvoked.md
- packages/sdk/package.json
- packages/sdk/src/conversation/interface.ts
- packages/sdk/src/conversation/invokeResponseFactory.ts
- packages/sdk/src/conversation/sso/defaultBotSsoExecutionActivityHandler.ts
- pnpm-lock.yaml
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/24930627
> fix: fix sdk build warning

- packages/fx-core/src/common/spec-parser/adaptiveCardGenerator.ts
- packages/fx-core/src/common/spec-parser/constants.ts
- packages/fx-core/src/common/spec-parser/interfaces.ts
- packages/fx-core/src/common/spec-parser/manifestUpdater.ts
- packages/fx-core/src/common/spec-parser/specParser.ts
- packages/fx-core/src/common/spec-parser/utils.ts
- packages/fx-core/tests/common/spec-parser/adaptiveCardGenerator.test.ts
- packages/fx-core/tests/common/spec-parser/manifestUpdater.test.ts
- packages/fx-core/tests/common/spec-parser/specParser.test.ts
- packages/fx-core/tests/common/spec-parser/utils.test.ts
1. support partial generate adaptive card
2. support empty schema
3. support response code 20X
4. filter api without json response
5. support required parameter <=1
> perf(specParser): support partial generate ac, support empty schema

- templates/csharp/default-bot/Bot/EchoBot.cs.tpl
> fix: modify welcome msg of echo bot

- packages/fx-core/src/question/create.ts
- packages/fx-core/tests/question/create.test.ts
fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/24906494
> fix(cli): cli default folder for new command

- packages/cli/package.json
- pnpm-lock.yaml
fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/24932885
> fix: cli depedency of lodash

- templates/csharp/message-extension-action/Action/ActionApp.cs.tpl
- templates/csharp/message-extension-action/Resources/helloWorldCard.json
- templates/csharp/message-extension-action/{{ProjectName}}.csproj.tpl
- templates/csharp/message-extension-search/Resources/helloWorldCard.json
- templates/csharp/message-extension-search/Search/SearchApp.cs.tpl
- templates/csharp/message-extension-search/{{ProjectName}}.csproj.tpl
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/24869801/
> refactor: move adaptive cards to json file for c# message extension templates

- packages/cli/src/commands/models/index.ts
- packages/cli/src/commands/models/list.ts
- packages/cli/src/commands/models/listTemplates.ts
- packages/cli/tests/unit/commands.tests.ts
- packages/cli/tests/unit/engine.tests.ts
- packages/fx-core/src/question/create.ts
- packages/fx-core/src/question/options/CreateProjectOptions.ts
- packages/fx-core/src/question/options/CreateSampleProjectOptions.ts
fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/24944725
> fix(cli): rename list capabilities

- packages/fx-core/src/core/FxCore.ts
fix: fix vs add sso failure 30572c2e0 
> fix: fix vs add sso failure

- packages/cli/src/colorize.ts
- packages/cli/src/commonlib/logger.ts
- packages/cli/src/prompts/customizedCheckboxPrompt.ts
- packages/cli/src/prompts/customizedListPrompt.ts
- packages/cli/tests/unit/colorize.tests.ts
fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/24946528
> fix: visiable for white backgroup color

- Localize/loc/cs/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/cs/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/de/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/de/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/es/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/es/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/fr/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/fr/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/it/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/it/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/ja/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/ja/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/ko/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/ko/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/pl/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/pl/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/pt-BR/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/pt-BR/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/ru/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/ru/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/tr/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/tr/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/zh-Hans/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/zh-Hans/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/zh-Hant/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/zh-Hant/packages/vscode-extension/package.nls.json.lcl
LEGO: Pull request from juno/hb_fd34cb3d-1ea5-4a7c-8a66-721a44a97af3_20230826144451528 to dev with localized lcls
> chore(localization): [LEGO] Pull request from juno/hb_fd34cb3d-1ea5-4a7c-8a66-721a44a97af3_20230826144451528 to dev

- packages/cli/src/commands/helper.ts
- packages/fx-core/src/component/coordinator/index.ts
- packages/fx-core/src/question/create.ts
- packages/fx-core/src/question/options/CreateProjectOptions.ts
- packages/fx-core/src/question/options/CreateSampleProjectOptions.ts
- packages/fx-core/tests/question/create.test.ts
fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/24948973
> fix(cli): new default folder

- packages/fx-core/src/component/driver/deploy/azure/azureStorageDeployDriver.ts
- packages/fx-core/src/component/driver/deploy/azure/impl/AzureZipDeployImpl.ts
- packages/fx-core/src/component/driver/deploy/azure/impl/azureDeployImpl.ts
- packages/fx-core/src/component/driver/deploy/azure/impl/baseDeployImpl.ts
- packages/fx-core/tests/component/driver/deploy/azure/AzureDeployImpl.test.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_sprints/taskboard/Compute%20Team/Microsoft%20Teams%20Extensibility/Gallium/CY23Q3/2Wk/2Wk11%20(Aug%2013%20-%20Aug%2026)?workitem=24878287
> feat: add deploy driver log

- packages/vscode-extension/package.json
> refactor: description

- packages/fx-core/src/common/constants.ts
- packages/fx-core/src/common/samples.ts
- packages/fx-core/tests/common/samples.test.ts
Related task: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/24610127
Download design:
1. stable version uses bundled tag.
2. prerelease version uses bundled branch head for prerelease.
3. rc version uses bunded tag.
4. daily release uses 'dev' branch.
5. stable version uses environment variable _TEAMSFX_SAMPLE_CONFIG_BRANCH_ branch if available.
> feat(core): enable feature flag when downloading samples

- packages/fx-core/tests/component/generator/copilotPluginGenerator.test.ts
- packages/fx-core/tests/component/generator/generator.test.ts
- packages/fx-core/tests/component/generator/officeAddinGenerator.test.ts
- packages/fx-core/tests/component/generator/spfxGenerator.test.ts
Clean up ./tmp folder after unit test.
> test: refine ut clean up

- .github/workflows/cd_trigger.yml
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/24962937
> fix: fix github action injection

- packages/fx-core/package.json
- pnpm-lock.yaml
fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/24964178
> fix(fx-core): node-forge vulnerabilities

- packages/cli/src/commands/models/upgrade.ts
fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/24946024
> fix(cli): upgrade

- packages/cli/src/commands/models/createSample.ts
fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/24931789
> fix(cli): create sample project name color

- packages/cli/src/commands/helper.ts
- packages/cli/tests/unit/helper.tests.ts
fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/24931819
> fix(cli): default value of interactive option

- templates/csharp/copilot-plugin-existing-api/GettingStarted.md
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/24894109
> feat(vs): add getting started for copilot exising api template

- packages/fx-core/src/common/spec-parser/interfaces.ts
- packages/fx-core/src/common/spec-parser/manifestUpdater.ts
- packages/fx-core/src/component/driver/teamsApp/createAppPackage.ts
- packages/fx-core/tests/common/spec-parser/manifestUpdater.test.ts
- packages/fx-core/tests/component/driver/teamsApp/createAppPackage.test.ts
- packages/fx-core/tests/component/generator/copilotPluginGenerator.test.ts
- packages/fx-core/tests/core/FxCore.test.ts
- packages/manifest/src/index.ts
- packages/manifest/src/manifest.ts
- packages/vscode-extension/test/extension/codeLensProvider.test.ts
- templates/js/copilot-plugin-from-scratch/appPackage/manifest.json.tpl
- templates/ts/copilot-plugin-from-scratch/appPackage/manifest.json.tpl
- Update manifest renaming "type" to "composeExtensionType"
- Edit related code
> refactor: manifest update renaming to composeExtensionType

- packages/fx-core/src/common/m365/launchHelper.ts
- packages/fx-core/src/core/FxCore.ts
- packages/fx-core/tests/common/m365/launchHelper.test.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/23094134
> feat: support preview copilot plugin from treeview

- packages/fx-core/src/common/spec-parser/constants.ts
- packages/fx-core/src/common/spec-parser/interfaces.ts
- packages/fx-core/src/common/spec-parser/manifestUpdater.ts
- packages/fx-core/src/common/spec-parser/specFilter.ts
- packages/fx-core/src/common/spec-parser/specParser.ts
- packages/fx-core/src/common/spec-parser/utils.ts
- packages/fx-core/tests/common/spec-parser/manifestUpdater.test.ts
- packages/fx-core/tests/common/spec-parser/specFilter.test.ts
- packages/fx-core/tests/common/spec-parser/specParser.test.ts
- packages/fx-core/tests/common/spec-parser/utils.test.ts
- packages/fx-core/tests/question/create.test.ts
1. Support post operation
2. Update server validation
> perf(spec-parser): support post and update server validation

- packages/cli/src/commands/models/m365.ts
fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/24979692
> fix(cli): expose m365 command

- packages/fx-core/src/component/driver/deploy/azure/azureAppServiceDeployDriver.ts
- packages/fx-core/src/component/driver/deploy/azure/azureFunctionDeployDriver.ts
- packages/fx-core/src/component/driver/deploy/azure/azureStorageDeployDriver.ts
- packages/fx-core/src/component/driver/script/baseBuildStepDriver.ts
- packages/fx-core/src/component/driver/script/dotnetBuildDriver.ts
- packages/fx-core/src/component/driver/script/npmBuildDriver.ts
- packages/fx-core/src/component/driver/script/npxBuildDriver.ts
- packages/fx-core/tests/component/driver/deploy/azure/azureAppServiceDeployDriver.test.ts
- packages/fx-core/tests/component/driver/deploy/azure/azureFunctionDeployDriver.test.ts
- packages/fx-core/tests/component/driver/deploy/azure/azureStorageDeployDriver.test.ts
- packages/fx-core/tests/component/driver/script/dotnetBuildDriver.test.ts
- packages/fx-core/tests/component/driver/script/npmBuildDriver.test.ts
- packages/fx-core/tests/component/driver/script/npxBuildDriver.test.ts
* cleanup the run() method from all action
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_sprints/taskboard/Compute%20Team/Microsoft%20Teams%20Extensibility/Gallium/CY23Q3/2Wk/2Wk11%20(Aug%2013%20-%20Aug%2026)?workitem=24895503
> refactor: cleanup run() method from action

- packages/adaptivecards-tools-sdk/.eslintrc.js
- packages/adaptivecards-tools-sdk/package.json
- pnpm-lock.yaml
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/24964158
> fix: fix vulnerable dependency

- packages/fx-core/src/component/driver/teamsApp/createAppPackage.ts
- packages/fx-core/src/component/driver/teamsApp/utils/ManifestUtils.ts
- packages/fx-core/src/component/driver/teamsApp/validate.ts
- packages/fx-core/src/core/FxCore.ts
> refactor: add telemetry property

- Localize/loc/ru/packages/fx-core/resource/package.nls.json.lcl
LEGO: Pull request from juno/hb_fd34cb3d-1ea5-4a7c-8a66-721a44a97af3_20230830144500857 to dev with localized lcls
> chore(localization): [LEGO] Pull request from juno/hb_fd34cb3d-1ea5-4a7c-8a66-721a44a97af3_20230830144500857 to dev

- packages/cli/src/commands/models/create.ts
fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25017053
> fix(cli): create example issue

- packages/fx-core/src/common/tools.ts
- packages/fx-core/src/component/driver/teamsApp/interfaces/appdefinitions/messagingExtension.ts
- packages/fx-core/src/component/driver/teamsApp/interfaces/appdefinitions/messagingExtensionCommand.ts
- packages/fx-core/src/component/driver/teamsApp/utils/utils.ts
- packages/fx-core/tests/common/tools.test.ts
- packages/fx-core/tests/component/resource/appManifest/utils.test.ts
1) Update app definition
2) Int env doesn't support regional endpoint
> refactor: update app definition based latest API

- Localize/loc/cs/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/de/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/es/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/fr/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/it/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/ja/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/pt-BR/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/zh-Hans/packages/fx-core/resource/package.nls.json.lcl
LEGO: Pull request from juno/hb_fd34cb3d-1ea5-4a7c-8a66-721a44a97af3_20230831144643582 to dev with localized lcls
> chore(localization): [LEGO] Pull request from juno/hb_fd34cb3d-1ea5-4a7c-8a66-721a44a97af3_20230831144643582 to dev

- packages/fx-core/src/component/coordinator/index.ts
fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25020642
> fix: default resource group name for provision

- packages/fx-core/src/question/create.ts
- packages/fx-core/tests/question/create.test.ts
fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25020439
> fix(cli): teamsfx new flow parity with vscode create project flow

- packages/fx-core/src/question/create.ts
- packages/fx-core/tests/question/create.test.ts
fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25038851
> fix: cli non-interactive capabilities options

- packages/cli/src/commands/models/listTemplates.ts
- packages/fx-core/src/question/create.ts
- packages/fx-core/tests/question/create.test.ts
fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25038851
> fix: capability dynamic options

- Localize/loc/ko/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/pl/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/tr/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/zh-Hant/packages/fx-core/resource/package.nls.json.lcl
LEGO: Pull request from juno/hb_fd34cb3d-1ea5-4a7c-8a66-721a44a97af3_20230901144811460 to dev with localized lcls
> chore(localization):[LEGO] Pull request from juno/hb_fd34cb3d-1ea5-4a7c-8a66-721a44a97af3_20230901144811460 to dev

- packages/fx-core/src/common/telemetry.ts
- packages/fx-core/src/component/configManager/lifecycle.ts
- packages/fx-core/src/component/constants.ts
- packages/fx-core/src/component/driver/aad/create.ts
- packages/fx-core/src/component/driver/aad/update.ts
- packages/fx-core/src/component/driver/botAadApp/create.ts
- packages/fx-core/src/component/feature/collaboration.ts
- packages/fx-core/src/error/common.ts
- packages/fx-core/tests/component/driver/botAadApp/create.test.ts
fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25051477
> fix: keep inner error for unhandled user error

- packages/fx-core/src/common/m365/packageService.ts
- packages/fx-core/tests/common/m365/packageService.test.ts
Fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25051267
> fix: handle invalid url error in m365

- packages/fx-core/src/question/create.ts
- packages/fx-core/src/question/options/CreateProjectOptions.ts
fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25053517
> fix: cli framework type description

- packages/vscode-extension/src/extension.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25019256
> feat: add codelens for sme openapi spec file

- packages/cli/src/commands/models/listTemplates.ts
fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25063418
> fix(cli): list templates ui adjust

- packages/server/buildExe.js
- packages/server/src/providers/userInteraction.ts
- packages/server/src/utils.ts
- packages/server/tests/utils.test.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/24917760
> fix(server): calculate default value before calling UX

- .github/CODEOWNERS
- packages/fx-core/src/question/create.ts
- packages/fx-core/src/question/inputs/CreateProjectInputs.ts
- packages/fx-core/src/question/options/CreateProjectOptions.ts
- packages/fx-core/tests/question/create.test.ts
- packages/tests/src/commonlib/constants.ts
- packages/tests/src/e2e/bot/EchoBotHappyPath.dotnet.tests.ts
- packages/tests/src/e2e/bot/EchoBotHappyPath.tests.ts
- packages/tests/src/e2e/bot/LinkUnfurlingHappyPath.dotnet.tests.ts
- packages/tests/src/e2e/bot/MessageExtensionActionHappyPath.dotnet.tests.ts
- packages/tests/src/e2e/bot/MessageExtensionActionHappyPath.tests.ts
- packages/tests/src/e2e/bot/MessageExtensionSearchHappyPath.dotnet.tests.ts
- packages/tests/src/e2e/m365/DebugLinkUnfurling.tests.ts
- packages/tests/src/e2e/m365/DeployLinkUnfurling.tests.ts
- packages/tests/src/utils/constants.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/24906399/
> test: add e2e test for echo bot and message extension

- packages/fx-core/resource/package.nls.json
- templates/csharp/command-and-response/infra/azure.bicep
- templates/csharp/notification-webapi/infra/azure.bicep
- templates/csharp/workflow/infra/azure.bicep
- templates/js/ai-bot/infra/azure.bicep
- templates/js/command-and-response/infra/azure.bicep
- templates/js/default-bot-message-extension/infra/azure.bicep
- templates/js/default-bot/infra/azure.bicep
- templates/js/link-unfurling/infra/azure.bicep
- templates/js/m365-message-extension/infra/azure.bicep
- templates/js/message-extension-action/infra/azure.bicep
- templates/js/message-extension/infra/azure.bicep
- templates/js/non-sso-tab-default-bot/infra/azure.bicep
- templates/js/non-sso-tab/infra/azure.bicep
- templates/js/notification-restify/infra/azure.bicep
- templates/js/workflow/infra/azure.bicep
- templates/ts/ai-bot/infra/azure.bicep
- templates/ts/command-and-response/infra/azure.bicep
- templates/ts/default-bot-message-extension/infra/azure.bicep
- templates/ts/default-bot/infra/azure.bicep
- templates/ts/link-unfurling/infra/azure.bicep
- templates/ts/m365-message-extension/infra/azure.bicep
- templates/ts/message-extension-action/infra/azure.bicep
- templates/ts/message-extension/infra/azure.bicep
- templates/ts/non-sso-tab-default-bot/infra/azure.bicep
- templates/ts/non-sso-tab/infra/azure.bicep
- templates/ts/notification-restify/infra/azure.bicep
- templates/ts/workflow/infra/azure.bicep
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25020594#
> fix: fix typo

- packages/fx-core/resource/package.nls.json
- packages/fx-core/src/common/spec-parser/interfaces.ts
- packages/fx-core/src/component/generator/copilotPlugin/helper.ts
- packages/fx-core/tests/question/create.test.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25052215
> fix: show error when no extra API can be added

- templates/js/m365-message-extension/package.json.tpl
- templates/js/message-extension-action/package.json.tpl
- templates/js/message-extension-copilot/package.json.tpl
- templates/ts/m365-message-extension/package.json.tpl
- templates/ts/message-extension-action/package.json.tpl
- templates/ts/message-extension-copilot/package.json.tpl
fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25074377
> fix: fix adaptive cards dependency

- packages/cli/src/commands/models/create.ts
- packages/fx-core/src/question/create.ts
- packages/fx-core/tests/question/create.test.ts
fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25074954
> fix: cli create new capability dynamic choices

- packages/cli/src/utils.ts
- packages/cli/tests/unit/utils.tests.ts
fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25074954
> fix: capability question use dynamic options for old cli

- packages/fx-core/src/component/driver/teamsApp/utils/ManifestUtils.ts
- packages/fx-core/src/error/common.ts
- packages/fx-core/tests/component/resource/appManifest/manifestUtils.test.ts
fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/24541239
> fix: read manifest error

- packages/fx-core/src/core/FxCore.ts
- packages/fx-core/tests/core/FxCore.test.ts
> refactor: add warnings for optional params

- packages/fx-core/src/common/jsonUtils.ts
- packages/fx-core/src/component/driver/deploy/azure/impl/azureDeployImpl.ts
- packages/fx-core/src/component/driver/script/scriptDriver.ts
- packages/fx-core/src/component/utils/ResourceGroupHelper.ts
- packages/fx-core/src/error/arm.ts
- packages/fx-core/src/error/azure.ts
- packages/fx-core/src/error/common.ts
- packages/fx-core/src/error/deploy.ts
- packages/fx-core/src/error/m365.ts
- packages/fx-core/src/error/script.ts
- packages/fx-core/src/error/types.ts
- packages/fx-core/src/error/yml.ts
- packages/fx-core/tests/component/driver/script/scriptDriver.test.ts
- packages/fx-core/tests/component/jsonUtils.test.ts
fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25092591
> fix(core): ensure inner errors in predefined error types

- docs/fx-core/spfx-help-v5.md
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/24964045
> docs: add eslint warning issue to troubleshooting guide

- templates/js/message-extension-copilot/README.md
- templates/ts/message-extension-copilot/README.md
> docs: update README.md

- packages/vscode-extension/src/controls/sampleGallery/ISamples.ts
- packages/vscode-extension/src/controls/sampleGallery/SampleGallery.tsx
- packages/vscode-extension/src/controls/sampleGallery/sampleFilter.scss
- packages/vscode-extension/src/controls/webviewPanel.ts
Task: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25093360
UI of sample that doesn't work in current TTK will be added later.
> feat(vsc): add version compare result to each sample for different UI
