packages/fx-core/src/plugins/resource/function/utils/depsChecker/dotnetChecker.ts
packages/vscode-extension/src/debug/depsChecker/dotnetChecker.ts

* fix dotnet installation log
* send system error when validate dotnet with hello world failed

feat: add telemetry for validation with hello world

---

packages/vscode-extension/src/controls/SampleGallery.scss
packages/vscode-extension/src/controls/SampleGallery.tsx

feat: update sample app contents

---

packages/fx-core/src/plugins/resource/spfx/plugin.ts

related task: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/9891719

fix(spfx): show output window before deploy

---

packages/sdk/src/credential/onBehalfOfUserCredential.ts
packages/sdk/src/credential/teamsUserCredential.browser.ts

https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/9751776

fix(sdk): log ui required error with warning level

---

packages/fx-core/src/plugins/solution/fx-solution/solution.ts

related task: https://dev.azure.com/msazure/Microsoft%20Teams%20Extensibility/_workitems/edit/9891696

fix(spfx): remove spfx deploy success info

---

packages/vscode-extension/src/controls/openWelcomePage.ts
packages/vscode-extension/src/extension.ts

https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/9888174

feat(extension): show welcome page at first activation

---

packages/vscode-extension/src/controls/SampleGallery.tsx
packages/vscode-extension/src/controls/webviewPanel.ts

feat: download sample app subfolder from repo and open the app

---

packages/api/src/utils/login.ts
packages/vscode-extension/src/commonlib/common/login.ts
packages/vscode-extension/src/commonlib/graphLogin.ts

1. Change login callback behavior.
2. Change extension graph log level to error.

feat: change login callback behavior

---

templates/bot-msgext/js/default/dialogs/mainDialog.js
templates/bot-msgext/js/default/dialogs/rootDialog.js
templates/bot-msgext/ts/default/dialogs/mainDialog.ts
templates/bot-msgext/ts/default/dialogs/rootDialog.ts
templates/bot/js/default/dialogs/mainDialog.js
templates/bot/js/default/dialogs/rootDialog.js
templates/bot/ts/default/dialogs/mainDialog.ts
templates/bot/ts/default/dialogs/rootDialog.ts

Tested big change https://github.com/OfficeDev/TeamsFx/pull/773
Fix some bugs

fix(bot): fix bugs of bot and me templates

---

packages/vscode-extension/src/controls/SampleGallery.tsx

Use public repo under my own personal account before sample app repo goes public according to Zhen

feat: update link to public repo

---

packages/vscode-extension/src/resources/Strings.json

Update dialog text asking for feedback

---

packages/vscode-extension/src/controls/QuickStart.tsx
packages/vscode-extension/src/controls/SampleGallery.tsx
packages/vscode-extension/src/controls/WelcomePanel.tsx

Update the text for the extension pages.

Update the extension pages

---

packages/vscode-extension/test/suite/envChecker/cases/all.ts
packages/vscode-extension/test/suite/envChecker/utils/common.ts
packages/vscode-extension/test/suite/envChecker/utils/dotnet.ts

- Add assertions to backendExtensionInstaller to make the test path more complete
- Add utilities for creating tmp dir and tmp backend project dir
- Format code
A successful CI for all test cases is here: https://github.com/OfficeDev/TeamsFx/actions/runs/827063267
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/9769204

test(env-checker): add backend extension install test cases

---

packages/fx-core/src/plugins/resource/bot/configs/provisionConfig.ts
packages/fx-core/src/plugins/resource/bot/constants.ts
packages/fx-core/src/plugins/resource/bot/plugin.ts
packages/fx-core/src/plugins/resource/bot/resources/strings.ts

1. fix config name for identityId.
2. add site.identity settings.
to fix bug: https://dev.azure.com/msazure/Microsoft%20Teams%20Extensibility/_workitems/edit/9893371

fix(bot): align env and identity settings

---

packages/api/src/ci/functionValidator.ts

chore(function): disable func-deploy validator to reduce network traffic

---

packages/vscode-extension/src/controls/QuickStart.scss
packages/vscode-extension/src/controls/QuickStart.tsx
packages/vscode-extension/src/controls/SampleGallery.scss
packages/vscode-extension/src/controls/SampleGallery.tsx

https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/9888175

feat(extension): make quick start and sample page responsive

---

templates/bot-msgext/js/default/dialogs/rootDialog.js
templates/bot-msgext/ts/default/dialogs/rootDialog.ts
templates/bot/js/default/dialogs/rootDialog.js
templates/bot/ts/default/dialogs/rootDialog.ts

fix [BUG 9901905](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/9901905)

fix(bot): fix button text case

---

packages/api/src/qm/validation.ts
packages/cli/resource/newParam.json
packages/fx-core/src/core/question.ts

related task: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/9901373/

fix: make root folder question mandatory

---

packages/vscode-extension/src/debug/depsChecker/checker.ts
packages/vscode-extension/src/handlers.ts

fix [bug](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/9902032) for localdebug

feat: add popup helplink for installation failure of extension when localdebug

---

packages/vscode-extension/src/commandsTreeViewProvider.ts
packages/vscode-extension/src/extension.ts
packages/vscode-extension/src/handlers.ts
packages/vscode-extension/src/telemetry/extTelemetry.ts
packages/vscode-extension/src/telemetry/extTelemetryEvents.ts

update telemetry for extension.
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/9902778

chore: update telemetry for extension

---

packages/cli/src/cmds/account.ts

This is to fix https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/9885314

Fix spelling error

---

packages/vscode-extension/src/qm/quickpick.ts
packages/vscode-extension/src/qm/vsc_ui.ts

work item: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/9891745

fix(vsc): set focus to true in cmp

---

packages/vscode-extension/src/qm/vsc_ui.ts

work item: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_sprints/taskboard/Teams%20Extensibility%20E2E%20Team/Microsoft%20Teams%20Extensibility/CY21-5.1?workitem=9902548

fix(vsc): use build in multi selection

---

packages/vscode-extension/CONTRIBUTING.md
packages/vscode-extension/README.md
packages/vscode-extension/src/controls/QuickStart.tsx

Change "v.12" to "v12". This fixes https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/9901677.

Fix node version text

---

packages/vscode-extension/src/progressHandler.ts

This fixes https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/9901915

Fix spacing

---

packages/fx-core/src/core/index.ts

Read config when open so sidebar subscription item can load correctly
ADO: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/9888522

fix: cannot read selected subscription correctly

---

packages/vscode-extension/package.json
packages/vscode-extension/src/handlers.ts
packages/vscode-extension/src/resources/Strings.json
packages/vscode-extension/syntaxes/teamsfx-toolkit-output.tmLanguage

Utilize semantic highlighting to colorize output message.
Effect:

fix(extension): remove JSON string and colorize output message

---

packages/fx-core/src/plugins/resource/bot/constants.ts
packages/fx-core/src/plugins/resource/bot/index.ts
packages/fx-core/src/plugins/resource/bot/plugin.ts
packages/fx-core/src/plugins/resource/bot/utils/telemetry-helper.ts

1. refactor to use telemetry-helper.
2. remove -end for success cases.
3. add extra properties, for example, error-code.
4. update aka help link.

feat(bot): align telemetry update link

---

packages/fx-core/src/plugins/solution/fx-solution/solution.ts

https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_sprints/taskboard/Teams%20Extensibility%20E2E%20Team/Microsoft%20Teams%20Extensibility/CY21-5.1?workitem=9911774

fix(solution): change teamsfx init file path

---

packages/cli/src/error.ts
packages/cli/src/userInterface.ts

feat: add show message interactive operation for CLI

---

packages/fx-core/src/plugins/solution/fx-solution/appstudio/appstudio.ts
packages/fx-core/src/plugins/solution/fx-solution/constants.ts

https://dev.azure.com/msazure/Microsoft%20Teams%20Extensibility/_workitems/edit/9902853

fix(solution): not append suffix if resulting name exceeds limit

---

packages/cli/src/userInterface.ts

https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/9902093
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/9902113

feat: interactively ask sub

---

packages/fx-core/src/plugins/resource/appstudio/appStudio.ts
packages/fx-core/src/plugins/resource/appstudio/index.ts

fix: enhance error message

---

packages/fx-core/src/plugins/resource/identity/index.ts
packages/fx-core/src/plugins/resource/identity/utils/telemetryUtil.ts
packages/fx-core/src/plugins/resource/sql/plugin.ts
packages/fx-core/src/plugins/resource/sql/utils/telemetryUtils.ts
packages/vscode-extension/src/debug/commonUtils.ts
packages/vscode-extension/src/debug/constants.ts
packages/vscode-extension/src/handlers.ts

1 add required properties for telemetry event
2 send error event instead of exception when there is an error

feat(sql,identity): update telemetry

---

packages/fx-core/src/plugins/resource/aad/index.ts

feat:
1. log detailed error message:

feat(aad): log detailed error message from app studio

---

packages/fx-core/src/plugins/resource/function/utils/depsChecker/dotnetChecker.ts
packages/vscode-extension/src/debug/depsChecker/dotnetChecker.ts
packages/vscode-extension/src/debug/depsChecker/vscodeAdapter.ts

https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/9912239/

fix(env-checker): fix progress bar new line issue

---

packages/fx-core/src/core/index.ts
packages/vscode-extension/src/handlers.ts
packages/vscode-extension/src/telemetry/extTelemetryEvents.ts

work item: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/9888182

feat(vsc): add tree view telemetery in vsc

---

packages/vscode-extension/package.json

Fixes https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/9836256

Rename Teams Dev Center to Teams Developer Portal

---

packages/fx-core/src/plugins/resource/appstudio/questions.ts

work item: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/9911328

fix(appstudio): fix typo

---

packages/vscode-extension/src/handlers.ts

work item: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/9913508

fix(vsc): fix open link twice in account treeview

---

.github/workflows/e2e-test.yml
packages/cli/package.json
packages/cli/tests/e2e/function/TestAddFunction.tests.ts
packages/cli/tests/e2e/smoke/AzureAppHappyPath.tests.ts

Publish API has been broken, so remove publish test first: https://domoreexp.visualstudio.com/MSTeams/_workitems/edit/1746119

chore: update test account

---

packages/fx-core/src/plugins/solution/fx-solution/question.ts

https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/9911768

feat(solution): rename label MessageExtension->MessagingExtension

---

packages/api/src/qm/visitor.ts
packages/vscode-extension/package.json
packages/vscode-extension/src/handlers.ts

https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/9922900

fix(extension): ignore some user error

---

packages/vscode-extension/package.json
packages/vscode-extension/src/debug/teamsfxTaskHandler.ts

chore(extension): fix the extension setting title

---

packages/vscode-extension/src/controls/QuickStart.tsx

https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/9902954

fix: quick start page check status wrong

---

packages/cli/src/error.ts

When a subscription is not found, update the error message. This fixes https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/9913532.

Subscription not found error update

---

packages/cli/package.json
packages/cli/src/cmds/build.ts
packages/cli/src/cmds/capability.ts
packages/cli/src/cmds/deploy.ts
packages/cli/src/cmds/init.ts
packages/cli/src/cmds/new.ts
packages/cli/src/cmds/provision.ts
packages/cli/src/cmds/publish.ts
packages/cli/src/cmds/resource.ts
packages/cli/src/cmds/validate.ts
packages/cli/src/commonlib/log.ts
packages/cli/src/constants.ts
packages/cli/src/generators/generator.ts
packages/cli/src/telemetry/cliTelemetry.ts
packages/cli/src/telemetry/cliTelemetryEvents.ts
packages/cli/src/telemetry/telemetryReporter.ts
packages/cli/src/userInterface.ts
packages/cli/src/yargsCommand.ts

feat: Add telemetries for CLI.
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/9794226

feat: Add telemetries for CLI

---

packages/vscode-extension/CONTRIBUTING.md
packages/vscode-extension/README.md
packages/vscode-extension/src/controls/QuickStart.tsx

This fixes https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/9921679

Recommend node v14

---

packages/fx-core/src/plugins/resource/aad/plugin.ts
packages/fx-core/src/plugins/resource/simpleauth/index.ts
packages/fx-core/src/plugins/resource/simpleauth/plugin.ts

fix bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/9902891/

fix(simpleauth): fix progress bar

---

packages/vscode-extension/README.md

fix: readme resource link directory

---

packages/fx-core/src/plugins/resource/aad/constants.ts
packages/fx-core/src/plugins/resource/aad/utils/configs.ts

Main change in Constants: 9 and Configs: 109

fix(aad): remove trailing slash from oauthHost

---

packages/vscode-extension/src/controls/Commands.ts
packages/vscode-extension/src/controls/QuickStart.tsx
packages/vscode-extension/src/controls/webviewPanel.ts

PR: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/9922037

fix(vsc): inconsistent sign in status

---

docs/fx-core/sql-help.md

1 modified tags in help doc for help link.
2 improve doc wording.

fix(sql): improve error handling

---

packages/fx-core/src/core/index.ts
packages/fx-core/src/core/loader.ts
packages/fx-core/src/core/question.ts
packages/fx-core/src/plugins/resource/aad/plugin.ts
packages/fx-core/src/plugins/resource/aad/utils/dialog.ts
packages/fx-core/src/plugins/resource/aad/utils/telemetry.ts
packages/fx-core/src/plugins/resource/apim/constants.ts
packages/fx-core/src/plugins/resource/appstudio/plugin.ts
packages/fx-core/src/plugins/resource/bot/configs/teamsBotConfig.ts
packages/fx-core/src/plugins/resource/bot/index.ts
packages/fx-core/src/plugins/resource/bot/plugin.ts
packages/fx-core/src/plugins/resource/bot/questions.ts
packages/fx-core/src/plugins/resource/bot/resources/messages.ts
packages/fx-core/src/plugins/resource/bot/utils/templateManifest.ts
packages/fx-core/src/plugins/resource/frontend/ops/scaffold.ts
packages/fx-core/src/plugins/resource/function/constants.ts
packages/fx-core/src/plugins/resource/function/ops/scaffold.ts
packages/fx-core/src/plugins/resource/function/plugin.ts
packages/fx-core/src/plugins/resource/function/resources/message.ts
packages/fx-core/src/plugins/resource/simpleauth/plugin.ts
packages/fx-core/src/plugins/resource/simpleauth/utils/common.ts
packages/fx-core/src/plugins/resource/spfx/plugin.ts
packages/fx-core/src/plugins/resource/sql/questions.ts
packages/fx-core/src/plugins/resource/sql/utils/telemetryUtils.ts
packages/fx-core/src/plugins/solution/fx-solution/appstudio/appstudio.ts
packages/fx-core/src/plugins/solution/fx-solution/question.ts
packages/fx-core/src/plugins/solution/fx-solution/solution.ts

This pr will improve the performance of core importing by 30%. So please just approve it! Thanks.

perf(core): remove unused imports

---

packages/fx-core/src/core/index.ts

fix: supress select sub popup for spfx project

---

packages/fx-core/src/plugins/resource/apim/utils/openApiProcessor.ts
packages/fx-core/src/plugins/resource/apim/utils/telemetry.ts

Remove OpenApiDocumentEvent because it contains constomer data

fix(apim): delete customer data telemetry

---

packages/fx-core/src/plugins/resource/localdebug/util/localService.ts
packages/fx-core/tests/plugins/resource/localdebug/unit/localService.test.ts

Check version.txt to update auth bits when version is updated.

fix (local debug): update auth bits when new version

---

templates/bot-msgext/js/default/dialogs/rootDialog.js
templates/bot-msgext/ts/default/dialogs/rootDialog.ts
templates/bot/js/default/dialogs/rootDialog.js
templates/bot/ts/default/dialogs/rootDialog.ts

Fix if send the mention bot name, it should return intro card:

fix(bot): if send at bot name it should send intro card

---

packages/vscode-extension/src/commandsTreeViewProvider.ts
packages/vscode-extension/src/handlers.ts

https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_queries/edit/9753362/?triage=true

fix(vsc): update developer portal link

---

packages/fx-core/src/common/tools.ts
packages/fx-core/src/plugins/solution/fx-solution/solution.ts
packages/sdk/src/packageMetadata.ts
packages/vscode-extension/src/handlers.ts

https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/9935752
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/9941232

fix: unify user cancel handling

---

packages/fx-core/src/plugins/solution/fx-solution/commonQuestions.ts
packages/fx-core/src/plugins/solution/fx-solution/solution.ts

fixes https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/9944107

fix(solution): await setSubscription

---

packages/cli/src/error.ts
packages/cli/src/userInterface.ts

related issue: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/9950544

fix(cli): add support for confirm question with multiple options

---

packages/fx-core/src/plugins/resource/appstudio/index.ts

https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/9951257

fix(appstudio): publish manual submit notification async

---

packages/cli/README.md

fix: add getting started for cli readme
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/9951246

fix: add getting started for cli readme

---

packages/fx-core/src/plugins/resource/spfx/plugin.ts

related task:https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/9949162

fix(spfx): fix spfx cancel bug

---

packages/cli/.vscode/launch.json
packages/cli/src/cmds/account.ts
packages/cli/src/commonlib/appStudioLogin.ts
packages/cli/src/commonlib/azureLogin.ts
packages/cli/src/commonlib/codeFlowLogin.ts
packages/cli/src/telemetry/cliTelemetryEvents.ts
packages/fx-core/src/core/index.ts
packages/vscode-extension/src/commonlib/appStudioLogin.ts
packages/vscode-extension/src/commonlib/azureLogin.ts
packages/vscode-extension/src/commonlib/codeFlowLogin.ts
packages/vscode-extension/src/telemetry/extTelemetryEvents.ts

fix: fix login telemetry
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/9951570

Fix: make login telemetry accurate for extension and CLI

---

packages/vscode-extension/src/handlers.ts

ADO: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/9951265

fix(vsc): Open readme in preview mode only

---

packages/cli/resource/newParam.json
packages/cli/src/utils.ts

related PR: [fix: remove faq plus sample app in extension sample gallery page](https://github.com/OfficeDev/TeamsFx/pull/1081) adjust the order of sample apps in CLI.

fix: update the order of samples in CLI

---

packages/vscode-extension/package.json

ADO: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/9949611

fix(vsc): update extension name same as toolkit v1

---

packages/vscode-extension/src/utils/survey.ts

update toolkit survey link
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/9958631

fix: update toolkit survey link

---

docs/fx-core/sql-help.md

fix(sql):improve sql help doc

---

packages/cli/src/cmds/new.ts
packages/fx-core/src/common/tools.ts
packages/vscode-extension/src/controls/webviewPanel.ts

https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/9951057

fix: sample app download images broken

---

packages/cli/src/yargsCommand.ts

releted bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/9968633

fix: use another method to check the error type in CLI

---

packages/fx-core/resource/strings.json
packages/fx-core/src/plugins/solution/fx-solution/solution.ts

fix: toast message if user doesn't provision for spfx project before publish

---

packages/fx-core/src/core/index.ts

https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/9948007

fix(core): do not readConfigs in progress of provision

---

docs/vscode-extension/envchecker-help.md

Update the help doc according to the latest notification message: https://github.com/OfficeDev/TeamsFx/blob/release/20210514/packages/vscode-extension/src/debug/depsChecker/common.ts#L38

docs(env-checker): update the notification message of help doc according to the latest changes

---

packages/fx-core/src/plugins/resource/simpleauth/constants.ts

Fix for: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/9943996

fix simply auth to simple auth

---

packages/fx-core/src/plugins/solution/fx-solution/constants.ts
packages/fx-core/templates/plugins/resource/spfx/solution/manifest.json

fixes https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/9968857

feat(solution): update manifest to v1.10

---

templates/bot-msgext/js/default/README.md
templates/bot-msgext/ts/default/README.md
templates/bot/js/default/README.md
templates/bot/ts/default/README.md
templates/function-base/js/default/README.md
templates/function-base/ts/default/README.md
templates/msgext/js/default/README.md
templates/msgext/ts/default/README.md
templates/tab/js/default/README.md
templates/tab/ts/default/README.md

Add Preview Section in All Template READMEs, this fix for: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/9959757/

Add Preview Section In README

---

packages/vscode-extension/CONTRIBUTING.md

ADO: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/9978061

fix(vsc): update vsc contribution guide

---

packages/fx-core/resource/strings.json
packages/fx-core/src/plugins/solution/fx-solution/solution.ts

https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/9968980

fix(solution): return error when publish or deploy not-provisioned project for CLI

---

packages/cli/tests/commonlib/apimValidator.ts

Format packages/cli/tests/commonlib/apimValidator.ts

refactor(apim): refactor apim validator

---

packages/vscode-extension/package.json

ADO: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/9979108/?triage=true

fix(vsc): remove bot management command

---

packages/vscode-extension/CHANGELOG.md

Update from `2.0.0` to `2.0.1`

chore: update version in changelog for hotfix

---

packages/fx-core/tests/plugins/resource/bot/unit/languageStrategy.test.ts

Use mock-fs to mock the local filesystem.

chore(bot): remove localzip dep in ut

---

packages/fx-core/src/core/index.ts
packages/vscode-extension/src/controls/webviewPanel.ts

ADO: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/9978184

fix(vsc): remove sample app download dialog

---

packages/fx-core/src/plugins/resource/appstudio/index.ts
packages/fx-core/src/plugins/solution/fx-solution/appstudio/appstudio.ts

fix: expose app not found error

---

packages/fx-core/src/plugins/resource/bot/languageStrategy.ts

to fix bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/9978406

fix(bot): invalidBot by npm install

---

packages/fx-core/src/plugins/solution/fx-solution/question.ts

ADO: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_queries/edit/9910912/?triage=true

fix(solution): update place holder of language in scaffolding

---

templates/bot-msgext/js/default/teamsBot.js
templates/bot-msgext/ts/default/teamsBot.ts
templates/bot/js/default/teamsBot.js
templates/bot/ts/default/teamsBot.ts

1. Change teamsbot.ts --> teamsBot.ts
2. Remove redundant blank line in comments
fixed bug https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/9986696

fix(bot): file name case sensitive in linux

---

docs/fx-core/apim-help.md
packages/fx-core/src/plugins/resource/apim/constants.ts
packages/fx-core/src/plugins/resource/apim/error.ts

The bookmark is auto-added by the core.

fix(apim): update help link bookmark

---

packages/fx-core/src/plugins/resource/appstudio/index.ts

fix: avoid duplicate message for cli

---

packages/fx-core/src/plugins/solution/fx-solution/question.ts

fix: add description to avoid confusion

---

packages/vscode-extension/src/debug/teamsfxTaskHandler.ts

Currently there might be multiple npm-install tasks running in parallel. This PR is to switch the terminal to show other npm-install tasks when the current npm-install task is completed.
Please note, the terminal will be switched even the current npm-install task is failed (completed without exit code 0). This would be addressed in another separated PR (still under investigation).

feat(local-debug): switch to active npm install task automatically

---

packages/api/src/config.ts
packages/api/src/qm/question.ts
packages/api/src/qm/ui.ts
packages/api/src/qm/validation.ts
packages/api/src/qm/visitor.ts
packages/api/src/utils/dialog.ts
packages/api/tests/qm.visitor.test.ts
packages/vscode-extension/src/error.ts
packages/vscode-extension/src/handlers.ts
packages/vscode-extension/src/qm/quickpick.ts
packages/vscode-extension/src/qm/vsc_ui.ts

https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/10019233

feat: upgrade UI APIs

---

packages/cli/src/cmds/config.ts
packages/cli/src/cmds/index.ts
packages/cli/src/error.ts
packages/cli/src/telemetry/telemetryReporter.ts
packages/cli/src/userSetttings.ts

feat: able to turn on and off telemetry
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/9970057

feat: able to turn on and off telemetry

---

packages/fx-core/tests/plugins/solution/solution.scaffold.test.ts
packages/fx-core/tests/plugins/solution/solution.update.test.ts

fixes https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_sprints/taskboard/Teams%20Extensibility%20E2E%20Team/Microsoft%20Teams%20Extensibility/CY21-5.2?workitem=10019142

test(solution): add test for scaffold

---

packages/vscode-extension/src/utils/survey.ts

fix: change survey link pop out window
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/10018777

fix: change survey link pop out window

---

packages/vscode-extension/src/controls/openWelcomePage.ts
packages/vscode-extension/src/handlers.ts

ADO: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/10019865

fix(vsc): update ext name when detect vs code environment

---

packages/api/src/qm/ui.ts
packages/fx-core/src/plugins/solution/fx-solution/solution.ts
packages/sdk/src/packageMetadata.ts
packages/vscode-extension/src/qm/vsc_ui.ts

1. solve: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/9978718
2. fix vscode extension ui bug for showMessage

fix(solution): add resource

---

templates/tab/js/default/package.json
templates/tab/js/default/public/index.html
templates/tab/js/default/src/components/sample/AzureFunctions.jsx
templates/tab/ts/default/package.json
templates/tab/ts/default/public/index.html
templates/tab/ts/default/src/components/sample/AzureFunctions.tsx

1. The environment description should either be removed or be dynamic based on the actual environment (Azure or local). Remove here for there is already a message indicates the environment at the top of welcome page.
2. Remove the broken scripts. The cli command can only be run at the root folder, instead of ./tabs/ folder.

fix(tab): fix issues for tab template

---

packages/fx-core/src/plugins/resource/appstudio/plugin.ts

fix: use locale convention

---

packages/fx-core/src/core/index.ts
packages/fx-core/src/plugins/solution/fx-solution/question.ts
packages/vscode-extension/src/controls/QuickStart.tsx

ADO: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/9997355

fix(vsc): update content in quick start

---

packages/cli/src/commonlib/appStudioLogin.ts
packages/cli/src/commonlib/azureLogin.ts
packages/cli/src/commonlib/graphLogin.ts
packages/vscode-extension/src/commonlib/appStudioLogin.ts
packages/vscode-extension/src/commonlib/graphLogin.ts

1. Only output login error log

fix: filter login log

---

packages/api/src/utils/login.ts
packages/api/tests/login.test.ts
packages/cli/src/commonlib/appStudioLogin.ts
packages/cli/src/commonlib/appStudioLoginUserPassword.ts
packages/cli/src/commonlib/azureLogin.ts
packages/cli/src/commonlib/azureLoginCI.ts
packages/cli/src/commonlib/azureLoginUserPassword.ts
packages/cli/src/commonlib/graphLogin.ts
packages/cli/src/commonlib/graphLoginCI.ts
packages/cli/src/commonlib/graphLoginUserPassword.ts
packages/fx-core/tests/plugins/resource/apim/testUtil.ts
packages/fx-core/tests/plugins/resource/bot/unit/utils.ts
packages/vscode-extension/src/commonlib/appStudioCodeSpaceLogin.ts
packages/vscode-extension/src/commonlib/appStudioLogin.ts
packages/vscode-extension/src/commonlib/azureLogin.ts
packages/vscode-extension/src/commonlib/graphLogin.ts

1. remove login setStatusChange callback

feat: remove setStatusChange callback

---

packages/fx-core/src/plugins/resource/bot/index.ts
packages/fx-core/src/plugins/resource/bot/plugin.ts

to reduce risks:
1. remove the save config logic after exceptions.
2. add checkpoint between app studio call and azure call

chore(bot): add checkpoint between app studio call and azure call

---

packages/vscode-extension/src/commonlib/telemetry.ts
packages/vscode-extension/src/handlers.ts

fix: fix telemetry data loss.
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/10036342

fix: fix telemetry data loss

---

docs/fx-core/bot-help.md

to fix bug: https://dev.azure.com/msazure/Microsoft%20Teams%20Extensibility/_workitems/edit/9939864

chore(doc): add guide for deleting Free App Service Plan

---

packages/vscode-extension/src/handlers.ts

ADO: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/9923068?src=WorkItemMention&src-action=artifact_link

fix(vsc): undefined stack in tooling log

---

packages/cli/package.json
packages/cli/src/cmds/account.ts
packages/cli/src/cmds/config.ts
packages/cli/src/cmds/init.ts
packages/cli/src/cmds/new.ts
packages/cli/src/cmds/resource.ts
packages/cli/src/commonlib/appStudioLoginUserPassword.ts
packages/cli/src/commonlib/azureLogin.ts
packages/cli/src/commonlib/azureLoginUserPassword.ts
packages/cli/src/commonlib/codeFlowLogin.ts
packages/cli/src/commonlib/codeFlowTenantLogin.ts
packages/cli/src/commonlib/graphLoginUserPassword.ts
packages/cli/src/commonlib/log.ts
packages/cli/src/userInteraction.ts
packages/cli/src/yargsCommand.ts

related bugs:
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/9893250
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/9893368
description:
1. use `logProvider` instead of `console` in CLI.
2. check whether the `stdout` and `stderr` are `TTY`, if yes, add colors to the logs, otherwise, not add colors.

fix: stdout/stderr TTY

---

packages/fx-core/src/plugins/resource/appstudio/index.ts
packages/fx-core/src/plugins/resource/appstudio/plugin.ts
packages/fx-core/src/plugins/resource/appstudio/utils/telemetry.ts

- update telemetry for app studio plugin

fix: update telemetry for app studio plugin

---

docs/fx-core/bot-help.md
docs/fx-core/config.md

to provide support for https://github.com/OfficeDev/TeamsFx/issues/1238

chore(bot): add desc for bot configs

---

packages/cli/src/commonlib/codeFlowLogin.ts
packages/cli/src/commonlib/common/constant.ts

1. Change cli login log url message to real url

feat: cli login url

---

packages/fx-core/src/plugins/resource/apim/constants.ts

Increase retry time interval. The max waiting time will be 120 seconds.

fix(apim): increase retry time interval

---

docs/fx-core/bot-help.md
docs/fx-core/config.md

chore(doc): config file document

---

templates/bot-msgext/js/default/dialogs/mainDialog.js
templates/bot-msgext/js/default/teamsBot.js
templates/bot-msgext/ts/default/dialogs/mainDialog.ts
templates/bot-msgext/ts/default/teamsBot.ts
templates/bot/js/default/dialogs/mainDialog.js
templates/bot/js/default/teamsBot.js
templates/bot/ts/default/dialogs/mainDialog.ts
templates/bot/ts/default/teamsBot.ts

Fix this issue: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_sprints/taskboard/AuthAndData/Microsoft%20Teams%20Extensibility/CY21-6.1?workitem=9997644

fix(bot-template): click "Show profile" in bot app didn't response sometimes

---

packages/cli/src/cmds/deploy.ts
packages/cli/src/cmds/resource.ts
packages/cli/src/yargsCommand.ts
packages/cli/tests/e2e/smoke/AzureAppHappyPath.tests.ts

https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/10057340

fix: apim need undefined of some questions

---

packages/fx-core/resource/strings.json
packages/fx-core/src/plugins/solution/fx-solution/solution.ts

https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_sprints/taskboard/Teams%20Extensibility%20E2E%20Team/Microsoft%20Teams%20Extensibility/CY21-6.1?workitem=9969211

fix(solution): wording for adding capability/resource on CLI

---

docs/fx-core/sql-help.md

1. improve sql doc for adding aad admin.

feat(sql): improve sql doc

---

packages/fx-core/src/plugins/resource/aad/aadAppClient.ts
packages/fx-core/src/plugins/resource/aad/errors.ts
packages/fx-core/src/plugins/resource/aad/index.ts

feat:
1. print detailed error in telemetry:

fix(aad): print detailed message in telemetry

---

packages/cli/src/activate.ts
packages/cli/src/userInteraction.ts
packages/cli/src/userInterface.ts

Also returns APIM undefined preset answers.

fix: cannot provision with the wrong existing sub && validate preset answers

---

packages/fx-core/src/plugins/resource/frontend/constants.ts
packages/fx-core/src/plugins/resource/frontend/utils.ts

fix(frontend): normalize suffix for user may modify it

---

packages/sdk/src/util/logger.ts
templates/tab/js/default/src/components/sample/lib/useTeamsFx.js
templates/tab/ts/default/src/components/sample/lib/useTeamsFx.ts

https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/9912111

chore(template): prevent too many sdk logs by setting Error log level

---

packages/cli/src/userInteraction.ts

fix: remove '$(xxx)' of create in CLI (hard code)

---

packages/fx-core/src/plugins/resource/spfx/utils/constants.ts

related task: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/9923627

fix(spfx): update spfx deploy guide

---

packages/fx-core/src/core/index.ts
packages/vscode-extension/src/controls/Commands.ts
packages/vscode-extension/src/controls/LearnToolkit.tsx
packages/vscode-extension/src/controls/QuickStart.tsx
packages/vscode-extension/src/controls/webviewPanel.ts
packages/vscode-extension/src/error.ts
packages/vscode-extension/src/handlers.ts
packages/vscode-extension/src/telemetry/extTelemetryEvents.ts

Add telemetry for webview actions

feat: add telemetry for webview

---

packages/fx-core/src/plugins/resource/aad/constants.ts
packages/fx-core/src/plugins/resource/aad/utils/telemetry.ts
packages/fx-core/src/plugins/resource/simpleauth/constants.ts
packages/fx-core/src/plugins/resource/simpleauth/utils/telemetry.ts
packages/fx-core/tests/plugins/resource/aad/helper.ts
packages/fx-core/tests/plugins/resource/simpleauth/helper.ts

fix(aad, simpleauth): add app id in telemetry

---

packages/vscode-extension/src/utils/survey.ts

fix: change survey wait time to 7m according to PM's request.

fix: change survey wait time to 7m

---

packages/fx-core/src/plugins/resource/sql/index.ts

fix sql stage bug

---

.github/CODEOWNERS
templates/bot-msgext/js/default/README.md
templates/bot-msgext/ts/default/README.md
templates/bot/js/default/README.md
templates/bot/ts/default/README.md
templates/msgext/js/default/README.md
templates/msgext/ts/default/README.md
templates/tab/js/default/README.md
templates/tab/ts/default/README.md

fix updates for md in mistake for PR: https://github.com/OfficeDev/TeamsFx/pull/1291
should respect the dev branch for md.
and add code owners for templates.

fix: rollback md, add owners for templates

---

packages/cli/resource/newParam.json
packages/cli/src/constants.ts
packages/fx-core/src/core/question.ts
packages/vscode-extension/src/controls/SampleGallery.tsx

Update faq plus download link to main branch

feat: update faq plus sample app link

---

packages/fx-core/src/plugins/resource/apim/answer.ts
packages/fx-core/src/plugins/resource/apim/config.ts
packages/fx-core/src/plugins/resource/apim/error.ts
packages/fx-core/src/plugins/resource/apim/index.ts
packages/fx-core/src/plugins/resource/apim/managers/aadManager.ts
packages/fx-core/src/plugins/resource/apim/managers/apimManager.ts
packages/fx-core/src/plugins/resource/apim/managers/scaffoldManager.ts
packages/fx-core/src/plugins/resource/apim/managers/teamsAppAadManager.ts
packages/fx-core/src/plugins/resource/apim/questions/question.ts
packages/fx-core/src/plugins/resource/apim/questions/vscodeQuestion.ts
packages/fx-core/src/plugins/resource/apim/services/aadService.ts
packages/fx-core/src/plugins/resource/apim/services/apimService.ts
packages/fx-core/src/plugins/resource/apim/utils/openApiProcessor.ts

fix bugs in strict type checking

fix(apim): fix bugs in strict type checking

---

packages/fx-core/src/plugins/resource/bot/plugin.ts
packages/fx-core/src/plugins/resource/bot/resources/strings.ts

Fix bug https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/10057517

fix(bot): bot name is inconsistant with appname

---

packages/cli/src/userInteraction.ts

fix: scratch question hardcode error

---

packages/fx-core/src/plugins/resource/apim/answer.ts

Change the error message of API version

fix(apim): fix api version length bug

---

packages/cli/.vscode/launch.json
packages/cli/src/userSetttings.ts

fix: fix config command error if path not exists
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/10116025

fix: fix config command error if path not exists

---

templates/bot-msgext/js/default/index.js
templates/bot-msgext/ts/default/index.ts
templates/bot/js/default/index.js
templates/bot/ts/default/index.ts

to fix bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/10115715
test good with local debug & remote.

fix: change regexp to string

---

packages/sdk/src/packageMetadata.ts
packages/vscode-extension/.vscodeignore

fix: loss files when vsce package

fix(extension): .vscodeignore

---

packages/fx-core/tests/plugins/solution/solution.deploy.test.ts
packages/fx-core/tests/plugins/solution/solution.publish.test.ts
packages/fx-core/tests/plugins/solution/solution.usertask.test.ts
packages/fx-core/tests/plugins/solution/util.ts

Closes https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_sprints/taskboard/Teams%20Extensibility%20E2E%20Team/Microsoft%20Teams%20Extensibility/CY21-6.1?workitem=10026549
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_sprints/taskboard/Teams%20Extensibility%20E2E%20Team/Microsoft%20Teams%20Extensibility/CY21-6.1?workitem=10026550
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_sprints/taskboard/Teams%20Extensibility%20E2E%20Team/Microsoft%20Teams%20Extensibility/CY21-6.1?workitem=10026553

test(solution): unit test cases for publish, vs publish, deploy

---

packages/cli/README.md

Add instructions in README to turn off telemetry

Add Telemetry Instruction in README

---

packages/api/src/qm/ui.ts
packages/cli/src/userInteraction.ts
packages/fx-core/src/plugins/resource/appstudio/index.ts
packages/fx-core/src/plugins/resource/spfx/plugin.ts
packages/vscode-extension/src/qm/vsc_ui.ts

feat: add color for showMessage

---

packages/fx-core/src/plugins/resource/function/plugin.ts
packages/fx-core/src/plugins/resource/function/resources/message.ts

Add one line below -- "Skip deployment." to make the message more readable.

fix(function): add skip deployment message

---

packages/fx-core/src/plugins/resource/function/enums.ts
packages/fx-core/src/plugins/resource/function/index.ts
packages/fx-core/src/plugins/resource/function/utils/telemetry-helper.ts

1. rename telemetryHelper to TelemetryHelper
2. rename LifeCycle to FunctionEvent
3. adjust type from string to FunctionEvent | TelemetryHelper

refactor(function): rename telemetry helper class and enhance event type

---

packages/api/src/utils/index.ts
packages/cli/src/cmds/provision.ts
packages/cli/src/cmds/publish.ts
packages/cli/src/cmds/resource.ts
packages/cli/src/cmds/validate.ts
packages/cli/src/helpParamGenerator.ts
packages/fx-core/src/common/telemetry.ts
packages/vscode-extension/src/accountTree.ts

https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/10161587

fix: CLI help need telemtry but not found

---

packages/vscode-extension/src/commonlib/azureLogin.ts
packages/vscode-extension/src/commonlib/codeFlowLogin.ts
packages/vscode-extension/src/telemetry/extTelemetryEvents.ts

1. Add extension logout telemetry
Fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/10096315

feat: add extension logout telemetry

---

packages/fx-core/src/plugins/resource/function/enums.ts
packages/fx-core/src/plugins/resource/function/ops/scaffold.ts
packages/fx-core/src/plugins/resource/function/resources/errors.ts
packages/fx-core/src/plugins/resource/function/utils/telemetry-helper.ts

add telemetry for fallback, we can use event `scaffold-fallback` to track it.

feat(function): add telemetry for fallback

---

packages/vscode-extension/README.md
packages/vscode-extension/src/accountTree.ts

ADO: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_sprints/taskboard/Teams%20Extensibility%20E2E%20Team/Microsoft%20Teams%20Extensibility/cy21-6.2?workitem=10126470

fix(vsc): Account subscription display incorrectly

---

templates/bot-msgext/js/default/teamsBot.js
templates/bot-msgext/ts/default/teamsBot.ts
templates/msgext/js/default/messageExtensionBot.js
templates/msgext/ts/default/messageExtensionBot.ts

fix bug https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/10126524

fix(bot): me card can not show complete message

---

packages/cli/tests/e2e/aad/Aad Error Tests.tests.ts
packages/cli/tests/e2e/aad/Provision Resource Update Endpoint and Domain for AAD.tests.ts
packages/cli/tests/e2e/aad/Provision Resource Update Permission for AAD.tests.ts
packages/cli/tests/e2e/apim/TestCreateNewApim.tests.ts
packages/cli/tests/e2e/apim/TestImportApiIntoApim.tests.ts
packages/cli/tests/e2e/apim/TestUseExistingApim.tests.ts
packages/cli/tests/e2e/bot/Provision Resource project with new bot.tests.ts
packages/cli/tests/e2e/commonUtils.ts
packages/cli/tests/e2e/frontend/TestCreateTab.tests.ts
packages/cli/tests/e2e/function/TestAddFunction.tests.ts
packages/cli/tests/e2e/simpleauth/Provision Resource Provision SimpleAuth with different pricing tier.tests.ts
packages/cli/tests/e2e/smoke/AzureAppHappyPath.tests.ts

https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/10097326

test: retry when provision/deploy/publish/validate/test/build fail

---

packages/fx-core/src/plugins/resource/frontend/constants.ts
packages/fx-core/src/plugins/resource/frontend/index.ts
packages/fx-core/src/plugins/resource/frontend/ops/scaffold.ts
packages/fx-core/src/plugins/resource/frontend/resources/errors.ts
packages/fx-core/src/plugins/resource/frontend/utils/telemetry-helper.ts

Align to function plugin's changes.

feat(frontend): send scaffold fallback event

---

packages/cli/src/cmds/account.ts
packages/cli/src/commonlib/codeFlowLogin.ts
packages/cli/src/commonlib/codeFlowTenantLogin.ts

M365 signin color:
Azure signin color:

fix: update color for m365 signin and azure signin

---

packages/fx-core/src/plugins/resource/frontend/ops/scaffold.ts
packages/fx-core/src/plugins/resource/frontend/resources/errors.ts
packages/fx-core/src/plugins/resource/frontend/utils/telemetry-helper.ts

1. explicit the error on sending scaffold telemetry.
2. fix wrong error for scaffolding

refactor(frontend): explicit the error on sending scaffold telemetry

---

.github/CODEOWNERS
packages/cli/src/cmds/preview/task.ts

1. spawn shell command
2. no timeout support
3. no kill support

feat(cli): add task wrapper for preview command

---

packages/cli/package-lock.json
packages/cli/package.json
packages/cli/src/index.ts
packages/cli/src/prompts/customizedCheckboxPrompt.ts
packages/cli/src/prompts/customizedListPrompt.ts
packages/cli/src/prompts/index.ts
packages/cli/src/userInteraction.ts

https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/9823352
radio:
checkbox:
result:

feat: add inquirer plugins

---

packages/cli/src/cmds/preview/commonUtils.ts
packages/cli/src/cmds/preview/constants.ts
packages/cli/src/cmds/preview/errors.ts
packages/cli/src/cmds/preview/preview.ts
packages/cli/src/cmds/preview/task.ts

feat(cli): init preview command

---

packages/fx-core/src/core/index.ts
packages/vscode-extension/src/handlers.ts

ADO: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_sprints/taskboard/Teams%20Extensibility%20E2E%20Team/Microsoft%20Teams%20Extensibility/cy21-6.2?workitem=10209544

fix(vsc): open readme in new tab

---

packages/cli/src/prompts/customizedCheckboxPrompt.ts
packages/cli/src/prompts/customizedListPrompt.ts
packages/cli/src/prompts/index.ts
packages/cli/src/prompts/utils.ts
packages/cli/src/userInteraction.ts

https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/10209725

feat: show details about inquirer questions' choices

---

packages/cli/src/progressHandler.ts

https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/10221212

feat: change the progress messages' color to bright white

---

packages/api/src/qm/question.ts
packages/api/src/qm/ui.ts
packages/api/src/qm/validation.ts

1. add comments on `ui.ts`, `question.ts`and `validation.ts`
2. format these three files

docs(api): add comments to generate API docs

---

packages/cli/tests/commonlib/functionValidator.ts

test(function): add retry in e2e validator

---

packages/cli/src/cmds/preview/commonUtils.ts
packages/cli/src/cmds/preview/constants.ts
packages/cli/src/cmds/preview/errors.ts
packages/cli/src/cmds/preview/preview.ts
packages/cli/src/cmds/preview/task.ts

feat(cli-preview): implement prepare dev env stage

---

packages/fx-core/src/plugins/solution/fx-solution/solution.ts
packages/fx-core/tests/plugins/solution/solution.provision.test.ts

replace dialog with unified ui interface in solution

refactor(solution): ctx.dialog-->ctx.ui

---

packages/fx-core/src/core/index.ts
packages/fx-core/tests/core/utils.ts

refactor(core): transfer progress bar

---

packages/cli/src/cmds/deploy.ts
packages/cli/src/error.ts

related task:https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/9951013

fix(cli): check if given plugin is actually in the project

---

packages/fx-core/src/plugins/resource/function/utils/depsChecker/dotnetChecker.ts
packages/vscode-extension/src/debug/depsChecker/dotnetChecker.ts

[Bug 10058405](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/10058405)
Fix error of verifying dotnet hello world failed

fix(env checker): fix error of verifying dotnet hello world failed

---

packages/cli/src/cmds/preview/commonUtils.ts
packages/cli/src/cmds/preview/constants.ts
packages/cli/src/cmds/preview/errors.ts
packages/cli/src/cmds/preview/preview.ts
packages/cli/src/cmds/preview/task.ts

Happy path:
Know issue:
If error occurs during preview, the preview command will stop, but the task child processes will not be terminated.

feat(cli-preview): complete local preview flow

---

packages/cli/src/cmds/preview/commonUtils.ts
packages/cli/src/cmds/preview/constants.ts
packages/cli/src/cmds/preview/errors.ts
packages/cli/src/cmds/preview/preview.ts

feat(cli-preview): detect if ports are already in use

---

packages/cli/src/index.ts

https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/9969018
Before fixed:
After fixed:

fix: change the minimum columns of yargs help

---

packages/cli/src/cmds/provision.ts
packages/cli/src/constants.ts
packages/cli/src/helpParamGenerator.ts
packages/cli/tests/e2e/smoke/AzureAppHappyPath.tests.ts
packages/cli/tests/e2e/sql/ProvisionReactAppWithAzureFunctionAndSQL.tests.ts

1. hide sql-confirm-password in help view.
2. set sql-confirm-password value when user input sql-password in the non-interactive way.
3. update test case.
4. remove space in test file to get lint(pre-commit work) pass.
related task:https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/9892033

fix(cli): conceal sql-confirm-password in cli provision cmd

---

packages/fx-core/templates/plugins/resource/spfx/webpart/none/{componentClassName}.ts
packages/fx-core/templates/plugins/resource/spfx/webpart/react/components/{componentName}.tsx

related task: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/10242379

fix(spfx): use pop out window for hyperlink in scaffold template

---

packages/cli/src/cmds/preview/constants.ts
packages/cli/src/cmds/preview/preview.ts

- support preview for typescript
- remove node inspector for function and bot
- add backend extensions install

feat(cli-preview): support typescript

---

packages/fx-core/src/plugins/resource/bot/azureOps.ts

fix bug https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/10211407

fix(bot): no detailed error message when deploy failed

---

packages/cli/src/utils.ts

Add non-breaking space for each line, to avoid tailing color.
Reference: https://stackoverflow.com/questions/66123718/write-host-with-background-colour-fills-the-entire-line-with-background-colour-w

fix: add non-breaking space to avoid tailing color

---

packages/vscode-extension/src/commandsTreeViewProvider.ts
packages/vscode-extension/src/extension.ts
packages/vscode-extension/src/handlers.ts
packages/vscode-extension/src/resources/Strings.json
packages/vscode-extension/src/telemetry/extTelemetryEvents.ts

UX design:
https://www.figma.com/file/qqVegbnWWBsqHhR8Qijs4O/Teams-Toolkit---GA?node-id=1%3A297

feat: add 'run and debug' item on sidebar for a/b testing

---

packages/fx-core/src/plugins/resource/spfx/plugin.ts

refactor(spfx): replace dialog with unified ui

---

packages/cli/tests/commonlib/functionValidator.ts

Use the retry-after field in response for retry interval when 429 occurs. see https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/request-limits-and-throttling.
```
response: {
status: 429,
statusText: 'Too Many Requests',
headers: {
'cache-control': 'no-cache',
pragma: 'no-cache',
'content-length': '310',
'content-type': 'application/json; charset=utf-8',
expires: '-1',
'retry-after': '5',
'strict-transport-security': 'max-age=31536000; includeSubDomains',
'x-ms-ratelimit-remaining-subscription-reads': '11998',
server: 'Microsoft-IIS/10.0',
'x-aspnet-version': '4.0.30319',
'x-powered-by': 'ASP.NET',
'x-ms-request-id': '6da721e0-ff95-48e9-94c8-28860d398039',
'x-ms-correlation-request-id': '6da721e0-ff95-48e9-94c8-28860d398039',
'x-ms-routing-request-id': …
```

test(function): use retry-after for 429 response in e2e validator

---

packages/cli/src/cmds/preview/errors.ts
packages/cli/src/cmds/preview/preview.ts

feat(cli-preview): implement remote preview

---

packages/fx-core/src/plugins/solution/fx-solution/solution.ts

Fixes https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_sprints/taskboard/Teams%20Extensibility%20E2E%20Team/Microsoft%20Teams%20Extensibility/CY21-6.3?workitem=9986720

fix(solution): fix add capability message

---

packages/fx-core/src/plugins/solution/fx-solution/solution.ts
packages/fx-core/tests/plugins/solution/solution.provision.test.ts

https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/10272595

fix(solution): don't change helplink

---

packages/vscode-extension/package.json

ADO: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/10160619

fix(vsc): collapse feedback tree view container

---

packages/fx-core/src/plugins/resource/aad/aadAppClient.ts
packages/fx-core/src/plugins/resource/aad/constants.ts
packages/fx-core/src/plugins/resource/aad/errors.ts

Change system error to user error for some cases.
Add new error type for failing to call app studio api:

fix(aad): change system error to user error

---

packages/fx-core/src/plugins/resource/appstudio/index.ts
packages/fx-core/src/plugins/resource/appstudio/plugin.ts
packages/fx-core/tests/core/utils.ts
packages/fx-core/tests/plugins/resource/appstudio/helper.ts
packages/fx-core/tests/plugins/resource/appstudio/unit/publish.test.ts

https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/10281512

refactor(appstudio): dialog -> ui

---

packages/fx-core/src/plugins/resource/sql/index.ts
packages/fx-core/src/plugins/resource/sql/plugin.ts
packages/fx-core/tests/plugins/resource/sql/helper.ts
packages/fx-core/tests/plugins/resource/sql/unit/index.test.ts
packages/fx-core/tests/plugins/resource/sql/unit/skipAddingUser.test.ts

1. remove useless callFunc code 
2. add unit test.

chore(sql): remove useless callFunc code

---

packages/fx-core/src/plugins/resource/bot/azureOps.ts
packages/fx-core/src/plugins/resource/bot/index.ts

fix bug https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/10273591
1. Fix provision/deploy/scaffold operation failed do not have detail error message
2. Fix unhandled error telemetry do not have detail error message

fix(bot): do not have detailed error message

---

packages/fx-core/src/plugins/resource/sql/utils/dialogUtils.ts
packages/fx-core/tests/core/utils.ts
packages/fx-core/tests/plugins/resource/sql/helper.ts

https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/10282903

refactor(sql): dialog -> ui

---

packages/cli/src/cmds/preview/commonUtils.ts
packages/cli/src/cmds/preview/constants.ts
packages/cli/src/cmds/preview/preview.ts
packages/cli/src/cmds/preview/task.ts

refactor(cli-preview): refactor task construct

---

packages/fx-core/src/plugins/resource/localdebug/certificate.ts

https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/10283222

refactor(localdebug): dialog->ut

---

packages/fx-core/src/plugins/resource/aad/plugin.ts
packages/fx-core/src/plugins/resource/aad/utils/dialog.ts
packages/fx-core/tests/core/utils.ts
packages/fx-core/tests/plugins/resource/aad/helper.ts

https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/10283504

refactor(aad): dialog->ui

---

packages/sdk/src/util/logger.ts
templates/tab/js/default/src/components/sample/lib/useTeamsFx.js
templates/tab/ts/default/src/components/sample/lib/useTeamsFx.ts

https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/9921340

chore(sdk): remove default logger and let developer set

---

packages/cli/package-lock.json
packages/cli/package.json
packages/cli/src/commonlib/cacheAccess.ts
packages/vscode-extension/package-lock.json
packages/vscode-extension/package.json
packages/vscode-extension/src/commonlib/cacheAccess.ts
packages/vscode-extension/src/resources/Strings.json

Per security requirement, local token cache should be protected.
This implementation uses `msal-node-extensions` to create protected local token cache, and this PR is the first one to prepare dependencies and does not break any existing flow.
@xiaolang124 - please help review the new APIs.
@Alive-Fish @chagong - please help review the package.json change in cli
@1openwindow - please help review the package.json change in vscode-extension

chore(login): prepare msal-node-extension to encrypt/decrypt token

---

packages/fx-core/src/plugins/resource/function/index.ts
packages/fx-core/src/plugins/resource/function/utils/depsChecker/funcPluginAdapter.ts
packages/fx-core/src/plugins/resource/function/utils/dialog.ts
packages/fx-core/src/plugins/resource/function/utils/step-helper.ts

https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/10283010

refactor(function): dialog->ui

---

.github/CODEOWNERS
.github/workflows/cd.yml
lerna.json
package.json

chore: Separate lerna version and publish

---

packages/cli/src/cmds/index.ts
packages/fx-core/src/plugins/resource/localdebug/index.ts

feat(cli-preview): enable cli preview command

---

packages/fx-core/src/plugins/resource/sql/managementClient.ts

1. improve error message for azure api call scenarios.

chore(sql): improve sql error message

---

packages/fx-core/src/plugins/solution/fx-solution/question.ts

ADO: https://github.com/OfficeDev/TeamsFx/issues/1479

fix: update detail strings when creating project

---

.github/workflows/e2e-test.yml
packages/cli/package.json

https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/10261350
Test running time is about 20min, but others run 10min.

ci: use the self-hosted runner

---

packages/vscode-extension/src/debug/constants.ts
packages/vscode-extension/src/debug/teamsfxTaskHandler.ts

1. When NPM install encounters error, show error notify message and add a report link.

fix: add npm install show error

---

packages/vscode-extension/src/commandsTreeViewProvider.ts
packages/vscode-extension/src/exp/treatmentVariables.ts
packages/vscode-extension/src/handlers.ts

feat: show debug profile when clicking 'run and debug'

---

docs/fx-core/sql-help.md
packages/fx-core/src/plugins/resource/sql/constants.ts
packages/fx-core/src/plugins/resource/sql/errors.ts
packages/fx-core/src/plugins/resource/sql/plugin.ts
packages/fx-core/src/plugins/resource/sql/sqlClient.ts

1. add sql access error when check database user.
2. improve doc for access error.

chore(sql): add access error help

---

packages/fx-core/src/core/index.ts
packages/fx-core/src/plugins/resource/spfx/index.ts
packages/fx-core/src/plugins/resource/spfx/plugin.ts
packages/fx-core/src/plugins/resource/spfx/utils/utils.ts

1. remove spfxConfig due to duplication
2. make utils a class for stub use in test benefit

refactor(spfx): remove spfxConfig & make utils a class

---

packages/cli/src/cmds/preview/constants.ts
packages/cli/src/cmds/preview/errors.ts
packages/cli/src/cmds/preview/preview.ts

fix(cli-preview): show error for spfx

---

packages/fx-core/package.json
packages/fx-core/tests/plugins/resource/spfx/helper.ts
packages/fx-core/tests/plugins/resource/spfx/unit/scaffold.test.ts

related task: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/10282067

test(spfx): add unit test for spfx scaffold

---

docs/cli/user-manual.md

docs(cli-preview): add docs for cli preview command

---

packages/vscode-extension/src/handlers.ts

ADO: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/10282933

fix(vsc): set default report issue link

---

packages/vscode-extension/src/debug/constants.ts
packages/vscode-extension/src/debug/teamsfxTaskHandler.ts

1. Add NPM install error template.

fix: add npm error template

---

packages/fx-core/package.json
packages/fx-core/tests/plugins/resource/identity/unit/provision.test.ts
packages/fx-core/tests/plugins/resource/sql/unit/index.test.ts
packages/fx-core/tests/plugins/resource/sql/unit/skipAddingUser.test.ts
packages/fx-core/tests/plugins/resource/sql/unit/sqlClient.test.ts

1. add unit test for sqlClient.
2. remove useless test code

chore(sql): add unit test

---

packages/vscode-extension/src/handlers.ts

Fix https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/10318839

fix: not open command palette after click 'run and debug'

---

.github/workflows/cd.yml

Install mustache used for generating template code

fix: cd pipeline to install mustach before gen tempaltes

---

packages/cli/src/cmds/preview/constants.ts
packages/cli/src/cmds/preview/preview.ts

Remove word 'sideloading' in cli preview command log
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/10317972/

fix(localdebug): remove word 'sideloading' in cli preview command log

---

.github/workflows/e2e-test.yml
packages/cli/package.json

https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/10298201
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/10261354

chore: reduce e2e test running time

---

package-lock.json
packages/vscode-extension/package-lock.json
packages/vscode-extension/package.json

https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/10109465

fix(vscode): security alerts of trim-newlines by upgrading to 3.0.1

---

packages/vscode-extension/src/commonlib/graphLogin.ts

1. Fix graph login compile error. (Change cache access login to new way, use encrypt method)

fix: graph login compile error

---

packages/cli/src/cmds/build.ts
packages/cli/src/cmds/capability.ts
packages/cli/src/cmds/deploy.ts
packages/cli/src/cmds/new.ts
packages/cli/src/cmds/provision.ts
packages/cli/src/cmds/publish.ts
packages/cli/src/cmds/resource.ts
packages/cli/src/cmds/validate.ts
packages/cli/src/error.ts
packages/cli/src/helpParamGenerator.ts
packages/cli/src/index.ts
packages/cli/tests/unit/help.tests.ts

https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/10338206
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/10338214

test: add help generator's tests

---

packages/cli/src/cmds/preview/depsChecker/cliAdapter.ts

- Implement dialog related features in CLI env checker in the adatper
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/10338893

feat(env-checker): [part-2] Implement dialog UI in CLI env checker

---

packages/cli/tests/e2e/apim/TestCreateNewApim.tests.ts
packages/cli/tests/e2e/apim/TestImportApiIntoApim.tests.ts
packages/cli/tests/e2e/apim/TestUseExistingApim.tests.ts
packages/cli/tests/e2e/commonUtils.ts
packages/cli/tests/e2e/smoke/AzureAppHappyPath.tests.ts

https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/10298207

test: retry new command when apim deploy fail

---

packages/cli/src/cmds/config.ts

https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/10348493

fix: teamsfx config get will show all configs' values

---

templates/bot/js/default/package.json
templates/bot/ts/default/package.json
templates/msgext/js/default/package.json
templates/msgext/ts/default/package.json

related bug https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/10334443

chore(bot): update bot builder version for templates

---

.github/workflows/greeting.yml

1. add greeting github issue workflow. The secret name _secrets.TEAMSFX_BOT_ maybe change based on the repo secret setting name.

chore(workflow): add greeting github issue workflow

---

packages/vscode-extension/src/accountTree.ts
packages/vscode-extension/src/commonlib/azureLogin.ts
packages/vscode-extension/src/commonlib/common/constant.ts

1. Add save, read subscriptionInfo feature.
2. Add support for old projects.

fix: add vscode azure save sub

---

packages/cli/src/cmds/preview/depsChecker/checker.ts
packages/cli/src/cmds/preview/depsChecker/funcToolChecker.ts
packages/fx-core/src/plugins/resource/function/utils/depsChecker/checker.ts
packages/vscode-extension/src/debug/depsChecker/checker.ts
packages/vscode-extension/src/debug/depsChecker/funcToolChecker.ts

* add sentinel for func-core-tools
* fix helplink for linux user

fix(env checker): add sentinel for func-core-tools

---

packages/api/review/teamsfx-api.api.md
packages/api/src/core.ts
packages/fx-core/src/common/tools.ts

To update api and core package version.

feat(core): add encryption api

---

packages/cli/src/cmds/config.ts
packages/cli/src/cmds/resource.ts
packages/cli/src/error.ts
packages/cli/src/utils.ts
packages/cli/tests/unit/cmds/config.tests.ts
packages/cli/tests/unit/cmds/resource.tests.ts
packages/cli/tests/unit/utils.tests.ts

https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/10367028

fix: unknown error when initialize a project with an invalid env file

---

packages/fx-core/src/plugins/resource/aad/utils/tokenProvider.ts

Switch back to App Studio API to avoid alert on application id uri.

fix(aad): switch to App Studio API

---

packages/fx-core/src/common/correlator.ts
packages/fx-core/src/common/index.ts
packages/vscode-extension/package-lock.json
packages/vscode-extension/package.json
packages/vscode-extension/src/commonlib/telemetry.ts
packages/vscode-extension/src/extension.ts
packages/vscode-extension/src/handlers.ts
packages/vscode-extension/src/telemetry/extTelemetryEvents.ts
packages/vscode-extension/src/utils/commonUtils.ts
packages/vscode-extension/test/unit/extension/handlers.test.ts
packages/vscode-extension/test/unit/extension/telemetry.test.ts

chore: add projecId and correlationId to telemetry
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/10160552
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/10160554

chore: add projecId and correlationId to telemetry

---

docs/cli/user-manual.md

Update test command to validate.

docs(CLI): Update user-manual.md

---

packages/vscode-extension/src/extension.ts
packages/vscode-extension/src/handlers.ts
packages/vscode-extension/src/telemetry/extTelemetryEvents.ts

ADO: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/10385602

chore: add telemetry when user open & update teams app project

---

packages/fx-core/src/core/error.ts

https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/10384757

fix(core): invalid project error message

---

packages/cli/tests/e2e/apim/TestCreateNewApim.tests.ts
packages/cli/tests/e2e/apim/TestUseExistingApim.tests.ts
packages/cli/tests/e2e/bot/ProvisionResourceProjectWithNewBot.tests.ts
packages/cli/tests/e2e/commonUtils.ts

e2e test result: https://github.com/OfficeDev/TeamsFx/runs/3130741571?check_suite_focus=true
related bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/10404310/

fix(tests): fix failed e2e tests

---

packages/fx-core/src/plugins/resource/frontend/resources/errors.ts
packages/fx-core/src/plugins/resource/function/plugin.ts
packages/fx-core/src/plugins/resource/function/resources/errors.ts

1. add Azure error code to indicate the root cause of provision error.
2. refine some error suggestion.

fix(frontend&function): refine error handling

---

packages/fx-core/src/plugins/resource/appstudio/constants.ts
packages/fx-core/src/plugins/resource/appstudio/plugin.ts
packages/fx-core/src/plugins/resource/spfx/index.ts
packages/fx-core/src/plugins/resource/spfx/plugin.ts
packages/fx-core/src/plugins/solution/fx-solution/constants.ts
packages/fx-core/src/plugins/solution/fx-solution/solution.ts

refactor: move some manifest constants in solution to appstudio/constants.ts
fix: solution

fix: solution

---

packages/fx-core/src/plugins/solution/fx-solution/executor.ts
packages/fx-core/src/plugins/solution/fx-solution/solution.ts

1) Return post results error 10411718
2) Execute postProvision to update teams app 10412022

fix: return post results error, execute postProvision to update teams app

---

templates/.eslintrc.js
templates/.gitignore
templates/.prettierrc.js
templates/package-lock.json
templates/package.json

https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/10193427/

chore: ESLint support templates 

---

packages/cli/src/utils.ts
packages/fx-core/src/plugins/solution/fx-solution/question.ts

https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/10396422

fix: spfx language question default value

---

packages/cli/package-lock.json
packages/cli/package.json
packages/cli/src/commonlib/telemetry.ts
packages/cli/src/telemetry/cliTelemetryEvents.ts
packages/cli/src/utils.ts
packages/cli/src/yargsCommand.ts
packages/cli/tests/unit/utils.tests.ts

chore: add project-id and correlation-id for CLI telemetry
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/10160555

chore: add project-id and correlation-id for CLI telemetry

---

packages/fx-core/src/plugins/resource/bot/index.ts

fix the bot errorcode issue in bug https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/10335644

fix(bot): change error name 'Error' to 'UnhandledError'

---

docs/vscode-extension/envchecker-help.md
packages/vscode-extension/src/controls/QuickStart.tsx

Fix https://github.com/OfficeDev/TeamsFx/issues/1720

docs(env-checker): update Node.js install link

---

packages/cli/src/cmds/account.ts
packages/cli/src/cmds/deploy.ts
packages/cli/src/cmds/init.ts
packages/cli/src/cmds/new.ts
packages/cli/src/index.ts
packages/cli/src/utils.ts
packages/cli/tests/e2e/smoke/AzureAppHappyPath.tests.ts
packages/cli/tests/unit/utils.tests.ts

https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/9721031

fix: enable case insensitive in CLI

---

packages/fx-core/src/plugins/resource/bot/configs/deployConfig.ts
packages/fx-core/src/plugins/resource/bot/configs/localDebugConfig.ts
packages/fx-core/src/plugins/resource/bot/configs/provisionConfig.ts
packages/fx-core/src/plugins/resource/bot/configs/scaffoldConfig.ts
packages/fx-core/src/plugins/resource/bot/configs/teamsBotConfig.ts
packages/fx-core/src/plugins/resource/bot/resources/strings.ts
packages/fx-core/tests/plugins/resource/bot/unit/index.test.ts
packages/fx-core/tests/plugins/resource/bot/unit/utils.ts

fix bug https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/10430876

fix(bot): sync TeamsBotConfig from context

---

packages/cli/src/commonlib/log.ts
packages/fx-core/src/plugins/resource/appstudio/index.ts
packages/fx-core/src/plugins/resource/spfx/plugin.ts
packages/fx-core/src/plugins/solution/fx-solution/solution.ts

1) Scaffold
2) Provision
3) Deploy
4) Publish
5) Error

fix: add prefix for cli success/error message

---

packages/fx-core/src/common/armInterface.ts
packages/fx-core/src/plugins/solution/fx-solution/arm.ts
packages/fx-core/src/plugins/solution/fx-solution/solution.ts
packages/fx-core/templates/plugins/resource/aad/bicep/input_param.template.bicep
packages/fx-core/templates/plugins/resource/aad/bicep/parameters.json
packages/fx-core/templates/plugins/resource/aad/bicep/variables.template.bicep
packages/fx-core/tests/plugins/resource/aad/unit/expectedBicepFiles/bot_variables.bicep
packages/fx-core/tests/plugins/resource/aad/unit/expectedBicepFiles/input_param.bicep
packages/fx-core/tests/plugins/resource/aad/unit/expectedBicepFiles/parameters.json
packages/fx-core/tests/plugins/resource/aad/unit/expectedBicepFiles/tabAndBot_variables.bicep
packages/fx-core/tests/plugins/resource/aad/unit/expectedBicepFiles/tab_variables.bicep
packages/fx-core/tests/plugins/resource/aad/unit/generateArmTemplates.test.ts
packages/fx-core/tests/plugins/solution/solution.arm.test.ts
packages/fx-core/tests/plugins/solution/solution.scaffold.test.ts
packages/fx-core/tests/plugins/solution/util.ts

Generate arm template when scaffold

chore: generate arm template when scaffold

---

packages/fx-core/src/common/tools.ts
packages/fx-core/src/plugins/resource/simpleauth/constants.ts
packages/fx-core/src/plugins/resource/simpleauth/index.ts
packages/fx-core/src/plugins/resource/simpleauth/plugin.ts
packages/fx-core/src/plugins/resource/simpleauth/utils/common.ts

under the isArmSupportEnabled flag:
1. add common tool to load config from arm output.
2. update simple auth config load.
3. move zip deploy to post-provision stage.
4. move config setting to post-provision stage.
5. remove appsettings.
6. disable provision stage.

chore: load config from arm output

---

packages/fx-core/src/plugins/resource/appstudio/constants.ts
packages/fx-core/src/plugins/resource/appstudio/plugin.ts

Read provision result from ARM deployment output when ARM support enabled

chore: update appstudio plugin logic to support arm

---

packages/cli/src/cmds/preview/npmLogHandler.ts
packages/vscode-extension/src/debug/npmLogHandler.ts
packages/vscode-extension/src/debug/teamsfxTaskHandler.ts

To fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/10475013

fix(local-debug): terminate running services when npm install fails

---

packages/fx-core/src/plugins/resource/frontend/configs.ts
packages/fx-core/src/plugins/resource/frontend/constants.ts
packages/fx-core/src/plugins/resource/frontend/index.ts
packages/fx-core/src/plugins/resource/frontend/plugin.ts
packages/fx-core/src/plugins/resource/simpleauth/constants.ts
packages/fx-core/src/plugins/resource/simpleauth/plugin.ts

under the isArmSupportEnabled flag:
1. update frontend config load.
2. move enable static web to post-provision.
3. disable provision stage.
4. move config setting to post-provision stage.
5. fix bug for arm support in simple auth.

chore: add arm for frontend

---

packages/fx-core/src/plugins/resource/identity/constants.ts
packages/fx-core/src/plugins/resource/identity/index.ts
packages/fx-core/src/plugins/resource/identity/utils/messages.ts

add resource provider check for identity

chore(identity): add resource provider check

---

packages/fx-core/src/plugins/resource/appstudio/plugin.ts

fix: throw error if user build package before provision

---

packages/fx-core/src/core/environment.ts
packages/fx-core/tests/core/environment.test.ts

Add API to list env profiles under `.fx/`, which matches the pattern `/env\.(?<envName>[\w\d-_]+)\.json/i`. Please note, the naming convention might be changed in future and we could discuss it here or later.

chore(core): add API to list env profiles

---

packages/fx-core/src/plugins/solution/fx-solution/constants.ts
packages/fx-core/src/plugins/solution/fx-solution/solution.ts

1. remove user_info in env.default.json
2. check tenant id

feat(collbaoration): check tenant id

---

packages/vscode-extension/src/accountTree.ts
packages/vscode-extension/src/commandsTreeViewProvider.ts
packages/vscode-extension/src/controls/webviewPanel.ts
packages/vscode-extension/src/handlers.ts
packages/vscode-extension/src/telemetry/extTelemetryEvents.ts

1. add login click event when user click login on UI. The signout event for user clicking on UI already exists as signout-start
2. add correlation id for login and logout

chore: add login click event and correlation id for login/logout

---

packages/fx-core/src/plugins/solution/fx-solution/arm.ts

https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/10512760
Detailed error message

perf(arm support): print detailed error message

---

packages/vscode-extension/src/commandsTreeViewProvider.ts
packages/vscode-extension/src/exp/treatmentVariables.ts
packages/vscode-extension/src/extension.ts
packages/vscode-extension/src/handlers.ts
packages/vscode-extension/src/resources/Strings.json
packages/vscode-extension/src/telemetry/extTelemetryEvents.ts

stop the a/b test and remove code.

feat: remove Run and Debug treeview item

---

packages/fx-core/src/core/index.ts

to support cicd scenario, scaffold cli as dev dependency.
and will move this to the cicd plugin in the future.
to finish: https://dev.azure.com/msazure/Microsoft%20Teams%20Extensibility/_workitems/edit/10513290

feat: scaffold with cli as dev dependencies

---

packages/fx-core/src/core/index.ts
packages/fx-core/src/core/middleware/projectSettingsLoader.ts
packages/fx-core/src/core/middleware/projectSettingsWriter.ts
packages/fx-core/tests/core/core.test.ts
packages/fx-core/tests/core/hooks.test.ts

Renaming the middleware for its new scope:
- contextLoader => projectSettingsLoader
- configWriter => projectSettingsWriter
related PR: https://github.com/OfficeDev/TeamsFx/pull/1838

refactor(core): rename contextLoader and configWriter

---

packages/fx-core/src/plugins/resource/localdebug/certificate.ts

Fix ADO bug-10533295 - Revert the trust cert behavior for windows non-admin users.

fix(localdebug): revert cert behavior for windows non-admin users

---

packages/fx-core/src/plugins/resource/simpleauth/plugin.ts

If multi-env feature flag is enabled, SimpleAuth plugin will use `localSettings.json` to read/write local debug related configuration. Otherwise, the local debug config logic remains the same as original.

refactor(local-debug): update simpleauth plugin to use localSettings for local debug

---

packages/fx-core/src/plugins/resource/bot/configs/scaffoldConfig.ts
packages/fx-core/src/plugins/resource/bot/constants.ts
packages/fx-core/src/plugins/resource/bot/resources/messages.ts

fix bug https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/10514986

fix(bot): duplicate language settings

---

packages/fx-core/src/plugins/resource/simpleauth/utils/common.ts

Read local debug configs from `localSettings` to generate the web config for simple auth service.

refactor(localdebug): use localSettings to read local debug config in SimpleAuth

---

packages/fx-core/package-lock.json
packages/fx-core/package.json

`blobServiceClient.getProperties()` throw system error, upgrade storage-blob to 12.7 since we lock the version to 12.6 in package-lock.json.

fix(frontend): SDK introduces error when frontend provision for dev branch

---

packages/api/review/teamsfx-api.api.md
packages/api/src/qm/question.ts
packages/api/src/qm/ui.ts
packages/api/src/qm/visitor.ts

1. add forgetLastValue for Question to ignore the default value of last answer
2. fix some spellings of API doc

feat: forgetLastValue for question

---

.github/workflows/milestoned-azdo.yml

chore: add milestoned-azdo action

---

packages/fx-core/src/core/index.ts

use 0.* to involve latest version.

chore: update cli version range

---

packages/fx-core/src/common/checkAzureResourcePermission.ts
packages/fx-core/src/common/permissionInterface.ts
packages/fx-core/src/plugins/resource/aad/plugin.ts
packages/fx-core/src/plugins/resource/appstudio/plugin.ts
packages/fx-core/src/plugins/resource/bot/plugin.ts
packages/fx-core/src/plugins/resource/frontend/plugin.ts
packages/fx-core/src/plugins/resource/function/plugin.ts
packages/fx-core/src/plugins/resource/simpleauth/plugin.ts
packages/fx-core/src/plugins/solution/fx-solution/solution.ts

refactor: update check permission messages

---

packages/cli/src/index.ts

fix: fix more information link for CLI
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/10009879

fix: fix more information link for CLI

---

templates/tab/js/default/package.json
templates/tab/ts/default/package.json

Has fixed the issue in https://github.com/OfficeDev/TeamsFx/pull/1899

fix(tab): revoke workaround for webpack issue

---

packages/cli/src/utils.ts
packages/vscode-extension/src/debug/commonUtils.ts

Update `getLocalTeamsAppId` due to config structure change.

fix(local debug telemetry): correct appid in telemetry

---

packages/cli/src/cmds/account.ts
packages/cli/tests/unit/cmds/account.tests.ts

1. Fix set subscripition show bug.
Fix issue: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/10541740

fix: cli set subscription

---

packages/cli/src/cmds/build.ts
packages/cli/src/cmds/deploy.ts
packages/cli/src/cmds/preview/commonUtils.ts
packages/cli/src/cmds/preview/preview.ts
packages/cli/src/cmds/provision.ts
packages/cli/src/constants.ts
packages/cli/src/helpParamGenerator.ts
packages/cli/src/utils.ts
packages/cli/tests/unit/help.tests.ts
packages/fx-core/src/core/environment.ts
packages/fx-core/src/core/error.ts
packages/fx-core/src/core/index.ts
packages/fx-core/src/core/middleware/envInfoLoader.ts

1. Add provision, deploy, build, publish env parameter.
2. Add user set env feature.

fix: add cli env support

---

docs/cicd/README.md
docs/cicd/github-cd-template.yml
docs/cicd/github-ci-template.yml
docs/cicd/others-script-cd-template.sh
docs/cicd/others-script-ci-template.sh

1. prepare predefined ymls for github action, example scripts for other platforms.
2. add readme.md placehoder for PM.

feat: prepare predefined ymls/scripts

---

packages/vscode-extension/src/controls/QuickStart.tsx
packages/vscode-extension/src/controls/declarations.d.ts
packages/vscode-extension/src/controls/webviewPanel.ts

feat(vsc): expand create project card

---

packages/cli/src/cmds/preview/commonUtils.ts
packages/cli/src/cmds/preview/constants.ts
packages/cli/src/cmds/preview/preview.ts
packages/cli/src/cmds/preview/task.ts

Adapt to new progress handler introduced in #1769.

fix(cli-preview): adapt to new progress handler

---

docs/cicd/github-cd-template.yml
docs/cicd/others-script-cd-template.sh

adapt appPackage.zip's location with newest cli.

fix: adapt app package location

---

packages/api/review/teamsfx-api.api.md
packages/api/src/error.ts
packages/fx-core/src/common/fileUtils.ts
packages/fx-core/src/common/telemetry.ts
packages/fx-core/src/core/crypto.ts
packages/fx-core/src/core/environment.ts
packages/fx-core/src/core/error.ts
packages/fx-core/src/core/index.ts
packages/fx-core/src/core/middleware/projectSettingsLoader.ts
packages/fx-core/src/core/middleware/projectUpgrader.ts
packages/fx-core/src/core/middleware/telemetrySender.ts
packages/fx-core/tests/core/other.test.ts
packages/vscode-extension/src/handlers.ts
packages/vscode-extension/src/telemetry/extTelemetry.ts
packages/vscode-extension/src/utils/commonUtils.ts

1.add stack data in error-message properties of telemetry data:
2.add desensitized user file data in the issue body:

feat: add stack data in error telemetry and add desensitized file content in issue report

---

packages/fx-core/src/plugins/resource/spfx/error.ts
packages/fx-core/src/plugins/resource/spfx/plugin.ts

related task: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_sprints/taskboard/Teams%20Extensibility%20E2E%20Team/Microsoft%20Teams%20Extensibility/CY21-8.1?workitem=10644873

fix: update spfx error handling

---

packages/vscode-extension/src/utils/survey.ts

https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/10644818

fix: adjust the show-time of the vsc survey

---

packages/fx-core/src/core/tools.ts
packages/vscode-extension/package.json
packages/vscode-extension/src/extension.ts
packages/vscode-extension/src/handlers.ts
packages/vscode-extension/src/telemetry/extTelemetry.ts
packages/vscode-extension/src/telemetry/extTelemetryEvents.ts

Add migrate v1 project command into vsc

feat(localdebug): add migrate v1 project command into vsc

---

packages/fx-core/src/plugins/solution/fx-solution/solution.ts

1) Provision resources
2) click provision again, will check resources and show success message
3) Delete resource group
4) click provision again, resources will be re-provisioned.

fix: users can re-provision resource

---

packages/cli/.vscode/launch.json
packages/cli/src/telemetry/telemetryReporter.ts
packages/cli/tests/unit/telemetry/telemetryReporter.tests.ts
packages/vscode-extension/package-lock.json
packages/vscode-extension/package.json

fix: remove PII from telemetry properties.
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/10676925

fix: remove PII from telemetry properties

---

packages/fx-core/src/plugins/resource/aad/appStudio.ts
packages/fx-core/src/plugins/resource/appstudio/appStudio.ts
packages/fx-core/src/plugins/resource/bot/appStudio/appStudio.ts

As Niranjan suggested, pass values in header rather than query params.

fix: use headers rather than query param

---

packages/vscode-extension/src/accountTree.ts
packages/vscode-extension/src/handlers.ts

ADO: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/10629499

feat(vsc): hide login in case of spfx project

---

packages/fx-core/src/plugins/resource/appstudio/plugin.ts
packages/fx-core/src/plugins/resource/localdebug/index.ts
packages/fx-core/src/plugins/resource/localdebug/launch.ts
packages/fx-core/src/plugins/resource/localdebug/legacyPlugin.ts
packages/fx-core/src/plugins/resource/localdebug/localEnv.ts
packages/fx-core/src/plugins/resource/localdebug/projectSettingLoader.ts
packages/fx-core/src/plugins/resource/localdebug/tasks.ts
packages/fx-core/tests/plugins/resource/localdebug/unit/index.test.ts
packages/fx-core/tests/plugins/resource/localdebug/unit/localEnv.test.ts

Add `migrateV1Project` method in `executeUserTask`.
Localdebug project migrates from Team Toolkit V1.

feat(localdebug): scaffold and localdebug project migrated from Team Toolkit V1 in localdebug plugin

---

packages/fx-core/src/core/tools.ts
packages/vscode-extension/src/debug/commonUtils.ts
packages/vscode-extension/src/debug/constants.ts

do not check port 5000 if the project is migrate from v1

feat(localdebug): do not check port 5000 if the project is migrate from v1

---

packages/vscode-extension/src/accountTree.ts

ADO: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/10700519

fix(vsc): show login when non-teamsfx project

---

.github/workflows/create-milestone.yml

add action to create milestone

chore: add action create milestone

---

packages/cli/src/commonlib/telemetry.ts
packages/cli/src/constants.ts
packages/cli/src/telemetry/cliTelemetryEvents.ts
packages/cli/src/utils.ts
packages/vscode-extension/src/commonlib/telemetry.ts
packages/vscode-extension/src/telemetry/extTelemetryEvents.ts
packages/vscode-extension/src/utils/commonUtils.ts
packages/vscode-extension/test/unit/extension/telemetry.test.ts

chore: add feature flags in telemetry

---

packages/fx-core/src/plugins/solution/fx-solution/commonQuestions.ts
packages/fx-core/tests/plugins/solution/solution.provision.test.ts

test(multi-env): add test cases for asking for resource group info before provision

---

packages/fx-core/src/core/middleware/errorHandler.ts

https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/10728406

feat: convert some SystemError to UserError

---

.github/CODEOWNERS
packages/fx-core/src/common/constants.ts
packages/fx-core/src/common/tools.ts

- add bicep cli env checker settings in solution
- add depsChecker folder in fx-solution/utils

chore(env checker): add bicep cli settings and depsChecker folder in solution

---

packages/dotnet-sdk/src/TeamsFx/ExceptionWithCode.cs
packages/dotnet-sdk/src/TeamsFx/MsGraphAuthProvider.cs
packages/dotnet-sdk/src/TeamsFx/TeamsFx.cs
packages/dotnet-sdk/src/TeamsFx/TeamsUserCredential.cs

related task: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/10551165

chore(dotnet-sdk): update dotnet sdk XML comments

---

docs/vscode-extension/envchecker-help.md
packages/vscode-extension/package.json
packages/vscode-extension/src/constants.ts
packages/vscode-extension/src/utils/commonUtils.ts

Add bicep env checker feature setting, default is false.

feat(vscode-extension): add bicep env checker feature setting

---

packages/fx-core/src/plugins/solution/fx-solution/commonQuestions.ts

feat(multi-env): show location along with resource group

---

packages/fx-core/src/core/index.ts
packages/fx-core/src/core/tools.ts
packages/fx-core/src/plugins/solution/fx-solution/arm.ts

* support to scaffold environment config file & bicep parameter file;
* support to create bicep parameter file while creating new environment;
* merge the feature flag `TEAMSFX_ARM_NEW_FOLDER_STRUCTURE` to `TEAMSFX_MULTI_ENV`

refactor(multi-env): support to scaffold env config & bicep parameter

---

docs/cicd/github-cd-template.yml
docs/cicd/others-script-cd-template.sh

cli's sub-command is changed, adapt it inside ymls.
to finish https://dev.azure.com/msazure/Microsoft%20Teams%20Extensibility/_sprints/taskboard/Compute%20Team/Microsoft%20Teams%20Extensibility/CY21-8.2?workitem=10629315

chore: adapt teamsfx package

---

packages/fx-core/src/plugins/solution/fx-solution/commonQuestions.ts

- Prefill default resource group name in the question. The default resource group name will align with the current behavior.

chore(multi-env): prefill default rg name in the question

---

packages/vscode-extension/src/controls/SampleGallery.tsx

to finish: https://dev.azure.com/msazure/Microsoft%20Teams%20Extensibility/_workitems/edit/10735207

feat: add cicd tag

---

packages/dotnet-sdk/.gitignore
packages/dotnet-sdk/src/TeamsFx/ExceptionWithCode.cs
packages/dotnet-sdk/src/TeamsFx/JsInteropBase.cs
packages/dotnet-sdk/src/TeamsFx/Microsoft.TeamsFx.csproj
packages/dotnet-sdk/src/TeamsFx/Model/Configuration.cs
packages/dotnet-sdk/src/TeamsFx/Model/LogFunction.cs
packages/dotnet-sdk/src/TeamsFx/MsGraphAuthProvider.cs
packages/dotnet-sdk/src/TeamsFx/TeamsFx.cs
packages/dotnet-sdk/src/TeamsFx/TeamsUserCredential.cs

1. Update comments
2. Include XML comments into pack.
before:
after:
3. Change JsInteropBase Class to internal class, so that have to make it sub-class in TeamsUserCrendential class instead of inherit class.

chore(dotnet-sdk): update comments & adjust code

---

packages/fx-core/src/core/tools.ts
packages/fx-core/src/plugins/solution/fx-solution/question.ts
packages/fx-core/src/plugins/solution/fx-solution/solution.ts
packages/fx-core/src/plugins/solution/fx-solution/v2/scaffolding.ts
packages/fx-core/tests/plugins/solution/solution.migrate.test.ts
packages/vscode-extension/src/debug/commonUtils.ts
packages/vscode-extension/src/handlers.ts

Open readme file after execute migrate command

feat(migratev1): open readme file after execute migrate command

---

packages/vscode-extension/package.json
packages/vscode-extension/src/controls/QuickStart.tsx
packages/vscode-extension/src/controls/declarations.d.ts
packages/vscode-extension/src/controls/webviewPanel.ts
packages/vscode-extension/src/exp/treatmentVariables.ts
packages/vscode-extension/src/extension.ts
packages/vscode-extension/src/handlers.ts

feat: [a/b]show welcome page when user didn't open valid project

---

packages/cli/src/cmds/account.ts
packages/cli/tests/unit/cmds/account.tests.ts

1. Fix cli account show subscription information.

fix: cli account show

---

packages/vscode-extension/src/constants.ts
packages/vscode-extension/src/resources/Strings.json
packages/vscode-extension/src/utils/migrateV1.ts

fix(migrate-v1): add learn more button to migrating v1 notification

---

packages/vscode-extension/src/extension.ts

- Codelens now works for the new folder structure

fix(multi-env): fix codelens for new folder structure

---

packages/fx-core/src/plugins/solution/fx-solution/utils/depsChecker/bicepChecker.ts

Remove progress indicator of bicep in log.

chore: remove bicep progress indicator in log (env checker)

---

docs/vscode-extension/migrate-v1/migrate-v1-bot.md

docs(migrate-v1): add migrate v1 bot document

---

packages/fx-core/src/plugins/resource/appstudio/index.ts
packages/fx-core/src/plugins/resource/appstudio/plugin.ts

As vs extension won't call teamsfx cli anymore, remove logics for vs platform.

fix: remove vs check for app studio build/publish

---

packages/vscode-extension/src/debug/commonUtils.ts
packages/vscode-extension/src/handlers.ts
packages/vscode-extension/src/utils/commonUtils.ts
packages/vscode-extension/test/unit/extension/handlers.test.ts

- fix local debug when TEAMSFX_MULTI_ENV is turned off
Tested local debug without feature flag

fix: fix local debug without multi env

---

packages/fx-core/src/core/question.ts

- default resource group name will be correct after changing env

fix(multi-env): fix default resource group name

---

.github/workflows/create-milestone.yml

1. update advanced creation days to 3
2. use default github_token

chore: update create milestone action

---

packages/fx-core/src/common/tools.ts
packages/fx-core/src/plugins/solution/fx-solution/arm.ts
packages/fx-core/tests/plugins/solution/solution.arm.test.ts

[Task Item](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/10719155)

perf(arm support): remove main.json

---

packages/fx-core/src/plugins/solution/fx-solution/commonQuestions.ts
packages/fx-core/src/plugins/solution/fx-solution/constants.ts

Fix [bug](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/10719249)

fix(solution common question): fix error handling when unauthorized subscription

---

packages/fx-core/src/plugins/solution/fx-solution/commonQuestions.ts
packages/fx-core/src/plugins/solution/fx-solution/constants.ts
packages/fx-core/tests/plugins/solution/solution.provision.test.ts

1. Add resource group location list.

fix: add rg location

---

packages/cli/src/cmds/permission.ts
packages/cli/src/telemetry/cliTelemetryEvents.ts
packages/cli/tests/e2e/collaboration/Permission.tests.ts
packages/fx-core/src/plugins/solution/fx-solution/solution.ts

Fix typo in cli parameter: `list-all-collaborator -> list-all-collaborators`
Update output color:
List collaborator:
Grant permission:
Check permission:

perf(collaboration): update cli parameter and output

---

packages/vscode-extension/src/commandsTreeViewProvider.ts
packages/vscode-extension/src/controls/Commands.ts
packages/vscode-extension/src/controls/tree.scss
packages/vscode-extension/src/controls/tree.tsx
packages/vscode-extension/src/handlers.ts

1. handlers for tree view items
2. basic styles: hover, selected
3. tooltip

chore: implement message, handlers, basic styles and tooltip

---

packages/fx-core/src/plugins/solution/fx-solution/constants.ts
packages/fx-core/src/plugins/solution/fx-solution/solution.ts

fixes https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_sprints/taskboard/Teams%20Extensibility%20E2E%20Team/Microsoft%20Teams%20Extensibility/CY21-9.1?workitem=10719707

chore(solution): add programming language telemetry

---

packages/vscode-extension/src/handlers.ts

hidden welcome treeview after migration

fix(migratev1): hidden welcome treeview after migration

---

packages/fx-core/src/common/constants.ts
packages/fx-core/src/common/tools.ts
packages/fx-core/src/plugins/resource/aad/aadAppClient.ts
packages/fx-core/src/plugins/resource/aad/constants.ts
packages/fx-core/src/plugins/resource/function/constants.ts
packages/fx-core/src/plugins/resource/function/ops/provision.ts
packages/fx-core/src/plugins/resource/localdebug/index.ts
packages/fx-core/src/plugins/resource/localdebug/legacyPlugin.ts
packages/fx-core/src/plugins/resource/simpleauth/utils/common.ts
packages/fx-core/templates/plugins/resource/function/bicep/functionConfiguration.template.bicep
packages/fx-core/templates/plugins/resource/simpleauth/bicep/simpleAuthConfiguration.template.bicep
packages/fx-core/tests/plugins/resource/function/unit/expectedBicepFiles/functionConfiguration.bicep
packages/fx-core/tests/plugins/resource/simpleauth/unit/expectedBicepFiles/simple_auth_configuration.all.bicep
packages/fx-core/tests/plugins/resource/simpleauth/unit/index.test.ts
packages/sdk/test/e2e/scripts/StartSimpleAuth.js

`kuojianlu/dev`: checked out from `dev`.

fix(pre-auth): pre-auth office and outlook

---

packages/api/review/teamsfx-api.api.md
packages/api/src/schemas/envConfig.json
packages/api/src/schemas/envConfig.ts
packages/fx-core/src/common/tools.ts
packages/fx-core/src/core/environment.ts
packages/fx-core/src/core/index.ts
packages/fx-core/src/core/tools.ts
packages/fx-core/src/plugins/resource/appstudio/constants.ts
packages/fx-core/src/plugins/resource/appstudio/plugin.ts
packages/fx-core/tests/core/environment.test.ts
packages/fx-core/tests/plugins/solution/solution.arm.test.ts

refactor: add manifest related properties to config file

---

packages/vscode-extension/media/microsoft-teams.svg
packages/vscode-extension/package.json
packages/vscode-extension/src/controls/PanelType.ts
packages/vscode-extension/src/controls/Survey.scss
packages/vscode-extension/src/controls/Survey.tsx
packages/vscode-extension/src/controls/index.tsx
packages/vscode-extension/src/controls/webviewPanel.ts
packages/vscode-extension/src/debug/teamsfxTaskHandler.ts
packages/vscode-extension/src/exp/treatmentVariables.ts
packages/vscode-extension/src/extension.ts
packages/vscode-extension/src/handlers.ts
packages/vscode-extension/src/resources/Strings.json
packages/vscode-extension/src/telemetry/extTelemetryEvents.ts
packages/vscode-extension/src/utils/survey.ts

feat: a/b test new survey on webview page
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/10719505
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/10719506

feat: a/b testing for new survey on webview page

---

packages/cli/src/helpParamGenerator.ts
packages/cli/tests/unit/help.tests.ts

https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/10794642

fix: CLI cannot add ME to projects

---

packages/cli/src/utils.ts

fix(multi-env): cli config file path for multi-env

---

packages/vscode-extension/src/debug/teamsfxTaskHandler.ts
packages/vscode-extension/src/extension.ts
packages/vscode-extension/src/utils/survey.ts
packages/vscode-extension/test/unit/extension/extTelemetry.test.ts

fix: make survey a static class
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/10719505

fix: make survey a static class

---

packages/api/review/teamsfx-api.api.md
packages/api/src/v2/solutionPlugin.ts
packages/fx-core/src/plugins/solution/fx-solution/v2/executeUserTask.ts
packages/fx-core/src/plugins/solution/fx-solution/v2/generateResourceTemplate.ts
packages/fx-core/src/plugins/solution/fx-solution/v2/provisionLocal.ts
packages/fx-core/src/plugins/solution/fx-solution/v2/solution.ts
packages/fx-core/tests/plugins/solution/solution.usertask.test.ts

refactor(solution): add solution v2

---

packages/fx-core/src/core/index.ts
packages/fx-core/src/core/v2/index.ts

Update the .gitignore content while scaffolding new project when multi-env is enabled.

fix(multi-env): add local settings and userdata to git ignore

---

.github/CODEOWNERS
packages/cli/tests/commonlib/botValidator.ts
packages/cli/tests/commonlib/frontendValidator.ts
packages/cli/tests/commonlib/functionValidator.ts
packages/cli/tests/e2e/scaffold/AzureAppScaffold.tests.ts

We don't have test case to cover project language before. Add a e2e test to check if we really create typescript project.

test(e2e): add test case for scaffolding ts project

---

packages/api/review/teamsfx-api.api.md
packages/api/src/core.ts
packages/api/src/solution.ts
packages/api/src/v2/solutionPlugin.ts
packages/api/src/v2/types.ts
packages/fx-core/src/core/index.ts
packages/fx-core/src/plugins/solution/fx-solution/solution.ts
packages/fx-core/src/plugins/solution/fx-solution/v2/createEnv.ts
packages/fx-core/src/plugins/solution/fx-solution/v2/executeUserTask.ts
packages/fx-core/src/plugins/solution/fx-solution/v2/provisionLocal.ts
packages/fx-core/src/plugins/solution/fx-solution/v2/solution.ts
packages/fx-core/tests/core/core.test.ts
packages/fx-core/tests/core/other.test.ts
packages/fx-core/tests/plugins/solution/solution.usertask.test.ts
packages/vscode-extension/src/handlers.ts
packages/vscode-extension/test/unit/extension/mocks/mockCore.ts

1. move azure parameter create code from core to solution
2. Fix API signatures

refactor: core

---

packages/api/review/teamsfx-api.api.md
packages/api/src/error.ts
packages/api/tests/error.test.ts
packages/fx-core/package-lock.json
packages/fx-core/src/common/fileUtils.ts
packages/fx-core/src/core/error.ts
packages/fx-core/src/plugins/resource/aad/index.ts
packages/fx-core/src/plugins/resource/appstudio/index.ts
packages/fx-core/tests/core/environment.test.ts
packages/fx-core/tests/core/hooks.test.ts
packages/vscode-extension/package-lock.json
packages/vscode-extension/src/accountTree.ts

1. Add override constructors for UserError and SystemError
2. Predefine some error types

feat: improve error

---

packages/api/review/teamsfx-api.api.md
packages/api/src/constants.ts
packages/cli/src/cmds/env.ts
packages/cli/src/helpParamGenerator.ts
packages/cli/src/utils.ts
packages/cli/tests/unit/cmds/env.tests.ts

- add teams env activate command and unit test
- display active mark on "teamsfx env list"
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/10844614

feat(multi-env): "teamsfx env activate"

---

packages/vscode-extension/package.json

chore(multi-env): rename add env command

---

.github/workflows/e2e-test.yml

This reverts commit 4811aba06f13e9bcb331636c9f182dbe627cc138.

test: cleanup repo always 

---

packages/vscode-extension/src/constants.ts
packages/vscode-extension/src/extension.ts
packages/vscode-extension/src/telemetry/extTelemetry.ts
packages/vscode-extension/src/telemetry/extTelemetryEvents.ts
packages/vscode-extension/src/utils/commonUtils.ts
packages/vscode-extension/src/utils/upgrade.ts
packages/vscode-extension/test/unit/extension/extTelemetry.test.ts
packages/vscode-extension/test/unit/extension/utils/versionUtil.test.ts

ADO: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/10892498

chore(vsc): add upgrade user propery in telemetry

---

packages/cli/src/utils.ts
packages/cli/tests/commonlib/simpleAuthValidator.ts
packages/cli/tests/e2e/commonUtils.ts
packages/cli/tests/e2e/frontend/TestCreateTabMultiEnv.tests.ts

add frontend e2e test case with multi-env feature flag enabled.
- fix resource name for multi-env cases
- fix CLI telemetry error handling for multi-env cases
- update SKU using bicep parameters file
manual E2E result: https://github.com/OfficeDev/TeamsFx/actions/runs/1233106907
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/10788947

test(multi-env): add multi-env e2e test cases for frontend

---

packages/fx-core/src/plugins/resource/appstudio/constants.ts
packages/fx-core/src/plugins/resource/appstudio/plugin.ts

1) bot id mustache template
2) fix webApplicationInfoResource

refactor: update bot manifest for multi-env

---

docs/fx-core/arm/arm-help.md
packages/fx-core/src/common/constants.ts
packages/fx-core/src/plugins/solution/fx-solution/arm.ts

1. get deployment error message and detailed error
2. add help link and doc
the error message in output pasted in
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/10877773

chore(arm): improve error handling

---

packages/fx-core/src/plugins/solution/fx-solution/arm.ts
packages/fx-core/tests/plugins/resource/sql/unit/index.test.ts
packages/fx-core/tests/plugins/solution/solution.arm.test.ts

add retry for getting deployment status

fix(arm): add retry for getting  deployment status

---

packages/fx-core/src/core/index.ts
packages/fx-core/src/plugins/resource/bot/v2/index.ts
packages/fx-core/src/plugins/resource/utils4v2.ts
packages/fx-core/src/plugins/solution/fx-solution/v2/generateResourceTemplate.ts

fix: bot questions are removed

---

packages/cli/src/index.ts

https://dev.azure.com/msazure/Microsoft%20Teams%20Extensibility/_workitems/edit/10941187

fix(cli): do not swallow the error for initializeQuetionsForHelp

---

packages/fx-core/src/core/index.ts
packages/fx-core/src/core/middleware/projectMigrator.ts

fix [bug](https://dev.azure.com/msazure/Microsoft%20Teams%20Extensibility/_workitems/edit/10941187)

fix: fix issues to multi-env migration

---

packages/fx-core/src/common/tools.ts
packages/fx-core/src/plugins/solution/fx-solution/arm.ts
packages/fx-core/tests/plugins/resource/sql/unit/index.test.ts
packages/fx-core/tests/plugins/solution/solution.arm.test.ts

1. reduce time waiting to improve unit test
2. update sql unit test

chore(arm): reduce time waiting to improve unit test

---

packages/vscode-extension/src/treeview/commandsWebviewProvider.ts
packages/vscode-extension/webpack.config.js

fix: webpack needed resource for tree webview provider

---

packages/fx-core/src/core/middleware/projectMigrator.ts

fix [bug](https://dev.azure.com/msazure/Microsoft%20Teams%20Extensibility/_workitems/edit/10949009/)

fix: fix bug to multi-env migration

---

packages/vscode-extension/src/envTree.ts
packages/vscode-extension/src/resources/Strings.json

**No azure account signed in:**
**No permission to the target subscription (used to provision resource in an environment):**

chore(multi-env): check account and sub in env tree view

---

packages/fx-core/src/core/environment.ts
packages/fx-core/src/core/error.ts
packages/vscode-extension/package.json
packages/vscode-extension/src/extension.ts
packages/vscode-extension/src/handlers.ts

**Add refresh button to allow manually refresh env tree view:**

chore(multi-env): add refresh env support in tree view

---

packages/fx-core/src/plugins/resource/bot/appStudio/appStudio.ts
packages/fx-core/src/plugins/resource/bot/resources/messages.ts

fix bug https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/10941861

fix(bot): re-create bot on Appstudio failed due to non idempotent of AppStudio API

---

.azure-pipelines/CredScanSuppressions.json

1. Update credScan white list.

fix: update white list

---

packages/vscode-extension/CHANGELOG.md
packages/vscode-extension/WHATISNEW.md

update changelog and WhatIsNew.md

docs: Update CHANGELOG.md

---

packages/fx-core/src/plugins/solution/fx-solution/executor.ts
packages/fx-core/src/plugins/solution/fx-solution/solution.ts

https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/10880169
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/10957342

feat(solution): add some check points to locate unknown error

---

packages/api/review/teamsfx-api.api.md
packages/api/src/types.ts
packages/fx-core/src/core/middleware/envInfoLoader.ts
packages/fx-core/src/plugins/solution/fx-solution/v2/provision.ts
packages/vscode-extension/src/handlers.ts

1. Ask target env selection when provision/deploy/build/validate/publish.
2. Remove `Switch environment` option when ask provision consent.

chore(multi-env): select env on provision/deploy/build/validate/publish

---

packages/cli/tests/e2e/multienv/TestRemoteHappyPath.tests.ts

https://github.com/OfficeDev/TeamsFx/actions/runs/1247972054

test(e2e): add sql test case

---

packages/vscode-extension/src/commonlib/azureLogin.ts

1. Throw timeout error when azure login does not success.

fix: update azure time out logic

---

packages/cli/tests/e2e/multienv/TestRemoteHappyPath.tests.ts

E2E test result: https://github.com/OfficeDev/TeamsFx/actions/runs/1247688222
Tested locally

test: add validate/package/publish to e2e

---

packages/fx-core/src/plugins/resource/identity/index.ts
packages/fx-core/src/plugins/resource/identity/utils/contextUtils.ts
packages/fx-core/src/plugins/resource/sql/config.ts
packages/fx-core/src/plugins/resource/sql/constants.ts
packages/fx-core/src/plugins/resource/sql/errors.ts
packages/fx-core/src/plugins/resource/sql/plugin.ts
packages/fx-core/src/plugins/resource/sql/utils/contextUtils.ts
packages/fx-core/templates/plugins/resource/sql/bicep/output.template.bicep
packages/fx-core/templates/plugins/resource/sql/bicep/sql.template.bicep
packages/fx-core/tests/plugins/resource/sql/unit/expectedBicepFiles/output.bicep
packages/fx-core/tests/plugins/resource/sql/unit/expectedBicepFiles/sql.template.bicep

1.add resource id and resource group output
2.update config load
3.update empty admin case in sql bicep

chore(arm): add resource id for sql and identity

---

packages/fx-core/src/core/index.ts
packages/fx-core/src/plugins/resource/utils4v2.ts

fix: executeUserTask

---

packages/cli/tests/commonlib/appStudioValidator.ts
packages/cli/tests/commonlib/interfaces/IAADDefinition.ts
packages/cli/tests/e2e/commonUtils.ts
packages/cli/tests/e2e/multienv/TestRemoteHappyPath.tests.ts
packages/cli/tests/e2e/multienv/TestRemoteHappyPathSPFx.tests.ts
packages/cli/tests/e2e/smoke/AzureAppHappyPath.tests.ts

- Add SPFx happy path E2E test case
- Add utils methods to app studio validator accordingly
E2E test result: https://github.com/OfficeDev/TeamsFx/actions/runs/1248244203
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/10957447

test(multi-env): add spfx happy path

---

packages/fx-core/src/core/index.ts
packages/fx-core/src/core/middleware/envInfoLoader.ts
packages/fx-core/tests/core/core.test.ts
packages/fx-core/tests/core/hooks.test.ts

Similar as the previous fix: https://github.com/OfficeDev/TeamsFx/pull/2387

fix(multi-env): process env is not ready when hooks init

---

packages/cli/src/console/screen.ts
packages/cli/src/prompts/customizedCheckboxPrompt.ts
packages/cli/src/prompts/customizedListPrompt.ts
packages/cli/src/yargsCommand.ts

https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/10942118
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/10942148

fix: the overwritten cases when asking questions

---

docs/cicd/README.md
docs/cicd/others-script-cd-template.sh

to fix: https://stackoverflow.com/questions/69266544/login-via-cli-for-ci-cd/69278613#69278613

docs(cicd): add ci enabled

---

packages/vscode-extension/src/handlers.ts

Fix:
Alert can be hide under "Collaborator" node.

fix: fix node parent in UI

---

packages/vscode-extension/src/extension.ts

1. Keep environment, deployment, provision tree view show logic consistent.
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/10957575/

fix: env tree view logic

---

packages/cli/src/console/progress.ts

https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/10979777

fix: adjust the progress speed and not arrive 100 until complete

---

packages/fx-core/src/core/index.ts
packages/fx-core/src/core/middleware/envInfoLoader.ts
packages/vscode-extension/package.json
packages/vscode-extension/src/envTree.ts
packages/vscode-extension/src/extension.ts
packages/vscode-extension/src/handlers.ts
packages/vscode-extension/src/telemetry/extTelemetryEvents.ts

Hide the active status of environment and command temporary for demo usage and might need to rollback in future.

chore(multi-env): hide active status and command

---

packages/fx-core/src/plugins/resource/appstudio/plugin.ts

https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/10980562

fix(appstudio): throw result as error

---

.github/scripts/lint-pr.sh

https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-comparing-branches-in-pull-requests#three-dot-and-two-dot-git-diff-comparisons

chore: git diff with common base test

---

packages/fx-core/src/plugins/solution/fx-solution/constants.ts
packages/fx-core/src/plugins/solution/fx-solution/solution.ts

fix(collaboration): fix output to show env name in output

---

docs/sdk/teamsfx.authenticationconfiguration.md
docs/sdk/teamsfx.configuration.md
docs/sdk/teamsfx.teamsbotssopromptsettings.md
packages/vscode-extension/package.json
packages/vscode-extension/src/envTree.ts
packages/vscode-extension/src/handlers.ts

perf: move add collaborator icon

---

packages/vscode-extension/src/handlers.ts

ADO: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_sprints/taskboard/Teams%20Extensibility%20E2E%20Team/Microsoft%20Teams%20Extensibility/CY21-9.2?workitem=10978038

fix(vsc): don't await when open new folder

---

packages/fx-core/src/plugins/resource/function/utils/depsChecker/funcPluginAdapter.ts

fix [bug](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/10951582)

chore: fix the infinite loop of dotnet checker in CI

---

packages/fx-core/src/core/middleware/envInfoLoader.ts
packages/fx-core/tests/core/hooks.test.ts

- add unit test for EnvInfoLoaderMW
- fix a bug related to error type
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/10728279

test(multi-env): add unit test for EnvInfoLoaderMW

---

.azure-pipelines/CredScanSuppressions.json

fix: update cred white list

---

packages/api/review/teamsfx-api.api.md
packages/api/src/types.ts
packages/api/src/v2/types.ts
packages/fx-core/src/core/index.ts
packages/fx-core/src/core/middleware/envInfoWriter.ts
packages/fx-core/src/core/tools.ts
packages/fx-core/src/plugins/resource/appstudio/plugin.ts
packages/fx-core/src/plugins/resource/frontend/v2/index.ts
packages/fx-core/src/plugins/resource/utils4v2.ts
packages/fx-core/src/plugins/solution/fx-solution/commonQuestions.ts
packages/fx-core/src/plugins/solution/fx-solution/constants.ts
packages/fx-core/src/plugins/solution/fx-solution/solution.ts
packages/fx-core/src/plugins/solution/fx-solution/v2/adaptor.ts
packages/fx-core/src/plugins/solution/fx-solution/v2/executor.ts
packages/fx-core/src/plugins/solution/fx-solution/v2/getQuestions.ts
packages/fx-core/src/plugins/solution/fx-solution/v2/provision.ts
packages/fx-core/src/plugins/solution/fx-solution/v2/provisionLocal.ts
packages/fx-core/src/plugins/solution/fx-solution/v2/scaffolding.ts
packages/fx-core/src/plugins/solution/fx-solution/v2/utils.ts
packages/fx-core/tests/core/tools.test.ts
packages/fx-core/tests/plugins/resource/apiv2/utils4v2.test.ts
packages/fx-core/tests/plugins/resource/spfx/unit/v2lifecycle.test.ts
packages/fx-core/tests/plugins/solution/solution.provision.test.ts
packages/fx-core/tests/plugins/solution/solution.publish.test.ts

closes https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_sprints/taskboard/Teams%20Extensibility%20E2E%20Team/Microsoft%20Teams%20Extensibility/CY21-9.2?workitem=10754374

refactor(core): provision parity with legacy implementation for API v2 refactor

---

packages/fx-core/src/core/middleware/envInfoWriter.ts
packages/fx-core/src/core/middleware/projectSettingsWriter.ts

https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/11032160

fix: ProjectSettingsWriterMW and EnvInfoWriterMW

---

packages/vscode-extension/src/exp/treatmentVariables.ts
packages/vscode-extension/src/qm/vsc_ui.ts
packages/vscode-extension/src/resources/Strings.json

chore: refine keyboard related tooltip

---

packages/fx-core/src/common/tools.ts
packages/fx-core/src/plugins/solution/fx-solution/constants.ts
packages/fx-core/src/plugins/solution/fx-solution/solution.ts
packages/fx-core/src/plugins/solution/fx-solution/utils/util.ts

fix(collaborator): add hashed env in telemetry

---

packages/vscode-extension/src/handlers.ts

bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_sprints/taskboard/AuthAndData/Microsoft%20Teams%20Extensibility/CY21-9.2?workitem=11034282

fix(collaboration): fix collaborator not show

---

packages/fx-core/src/plugins/solution/fx-solution/solution.ts
packages/vscode-extension/src/envTree.ts
packages/vscode-extension/src/handlers.ts

1. CreateEnv in fx-core now return a string represent the newly added environment name
2. Use cache after create new environment
3. Simplify some code logic

perf(collaboration): use cache after create new environment

---

packages/fx-core/src/plugins/resource/aad/aadAppClient.ts
packages/fx-core/src/plugins/resource/aad/constants.ts
packages/fx-core/src/plugins/resource/aad/errors.ts
packages/fx-core/src/plugins/resource/aad/plugin.ts
packages/fx-core/src/plugins/resource/aad/utils/common.ts
packages/fx-core/tests/plugins/resource/aad/unit/aadAppClient.test.ts

bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/11012874?src=WorkItemMention&src-action=artifact_link

fix(aad): fix error message

---

packages/fx-core/src/plugins/resource/bot/aadRegistration.ts
packages/fx-core/src/plugins/resource/bot/plugin.ts

fix bug https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/10957268

fix(bot): recreate secret to adapt to collaboration scenario

---

packages/vscode-extension/src/exp/treatmentVariables.ts
packages/vscode-extension/src/handlers.ts

ADO: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/11220982

feat(vsc): add treatment variable for  local debug

---

packages/fx-core/src/plugins/resource/bot/configs/provisionConfig.ts
packages/fx-core/src/plugins/resource/bot/plugin.ts
packages/fx-core/src/plugins/resource/bot/resources/strings.ts
packages/fx-core/src/plugins/resource/function/constants.ts
packages/fx-core/src/plugins/resource/function/ops/provision.ts
packages/fx-core/src/plugins/resource/function/plugin.ts
packages/fx-core/src/plugins/resource/identity/config.ts
packages/fx-core/src/plugins/resource/identity/constants.ts
packages/fx-core/src/plugins/resource/identity/index.ts
packages/fx-core/src/plugins/resource/identity/utils/messages.ts
packages/fx-core/src/plugins/resource/sql/constants.ts
packages/fx-core/src/plugins/resource/sql/plugin.ts
packages/fx-core/templates/plugins/resource/bot/bicep/botConfiguration.template.bicep
packages/fx-core/templates/plugins/resource/bot/bicep/botProvision.template.bicep
packages/fx-core/templates/plugins/resource/bot/bicep/module.template.bicep
packages/fx-core/templates/plugins/resource/function/bicep/functionConfiguration.template.bicep
packages/fx-core/templates/plugins/resource/function/bicep/functionProvision.template.bicep
packages/fx-core/templates/plugins/resource/function/bicep/module.template.bicep
packages/fx-core/templates/plugins/resource/identity/bicep/output.template.bicep
packages/fx-core/templates/plugins/resource/identity/bicep/userAssignedIdentity.template.bicep
packages/fx-core/tests/plugins/resource/bot/unit/expectedBicepFiles/botConfiguration.all.bicep
packages/fx-core/tests/plugins/resource/bot/unit/expectedBicepFiles/botProvision.all.bicep
packages/fx-core/tests/plugins/resource/bot/unit/expectedBicepFiles/module.all.bicep
packages/fx-core/tests/plugins/resource/bot/unit/generateArmTemplates.test.ts
packages/fx-core/tests/plugins/resource/function/unit/deploy.test.ts
packages/fx-core/tests/plugins/resource/function/unit/provision.test.ts
packages/fx-core/tests/plugins/resource/identity/unit/expectedBicepFiles/output.bicep
packages/fx-core/tests/plugins/resource/identity/unit/expectedBicepFiles/userAssignedIdentity.template.bicep
packages/fx-core/tests/plugins/resource/identity/unit/provision.test.ts
packages/fx-core/tests/plugins/resource/sql/helper.ts

1. update identity output: identity resource id and identity client id
2. update function, bot, SQL reading the output
3. update unit test

chore(arm): update identity output

---

packages/api/review/teamsfx-api.api.md
packages/api/src/context.ts
packages/api/src/utils/login.ts
packages/cli/src/activate.ts
packages/cli/src/commonlib/sharepointLogin.ts
packages/cli/src/helpParamGenerator.ts
packages/cli/tests/unit/commonlib/sharepointLogin.tests.ts
packages/fx-core/tests/core/utils.ts
packages/fx-core/tests/plugins/resource/apiv2/utils4v2.test.ts
packages/fx-core/tests/plugins/solution/solution.getQuestions.test.ts
packages/fx-core/tests/plugins/solution/solution.provision.test.ts
packages/fx-core/tests/plugins/solution/solution.usertask.test.ts
packages/fx-core/tests/plugins/solution/util.ts
packages/vscode-extension/src/accountTree.ts
packages/vscode-extension/src/commonlib/appStudioLogin.ts
packages/vscode-extension/src/commonlib/sharepointLogin.ts
packages/vscode-extension/src/controls/webviewPanel.ts
packages/vscode-extension/src/handlers.ts

Add sharepoint login token provider for spfx auto deploy.

refactor: add sharepoint login provider for spfx auto deploy

---

packages/fx-core/src/core/error.ts
packages/fx-core/src/core/index.ts
packages/fx-core/src/core/middleware/questionModel.ts
packages/fx-core/tests/core/core.test.ts
packages/vscode-extension/src/handlers.ts

1.  Add notification before v1 project migration
2.  Fix unhandled error

fix(migratev1): add notification before v1 project migration and fix unhandled error

---

packages/vscode-extension/src/handlers.ts

https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/11372095

fix: cancel migration messagebox and show error message

---

packages/fx-core/src/core/middleware/projectMigrator.ts

- Backup before remove old files.

chore: add backup for multi-env migration

---

docs/cicd/jenkins-cd-template.Jenkinsfile
docs/cicd/jenkins-ci-template.Jenkinsfile

chore: fix jenkins comments

---

packages/fx-core/src/core/middleware/projectMigrator.ts

https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/11990509

perf: add bot sku if exist

---

packages/fx-core/src/core/middleware/projectMigrator.ts

FIx [bug](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/12193819)

chore: fix dialog popped up twice when open teams project

---

packages/fx-core/src/core/middleware/envInfoLoader.ts

Fix unit test failure because of TOOLS undefined

fix: fix TOOLS undefined in UT

---

packages/fx-core/src/plugins/solution/fx-solution/v2/scaffolding.ts

https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/12013290

fix(solution): scaffoldReadmeAndLocalSettings

---

packages/fx-core/src/plugins/resource/appstudio/plugin.ts

fix: [insider] handle app name for spfx local debug

---

packages/vscode-extension/src/handlers.ts
packages/vscode-extension/src/resources/Strings.json

refactor(collaboration): add warning messages for Azure related permission

---

packages/vscode-extension/.vscodeignore

chore(vsc): ignore img folder

---

packages/fx-core/src/core/middleware/projectMigrator.ts

Fix [bug](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/12471557)

chore: add compatibility with the latest version of bot

---

packages/vscode-extension/src/handlers.ts

ADO: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/12470211

fix(vsc): fix create project event lost issue

---

packages/vscode-extension/src/envTree.ts
packages/vscode-extension/src/handlers.ts

1. Fix create new environment not show collaborator.

fix: add mutex to add collaborator

---

packages/fx-core/templates/plugins/resource/spfx/solution/README.md

ADO: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_sprints/taskboard/Teams%20Extensibility%20E2E%20Team/Microsoft%20Teams%20Extensibility/CY21-11.1?workitem=12470763

chore(vsc): provision in the cloud typo

---

packages/cli/src/constants.ts
packages/fx-core/src/common/index.ts
packages/fx-core/src/common/samples-config.json
packages/fx-core/src/common/samples.ts
packages/fx-core/src/core/question.ts
packages/vscode-extension/src/controls/Commands.ts
packages/vscode-extension/src/controls/SampleGallery.tsx
packages/vscode-extension/src/controls/messages.ts
packages/vscode-extension/src/controls/webviewPanel.ts

Extract the samples info into common lib in fx-core, so that there will be single source of truth for the samples info.

chore(samples): extract the sample info in common lib

---

.azure-pipelines/CredScanSuppressions.json

chore: update cred white

---

packages/fx-core/src/plugins/solution/fx-solution/commonQuestions.ts

https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/12446250

feat: create tag for resource group

---

.github/workflows/unit-test.yml
packages/cli/tests/commonlib/functionValidator.ts
packages/fx-core/src/core/middleware/projectMigrator.ts
packages/fx-core/src/plugins/resource/aad/utils/configs.ts
packages/fx-core/src/plugins/resource/apim/constants.ts
packages/fx-core/src/plugins/resource/apim/managers/apimManager.ts
packages/fx-core/src/plugins/resource/function/constants.ts
packages/fx-core/src/plugins/resource/function/enums.ts
packages/fx-core/src/plugins/resource/function/plugin.ts
packages/fx-core/src/plugins/resource/simpleauth/plugin.ts
packages/fx-core/src/plugins/resource/simpleauth/utils/common.ts
packages/fx-core/templates/plugins/resource/apim/bicep/apimProvision.bicep
packages/fx-core/templates/plugins/resource/apim/bicep/output.template.bicep
packages/fx-core/templates/plugins/resource/function/bicep/output.template.bicep
packages/fx-core/tests/plugins/resource/apim/expectedBicepFiles/apimProvision.bicep
packages/fx-core/tests/plugins/resource/apim/expectedBicepFiles/output.bicep
packages/fx-core/tests/plugins/resource/function/unit/deploy.test.ts
packages/fx-core/tests/plugins/resource/function/unit/expectedBicepFiles/output.bicep
packages/fx-core/tests/plugins/resource/simpleauth/helper.ts

* [[apim] solution help fill in arm output](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/12461160)
* [[function] solution help fill in arm output](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/12461172)
Design docs: [Auto fill resource plugin context after ARM deployment](https://microsoftapc-my.sharepoint.com/:w:/g/personal/chyuan_microsoft_com/Eb5sguPTQwlOiJXo0se6feIBMOatMLn9w_0_MhrTdkcarg?e=KviQnO&isSPOFile=1)

perf(arm): solution help apim and function fill arm output

---

packages/cli/tests/e2e/multienv/TestRemoteHappyPath.tests.ts
packages/cli/tests/e2e/multienv/TestRemoteHappyPathSPFx.tests.ts

Align with this test plan
E2E TEST: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_testPlans/define?planId=10445806&suiteId=11998474

test(multi-env): align test case names with test plan

---

packages/cli/package-lock.json
packages/cli/package.json

chore: fix audit
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/12492281
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/12492259

chore: fix audit

---

packages/vscode-extension/package-lock.json
packages/vscode-extension/package.json

ADO: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/12492254

chore(vsc): fix security issues in npm dependencies

---

packages/cli/src/cmds/preview/preview.ts

- Remove the check (isWorkspaceSupported) in preview.

chore: remove project check in preview

---

packages/cli/tests/e2e/multienv/TestRemoteHappyPathSPFx.tests.ts
packages/cli/tests/e2e/smoke/SPFxAppHappyPath.tests.ts
packages/cli/tests/e2e/spfx/CreateSPFxProjectWithoutFramework.tests.ts
packages/fx-core/src/plugins/solution/fx-solution/question.ts
packages/fx-core/src/plugins/solution/fx-solution/solution.ts
packages/fx-core/src/plugins/solution/fx-solution/v2/utils.ts
packages/fx-core/tests/plugins/solution/solution.create.test.ts

ADO: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/12400825
VSC experience:
CLI experience:
CLI experience (interactive false):

feat(vsc): remove hosting type from ui

---

packages/fx-core/src/plugins/resource/apim/config.ts
packages/fx-core/src/plugins/resource/apim/constants.ts
packages/fx-core/src/plugins/resource/apim/error.ts
packages/fx-core/src/plugins/resource/apim/factory.ts
packages/fx-core/src/plugins/resource/apim/index.ts
packages/fx-core/src/plugins/resource/apim/managers/aadManager.ts
packages/fx-core/src/plugins/resource/apim/managers/apimManager.ts
packages/fx-core/src/plugins/resource/apim/managers/questionManager.ts
packages/fx-core/src/plugins/resource/apim/managers/scaffoldManager.ts
packages/fx-core/src/plugins/resource/apim/managers/teamsAppAadManager.ts
packages/fx-core/src/plugins/resource/apim/questions/vscodeQuestion.ts
packages/fx-core/src/plugins/resource/apim/services/aadService.ts
packages/fx-core/src/plugins/resource/apim/utils/commonUtils.ts
packages/fx-core/src/plugins/resource/apim/utils/telemetry.ts
packages/fx-core/tests/plugins/resource/apim/aadManager.test.ts
packages/fx-core/tests/plugins/resource/apim/config.test.ts
packages/fx-core/tests/plugins/resource/apim/index.test.ts
packages/fx-core/tests/plugins/resource/apim/teamsAppAadManager.test.ts

Detail: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/12186302
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/12493238

fix(apim): change the error message if enable arm support

---

packages/fx-core/src/plugins/solution/fx-solution/question.ts
packages/fx-core/tests/plugins/solution/solution.container.test.ts

ADO: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/12533476

fix(vsc): not need to choose language in spfx case

---

packages/fx-core/src/plugins/resource/identity/index.ts
packages/fx-core/tests/plugins/resource/frontend/unit/index.test.ts
packages/fx-core/tests/plugins/resource/simpleauth/helper.ts

1. Update identity plugin to handle migrate V1 cases
2. Update frontend hosting plugin test case to adapt the solution auto fill plugin context change
3. Update simple auth plugin test case to adapt the solution auto fill plugin context change

test: fix unit test

---

packages/vscode-extension/package.json
packages/vscode-extension/src/extension.ts
packages/vscode-extension/src/handlers.ts
packages/vscode-extension/src/treeview/deploymentView.tsx
packages/vscode-extension/src/treeview/treeViewManager.ts

ADO: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/10920946
E2E TEST:  removal of UI

feat: remove validate manifest on tree view

---

packages/fx-core/tests/core/core.test.ts

https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_boards/board/t/Infrastructure%20Team/Stories/?workitem=12023943

test(migrate-v1): enable migrate v1 test cases for multi env

---

packages/cli/tests/e2e/frontend/TestCreateTab.tests.ts

VS Code Test Plan
Start a new Project -> Create react app without Azure Function
Provision -> Provision Resource: React app without function
Deploy to Azure -> Deploy react app without Azure Function and SQL

test(frontend): sync test description with test plan

---

.github/scripts/testPlan.ts

1. add break
2. adjust outcome type to string according to: https://docs.microsoft.com/en-us/rest/api/azure/devops/testplan/test-point/update?view=azure-devops-rest-6.1#outcome

chore: adapt outcome type

---

packages/fx-core/src/core/middleware/projectMigrator.ts

E2E TEST: https://github.com/OfficeDev/TeamsFx/blob/dev/packages/cli/tests/e2e/multienv/TestRemoteHappyPath.tests.ts

fix(multi-env): fix empty project settings properties in projectMigrator telemetry

---

packages/fx-core/src/plugins/solution/fx-solution/arm.ts
packages/fx-core/tests/plugins/solution/solution.arm.test.ts

To align with the place holder style introduced in PR: https://github.com/OfficeDev/TeamsFx/pull/2841

chore: use new env placeholder style

---

packages/fx-core/src/common/tools.ts

ADO:
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/12565786
E2E TEST: ignore for quick hotfix and will add E2E test later

fix: download  azure sample will download two samples

---

packages/fx-core/src/common/constants.ts
packages/fx-core/src/core/middleware/projectMigrator.ts
packages/fx-core/tests/core/hooks.test.ts
packages/fx-core/tests/samples/migration/.fx/env.default.json

[apim migratioin support](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/12421163)

perf(apim): migrate apim

---

packages/vscode-extension/src/controls/webviewPanel.ts

E2E TEST: ignore for quick hotfix and will add E2E test later

fix: download azure will have two sample apps from sample gallery

---

packages/vscode-extension/package.json

This is to hotfix migrate commands' strings from PR https://github.com/OfficeDev/TeamsFx/pull/2915

fix: adjust migrate command strings

---

packages/vscode-extension/package.json
packages/vscode-extension/src/codeLensProvider.ts
packages/vscode-extension/src/extension.ts
packages/vscode-extension/src/handlers.ts

feat: open manifest schema in codelens

---

packages/vscode-extension/src/controls/SampleGallery.scss
packages/vscode-extension/src/controls/SampleGallery.tsx

https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_sprints/taskboard/Teams%20Extensibility%20E2E%20Team/Microsoft%20Teams%20Extensibility/CY21-11.2?workitem=12544251

style(vsc): change sample gallery style

---

packages/fx-core/src/plugins/solution/fx-solution/arm.ts

1. add error handling for invalid template scenario.
2. fix error handling bug for no deployment error.

chore(arm): udate arm error handling

---

packages/vscode-extension/package.json

work item: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/12554557/

chore(upgrade): update the command pallete title

---

packages/fx-core/src/core/middleware/projectMigrator.ts

Add below files/folder to .gitignore to avoid unexpected check-in:
- .backup/
- .fx/configs/localSettings.json
- **/.env.teamsfx.local
work item: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/12554473/

chore(upgrade): add backup folder to .gitignore

---

templates/bot-msgext/js/default/README.md
templates/bot-msgext/ts/default/README.md
templates/msgext/js/default/README.md
templates/msgext/ts/default/README.md

fix https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/12420523

docs: fix me doc format 

---

packages/fx-core/src/common/samples-config.json

Point the branch of Sample app from [main ](https://github.com/OfficeDev/TeamsFx-Samples/tree/main)to [v2](https://github.com/OfficeDev/TeamsFx-Samples/tree/v2) branch.

chore(sample): update the branch of sample app from main to v2 for new Teams Toolkit

---

packages/fx-core/src/core/middleware/envInfoLoader.ts

the notification no need to be exposed to customer via UI and can be added to output channel.

chore(multi-env): update the notification when env is selected

---

packages/fx-core/resource/strings.json

According to the feedback from bug bash meeting, remove the `()` around `environment`.

chore: update the provision confirm message

---

packages/fx-core/tests/core/core.test.ts

Since sample apps are upgraded to adapt the new structure for multi-env in [v2 branch](https://github.com/OfficeDev/TeamsFx-Samples/tree/v2), update the unit tests to check the process to create sample app in multi-env scenarios.

chore: update UT to check creating from sample in multi-env

---

packages/fx-core/templates/plugins/resource/bot/bicep/botConfiguration.template.bicep
packages/fx-core/templates/plugins/resource/bot/bicep/botProvision.template.bicep
packages/fx-core/templates/plugins/resource/bot/bicep/config.template.bicep
packages/fx-core/templates/plugins/resource/frontend/bicep/frontendHostingProvision.bicep
packages/fx-core/templates/plugins/resource/frontend/bicep/provision.template.bicep
packages/fx-core/templates/plugins/resource/function/bicep/config.template.bicep
packages/fx-core/templates/plugins/resource/function/bicep/functionConfiguration.template.bicep
packages/fx-core/templates/plugins/resource/function/bicep/functionProvision.template.bicep
packages/fx-core/templates/plugins/resource/identity/bicep/identityProvision.template.bicep
packages/fx-core/templates/plugins/resource/identity/bicep/provision.template.bicep
packages/fx-core/templates/plugins/resource/simpleauth/bicep/config.template.bicep
packages/fx-core/templates/plugins/resource/simpleauth/bicep/simpleAuthConfiguration.template.bicep
packages/fx-core/templates/plugins/resource/simpleauth/bicep/simpleAuthProvision.template.bicep
packages/fx-core/templates/plugins/resource/sql/bicep/provision.template.bicep
packages/fx-core/templates/plugins/resource/sql/bicep/sqlProvision.template.bicep
packages/fx-core/tests/plugins/resource/bot/unit/expectedBicepFiles/botConfig.result.bicep
packages/fx-core/tests/plugins/resource/bot/unit/expectedBicepFiles/botProvision.result.bicep
packages/fx-core/tests/plugins/resource/bot/unit/expectedBicepFiles/config.result.bicep
packages/fx-core/tests/plugins/resource/frontend/unit/expectedBicepFiles/frontendProvision.result.bicep
packages/fx-core/tests/plugins/resource/frontend/unit/expectedBicepFiles/provision.result.bicep
packages/fx-core/tests/plugins/resource/function/unit/expectedBicepFiles/config.result.bicep
packages/fx-core/tests/plugins/resource/function/unit/expectedBicepFiles/functionConfig.result.bicep
packages/fx-core/tests/plugins/resource/function/unit/expectedBicepFiles/functionProvision.result.bicep
packages/fx-core/tests/plugins/resource/identity/unit/expectedBicepFiles/identityProvision.result.bicep
packages/fx-core/tests/plugins/resource/identity/unit/expectedBicepFiles/provision.result.bicep
packages/fx-core/tests/plugins/resource/simpleauth/unit/expectedBicepFiles/config.result.bicep
packages/fx-core/tests/plugins/resource/simpleauth/unit/expectedBicepFiles/simpleAuthConfig.result.bicep
packages/fx-core/tests/plugins/resource/simpleauth/unit/expectedBicepFiles/simpleAuthProvision.result.bicep
packages/fx-core/tests/plugins/resource/sql/unit/expectedBicepFiles/provision.result.bicep
packages/fx-core/tests/plugins/resource/sql/unit/expectedBicepFiles/sqlProvision.result.bicep

1. update resource names for plugins
2. add segment comments for modules

chore(arm): update resource names for plugins

---

.github/CODEOWNERS
packages/fx-core/src/plugins/resource/frontend/blazor/constants.ts
packages/fx-core/src/plugins/resource/frontend/blazor/ops/deploy.ts
packages/fx-core/src/plugins/resource/frontend/blazor/plugin.ts
packages/fx-core/tests/plugins/resource/blazor/unit/index.test.ts

E2E TEST: https://github.com/OfficeDev/TeamsFx/blob/bb110600e8feccf400fb050598f7ff7b4e62d32f/packages/cli/tests/e2e/blazor/TestDeployBlazor.tests.ts#L6

fix(blazor): parse csproj file to get correct framework version

---

packages/fx-core/src/core/middleware/projectMigrator.ts
packages/fx-core/tests/core/hooks.test.ts

1. Remove add resource folder to appPackage logic.

chore: remove add resource to appPackage logic

---

packages/fx-core/src/core/middleware/projectMigrator.ts

Fix [bug](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/12554334)

chore: change solution version to 2.0.0 for upgrade

---

packages/vscode-extension/package.json
packages/vscode-extension/src/extension.ts
packages/vscode-extension/src/handlers.ts

ADO: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_sprints/taskboard/Teams%20Extensibility%20E2E%20Team/Microsoft%20Teams%20Extensibility/CY21-11.2?workitem=125442
57

chore(vsc): add tooltip icon for each treeview

---

packages/fx-core/src/core/index.ts
packages/fx-core/src/core/middleware/projectMigrator.ts

- add more items to .gitignore for upgrade:
* `.fx/subscriptionInfo.json`
* `.fx/states/*.userdata`
* `build`
- add `build` to .gitignore during scaffolding

chore(upgrade): add more items to .gitignore

---

packages/fx-core/src/core/middleware/projectMigrator.ts

Fix [bug](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/12554290)

chore: check userdata before remove keys(upgrade)

---

packages/fx-core/resource/upgrade-change-logs.md

[update upgrade report for apim](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/12614671)

docs(apim): migration docs

---

.github/workflows/milestoned-azdo.yml

1. add ignore choice for feature label for azdo-creation

chore(workflows): ignore feature label for azdo-creation

---

packages/vscode-extension/src/handlers.ts

https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/12457753

feat(extension): show warning message for concurrent error

---

packages/fx-core/src/plugins/solution/fx-solution/commonQuestions.ts

chore: refine error message if user signed in with incorrect M365 account

---

packages/vscode-extension/src/commonlib/log.ts

https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/12626212

feat(extension): hide debug log

---

packages/fx-core/src/common/telemetry.ts
packages/fx-core/src/core/middleware/projectMigrator.ts

- fix https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/12586973/
- also send telemetry error event to make later BI easier

fix: fix missing telemetry event if precheck fails

---

packages/vscode-extension/src/handlers.ts
packages/vscode-extension/src/resources/Strings.json

style(vsc): add ok button

---

packages/fx-core/src/plugins/solution/fx-solution/utils/depsChecker/bicepChecker.ts

fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/12637304
Tested

fix: fix bicep latest version checking

---

packages/vscode-extension/syntaxes/teamsfx-toolkit-output.tmLanguage

perf(collaboration): add color output for list collaboration in vscode

---

packages/fx-core/src/plugins/solution/fx-solution/v2/provision.ts
packages/fx-core/tests/plugins/solution/solution.provision.test.ts

work item: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/12626104/

chore: remove price calculator during provision

---

packages/fx-core/src/core/middleware/concurrentLocker.ts
packages/fx-core/tests/core/middleware/ConcurrentLockerMW.test.ts

chore(solution): improve ut for concurrentLockerMW

---

packages/api/src/error.ts
packages/fx-core/src/common/constants.ts
packages/fx-core/src/core/index.ts
packages/fx-core/src/plugins/resource/appstudio/errors.ts
packages/fx-core/src/plugins/resource/appstudio/index.ts
packages/fx-core/src/plugins/resource/appstudio/plugin.ts
packages/fx-core/src/plugins/resource/appstudio/results.ts
packages/fx-core/src/plugins/solution/fx-solution/arm.ts
packages/fx-core/src/plugins/solution/fx-solution/constants.ts
packages/fx-core/src/plugins/solution/fx-solution/solution.ts
packages/fx-core/src/plugins/solution/fx-solution/v2/getQuestions.ts

[add get help button when validate manifest / zip pkg](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/12663844)

perf(error handling): add get help button when validate manifest / zip pkg

---

packages/vscode-extension/src/migration/migrationTool/ts/replaceTsImport.ts
packages/vscode-extension/test/unit/migration/data/js/app/replace-getContext.input.js
packages/vscode-extension/test/unit/migration/data/js/app/replace-getContext.output.js
packages/vscode-extension/test/unit/migration/data/js/others/replace-import-with-comment.input.js
packages/vscode-extension/test/unit/migration/data/js/others/replace-import-with-comment.output.js
packages/vscode-extension/test/unit/migration/data/ts/app/replace-getContext.input.ts
packages/vscode-extension/test/unit/migration/data/ts/app/replace-getContext.output.ts
packages/vscode-extension/test/unit/migration/data/ts/others/replace-import-with-comment.input.ts
packages/vscode-extension/test/unit/migration/data/ts/others/replace-import-with-comment.output.ts

Fix [ADO 12656106](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/12656106).
E2E TEST: AzureAppScaffold

fix(migration): fix the comments removed bug

---

packages/fx-core/templates/plugins/resource/simpleauth/bicep/simpleAuthProvision.template.bicep
packages/fx-core/tests/plugins/resource/simpleauth/unit/expectedBicepFiles/simpleAuthProvision.result.bicep

fix: typo in simple auth bicep

---

packages/cli/tests/e2e/aad/provisionResourceUpdateEndpointDomainForAad.tests.ts
packages/cli/tests/e2e/apim/TestCreateNewApim.tests.ts
packages/cli/tests/e2e/apim/TestImportApiIntoApim.tests.ts
packages/cli/tests/e2e/multienv/TestRemoteHappyPath.tests.ts
packages/cli/tests/e2e/simpleauth/ProvisionSimpleAuth.tests.ts

1. Change e2e provision SKU to B1.

chore: change e2e test sku

---

packages/fx-core/src/core/middleware/envInfoWriter.ts

https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/12663892

fix(core): not persist state if user cancel provision

---

packages/vscode-extension/src/handlers.ts

https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/12663847

fix(vsc): not show stack in output for UserError

---

packages/vscode-extension/src/envTree.ts

Move the account warning as sub items in env node:

perf(multi-env): fix perf issue for env tree

---

packages/fx-core/.gitignore
packages/fx-core/src/plugins/resource/appstudio/plugin.ts
packages/fx-core/tests/plugins/resource/appstudio/resources-multi-env/templates/appPackage/manifest.local.template.json

E2E TEST: https://github.com/OfficeDev/TeamsFx/blob/dev/packages/cli/tests/e2e/bot/ProvisionResourceProjectWithNewBot.tests.ts

fix: set default url for bot only project

---

packages/vscode-extension/src/handlers.ts

Bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_sprints/taskboard/AuthAndData/Microsoft%20Teams%20Extensibility/CY21-11.2?workitem=12663535

perf(collaboration): show output channel after clicking list collaborator

---

packages/vscode-extension/package.json
packages/vscode-extension/src/constants.ts

chore: update the wording of extension setting

---

packages/vscode-extension/src/envTree.ts

fix [bug: azure not signed in warning for spfx project](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/12664177)

fix: do not show azure account warning for spfx project

---

packages/vscode-extension/package.json
packages/vscode-extension/src/envTree.ts

When project type is SPFX, then hide collaboration buttons
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/12664542/

fix: hide collaboration button for SPFX project

---

packages/fx-core/src/plugins/resource/appstudio/errors.ts
packages/fx-core/src/plugins/resource/appstudio/plugin.ts

fix: local debug configuration

---

packages/fx-core/src/common/tools.ts
packages/fx-core/tests/core/environment.test.ts

Bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_sprints/taskboard/AuthAndData/Microsoft%20Teams%20Extensibility/CY21-11.2?workitem=12664076

fix: remove useless userdata

---

docs/vscode-extension/migrate-v1/migrate-v1-bot.md
docs/vscode-extension/migrate-v1/migrate-v1-tab.md
packages/fx-core/templates/plugins/solution/v1/README.md

Update the manifest file path in the document
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/12664431/

docs(migratev1): update migrate v1 document

---

packages/fx-core/src/plugins/resource/appstudio/index.ts
packages/fx-core/src/plugins/resource/appstudio/plugin.ts
packages/fx-core/src/plugins/resource/appstudio/utils/telemetry.ts

fix: error handling and telemetry for post-provision

---

packages/fx-core/src/core/middleware/projectMigrator.ts

Fix [bug](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/12664689)

chore: remove dialogs of upgrade for localdebug 

---

docs/vscode-extension/migrate-v1/migrate-v1-bot.md
docs/vscode-extension/migrate-v1/migrate-v1.md
packages/fx-core/src/common/samples-config.json
packages/fx-core/src/plugins/solution/fx-solution/question.ts
packages/fx-core/src/plugins/solution/fx-solution/solution.ts
packages/fx-core/src/plugins/solution/fx-solution/v2/getQuestions.ts
packages/vscode-extension/CHANGELOG.md
templates/bot-msgext/js/default/README.md
templates/bot-msgext/ts/default/README.md
templates/msgext/js/default/index.js
templates/msgext/js/default/package.json
templates/mustache-templates/teamsBot.js.mustache
templates/mustache-templates/teamsBot.ts.mustache

https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/12664226

fix: do not use Me as abbreviation for message extension

---

packages/fx-core/src/core/middleware/projectMigrator.ts

E2E TEST: https://github.com/OfficeDev/TeamsFx/actions/runs/1498494500
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/12674299

fix: add function web pattern and update azure SQL server name

---

packages/cli/src/cmds/new.ts
packages/cli/tests/e2e/template/templateCommand.tests.ts

Bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/12674980
E2E TEST: teamsfx new template

fix: teamsfx new template

---

packages/fx-core/src/core/index.ts
packages/fx-core/src/core/middleware/projectSettingsLoader.ts
packages/vscode-extension/src/handlers.ts

feat(core): add isFromSample state for FxCore

---

packages/cli/tests/e2e/apim/TestUseExistingApim.tests.ts
packages/cli/tests/e2e/commonUtils.ts

1. Update clean multi env rg logic.

chore: update clean e2e rg

---

packages/vscode-extension/src/handlers.ts

fix: should not select local env when disable insider preview

---

packages/fx-core/src/common/localSettingsProvider.ts
packages/fx-core/src/plugins/resource/appstudio/plugin.ts
packages/fx-core/src/plugins/resource/localdebug/index.ts
packages/fx-core/tests/core/localSettings.test.ts

1) Create bot, and add tab capability. Need to update localSettings.json.
2) Disable insider preview flag, get correct tabendpoint

fix: bot and tab local debug configuration

---

packages/fx-core/src/common/tools.ts

Fix [bug](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/12681361)

chore: enable bicep by default (cli)

---

packages/fx-core/src/common/samples-config.json

chore: update manual configuration wording

---

packages/fx-core/src/core/middleware/projectMigrator.ts
packages/fx-core/tests/core/hooks.test.ts

fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/12684229/

fix(cli): UnknownError when upgrading

---

packages/fx-core/src/core/middleware/projectMigrator.ts
packages/fx-core/templates/plugins/resource/function/bicep/functionProvision.template.bicep
packages/fx-core/tests/plugins/resource/function/unit/expectedBicepFiles/functionProvision.result.bicep

fix: function not start in migrated project after first provision

---

.github/scripts/kustoErrorClustering.ts
.github/workflows/kusto-error-clustering.yml

fix kusto secret in github action

feat(pipeline): fix kusto error secret

---

packages/fx-core/src/plugins/resource/appstudio/plugin.ts

https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/12615957

chore: revert manifest readonly logic temporarily

---

packages/vscode-extension/src/codeLensProvider.ts
packages/vscode-extension/src/error.ts
packages/vscode-extension/src/extension.ts
packages/vscode-extension/src/handlers.ts
packages/vscode-extension/src/telemetry/extTelemetryEvents.ts

E2E TEST: only for extension 
ADO:
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/12663965

feat: add codelens for states in manifest template

---

packages/cli/src/console/screen.ts
packages/cli/src/prompts/customizedCheckboxPrompt.ts
packages/cli/src/userInteraction.ts
packages/fx-core/src/plugins/solution/fx-solution/question.ts

E2E TEST: Azure App Happy Path
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/12517341
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/12517342
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/12700504

fix: typo error & not pass ids to validation functions

---

packages/vscode-extension/src/exp/treatmentVariables.ts
packages/vscode-extension/src/extension.ts
packages/vscode-extension/src/handlers.ts

feat(ab test): remove create from sample  step

---

packages/fx-core/src/common/armInterface.ts
packages/fx-core/src/plugins/resource/appstudio/v2/index.ts
packages/fx-core/src/plugins/resource/identity/v2/index.ts
packages/fx-core/src/plugins/solution/fx-solution/arm.ts
packages/fx-core/src/plugins/solution/fx-solution/v2/adaptor.ts
packages/fx-core/src/plugins/solution/fx-solution/v2/executeUserTask.ts
packages/fx-core/src/plugins/solution/fx-solution/v2/generateResourceTemplate.ts
packages/fx-core/tests/plugins/solution/solution.arm.test.ts
packages/fx-core/tests/plugins/solution/solution.scaffold.test.ts
packages/fx-core/tests/plugins/solution/solution.usertask.test.ts

fixes https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_queries/edit/12639394/?triage=true.
Arm module is refactored to support both v1 and v2 api.

fix: v2 add capability

---

packages/cli/tests/e2e/sql/ProvisionReactAppWithAzureFunctionAndSQL.tests.ts
packages/fx-core/src/plugins/solution/fx-solution/arm.ts
packages/fx-core/tests/plugins/solution/solution.arm.test.ts

1. update arm poll status for across resource group and subscription
2. update e2e test name

chore(arm): update poll status

---

packages/fx-core/src/plugins/solution/fx-solution/solution.ts
packages/fx-core/templates/plugins/resource/keyvault/bicep/keyVaultProvision.template.bicep
packages/fx-core/tests/plugins/resource/keyvault/unit/expectedBicepFiles/keyVaultProvision.result.bicep

1. support passing SKU name from provisionParameters
2. check whether KeyVault is already added

refactor(key-vault): support passing SKU name from provisionParameters

---

packages/fx-core/src/plugins/solution/fx-solution/v2/collaborationUtil.ts
packages/fx-core/src/plugins/solution/fx-solution/v2/grantPermission.ts
packages/fx-core/src/plugins/solution/fx-solution/v2/listCollaborator.ts
packages/fx-core/tests/plugins/solution/solution.grantPermission.test.ts
packages/fx-core/tests/plugins/solution/solution.listAllCollaborators.test.ts
packages/fx-core/tests/plugins/solution/solution.listCollaborator.test.ts
packages/vscode-extension/syntaxes/teamsfx-toolkit-output.tmLanguage

E2E TEST: https://github.com/OfficeDev/TeamsFx/blob/d18908a872b16f0c737d211bd056ffe9e927018b/packages/cli/tests/e2e/collaboration/Permission.tests.ts#L29

feat(collaboration): collaboration support no aad scenario

---

packages/fx-core/src/common/tools.ts
packages/fx-core/src/core/middleware/envInfoLoader.ts
packages/fx-core/src/plugins/solution/fx-solution/solution.ts
packages/fx-core/src/plugins/solution/fx-solution/v2/provision.ts
packages/fx-core/tests/core/middleware/EnvInfoMW.test.ts

fixes https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_sprints/taskboard/Teams%20Extensibility%20E2E%20Team/Microsoft%20Teams%20Extensibility/CY21-12.1?workitem=12729490

fix: spfx provision

---

packages/api/review/teamsfx-api.api.md
packages/api/src/index.ts
packages/api/src/v3/plugins.ts

feat(api): add platforms for ScaffoldTemplate

---

packages/api/src/qm/validation.ts
packages/fx-core/package-lock.json
packages/fx-core/src/plugins/solution/fx-solution/v2/getQuestions.ts

https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/12729473

fix(api,solution): fix SPFx condition

---

packages/vscode-extension/src/migration/constants.ts

Sample in dev branch: https://github.com/OfficeDev/TeamsFx-Samples/pull/212
Sample in main branch: https://github.com/OfficeDev/TeamsFx-Samples/pull/213

fix(migration): update teams client sdk version

---

packages/cli/src/helpParamGenerator.ts

https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/12758258
E2E TEST: Test Add Function

fix: teamsfx resource add xxx -h

---

packages/fx-core/src/plugins/solution/fx-solution/solution.ts
packages/fx-core/src/plugins/solution/fx-solution/v2/executeUserTask.ts

https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/12760054

fix(solution): not generate arm template when add a function api

---

packages/fx-core/src/plugins/solution/fx-solution/solution.ts
packages/fx-core/src/plugins/solution/fx-solution/v2/provisionLocal.ts
packages/fx-core/src/plugins/solution/fx-solution/v2/utils.ts

fixes https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_queries/edit/12749024/?triage=true

fix: local debug for spfx

---

packages/cli/.vscode/launch.json
packages/cli/src/cmds/permission.ts
packages/cli/src/utils.ts
packages/cli/tests/unit/cmds/permission.tests.ts
packages/vscode-extension/package.json
packages/vscode-extension/src/envTree.ts

E2E TEST: Will add E2E test in next PR

feat(collaboration): collaboration support spfx project, cli message update

---

packages/cli/tests/commonlib/sqlValidate.ts
packages/cli/tests/e2e/commonUtils.ts
packages/cli/tests/e2e/sql/ProvisionWithSkipAddingUser.ts
packages/fx-core/src/plugins/resource/sql/constants.ts
packages/fx-core/src/plugins/resource/sql/plugin.ts
packages/fx-core/tests/plugins/resource/sql/unit/skipAddingUser.test.ts

1. update skipAddingSqlUser  config
2. add e2e test

chore(sql): update skipAddingSqlUser config

---

packages/vscode-extension/package.json

Detail: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_boards/board/t/Infrastructure%20Team/Stories/?workitem=12663652

chore(vsc): change preview button description

---

packages/api/review/teamsfx-api.api.md
packages/api/src/types.ts
packages/cli/src/telemetry/cliTelemetry.ts
packages/cli/src/telemetry/cliTelemetryEvents.ts
packages/cli/src/utils.ts
packages/fx-core/src/core/index.ts
packages/fx-core/src/core/middleware/projectSettingsLoader.ts
packages/fx-core/tests/core/core.test.ts
packages/vscode-extension/src/handlers.ts
packages/vscode-extension/src/telemetry/extTelemetry.ts
packages/vscode-extension/src/telemetry/extTelemetryEvents.ts

- fix the bug that project settings is not changed in 3.0.0
- remove `createdFrom` (not needed and it is a duplicate) and use `version` instead in telemetry

fix: fix project settings version

---

packages/vscode-extension/package.json
packages/vscode-extension/src/extension.ts
packages/vscode-extension/src/handlers.ts
packages/vscode-extension/src/treeview/treeViewManager.ts

1) For Azure project:
2) For SPFx project:

feat: hide add capability or resource in Treeview for SPFx project

---

packages/api/review/teamsfx-api.api.md
packages/api/src/v2/resourcePlugin.ts
packages/api/src/v2/solutionPlugin.ts
packages/fx-core/src/core/index.ts
packages/fx-core/src/core/middleware/envInfoWriter.ts
packages/fx-core/src/plugins/resource/apim/v2/index.ts
packages/fx-core/src/plugins/resource/bot/v2/index.ts
packages/fx-core/src/plugins/resource/frontend/v2/index.ts
packages/fx-core/src/plugins/resource/function/v2/index.ts
packages/fx-core/src/plugins/resource/spfx/v2/index.ts
packages/fx-core/src/plugins/resource/utils4v2.ts
packages/fx-core/src/plugins/solution/fx-solution/v2/deploy.ts
packages/fx-core/src/plugins/solution/fx-solution/v2/executor.ts
packages/fx-core/src/plugins/solution/fx-solution/v2/provision.ts
packages/fx-core/src/plugins/solution/fx-solution/v2/publish.ts
packages/fx-core/src/plugins/solution/fx-solution/v2/solution.ts
packages/fx-core/src/plugins/solution/fx-solution/v2/utils.ts
packages/fx-core/tests/core/utils.ts
packages/fx-core/tests/plugins/resource/spfx/unit/v2lifecycle.test.ts
packages/fx-core/tests/plugins/solution/solution.deploy.test.ts
packages/fx-core/tests/plugins/solution/solution.getQuestions.test.ts
packages/fx-core/tests/plugins/solution/solution.provision.test.ts
packages/fx-core/tests/plugins/solution/solution.publish.test.ts
packages/fx-core/tests/plugins/solution/util.ts

fixes https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_queries/query/eded2ac0-3291-4335-9382-75f270bc8ffa/

fix: apiv2 spfx deploy

---

packages/simpleauth/src/TeamsFxSimpleAuth.Tests/Microsoft.TeamsFx.SimpleAuth.Tests.csproj
packages/simpleauth/src/TeamsFxSimpleAuth/Microsoft.TeamsFx.SimpleAuth.csproj

Fix issue: https://github.com/OfficeDev/TeamsFx/issues/3097

fix: add newtonsoft.json to package reference

---

packages/api/review/teamsfx-api.api.md
packages/api/src/v2/resourcePlugin.ts
packages/fx-core/src/plugins/resource/apim/v2/index.ts
packages/fx-core/src/plugins/resource/bot/v2/index.ts
packages/fx-core/src/plugins/resource/function/v2/index.ts
packages/fx-core/src/plugins/resource/identity/index.ts
packages/fx-core/src/plugins/resource/identity/v2/index.ts
packages/fx-core/src/plugins/resource/keyvault/index.ts
packages/fx-core/src/plugins/resource/keyvault/v2/index.ts
packages/fx-core/src/plugins/resource/simpleauth/v2/index.ts
packages/fx-core/src/plugins/resource/sql/index.ts
packages/fx-core/src/plugins/resource/sql/v2/index.ts
packages/fx-core/src/plugins/resource/utils4v2.ts
packages/fx-core/src/plugins/solution/fx-solution/ResourcePluginContainer.ts
packages/fx-core/src/plugins/solution/fx-solution/arm.ts
packages/fx-core/src/plugins/solution/fx-solution/solution.ts
packages/fx-core/src/plugins/solution/fx-solution/v2/adaptor.ts
packages/fx-core/src/plugins/solution/fx-solution/v2/executeUserTask.ts
packages/fx-core/src/plugins/solution/fx-solution/v2/getQuestions.ts
packages/fx-core/tests/plugins/resource/identity/unit/generateArmTemplates.test.ts
packages/fx-core/tests/plugins/resource/sql/unit/generateArmTemplates.test.ts
packages/fx-core/tests/plugins/solution/solution.usertask.test.ts

https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/12729236

chore(solution): fix add resource

---

packages/fx-core/src/common/tools.ts
packages/fx-core/tests/core/other.test.ts
packages/vscode-extension/package.json

fix: support homedir for project path setting

---

docs/fx-core/arm/arm-help.md

https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/12759218

docs: apim soft delete help docs

---

.github/workflows/cicd_test_trigger.yml

chore: use -X for method

---

packages/fx-core/templates/plugins/resource/simpleauth/bicep/simpleAuthConfiguration.template.bicep
packages/fx-core/tests/plugins/resource/simpleauth/unit/expectedBicepFiles/simpleAuthConfig.result.bicep
packages/fx-core/tests/plugins/resource/simpleauth/unit/expectedBicepFiles/simpleAuthConfigWithKeyVaultPlugin.result.bicep

Fix https://dev.azure.com/msazure/Microsoft%20Teams%20Extensibility/_workitems/edit/12806936

fix(simple-auth): simple auth does not update properties when doing re-provision

---

packages/fx-core/src/common/tools.ts
packages/fx-core/src/plugins/solution/fx-solution/v2/provision.ts

https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/12807768

feat(solution): fix provision

---

packages/fx-core/src/plugins/resource/utils4v2.ts
packages/fx-core/src/plugins/solution/fx-solution/v2/getQuestions.ts
packages/fx-core/src/plugins/solution/fx-solution/v2/provision.ts

fixes 
1:https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/12807393
2.https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_sprints/taskboard/Teams%20Extensibility%20E2E%20Team/Microsoft%20Teams%20Extensibility/CY21-12.1?workitem=12807351
3.https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/12808180

fix: 1.createProject questions for cli 2. spfx collaboration

---

packages/fx-core/src/core/index.ts

fix(core): getProjectConfig

---

packages/fx-core/src/core/error.ts
packages/fx-core/src/core/index.ts

ADO:
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_sprints/taskboard/Teams%20Extensibility%20E2E%20Team/Microsoft%20Teams%20Extensibility/CY21-12.1?workitem=12656042
Screenshot:

chore: refine error msg for invalid root folder

---

packages/fx-core/src/common/tools.ts
packages/fx-core/src/core/error.ts
packages/fx-core/src/core/index.ts
packages/fx-core/tests/core/other.test.ts

https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/12799422
Refine telemetry for better troubleshooting fetch sample data error issue.

chore: refine telemetry for fetch sample data fail event

---

packages/fx-core/src/plugins/resource/utils4v2.ts
packages/fx-core/tests/plugins/resource/apiv2/utils4v2.test.ts

fixes https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/12807219

fix: wrong config structure in getQuestions v2 adaptor

---

templates/bot/js/default/package.json
templates/bot/ts/default/package.json
templates/msgext/js/default/package.json
templates/msgext/ts/default/package.json

- remove ngrok dependency from bot and message extension since installing global ngrok has been implemented in env checker

fix(template): remove ngrok dependency from bot and message extension

---

packages/cli/tests/e2e/apim/TestCreateNewApim.tests.ts
packages/cli/tests/e2e/apim/TestImportApiIntoApim.tests.ts
packages/fx-core/src/plugins/solution/fx-solution/v2/checkPermission.ts
packages/fx-core/src/plugins/solution/fx-solution/v2/collaborationUtil.ts
packages/fx-core/src/plugins/solution/fx-solution/v2/grantPermission.ts

Changes are:
1. Remove subscription parameter from APIM e2e cases. The changes are already made on dev branch.
2. Fix check grant Permission API v2 implementation.

fix: check/grant Permission and APIM e2e tests

---

packages/fx-core/.vscode/launch.json
packages/fx-core/tests/plugins/solution/solution.arm.test.ts
packages/fx-core/tests/plugins/solution/util.ts

https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/12757365

test: add provision and config bicep content compare

---

packages/fx-core/src/plugins/resource/localdebug/index.ts
packages/fx-core/src/plugins/resource/localdebug/settings.ts
packages/fx-core/src/plugins/resource/localdebug/tasks.ts
packages/fx-core/tests/plugins/resource/localdebug/unit/index.test.ts
packages/vscode-extension/src/debug/constants.ts
packages/vscode-extension/src/handlers.ts
packages/vscode-extension/src/resources/Strings.json

- current behavior: https://user-images.githubusercontent.com/37978464/145521469-cae40fc4-2644-4e45-8f32-90fd907e29f4.gif
- new behavior: https://user-images.githubusercontent.com/37978464/145521513-7f860a73-53e0-44fd-b98f-612b9fe6409a.gif
- current behavior: https://user-images.githubusercontent.com/37978464/145521686-0f57dca0-e5ff-4817-8b41-08a7b64bd404.gif
- new behavior: https://user-images.githubusercontent.com/37978464/145521789-d59c4564-6e20-493e-ad39-7b56e39c0f32.gif
- current behavior: https://user-images.githubusercontent.com/37978464/145521860-151ae39e-1044-48b6-9fc8-3e58bd5b8554.gif
- new behavior: https://user-images.githubusercontent.com/37978464/145521901-d41d1488-243e-4cf3-bc72-04f558e6a6c3.gif
The error dialogs are not covered in this PR: modal or not, detailed message, …

fix(localdebug): remove debug anyway

---

.github/workflows/cicd_test_trigger.yml

remove env BRANCH, use github secrets

chore: use native macro

---

packages/fx-core/src/plugins/resource/sql/config.ts
packages/fx-core/src/plugins/resource/sql/plugin.ts
packages/fx-core/src/plugins/resource/sql/utils/checkInput.ts
packages/fx-core/tests/plugins/resource/sql/unit/index.test.ts

1. update input validate
2. remove useless code
3. add ut

chore(sql): update input validate

---

.github/workflows/unit-test.yml
packages/fx-core/src/core/middleware/localSettingsLoader.ts

https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/12826032

chore(core): local settings loader

---

packages/vscode-extension/src/qm/vsc_ui.ts

fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/12816005

fix(bi): fix the bug that cause project migrator telemetry lost

---

.github/workflows/unit-test.yml
packages/fx-core/src/core/index.ts
packages/fx-core/src/core/middleware/localSettingsLoader.ts
packages/fx-core/src/plugins/resource/utils4v2.ts
packages/fx-core/src/plugins/solution/fx-solution/v2/provisionLocal.ts

fixes https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/12837954
and https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/12836125

fix: local debug are now updated

---

packages/fx-core/src/plugins/resource/appstudio/plugin.ts
packages/fx-core/tests/plugins/solution/solution.provision.test.ts

ADO:
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_sprints/taskboard/Teams%20Extensibility%20E2E%20Team/Microsoft%20Teams%20Extensibility/CY21-12.2?workitem=12615957
E2E TEST: SPFxHappyPath

feat: make manifest as readonly

---

packages/fx-core/src/plugins/resource/utils4v2.ts
packages/fx-core/src/plugins/solution/fx-solution/v2/provision.ts
packages/fx-core/src/plugins/solution/fx-solution/v2/provisionLocal.ts
packages/fx-core/tests/plugins/resource/apiv2/utils4v2.test.ts

fixes https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/12849296.

fix: concurrently modify localSettings

---

packages/fx-core/src/common/localSettingsProvider.ts

fixes https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/12856828

fix: local settings encryption

---

packages/fx-core/src/plugins/solution/fx-solution/commonQuestions.ts
packages/fx-core/src/plugins/solution/fx-solution/solution.ts
packages/fx-core/src/plugins/solution/fx-solution/v2/provision.ts

Fix [Bug 12664212: [Toolkit 3.0.0] [BugBash] Shouldn't create resource group if provision is canceled](https://dev.azure.com/msazure/Microsoft%20Teams%20Extensibility/_workitems/edit/12664212)
If user canceled the provision, toolkit will not create the resource group.

fix: only create resource group when user confirm the provision

---

packages/fx-core/src/core/question.ts

ADO:
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_sprints/taskboard/Teams%20Extensibility%20E2E%20Team/Microsoft%20Teams%20Extensibility/CY21-12.2?workitem=12587763
E2E TEST: for extension only

fix: teams app name length has a max limit of 30

---

docs/cicd_insider/README.md
docs/cicd_insider/github-cd-template.yml
docs/cicd_insider/jenkins-cd-template.Jenkinsfile
docs/cicd_insider/others-script-cd-template.sh

Replace username/password with service principal login for Azure in CI/CD.
To finish: https://dev.azure.com/msazure/Microsoft%20Teams%20Extensibility/_workitems/edit/12421108
On hold for smoke test after cli's ready, but you can review it first.

chore: cicd service principal integration

---

packages/fx-core/templates/plugins/resource/keyvault/bicep/provision.template.bicep
packages/fx-core/tests/plugins/resource/keyvault/unit/expectedBicepFiles/provision.result.bicep

ADO task: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/12788123

refactor(key-vault): output key Vault Reference String in state.{env}.json file

---

packages/fx-core/src/plugins/resource/appstudio/plugin.ts

ADO link: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/12655978

fix: unknown error for validate manifest

---

packages/cli/tests/e2e/aad/aadErrorTests.tests.ts

success run: https://github.com/OfficeDev/TeamsFx/actions/runs/1600831719

fix: fix e2e test

---

packages/fx-core/src/plugins/solution/fx-solution/debug/scaffolding.ts

Detail: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_boards/board/t/Infrastructure%20Team/Stories/?workitem=12879287

fix(localdebug): fix decrypt the localdebug secret after add resource

---

packages/dotnet-sdk/README.md

Add documents about version and upgrade steps.
Related issue: #3327

docs(dotnet-sdk): add upgrade steps

---

packages/vscode-extension/test/unit/extension/commonUtils.test.ts

Fix https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/12883921

fix: use tdd instead of bdd for mocha

---

packages/cli/src/commonlib/azureLoginCI.ts

1. Deploy no need to check subscription file.

chore: cd no need subscription file

---

packages/api/review/teamsfx-api.api.md
packages/api/src/error.ts
packages/vscode-extension/src/handlers.ts

1. add optional property notificationMessage in error.

chore(solution): add notification message for error

---

packages/fx-core/src/core/index.ts
packages/fx-core/src/core/middleware/envInfoLoader.ts
packages/fx-core/src/core/middleware/envInfoWriter.ts
packages/fx-core/src/core/middleware/errorHandler.ts
packages/fx-core/src/core/middleware/localSettingsLoader.ts
packages/fx-core/src/core/middleware/localSettingsWriter.ts
packages/fx-core/src/core/middleware/projectMigrator.ts
packages/fx-core/src/core/middleware/projectSettingsLoader.ts
packages/fx-core/src/core/middleware/projectSettingsWriter.ts
packages/fx-core/src/core/middleware/questionModel.ts
packages/fx-core/src/plugins/resource/appstudio/plugin.ts
packages/fx-core/src/plugins/solution/fx-solution/arm.ts
packages/fx-core/src/plugins/solution/fx-solution/v2/provision.ts
packages/fx-core/tests/core/core.test.ts
packages/fx-core/tests/core/middleware/EnvInfoMW.test.ts
packages/fx-core/tests/core/middleware/LocalSettingsLoaderMW.test.ts
packages/fx-core/tests/core/middleware/ProjectSettingsLoaderMW.test.ts
packages/fx-core/tests/core/middleware/ProjectSettingsLoaderMW_V3.test.ts
packages/fx-core/tests/core/middleware/QuestionModelMW.test.ts
packages/fx-core/tests/core/middleware/SolutionLoaderMW.test.ts

remove isV2() feature flag is related codes

chore(core): remove isV2()

---

packages/fx-core/tests/plugins/resource/spfx/unit/deploy.test.ts

fix: avoid timeout wait

---

packages/api/src/error.ts
packages/fx-core/src/plugins/solution/fx-solution/arm.ts

customize notification message to update error handling.

chore(arm): customize notification message for error

---

packages/fx-core/src/core/index.ts
packages/fx-core/src/plugins/resource/utils4v2.ts

Related PR: https://github.com/OfficeDev/TeamsFx/pull/3470

chore: (part 2) remove multi env check form fx-core

---

packages/fx-core/src/core/middleware/projectMigrator.ts
packages/fx-core/src/core/middleware/projectUpgrader.ts

Related: 
* https://github.com/OfficeDev/TeamsFx/pull/3472
* https://github.com/OfficeDev/TeamsFx/pull/3470

chore: (part 3) remove multi env check from fx-core

---

packages/fx-core/templates/plugins/resource/keyvault/bicep/keyVaultProvision.template.bicep
packages/fx-core/templates/plugins/resource/keyvault/bicep/provision.template.bicep
packages/fx-core/tests/plugins/resource/keyvault/unit/expectedBicepFiles/keyVaultProvision.result.bicep
packages/fx-core/tests/plugins/resource/keyvault/unit/expectedBicepFiles/provision.result.bicep

ADO task: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/12788123

fix(key-vault): add Resource Id in output

---

packages/cli/CONTRIBUTING.md

chore: update CLI doc
Fix node version.
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/12899078

chore: update CLI doc

---

packages/fx-core/src/core/middleware/errorHandler.ts

Detail: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_boards/board/t/Infrastructure%20Team/Stories/?workitem=12901623

fix(migratev1): donot print inputs in error handler

---

packages/fx-core/src/plugins/solution/fx-solution/v2/provisionLocal.ts

Detail: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/12899181

fix(localdebug): allow v1 project local debug without aad plugin

---

packages/api/src/error.ts
packages/fx-core/src/plugins/resource/sql/errors.ts
packages/fx-core/src/plugins/resource/sql/managementClient.ts
packages/fx-core/src/plugins/resource/sql/plugin.ts
packages/fx-core/src/plugins/resource/sql/results.ts
packages/fx-core/src/plugins/resource/sql/sqlClient.ts
packages/fx-core/tests/plugins/resource/sql/unit/index.test.ts
packages/fx-core/tests/plugins/resource/sql/unit/skipAddingUser.test.ts
packages/fx-core/tests/plugins/resource/sql/unit/sqlClient.test.ts

1. add notification message for sql error.
2. update error message.
3. remove duplicated error log in sql plugin.
4. mock network call in unit test.

chore(sql): add notification message and remove error log in plugin

---

docs/cicd_insider/README.md
docs/cicd_insider/github-cd-template.yml
docs/cicd_insider/jenkins-cd-template.Jenkinsfile
docs/cicd_insider/others-script-cd-template.sh

remove userdata from cicd.
also, remove ci_enabled from cicd
to finish the task: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/12896175

chore: remove userdata from cicid

---

templates/tab/js/default/package.json
templates/tab/ts/default/package.json

1. add dev dependency `cross-env` and `env-cmd`.
2. add sample build script to use .env.teamsfx.dev file for building react app in dev environment.

chore(frontend): add build script for react in multi env

---

packages/fx-core/tests/plugins/solution/debug/util/tasks.test.ts

ADO:
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_queries/query/?tempQueryId=3033c54a-e116-4e4a-9c63-16605869c66f

test: add unit test for spfx local debug in parallel issue

---

packages/cli/README.md

Update CLI Readme to reference User Manual on Doc Site.

docs(readme): update CLI readme

---

packages/cli/tests/e2e/solution/ScaffoldTabThenAddFunctionAndSQL.test.ts

Closes https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/12836125
Manually running this case is successful https://github.com/OfficeDev/TeamsFx/actions/runs/1652642413.

test(cli): add localSettings validation when adding function and sql 

---

packages/fx-core/templates/plugins/resource/frontend/bicep/frontendHostingProvision.bicep
packages/fx-core/tests/plugins/resource/frontend/unit/expectedBicepFiles/frontendProvision.result.bicep

To help users understand the provision behavior easier

chore: add comments for frontend hosting bicep files

---

packages/cli/tests/commonlib/cliHelper.ts
packages/cli/tests/commonlib/utilities.ts
packages/cli/tests/e2e/function/TabAddFunctionSql.tests.ts
packages/cli/tests/e2e/sql/ProvisionReactAppWithAzureFunctionAndSQL.tests.ts
packages/cli/tests/e2e/sql/ProvisionWithSkipAddingUser.ts

1. Remove log of setting value to not print secret
2. Add unique uuid in password

test: remove log of value

---

packages/fx-core/src/plugins/resource/appstudio/index.ts

https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/12941918

fix: admin portal cannot open

---

packages/cli/src/cmds/config.ts
packages/cli/src/cmds/index.ts
packages/cli/src/cmds/provision.ts
packages/cli/src/cmds/resource.ts
packages/cli/src/error.ts
packages/cli/src/helpParamGenerator.ts
packages/cli/src/utils.ts
packages/cli/tests/unit/cmds/config.tests.ts
packages/cli/tests/unit/cmds/resource.tests.ts
packages/cli/tests/unit/utils.tests.ts

code cleanup https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/12890204/

chore: remove isMultiEnvEnabled from CLI

---

packages/fx-core/templates/plugins/resource/keyvault/bicep/keyVaultProvision.template.bicep
packages/fx-core/tests/plugins/resource/keyvault/unit/expectedBicepFiles/keyVaultProvision.result.bicep

help users better understand the provision behavior

chore: add comments for key vault bicep files

---

packages/fx-core/templates/plugins/resource/identity/bicep/identityProvision.template.bicep
packages/fx-core/tests/plugins/resource/identity/unit/expectedBicepFiles/identityProvision.result.bicep

help users better understand provision behavior of user assigned identity

chore: add comments for identity bicep files

---

packages/fx-core/templates/plugins/resource/sql/bicep/sqlProvision.template.bicep
packages/fx-core/tests/plugins/resource/sql/unit/expectedBicepFiles/sqlProvision.result.bicep

help users better understand provision behavior

chore: add comments for sql bicep files

---

packages/fx-core/templates/plugins/resource/apim/bicep/apimConfiguration.bicep
packages/fx-core/templates/plugins/resource/apim/bicep/apimProvision.bicep
packages/fx-core/templates/plugins/resource/apim/bicep/config.template.bicep
packages/fx-core/tests/plugins/resource/apim/expectedBicepFiles/apimConfiguration.result.bicep
packages/fx-core/tests/plugins/resource/apim/expectedBicepFiles/apimProvision.result.bicep
packages/fx-core/tests/plugins/resource/apim/expectedBicepFiles/config.result.bicep

to help users better understand provision behavior and purpose of each resource

chore: add comments for APIM bicep

---

packages/cli/package.json
packages/fx-core/src/plugins/solution/fx-solution/question.ts
packages/fx-core/src/plugins/solution/fx-solution/v2/getQuestions.ts

1. fix: SQL is always addable
2. fix: getQuestionns for addResource when platform=cli_help
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/12961263

fix(solutionv2): add resource sql

---

packages/fx-core/src/common/armInterface.ts

1. Add comments for ARM template result
2. Remove unused interfaces

chore: add comments for interface and remove unused interfaces

---

packages/fx-core/src/common/template-utils/index.ts
packages/fx-core/src/common/template-utils/readme.md
packages/fx-core/src/common/template-utils/templates.ts
packages/fx-core/src/common/template-utils/templatesActions.ts
packages/fx-core/src/common/template-utils/templatesUtils.ts
packages/fx-core/src/plugins/resource/bot/languageStrategy.ts
packages/fx-core/src/plugins/resource/frontend/dotnet/ops/deploy.ts
packages/fx-core/src/plugins/resource/frontend/ops/scaffold.ts
packages/fx-core/src/plugins/resource/frontend/resources/templateInfo.ts
packages/fx-core/src/plugins/resource/function/ops/deploy.ts
packages/fx-core/src/plugins/resource/function/ops/scaffold.ts
packages/fx-core/tests/common/templateFetch.test.ts
packages/fx-core/tests/plugins/resource/bot/unit/languageStrategy.test.ts
packages/fx-core/tests/plugins/resource/frontend/unit/index.test.ts
packages/fx-core/tests/plugins/resource/function/unit/scaffold.test.ts

1. Move scaffold utils to a dedicated folder.
2. Add readme for how to debug template.

refactor(template): template utils

---

packages/vscode-extension/CHANGELOG.md
packages/vscode-extension/WHATISNEW.md

the expected version should be 3.2.0.

chore: fix release version

---

packages/fx-core/src/plugins/resource/apim/error.ts
packages/fx-core/src/plugins/resource/apim/managers/apimManager.ts
packages/fx-core/src/plugins/resource/apim/managers/questionManager.ts
packages/fx-core/src/plugins/resource/apim/questions/vscodeQuestion.ts
packages/fx-core/tests/plugins/resource/apim/config.test.ts
packages/fx-core/tests/plugins/resource/apim/index.test.ts

I just removed the feature flag. Some further code clean up (like removing legacy code that is not invoked any more) is still required by component owner.

chore: remove arm feature flag in apim plugin

---

packages/fx-core/src/plugins/solution/fx-solution/v2/executeUserTask.ts

E2E test pass: https://github.com/OfficeDev/TeamsFx/actions/runs/1677708458

fix(solutionv2): add capability Tab missing simple auth config

---

.azure-pipelines/CredScanSuppressions.json

chore: update cred white list

---

packages/fx-core/src/plugins/resource/bot/configs/provisionConfig.ts
packages/fx-core/src/plugins/resource/bot/plugin.ts
packages/fx-core/src/plugins/resource/function/index.ts
packages/fx-core/src/plugins/resource/function/plugin.ts
packages/fx-core/tests/plugins/resource/bot/unit/index.test.ts
packages/fx-core/tests/plugins/resource/frontend/helper.ts
packages/fx-core/tests/plugins/resource/frontend/unit/config.test.ts
packages/fx-core/tests/plugins/resource/function/unit/deploy.test.ts
packages/fx-core/tests/plugins/resource/function/unit/provision.test.ts

I just removed the feature flag. Some further code clean up is required.

chore: remove arm feature flag for bot and function

---

packages/api/review/teamsfx-api.api.md
packages/api/src/v3/plugins.ts
packages/api/src/v3/solution.ts
packages/api/src/v3/solutionSettings.ts
packages/fx-core/src/core/index.ts
packages/fx-core/src/plugins/resource/frontend/ops/deploy.ts
packages/fx-core/src/plugins/resource/frontend/v3/AzureStoragePlugin.ts
packages/fx-core/src/plugins/resource/frontend/v3/ReactTabScaffoldPlugin.ts
packages/fx-core/src/plugins/solution/fx-solution/debug/scaffolding.ts
packages/fx-core/src/plugins/solution/fx-solution/v3/addModule.ts
packages/fx-core/src/plugins/solution/fx-solution/v3/addResource.ts
packages/fx-core/src/plugins/solution/fx-solution/v3/deploy.ts
packages/fx-core/src/plugins/solution/fx-solution/v3/scaffold.ts
packages/fx-core/src/plugins/solution/spfx-solution/addModule.ts
packages/fx-core/src/plugins/solution/spfx-solution/scaffold.ts
packages/fx-core/src/plugins/solution/spfx-solution/solution.ts
packages/fx-core/tests/plugins/solutionv3/mockPlugins.ts
packages/fx-core/tests/plugins/solutionv3/solution.deploy.test.ts

1. plugin add property type  ( "resource"|"scaffold")  to help select all plugins by type
2. fix fontendhosting plugin
3. fix local debug api
4. improve v3 api interface

feat: fix v3 types

---

packages/fx-core/src/plugins/resource/sql/index.ts

remove SQL plugin active condition of tab existing

chore(sql): update active condition

---

packages/vscode-extension/src/qm/vsc_ui.ts

https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/12963091

feat: remove step info for scaffolding

---

packages/cli/tests/commonlib/apimValidator.ts
packages/cli/tests/e2e/apim/BotAddApim.tests.ts
packages/cli/tests/e2e/apim/TabAddApim.tests.ts
packages/cli/tests/e2e/apim/TabAddApimBot.tests.ts

[[e2e][apim] verify configuration successfully changed when with different plugins](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/12905462)

test: add apim e2e test when with different plugins

---

packages/fx-core/src/common/localSettingsConstants.ts
packages/fx-core/src/common/localSettingsProvider.ts
packages/fx-core/src/plugins/resource/appstudio/constants.ts
packages/fx-core/src/plugins/resource/appstudio/plugin.ts
packages/fx-core/src/plugins/resource/frontend/constants.ts
packages/fx-core/src/plugins/resource/frontend/index.ts
packages/fx-core/src/plugins/resource/frontend/plugin.ts
packages/fx-core/src/plugins/resource/frontend/v2/index.ts
packages/fx-core/templates/plugins/resource/frontend/bicep/frontendHostingProvision.bicep
packages/fx-core/templates/plugins/resource/frontend/bicep/provision.template.bicep
packages/fx-core/tests/plugins/resource/frontend/unit/expectedBicepFiles/frontendProvision.result.bicep
packages/fx-core/tests/plugins/resource/frontend/unit/expectedBicepFiles/provision.result.bicep

E2E test pass: https://github.com/OfficeDev/TeamsFx/actions/runs/1686156988

fix: fix hard code tab index path in manifest template

---

packages/cli/tests/commonlib/simpleAuthValidator.ts
packages/cli/tests/e2e/simpleauth/ProvisionSimpleAuth.tests.ts
packages/cli/tests/e2e/simpleauth/TabAddBot.tests.ts
packages/cli/tests/e2e/simpleauth/TabAddKeyvault.tests.ts

[[e2e][simpleauth] verify configuration successfully changed when with different plugins](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/12905503)

test(simpleauth): add e2e test simple auth with other plugins

---

packages/fx-core/src/common/local/projectSettingsHelper.ts
packages/fx-core/tests/common/local/localEnvManager.test.ts
packages/fx-core/tests/common/local/localSettingsHelper.test.ts
packages/fx-core/tests/common/local/portChecker.test.ts
packages/fx-core/tests/common/local/projectSettingsHelper.test.ts
packages/fx-core/tests/plugins/solution/debug/solution.debug.scaffolding.test.ts

Align component enablement logic the same as plugin.activate(). Adjust unit test as well.
@jayzhang - the same purpose as https://github.com/OfficeDev/TeamsFx/pull/3625

fix(localdebug): make projectsettingshelper more accurate

---

packages/vscode-extension/src/controls/SampleGallery.scss
packages/vscode-extension/src/controls/SampleGallery.tsx

feat: new sample gallery overview page layout

---

packages/vscode-extension/src/debug/prerequisitesHandler.ts

Detail: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/12863544

chore(localdebug): trust cert in prerequisitesHandler

---

packages/fx-core/src/common/samples-config.json
packages/fx-core/src/common/samples.ts
packages/vscode-extension/src/controls/ISamples.ts
packages/vscode-extension/src/controls/SampleGallery.scss
packages/vscode-extension/src/controls/SampleGallery.tsx

ADO: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_sprints/taskboard/Teams%20Extensibility%20E2E%20Team/Microsoft%20Teams%20Extensibility/CY22-1.1?workitem=12983455

feat: star the suggested sample apps

---

packages/fx-core/src/core/middleware/errorHandler.ts

https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/13023179

fix(core): convert no space left as user error

---

packages/fx-core/src/plugins/solution/fx-solution/v2/scaffolding.ts

https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/12995363

feat(solutionv2): scaffold telemetry

---

packages/vscode-extension/package.json
packages/vscode-extension/src/extension.ts

Disable to show v1 migration notification
PS: The code will be removed in another PR.

chore(migrate-v1): disable migrate v1 notification

---

packages/fx-core/src/plugins/solution/fx-solution/debug/provisionLocal.ts

Add telemetry to track whether there are v1 F5 users

chore(localdebug): add v1 property in local debug telemetry

---

packages/fx-core/src/plugins/resource/sql/index.ts
packages/fx-core/src/plugins/resource/sql/managementClient.ts
packages/fx-core/tests/plugins/resource/sql/unit/index.test.ts

chore(sql): update axios error

---

packages/fx-core/src/plugins/resource/appstudio/constants.ts
packages/fx-core/src/plugins/resource/appstudio/manifestTemplate.ts

1. do not provide webapplicationinfo in manifest template
2.

refactor: do not provide webapplicationinfo in init manifest template

---

docs/fx-core/sql-help.md

update for supporting multiple databases

chore(sql): update help doc

---

packages/fx-core/src/plugins/solution/fx-solution/debug/provisionLocal.ts
packages/fx-core/tests/plugins/solution/debug/solution.debug.provisionLocal.test.ts

https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/13026923/
In case the input localsettings has missing field. Test added as well.

fix(localdebug): potential missing local settings

---

packages/fx-core/src/plugins/resource/bot/aadRegistration.ts

add retry logic for aad/secret creation.
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/13023199

chore: add retry logic for secret creation

---

packages/sdk/tsconfig.json

fix: https://github.com/OfficeDev/TeamsFx/issues/3668
@tecton will help enhance checklist when release sdk:
1. [TBD] Update changelog using lerna
2. [TBD] Update sample app to use latest sdk version
3. [Done] Update new project template to use latest sdk version
Manual test can cover this issue once #2 is done.

fix(sdk): sdk target es6

---

packages/vscode-extension/src/controls/ISamples.ts
packages/vscode-extension/src/controls/SampleGallery.scss
packages/vscode-extension/src/controls/SampleGallery.tsx
packages/vscode-extension/src/controls/sampleDetailPage.scss
packages/vscode-extension/src/controls/sampleDetailPage.tsx

UX design:
https://www.figma.com/file/qqVegbnWWBsqHhR8Qijs4O/Teams-Toolkit---GA?node-id=1035%3A112132

feat: add sample detail page

---

packages/server/package-lock.json
packages/server/src/index.ts
packages/server/src/utils.ts

https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/13051019

fix: server gotten errors' type

---

packages/fx-core/src/plugins/resource/appstudio/manifestTemplate.ts
packages/fx-core/src/plugins/resource/appstudio/utils/telemetry.ts
packages/fx-core/src/plugins/resource/appstudio/v3/index.ts

1. add v3 telemetries
2. fix app name

fix: add v3 telemetries

---

packages/fx-core/resource/strings.json

e2e test failed due to missing a space

fix(collaboration): fix e2e test failed

---

packages/cli/src/helpParamGenerator.ts
packages/cli/tests/e2e/command/helpInfo.tests.ts
packages/fx-core/src/plugins/resource/apim/managers/questionManager.ts

https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/13051144
E2E TEST: ["helpInfo.tests.ts", "TabAddApim.tests.ts"]

fix: cli resource add azure-apim wrong parameters

---

packages/fx-core/src/common/localSettingsConstants.ts
packages/fx-core/src/common/localSettingsProvider.ts
packages/fx-core/src/core/middleware/localSettingsLoader.ts
packages/fx-core/src/plugins/resource/simpleauth/plugin.ts
packages/fx-core/tests/core/localSettings.test.ts
packages/fx-core/tests/core/middleware/LocalSettingsLoaderMW.test.ts
packages/fx-core/tests/plugins/resource/simpleauth/unit/index.test.ts

related bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/13051456

fix(local debug): remove simple auth related local settings when simple auth plugin is not activated

---

packages/cli/src/cmds/deploy.ts
packages/fx-core/src/plugins/resource/apim/managers/questionManager.ts

Detail:
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/13051602

fix(apim): generate deploy question according to ctx

---

packages/server/.vscode/launch.json
packages/server/src/providers/telemetry.ts
packages/server/src/serverConnection.ts

chore: support correlation-id
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/12924674

chore: support correlation-id

---

packages/vscode-extension/src/debug/npmInstallHandler.ts
packages/vscode-extension/src/handlers.ts
packages/vscode-extension/test/unit/localdebug/npmInstallHandler.test.ts

- update adding resource/capability handler to support automatic npm install
- update automatic npm install handler to support adding resource/capability
- add unit test for automatic npm install
Related: #3735

feat: run npm install automatically after adding resource/capability in vsc

---

packages/fx-core/src/core/middleware/envInfoLoader.ts

Adds detailed telemetry to facilitate investigation into bug https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/13023140

chore: telemetry enhancement

---

packages/vscode-extension/package.json
packages/vscode-extension/src/constants.ts
packages/vscode-extension/src/debug/depsChecker/vscodeHelper.ts

chore(vsc): group validation configuration together

---

packages/vscode-extension/src/debug/npmInstallHandler.ts
packages/vscode-extension/src/telemetry/extTelemetryEvents.ts

@chagong Please help review the new telemetry events and properties.

chore: add telemetry for automatic npm install

---

packages/vscode-extension/src/controls/ISamples.ts
packages/vscode-extension/src/controls/SampleGallery.scss
packages/vscode-extension/src/controls/SampleGallery.tsx
packages/vscode-extension/src/controls/sampleDetailPage.tsx

UX design: https://www.figma.com/file/qqVegbnWWBsqHhR8Qijs4O/Teams-Toolkit---GA?node-id=1035%3A112132

chore: add handlers for sample detail page

---

packages/cli/src/cmds/preview/preview.ts

Fix https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/13086195/.

fix: fix backend deps in cli local preview

---

packages/cli/src/cmds/config.ts
packages/cli/src/cmds/new.ts
packages/cli/src/cmds/preview/constants.ts
packages/cli/src/cmds/preview/errors.ts
packages/cli/src/cmds/preview/npmInstallHandler.ts
packages/cli/src/telemetry/cliTelemetryEvents.ts
packages/cli/src/userSetttings.ts
packages/cli/tests/unit/cmds/preview/npmInstallHandler.test.ts

- add automatic npm install handler
- add telemetry event and property for automatic npm install
- update new command to support automatic npm install

feat: run npm install automatically after scaffolding in cli

---

lerna.json
packages/adaptivecards-tools-sdk/package.json

https://dev.azure.com/msazure/Microsoft%20Teams%20Extensibility/_workitems/edit/13049925
The initial tag was created https://github.com/OfficeDev/TeamsFx/releases/tag/%40microsoft%2Fadaptivecards-tools

chore: add to lerna, fix json format

---

packages/vscode-extension/src/commonlib/telemetry.ts
packages/vscode-extension/src/extension.ts
packages/vscode-extension/src/handlers.ts
packages/vscode-extension/src/telemetry/extTelemetry.ts
packages/vscode-extension/test/unit/extension/handlers.test.ts

fix: create project telemetry data loss

---

packages/cli/src/cmds/capability.ts
packages/cli/src/cmds/resource.ts
packages/cli/tests/unit/cmds/capability.tests.ts
packages/cli/tests/unit/cmds/resource.tests.ts

- update adding resource/capability command to support automatic npm install

feat: run npm install automatically after adding resource/cap in cli

---

packages/fx-core/src/plugins/solution/fx-solution/arm.ts
packages/fx-core/tests/constants.ts
packages/fx-core/tests/plugins/solution/helper.ts
packages/fx-core/tests/plugins/solution/solution.arm.test.ts

E2E test: https://github.com/OfficeDev/TeamsFx/actions/runs/1759533259
fix issue: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/13118546

fix: bicep config file update

---

packages/vscode-extension/src/controls/sampleDetailPage.scss
packages/vscode-extension/src/controls/sampleDetailPage.tsx

See the gif at https://microsoftapc.sharepoint.com/:i:/t/Testteam929/EcRDbSh5eVRMnSfJH6KDXFEBO4TTwrKxjOmC_f-dOu2-eQ?e=7OniBa
UX design: 
https://www.figma.com/file/qqVegbnWWBsqHhR8Qijs4O/Teams-Toolkit---GA?node-id=1654%3A222626

feat: responsive sample detail page layout
