packages/fx-core/src/plugins/resource/appstudio/plugin.ts

When the user submit the app, and the admin approved it. The lastModifiedTime of this record will be null. We will hide LastModifiedTime in this case.

fix: do not show LastModifiedTime if it's undefined

---

packages/fx-core/src/plugins/resource/function/utils/depsChecker/common.ts
packages/vscode-extension/src/debug/depsChecker/azureNodeChecker.ts
packages/vscode-extension/src/debug/depsChecker/common.ts
packages/vscode-extension/src/debug/depsChecker/nodeChecker.ts
packages/vscode-extension/src/debug/depsChecker/spfxNodeChecker.ts

1. Add telemetry event for node checker in common.ts. 
2. Sync the common.ts in function plugin.
3. Send telemetry if node can't be found or node not supported.

feat(env-checker): add telemetry for node checker

---

packages/fx-core/src/plugins/resource/localdebug/util/telemetry.ts

According to the latest telemetry doc, add `appid` to property. For local debug, use local app id as value.

fix: add appid to localdebug telemetry

---

packages/fx-core/src/plugins/resource/function/plugin.ts

- Also handle the DepsChecker error for BackendExtensionInstaller in function plugin to correctly pop-up dialog
If the user only has .NET SDK 2.1 and a global.json, an error will popup like this
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/9902032/

fix(env-checker): add error popup for backend extension install

---

packages/fx-core/src/plugins/resource/localdebug/util/telemetry.ts

Remove plugin name from event prefix

fix: correct local debug event name

---

.azure-pipelines/CredScanSuppressions.json

To eliminate some false alarms for the credential scan task, we can add a suppression file to whitelist some test files or terms for security. See https://strikecommunity.azurewebsites.net/articles/4127/local-suppression-usage-examples.html for how to configure rules in a suppression file.

chore(credscan): add suppression file for credential scan task

---

packages/vscode-extension/src/controls/webviewPanel.ts

The wording 'whitelist' breaks diversity rule. Change the string.

feat: update comment to avoid from diversity break

---

packages/fx-core/src/plugins/resource/function/utils/depsChecker/dotnetChecker.ts
packages/vscode-extension/src/debug/depsChecker/dotnetChecker.ts

1. fix `options` is an object without being serialized in error message.
2. fix `command` has been changed after running `command.splice(1)`

fix(env-checker): fix the error message

---

packages/fx-core/src/plugins/resource/function/utils/depsChecker/dotnetChecker.ts
packages/vscode-extension/src/debug/depsChecker/dotnetChecker.ts

- When using relative PATH in execFile, it will throw ENOENT on macOS 11.2.3. Changed to absolute path to workaround this issue
Run local debug without .NET SDK
Linux is not affected because we won't install .NET SDK on Linux

fix(env-checker): fix ENOENT error when run dotnet-install script with execFile

---

packages/fx-core/src/plugins/resource/frontend/constants.ts
packages/fx-core/src/plugins/resource/frontend/index.ts
packages/fx-core/src/plugins/resource/frontend/ops/scaffold.ts
packages/fx-core/src/plugins/resource/frontend/utils/telemetry-helper.ts

1. start event doesn't need `success` property
2. error event need contains `error-code`, `error-message` and `error-type`
3. Plugin must send telemetry for api: [pre,post] [scaffold, provision, deploy], get question and local debug don't need to send telemetry. We can offline discuss if our plugin need more telemetry for our own business.

feat(frontend): refine sending telemetry

---

packages/simpleauth/src/TeamsFxSimpleAuth/runtimeconfig.template.json

Set rollForward to `Major` which roll forward to lowest higher major version, and lowest minor version, if requested major version is missing.

fix: simple auth cannot run with .net 5 only

---

packages/cli/resource/newParam.json
packages/cli/src/constants.ts
packages/fx-core/src/core/error.ts
packages/fx-core/src/core/index.ts
packages/fx-core/src/core/question.ts
packages/vscode-extension/src/controls/webviewPanel.ts

1. rename "To Do List2" to "Todo List with SPFx"
2. add progress bar for sample clone in webview trigger.
3. add confirm button for sample clone in command palate & tree view trigger. 
(Note: here the confirm comes after all the answers collected , different in webview(confirm first, then select folder).
Bug opened:https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/9912386)
related task:
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/9902864
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/9888172

fix: add confirm & progress bar for sample clone

---

packages/vscode-extension/src/qm/vsc_ui.ts

bug reason: in WSL envirenment, QuickPick.ignoreFocusOut does not take effect.
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/9902557

fix: failed to scaffold in windows10+WSL(ubuntu)

---

packages/fx-core/src/plugins/resource/bot/utils/templateManifest.ts

Use common templates config/lib from fx-core.
Sorry for: Didn't realize the code is from fx-core which is a common place.

chore(bot): use template lib in fxcore

---

packages/vscode-extension/src/debug/depsChecker/checker.ts
packages/vscode-extension/src/debug/depsChecker/common.ts
packages/vscode-extension/src/debug/depsChecker/nodeChecker.ts

Notify user to restart VS Code after the required dependencies installed.
snapshot:

fix(env-checker): update notification message

---

packages/vscode-extension/src/commonlib/azureLogin.ts

For personal account, the accountInfo is different.

fix: get email from personal account

---

packages/fx-core/src/plugins/resource/appstudio/appStudio.ts

Check if the app is successfully published to app catalog. If so, ignore the badgateway error.

[WIP] fix: avoid BadGateway error

---

packages/fx-core/src/plugins/resource/bot/enums/pluginActRoles.ts

1. bot plugin get capabilities selected from solution's config in context.
2. solution change capability value from MessageExtension to MessagingExtension.
3. bot plugin checks if users selected me by value MessageExtension, so cause the bug.
Better way is to provide a common enum for these capability values in fx-core, but not existing for now.
to fix bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/9924015

fix(bot): align me capability value

---

packages/fx-core/src/plugins/resource/localdebug/launch.ts
packages/vscode-extension/src/debug/commonUtils.ts
packages/vscode-extension/src/debug/teamsfxDebugProvider.ts

Use `https://teams.microsoft.com/l/app/${teamsAppId}?installAppPackage=true&appTenantId=${tenantId}&login_hint=${userAccount}` as launch url to navigate user to login the correct account.
This could fix the app not found issue for local and remote debug, but:
- `login_hint` cannot be empty. So, when remote debug and no signed user, use "login_your_m365_account" as login hint - at least user has the chance to login another account.
- This will always show a Teams app selection page as following:

Fix: fix app-not-found by adding account hint

---

packages/vscode-extension/src/handlers.ts

move detecting ports later after core.localDebug and before frontend/backend/bot start, to avoid that the ports opened during last debugging have not been closed.

fix(local-debug): move detecting ports later

---

packages/api/src/constants.ts
packages/vscode-extension/src/handlers.ts

If user is running the Teams Toolkit in VS Code Remote environment (WSL/SSH/Container), the `VscEnv` will be detected as "remote", rather than "CodeSpace".

fix: detect vscode for remote environment

---

packages/vscode-extension/src/resources/Strings.json

Remove the specific guidance and make it more general "wait for task to complete." This fixes https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/9921867

Task running error update

---

packages/cli/resource/newParam.json
packages/cli/src/cmds/new.ts
packages/cli/src/constants.ts
packages/cli/src/error.ts
packages/fx-core/src/core/error.ts
packages/fx-core/src/core/index.ts
packages/fx-core/src/core/question.ts
packages/vscode-extension/src/controls/webviewPanel.ts

1. Rewording 'clone' to 'download'
2. Remove FAQ Plus sample app since it's not ready
3. update scaffold from sample app description according to PM spec

docs: update sample app strings

---

packages/fx-core/src/core/index.ts
packages/vscode-extension/src/controls/webviewPanel.ts

ADO: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/9921766
Screenshot:

fix: download sample app to same folder will overwrite

---

packages/vscode-extension/src/debug/depsChecker/vscodeAdapter.ts

If `Learn more` button clicked in the pop-up notification window, the link will be opened automatically and the notification window will be **kept there**.
work item: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/9943712/

fix(env-checker): update the behavior when learn more link clicked

---

packages/vscode-extension/src/handlers.ts

related bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/9950606/

fix: no help/issue link

---

docs/fx-core/localdebug-help.md

Teams capacity -> Teams capability

fix(local-debug): fix help doc typo

---

packages/cli/package-lock.json
packages/cli/src/cmds/new.ts
packages/cli/src/error.ts
packages/fx-core/src/core/index.ts

related bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/9942418/

fix: throw error when download samples to the folder twice

---

packages/fx-core/src/plugins/resource/function/plugin.ts
packages/fx-core/src/plugins/resource/function/utils/depsChecker/common.ts
packages/fx-core/src/plugins/resource/function/utils/depsChecker/funcPluginAdapter.ts
packages/vscode-extension/src/debug/depsChecker/common.ts

- Also tell the user the missing dependencies in the finall error message
** Note that a browser will automatically pop up to open the help link.
A popup dialog will show up and we also output the error message to output channel
The URL is not automatically opened in browser compared to Linux and Windows. But the user can copy and paste the link to a browser to open the URL manually.
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/9950544?src=WorkItemMention&src-action=artifact_link

fix(env-checker): fix dotnet-not-installed error message for Linux in function plugin

---

docs/vscode-extension/envchecker-help.md
packages/fx-core/src/plugins/resource/function/utils/depsChecker/funcPluginAdapter.ts

work item: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/9922768
Here's the help link with bookmark: 
https://aka.ms/teamsfx-envchecker-help#functionDepsCheckerdotnetnotfound 
=> 
Preview the doc in the personal branch: https://github.com/OfficeDev/TeamsFx/blob/qinezh/fix-1/docs/vscode-extension/envchecker-help.md#functionDepsCheckerdotnetnotfound
The pattern to generate bookmark in function plugin would be: `functionDepsChecker` + `${original_bookmark}`

fix(env-checker): correct the bookmark within help link

---

packages/fx-core/src/core/question.ts
packages/vscode-extension/src/controls/SampleGallery.tsx

fix: remove faq plus sample app in extension sample gallery page

---

packages/fx-core/src/plugins/resource/function/utils/depsChecker/common.ts
packages/fx-core/src/plugins/resource/function/utils/depsChecker/funcPluginAdapter.ts
packages/vscode-extension/src/debug/depsChecker/common.ts

**work item**: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/9951344/
**Summary**: Update the text of `Continue` button with `Continue anyway`.
Here's the snapshot:
teamsfx-cli (WSL): deploy function app when .NET SDK is not installed:
Teams Toolkit (WSL): local debug when .NET SDK is not installed:

fix(env-checker): update to 'Continue anyway' to reduce confusion

---

packages/fx-core/src/plugins/resource/localdebug/index.ts

use solution setting rather than plugin config to get active plugins.

fix(local-debug): use solution setting to get active plugins

---

packages/vscode-extension/src/debug/commonUtils.ts
packages/vscode-extension/src/debug/teamsfxTaskHandler.ts
packages/vscode-extension/src/handlers.ts
packages/vscode-extension/src/telemetry/extTelemetryEvents.ts

Add teams app id as `debug-appid` to local debug related telemetries:
- `debug-precheck` event records local teams app id if exist.
- `debug-start` event records local teams app id for local debug, and remote teams app id for remote launch.

fix: add app id to local debug telemetry

---

packages/fx-core/src/plugins/resource/bot/appStudio/appStudio.ts
packages/fx-core/src/plugins/resource/bot/azureOps.ts
packages/fx-core/src/plugins/resource/bot/constants.ts
packages/fx-core/src/plugins/resource/bot/errors.ts
packages/fx-core/src/plugins/resource/bot/languageStrategy.ts
packages/fx-core/src/plugins/resource/bot/plugin.ts
packages/fx-core/src/plugins/resource/bot/resources/messages.ts
packages/fx-core/tests/plugins/resource/bot/unit/errors.test.ts

1. add specific error message for bot name conflicts, and, remind users to clear resources in previous azure account.
2. align user error principle: If users can possibly recover by themselves, then it should be a user error.
3. refine wording for some errors.
4. remove CommandExecutionError message from low-level Error object, instead, using the message made by bot plugin, to avoid long low-level Error.message.
5. Log message endpoint to be updated manually.
to fix bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/9959194
Explanations for the screenshot below:
Since solution and plugins both need to throw error, to reduce duplicated error. Solution will throw an overall error if help link is not set. Plugins will throw a specific error if help link …

fix(bot): bot name conflicts

---

packages/fx-core/src/plugins/resource/appstudio/constants.ts
packages/fx-core/templates/plugins/solution/README.md
packages/vscode-extension/README.md
packages/vscode-extension/src/controls/WelcomePanel.tsx
packages/vscode-extension/src/handlers.ts

ADO: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/9978426

fix: update aka link

---

packages/fx-core/src/plugins/resource/localdebug/launch.ts

Add `&webjoin=true` to launch url to **skip** the selector page:

hotfix: skip join view when local debug

---

packages/fx-core/src/core/index.ts

Issue:
Subscription name not updated to sidebar after login with one sub
Reproducible steps:
1. login using account A
2. select subscription Sa under account A
3. sign out
4. sign in using another account B(which has only one subscription under this account)
5. subscription is auto selected but sidebar not updated
ADO:
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/9997487

fix: update subscription after sub auto selected

---

packages/vscode-extension/src/controls/QuickStart.tsx

Screenshot:
before:
after:
ADO:
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/9881529

fix: update wording 'teamsfx' to 'teams' on quick start page

---

packages/fx-core/templates/plugins/resource/apim/README.md

CLI will be removed in swagger-jsdoc. [Detail](https://github.com/Surnet/swagger-jsdoc/issues/261)
[swagger-jsdoc-generator](https://github.com/lmammino/swagger-jsdoc-generator) is outdated.
Bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/9986060

fix(apim): change swagger-jsdoc part in README file

---

packages/vscode-extension/src/controls/SampleGallery.scss

https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/9922655/?fullScreen=false&triage=true
In this bug, 
For #1, fix in this pr
For #2, already fixed
For #3, I don't think this is needed and not sure how to implement, confirmed with UX, not needed so far.

fix: update margin on sample gallery page according to UX

---

packages/fx-core/src/plugins/resource/frontend/configs.ts
packages/fx-core/src/plugins/resource/frontend/constants.ts
packages/fx-core/src/plugins/resource/frontend/index.ts
packages/fx-core/src/plugins/resource/frontend/ops/scaffold.ts
packages/fx-core/src/plugins/resource/frontend/plugin.ts
packages/fx-core/src/plugins/resource/frontend/resources/messages.ts
packages/fx-core/src/plugins/resource/frontend/resources/templateInfo.ts
packages/fx-core/tests/plugins/resource/frontend/helper.ts
packages/fx-core/tests/plugins/resource/frontend/unit/config.test.ts
packages/fx-core/tests/plugins/resource/frontend/unit/index.test.ts
packages/fx-core/tests/plugins/resource/frontend/unit/scaffold.test.ts

1. Make frontend plugin stateless.
2. Remove useless codes and comments.
3. Sync config to context, make it easier to add new persistent configs.

refactor(frontend): make frontend plugin stateless

---

packages/fx-core/src/plugins/resource/bot/index.ts

Didn't save config when exceptions will cause inconsistent behaviors.
to fix bug: https://dev.azure.com/msazure/Microsoft%20Teams%20Extensibility/_workitems/edit/9986090

fix(bot): save config when exceptions occur

---

.github/workflows/env-checker-ci-pr.yml
.github/workflows/env-checker-ci-schedule.yml
packages/vscode-extension/.vscode/launch.json
packages/vscode-extension/package.json
packages/vscode-extension/test/runEnvCheckerTest.ts
packages/vscode-extension/test/suite/envChecker/index.ts

https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/9769204/
Some bugs are not reproducible with standalone mocha tests. Use vscode-test to run the env-checker test cases in vscode context. This is more realistic to the actual user environment than launching the tests with mocha.
- add test script and test runner script for vscode-test
- add an entry in the extension's `launch.json` to support debugging the test cases
- modify GitHub action config to support vscode-test
- add macOS 11 as an test environment in schedule test
** tradeoff: using vscode-test will slightly decrease the performance. (e.g. Windows test 4min -> 5min)
- Schedule test passed: https://github.com/OfficeDev/TeamsFx/actions/runs/873636003
- Revert the commit that fixes the "ENOENT" bug …

test(env-checker): use vscode-test to run env-checker test cases

---

packages/vscode-extension/src/debug/teamsfxTaskHandler.ts

To fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/9999085/.
For linux/wsl, if the default shell is not bash, the root process of shell execution tasks will be the shell process. However, kill the tasks via SIGINT will not terminate the shell process, causing the tasks not terminated when stop debugging.

fix(local-debug): kill tasks via SIGTERM rather than SIGINT

---

packages/fx-core/src/core/index.ts

Issue:
Sign out from Azure extension command palette, the sidebar is not updated
ADO:
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/9881584
Screenshot:
before:
after:

fix: sidebar not updated when sign out from Azure extension

---

packages/fx-core/src/plugins/resource/function/enums.ts
packages/fx-core/src/plugins/resource/function/ops/provision.ts
packages/fx-core/src/plugins/resource/function/plugin.ts
packages/fx-core/src/plugins/resource/function/resources/steps.ts
packages/fx-core/src/plugins/resource/function/utils/azure-client.ts

An issue is that function app's settings will be updated at provision and post-provision.
So there is an intermediate stage during the provision. If user stop the process in the stage at second run, the env will break.
To avoid, in this PR, we don't update in the provision stage at second run.
We pass the setting to post stage, and update the app settings only in post provision.

fix(function): avoid to configure function app twice in second run

---

packages/vscode-extension/src/controls/QuickStart.tsx

Update status when user click `Play` in the video, or click `Watch in the browser`.

fix: update status when play video

---

packages/api/src/utils/login.ts
packages/api/tests/login.test.ts
packages/cli/src/commonlib/azureLogin.ts
packages/cli/src/commonlib/azureLoginCI.ts
packages/cli/src/commonlib/azureLoginUserPassword.ts
packages/fx-core/src/core/index.ts
packages/fx-core/tests/plugins/resource/apim/testUtil.ts
packages/fx-core/tests/plugins/resource/bot/unit/utils.ts
packages/fx-core/tests/plugins/resource/frontend/helper.ts
packages/fx-core/tests/plugins/resource/function/unit/deploy.test.ts
packages/fx-core/tests/plugins/resource/function/unit/provision.test.ts
packages/vscode-extension/src/commonlib/azureLogin.ts
packages/vscode-extension/src/controls/webviewPanel.ts
packages/vscode-extension/test/suite/integration/extension.noFolder.test.ts

1. Remove Azure login provider sync methods

feat: remove login sync

---

packages/vscode-extension/src/debug/teamsfxTaskHandler.ts

Improve the timing to switch active terminal for npm-install tasks:
* when the task in **active** terminal is ended **successfully**, switch terminal to show the hidden running task.
* when the task in **hidden** terminal **failed** to execute, switch terminal to show the hidden failure task.
----
Assumed there're two npm-install tasks running in parallel:
1. frontend npm install (active terminal)
2. backend npm install (hidden terminal)
**scenario 1**: task-1 completed successfully, task-2 is still running.
**behavior**: the terminal for task-2 will be displayed.
**scenario 2**: task-1 is still running, task-2 is failed to executed.
**behavior**: the terminal for task-2 will be displayed.
**scenario 3**: task-1 is failed to executed, task-2 is still running.
**behavior**: nothing …

feat(local-debug): improve the timing to switch active terminal

---

packages/vscode-extension/test/suite/envChecker/cases/all.ts
packages/vscode-extension/test/suite/envChecker/cases/backendExtensionsInstaller.ts
packages/vscode-extension/test/suite/envChecker/utils/backendExtensionsInstaller.ts
packages/vscode-extension/test/suite/envChecker/utils/node.ts

Add standalone test cases for backend extension installer.
Add 2 test cases:
- Run BackendExtensionInstaller when .NET SDK is installed
- Run BackendExtensionInstaller when the user has some broken nuget source in the global .NET SDK.
---
ADO task: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/9769204/

test(env-checker): add backend extension install nuget test cases

---

templates/bot-msgext/js/default/index.js
templates/bot-msgext/ts/default/index.ts
templates/bot/js/default/index.js
templates/bot/ts/default/index.ts

to fix bug: https://dev.azure.com/msazure/Microsoft%20Teams%20Extensibility/_workitems/edit/9902831

chore(bot): constrain HTTP Get for public folder

---

packages/vscode-extension/test/suite/envChecker/utils/dotnet.ts

As you can see in this PR GitHub Action error report: https://github.com/OfficeDev/TeamsFx/runs/2691126542?check_suite_focus=true
This error output is kind of confusing. The actual reason is the change in this PR breaks the install logic on Linux/macOS. But from the error message, it is hard to determine the actual reason. 
```
2) DotnetChecker E2E Test - second run
Invalid dotnet.json file and .NET SDK installed:
Error: ENOENT: no such file or directory, lstat '/this'
at Object.realpathSync (fs.js:1728:7)
at Object.realpathSync (electron/js2c/asar_bundle.js:5:4607)
at Object.assertPathEqual (out/test/suite/envChecker/utils/common.js:37:26)
at Context.<anonymous> (out/test/suite/envChecker/cases/dotnet.js:282:26)
at Generator.next (<anonymous>)
at fulfilled …
```

test(env-checker): add validation after installing .NET SDK for testing

---

packages/vscode-extension/test/suite/envChecker/cases/dotnet.ts
packages/vscode-extension/test/suite/envChecker/utils/dotnet.ts

There is a bug causing a env-checker test case to fail when .NET SDK is installed on macOS or Windows. The PR triggered CI won't fail because this case is not covered in the PR triggered test. The schedule CI failed because of this bug.
This PR fixes:
- The skip condition is wrong. This description of this test case states that it is for cases where .NET SDK is installed.
[The failed schedule CI](https://github.com/OfficeDev/TeamsFx/actions/runs/894663114)
[The manually triggered successful CI after this fix](https://github.com/OfficeDev/TeamsFx/actions/runs/894846410)

test(env-checker): fix skip condition for existing .NET SDK test case

---

packages/vscode-extension/src/debug/depsChecker/vscodeTelemetry.ts
packages/vscode-extension/src/telemetry/extTelemetryEvents.ts

- Add os.arch and os.release to telemetry properties.
- To detect some platforms:
- os.arch == "arm64" for M1 macOS.
- os.release contains "WSL" from Windows Subsystem for Linux. [From an official source](https://github.com/microsoft/WSL/issues/423#issuecomment-221627364). Example: `5.4.72-microsoft-standard-WSL2`
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_queries/query/2ef235af-bf64-4e1e-a595-f548ae6371d8/

chore(env-checker): add os-info to env-checker telemetry in extension

---

packages/fx-core/src/plugins/resource/localdebug/index.ts

set `skipNgrok` and `trustDevCert` to default value if they are undefined on `localDebug` and `postLocalDebug`.
To fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/9941264

fix(local-debug): set skipNgrok, trustDevCert to default value if undefined

---

README.md

Correct the aka short link to point to the right documentation page: #1271

docs(README): correct the documentation link in README.md

---

packages/fx-core/src/plugins/resource/function/constants.ts
packages/fx-core/src/plugins/resource/function/ops/provision.ts

1. Normalize suffix when generating resource name. it is not a bug in current stage because suffix and resource name are generated in same lifecycle, user has no chance to inject. In case it becomes a bug someday, let's refine it.
2. Unify the max length of function app name and storage name because there is no benefit to separate them. Unification makes it simpler.

refactor(function): normalize suffix when generate service name

---

packages/fx-core/src/core/index.ts

The bug is due to the change from sync call to async call, since sync call is removed and setStatusMap will auto fire, so there's no need to get initial status manually.
ADO: 10068005

fix: start vsc will be asked to login Azure

---

templates/tab/js/default/src/components/sample/Welcome.jsx
templates/tab/js/default/src/components/sample/lib/useGraph.js
templates/tab/ts/default/src/components/sample/Welcome.tsx
templates/tab/ts/default/src/components/sample/lib/useGraph.ts

Duplicated log messages were shown in console since we new credentials for each react render.

fix(tab): prevent creating credentials for each render

---

packages/fx-core/src/plugins/resource/function/ops/deploy.ts
packages/fx-core/src/plugins/resource/function/plugin.ts
packages/fx-core/src/plugins/resource/function/utils/depsChecker/common.ts
packages/fx-core/src/plugins/resource/function/utils/depsChecker/funcPluginAdapter.ts
packages/vscode-extension/src/debug/depsChecker/common.ts
packages/vscode-extension/src/debug/depsChecker/dotnetChecker.ts
packages/vscode-extension/src/debug/depsChecker/vscodeAdapter.ts

- Add telemetry events for clicking "Learn More", "Continue" and "Cancel" buttons. One event for each button.
- Also add in function plugin
- Add error event for searchDotnetSdks()
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/10036370/

feat(env-checker): add telemetry event for learn more/continue/cancel buttons

---

packages/cli/src/cmds/build.ts
packages/cli/src/cmds/capability.ts
packages/cli/src/cmds/deploy.ts
packages/cli/src/cmds/init.ts
packages/cli/src/cmds/new.ts
packages/cli/src/cmds/provision.ts
packages/cli/src/cmds/publish.ts
packages/cli/src/cmds/resource.ts
packages/cli/src/cmds/validate.ts
packages/cli/src/helpParamGenerator.ts
packages/cli/src/index.ts
packages/cli/src/userInteraction.ts
packages/cli/src/utils.ts
packages/fx-core/src/common/tools.ts
packages/fx-core/src/plugins/resource/apim/factory.ts
packages/fx-core/src/plugins/resource/appstudio/index.ts
packages/fx-core/src/plugins/resource/sql/plugin.ts
packages/fx-core/src/plugins/resource/sql/questions.ts
packages/fx-core/src/plugins/solution/fx-solution/solution.ts

1. Initialize core and get questions for help param of all the stage at the begining.
2. Switch all the cmd(except init) builder to use params from core.
3. Reorganize all the runCommand() to be consistent.
4. Fix updatePresetAnswers(): use questions/params to set the answer instead of the yargs args.
Plugin Change:
1. Add APIM getQuestions() for CLI_HELP platform @XiaofuHuang 
2. Add SQL getQuestions() for CLI_HELP platform @xzf0587 
3. Change publish getQuestions().(remove build-or-publish for CLI platform) @nliu-ms 
Core Change:
1. Add subscription question node in provision stage. @jayzhang  @LongOddCode  @1yefuwang1

feat: Use core getQuestions to get CLI help param

---

packages/fx-core/src/plugins/resource/apim/index.ts
packages/fx-core/src/plugins/resource/apim/utils/namingRules.ts

The user often change the app name in manifest.json, so use the app name in settings.json

fix(apim): change the appName used in apim plugin

---

packages/cli/package-lock.json

upgrade `renderkid` to 2.0.6
upgrade `css-select` to 4.1.3
upgrade `css-what` to 5.0.1

chore: update package-lock file to avoid css-what high severity

---

packages/fx-core/src/plugins/solution/fx-solution/commonQuestions.ts

fixes https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_sprints/taskboard/Teams%20Extensibility%20E2E%20Team/Microsoft%20Teams%20Extensibility/CY21-6.1?workitem=10107295

fix(solution): wording when no sub was found

---

packages/api/src/utils/log.ts
packages/api/tests/log.test.ts
packages/cli/package-lock.json
packages/cli/package.json
packages/cli/src/commonlib/azureLogin.ts
packages/cli/src/commonlib/codeFlowLogin.ts
packages/cli/src/commonlib/codeFlowTenantLogin.ts
packages/cli/src/commonlib/log.ts
packages/cli/src/utils.ts
packages/fx-core/src/plugins/resource/appstudio/index.ts
packages/fx-core/tests/plugins/resource/aad/helper.ts
packages/fx-core/tests/plugins/resource/bot/unit/utils.ts
packages/fx-core/tests/plugins/resource/frontend/helper.ts
packages/vscode-extension/src/commonlib/log.ts

1) Support color for LogProvider.info, others like error/warning will have default color.
2) Replace colors with chalk package.
E.g. CLI:
VSCode output channel (default color):

feat: support ansi color for logprovider info

---

packages/fx-core/src/plugins/resource/function/index.ts
packages/fx-core/src/plugins/resource/function/ops/deploy.ts
packages/fx-core/src/plugins/resource/function/plugin.ts
packages/fx-core/src/plugins/resource/function/utils/depsChecker/funcPluginTelemetry.ts
packages/fx-core/src/plugins/resource/function/utils/telemetry-helper.ts

1. rename `telemetryHelper` to `TelemetryHelper`
2. make ctx static to avoid broadcast

refactor(function): rename telemetryHelper and make ctx static

---

packages/vscode-extension/src/commonlib/azureLogin.ts

1. Fix Azure notify status when first open Vs Code and not signed in.  (This is because Azure Account will be ready after toolkit extension starts.)
Bug: When open new VsCode and do not sign in Azure after treeView move from core to extension.
https://dev.azure.com/msazure/Microsoft%20Teams%20Extensibility/_workitems/edit/10192921/

fix: azure initialize status

---

packages/fx-core/src/plugins/solution/fx-solution/solution.ts

Update error message for `validate manifest` and `build teams package` without provision.

fix: update error message for validate/build

---

packages/fx-core/src/plugins/resource/frontend/plugin.ts
packages/fx-core/src/plugins/resource/frontend/resources/errors.ts

There are many CreateStorageAccountError in telemetry but we don't know why. Add Azure error code to error message and the error message will be added to telemetry, which may help us know what's happening.

feat(frontend): Add Azure error code to error message and send for telemetry

---

packages/vscode-extension/src/controls/openWelcomePage.ts

ADO: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_sprints/taskboard/Teams%20Extensibility%20E2E%20Team/Microsoft%20Teams%20Extensibility/cy21-6.2?workitem=10209884

fix(vsc): auto show teamsfx treeview at first time

---

packages/fx-core/src/plugins/resource/frontend/constants.ts
packages/fx-core/src/plugins/resource/frontend/error-factory.ts
packages/fx-core/src/plugins/resource/frontend/index.ts
packages/fx-core/src/plugins/resource/frontend/resources/errors.ts

Found some EnableStaticWebsiteError and StaticWebsiteDisableError for frontend plugin, add a help document to tell user how to deal with these.

feat(frontend): Add help link for some user errors

---

packages/cli/src/index.ts

related task: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/9823359

fix(cli): disable default show help when user input error cmd

---

packages/fx-core/src/plugins/resource/sql/index.ts
packages/fx-core/src/plugins/resource/sql/plugin.ts
packages/fx-core/src/plugins/resource/sql/questions.ts
packages/fx-core/tests/plugins/resource/sql/unit/skipAddingUser.test.ts

1. remove sql skip-adding-user question.
2. set default skip-adding-user value based on azureAccountProvider?.getIdentityCredentialAsync

fix(sql): remove sql skip-adding-user question

---

packages/fx-core/templates/plugins/resource/spfx/solution/manifest.json

related task: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/10241958
"Add to a chat" has been removed.

fix(spfx): disable spfx chat tab

---

packages/cli/src/utils.ts
packages/cli/tests/e2e/smoke/AzureAppHappyPath.tests.ts
packages/cli/tests/e2e/sql/Provision react app with Azure Function and SQL.tests.ts

https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/10242391
Before fixed:
After fixed:
And don't use bool:
Run E2E test workflow successfully:

fix: apim parameter is not string

---

packages/cli/src/cmds/preview/commonUtils.ts
packages/cli/src/cmds/preview/preview.ts

merge process.env when starting services, otherwise there will be an error on macos: `env: node: No such file or directory` or `/bin/sh: dotnet: command not found`

fix(cli-preview): merge process.env when starting services

---

packages/cli/package-lock.json
packages/cli/package.json
packages/cli/src/cmds/preview/commonUtils.ts
packages/cli/src/cmds/preview/preview.ts
packages/cli/src/cmds/preview/task.ts

use `tree-kill` to terminate background tasks when error occurs.

fix(cli-preview): terminate background tasks when error occurs

---

packages/fx-core/src/plugins/resource/apim/answer.ts
packages/fx-core/src/plugins/resource/apim/config.ts
packages/fx-core/src/plugins/resource/apim/constants.ts
packages/fx-core/src/plugins/resource/apim/index.ts
packages/fx-core/src/plugins/resource/apim/managers/questionManager.ts
packages/fx-core/src/plugins/resource/apim/questions/question.ts
packages/fx-core/src/plugins/resource/apim/questions/vscodeQuestion.ts
packages/fx-core/tests/plugins/resource/apim/config.test.ts

Refactor APIM plugin according to the changes of teamsfx-api.
1. Use `input` instead of `answer` in the question model
2. Use `LocalFunc` instead of `callFunc` in the question model
3. Remove the usage of `Stage.update`
4. Add lifecycle `GetQuestionsForUserTask`

refactor(apim): refactor apim plugin according to core refactor

---

packages/fx-core/src/plugins/resource/aad/errors.ts
packages/fx-core/src/plugins/resource/aad/index.ts

show detail message in pop up window;
remove "Please refer to the log for detailed information" from error message;
Previous pop up winodw:
Now:

fix(aad): show detail error message in pop up window

---

packages/cli/package-lock.json
packages/cli/package.json
packages/cli/src/commonlib/cacheAccess.ts
packages/vscode-extension/package-lock.json
packages/vscode-extension/package.json
packages/vscode-extension/src/commonlib/cacheAccess.ts
packages/vscode-extension/src/resources/Strings.json

Revert the changes in #1494 
The "@azure/msal-node-extensions" contains native module "dpapi" which may not work in vscode extension. Revert the change and to not break vsix.

chore(login): revert "prepare msal-node-extension to encrypt/decrypt token (#1494)"

---

packages/fx-core/src/plugins/resource/apim/log.ts

Change `Failed to find resource` to `Resource does not exist` in the log message.

fix(apim): change resource not found error message

---

packages/fx-core/src/plugins/resource/function/constants.ts
packages/fx-core/src/plugins/resource/function/plugin.ts
packages/fx-core/src/plugins/resource/function/resources/errors.ts
packages/fx-core/src/plugins/resource/function/resources/message.ts
packages/fx-core/src/plugins/resource/function/resources/steps.ts
packages/fx-core/src/plugins/resource/function/utils/azure-client.ts
packages/fx-core/tests/plugins/resource/function/unit/azure-client.test.ts
packages/fx-core/tests/plugins/resource/function/unit/provision.test.ts

Have tested below scenario and all get expected result.
<body lang=EN-US style='tab-interval:.5in;word-wrap:break-word'>
  | User can create resource but is not granted to register   resource provider | User have full permission to the subs
-- | -- | --
Required RPs have been registered | Pass | Pass
Required RPs are in Unregistering, Registering or   Unregistered status. | Failed with   RegisterResourceProviderError | Pass
</body>

feat(function): register required RPs for function app in provision step

---

packages/vscode-extension/src/debug/runIconHandler.ts
packages/vscode-extension/src/extension.ts

1. Do not change run icon display status when opening a new editor
2. Make sure `workbench.view.debug` finished before `workbench.action.debug.selectandstart`

fix(localdebug): Do not change run icon display status when opening a new editor

---

packages/cli/src/cmds/index.ts

Disabled preview command as env checker for CLI is not ready.

fix(cli-preview): disable cli preview

---

packages/cli/src/cmds/preview/depsChecker/checker.ts
packages/cli/src/cmds/preview/depsChecker/cliAdapter.ts
packages/cli/src/cmds/preview/depsChecker/dotnetChecker.ts
packages/cli/src/cmds/preview/depsChecker/funcToolChecker.ts
packages/cli/src/cmds/preview/depsChecker/nodeChecker.ts
packages/fx-core/src/plugins/resource/function/utils/depsChecker/checker.ts
packages/fx-core/src/plugins/resource/function/utils/depsChecker/dotnetChecker.ts
packages/fx-core/src/plugins/resource/function/utils/depsChecker/funcPluginAdapter.ts
packages/vscode-extension/src/debug/depsChecker/checker.ts
packages/vscode-extension/src/debug/depsChecker/dotnetChecker.ts
packages/vscode-extension/src/debug/depsChecker/funcToolChecker.ts
packages/vscode-extension/src/debug/depsChecker/nodeChecker.ts
packages/vscode-extension/src/debug/depsChecker/vscodeAdapter.ts
packages/vscode-extension/test/suite/envChecker/adapters/testAdapter.ts

- Refactor `xxxEnabled()` function to async function, because retrieving config requires async function calls which won't work with normal functions.
- There are two commits, the first of which is refactoring and the other is just copying files.
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/10338893/

refactor(env-checker): [part-4] refactor feature flags with async functions to support cli senarios

---

packages/cli/src/utils.ts

When the output `scrolling the window`, the rest of the line will be filled with color of the first character.
Reference: https://stackoverflow.com/a/53741857/16437100

fix(cli): set background color for the rest of the line

---

packages/cli/src/cmds/preview/depsChecker/cliAdapter.ts
packages/cli/src/cmds/preview/depsChecker/cliTelemetry.ts
packages/cli/src/telemetry/cliTelemetryEvents.ts

The telemetry implemenation is similar to the extension's, with just slight differences replacing `ExtTelemetry` with `cliTelemtry`
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/10338893/

feat(env-checker): [part-3] add telemetry implementation in CLI env checker

---

packages/fx-core/package.json
packages/fx-core/src/plugins/resource/apim/error.ts
packages/fx-core/src/plugins/resource/apim/utils/openApiProcessor.ts
packages/fx-core/tests/plugins/resource/apim/data/openApiProcessor/errorSpec/title-empty.json
packages/fx-core/tests/plugins/resource/apim/data/openApiProcessor/errorSpec/title-undefined.yaml
packages/fx-core/tests/plugins/resource/apim/data/openApiProcessor/errorSpec/version-empty.yaml
packages/fx-core/tests/plugins/resource/apim/data/openApiProcessor/errorSpec/version-undefined.json
packages/fx-core/tests/plugins/resource/apim/openApiProcessor.test.ts

Validate the Open API document when loading the document
Fix the bugs when the Open API document is invalid.
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/10117377/
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/10126313/

fix(apim): validate the openapi document when load the document

---

packages/cli/package-lock.json
packages/cli/package.json
packages/cli/src/cmds/preview/constants.ts
packages/cli/src/cmds/preview/errors.ts
packages/cli/src/cmds/preview/preview.ts
packages/cli/src/telemetry/cliTelemetryEvents.ts

To fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/10318744
@Alive-Fish @jiayi-ruan Please help review, thanks:
1. `package.json` and `package-lock.json`: upgrade `open` version to use `open.apps` for browser selection
2. `src/telemetry/cliTelemetryEvents.ts`: add `preview-browser` telemetry property

feat(cli-preview): add browser option to preview command

---

packages/cli/src/cmds/preview/depsChecker/funcToolChecker.ts
packages/vscode-extension/src/debug/depsChecker/funcToolChecker.ts

[bug](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/10357266)

fix(env checker): remove func-core-tool v2 from supported list

---

.github/workflows/cd.yml
.github/workflows/unit-test.yml

before publish npm package, there will be a update AI key commit, so So it turns out that there will be errors by judging ^HEAD package.json version.
It's better to judge the version change by last commits with local tags, if changed, means lerna version tags on last commits, so there need to release visx to GitHub

chore: fix pack bug

---

packages/cli/src/cmds/config.ts

Originally, the config value of `validate-dotnet-sdk` will fail to be printed because a wrong key is specified.
After the fix:

fix(env-checker): cli config get returns incorrect undefined value

---

packages/cli/src/cmds/preview/depsChecker/cliAdapter.ts
packages/cli/src/userSetttings.ts

We should check whether the config value equals to the string literal "on", instead of checking for truthy values.
Test result (set validate-dotnet-sdk to off and uninstall dotnet-sdk)

fix(env-checker): config set to off does not disable env checker

---

docs/cli/user-manual.md

Add documentation for env checker feature flags in CLI.
You can preview the markdown here: https://github.com/OfficeDev/TeamsFx/blob/aochengwang/docs/cli-env-checker/docs/cli/user-manual.md
task: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/10356462

docs(env-checker): add env checker config document

---

packages/vscode-extension/package.json

fix: Remove the space character at the end of command - Create New Project in vscode extension

fix: remove space character at the end of command - Create New Project in vscode extension

---

packages/cli/.nycrc
packages/cli/package.json
packages/cli/tests/unit/cmds/new.tests.ts
packages/cli/tests/unit/progressHandler.tests.ts
packages/cli/tests/unit/telemetry/cliTelemetry.tests.ts
packages/cli/tests/unit/telemetry/telemetryReporter.tests.ts

https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/10374056
Except for the `commonlib` and `preview` part, the coverage has gone to 90%:

test: add telemetry and progress handler's unit tests

---

packages/fx-core/src/common/tools.ts
packages/fx-core/tests/core/other.test.ts

Add an extra `isArmSupportEnabled` function for ARM, so we can turn on/off ARM support by default in code easily.

chore: add feature flag function for arm

---

packages/fx-core/src/plugins/resource/aad/appStudio.ts
packages/fx-core/src/plugins/resource/appstudio/appStudio.ts
packages/fx-core/src/plugins/resource/bot/appStudio/appStudio.ts

Add a query parameter to app studio calls, to let dev portal's telemetry know how many calls are from Teams toolkit.
Related bug: 10386504

fix: add query param to app studio calls

---

packages/vscode-extension/src/telemetry/extTelemetry.ts
packages/vscode-extension/src/utils/survey.ts

https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/10397347
1. set interval to check if it should start to count down (for fixing the reminding button cannot work when users don't reopen vscode extension.
2. add a flag in `ExtTelemetry` to identify the user's first activity which move the `exp` telemetry event -- query-expfeature.
3. fixed: show survey 7min later when triggering the `reminder` button.
4. fixed: the 25% flag is applied to the whole session.

fix: start to count down (show survey) when sending the first telemetry event

---

packages/vscode-extension/src/controls/QuickStart.tsx

1. Focus on step card when navigate using keyboard
2. Focus on next step card when clicking next button
3. When clicking step card, re-trigger the screen reader to read expanded contents

feat: keyboard navigation support on quick start webview

---

packages/cli/src/helpParamGenerator.ts
packages/cli/tests/unit/help.tests.ts

https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/9880763

fix: hide scratch and samples in CLI new parameters

---

packages/vscode-extension/src/controls/SampleGallery.tsx

feat: support accessibility for sample gallery

---

packages/fx-core/src/plugins/resource/appstudio/plugin.ts
packages/fx-core/src/plugins/solution/fx-solution/solution.ts

Create an app again if the user manually deletes the app from dev portal and run localDebug.

fix: fix appstudio localDebug cornercase

---

packages/sdk/rollup.base.config.js
packages/sdk/rollup.config.js

The ES format output could be used in .NET SDK.

chore(sdk): add a new bundle output for Blazor interop

---

packages/fx-core/src/plugins/resource/function/constants.ts

Also align to Azure Portal, Storage Account for Function App use flat namespace.

fix(function): storage account could use flat namespace to lessen cost

---

packages/fx-core/src/core/environment.ts
packages/fx-core/src/core/middleware/configWriter.ts
packages/fx-core/src/core/middleware/contextLoader.ts
packages/fx-core/tests/core/environment.test.ts
packages/fx-core/tests/core/hooks.test.ts

This is the following PR after https://github.com/OfficeDev/TeamsFx/pull/1752: Extract the logic to persist the env profile from `configWriter.ts` to `environment.ts`, and add a few test cases for the new added API.

refactor(core): extract the logic to write env profiles

---

packages/api/review/teamsfx-api.api.md
packages/api/src/types.ts
packages/fx-core/src/common/tools.ts
packages/fx-core/src/core/environment.ts
packages/fx-core/src/core/index.ts
packages/fx-core/src/core/middleware/contextLoader.ts
packages/fx-core/src/core/middleware/projectUpgrader.ts
packages/fx-core/tests/core/environment.test.ts
packages/fx-core/tests/core/hooks.test.ts
packages/fx-core/tests/core/utils.ts
packages/fx-core/tests/plugins/resource/appstudio/unit/build.test.ts
packages/fx-core/tests/plugins/resource/appstudio/unit/getAppDefinitionAndUpdate.test.ts
packages/fx-core/tests/plugins/resource/appstudio/unit/localDebug.test.ts
packages/fx-core/tests/plugins/resource/appstudio/unit/publish.test.ts
packages/fx-core/tests/plugins/resource/appstudio/unit/scaffold.test.ts
packages/fx-core/tests/plugins/resource/bot/unit/utils.ts
packages/fx-core/tests/plugins/resource/frontend/helper.ts
packages/fx-core/tests/plugins/resource/localdebug/unit/index.test.ts
packages/fx-core/tests/plugins/solution/solution.arm.test.ts
packages/fx-core/tests/plugins/solution/solution.create.test.ts
packages/fx-core/tests/plugins/solution/solution.provision.test.ts
packages/fx-core/tests/plugins/solution/solution.scaffold.test.ts
packages/fx-core/tests/plugins/solution/solution.update.test.ts

This is the following PR after https://github.com/OfficeDev/TeamsFx/pull/1752 and https://github.com/OfficeDev/TeamsFx/pull/1798 : clean up the usage of `currentEnv` from project settings because the target env name from user input will be respected.
For current usage of `currentEnv`, the default value of target env name (`default`) will be used, because only single default environment is supported until the user input of env is enabled.

refactor(core): clean up currentEnv from project settings

---

packages/api/review/teamsfx-api.api.md
packages/api/src/context.ts
packages/api/src/types.ts
packages/fx-core/src/common/localSettingsConstants.ts
packages/fx-core/src/common/localSettingsProvider.ts
packages/fx-core/src/plugins/solution/fx-solution/solution.ts
packages/fx-core/tests/core/localSettings.test.ts
packages/fx-core/tests/plugins/solution/solution.scaffold.test.ts

**Changes in this PR**:
1. Add `localSettings` API contract in solution & plugin context.
2. Define interface `LocalSettings` for the schema of `localSettings.json` file.
3. Provide a `LocalSetingsProvider` to init/local/save `localSettings.json` file.
**Changes in upcoming PRs**:
1. Update resource plugins to read/write local debug related configs from `localSettings.json` file.
2. Update local debug component to generated env variables from `localSettings.json` file.
3. Update VS Code extension & CLI to integrate with the new `localSettings.json` file. 
4. Add feature flag to enable/disable using the new local debug settings.
5. Clean up legacy code for `local.env`.
6. ...

feat(multi-env): add localSettings in context and implement provider for init/load/save

---

packages/fx-core/src/common/constants.ts
packages/fx-core/src/common/tools.ts
packages/fx-core/src/plugins/solution/fx-solution/solution.ts
packages/fx-core/tests/core/other.test.ts
packages/fx-core/tests/plugins/solution/solution.scaffold.test.ts

Added environment variable `TEAMSFX_MULTI_ENV` as feature flag to control multi-env related features. 
In this PR, the toolkit will not persistent the localSettings to file system if the multi-env feature flag is not enabled.

chore(multi-env): add feature flag for multiple environment support

---

packages/fx-core/src/core/index.ts
packages/fx-core/src/plugins/resource/appstudio/plugin.ts
packages/fx-core/tests/plugins/resource/appstudio/unit/build.test.ts
packages/fx-core/tests/plugins/resource/appstudio/unit/publish.test.ts

1. When building teamsAppPackage, if the icons are found in .fx directory, it will be moved to appPackage directory
2. Fix the wrong directory ensure 
`await fs.ensureDir(path.join(projectPath, ${AppPackageFolderName}));`

feat: migrate icons and manifest in old project when building teams package

---

packages/cli/src/cmds/preview/constants.ts
packages/cli/src/cmds/preview/preview.ts

To fix: #1773 or https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/10512957.

fix(cli-preview): do not terminate the preview if opening browser fails

---

packages/api/review/teamsfx-api.api.md
packages/api/src/types.ts
packages/cli/src/cmds/preview/errors.ts
packages/cli/src/cmds/preview/preview.ts
packages/fx-core/src/core/middleware/contextLoader.ts
packages/fx-core/src/plugins/resource/bot/configs/scaffoldConfig.ts
packages/fx-core/src/plugins/resource/function/plugin.ts
packages/fx-core/src/plugins/resource/localdebug/index.ts
packages/fx-core/src/plugins/solution/fx-solution/solution.ts
packages/fx-core/tests/plugins/resource/function/unit/deploy.test.ts
packages/fx-core/tests/plugins/resource/function/unit/provision.test.ts
packages/fx-core/tests/plugins/resource/function/unit/scaffold.test.ts
packages/fx-core/tests/plugins/solution/solution.create.test.ts

Previously the `programmingLanguage` settings is saved in `env.default.json` file. As this is a project-level config, we'll move it to `settings.json` file to better support multi-env.
@YitongFeng-git As we modified bot & function plugin to read `programmingLanguage` from project settings instead of solution plugin config, please also help to review this PR. Thanks in advance.

refactor(multi-env): move programming language to project settings

---

packages/api/review/teamsfx-api.api.md
packages/fx-core/src/core/environment.ts
packages/fx-core/src/core/index.ts
packages/fx-core/src/core/middleware/configWriter.ts
packages/fx-core/src/core/middleware/contextLoader.ts
packages/fx-core/src/core/middleware/envInfoLoader.ts
packages/fx-core/src/core/middleware/envInfoWriter.ts
packages/fx-core/tests/core/core.test.ts
packages/fx-core/tests/core/hooks.test.ts

Separate the original `ContextLoad` and `ConfigWriter` middleware into two parts:
- Project settings loader/writer
- Env profile loader/writer
Reason to do it:
- Some lifecycle or operation doesn't need to load env profile, such like local debug.
- Env profile loader would require user input for the target env name if there're multiple environments, while project settings loader doesn't need.

refactor(core): extract the env info loader/writer from context loader/writer middleware

---

packages/fx-core/src/common/localSettingsConstants.ts
packages/fx-core/src/plugins/resource/aad/plugin.ts
packages/fx-core/src/plugins/resource/aad/utils/common.ts
packages/fx-core/src/plugins/resource/aad/utils/configs.ts

If multi-env feature flag is enabled, AAD plugin will use `localSettings.json` to read/write local debug related configuration. Otherwise, the local debug config logic remains the same as original.

refactor(local-debug): update aad plugin to use localSettings for local debug

---

packages/cli/src/cmds/preview/commonUtils.ts
packages/cli/src/cmds/preview/npmLogHandler.ts
packages/fx-core/src/plugins/resource/localdebug/tasks.ts
packages/vscode-extension/src/debug/constants.ts
packages/vscode-extension/src/debug/npmLogHandler.ts
packages/vscode-extension/src/debug/teamsfxTaskHandler.ts

- remove silent config for backend install task since we already have switching running terminal function
- make npm install failed hint message clearer
- check the time difference between the timestamp of npm install log and when the task stops
Fix https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/10523883

fix(local-debug): improve local debug experience

---

packages/fx-core/src/common/localSettingsConstants.ts
packages/fx-core/src/plugins/resource/bot/configs/localDebugConfig.ts

If multi-env feature flag is enabled, bot plugin will use `localSettings.json` to read/write local debug related configuration. Otherwise, the local debug config logic remains the same as original.

refactor(localdebug): update bot plugin to use localSettings for local debug

---

packages/fx-core/src/plugins/resource/appstudio/plugin.ts
packages/fx-core/src/plugins/solution/fx-solution/solution.ts

If multi-env feature flag is enabled, AppStudio plugin will use `localSettings.json` to read/write local debug related configuration. Otherwise, the local debug config logic remains the same as original.

refactor(localdebug): use localSettings in AppStudio plugin for local debug

---

packages/fx-core/src/plugins/resource/simpleauth/utils/common.ts

Bug description: if `TEAMSFX_MULTI_ENV` is enable, the simple auth plugin will always read config from `localSettings` whether or not it is in localdebug.

fix(localdebug): simpleauth read config bug if enable multi-env

---

packages/api/review/teamsfx-api.api.md
packages/api/src/types.ts
packages/cli/src/cmds/preview/commonUtils.ts
packages/cli/src/cmds/preview/constants.ts
packages/cli/src/cmds/preview/preview.ts
packages/fx-core/.nycrc
packages/fx-core/src/plugins/resource/localdebug/index.ts
packages/fx-core/src/plugins/resource/localdebug/legacyPlugin.ts
packages/vscode-extension/src/debug/commonUtils.ts
packages/vscode-extension/src/debug/teamsfxTaskProvider.ts

If `TEAMSFX_MULTI_ENV` feature flag is enabled:
- LocalDebug plugin will use `localSettings` to read/write configurations for local debug.
- The `local.env` file will not be used in `post-localdebug` to persist the environment variables passed to UX layer. Instead, we maintain these local envs in-memory, and expose an user task to invoke by the toolkit extension.
- Extension and CLI will use the `localSetings.json` file  as the source-of-truth to read configuration for local debug.
Otherwise:
- The local debug behavior keeps the same as original, which still uses `env.default.json`, `local.env`, `default.userdata` to run local debug.
**NOTE**: To make this PR more friendly to be reviewed, I copy the [original `localDebug` & `postLocalDebug`](https://github.com/OfficeDev/TeamsFx/blob/dev/pa …

refactor(localdebug): update localdebug plugin and UX(ext&cli) to use localSettings

---

packages/fx-core/src/plugins/solution/fx-solution/arm.ts
packages/fx-core/tests/plugins/solution/solution.arm.test.ts

Replace the hardcoded `default` env name with the target env name from context. 
- When the feature flag `TEAMSFX_MULTI_ENV` is not enabled, the target env equals to `default`.
- When the feature flag `TEAMSFX_MULTI_ENV` enabled, the target env is specified by user and would be accessed from context.

chore(arm): use target env name from context

---

packages/api/review/teamsfx-api.api.md
packages/api/src/error.ts
packages/api/tests/error.test.ts

When creating UserError or SystemError, the stack fields will be created automatically, user don't need to input.
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/10577820

fix: make sure SystemError and UserError has stack

---

packages/fx-core/src/core/environment.ts
packages/fx-core/src/core/error.ts
packages/fx-core/src/core/index.ts
packages/fx-core/src/core/middleware/envInfoLoader.ts
packages/fx-core/src/core/middleware/envInfoWriter.ts
packages/fx-core/src/core/middleware/projectSettingsLoader.ts
packages/fx-core/src/core/question.ts
packages/fx-core/src/plugins/solution/fx-solution/solution.ts
packages/fx-core/tests/core/environment.test.ts
packages/fx-core/tests/core/hooks.test.ts

If `TEAMSFX_MULTI_ENV` feature flag is enabled, user will be asked to input the target environment when provision, deploy and publish.
Here's the gif for the new UX:
Please note:
* the UX design is not finalized and above user behavoir might be changed in future.
* only **VS Code extension** is supported, while **CLI** is not supported at the moment.
* only projects contain **Tab** or **Function** is supported, while **Bot/SQL** is not support.

chore(multi-env): support user input for target env

---

packages/fx-core/src/core/middleware/envInfoLoader.ts

* append `(current)` if user has choose the target env before.
* the last used env will be in the first place of all environments except for the new environment.
Please note, since the last used info won't be persisted in project, it will reset to undefined if the vscode is reopened.
**Provision**:
**Deploy/Publish**:

chore(multi-env): support to display the last used env with new order

---

packages/fx-core/src/common/constants.ts
packages/fx-core/src/common/localSettingsConstants.ts
packages/fx-core/src/plugins/resource/aad/utils/configs.ts
packages/fx-core/src/plugins/resource/function/constants.ts
packages/fx-core/src/plugins/resource/function/ops/provision.ts
packages/fx-core/src/plugins/resource/localdebug/index.ts
packages/fx-core/src/plugins/resource/localdebug/legacyPlugin.ts
packages/fx-core/src/plugins/resource/simpleauth/constants.ts
packages/fx-core/src/plugins/resource/simpleauth/utils/common.ts
packages/fx-core/tests/plugins/resource/simpleauth/helper.ts
packages/fx-core/tests/plugins/resource/simpleauth/unit/index.test.ts

Current Teams toolkit persists the `teamsMobileDesktopAppId` and `teamsWebAppId` in the AAD plugin config, and other resource plugins (e.g. simpleAuth, localdebug) will read these value from the config.
```json
"fx-resource-aad-app-for-teams": {
"teamsMobileDesktopAppId": "1fec8e78-bce4-4aaf-ab1b-5451cc387264",
"teamsWebAppId": "5e3ce6c0-2b1f-4285-8d4b-75ee78787346",
},
```
As these are known constant values, we can remove them from the config and use global constants to read the values.

refactor: remove teamsMobileDesktopAppId and teamsWebAppId from env config

---

packages/fx-core/tests/plugins/resource/frontend/unit/index.test.ts

With ARM provision feature enabled, the ut fails for original provision method is not called.

fix(frontend): ut should not be affected by environment

---

packages/api/review/teamsfx-api.api.md
packages/api/src/context.ts
packages/api/src/utils/index.ts
packages/api/src/utils/permissionRequest.ts
packages/fx-core/src/core/middleware/envInfoLoader.ts
packages/fx-core/src/core/middleware/projectSettingsLoader.ts
packages/fx-core/src/core/permissionRequest.ts
packages/fx-core/src/plugins/resource/aad/errors.ts
packages/fx-core/src/plugins/resource/aad/utils/configs.ts
packages/fx-core/src/plugins/solution/fx-solution/constants.ts
packages/fx-core/src/plugins/solution/fx-solution/solution.ts
packages/fx-core/tests/core/utils.ts
packages/fx-core/tests/plugins/resource/aad/helper.ts

**Changes:**
Add `permissionRequestProvider` in the context interface so that AAD plugin can get permissionRequest content to set/update the AAD permissions. 
**Reasons to do so:**
- Remove the dependency of using solution config to set the permission request content and pass to the resource plugins.
- Separate the provider implementation out of AAD plugin, e.g. for VSC it is a file provider, which read content from `permissions.json`, while for "teamsfx init" for Blazor app it should be an constant default value since there is no `permissions.json` in the project.
- For better testability.

refactor: don't use solution config for AAD permission request

---

packages/fx-core/src/plugins/resource/localdebug/launch.ts
packages/vscode-extension/src/debug/teamsfxDebugProvider.ts

- add timeout to launch browser configuration and set it to 20 seconds (default is 10 seconds) to mitigate "could not attach to main target" error
To fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/10576081 or #1882

fix(local-debug): add timeout to launch browser configuration

---

packages/fx-core/src/core/middleware/envInfoWriter.ts
packages/fx-core/src/plugins/resource/aad/utils/configs.ts
packages/fx-core/src/plugins/solution/fx-solution/solution.ts

Fix in this PR:
- When local debug, retrieve the `tabDomain` and `tabEndpoint` from `localSettings` if `TEAMSFX_ARM_SUPPORT` is enabled.
- Do not persist the local debug plugin config in `env.default.json`,

fix: auth failed in local debug and skip local debug config persistent

---

packages/cli/src/cmds/config.ts
packages/cli/src/commonlib/telemetry.ts
packages/cli/src/userSetttings.ts

Add new config to support `run-from`.
`teamsfx config set run-from GitHubAction`
then, the telemetry will contains extra property p['run-from'] = 'GitHubAction'
set config by `teamsfx config set run-from GitHubAction`
receive telemetry with property:
to support https://dev.azure.com/msazure/Microsoft%20Teams%20Extensibility/_workitems/edit/10366285

feat: support run-from config

---

packages/fx-core/src/plugins/resource/appstudio/plugin.ts

For spfx project, the id in scaffolded manifet.source.json equals to component ID.
So we want to let remote teams app id equals to manifest.id, keep consistency.

fix: use componentID for SPFx remote teams app

---

packages/api/review/teamsfx-api.api.md
packages/api/src/types.ts
packages/fx-core/src/core/middleware/envInfoLoader.ts
packages/fx-core/src/core/middleware/envInfoWriter.ts
packages/vscode-extension/src/accountTree.ts

solutionSettings is from project settings `settings.json`, so there's no need to load env profile such like `env.<env_name>.json`.

fix(multi-env): no need to load env info for getAzureSolutionSettings

---

packages/cli/src/console/screen.ts

https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/10645266
1. show cursor first when initialize screen manager.
2. move cursor to left first before move cursor up/down.

fix: cli screen's anomalous experience

---

packages/fx-core/src/plugins/solution/fx-solution/executor.ts
packages/fx-core/src/plugins/solution/fx-solution/solution.ts

Save remote teams app id into config file, even if other resources provision failed. (like app service plan quota)
Otherwise, the toolkit will create multiple teams app when provision again.

fix: save teams app id when provisioning failed for other resources

---

packages/fx-core/src/plugins/resource/function/enums.ts
packages/fx-core/src/plugins/resource/function/index.ts
packages/fx-core/src/plugins/resource/function/plugin.ts
packages/fx-core/src/plugins/resource/function/v2/index.ts

V2 api treats `addResource` as customizedTask of plugin. Function plugin needs to implement the `executeUserTask` for addResource.

refactor(function): adapt v2 api

---

packages/api/review/teamsfx-api.api.md
packages/api/src/constants.ts
packages/fx-core/src/common/localSettingsProvider.ts
packages/fx-core/src/core/environment.ts
packages/fx-core/src/core/middleware/projectSettingsLoader.ts
packages/fx-core/src/core/middleware/projectSettingsWriter.ts
packages/fx-core/src/core/middleware/projectUpgrader.ts
packages/vscode-extension/src/commonlib/azureLogin.ts
packages/vscode-extension/src/commonlib/common/constant.ts
packages/vscode-extension/src/debug/commonUtils.ts
packages/vscode-extension/src/utils/commonUtils.ts

[design](https://microsoftapc.sharepoint.com/teams/DevDivTeamsDevXProductTeam/_layouts/OneNote.aspx?id=%2Fteams%2FDevDivTeamsDevXProductTeam%2FShared%20Documents%2FService%20infrastructure%20Team%2FInfra%20team&wd=target%28Infra.one%7C54126BB5-B660-493E-ABC2-5CDF1390B13A%2FFolder%20structure%20and%20file%20naming%7C137CF56A-5AD2-4117-9AB0-E2C7609DA551%2F%29)
- move `.fx/localSettings.json` to `.fx/configs/localSettings.json`
- move `.fx/settings.json` to `.fx/projectSettings.json`
- fix default profile file name for local debug
- for CLI part, I will change in another PR
Test result:
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/10667418/

refactor(multi-env): rename project/local settings file and fix local debug

---

packages/fx-core/src/common/tools.ts
packages/fx-core/src/core/index.ts
packages/fx-core/src/plugins/resource/appstudio/constants.ts
packages/fx-core/src/plugins/resource/appstudio/plugin.ts
packages/fx-core/src/plugins/resource/spfx/plugin.ts

[feature design](https://microsoftapc.sharepoint.com/teams/DevDivTeamsDevXProductTeam/_layouts/OneNote.aspx?id=%2Fteams%2FDevDivTeamsDevXProductTeam%2FShared%20Documents%2FService%20infrastructure%20Team%2FInfra%20team&wd=target%28Infra.one%7C54126BB5-B660-493E-ABC2-5CDF1390B13A%2FFolder%20structure%20and%20file%20naming%7C137CF56A-5AD2-4117-9AB0-E2C7609DA551%2F%29)
- move `appPackage/appPackage.zip` to `appPackage/appPackage.{envName}.zip`
- move `appPackage/manifest.source.json` to `templates/appPackage/manifest.template.json`
- move `appPackage/*.png` to `templates/appPackage/resources/*.png`
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/10667418/

refactor(multi-env): move appPackage to templates folder

---

packages/fx-core/src/core/environment.ts
packages/fx-core/src/core/middleware/envInfoLoader.ts
packages/fx-core/src/core/middleware/projectUpgrader.ts
packages/vscode-extension/src/commonlib/common/constant.ts
packages/vscode-extension/src/debug/commonUtils.ts
packages/vscode-extension/src/debug/constants.ts

[design](https://microsoftapc.sharepoint.com/teams/DevDivTeamsDevXProductTeam/_layouts/OneNote.aspx?id=%2Fteams%2FDevDivTeamsDevXProductTeam%2FShared%20Documents%2FService%20infrastructure%20Team%2FInfra%20team&wd=target%28Infra.one%7C54126BB5-B660-493E-ABC2-5CDF1390B13A%2FFolder%20structure%20and%20file%20naming%7C137CF56A-5AD2-4117-9AB0-E2C7609DA551%2F%29)
- rename default env name from "default" to "dev"
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/10667418

refactor(multi-env): rename default env to 'dev'

---

packages/fx-core/src/core/index.ts
packages/fx-core/src/core/middleware/envInfoWriter.ts
packages/fx-core/tests/core/hooks.test.ts

When multi-env is enabled, no need to scaffold `profile.<env>.json` any more.

refactor(multi-env): skip to create env profile during scaffolding

---

packages/fx-core/templates/plugins/resource/function/bicep/functionConfiguration.template.bicep
packages/fx-core/tests/plugins/resource/function/unit/expectedBicepFiles/functionConfiguration.bicep

ARM will randomly return internal server error when configuration auth setting for Azure Functions. Try to update API version to mitigate this issue. I tried provision ~10 times, all of them passed.
Waiting Azure support to provide the root cause.

fix: random internal server error from function app ARM

---

packages/fx-core/src/core/middleware/envInfoWriter.ts

If multi-env feature flag is not enabled, the local-debug experience keeps the same as the official release now.

fix: add back fx-resource-local-debug config in env.default.json

---

packages/fx-core/src/core/middleware/projectUpgrader.ts
packages/fx-core/src/core/tools.ts
packages/fx-core/tests/core/hooks.test.ts
packages/vscode-extension/src/debug/commonUtils.ts
packages/vscode-extension/src/debug/constants.ts

- Fix projectUpgrader. If `profile.${envName}.json` or `{envName}.userdata` do not exist, it must be a new project. It does not need to be upgraded
- Fix the valid project checking for new folder structure
- Fix local debug teamsAppId and tenantId in the new folder structure
Tested local debug.
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/10728294

fix(multi-env): fix multi-env for local debug

---

packages/fx-core/src/plugins/resource/sql/constants.ts
packages/fx-core/src/plugins/resource/sql/plugin.ts
packages/fx-core/tests/plugins/resource/sql/unit/index.test.ts

when the provisionSucceeded flag is true, the get question step in provision will skip.
Fix it by adding the config into ctx and loading it at the pre provision step.

chore(sql): fix sql exist check

---

packages/fx-core/.nycrc

exclude bicep env checker in fx-core, will add e2e test case to cover ut test

chore(env checker): exclude depsChecker in fx-core

---

packages/fx-core/src/plugins/solution/fx-solution/commonQuestions.ts
packages/fx-core/src/plugins/solution/fx-solution/constants.ts

- read resource group from `config.{envName}.json`
- fix a typo
Tested custom input file
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/10728283

chore(multi-env): read resource group info from input config

---

.github/CODEOWNERS
packages/api/review/teamsfx-api.api.md
packages/api/src/schemas/envConfig.json
packages/api/src/schemas/envConfig.ts

1. add code owner for the schema of env config.
2. remove the location of resource group from schema, as it's only allowed to specify an existing resource group.
3. remove the tenant id from schema, as there's no P0 scenario to support to customize tenant in env config.
3. add restriction to avoid empty string.
4. add pattern to validate the resource group name.

chore(multi-env): refine the schema of env config

---

packages/fx-core/src/plugins/resource/appstudio/constants.ts
packages/fx-core/src/plugins/resource/appstudio/index.ts
packages/fx-core/src/plugins/resource/appstudio/plugin.ts
packages/fx-core/tests/plugins/resource/appstudio/unit/migrate.test.ts

1. Replace `V1_MANIFEST` to `V1ManifestFileName`
2. Add a telemetry property to track whether a v1 tab app includes SSO.

fix(appstudio): add v1 project sso telemetry during migration

---

packages/fx-core/src/core/middleware/envInfoLoader.ts
packages/vscode-extension/src/debug/commonUtils.ts

- set `ignoreEnvInfo` to true to prevent asking for env when local debug 
- for local debug, it also needs the default env's solution context
Tested local debug with multi env feature flags on

fix(multi-env): fix the issue that toolkit asking env when localdebug

---

packages/fx-core/src/plugins/solution/fx-solution/commonQuestions.ts
packages/fx-core/src/plugins/solution/fx-solution/constants.ts

Check resource group info in the following order:
- config.{envName}.json, use can only use existing resource group
- profile.{envName}.json, for reprovision
- asking user

chore(multi-env): also check resource group from profile

---

packages/fx-core/src/plugins/resource/appstudio/appStudio.ts
packages/fx-core/src/plugins/resource/appstudio/errors.ts
packages/fx-core/src/plugins/resource/appstudio/plugin.ts

Users may manually delete teams app in dev portal, treat it as user error. 
1) Before publish, we will identify this error.
2) For local debug/provision, if app not found we will automatically create one

fix: identify app not found as UserError

---

packages/cli/.nycrc
packages/cli/cli.js
packages/cli/package.json

https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/10654915
When running `teamsfx -h` with node 10, it will look as below:

fix: change node version error in cli

---

packages/fx-core/src/plugins/solution/fx-solution/executor.ts

For provision, will save app id and then check the results.

fix: check lifecycle results for deploy/scaffold

---

docs/vscode-extension/migrate-v1/migrate-v1-tab.md

add the way to find aad client id in migrate tab doc

docs(migratev1): add the way to find aad client id in migrate tab doc

---

packages/fx-core/src/plugins/solution/fx-solution/commonQuestions.ts

- When `TEAMS_MULTI_ENV` is enabled, default resource group name will contain envName to prevent collison. The format is `{appName}-{envName}-rg`
- When `TEAMS_MULTI_ENV` is not enabled, the behavior is the same as before

chore(multi-env): put env name in default resource group name

---

packages/fx-core/src/plugins/resource/appstudio/plugin.ts

Some values are missed when covert manifest to app definition.

fix: devicePermission is not updated in app studio

---

templates/bot/ts/default/package.json

To fix remote debug failed, for it runs index.js under lib/ when remote debug. Local debug works well.

fix(bot): copy adaptive cards to lib

---

docs/vscode-extension/customapp-help.md

Add help doc for custom app permission. This doc helps user on enabling custom app policy.

docs: add help doc for custom app permission

---

packages/fx-core/src/core/middleware/envInfoLoader.ts
packages/vscode-extension/src/handlers.ts
packages/vscode-extension/test/unit/extension/handlers.test.ts

This PR removes the dependency on default env for local debug.
The implementation is:
- extension will set `ignoreEnvInfo` to `true` for local debug
- when `ignoreEnvInfo` is set to `true`, 
- Core will try to load default env for upgrading project.
- On failure to load default env, core will ignore the error and continue to load other configs to solutionContext (e.g. project settings). This works because local debug does not use env info
Tested local debug without default env (no config.dev.json)
CLI will be changed later

fix(multi-env): local debug does not depend on default env

---

packages/vscode-extension/src/debug/commonUtils.ts

- should not ignore env info for remote debug
Tested that local debug and remote debug works.

fix(multi-env): fix remote debug for multi env

---

packages/fx-core/src/plugins/resource/sql/config.ts
packages/fx-core/src/plugins/resource/sql/constants.ts
packages/fx-core/src/plugins/resource/sql/plugin.ts

Since getQuestions will skip in reprovision if first provision is successful, the check status of sql existing is skipped as well.
Use the config prepareQuestions to keep the status of sql existing when the getQuestions is skipped.

chore(sql): fix reprovision bug

---

packages/fx-core/src/plugins/resource/apim/config.ts
packages/fx-core/src/plugins/resource/apim/factory.ts
packages/fx-core/src/plugins/resource/bot/configs/provisionConfig.ts
packages/fx-core/src/plugins/resource/bot/resources/strings.ts
packages/fx-core/src/plugins/resource/frontend/configs.ts
packages/fx-core/src/plugins/resource/function/plugin.ts
packages/fx-core/src/plugins/resource/identity/index.ts
packages/fx-core/src/plugins/resource/simpleauth/plugin.ts
packages/fx-core/src/plugins/resource/sql/plugin.ts
packages/fx-core/src/plugins/solution/fx-solution/arm.ts
packages/fx-core/src/plugins/solution/fx-solution/commonQuestions.ts
packages/fx-core/src/plugins/solution/fx-solution/constants.ts
packages/fx-core/src/plugins/solution/fx-solution/solution.ts
packages/fx-core/tests/plugins/resource/bot/unit/utils.ts
packages/fx-core/tests/plugins/resource/frontend/helper.ts
packages/fx-core/tests/plugins/resource/function/unit/deploy.test.ts
packages/fx-core/tests/plugins/solution/solution.arm.test.ts

Plugins will read sub from `ctx` (just like resource group) instead of `accountProvider`. This will clear the path to change the logic of reading subs in solution.
Tested local debug and remote happy path.
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/10736857

refactor(multi-env): plugin retrieves subscription from ctx instead of accountProvider

---

packages/fx-core/src/plugins/solution/fx-solution/solution.ts
packages/vscode-extension/src/envTree.ts

1. Show different icons for active environment and inactive environments.

fix: update env ui

---

packages/fx-core/src/plugins/resource/apim/factory.ts

AddResource can happen before provision, and it requires subscription ID to list the existing APIM instances. In that case, subscriptionId from solutionConfig does not exist yet, so it will not work. Fix this bug by falling back to the previous behavior to read subs from `azureAccountProvider` when `solutionConfig.subscriptionId` is a falsy value.
I've also checked that other plugins does not have this issue.
E2E test result: https://github.com/OfficeDev/TeamsFx/actions/runs/1204566179
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/10790598/

fix: fix apim e2e test AddResource failure with null sub id

---

templates/tab/ts/default/src/components/sample/AzureFunctions.tsx
templates/tab/ts/default/src/components/sample/lib/useGraph.ts

This PR is going to fix the compiler error:
```
Object is of type 'unknown'.  TS2571
27 |   } catch (err) {
28 |     let funcErrorMsg = "";
> 29 |     if (err.response?.status === 404) {
|         ^
30 |       funcErrorMsg = `There may be a problem with the deployment of Azure Function App, please deploy Azure Function (Run command palette "TeamsFx - Deploy Package") first before running this App`;
31 |     } else if (err.message === "Network Error") {
32 |       funcErrorMsg =
```
Before TypeScript 4.4, the `catch` clause bindings were set to `any`. TypeScript 4.4 introduced a new compiler option [`useUnknownInCatchVariables`](https://www.typescriptlang.org/tsconfig#useUnknownInCatchVariables) which is `true` by default if you have `strict` option turned on (as we have done).
By turning …

fix(tab): refine type annotation in ts error handling

---

packages/api/review/teamsfx-api.api.md
packages/api/src/utils/login.ts
packages/fx-core/src/plugins/solution/fx-solution/commonQuestions.ts
packages/fx-core/src/plugins/solution/fx-solution/constants.ts

- when multi-env is enabled, it will first read subs from input config (config.dev.json). If not found, it will pop up and ask user, same as the previous behavior)
- confirmed with @xiaolang124 that `getAccountCredentialAsync` will never return undefined
Tested remote happy path with and without feature flag
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/10736857

feat(multi-env): support to read subs from input config

---

packages/vscode-extension/src/accountTree.ts

Per *vscode/issues/131955*, need to call `TreeView.reveal` to show a collapsed tree item.
This PR is a workaround to force expand the item by changing its label, and could be improved later when `reveal` is supported.

fix: workaround to expand account child item

---

packages/cli/src/userInteraction.ts

- there are two possibilities for the `choices` object. Once is `string` and another is `ChoicesOption`. The latter is not handled previously.

fix(cli): fix CLI user interaction in CI mode

---

packages/vscode-extension/src/handlers.ts

ADO: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/10793856

fix(vsc): show azure account in cpm when open empty project

---

templates/tab/ts/default/src/components/sample/lib/useGraph.ts

We also need to update the [document](https://github.com/OfficeDev/TeamsFx/blob/dev/packages/sdk/README.md#error-handling) later.

fix(tab): graph client wrap ErrorWithCode as GraphError

---

packages/fx-core/src/core/error.ts
packages/fx-core/src/core/index.ts
packages/fx-core/src/core/middleware/envInfoLoader.ts
packages/fx-core/src/core/question.ts
packages/fx-core/src/core/v2/index.ts
packages/fx-core/src/plugins/solution/fx-solution/arm.ts
packages/fx-core/tests/core/core.test.ts

1. On scaffold, a default environment "dev" will be created for user;
2. When project is scaffolded, user can user "create new environment copy" command to add a new environment.
-  User need to provide an existing environment name to copy (by default, the new env is copied from the active environment)
- The environment input file (`config.{env}.json` and `azure.parameters.{env}.json`) are copied from the specified env.
Select "+" button:
Provide new environment name:
Select an existing env to create copy (default is the active env):
1. @jayzhang will help to consolidate the duplicate code and sync the behavior between v1 and v2 APIs.
2. @blackchoey will help tp modify the resource base name in bicep parameter file when copy env.
3. @blackchoey will help to remove parameter.template.json.

chore(multi-env): support create environment copy

---

packages/api/review/teamsfx-api.api.md
packages/api/src/schemas/envConfig.json
packages/api/src/schemas/envConfig.ts

Add config section for existing AAD app to the schema of env config, so that user can customize it and resource plugin can consume the value.

chore(schema): add existing AAD config to env config schema

---

packages/api/review/teamsfx-api.api.md
packages/api/src/constants.ts
packages/cli/src/cmds/env.ts
packages/cli/src/cmds/index.ts
packages/cli/tests/unit/cmds/env.tests.ts

- add "teamsfx env list" command. Highlighting current env will be added with activate command in another pr
- add unit test cases for env list
- teamsfx env xxx will only be available with TEAMSFX_MULTI_ENV feature flag

feat(multi-env): add "teamsfx env list" command

---

packages/fx-core/src/plugins/resource/frontend/constants.ts
packages/fx-core/src/plugins/resource/frontend/ops/deploy.ts
packages/fx-core/src/plugins/resource/function/enums.ts
packages/fx-core/src/plugins/resource/function/ops/deploy.ts

By comparing `count EventName=deployment-info-not-found` and `distinct count MachineId+ProjectId`, we can find out how many users remove the .deployment folder and decide whether to remove the skip deployment feature.

chore: send telemetry when fail to read deployment info

---

packages/fx-core/src/core/middleware/envInfoLoader.ts

Append `(active)` on the active env when doing env selection for create env copy:

chore(multi-env): mark active env on env selection for creating env copy

---

packages/cli/src/cmds/config.ts
packages/cli/src/utils.ts
packages/cli/tests/unit/cmds/config.tests.ts
packages/fx-core/src/core/error.ts
packages/fx-core/src/core/tools.ts
packages/vscode-extension/src/debug/commonUtils.ts
packages/vscode-extension/src/envTree.ts
packages/vscode-extension/src/utils/commonUtils.ts

- move `getActiveEnv` to core so extension and CLI can share the function
- add error handling for `getActiveEnv`
- add error handling for callers of `getActiveEnv`

refactor(multi-env): move getActiveEnv to core

---

packages/cli/src/utils.ts
packages/cli/tests/unit/cmds/env.tests.ts
packages/fx-core/src/core/environment.ts
packages/fx-core/src/core/tools.ts
packages/vscode-extension/src/envTree.ts
packages/vscode-extension/src/utils/commonUtils.ts

Global functions in ESM exported by reimporting from another file cannot be mocked by sinon. Take `setActiveEnv` as an example, in core's index.ts, there are code like this:
```
export { setActiveEnv } from "./core/middleware/envInfoLoader";
```
This will be compiled to 
```
Object.defineProperty(exports, "setActiveEnv", { enumerable: true, get: function () { return envInfoLoader_1.setActiveEnv; } });
```
From [mozzila docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperty#description), we can know that this is wrapped as an readonly function (`defineProperty` without `writable: true`). This will cause sinon to fail to mock it.
This is a known issue of sinon and they said these types of issues related to module system is [out of …

refactor(multi-env): move getActiveEnv to environmentManager so we can mock in UT

---

packages/fx-core/src/core/index.ts
packages/fx-core/src/core/middleware/projectSettingsWriter.ts
packages/fx-core/tests/core/hooks.test.ts

Offline discuss with @jayzhang, this is a bug of ProjectSettingsWriter.  ProjectSettingsReader/ProjectSettingsWriter should be consistent to read/write from `ctx` instead of `solutionContext`

fix(core): projectSettingsWriter should read from ctx

---

packages/api/review/teamsfx-api.api.md
packages/api/src/types.ts
packages/fx-core/src/core/middleware/envInfoLoader.ts
packages/fx-core/src/plugins/solution/fx-solution/arm.ts
packages/fx-core/src/plugins/solution/fx-solution/solution.ts
packages/fx-core/src/plugins/solution/fx-solution/v2/createEnv.ts

**Bug**: use the active env name in context as the target env when copy bicep parameter JSON file.
**Expected**: should use the input new env name as the target env name when copy bicep parameter JSON file.

fix(multi-env): incorrect target env name when copy bicep parameter file

---

packages/cli/src/cmds/env.ts
packages/cli/tests/unit/cmds/env.tests.ts

- add `teamsfx env` command to show current active env name.
- add test cases
`teamsfx env` will show active env and the `--help` parameter also works.
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/10920600

feat(multi-env): add "teamsfx env" command

---

packages/cli/src/activate.ts

- Set the active env when activating, similar to the vscode extension, so that core can fallback to using currrent active env when not specified
For example, the provision command will use the current active env

feat(multi-env): read active env for all cmds

---

packages/fx-core/src/index.ts
packages/vscode-extension/package.json
packages/vscode-extension/src/constants.ts
packages/vscode-extension/src/envTree.ts
packages/vscode-extension/src/handlers.ts
packages/vscode-extension/src/resources/Strings.json

Add `local` to the environment tree view. It supports to 
* view the localSettings.json
* It can't be activated.

chore(multi-env): refine the environment view

---

packages/fx-core/src/common/localSettingsProvider.ts

When scaffold a bot only project, toolkit should also scaffold `auth` related config in local debug config file (`localSettings.json`).

fix(multi-env): missing auth section when scaffold bot only project

---

packages/cli/src/cmds/env.ts
packages/cli/src/helpParamGenerator.ts
packages/cli/tests/unit/cmds/env.tests.ts

- add `teamsfx env add <name> [--env sourceEnv]` command. If --env is not specified, it will use current active env.
- add test cases (the test cases might be somewhat too long, so I split them into 3 commits for easier reading)
The --help output
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/10921113

feat(multi-env): add "teamsfx env add" command in CLI

---

packages/vscode-extension/src/commonlib/azureLogin.ts
packages/vscode-extension/src/envTree.ts
packages/vscode-extension/src/utils/commonUtils.ts

If the env has already been provisioned, then the resource group and sub info will be showed in the tree view:

chore(multi-env): show sub and resource group in env tree

---

packages/fx-core/src/core/index.ts

These functions do not read or write configuration files, so remove concurrent locker to avoid errors when used on tree view

perf(collaboration): remove unnecessary concurrent locker

---

packages/vscode-extension/package.json

For webpacked code, there's generated soucemap. In theory, that's enough for debug locally. 
I compared our soucemaps with other project and didn't find any difference.
So use this way as a workaround for now.

chore: update script to fix webview debug issue temporarily

---

packages/api/review/teamsfx-api.api.md
packages/api/src/types.ts
packages/cli/src/cmds/provision.ts
packages/fx-core/src/plugins/solution/fx-solution/commonQuestions.ts

- add resource group argument for provision command
- change get resource group logic in core
It will use the specified rg without asking user
It will ask user if rg is not specified

feat(multi-env): add --resource-group argument for provision command in CLI

---

packages/cli/src/cmds/env.ts
packages/cli/src/helpParamGenerator.ts

The design is `teamsfx env activate <name>`.

fix(multi-env): fix activate command argument format

---

packages/fx-core/src/plugins/solution/fx-solution/ResourcePluginContainer.ts
packages/fx-core/tests/plugins/solution/solution.provision.test.ts

closes https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_sprints/taskboard/Teams%20Extensibility%20E2E%20Team/Microsoft%20Teams%20Extensibility/CY21-9.1?workitem=10942102

fix(solution): pass the right plugin v2 name

---

packages/fx-core/src/plugins/resource/bot/index.ts

Due to recent api/ 's change bot plugin has duplicated error shown to user, for api now will join the inner error msg, so remove it from plugin now.

fix(bot): fix duplicate detail errors

---

packages/vscode-extension/src/accountTree.ts
packages/vscode-extension/src/handlers.ts

- Automatically refresh env tree view when sign in/out with Azure account
- Fix bug: missing `await` when invoke `registerEnvTreeHandler()`

chore(multi-emv): refresh env tree on azure account status changed

---

packages/fx-core/src/core/environment.ts
packages/fx-core/tests/core/environment.test.ts
packages/vscode-extension/src/handlers.ts

Use vscode API to monitor the file changes and refresh env tree view when env config file is added or deleted.

fix(multi-env): refresh env tree if env config added/deleted

---

packages/vscode-extension/src/handlers.ts

This bug is introduced by my last PR: https://github.com/OfficeDev/TeamsFx/pull/2367, and add back the logic `registerEnvTreeHandler` when new environment is created.

fix(multi-env): refresh env tree when new env created

---

packages/cli/src/cmds/publish.ts

we should use `inputs.projectRoot` rather than `inputs.folder` because `argsToInputs` has already converted inputs.folder to inputs.projectPath.
This bug should also exist in old versions, but will only cause `AzureAccountManager.setSubscription()`. not called before calling core's `publishApplication`.
But in multienv case, it will cause active environment not set.
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/10950624/

fix(cli): fix rootFolder undefined when publishing

---

packages/fx-core/src/core/index.ts
packages/fx-core/src/core/middleware/envInfoWriter.ts

The root cause is the hooks init step occurs before the extension activate step, so the process env is not ready if using the decorator like `EnvInfoWriterMW(isMultiEnvEnabled())`, as `isMultiEnvEnabled()` will return `false` before process env is set by extension activate.

fix(multi-env): process env is not ready when hooks init

---

packages/fx-core/src/core/middleware/envInfoLoader.ts
packages/fx-core/src/plugins/solution/fx-solution/solution.ts
packages/fx-core/src/plugins/solution/fx-solution/v2/provision.ts

- If the user presses ESC to cancel the select-env dialog, it will not throw system errors.

fix(multi-env): handle cancel error when selecting env

---

packages/fx-core/src/core/middleware/envInfoLoader.ts

- env loader should test `inputs.ignoreEnvInfo` to determine whether to skip loading env
tested local debug

fix(multi-env): fix local debug NonActiveEnvError

---

packages/vscode-extension/src/accountTree.ts

Fix sideloading status tree view item - automatically hide the status if refresh passed (user has sideloading permission now).

fix: reset sideloading status if refresh passed

---

packages/api/review/teamsfx-api.api.md
packages/api/src/types.ts
packages/fx-core/src/core/middleware/envInfoLoader.ts
packages/vscode-extension/src/handlers.ts

This is part of a bigger refactor, which is to unify skip logic for `EnvInfoLoaderMW`. Only `skip` argument and  `inputs.skipEnvInfo` will remain.
- remove input.askEnvSelect to prevent code like `input.askEnvSelect` scattered everywhere
- for extension, as the concept of activeEnv is removed. Every lifecycle that requires env will ask from the users. So check platform in envInfoLoader to determine whether to ask env
Tested all these button, local debug and launch remote
The operations that will ask env are:
- Provision in the cloud
- Validate manifest file
- Zip teams metadata package
- Deploy to the cloud
- Publish to Teams
- Remote launch
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/10896919

refactor(multi-env): remove inputs.askEnvSelect

---

packages/api/review/teamsfx-api.api.md
packages/api/src/types.ts
packages/cli/src/cmds/preview/commonUtils.ts
packages/cli/src/cmds/preview/constants.ts
packages/cli/src/cmds/preview/preview.ts
packages/cli/src/utils.ts
packages/fx-core/src/core/middleware/envInfoLoader.ts
packages/fx-core/src/core/middleware/projectSettingsLoader.ts
packages/fx-core/tests/core/hooks.test.ts

- remove `ignoreTypeCheck`. Discussed with @jayzhang that this is not used anymore.
- remove `previewType` because it is only used by CLI preview to determine whether to skip loading env. This functionality is the same as `ignoreEnvInfo`, so just reuse it.
- fix bugs in remote preview
tested CLI local/remote preview

refactor(multi-env): unify skip flags for EnvInfoLoaderMW

---

packages/cli/tests/unit/cmds/env.tests.ts

- Fixes the `prints all env names` unit test under to use OS-independent line separators. (The test fails on Windows.)

fix(multi-env): fix 'prints all env names' unit test to use os.EOL

---

packages/fx-core/src/core/middleware/envInfoLoader.ts
packages/fx-core/tests/core/environment.test.ts
packages/fx-core/tests/core/hooks.test.ts

- when skip is set, EnvInfo should not be loaded
- add UT for skip logic
- add a test case for NonExistEnvError to prevent the coverage drop because after the bugfix, this exception is not thrown in the happy path case.

test(multi-env): add EnvInfoLoader UT for skip logic and fix a bug

---

packages/cli/src/activate.ts
packages/cli/src/cmds/env.ts
packages/cli/tests/e2e/multienv/TestRemoteHappyPath.tests.ts
packages/cli/tests/e2e/multienv/TestRemoteHappyPathSPFx.tests.ts
packages/cli/tests/unit/cmds/env.tests.ts

- remove CLI commands: `teamsfx env`, `teamsfx env activate`
- remove active env mark from `teamsfx env list`
- fix unit test and e2e test
e2e test result: https://github.com/OfficeDev/TeamsFx/runs/3717614569?check_suite_focus=true
interactive mode will be in the next pr
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/11012678

chore(multi-env): remove active env from CLI

---

packages/cli/src/cmds/preview/commonUtils.ts
packages/cli/src/cmds/preview/preview.ts

Adds a new `--browser-arg` option for the `preview` command to pass a user-supplied argument to the selected browser.
* Private session:
* `teamsfx preview --local --browser edge --browser-arg="--inprivate"`
* `teamsfx preview --local --browser chrome --browser-arg="--incognito"`
* Guest session:
* `teamsfx preview --local --browser edge --browser-arg="--guest"`
* `teamsfx preview --local --browser chrome --browser-arg="--guest"`
* Select a named profile:
* `teamsfx preview --local --browser edge --browser-arg="--profile-directory=Profile 2"`
* `teamsfx preview --local --browser chrome --browser-arg="--profile-directory=Profile 1"`
* Pass multiple arguments:
* `teamsfx preview --local --browser "chrome" --browser-arg="--incognito" --browser-arg="--start-fullscreen"`
Fixes issue #1772.
(A …

feat(cli-preview): add browser argument option to preview command

---

packages/fx-core/src/core/index.ts
packages/fx-core/src/core/middleware/envInfoWriter.ts

Decrypting and local debugging will cause `profile.dev.json` to be cleared. The root cause is `ctx.envInfo` is set to an empty value because `EnvInfoLoaderMW` is skipped for these stages, but `EnvInfoWriteMW` is not skipped.
Tested local debug and decrypt with and without feature flags.
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/11013525

fix(multi-env): fix a bug that cause profile.dev.json to be cleared

---

packages/cli/src/activate.ts
packages/cli/src/constants.ts
packages/cli/src/helpParamGenerator.ts
packages/fx-core/src/core/middleware/envInfoLoader.ts
packages/fx-core/src/index.ts
packages/fx-core/tests/core/hooks.test.ts

- In CLI, if `--env` is not specified, it will ask from user. This behavior is the same as vscode extension.
- Remove related unit test code.
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/11012678

chore(multi-env): remove active env from CLI part 2

---

packages/cli/src/commonlib/codeFlowLogin.ts
packages/vscode-extension/src/commonlib/codeFlowLogin.ts

1. Fix when user already gets graph token and app studio token, and then logout app studio, user can still get graph token bug.
2. Long term: merge graph, app studio into one m365 provider.

fix: multi m365 login

---

packages/vscode-extension/package-lock.json
packages/vscode-extension/package.json
packages/vscode-extension/src/commonlib/telemetry.ts
packages/vscode-extension/src/utils/commonUtils.ts

chore: support telemetry test
To support telemetry UITEST we need to send telemetry into a log file instead of sending to AI. The test need to set a env variable  (TEAMSFX_TELEMETRY_TEST) to enable it.
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/10676875

chore: support telemetry test

---

packages/vscode-extension/.prettierignore
packages/vscode-extension/syntaxes/teamsfx-toolkit-output.tmLanguage

Update language grammar to support multi-line message matching.

fix(vsc): multiline error not colorized

---

packages/vscode-extension/src/telemetry/extTelemetryEvents.ts
packages/vscode-extension/src/utils/migrateV1.ts

Remove open-v1-project telemetry to avoid send telemetry when open vscode

fix(migrate-v1): remove open v1 project telemetry

---

packages/fx-core/src/common/telemetry.ts
packages/fx-core/src/plugins/solution/fx-solution/commonQuestions.ts

- add telemetry events `check-resource-group-start` and `check-resource-group` to track how the user customizes the resource group when provision
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/11012613

chore(multi-env): telemetry for resource group when provision

---

packages/fx-core/src/core/middleware/envInfoLoader.ts

The root cause of this bug is that, the closure variable `skip` is changed by the last execution of `EnvInfoLoader`. The change is to keep closure variable unchanged.
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/11045095

fix(multi-env): closure variable is changed unexpectedly

---

packages/api/review/teamsfx-api.api.md
packages/api/src/types.ts
packages/fx-core/src/plugins/resource/appstudio/plugin.ts
packages/fx-core/src/plugins/resource/localdebug/index.ts
packages/fx-core/src/plugins/resource/utils4v2.ts
packages/fx-core/src/plugins/solution/fx-solution/solution.ts
packages/fx-core/src/plugins/solution/fx-solution/v2/executeUserTask.ts
packages/fx-core/src/plugins/solution/fx-solution/v2/scaffolding.ts
packages/fx-core/tests/plugins/resource/apiv2/utils4v2.test.ts
packages/vscode-extension/src/debug/commonUtils.ts

`localSettings.json` didn't get updated when add bot capability.
The updated `localSettings` wasn't synced back to context when we update the `localSettings.json` for adding capability, and finaly the `localSettingsWriterMW` will overwrite the file with an old `localSettings` object.

fix(local-debug): missing bot config in localSetings when add bot capability

---

packages/vscode-extension/src/commonlib/codeFlowLogin.ts

1. Fix logging notify logic, when signing in show singing status in tree view. (Cli does not need notify logic)

fix: logging status notify

---

packages/api/review/teamsfx-api.api.md
packages/api/src/schemas/index.ts
packages/fx-core/src/common/telemetry.ts
packages/fx-core/src/common/tools.ts
packages/fx-core/src/plugins/solution/fx-solution/solution.ts
packages/fx-core/tests/core/tools.test.ts

- send envConfig file with unknown properties and all values redacted when provisioning
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/11012613

chore(multi-env): add env config telemetry

---

packages/fx-core/package.json
packages/fx-core/scripts/download-templates-zip.js

In current CD pipeline, template-tags.txt is updated with latest template version. When packaging extension, template-tags.txt is downloaded and parsed so that fx-core gets the latest template version. 
The CD pipeline both updates and consumes the txt file. We might download the txt before the updated txt takes effect and we eventually get older version templates.
This PR is to get latest template version from git tag rather than the txt file.

chore: decouple CD pipeline with template-tags.txt

---

packages/fx-core/src/core/index.ts

Bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/11643349

fix(multi-env): no need refresh env tree when user cancelled create env copy

---

packages/vscode-extension/src/handlers.ts

bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/11643501/

fix(multi-env): env tree didn't refresh automatically when env config is renamed

---

packages/api/review/teamsfx-api.api.md
packages/api/src/schemas/envConfig.json
packages/api/src/schemas/envConfig.ts
packages/fx-core/src/core/environment.ts
packages/fx-core/src/core/middleware/projectMigrator.ts
packages/fx-core/src/core/tools.ts
packages/fx-core/src/plugins/resource/appstudio/constants.ts
packages/fx-core/templates/plugins/resource/spfx/solution/manifest_multi_env.json
packages/fx-core/tests/core/environment.test.ts
packages/fx-core/tests/core/hooks.test.ts
packages/fx-core/tests/plugins/resource/apiv2/utils4v2.test.ts
packages/fx-core/tests/plugins/resource/appstudio/spfx-resources/appPackage/manifest.template.json
packages/fx-core/tests/plugins/solution/solution.provision.test.ts
packages/fx-core/tests/plugins/solution/solution.publish.test.ts

Bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/11033171
Update env config schema with root level description and remove the original `description` and `values` for manifest section.
sample env config:
```json
{
"$schema": "https://raw.githubusercontent.com/OfficeDev/TeamsFx/dev/packages/api/src/schemas/envConfig.json",
"description": "You can customize the TeamsFx config for different environments. Visit https://aka.ms/teamsfx-config to learn more about this.",
"manifest": {
"appName": {
"short": "qinezh1011",
"full": "Full name for qinezh1011"
}
}
}
```

chore(multi-env): update env config schema with root level description

---

packages/fx-core/src/core/question.ts

Bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/11645755

fix(multi-env): validate the length of environment name

---

packages/fx-core/src/plugins/resource/bot/deployMgr.ts
packages/fx-core/src/plugins/resource/frontend/ops/deploy.ts
packages/fx-core/src/plugins/resource/function/ops/deploy.ts

Plugin skips deployment if no code change detected. When ARM support or multiple environment enabled, plugin might wrongly skip necessary deployment. This PR is to workaround these cases and next step we will figure out an ultimate solution.

fix: always deploy when ARM or multi-env enabled

---

packages/vscode-extension/src/handlers.ts
packages/vscode-extension/src/telemetry/extTelemetry.ts
packages/vscode-extension/src/utils/commonUtils.ts

- when multi-env is enabled, the appid property is not sent.
- Only affect cases when multi-env is enabled
tested provision telemetry with/without feature flag

fix(telemetry): send appid for telemetry events

---

packages/cli/src/cmds/preview/commonUtils.ts
packages/cli/src/cmds/preview/preview.ts
packages/vscode-extension/src/debug/commonUtils.ts
packages/vscode-extension/src/debug/teamsfxTaskProvider.ts

To fix https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/11033697.
Avoid calling getLocalDebugEnvs every time when getting frontend/backend/auth/bot envs.

fix(local-debug): remove duplicate getLocalDebugEnvs

---

packages/vscode-extension/src/handlers.ts

If we open a old project with invalid config, then warning message of collaborator list will not show:
After fix:

fix(collaboration): warning message not show when list failed

---

packages/fx-core/src/core/index.ts
packages/fx-core/src/plugins/resource/localdebug/constants.ts
packages/fx-core/src/plugins/resource/localdebug/index.ts
packages/fx-core/src/plugins/resource/localdebug/localEnv.ts
packages/fx-core/src/plugins/resource/localdebug/localEnvMulti.ts
packages/fx-core/tests/plugins/resource/localdebug/unit/index.test.ts
packages/fx-core/tests/plugins/resource/localdebug/unit/localEnvMulti.test.ts

This is a preparation for customized local debug, which is to generate `.env.teamsfx.local` for each component, then user can partial launch local service(s) or add customized environment variables.
- Only enabled for multi-env
- Add `.env.teamsfx.local` to git ignore
- Add unit tests

chore: generate .env.teamsfx.local for multienv local debug

---

packages/api/review/teamsfx-api.api.md
packages/api/src/constants.ts
packages/cli/src/cmds/resource.ts
packages/cli/src/utils.ts
packages/cli/tests/e2e/commonUtils.ts
packages/cli/tests/e2e/multienv/TestRemoteHappyPath.tests.ts
packages/fx-core/src/common/telemetry.ts
packages/fx-core/src/core/environment.ts
packages/fx-core/src/core/index.ts
packages/fx-core/src/core/middleware/envInfoWriter.ts
packages/fx-core/src/core/middleware/projectMigrator.ts
packages/fx-core/src/core/middleware/projectUpgrader.ts
packages/fx-core/src/plugins/resource/aad/constants.ts
packages/fx-core/src/plugins/resource/aad/utils/common.ts
packages/fx-core/src/plugins/solution/fx-solution/commonQuestions.ts
packages/fx-core/tests/core/environment.test.ts
packages/fx-core/tests/core/middleware/EnvInfoMW.test.ts
packages/vscode-extension/src/commonlib/common/constant.ts
packages/vscode-extension/src/error.ts
packages/vscode-extension/src/extension.ts
packages/vscode-extension/src/handlers.ts
packages/vscode-extension/src/utils/commonUtils.ts

PR changes:
1. Rename the folder `publishProfiles` to `states`.
2. Rename the publish profile file `profile.<env>.json` to `state.<env>.json`.
3. Rename some variables from `profile` to `state`. 
Please note, the renaming of `envInfo.profile` will be covered in another separated PR.
work item: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/11012592

chore(multi-env): rename profile to state

---

packages/vscode-extension/src/controls/webviewPanel.ts

Issue:
Some telemetry events from quick start page don't have a correlation id like create-project, download-sample
ADO item: 
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/11000095?src=WorkItemMention&src-action=artifact_link

fix: some telemetry events don't have correlation id

---

.github/workflows/unit-test.yml
packages/fx-core/src/common/tools.ts
packages/fx-core/src/core/middleware/projectUpgrader.ts
packages/fx-core/tests/core/core.test.ts
packages/fx-core/tests/core/environment.test.ts
packages/fx-core/tests/core/hooks.test.ts
packages/fx-core/tests/core/localSettings.test.ts

The whole plan is to make the unit test support both multi-env enabled/disabled cases. And then run the unit test twice: with TEAMSFX_INSIDER_PREVIEW and without.
- fix the unit test so the it can pass with multi-env enabled in fx-core
- use deepEqual to compare JSON because the key order of JSON.stringify is not [in any particular order](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify)
- throw the error instead of `assert.fail` so we can know the actual stack and error message when the test fails 
- fix a projectMigrator bug
- fix loop import in core

chore(multi-env): core unittest supports multi-env

---

packages/cli/src/cmds/preview/depsChecker/funcToolChecker.ts
packages/vscode-extension/src/debug/depsChecker/funcToolChecker.ts

- Expose bin folder so that `func` can be used directly from cmd
- Delete `func.ps1` for portable installation as well
@a1exwang @meifans - please help review

chore: prepare func checker for custom local debug

---

.github/workflows/unit-test.yml
packages/fx-core/tests/plugins/resource/aad/helper.ts
packages/fx-core/tests/plugins/resource/aad/unit/index.test.ts
packages/fx-core/tests/plugins/resource/simpleauth/helper.ts
packages/fx-core/tests/plugins/resource/simpleauth/unit/index.test.ts

The test will run twice, one with TEAMSFX_INSIDER_PREVIEW and one without it. This PR fixes the cases with TEAMSFX_INSIDER_PREVIEW=true

test(multi-env): make unit test of aad and simpleauth plugins support multi-env

---

packages/fx-core/src/plugins/resource/localdebug/index.ts

Move initial .env.teamsfx.local to template (template change will be another PR) to avoid conflict with component plugins.

fix: move .env.teamsfx.local to template

---

.github/workflows/unit-test.yml
packages/fx-core/tests/plugins/resource/frontend/helper.ts
packages/fx-core/tests/plugins/resource/frontend/unit/config.test.ts
packages/fx-core/tests/plugins/resource/frontend/unit/index.test.ts

The unit test will run twice, one with TEAMSFX_INSIDER_PREVIEW=true and one without it. This PR make frontend plugin to support both cases.
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/12217265

test: make frontend plugin ut support insider preview

---

packages/cli/package-lock.json
packages/cli/package.json
packages/vscode-extension/package-lock.json
packages/vscode-extension/package.json

bump cli version from 0.7.0 to 0.7.1 since we cannot publish 0.7.0 for the second time.
- @microsoft/teamsfx-cli: 0.7.1-rc.0 => 0.7.1
- ms-teams-vscode-extension: 2.8.0-rc.4 => 2.8.0

chore(release): bump cli for repub

---

packages/fx-core/src/plugins/resource/localdebug/launch.ts

VSCode sort  dropdown items with group name.  Refer to: https://code.visualstudio.com/Docs/editor/debugging

fix: put teams workbench in front

---

packages/vscode-extension/src/qm/vsc_ui.ts

ADO:
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/12470841
Issue:
click ok button for single select control doesn't work
Root cause:
This issue is introduced by https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/11033114. when there's no valid selection for matching, we shouldn't select the first option by default. It's weird that when using enter key, the selected item is currently active item, but when using ok button, the selected item is null. So I assign active item to selected item before onDidAccept event to fix the issue
E2E TEST: Only affect UI

fix: ok button for single select doesn't work

---

packages/fx-core/tests/common/templateFetch.test.ts

When setting TEAMSFX_TEMPLATE_PRERELEASE=alpha, scaffold lib always get template with version 0.0.0-alpha, which causes ut fail.

test(scaffold): template ut fails when set preRelease env variable

---

packages/fx-core/src/plugins/resource/appstudio/index.ts
packages/fx-core/src/plugins/resource/appstudio/plugin.ts
packages/fx-core/src/plugins/resource/appstudio/utils/telemetry.ts
packages/fx-core/src/plugins/resource/appstudio/utils/utils.ts

For multi-env, users may add some customized placeholders in manifest template, in a format of {{config.manifest.xx}}
Add these keys to telemetry properties to give more insights.

chore: add customized manifest keys for multi-env telemetry

---

packages/vscode-extension/src/accountTree.ts
packages/vscode-extension/src/handlers.ts
packages/vscode-extension/src/treeview/commandsTreeViewProvider.ts

ADO: 
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/12401147
Issue:
the signInAzure(M365)Callback will be triggered when user click related tree item even if user already sign in. This will introduce performance issue on collaborator feature. 
E2E TEST: Only affect UI

fix: click m365 account will trigger sign in logic

---

packages/cli/src/cmds/env.ts

- `teamsfx env` requires following actions because there is no active env to show
- remove active env from cli help
E2E TEST: https://github.com/OfficeDev/TeamsFx/blob/f6f87441aa4176fabddb2feb3a60bd5983d971dc/packages/cli/tests/e2e/multienv/TestRemoteHappyPath.tests.ts#L38

fix: remove active env from cli help

---

packages/fx-core/src/core/environment.ts
packages/fx-core/tests/core/environment.test.ts
packages/fx-core/tests/core/middleware/EnvInfoMW.test.ts

In current multi-env design, user may need to config some secret value in the `config.<env>.json` file, such as AAD client secret, bot app secret, as well as some other user customized secret data.
To prevent check-in the credential into the project's repo, we are now supporting resolving the credential in env config from environment variables, you can define your config like this:
```json
{
"clientId": "{{$env.my_env_name}}"
}
```

chore: support resolving secret value from environment variables

---

packages/cli/src/cmds/config.ts
packages/cli/src/error.ts
packages/cli/src/utils.ts
packages/cli/tests/unit/cmds/config.tests.ts
packages/cli/tests/unit/utils.tests.ts

```
>  teamsfx config set key value --env dev                                   15:32:33
(✖) [TeamsfxCLI.UserdataNotFound]: The userdata file ".fx/states/dev.userdata" is not found. Please try to provision in the "dev" envrionment
> teamsfx config get --env dev                                             15:35:22
{}
(✖) [TeamsfxCLI.UserdataNotFound]: The userdata file ".fx/states/dev.userdata" is not found. Please try to provision in the "dev" envrionment
```
E2E TEST: https://github.com/OfficeDev/TeamsFx/blob/84b4cbf2229fc06e97b411bd15655f5247e66626/packages/cli/tests/e2e/multienv/TestRemoteHappyPath.tests.ts#L38

fix(multi-env): make error message clear when running teamsfx config before provision

---

packages/cli/src/cmds/env.ts

`teamsfx env list` previously required `action` option be set, but apparently there is no `action` option in the `list` command.
Use `<>` instead of `[]` to make the `action` option in `teamsfx env` command a required option. This aligns with other commands like `teamsfx config` and `teamsfx permission` 
E2E TEST https://github.com/OfficeDev/TeamsFx/blob/d3ab1f1be30620255343538fb1839bec273613f1/packages/cli/tests/e2e/multienv/TestRemoteHappyPath.tests.ts#L38
e2e test result: https://github.com/OfficeDev/TeamsFx/actions/runs/1424222811

fix(multi-env): fix teamsfx env list and teamsfx env add

---

packages/fx-core/src/common/constants.ts
packages/fx-core/src/core/index.ts

Add feature flag for further development on VS extension calling CLI.
closes https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_sprints/taskboard/Teams%20Extensibility%20E2E%20Team/Microsoft%20Teams%20Extensibility/CY21-11.1?workitem=12525135

chore(core): add feature flag for vs calling cli

---

packages/sdk/package.json
packages/sdk/rollup.base.config.js
templates/tab/js/default/package.json
templates/tab/ts/default/package.json

Related bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/12514687

chore(sdk): move teams-js sdk to peer dependency

---

packages/cli/src/utils.ts
packages/cli/tests/unit/utils.tests.ts
packages/vscode-extension/src/utils/commonUtils.ts
packages/vscode-extension/test/unit/extension/commonUtils.test.ts

When users enable `TEAMSFX_INSIDER_PREVIEW` and open an old project, the `project-id` property in telemetry is not correctly sent. This is because `getProjectId()` will incorrectly assume this is a new project and retrieve `project-id` from the new location.
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/12525703
E2E TESTS: https://github.com/OfficeDev/TeamsFx/blob/dev/packages/cli/tests/e2e/multienv/TestRemoteHappyPath.tests.ts

fix(multi-env): send correct project id before migration

---

packages/fx-core/src/plugins/resource/appstudio/plugin.ts

feat: make manifest preview file as readonly

---

packages/fx-core/src/core/question.ts
packages/fx-core/tests/core/other.test.ts

ADO:
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/12517688
before:
after:
E2E TEST: only UI affected

fix: block user from wrong app name

---

packages/fx-core/templates/plugins/resource/bot/bicep/botProvision.template.bicep
packages/fx-core/templates/plugins/resource/function/bicep/functionProvision.template.bicep
packages/fx-core/templates/plugins/resource/simpleauth/bicep/simpleAuthProvision.template.v2.bicep
packages/fx-core/tests/plugins/resource/bot/unit/expectedBicepFiles/botProvision.result.bicep
packages/fx-core/tests/plugins/resource/function/unit/expectedBicepFiles/functionProvision.result.bicep
packages/fx-core/tests/plugins/resource/simpleauth/unit/expectedBicepFiles/simpleAuthProvision.result.v2.bicep

Due to a service issue of Azure Web App / Function, we cannot config keyvault reference identity via Azure Web App / Function config API. We need to add keyvault reference identity in advance so users can adopt the key vault feature smoothly. @formulahendry will work with Azure support team on the issue we found.
Changes:
1. Use latest service API version
2. Config Azure Web App / Function to use user assigned identity to access keyvault

chore: add keyvault reference identity for keyvault support

---

packages/fx-core/src/core/middleware/projectMigrator.ts
packages/fx-core/src/plugins/resource/appstudio/plugin.ts
packages/fx-core/src/plugins/resource/appstudio/utils/utils.ts

1) Generate local manifest template from manifest.source.json, rather than creating a new one.
2) get local app name

fix: local manifest migration

---

packages/fx-core/src/plugins/solution/fx-solution/commonQuestions.ts
packages/fx-core/src/plugins/solution/fx-solution/constants.ts
packages/fx-core/tests/plugins/solution/solution.provision.test.ts

When selecting resource group before provision, and if the user does not have permission to acess current selected subscription, it will display a more user friendly error message.
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/12545873

fix(multi-env): improve resource group permission error message

---

packages/fx-core/src/plugins/resource/localdebug/index.ts
packages/fx-core/src/plugins/resource/localdebug/util/localService.ts
packages/fx-core/tests/plugins/resource/localdebug/unit/index.test.ts
packages/fx-core/tests/plugins/resource/localdebug/unit/localService.test.ts

Make `getLocalDebugEnvs` a read-only operation so it could be called before `localDebug`.
(This fixes ADO bug 12514524)

fix: make getLocalDebugEnvs readonly operation

---

packages/fx-core/tests/plugins/resource/localdebug/unit/index.test.ts

This is the prereqs of
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/12586858

chore: localdebug plugin to check insider flag instead of mocking it

---

packages/fx-core/src/core/question.ts

ADO:
BUG 12606780
Before:
after:

fix: unexpected ux change for create from sample

---

templates/function-base/js/default/package.json
templates/function-base/ts/default/package.json
templates/tab/js/default/package.json
templates/tab/ts/default/package.json

Explicitly add `@microsoft/microsoft-graph-client` as dependency because SDK makes it as peer dependency.

chore(template): add graph client as dependency

---

packages/cli/src/commonlib/sharepointLogin.ts
packages/vscode-extension/src/commonlib/sharepointLogin.ts

https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/12587039?src=WorkItemMention&src-action=artifact_link
Root cause:
The scope is not updated if sharepoint.getAccessToken() called before user switch account.
E2E TEST: the token provider implementation for e2e is not the same with product code

fix: spfx deploy cause 401 error

---

packages/cli/src/commonlib/sharepointLogin.ts
packages/cli/src/commonlib/sharepointLoginUserPassword.ts
packages/vscode-extension/src/commonlib/sharepointLogin.ts

- Do not set axios.default because this will affect all axios instances globally
- SPFx sets a global `Authorization` headers, so when bicepChecker calls GitHub API (this is public API, and it does not need auth), it includes an Authorization header. GitHub will treat this as a invalid PAT and return a 401 error
- This will only happen in release package because SPFx login is in `vscode-extension` package and bicepChecker is in `core` package. After packaging, webpack will merge `axios` package in `vscode-extension` and `core` into one

fix: fix bicepChecker 401 error

---

packages/vscode-extension/src/extension.ts

Fix upgrade [bug 12554464 : Do not know what to do for original local debug resources ](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_dashboards/dashboard/8bb5e24b-9df9-44a7-b32d-6f073b8ce2f8).
**Mitigation**: 
As we already backed up original local debug config in `.backup` folder, they can check the previous local debug info in related config files (`env.default.json`, `local.env`, `default.userdata`), and clean up manually if needed. For secret data, we also support codelens to let user retrieve the previous app secret, e.g. AAD client secret, SQL password, etc.

chore(upgrade): enable codelens to view userdata in backup folder

---

packages/fx-core/src/plugins/solution/fx-solution/utils/depsChecker/bicepChecker.ts

The bug is: when it fails to write to `.fx/bin/bicep/bicep` (e.g. no permission or no space), the provision will be stuck forever.
Remove this defensive `writer.end()` because it will stuck on error
This is a possible node.js bug: https://github.com/nodejs/node/issues/40851

fix: bicepChecker will stuck on write error

---

packages/fx-core/src/plugins/resource/appstudio/errors.ts
packages/fx-core/src/plugins/resource/appstudio/index.ts
packages/fx-core/src/plugins/resource/appstudio/plugin.ts
packages/fx-core/src/plugins/resource/appstudio/utils/telemetry.ts
packages/vscode-extension/package.json
packages/vscode-extension/src/codeLensProvider.ts
packages/vscode-extension/src/extension.ts
packages/vscode-extension/src/handlers.ts
packages/vscode-extension/src/telemetry/extTelemetryEvents.ts

User can update manifest file manually from editor context menu/preview file codelens/command palette.
For the former two scenarios, update current manifest. For  command palette, ask user to select env to update

feat: allow user to manually update manifest file

---

packages/fx-core/src/plugins/solution/fx-solution/utils/depsChecker/bicepChecker.ts
packages/fx-core/src/plugins/solution/fx-solution/utils/depsChecker/common.ts

- Unauthenticated GitHub API call has a limit of 60 requests per hour per IP. It is easily hit. If the API fails, fallback to use a hard-coded version of bicep
Tested by changing hosts file

fix(env-checker): fallback to use hardcoded bicep version if Github API fails

---

packages/vscode-extension/src/envTree.ts
packages/vscode-extension/src/resources/Strings.json

Remove warning nodes under env node, and show warning messages when user hover mouse to the env node.

chore(multi-env): refine account warning UI in tree view

---

packages/api/src/error.ts
packages/fx-core/src/core/error.ts
packages/sdk/README.md

To apply the wording changes from https://github.com/OfficeDev/TeamsFx/pull/2915
The migration commands part is already released in https://github.com/OfficeDev/TeamsFx/pull/2925, and this PR is for the remaining part.

chore: adjust wording

---

packages/fx-core/src/plugins/resource/frontend/blazor/enum.ts
packages/fx-core/src/plugins/resource/frontend/blazor/plugin.ts
packages/fx-core/src/plugins/resource/frontend/index.ts
packages/fx-core/src/plugins/resource/frontend/resources/errors.ts
packages/fx-core/src/plugins/resource/frontend/utils/telemetry-helper.ts

For blazor scenario, we do scaffolding in VS extension, so we don't need to implement `generateArmTemplate` in blazor plugin, just update the arm bicep files in scaffold templates.
E2E TEST: https://github.com/OfficeDev/TeamsFx/blob/bb110600e8feccf400fb050598f7ff7b4e62d32f/packages/cli/tests/e2e/blazor/TestDeployBlazor.tests.ts#L6

feat(blazor): support arm

---

packages/cli/src/constants.ts
packages/cli/src/utils.ts
packages/fx-core/src/common/constants.ts
packages/fx-core/src/common/tools.ts
packages/vscode-extension/package.json
packages/vscode-extension/src/constants.ts
packages/vscode-extension/src/utils/commonUtils.ts

This is a workaround only for upgrade failure and plan to be removed soon. As for the accurate date to remove it, it will depend on the upgrade failure rate from BI report.

chore(upgrade): add extension setting as workaround for upgrade failure

---

packages/vscode-extension/.vscode/extensions.json

Remove the invalid recommended vscode extension to avoid warning every time opening the project:

chore: remove invalid recommended extension

---

packages/vscode-extension/src/handlers.ts

Skip to refresh env tree when provision cancelled.
work item: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/12664126
E2E TEST: UI changes.

perf(env-tree): no need to refresh env tree when provision cancelled

---

packages/fx-core/src/common/tools.ts
packages/fx-core/src/core/index.ts

If sample app exists, will append suffix like <sample name>_1, <sample name>_2, ...
E2E TEST: hotfix, will add later

fix: download sample twice will failed with progress bar hang

---

packages/vscode-extension/src/envTree.ts

Display `local` in env tree no matter the `localSettings.json` exist or not.
Bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/12664790/
E2E TEST: only affect UI

fix: always show local in env tree

---

packages/vscode-extension/src/migration/migrationHandler.ts
packages/vscode-extension/src/migration/migrationTool/replaceSDK.ts
packages/vscode-extension/src/migration/migrationTool/ts/replaceTsSDK.ts
packages/vscode-extension/test/unit/migration/data/js/others/replace-without-entire-import.input.js
packages/vscode-extension/test/unit/migration/data/js/others/replace-without-entire-import.output.js
packages/vscode-extension/test/unit/migration/data/ts/others/replace-without-entire-import.input.ts
packages/vscode-extension/test/unit/migration/data/ts/others/replace-without-entire-import.output.ts

Fix [ADO 12577791](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/12577791).
If there is no import `microsoftTeams` declaration in the file but there are `microsoftTeams` references, then the references will also be migrated.
E2E TEST: AzureAppScaffold

fix(migration): migrate without import

---

packages/fx-core/src/plugins/resource/appstudio/errors.ts
packages/fx-core/src/plugins/resource/appstudio/plugin.ts

double question mark only works for undefined and null values. 
local settings configuration entry return empty string instead.

fix: local debug configuration

---

.github/workflows/cd.yml
package.json

1. templates alpha need to update daily
2. templates rc need to update every rc release
3. templates stable no need to update every stable release since sdk deps is semver as ^
4. sync up templates deps in rc will make code change on main branch, this will let template auto release rc and stable. which is not reasonable.
5. so template sync up script will be ignore at rc release, and separate as a single action later.
6. actually, once template bump up version on stable release, the rc version also sync up with sdk.

chore: update rc template deps sync up with sdk

---

packages/fx-core/src/plugins/resource/bot/aadRegistration.ts

fix bug https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/12674401
After fix, the error log will be:
[2021-11-24T08:32:51.582Z] [Error] - code:BT.ProvisionError, message: Failed to provision 'AAD client secret'. Suggestions: Please check log in output channel and try to fix this issue. Please retry the current step., Request failed with status code 404, stack: Error: Request failed with status code 404
at createError (D:\Work\TeamsFx\packages\fx-core\node_modules\axios\lib\core\createError.js:16:15)
at settle (D:\Work\TeamsFx\packages\fx-core\node_modules\axios\lib\core\settle.js:17:12)
at IncomingMessage.handleStreamEnd (D:\Work\TeamsFx\packages\fx-core\node_modules\axios\lib\adapters\http.js:269:11)
at IncomingMessage.emit (events.js:327:22)
at …

fix(bot): aad error handling

---

packages/vscode-extension/src/envTree.ts

As subscription name might not existing for old TeamsFx project, update the behavoir to display subscription id as fallback for this scenario.
E2E TEST: only affect UI.

fix(env-tree): display subs id as fallback if subs name is missing

---

packages/fx-core/src/core/middleware/projectMigrator.ts

When the upgrade process fails in the backup stage, there will be no popup message or error log at all. Fix https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/12674853/
The new behavior:

fix: popup and error log when backup fails

---

packages/vscode-extension/src/migration/migrationTool/ts/replaceFunction.ts
packages/vscode-extension/test/unit/migration/data/js/others/replace-getContext-commentLine.input.js
packages/vscode-extension/test/unit/migration/data/js/others/replace-getContext-commentLine.output.js
packages/vscode-extension/test/unit/migration/data/ts/others/replace-getContext-commentLine.input.ts
packages/vscode-extension/test/unit/migration/data/ts/others/replace-getContext-commentLine.output.ts

Fix [ADO-12494034](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/12494034/)
Detect parent node of the line start, so comment will be put at previous line. Tests added.
E2E TEST: AzureAppScaffold

fix(migration): correct comment location

---

packages/fx-core/resource/strings.json
packages/fx-core/src/plugins/resource/spfx/plugin.ts
packages/fx-core/src/plugins/resource/spfx/spoClient.ts
packages/fx-core/src/plugins/resource/spfx/utils/constants.ts
packages/fx-core/src/plugins/resource/spfx/utils/utils.ts

If tenant app catalog doesn't exist, we will call ensure `Ensure App Catalog` API to create one.
But it requires some time to take effect.
https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/retrieve-tenant-app-catalog-url-rest
So we just disabled automatic app catalog creation for the user, give doc to let user manually create tenant app catalog.

fix: create app catalog

---

packages/cli/src/cmds/capability.ts
packages/cli/src/cmds/resource.ts

- add `inputs.ignoreEnvInfo = true;` to `teamsfx resource add` and `teamsfx capability add`
- other changes are all automatic code formatting
fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/12684176/

fix(cli): do not ask env for addResource/addCapability

---

packages/fx-core/src/core/middleware/projectMigrator.ts

For SPFx project, `tab url` for teams workbench debug is different from remote. That is, the url in `local.manifest.template.json` is different from `remote.manifest.template.json`.
So we need to update `local.manifest.template.json`.
Test case 1:
1. Disable insider preview
2. Teams workbench debug
3. provision & deploy & publish
4. Enable insider preview & migration
5. Teams workbench debug
6. provision & deploy & publish (failed but fixed by pr: https://github.com/OfficeDev/TeamsFx/pull/3158)
Test case 2:
1. Enable insider preview
2. Teams workbench debug
3. provision & deploy & publish

fix: spfx migration tab url for teams workbench

---

packages/fx-core/src/plugins/resource/appstudio/index.ts
packages/fx-core/src/plugins/resource/appstudio/plugin.ts

1) Avoid two info messages when validation failed
2) Check icons in manifest validation

fix: do not support url for icons

---

packages/vscode-extension/src/commonlib/common/login.ts

1. Fix open share point login page unexpected when open a project.
Fix bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/12674790/

fix: move get status to immediate call logic

---

.github/workflows/env-checker-ci-schedule.yml
docs/vscode-extension/envchecker-help.md
packages/vscode-extension/src/debug/depsChecker/azureNodeChecker.ts
packages/vscode-extension/src/debug/depsChecker/common.ts
packages/vscode-extension/src/debug/depsChecker/nodeChecker.ts
packages/vscode-extension/src/debug/depsChecker/spfxNodeChecker.ts
packages/vscode-extension/test/integration/envChecker/cases/node.ts

- For non-function/non-spfx projects, support Node.js 16 LTS
- Update the documents accordingly
See the rendered document at [here](https://github.com/OfficeDev/TeamsFx/blob/aochengwang/feat/node16/docs/vscode-extension/envchecker-help.md#nodenotsupportedazure-functions)
env-checker test result: https://github.com/OfficeDev/TeamsFx/actions/runs/1525007470
M1 for https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/12196596/

feat(env-checker): support node16 for non-function/non-spfx projects

---

packages/api/review/teamsfx-api.api.md
packages/api/src/types.ts
packages/cli/src/telemetry/cliTelemetry.ts
packages/cli/src/telemetry/cliTelemetryEvents.ts
packages/cli/src/utils.ts
packages/fx-core/src/core/index.ts
packages/fx-core/src/core/middleware/projectSettingsLoader.ts
packages/fx-core/tests/core/core.test.ts
packages/vscode-extension/src/handlers.ts
packages/vscode-extension/src/telemetry/extTelemetry.ts
packages/vscode-extension/src/telemetry/extTelemetryEvents.ts

- add created-from property to telemetry events so BI report will not need to aggregate all projects and some hacky methods to determine at what version the project is created
- BI reports for old projects will still use the old method
- create-from property is core's package version, because we cannot get extension/cli version from core. toolkit/cli version can be determined because they have 1:1 mapping
- its implementation is similar to is-from-sample
- ut added
tested local debug happy path and packaged version:
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/12690560/

chore: add created-from telemetry property for bi data

---

packages/fx-core/src/core/middleware/migrateConditionHandler.ts
packages/vscode-extension/src/handlers.ts

Move reload command to vscode-extension to send telemetry after migrating success.
Detail: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_boards/board/t/Infrastructure%20Team/Stories/?workitem=12783805

fix(migratev1): send telemetry after migrate v1 success

---

packages/vscode-extension/src/envTree.ts
packages/vscode-extension/src/resources/Strings.json

Fix bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/12607395
- Add subscription id info as the tree item description for each subscription node.
- Add tooltip for subscription node (user can mouse over to see more info about this node)

chore: add more info for subscription item in env tree view

---

packages/vscode-extension/src/handlers.ts

Fix bug: https://dev.azure.com/msazure/Microsoft%20Teams%20Extensibility/_workitems/edit/12783952

fix: unexpected select-env window pop-up

---

packages/cli/tests/e2e/apim/TestCreateNewApim.tests.ts
packages/cli/tests/e2e/apim/TestImportApiIntoApim.tests.ts

The parameters of add apim resource command is changed in API V2. Change the e2e test case.
Relative PR: https://github.com/OfficeDev/TeamsFx/pull/3252
E2E: https://github.com/OfficeDev/TeamsFx/actions/runs/1553705719
Detail: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_boards/board/t/Infrastructure%20Team/Stories/?workitem=12800701

test(apim): change the add resource params in apim e2e test

---

packages/vscode-extension/src/commonlib/azureLogin.ts

1. Azure get status will wait Azure Account extension initialization.
Fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/12783666

fix: get status will wait for azure account extension initialization

---

packages/vscode-extension/src/debug/commonUtils.ts
packages/vscode-extension/src/debug/teamsfxDebugProvider.ts
packages/vscode-extension/src/debug/teamsfxTaskHandler.ts
packages/vscode-extension/src/extension.ts

localdebug contains several parts in TaskProvider, DebugProvider and several command handlers.
- the correlation id life cycle is defined as follows:
- starts from the start of env-checker
- ends when all the teamsfx debug sessions end or another debug session starts
Implementation:
1. For env-checker/task providers/preDebugCheck/DebugProvider, use a global variable to store correlation id (assuming at most one debug session at anytime)
2. For onDidStart/TerminateDebugSessionHandler, use event.configuration.teamsfxCorrelationId. So concurrent issue will not happen in this stage
Stage 2 is longer than stage 1, so maybe stage 1 is less likely to encounter concurrent issue.

chore(localdebug): add local debug correlation id

---

packages/api/review/teamsfx-api.api.md
packages/api/src/v2/resourcePlugin.ts
packages/api/src/v2/solutionPlugin.ts
packages/fx-core/src/core/index.ts
packages/fx-core/src/plugins/resource/apim/v2/index.ts
packages/fx-core/src/plugins/resource/appstudio/v2/index.ts
packages/fx-core/src/plugins/resource/bot/v2/index.ts
packages/fx-core/src/plugins/resource/frontend/v2/index.ts
packages/fx-core/src/plugins/resource/function/v2/index.ts
packages/fx-core/src/plugins/resource/spfx/v2/index.ts
packages/fx-core/src/plugins/resource/utils4v2.ts
packages/fx-core/src/plugins/solution/fx-solution/v2/deploy.ts
packages/fx-core/src/plugins/solution/fx-solution/v2/solution.ts
packages/fx-core/tests/plugins/resource/apiv2/utils4v2.test.ts
packages/fx-core/tests/plugins/resource/spfx/unit/v2lifecycle.test.ts
packages/fx-core/tests/plugins/solution/solution.deploy.test.ts

1) convert from v2 to v1 envInfo, should include config and envName
2) publishApplication with right envInfo
Test case passed:
1) Scaffold tab+bot project
2) Provision & deploy & publish
3) Create a new env
4) Provision & deploy & publish
5) Zip app package and select each environment

fix: pass and convert env info

---

packages/cli/src/constants.ts
packages/cli/src/utils.ts
packages/fx-core/src/common/constants.ts
packages/fx-core/src/common/tools.ts
packages/vscode-extension/package.json
packages/vscode-extension/src/constants.ts
packages/vscode-extension/src/utils/commonUtils.ts

Remove the feature flag added as a workaround for upgrade failure, related PR: https://github.com/OfficeDev/TeamsFx/pull/3050

chore: remove the flag to work on Toolkit v2

---

packages/sdk/README.md
packages/sdk/src/credential/teamsUserCredential.browser.ts
templates/tab/js/default/README.md
templates/tab/js/default/src/components/sample/lib/useGraph.js
templates/tab/ts/default/README.md
templates/tab/ts/default/src/components/sample/lib/useGraph.ts

@zhenyasav , could you help provide the helper link target URL, I will update it in aka service: https://aka.ms/teamsfx-session-storage-notice
Related task: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_sprints/taskboard/AuthAndData/Microsoft%20Teams%20Extensibility/CY21-12.1?workitem=12699312

docs: add sessionStorage notice

---

packages/fx-core/src/common/tools.ts

Mark below function as deprecated to reminder code owner to do code clean, and an email will be sent separately for more details:
* isMultiEnvEnabled()
* isArmSupportEnabled()
* isRemoteCollaborateEnabled()
All places referenced these functions will be marked as deprecated in VS Code:

chore: deprecated the function to check if Go Production features enabled

---

packages/fx-core/src/plugins/solution/fx-solution/v2/provision.ts

The fix of this bug https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/12807393
was accidentally deleted on main(https://github.com/OfficeDev/TeamsFx/commit/0f4eb4bdb8267a207a8a7cc6fede100543ecc765#diff-27f77cc037519b1cc57ac5f3c9b27a7e4b82db198830bdc1231b77aab121180aL266)  Restore it.

fix: set REMOTE_TEAMS_APP_TENANT_ID for spfx

---

packages/vscode-extension/package.json

To fix: (1) https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/12361074 and (2) #2594.
(1) can be stably reproduced, but (2) is hard to be reproduced.
From my test, task provider will not be called before activation finished. (1) can be definitely solved and we expect (2) can also be solved. See references below for more details.
References:
https://github.com/platformio/platformio-vscode-ide/issues/89#issuecomment-392447277

fix: block debug before extension activated

---

packages/vscode-extension/src/accountTree.ts
packages/vscode-extension/src/resources/Strings.json

1. Add warning to account tree when login with an Azure account with no subscriptions.
fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/12588918/

fix: add no subscriptions warning to tree view

---

packages/fx-core/package.json
packages/fx-core/src/common/localSettingsProvider.ts
packages/fx-core/tests/common/localSettingsProvider.test.ts
packages/fx-core/tests/core/localSettings.test.ts

fixes https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_sprints/taskboard/Teams%20Extensibility%20E2E%20Team/Microsoft%20Teams%20Extensibility/CY21-12.2?workitem=12873343
For bot-only projects, LocalSettingsProvider.initV2() doesn't generate "auth" key. This PR fixes it.

fix: generate correct localSettings.json using initV2()

---

packages/fx-core/src/common/tools.ts
packages/fx-core/tests/core/middleware/ProjectSettingsWriterMW.test.ts
packages/fx-core/tests/plugins/solution/solution.provision.test.ts

Update the return value of `isMultiEnvEnabled` to be `true` and fix several failed test cases.

chore: isMultiEnvEnabled() always returns true

---

.github/workflows/env-checker-ci-schedule.yml
docs/vscode-extension/envchecker-help.md
packages/cli/src/cmds/preview/depsChecker/common.ts
packages/cli/src/cmds/preview/depsChecker/dotnetChecker.ts
packages/fx-core/src/plugins/resource/function/utils/depsChecker/common.ts
packages/fx-core/src/plugins/resource/function/utils/depsChecker/dotnetChecker.ts
packages/vscode-extension/src/debug/depsChecker/common.ts
packages/vscode-extension/src/debug/depsChecker/dotnetChecker.ts

Support .NET 6.0 in env checker. Code and documents updated.
Tested tab+function project.
Tested on M1
[.NET support matrix for M1 mac](https://docs.microsoft.com/en-us/dotnet/core/install/macos#whats-supported)
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/12600126

feat(env-checker): add support for .NET 6.0

---

packages/fx-core/src/common/index.ts
packages/fx-core/src/common/local/localEnvManager.ts
packages/fx-core/src/common/local/npmLogHelper.ts
packages/fx-core/tests/common/local/npmLogHelper.test.ts

Add `getNpmInstallLogInfo()` to `LocalEnvManager`, as well as unit tests.
Export `LocalEnvManager` so it can be used by vsc/cli.

refactor(localdebug): getNpmInstallLog

---

packages/fx-core/src/common/templatesActions.ts

How to use this action:
1. Set DEBUG_TEMPLATE=true to your environment variables.
1. Add your changes in templates source code.
2. cd to vscode-extension folder.
3. F5 to local debug and create new project.
4. The `FetchTemplateZipFromSourceCode` action will get template from the source code that you just changed.
* `FetchTemplatesUrlWithTag`, `FetchTemplatesZipFromUrl`, `FetchTemplateZipFromLocal`, these actions are skipped.
* Since bot's and message extension's templates are generated during CD pipeline, we can't debug those code with this action.

chore: scaffold from local code for debug purpose

---

packages/fx-core/src/plugins/solution/fx-solution/debug/util/tasks.ts

ADO:
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_sprints/taskboard/Teams%20Extensibility%20E2E%20Team/Microsoft%20Teams%20Extensibility/CY21-12.3?workitem=12873660
Root cause:
When F5, both pre debug check and validate dependency handlers will be executed. The two handlers will call APIs of core which will cause concurrency error. So I change the order to 'sequence' instead of 'parallel' to avoid the lock fail issue.
E2E TEST: only for extension

fix: spfx local debug concurrency error

---

packages/cli/src/cmds/preview/constants.ts
packages/fx-core/src/common/local/constants.ts
packages/fx-core/src/common/local/localEnvProvider.ts
packages/fx-core/src/common/local/localSettingsHelper.ts
packages/fx-core/src/plugins/solution/fx-solution/debug/provisionLocal.ts
packages/fx-core/tests/common/local/localEnvManager.test.ts
packages/fx-core/tests/common/local/localEnvProvider.test.ts
packages/fx-core/tests/common/local/localSettingsHelper.test.ts
packages/fx-core/tests/core/localSettings.test.ts
packages/fx-core/tests/plugins/solution/debug/solution.debug.scaffolding.test.ts
packages/vscode-extension/src/debug/constants.ts

3000 -> 53000
5000 -> 55000
Changes in `.fx/configs/localSettings.json`:
```json
{
"auth": {
"AuthServiceEndpoint": "http://localhost:55000",
},
"frontend": {
"tabEndpoint": "https://localhost:53000"
}
}
```
Changes in `tabs/.env.teamsfx.local`:
```
Port=53000
```
Documentation related changes will be included in the another PR.

fix(localdebug): use better ports for frontend and auth

---

packages/fx-core/src/plugins/resource/localdebug/index.ts
packages/fx-core/src/plugins/solution/fx-solution/debug/error.ts
packages/fx-core/src/plugins/solution/fx-solution/debug/provisionLocal.ts
packages/fx-core/src/plugins/solution/fx-solution/debug/scaffolding.ts
packages/fx-core/src/plugins/solution/fx-solution/debug/util/telemetry.ts
packages/fx-core/src/plugins/solution/fx-solution/solution.ts
packages/fx-core/tests/plugins/solution/solution.migrate.test.ts

Migrate v1 should use the local debug settings scaffolding logic in the solution.

refactor(localdebug): support migrate v1 scaffold local debug settings

---

docs/cicd_insider/README.md
docs/cicd_insider/github-cd-template.yml
docs/cicd_insider/jenkins-cd-template.Jenkinsfile
docs/cicd_insider/others-script-cd-template.sh

bring M365 back to CD since:
1. spfx's deployment dep on M365.
2. `teamsfx package` dep on M365.
3. How to support M365 ops in CI/CD needs further discussions.
to finish: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/12890346

chore: bring m365 back

---

docs/fx-core/localdebug-help.md
packages/fx-core/src/common/local/localEnvProvider.ts
packages/fx-core/src/common/local/localSettingsHelper.ts
packages/fx-core/src/common/local/portChecker.ts
packages/fx-core/src/plugins/solution/fx-solution/debug/provisionLocal.ts
packages/fx-core/tests/common/local/localEnvProvider.test.ts
packages/fx-core/tests/plugins/solution/debug/solution.debug.scaffolding.test.ts

- let v1 project to use old frontend port 3000 rather than 53000
- fix help doc by the way
Tested v1 tab with SSO project with #3488 changes included.
Related: #3479 #3483

fix(localdebug): let v1 project to use old frontend port

---

packages/vscode-extension/src/debug/commonUtils.ts
packages/vscode-extension/src/debug/teamsfxTaskProvider.ts

Replace user tasks with `LocalEnvManager` and remove unused common utils.
Two pending ones:
- `getSkipNgrokConfig` is still used by deps checker and will be covered in deps checker refactor.
- `getLocalDebugConfig` is still used by tree view and will be covered in another PR.

refactor(localdebug): replace usertasks with LocalEnvManager

---

packages/fx-core/src/plugins/resource/apim/config.ts
packages/fx-core/src/plugins/resource/apim/constants.ts

Related PR: https://github.com/OfficeDev/TeamsFx/commit/1177a6238d52f1f1172091febd747323f4d5b9b2
Add the implementation of get subscriptionId from solution config.

fix(apim): load subs from state.xx.json

---

packages/fx-core/src/core/question.ts
packages/fx-core/tests/core/question.test.ts

Adds programming language question to support csharp on VS.
Closes https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_sprints/taskboard/Teams%20Extensibility%20E2E%20Team/Microsoft%20Teams%20Extensibility/CY22-1.1?workitem=12962397

feat(core): support csharp on VS

---

packages/fx-core/src/plugins/solution/fx-solution/arm.ts
packages/fx-core/tests/plugins/solution/solution.arm.test.ts

currently all telemetries set the error code to ArmDeploymentFailed, update the code to set correct error code in telemetry, like BicepInstallFailed.

chore: set correct error code for arm deployment

---

packages/cli/tests/unit/help.tests.ts
packages/fx-core/src/plugins/solution/fx-solution/question.ts
packages/fx-core/src/plugins/solution/fx-solution/solution.ts
packages/fx-core/src/plugins/solution/fx-solution/v2/getQuestions.ts
packages/fx-core/tests/plugins/solution/util.ts

When click grant permission, it will auto input default user email:
If user forget to update this default email, it will show tips:

perf(collaboration): auto input default user email when grant permission

---

packages/fx-core/src/plugins/resource/frontend/dotnet/constants.ts
packages/fx-core/src/plugins/resource/frontend/dotnet/plugin.ts
packages/fx-core/templates/plugins/resource/webapp/bicep/provision.template.bicep
packages/fx-core/templates/plugins/resource/webapp/bicep/webappConfiguration.template.bicep
packages/fx-core/templates/plugins/resource/webapp/bicep/webappProvision.template.bicep
packages/fx-core/tests/plugins/resource/dotnet/unit/arm.test.ts

`UpdateArmTemplate` will be called when a new capability/resource added.
For example:
1. Create a project with tab capability -> `scaffold` and `generateArmTemplate` of frontend plugin is called.
2. Add capability bot -> `updateArmTemplate` of frontend plugin is called.

feat(dotnet): updateArmTemplate

---

packages/fx-core/resource/strings.json
packages/fx-core/src/common/permissionInterface.ts
packages/fx-core/src/plugins/solution/fx-solution/v2/listCollaborator.ts
packages/vscode-extension/src/handlers.ts
packages/vscode-extension/src/resources/Strings.json
packages/vscode-extension/src/utils/commonUtils.ts
packages/vscode-extension/test/unit/extension/handlers.test.ts

- Will show warning message instead of tenant id not match:
- Format and update list collaborator failed message:
- Show message box when list collaborator success:

perf(collaboration): show warning message when tenant id is empty

---

packages/fx-core/src/common/local/taskDefinition.ts

https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/13028405/
Npm(npx) 7 does not follow `PATH` (https://github.com/npm/cli/issues/2627), so directly call `ngrok` since we already has ngrok checker to ensure ngrok is installed.
A quick validation could be - updating `start ngrok` task as:
``` json
{
"label": "start ngrok",
"type": "shell",
"command": "ngrok http 3978 --log=stdout",
"isBackground": true,
"problemMatcher": "$teamsfx-ngrok-watch",
"options": {
"cwd": "${workspaceFolder}/bot",
"env": {
"Path": "${your-HOME}/.fx/bin/ngrok/node_modules/ngrok/bin"
}
},
"dependsOn": [
"bot npm install"
]
},
```
F5 should work as well.

fix(localdebug): bot ngrok confirmation

---

packages/api/src/qm/visitor.ts

Fix the P0 bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_sprints/taskboard/Teams%20Extensibility%20E2E%20Team/Microsoft%20Teams%20Extensibility/CY22-1.1?workitem=13023698
Root cause: actually there's an invisible question for creating new project. So the current step for select capability is 2 and back button is available.

fix: select capability can go back

---

packages/vscode-extension/src/debug/constants.ts
packages/vscode-extension/src/debug/teamsfxTaskHandler.ts

- use issue template choice link when getting npm log fails
- fix replacing workspace folder logic
If user updates `cwd` of npm install tasks in tasks.json like to an absolute path, the original replacing logic will be wrong.

fix(localdebug): improve npm install task error handler

---

packages/fx-core/src/common/template-utils/templatesActions.ts
packages/fx-core/src/common/template-utils/templatesUtils.ts

The timeout parameter in axios is a response timeout, which throw an error when server doesn't response in time. While what we need is a connection timeout, which throw an error when the request doesn't end in time.
1. Replace template url with 1GB size test file download link.
2. Run scaffold, plugin takes more than 2 minutes to download the test file.
```
[2022-01-20T03:01:26.038Z] [Info] - [fx-resource-frontend-hosting] Retrieving template from 'https://speed.hetzner.de/1GB.bin'.
[2022-01-20T03:03:59.687Z] [Info] - [fx-resource-frontend-hosting] Error: Invalid or unsupported zip format. No END header found
[2022-01-20T03:03:59.689Z] [Info] - [fx-resource-frontend-hosting] Failed to retrieve latest template from GitHub. Using local template instead.
```
3. Add the changes.
4. Run …

perf(template): add connection timeout for fetching templates

---

packages/cli/src/cmds/deploy.ts
packages/cli/src/cmds/env.ts
packages/cli/src/cmds/manifest.ts
packages/cli/src/cmds/package.ts
packages/cli/src/cmds/provision.ts
packages/cli/src/cmds/publish.ts
packages/cli/src/telemetry/cliTelemetry.ts
packages/cli/src/utils.ts
packages/cli/tests/unit/telemetry/cliTelemetry.tests.ts
packages/cli/tests/unit/utils.tests.ts

1. for all env related commands, add "appid" telemetry property in the end event. 
2. fix the missing error event in env.ts
3. add related UT
1 is not need before multi-env because telemetry reporter handled this logic. But after multi-env, not all (e.g. the "start" events) events have appid (from the bussiness logic) and the telemetry reporter cannot handle this logic. It will be handled by lifecycle function callers.
This issue has already been fixed in vscode-extension before 3.0 release.
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/12962338/

fix: missing appid in cli for env related commands

---

packages/vscode-extension/src/handlers.ts

https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/13070653
Use `Correlator.run(provisionHandler)` instead of `runCommand(Stage.provision)` directly, which will refresh the tree view after provision

fix(collaboration): fix tree view not refresh after provision

---

packages/fx-core/src/common/local/taskDefinition.ts
packages/vscode-extension/src/debug/teamsfxTaskHandler.ts
packages/vscode-extension/src/debug/teamsfxTaskProvider.ts
packages/vscode-extension/test/unit/localdebug/teamsfxTaskProvider.test.ts

To be transparent, directly expose `npm run xxx` shell task in tasks.json, so extension only needs to handle such tasks, no need to provide/resolve such tasks.

chore: prepare custom local tasks

---

packages/fx-core/src/plugins/solution/fx-solution/debug/util/tasks.ts
packages/vscode-extension/src/debug/teamsfxTaskHandler.ts

Two fixes:
1. Update ngrok task to `teamsfx` source. The original one somehow could be recognized as `source: shell` so not correctly killed by task handler.
2. Use string as the key of `allRunningTeamsfxTasks`. The original one `IRunningTeamsfxTask` does not have `===` overload so the map is keeping increasing.

fix(localdebug): fix task handler

---

packages/vscode-extension/package.json
packages/vscode-extension/src/extension.ts
packages/vscode-extension/src/handlers.ts

Add a new hidden command `fx-extension.append-func-path` to be used by tasks.json.
``` json
{
"label": "start",
"type": "shell",
"command": "func start",
"options": {
"env": {
"PATH": "${env:PATH}${command:fx-extension.append-func-path}"
}
}
}
```

chore(local debug): get env for func task

---

packages/fx-core/src/plugins/resource/appstudio/plugin.ts

Manifest schema has an undefined format uri
Ignore this format to avoid cli errors.
Reference: https://ajv.js.org/packages/ajv-formats.html#options

fix: ignore format uri

---

packages/api/review/teamsfx-api.api.md
packages/api/src/types.ts
packages/fx-core/src/common/constants.ts
packages/fx-core/src/core/environment.ts
packages/fx-core/tests/core/environment.test.ts

For existing app, add some pre-defined variables to the default env config during scaffolding. Here's an example of config.dev.json while creating tab app from an existing app:
```json
{
"$schema": "https://aka.ms/teamsfx-env-config-schema",
"description": "You can customize the TeamsFx config for different environments. Visit https://aka.ms/teamsfx-env-config to learn more about this.",
"manifest": {
"appName": {
"short": "myapp",
"full": "Full name for my app"
},
"developerWebsiteUrl": "",
"developerPrivacyUrl": "",
"developerTermsOfUseUrl": "",
"tabContentUrl": "",
"tabWebsiteUrl": ""
}
}
```

feat(env-config): add empty variables to env config for existing app

---

packages/vscode-extension/src/debug/prerequisitesHandler.ts

`handleCheckResults` already throws when detecting error, so remove the wrapped one.

fix(localdebug): fix prerequisites check result

---

packages/fx-core/src/plugins/resource/aad/constants.ts
packages/fx-core/src/plugins/resource/aad/index.ts
packages/fx-core/tests/plugins/solution/solution.grantPermission.test.ts

Now provision and deploy works with some changes to the tempalte:
1. remove aad from active plugins
2. remove webApplicationInfo in teams app manifest.
TODO：add aad plugin when adding function/apim in solution

perf(aad): update AAD activate logic to allow Tab without AAD

---

packages/fx-core/src/plugins/solution/fx-solution/solution.ts
packages/fx-core/src/plugins/solution/fx-solution/v2/executeUserTask.ts
packages/fx-core/src/plugins/solution/fx-solution/v2/provisionLocal.ts

1. remove error when local debug does not contain AAD plugin
2. add aad plugin if not exists in active plugins when adding function
TODO: hardcoded aad plugin is not removed in registerTeamsAppAndAad since it is not used now.

perf(solution): update solution to separate AAD

---

templates/bot/js/default/package.json
templates/bot/ts/default/package.json
templates/function-base/js/default/package.json
templates/function-base/ts/default/package.json
templates/msgext/js/default/package.json
templates/msgext/ts/default/package.json
templates/tab/js/default/package.json
templates/tab/ts/default/package.json

The new `dev:teamsfx` script will be used by F5 to launch local services. Adjust templates to prepare those scripts.

feat(local debug): add dev:teamsfx script to new projects

---

packages/fx-core/src/common/local/localCertificateManager.ts
packages/fx-core/src/common/local/localEnvManager.ts
packages/vscode-extension/src/debug/depsChecker/doctorConstant.ts
packages/vscode-extension/src/debug/prerequisitesHandler.ts

When generate dev cert is failed:
When trust dev cert is skipped (Linux / vscode settings):
When user cancelled trust certification:
PS: change user cancel error message in PR: https://github.com/OfficeDev/TeamsFx/pull/3866

chore(localdebug): add log when trust local cert skipped or failed

---

packages/fx-core/src/plugins/resource/frontend/dotnet/constants.ts
packages/fx-core/src/plugins/resource/frontend/dotnet/plugin.ts
packages/fx-core/src/plugins/resource/frontend/dotnet/resources/errors.ts
packages/fx-core/src/plugins/resource/frontend/dotnet/resources/templateInfo.ts

Dotnet plugin need to parse project file to get current runtime and build the project depends on the csproj file. So we drop project file path in project setting when scaffolding.
E2E TEST: will add e2e test later.

fix(dotnet): dotnet project file path as project setting 

---

packages/sdk/src/credential/teamsUserCredential.browser.ts
packages/sdk/test/unit/browser/teamsUserCredential.browser.spec.ts

Use timeout to check whether SDK is running inside Teams client is not very stable especially when debug project.
Related code can be found here:
https://github.com/wictorwilen/msteams-react-base-component/blob/c3d941e3467365c23d8e8f4f2c067c4b0eb6a032/src/useTeams.ts#L10

perf(sdk): optimize check in teams logic

---

.github/scripts/template-zip-autogen.sh
.github/workflows/cd.yml

Release templates produces some temporary files, as below.
This PR is to generate the template zip files in a temporary folder so that we do not worry commit in those zip files by mistake.
There still be some js/ts files produced during generating template zip files, we will have another task to avoid those files.

chore(cd): generate zip to temporary folder in cd

---

.github/CODEOWNERS
packages/cli/tests/e2e/bot/CommandExecutionIsUserError.ts
packages/fx-core/src/plugins/resource/bot/errors.ts
packages/fx-core/tests/plugins/resource/bot/unit/errors.test.ts

to finish: https://dev.azure.com/msazure/Microsoft%20Teams%20Extensibility/_workitems/edit/13026392
errorType shouldn't be changed if statusCode = undefined, instead, respect the original errorType.
+ update code owners also.
1. Refactor inferInnerError as a external function.
2. Infer Graph Error in CreateAADError and CreateAADSecretError by need.
3. Add UT and E2E cases.
E2E TEST: https://github.com/OfficeDev/TeamsFx/blob/b9b0d58ec78d29044008cd64b49cb6c2406b9ba5/packages/cli/tests/e2e/bot/CommandExecutionIsUserError.ts#L35

fix: errorType should not be changed if statusCode = undefined

---

packages/cli/tests/e2e/bot/ProvisionResourceProjectWithNewBot.tests.ts

a very quick update of e2e case author.
FYI: grep -r "yitong.feng" under packages, nothing filtered out.

chore: update e2e case author

---

packages/fx-core/src/plugins/resource/appstudio/plugin.ts
packages/fx-core/tests/plugins/resource/appstudio/unit/updateManifest.test.ts

https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/13415034

fix: generate teams manifest first if provision has done

---

packages/fx-core/src/plugins/resource/frontend/dotnet/plugin.ts

Create new project with bot capability -> add tab -> provision -> deploy -> preview
Create new project with tab capability -> add bot -> provision -> deploy -> preview
Both cases pass. But user code may be replaced after adding capability.
E2E TEST: CLI does not support csharp scenario yet.

fix(dotnet): add capability generate broken biceps

---

packages/cli/src/cmds/publish.ts
packages/cli/src/telemetry/cliTelemetry.ts
packages/cli/src/telemetry/cliTelemetryEvents.ts
packages/cli/src/utils.ts
packages/cli/tests/unit/utils.tests.ts
packages/vscode-extension/src/debug/commonUtils.ts
packages/vscode-extension/src/handlers.ts
packages/vscode-extension/src/telemetry/extTelemetryEvents.ts
packages/vscode-extension/src/utils/commonUtils.ts

All 'end events' related to multi-env and teams app from extension and cli now contains 'tenant-id' property. This is for calculating OKR goals.
vscode:
cli:
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/13249760/

chore: add tenant id for multi-env telemetry events

---

packages/fx-core/src/common/projectSettingsValidator.ts
packages/fx-core/src/core/tools.ts

The treeview of project migrated from v1:
The notification of F5 / Add resource / Provision / Deploy......

chore: add migrate v1 retired notification

---

.github/workflows/cd.yml

pack server bits need win64, and test success once installed.

chore: install win64 for pack server bits.

---

packages/vscode-extension/src/exp/treatmentVariables.ts
packages/vscode-extension/src/extension.ts
packages/vscode-extension/src/handlers.ts

According to the telemetry data and discussion with Zhen & Jaeyong, will keep the create from sample option to avoid sample engagement decrease.
ADO: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/13413556
E2E TEST: feature discarded and no ux change

feat: remove ab test logic and keep create from sample option

---

packages/vscode-extension/src/handlers.ts

This fix is part of https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/13506162
E2E TEST: only for extension

fix: only notify azure sign in status for valid teamsfx project

---

packages/vscode-extension/src/commonlib/azureLogin.ts
packages/vscode-extension/src/commonlib/common/constant.ts

1.Status change logic when version<0.10.0
Initializing->loggedIn/loggedOut
Status change logic when version==0.10.0
Initializing->loggingIn->loggedIn/loggedOut
2.```azureAccount.waitForSubscriptions()``` will wait for login finish when version==0.10.0.

chore: compatible with 0.10.0 azure account extension

---

packages/fx-core/src/plugins/solution/fx-solution/v2/utils.ts

This PR will correctly propagate FxError by returning them during localdebug account checking, so that inner errors will be presented to users instead of only showing unknown.Unknown. 
Related issue: #4023
Note: This PR won't fix the root cause of #4023, but will correctly propagate errors to end users.

chore: returning error instead of throwing

---

packages/vscode-extension/src/envTree.ts
packages/vscode-extension/src/handlers.ts

For existing app scenario, local preview is supported to launch the teams app.

chore(env-tree): support to preview local env

---

packages/fx-core/src/plugins/resource/appstudio/manifestTemplate.ts
packages/fx-core/src/plugins/resource/appstudio/plugin.ts

Test with miniapp, provision succeed.

refactor: get capability from manifest, rather than project settings

---

packages/fx-core/src/plugins/solution/fx-solution/v2/deploy.ts
packages/fx-core/tests/plugins/solution/solution.deploy.test.ts

Fixes https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/13698661?src=WorkItemMention&src-action=artifact_link
E2E TEST: not needed since unit test cases are added.

fix(solution): do not check m365 account in Azure projects

---

packages/fx-core/src/common/constants.ts
packages/fx-core/src/common/tools.ts
packages/vscode-extension/package.json
packages/vscode-extension/src/constants.ts
packages/vscode-extension/src/utils/commonUtils.ts

Add experiential feature flag to enable to init a teamsfx app and unify the local & remote configs.
Preview:

chore(flag): add feature flag for incremental app building

---

packages/fx-core/src/core/FxCore.ts
packages/vscode-extension/package.json
packages/vscode-extension/src/extension.ts
packages/vscode-extension/src/handlers.ts
packages/vscode-extension/src/resources/Strings.json
packages/vscode-extension/src/telemetry/extTelemetry.ts
packages/vscode-extension/src/telemetry/extTelemetryEvents.ts
packages/vscode-extension/src/treeview/treeViewManager.ts

Add support to initialize an existing application when the [feature flag](https://github.com/OfficeDev/TeamsFx/pull/4142) is enabled. 
Please note, this is the draft UX and will be continuously improved according to PM's design.

chore(vsc): support to init an app when feature flag is enabled

---

packages/api/review/teamsfx-api.api.md
packages/api/src/types.ts
packages/cli/src/utils.ts
packages/fx-core/src/plugins/solution/fx-solution/v3/provision.ts

https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/13725740
Add a `targetResourceLocationName` property to `Inputs`. Check the platform when checking the resource group.
E2E TEST:

fix: solution resource group check for vs

---

packages/cli/src/cmds/index.ts
packages/cli/src/cmds/manifest.ts
packages/cli/src/cmds/validate.ts
packages/cli/tests/e2e/bot/ProvisionResourceProjectWithNewBot.tests.ts
packages/cli/tests/e2e/function/TestAddFunction.tests.ts
packages/cli/tests/e2e/multienv/TestRemoteHappyPath.tests.ts
packages/cli/tests/e2e/multienv/TestRemoteHappyPathSPFx.tests.ts
packages/cli/tests/e2e/spfx/CreateSPFxProject.tests.ts
packages/cli/tests/unit/cmds/index.tests.ts
packages/cli/tests/unit/cmds/validate.tests.ts

Change `teamsfx manifest validate` to `teamsfx validate`
Related task https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_sprints/taskboard/Teams%20Extensibility%20E2E%20Team/Microsoft%20Teams%20Extensibility/CY22-3.1?workitem=13294507
E2E TEST: multiple cases are changed in the PR

feat(cli): add teamsfx validate back

---

packages/vscode-extension/src/treeview/treeViewManager.ts

Show init tree view command only when the feature flag is enabled.
E2E TEST: UI related.

fix(vsc): show init command only when feature flag is enabled

---

packages/vscode-extension/package.json
packages/vscode-extension/src/constants.ts
packages/vscode-extension/src/utils/commonUtils.ts

revert extension settings for experimental features (unify configs & init app), related PR: https://github.com/OfficeDev/TeamsFx/pull/4142
Then, to enable to unify local & remote configs and init app, the environment variables need to be updated manually.
```shell
export TEAMSFX_INIT_APP=true
export TEAMSFX_CONFIG_UNIFY=true
```

chore(vsc): revert extension settings for experimental features

---

packages/cli/src/cmds/index.ts
packages/cli/src/cmds/init.ts

Add `init` command if feature flag `TEAMSFX_INIT_APP` is enabled.
work item: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/13725446/

chore(cli): add init command

---

packages/fx-core/src/plugins/resource/appstudio/plugin.ts

Before:
After:
E2E TEST: only for extension

fix: app name does not show when local debug

---

packages/fx-core/src/plugins/resource/bot/constants.ts
packages/fx-core/src/plugins/resource/bot/languageStrategy.ts
packages/fx-core/src/plugins/resource/bot/plugin.ts
packages/fx-core/tests/plugins/resource/bot/unit/languageStrategy.test.ts

- add bot notification with azure functions hosting scaffold
- currently UI is not finalized yet, so add an environment variable TEAMSFX_BOT_HOST_TYPE to test different host types. Later this information will be from question model
How to test this:
1. select notification in question model 
2. set TEAMSFX_BOT_HOST_TYPE=function to test function scaffold or set TEAMSFX_BOT_HOST_TYPE=appService to test app service scaffold
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/13762945

feat: scaffold bot notification with function template

---

.github/CODEOWNERS
packages/fx-core/src/plugins/resource/bot/configs/scaffoldConfig.ts
packages/fx-core/src/plugins/resource/bot/functionsHostedBot/plugin.ts
packages/fx-core/src/plugins/resource/bot/index.ts
packages/fx-core/src/plugins/resource/bot/plugin.ts
packages/fx-core/tests/plugins/resource/bot/unit/index.test.ts

As the offline discussion with @eriolchan team, we will move the function hosted notification code into a inherited class of `TeamsBotImpl`
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/13814055

refactor: move function hosted notification code

---

packages/fx-core/src/common/tools.ts

Due to the usage of https://github.com/OfficeDev/TeamsFx/blob/dev/packages/fx-core/src/common/local/projectSettingsHelper.ts#L51, the `projectSettings?.solutionSettings as AzureSolutionSettings` might be undefined and throw exception while calling `isAADEnabled.`

chore(core): add null check for method isAADEnabled

---

package.json

since the root package.json run lint:staged needs no-secrets plugins.
so delete this secret-checker.

chore: update

---

packages/api/review/teamsfx-api.api.md
packages/api/src/types.ts
packages/fx-core/src/common/constants.ts
packages/fx-core/src/common/tools.ts

- add isM365 in ProjectSettings
- add isM365 in Inputs
- add TEAMSFX_M365_APP feature flag
The setting and feature flag will be used when scaffolding M365 projects.

chore(m365): add m365 setting and feature flag

---

.github/workflows/cd.yml

`mo` has been removed from `template-zip-autogen.sh`. https://github.com/OfficeDev/TeamsFx/pull/4025

chore(cd): remove mo

---

packages/fx-core/src/core/FxCore.ts

Before: `.gitignore` won't be scaffolded if it exists.
After: content of `.gitignore` will be append to the existing `.gitgnore` file.

chore(core): append if .gitignore already exists

---

packages/server/buildExe.js

Naming rule: server-${arch}-${version}.exe. This is to distinguish the different version/arch of the server.

chore: change server packing name

---

packages/vscode-extension/src/handlers.ts

Always run debug lifecycle for local preview.

chore(vsc): refine local preview for mini app

---

packages/vscode-extension/package.json

fix bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/13862400/
E2E TEST: UI related.

fix(vsc): env view shows if no project opened

---

packages/vscode-extension/package.json
packages/vscode-extension/package.nls.json
packages/vscode-extension/src/commonlib/graphLogin.ts
packages/vscode-extension/src/extension.ts
packages/vscode-extension/src/handlers.ts
packages/vscode-extension/src/telemetry/extTelemetryEvents.ts

- add a new command to create a m365 app, this command will be only enabled if m365 feature flag is set
- add create new m365 project handler, set isM365 in inputs to let FxCore know this is to create a m365 project
- add TeamsAppInstallation.ReadForUser to graph scopes

feat(m365): add create m365 app command

---

packages/fx-core/src/plugins/resource/frontend/resources/templateInfo.ts
templates/tab/js/m365/package.json
templates/tab/js/m365/src/components/sample/Welcome.jsx
templates/tab/ts/m365/package.json
templates/tab/ts/m365/src/components/sample/Welcome.tsx

Frontend plugin:
- scaffold m365 tab template if isM365 is true
M365 template:
- use teams-js v2 to get hub name
- show hub name in template welcome page
- update @microsoft/mgt-element version to 2.4.1-next.teamsfx.053a600
- update @microsoft/mgt-react version to 2.4.1-next.teamsfx.053a600
- update @microsoft/mgt-teamsfx-provider version to 2.4.1-next.teamsfx.053a600

chore(m365): scaffold m365 tab template

---

packages/fx-core/.gitignore
packages/fx-core/scripts/download-templates-zip.js
packages/fx-core/src/common/template-utils/templatesActions.ts
packages/fx-core/src/common/templates-config.json
packages/fx-core/src/plugins/resource/bot/constants.ts
packages/fx-core/src/plugins/resource/bot/languageStrategy.ts
packages/fx-core/src/plugins/resource/bot/v3/index.ts
packages/fx-core/src/plugins/resource/frontend/constants.ts
packages/fx-core/src/plugins/resource/frontend/dotnet/constants.ts
packages/fx-core/src/plugins/resource/frontend/dotnet/ops/scaffold.ts
packages/fx-core/src/plugins/resource/frontend/ops/scaffold.ts
packages/fx-core/src/plugins/resource/frontend/v3/index.ts
packages/fx-core/src/plugins/resource/function/constants.ts
packages/fx-core/src/plugins/resource/function/ops/scaffold.ts
packages/fx-core/tests/plugins/resource/bot/unit/index.test.ts
packages/fx-core/tests/plugins/resource/bot/unit/languageStrategy.test.ts
packages/fx-core/tests/plugins/resource/frontend/unit/index.test.ts
packages/fx-core/tests/plugins/resource/function/unit/scaffold.test.ts

1. Move all fallback zip to a common folder.
2. download-template-zip.js download all assets from github release by tag name.
By doing so, we do not need to update download-template-zip.js when there is new template added.
E2E TEST: all passed https://github.com/OfficeDev/TeamsFx/actions/runs/1990669349

refactor(template): move all fallback zip to a common folder

---

packages/vscode-extension/src/debug/teamsfxDebugProvider.ts

Fix https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/13864517.

fix: fix getTeamsAppInternalId bug in debug provider

---

templates/bot/ts/notification-function-base/package.json

Include "test" in the semver prerelease part to prevent auto upgrading.

chore: update notification sdk version

---

packages/fx-core/src/core/environment.ts
packages/fx-core/tests/core/environment.test.ts

if there's no secret, then no need to save *.userdata file under .fx/configs/

chore(env): no need to save userdata file when no secrets

---

packages/fx-core/src/plugins/resource/cicd/utils/buildScripts.ts
packages/fx-core/templates/plugins/resource/cicd/azdo/cd.yml
packages/fx-core/templates/plugins/resource/cicd/azdo/ci.yml
packages/fx-core/templates/plugins/resource/cicd/azdo/provision.yml
packages/fx-core/templates/plugins/resource/cicd/azdo/publish.yml

to fix 
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/13883926
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/13883902
1. fix azdo's trigger to `trigger: none`, i.e., the manual trigger.
2. align `npm ci`
3. turn on `failOnStandardErr`

chore: refine templates, align npm ci

---

packages/vscode-extension/src/envTree.ts
packages/vscode-extension/src/handlers.ts

refresh env tree and update the `Preview` button to `Local Debug` button when project settings is updated (for example, a component is added to a mini app).

chore(vsc): refresh env tree when project settings updated

---

packages/fx-core/templates/plugins/resource/cicd/azdo/cd.yml
packages/fx-core/templates/plugins/resource/cicd/azdo/ci.yml
packages/fx-core/templates/plugins/resource/cicd/azdo/provision.yml
packages/fx-core/templates/plugins/resource/cicd/azdo/publish.yml

failOnStderr is too strict which will cause warning to fail the whole process.
1. remove failOnStderr
2. set -e for the bash to fail as soon as possible

chore: tune fail on err

---

packages/sdk/karma.conf.js
packages/sdk/package.json
packages/sdk/test/e2e/browser/msGraphAuthProvider.browser.spec.ts
packages/sdk/test/e2e/browser/msGraphClientProvider.browser.spec.ts
packages/sdk/test/e2e/browser/teamsUserCredential.browser.spec.ts
packages/sdk/test/e2e/helper.browser.ts
packages/sdk/test/e2e/helper.ts
packages/sdk/test/e2e/node/appCredential.spec.ts
packages/sdk/test/e2e/node/msGraphAuthProvider.spec.ts
packages/sdk/test/e2e/node/msGraphClientProvider.spec.ts
packages/sdk/test/e2e/node/onBehalfOfUserCredential.spec.ts
packages/sdk/test/e2e/node/sqlConnector.spec.ts
packages/sdk/test/e2e/node/teamsBotSsoPrompt.spec.ts

Using 3 environment variables in e2e test:
- SDK_INTEGRATION_TEST_SQL
- SDK_INTEGRATION_TEST_ACCOUNT
- SDK_INTEGRATION_TEST_AAD

chore(sdk): decrease the number of env variables for integration test

---

packages/fx-core/src/plugins/resource/bot/configs/scaffoldConfig.ts
packages/fx-core/src/plugins/resource/bot/configs/teamsBotConfig.ts
packages/fx-core/src/plugins/resource/bot/resources/strings.ts
packages/fx-core/src/plugins/solution/fx-solution/question.ts
packages/fx-core/src/plugins/solution/fx-solution/v2/utils.ts
packages/fx-core/tests/plugins/resource/bot/unit/configs/scaffoldConfig.test.ts

- Add 'capabilities' to bot plugin settings to distinguish notification bot, command response bot, etc.
- Refactor 'scenario' to 'scenarios' in ctx.answers (Please note this key was added only for bot. No other plugin is affected)
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/13908646

chore: add bot plugin settings capabilities

---

.github/workflows/e2e-test.yml
.github/workflows/unit-test.yml
packages/fx-core/src/plugins/resource/appstudio/errors.ts

Fixes bug https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/13918768
It is caused by excessive use of `any`, which delays the type error till runtime.
Please avoid using `any` when necessary. 
E2E TEST: not needed.

fix: appstudio error msg for building package

---

packages/fx-core/src/plugins/resource/appstudio/v3/index.ts

https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/13841713
Root cause:
We use isExistingApp flag to decide whether use config placeholder for developer info in manifest template. But the flag is already removed, so the logic should be updated
Fix:
Check solution settings in ctx: it should be undefined for existing apps.
E2E TEST: bug during development, will add test later

fix: manifest template developer field wrong for init app

---

packages/fx-core/resource/package.nls.json
packages/fx-core/src/core/FxCore.ts
packages/fx-core/src/core/question.ts
packages/fx-core/src/plugins/resource/frontend/resources/templateInfo.ts
packages/fx-core/src/plugins/solution/fx-solution/question.ts
packages/fx-core/src/plugins/solution/fx-solution/v2/getQuestions.ts
packages/fx-core/src/plugins/solution/fx-solution/v2/utils.ts
packages/fx-core/tests/plugins/solution/solution.util.test.ts

1. Add non SSO Tab in selection.
2. Use default tab template when Tab is selected.

perf(solution, fe): add non sso Tab item in create project

---

packages/fx-core/src/plugins/resource/bot/constants.ts
packages/fx-core/src/plugins/resource/bot/functionsHostedBot/plugin.ts

Progress bar title in `scaffold()` must match `index.ts`. Otherwise, the following progress bar will not be closed after success.

fix: fix progress bar for func hosted bot

---

packages/fx-core/resource/package.nls.json
packages/fx-core/src/core/FxCore.ts
packages/fx-core/src/plugins/resource/bot/configs/scaffoldConfig.ts
packages/fx-core/src/plugins/resource/bot/configs/teamsBotConfig.ts
packages/fx-core/src/plugins/resource/bot/functionsHostedBot/plugin.ts
packages/fx-core/src/plugins/resource/bot/index.ts
packages/fx-core/src/plugins/resource/bot/plugin.ts
packages/fx-core/src/plugins/resource/bot/question.ts
packages/fx-core/src/plugins/solution/fx-solution/question.ts
packages/fx-core/src/plugins/solution/fx-solution/v2/executeUserTask.ts
packages/fx-core/src/plugins/solution/fx-solution/v2/getQuestions.ts
packages/fx-core/src/plugins/solution/fx-solution/v3/userTask.ts
packages/fx-core/tests/plugins/resource/bot/unit/configs/scaffoldConfig.test.ts
packages/fx-core/tests/plugins/resource/bot/unit/question.test.ts

- call `getQuestionsForUserTask` when addCapability for bot plugin. (offline discussed with @jayzhang to hardcode bot plugin for v2 now, v3 will not need this)
- support notification/command response bot for addCapability
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/13883632
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/13863654

feat: addCapability for notification/command response bot

---

packages/fx-core/templates/plugins/resource/bot/bicep/funcHostedBotProvision.template.bicep
packages/fx-core/tests/plugins/resource/bot/unit/expectedBicepFiles/botProvisionOfFuncHosted.result.bicep

Zip deploy does not update node module files for NPM 5.6 and later
See https://github.com/projectkudu/kudu/issues/2917 and https://github.com/npm/npm/issues/20439. This affects the default zipdeploy behavior where it is optimized to only copy files that are changed. To workaround the issue, do set appSettings SCM_ZIPDEPLOY_DONOT_PRESERVE_FILETIME=1. Zipdeploy files will always be updated and, as a result, overwriting the existing ones regardless of change.

chore(bot): add SCM_ZIPDEPLOY_DONOT_PRESERVE_FILETIME into func hosted bot app settings

---

packages/fx-core/src/plugins/resource/appstudio/constants.ts
packages/fx-core/src/plugins/resource/appstudio/plugin.ts
packages/fx-core/tests/plugins/resource/appstudio/unit/scaffold.test.ts

From dogfooding feedback, there is no command provided by the notification bot, so it makes no senses to put them in the manifest.

fix: remove bot commands for notification bot

---

packages/fx-core/src/plugins/solution/fx-solution/debug/util/launch.ts
packages/fx-core/src/plugins/solution/fx-solution/debug/util/launchNext.ts

- if no cascadeTerminateToConfigurations, closing browser will not stop `Attach to Backend` and `Attach to Bot` even though stopAll in compound is true
Fix a regression bug https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/13929895.
E2E TEST: N/A

fix(localdebug): add back cascadeTerminateToConfigurations

---

packages/fx-core/src/plugins/solution/fx-solution/v2/getQuestions.ts

This is a quick fix for command and response bot to not ask for triggers. Later change to add a new tree node to prevent overwriting plugin's `node.condition` in solution.

fix: command and response should not ask for trigger

---

packages/vscode-extension/src/treeview/treeViewManager.ts

Register tree views since environment tree depends on TreeViewProvider in non-teamsfx project and causes exception otherwise.

chore(vsc): add tree registration for non-teamsfx project

---

packages/vscode-extension/src/treeview/treeViewManager.ts

Since tree view commands are handled in TreeViewManager, they should be registered in non-teamsfx project too.
Will fix this logic in later PR.
E2E TEST: manual tested.

chore(vsc): add command handlers

---

packages/fx-core/src/plugins/resource/bot/configs/teamsBotConfig.ts
packages/fx-core/tests/plugins/resource/bot/unit/configs/teamsBotConfig.test.ts

- bug: with BOT_NOTIFICATION_ENABLED=false, add capability of legacy bot will throw error: `[Bot Plugin] act roles is missing.`
- This is due to a missing feature flag check. Fixed and regression test attached.
Tested add capability with `BOT_NOTIFICATION_ENABLED=false`

fix: fix legacy bot add capability

---

packages/vscode-extension/README.md
packages/vscode-extension/package.json

Related bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/13964752
E2E TEST: N/A

fix(vscode): branding typo

---

packages/vscode-extension/package.nls.json
packages/vscode-extension/src/progressHandler.ts

Effect Preview:
1. ![image](https://user-images.githubusercontent.com/886116/161181503-600c7246-ff36-4268-8cdf-9275c7e0f694.png)
2. ![image](https://user-images.githubusercontent.com/886116/161181542-1a4fd2ae-bde7-42d3-ba86-297f15fa931d.png)
Related bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/13827715

chore(vsc): add output window link in progress bar

---

packages/fx-core/src/plugins/resource/bot/functionsHostedBot/deployMgr.ts
packages/fx-core/src/plugins/resource/bot/functionsHostedBot/plugin.ts
packages/fx-core/tests/plugins/resource/bot/unit/funcHostedDeployMgr.test.ts

Fix the bug during calculate whether need to redeploy.
1. Move the generation of `lastUpdateTime` after `npm build`
2. Do not check the file which is ignored in both `.funcignore` and `.gitignore`.
PS: `*.ts` is ignored in  `.funcignore` bot not in `.gitignore`

fix(bot): skip deployment after *.ts file is changed

---

packages/fx-core/src/plugins/resource/spfx/depsChecker/generatorChecker.ts
packages/fx-core/src/plugins/resource/spfx/depsChecker/yoChecker.ts
packages/fx-core/src/plugins/resource/spfx/plugin.ts

ADO:
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/14000279
1> Get bin folder according to npm version since npm v7 has different behavior with npm v6
2> Show instruction to tell user suggested versions for npm and node.(Maybe add help link to tell user how to troubleshooting later in dev branch)

fix: spfx scaffold failed due to yo not recognized

---

packages/adaptivecards-tools-sdk/rollup.config.js

It is defined in `package.json` that all d.ts files under `types` folder will be packed, however there are no `types` folder generated after build.
This PR modify `rollup.config.js` to generate d.ts files into `types` folder when build.

chore: pack d.ts into adaptivecards-tools

---

packages/fx-core/src/core/middleware/aadManifestMigration.ts
packages/fx-core/src/plugins/resource/aad/plugin.ts
packages/fx-core/templates/plugins/resource/aad/manifest/aad.template.json
packages/fx-core/tests/plugins/resource/aad/unit/index.test.ts

When scaffold, based on capability whether contain "Bot" or "Tab" to add redirect URL in aad.template.json file

perf(aad-manifest): update scaffold to support bot

---

packages/cli/package-lock.json
packages/cli/package.json
packages/cli/src/utils.ts

Upgrade the `yargs` version to support async builder for removing the `helpParamGenerator.ts` hardcode.
Task: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/14034041
E2E Test: https://github.com/OfficeDev/TeamsFx/runs/5846127186?check_suite_focus=true the failed cases are also failed in the dev branch.

chore: use latest yargs

---

packages/cli/src/cmds/preview/constants.ts
packages/cli/src/cmds/preview/preview.ts
packages/cli/src/cmds/preview/teamsAppInstallation.ts

Same as the behavior in vsc.
For launch page:
For messaging extension:

chore(m365): add outlook channel prompt in cli preview for bot app

---

packages/cli/src/cmds/capability.ts
packages/cli/tests/unit/cmds/capability.tests.ts
packages/fx-core/src/plugins/resource/bot/question.ts
packages/fx-core/src/plugins/solution/fx-solution/v2/getQuestions.ts

- Add CLI support for add capability notification/command response bot
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/13883760/

feat(cli): support add capability for notification/command response bot

---

packages/fx-core/src/plugins/resource/appstudio/manifestTemplate.ts
packages/fx-core/src/plugins/resource/appstudio/v3/index.ts
packages/fx-core/src/plugins/solution/fx-solution/v2/executeUserTask.ts
packages/fx-core/tests/plugins/resource/appstudio/unit/manifestTemplate.test.ts

- Fix the bug 'manifest is not correct when adding notification/commandresponse capability'
notification:
command response:
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/13942934/

fix: add capability notification/commandbot manifest

---

packages/api/review/teamsfx-api.api.md
packages/api/src/schemas/envConfig.json
packages/api/src/schemas/envConfig.ts
packages/fx-core/resource/package.nls.json
packages/fx-core/src/core/middleware/aadManifestMigration.ts
packages/fx-core/src/plugins/resource/aad/constants.ts
packages/fx-core/src/plugins/resource/aad/errors.ts
packages/fx-core/src/plugins/resource/aad/plugin.ts
packages/fx-core/src/plugins/resource/aad/utils/configs.ts
packages/fx-core/src/plugins/solution/fx-solution/v2/getQuestions.ts
packages/fx-core/src/plugins/solution/fx-solution/v2/provision.ts
packages/fx-core/src/plugins/solution/fx-solution/v2/utils.ts
packages/fx-core/tests/plugins/resource/aad/unit/index.test.ts
packages/fx-core/tests/plugins/solution/solution.provision.test.ts

1. Allow user to config frontend and bot info for existing app, user config has the highest priority:
```
{
"$schema": "https://aka.ms/teamsfx-env-config-schema",
"description": "You can customize the TeamsFx config for different environments. Visit https://aka.ms/teamsfx-env-config to learn more about this.",
"manifest": {
"appName": {
"short": "test-local-debug",
"full": "Full name for test-local-debug"
}
},
"auth": {
"frontendDomain": "example.com",
"botId": "xxxx",
"botEndpoint": "https://example.com"
}
}
```
2. Skip arm deployment if there is no Azure resource need to provision
3. Update config json schema

perf(aad-manifest): allow user to config frontend and bot info

---

packages/vscode-extension/src/treeview/environmentTreeItem.ts

Update the condition to collapse the env tree node according to its children number.
E2E TEST: UI related.

fix(env-tree): update the collapsible status condition

---

packages/fx-core/src/core/middleware/aadManifestMigration.ts

Do not remove permissions file when migration to make it compatible with old extension

perf(aad-manifest): not remove permissions file when migration

---

packages/vscode-extension/src/codeLensProvider.ts
packages/vscode-extension/src/constants.ts
packages/vscode-extension/src/extension.ts
packages/vscode-extension/src/hoverProvider.ts

When user hover over the placeholder, it will show values from all environments, with the button to open state/config file.

feat: add hover for manifest template

---

packages/sdk/src/core/teamsfx.ts
packages/sdk/test/unit/node/teamsFx.spec.ts

New feature: `TeamsFx` will load all environment variables now
BREAKING CHANGE: `TeamsFx` will not remove `TEAMSFX_` prefix in loaded environment variables. To read environment variable `TEAMSFX_MY_ENV`, you need to use `TeamsFx.getConfig('TEAMSFX_MY_ENV')` instead of `TeamsFx.getConfig('MY_ENV')`. This makes configuration set and read more consistent.

feat(SDK)!: load all env in TeamsFx

---

packages/sdk/src/conversation/middleware.ts
packages/sdk/test/unit/node/conversation/middleware.spec.ts

To fix https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/14102628/
The bot could be mentioned anywhere with different conversation ids, so cannot be persisted.
E2E TEST: N/A, covered by unit test

fix: remove BotMessaged from notification sdk

---

packages/fx-core/src/common/local/portChecker.ts
packages/fx-core/tests/common/local/portChecker.test.ts

Fix https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/14124366
In case `detect-port` hangs, add 10 seconds timeout to skip port check.
E2E TEST: N/A, covered by unit test

fix: add timeout to port detect

---

templates/function-base/js/default/package.json
templates/function-base/ts/default/package.json

The connection existing api feature requires latest SDK. This PR enables auto version sync for function template.

chore: use latest sdk in function template

---

packages/fx-core/resource/package.nls.json
packages/vscode-extension/package.nls.json
packages/vscode-extension/src/progressHandler.ts
packages/vscode-extension/src/qm/vsc_ui.ts

1> Remove the '[Teams Toolkit]' prefix to avoid truncated output link(Also a feedback from vscode to UX)
2> There's already 'details' link to output window and the one introduced in https://github.com/OfficeDev/TeamsFx/pull/4480 will duplicate the link. So remove the original one
Before:
After:
ADO:
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/14000243
E2E TEST: na

fix: refine spfx progress bar

---

packages/fx-core/templates/plugins/resource/apiconnector/sample/js/aad.template
packages/fx-core/templates/plugins/resource/apiconnector/sample/ts/aad.template
packages/fx-core/tests/plugins/resource/apiconnector/expectedFiles/js/aad
packages/fx-core/tests/plugins/resource/apiconnector/expectedFiles/js/aad-existing-app
packages/fx-core/tests/plugins/resource/apiconnector/expectedFiles/ts/aad
packages/fx-core/tests/plugins/resource/apiconnector/expectedFiles/ts/aad-existing-app

In ts strict mode, the sample will build failure due to some type check problem.

chore: update call api sample to support strict mode

---

packages/fx-core/src/plugins/resource/bot/index.ts
packages/fx-core/src/plugins/resource/bot/question.ts
packages/fx-core/tests/plugins/resource/bot/unit/question.test.ts

Display notification host type in `option.label` in CLI because CLI does not have `option.description`.

chore: improve wordings for CLI

---

packages/fx-core/resource/package.nls.json
packages/fx-core/src/plugins/resource/bot/azureOps.ts
packages/fx-core/src/plugins/resource/bot/constants.ts
packages/fx-core/src/plugins/resource/bot/errors.ts
packages/fx-core/src/plugins/resource/bot/functionsHostedBot/plugin.ts
packages/fx-core/src/plugins/resource/bot/plugin.ts
packages/fx-core/src/plugins/resource/bot/resources/messages.ts
packages/fx-core/src/plugins/resource/bot/utils/common.ts
packages/fx-core/src/plugins/resource/bot/utils/zipDeploy.ts
packages/fx-core/src/plugins/resource/bot/v3/index.ts
packages/fx-core/tests/plugins/resource/bot/unit/index.test.ts
packages/fx-core/tests/plugins/resource/bot/unit/utils/zipDeploy.test.ts

A limit of app service is that the deploy API will response 500 (Request Timed Out) after approx 230s. Now the first-time deployment may spend about 8 mins. Our solution is to use the [async zip deployment API]((https://github.com/projectkudu/kudu/wiki/Deploying-from-a-zip-file-or-url)) to check the deployment status.
Detail: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/14103329/

fix(bot): use async deployment api

---

packages/vscode-extension/package.json

Fix CD error that "@types/vscode ^1.64.0 greater than engines.vscode ^1.58.0."
E2E TEST: N/A

fix(vsc): upgrade lowest vscode engine version

---

packages/fx-core/src/plugins/resource/apiconnector/errors.ts
packages/vscode-extension/src/handlers.ts

https://dev.azure.com/msazure/Microsoft%20Teams%20Extensibility/_workitems/edit/14171495
fx-core already sendTelemetryEvent once, and showErrorMsg, no need to do again on extension handler

perf: update msg

---

templates/bot/ts/command-and-response/package.json
templates/bot/ts/notification-function-base/package.json
templates/bot/ts/notification-restify/package.json

Fix https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/14171601
There are build failures when using @types/fs-extra 9 and @types/node <= 12.
Force command/notification templates to use @types/node 14 to avoid such errors. (Here uses 14 since our toolkit recommends Node 14)

fix: add @types/node hint

---

packages/fx-core/src/plugins/resource/bot/azureOps.ts
packages/fx-core/src/plugins/resource/bot/constants.ts

fix the comments in PR: https://github.com/OfficeDev/TeamsFx/pull/4720
If `always on` is enabled, the deployment will never be timeout. 
If `always on` is closed, the deployment will be timeout after 20 min. https://github.com/projectkudu/kudu/wiki/Investigating-issues#deployment-process-got-terminated-due-to-idle-timeout

fix(bot): set deploy timeout to 20 min

---

packages/fx-core/resource/aad-manifest-change-logs.md
packages/fx-core/src/core/middleware/aadManifestMigration.ts

1. Do not show modal dialog when open old project
2. Generate aad-manifest-change-logs.md file after migration success
3. Add learn more button

perf(aad-manifest): update aad manifest migration middleware

---

packages/fx-core/src/plugins/solution/fx-solution/debug/scaffolding.ts
packages/fx-core/src/plugins/solution/fx-solution/debug/util/settings.ts
packages/fx-core/tests/plugins/solution/debug/solution.debug.scaffolding.test.ts

Fix this bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_sprints/taskboard/AuthAndData/Microsoft%20Teams%20Extensibility/CY22-4.2?workitem=14171623
Due to limitation of VSCode, we can only partially disable intellisense using empty JSON schema, see this issue for details: https://github.com/microsoft/vscode/issues/63270
Use empty JSON schema in VSCode settings.json file:
```
{
"json.schemas": [
{
"fileMatch": [
"/aad.*.json"
],
"schema": {}
}
]
}
```

perf(aad-manifest): partially disable aad manifest json intellisense

---

packages/cli/src/cmds/add.ts
packages/cli/src/cmds/index.ts
packages/cli/src/index.ts
packages/cli/tests/commonlib/cliHelper.ts
packages/cli/tests/e2e/command/argumentCheck.tests.ts
packages/cli/tests/e2e/command/helpInfo.tests.ts
packages/fx-core/src/common/constants.ts
packages/fx-core/src/common/featureFlags.ts
packages/fx-core/src/plugins/solution/fx-solution/v2/getQuestions.ts
packages/vscode-extension/package.json
packages/vscode-extension/package.nls.json
packages/vscode-extension/src/constants.ts
packages/vscode-extension/src/extension.ts
packages/vscode-extension/src/handlers.ts
packages/vscode-extension/src/treeview/treeViewManager.ts
packages/vscode-extension/src/utils/commonUtils.ts

1. Clean VS Code configuration and wording.
2. Move tutorial command under feature flag control.
Related AzDO bug: 14176509, 14176540

fix(vsc+core+cli): tutorial entry and feature flags

---

packages/adaptivecards-tools-sdk/package.json

Some of the declaration files in adaptivecards-tools has error. This can be fixed by changing @type/react from devDependency to dependency.

fix(adaptivecards-tools): change @type/react from devDependency to dependency

---

packages/fx-core/src/plugins/solution/fx-solution/v2/utils.ts
packages/fx-core/tests/plugins/solution/solution.util.test.ts

Fix these bugs:
[Bug 14177017](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/14177017): No AAD Manifest for MetaOS Apps and SSO is broken
[Bug 14177047](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/14177047): SSO should not be added to MetaOS Tab app

perf(aad-manifest): fix m365 sso tab doesn't work issue

---

templates/function-base/js/default/package.json
templates/function-base/ts/default/package.json

Add api feature requires latest SDK version.
Since our stable release does not require latest SDK version, merge main to ga changed the SDK version in ga branch. So update function scaffolding template to use latest SDK again.

chore: upgrade function template sdk version

---

packages/fx-core/src/core/middleware/concurrentLocker.ts

Workaround for this bug: 14225849
When executing commands like provisioning, and then open manifest template, it will has some acquire lock errors in output window. But when provisioning done, the real value will show successfully.
So change the log level to avoid this terrifying logs.
Before:
After:

fix: avoid error log when opening manifest template while provisioning

---

packages/vscode-extension/package.json
packages/vscode-extension/src/extension.ts
packages/vscode-extension/src/handlers.ts
packages/vscode-extension/src/treeview/treeViewManager.ts
packages/vscode-extension/src/utils/commonUtils.ts

Enable in VS Code and will update `isPreviewFeaturesEnabled()` in fx-core after E2E tests are all fixed.

chore(vsc): enable preview feature by default

---

packages/fx-core/src/plugins/solution/fx-solution/v2/provisionLocal.ts

After added SSO to an embed existing app, the plugin `fx-resource-aad-app-for-teams` also needs to be loaded to provision AAD app for local environment.
The projectSettings.json will be like:
```
{
"appName": "myapp",
"projectId": "9519ed3e-357c-44ff-8b0c-7da651f9f07b",
"version": "2.1.0",
"solutionSettings": {
"name": "fx-solution-azure",
"version": "1.0.0",
"hostType": "Azure",
"capabilities": [
"TabSSO"
],
"azureResources": [],
"activeResourcePlugins": [
"fx-resource-aad-app-for-teams"
]
}
}
```
E2E TEST: https://github.com/OfficeDev/TeamsFx/blob/01d6a9fb35d8418a3cec89a96949325bcbbea968/packages/cli/tests/e2e/existingapp/TestCreateExistingTab.tests.ts#L17

fix(existing-tab): load active plugins

---

templates/bot/js/notification-function-base/README.md
templates/bot/js/notification-restify/README.md
templates/bot/js/notification-restify/src/index.js
templates/bot/js/notification-trigger-http/src/httpTrigger.js
templates/bot/ts/notification-function-base/README.md
templates/bot/ts/notification-restify/README.md
templates/bot/ts/notification-restify/src/index.ts
templates/bot/ts/notification-trigger-http/src/httpTrigger.ts

The scaffolded http trigger does not have auth, we need tell users they should add auth for the http trigger before using it for production purpose.

docs: add auth notice for notification bot

---

templates/bot/js/notification-function-base/README.md
templates/bot/js/notification-restify/README.md
templates/bot/ts/notification-function-base/README.md
templates/bot/ts/notification-restify/README.md

Add Incoming Webhook sample reference to notification bot readme, to let user know there's an alternative.
For: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/14195884/

chore: adjust notification readme

---

packages/fx-core/src/common/deps-checker/internal/nodeChecker.ts

Fix [bug](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/14234230)
E2E TEST: N/A

fix: remove Node v10 from versions supported by SPFx

---

packages/fx-core/templates/plugins/resource/cicd/azdo/cd.yml
packages/fx-core/templates/plugins/resource/cicd/jenkins/Jenkinsfile.cd

Bug: https://dev.azure.com/msazure/Microsoft%20Teams%20Extensibility/_workitems/edit/14236128
Use CI_ENABLED=true to cover:
1. M365 login by env vars.
2. Make CLI non-interactive.

chore(cicd): set ci_enabled for azure projects

---

packages/cli/src/cmds/capability.ts
packages/cli/src/cmds/preview/errors.ts
packages/cli/tests/commonlib/constants.ts
packages/cli/tests/e2e/m365/CreateMessagingExtension.tests.ts
packages/cli/tests/e2e/solution/AddCapabilities_MEAddTab.tests.ts
packages/cli/tests/e2e/solution/AddCapabilities_TabAddME.tests.ts
packages/cli/tests/unit/cmds/capability.tests.ts
packages/fx-core/src/plugins/solution/fx-solution/question.ts

Bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/14264635
E2E TEST: https://github.com/OfficeDev/TeamsFx/runs/6204077904?check_suite_focus=true

chore(cli): rename messaging extension to message extension

---

packages/sdk/package-lock.json
packages/sdk/package.json

Use latest axios release which has some impactful breaking change (especially on error handling) and security fixes. The release note can be found here: https://github.com/axios/axios/releases
Using latest release will avoid introducing such breaking change in the future.

chore: use latest version of axios

---

packages/fx-core/src/plugins/solution/fx-solution/v2/executeUserTask.ts

Update:
Call addSso when adding function in sso not enabled projects. Thus we will have code sample added and also telemetry for add sso.
Fix bug:
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_sprints/taskboard/AuthAndData/Microsoft%20Teams%20Extensibility/CY22-4.2?workitem=14273584
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_sprints/taskboard/AuthAndData/Microsoft%20Teams%20Extensibility/CY22-4.2?workitem=14273586

perf(add sso): call addSso when add func

---

templates/tab/js/default/package.json
templates/tab/js/m365/package.json
templates/tab/js/non-sso/package.json
templates/tab/ts/default/package.json
templates/tab/ts/m365/package.json
templates/tab/ts/non-sso/package.json

Upgrades react-scripts to 5.0 to fix:
1. vulnerabilities
1. https://github.com/OfficeDev/TeamsFx/issues/3929
E2E TEST: https://github.com/OfficeDev/TeamsFx/blob/55566067b0a3a1a6838b686e1be492de5603dd8b/packages/cli/tests/e2e/frontend/TestCreateTab.tests.ts#L27

fix(tab): upgrade react-scripts to fix vulnerability

---

packages/fx-core/src/plugins/resource/bot/configs/teamsBotConfig.ts
packages/fx-core/tests/plugins/resource/bot/unit/configs/teamsBotConfig.test.ts

For GA we also support adding features of legacy bot.
Fix https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/14280060/
E2E TEST: n/a covered by unit test

fix: add features for legacy bot

---

packages/fx-core/src/plugins/solution/fx-solution/v2/executeUserTask.ts
packages/fx-core/src/plugins/solution/fx-solution/v2/getQuestions.ts

Fix bug: Readme for add sso will not automatically open when adding sso in add function
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_sprints/taskboard/AuthAndData/Microsoft%20Teams%20Extensibility/CY22-4.2?workitem=14273851

perf(add sso): open add sso readme when add sso in add function

---

packages/sdk/src/credential/teamsUserCredential.browser.ts

Fix https://github.com/OfficeDev/TeamsFx/issues/4859
There seems an issue from Teams SDK: https://github.com/OfficeDev/microsoft-teams-library-js/issues/473
Refer to the previous code logic:  https://github.com/OfficeDev/TeamsFx/blob/44ed5ea97551d6abba1c46a891f74bae163e68b2/packages/sdk/src/util/utils.ts#L92, try to handle when `result` is an `object` instead of a `string`.
E2E TEST: N/A

fix(sdk): handle Json paring for Android

---

templates/bot/js/command-and-response/package.json
templates/bot/ts/command-and-response/package.json

Fix [Bug 14276120](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/14276120): Remove unused dependency in scaffolding template

chore(template): remove unused npm dependencies in command bot

---

packages/sdk-react/tsconfig.json

Fixing the source map error in tab app templates caused by @microsoft/teamsfx-react after upgrading to CRA5.
According to https://github.com/facebook/create-react-app/discussions/11767, the `sourcemap` config is disabled.

chore(react): disable sourcemap generation

---

packages/fx-core/src/common/samples-config.json
packages/vscode-extension/src/controls/SampleGallery.scss

1. fix sample gallery layout for 'incoming webhook notification' and 'graph connector app'
2. remove proactive message app which is reverted unexpectedly when merging to ga
Note: the resources of 'Adaptive card notification' and 'incoming webhook notification' will be added by sample owner later
After:
ADO:
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/14344432
E2E TEST: NA

fix: adjust sample gallery layout and remove proactive sample

---

packages/fx-core/templates/plugins/resource/apiconnector/package.json

api connector plugin should use latest SDK version in next release

chore: revert sdk change from main branch

---

packages/sdk/src/conversation/middleware.ts
packages/sdk/test/unit/node/conversation/middleware.spec.ts
templates/bot/js/notification-restify/src/index.js
templates/bot/ts/notification-restify/src/index.ts

Fix:
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/14291987/
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/14336323/
- Support `BotMessaged` for personal and group chat, as a fix of empty `installations()`
- Support default parsers in `api/notification` request handler
E2E TEST: covered by UI test

fix: fix notification sdk and template

---

packages/fx-core/src/common/featureFlags.ts
packages/fx-core/src/core/question.ts
packages/fx-core/tests/core/question.test.ts
packages/vscode-extension/src/handlers.ts

Due to the latest decision from PM side, "embed existing app" will be hide from UI and Tutorial.
work item: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/14355354/
E2E TEST: https://github.com/OfficeDev/TeamsFx/blob/01d6a9fb35d8418a3cec89a96949325bcbbea968/packages/cli/tests/e2e/existingapp/TestCreateExistingTab.tests.ts#L17

fix(existing-app): hide embed existing app from UI and Tutorial

---

templates/tab/js/non-sso/src/components/App.jsx
templates/tab/ts/non-sso/src/components/App.tsx

Fix the bug [14290637](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/14290637/). useless bracket in tab config description after add app to a chat or a team.
E2E TEST: https://github.com/OfficeDev/TeamsFx/blob/6ea4ac9e4d603118b47ccc8e6bae8638c6a23ea2/packages/cli/tests/e2e/frontend/TestCreateTab.tests.ts#L38

fix(tab): remove extra bracket

---

packages/vscode-extension/README.md
templates/bot/js/default/README.md
templates/bot/js/default/teamsBot.js
templates/bot/js/m365/README.md
templates/bot/js/m365/teamsBot.js
templates/bot/ts/default/README.md
templates/bot/ts/default/teamsBot.ts
templates/bot/ts/m365/README.md
templates/bot/ts/m365/teamsBot.ts

Update naming for scaffold template from bot plugin
Error message is already handled by Localization Team
Still need to sync with Teams team about the interface which contains the naming 'messaging extension'
Like 'handleTeamsMessagingExtensionQuery'

chore: rename messaging extension to message extension

---

packages/cli/tests/e2e/multienv/TestRemoteHappyPath.tests.ts

Fix E2E Test for  tests/e2e/multienv/TestRemoteHappyPath.tests.ts.
Preview features are enabled by default in this branch and the previous flag check is incorrect and removed.
Triggered action: https://github.com/OfficeDev/TeamsFx/actions/runs/2298092538

fix: assume preview features enabled

---

packages/cli/package-lock.json
packages/cli/src/cmds/add.ts
packages/cli/src/cmds/capability.ts
packages/cli/src/cmds/resource.ts
packages/cli/src/userInteraction.ts
packages/cli/tests/commonlib/constants.ts
packages/cli/tests/e2e/bot/BotAddTab.tests.ts
packages/cli/tests/e2e/manifest/addCapability.tests.ts
packages/cli/tests/e2e/solution/AddCapabilities_BotAddTab.tests.ts
packages/cli/tests/e2e/solution/AddCapabilities_MEAddTab.tests.ts
packages/cli/tests/unit/cmds/addApiConnection.tests.ts
packages/cli/tests/unit/cmds/addCICD.tests.ts
packages/cli/tests/unit/cmds/addSso.tests.ts
packages/cli/tests/unit/cmds/index.tests.ts

1. Change the descriptions of `teamsfx add -h`.
2. Add `teamsfx add sso-tab` if the preview feature flag opens.
3. Remove the meaningless prefix of capabilities when running `teamsfx new`.
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/14378128
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/14378135
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/14378149
E2E TEST: https://github.com/OfficeDev/TeamsFx/actions/runs/2297896401 the failures are not caused by this PR.

fix: missing commands and descriptions of teamsfx add

---

packages/fx-core/src/plugins/resource/frontend/resources/errors.ts
packages/fx-core/src/plugins/resource/function/resources/errors.ts

E2E TEST: https://github.com/OfficeDev/TeamsFx/blob/3506843d440df397868ecde66760343708337a37/packages/cli/tests/e2e/frontend/TestCreateTab.tests.ts#L86
Frontend plugin or function plugin throw error without error message:
```
a Suggestions: Run 'npm run build' in the folder: 'tabs'. Check log for more information.
```
should be
```
Failed to build Tab app. Suggestions: Run 'npm run build' in the folder: 'tabs'. Check log for more information.
```

fix: error message is omitted

---

packages/api/src/schemas/envConfig.json
packages/fx-core/resource/package.nls.json
packages/fx-core/src/plugins/resource/aad/aadAppClient.ts
packages/fx-core/src/plugins/resource/aad/errors.ts
packages/fx-core/src/plugins/resource/aad/plugin.ts
packages/fx-core/src/plugins/resource/aad/utils/configs.ts
packages/fx-core/tests/plugins/resource/aad/unit/aadAppClient.test.ts
packages/fx-core/tests/plugins/resource/aad/unit/index.test.ts

For existing aad app scenario, allow user only input "objectId", "clientId" and "clientSecret" without "accessAsUserScopeId"
```json
"auth": {
"objectId": "58ad2e68-f442-4f6c-9282-xxx",
"clientId": "c075d7a2-29c8-4d2b-8609-xxx",
"clientSecret": "xxx",
"accessAsUserScopeId": "xxx" // now this property is optional
}
```
Automatically generate `accessAsUserScopeId` will following the sequence below:
1. Try to find it from "auth" config
2. Try to find it from state.xxx.json file
3. Try to find it from remote aad app
4. Generate a new one

perf(aad-manifest): automatically create or use existing scope id

---

docs/sdk/teamsfx.messagebuilder.attachadaptivecard.md
packages/sdk/review/teamsfx.api.md
packages/sdk/src/conversation/messageBuilder.ts

Fix incorrect type constraints in adaptive card builder api, otherwise it will break current notification/command bot template that use `CardModel`.

chore: incorrect type constraints in adaptive card builder api

---

packages/vscode-extension/src/qm/vsc_ui.ts

Related bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/14414796
Fixing effect:
1. choose 'Bot'.
2. go back.
E2E TEST: N/A

fix(vsc): reorder logic for default option in quickpick

---

packages/vscode-extension/src/extension.ts
packages/vscode-extension/src/handlers.ts
packages/vscode-extension/src/telemetry/extTelemetry.ts
packages/vscode-extension/src/telemetry/extTelemetryEvents.ts

Telemetry events are not sent in `deactivate()` function. Cache it locally and resend next time.

chore(vsc): cache telemetry event during deactivation

---

packages/cli/tests/e2e/existingapp/TestCreateExistingTab.tests.ts
packages/fx-core/src/core/middleware/questionModel.ts

Before:
After:
E2E Result: https://github.com/OfficeDev/TeamsFx/actions/runs/2329233226
E2E TEST: https://github.com/OfficeDev/TeamsFx/blob/01d6a9fb35d8418a3cec89a96949325bcbbea968/packages/cli/tests/e2e/existingapp/TestCreateExistingTab.tests.ts#L17

fix(cli): hide option for existing tab endpoint

---

packages/fx-core/src/core/error.ts

1. Move unify config cancel error message to normal place.

chore: update unify cancel error

---

packages/dotnet-sdk/src/TeamsFx/Conversation/NotificationBot.cs

Finish the `TODO` that handles BotNotInConversationRoster error.

chore: handle BotNotInConversationRoster

---

packages/fx-core/src/plugins/resource/appstudio/plugin.ts

resolve issue: https://github.com/OfficeDev/TeamsFx/issues/5048

fix: disable HTML escape to avoid user-defined config render error

---

packages/vscode-extension/package-lock.json
packages/vscode-extension/package.json

Related bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/14482778
E2E TEST: N/A

fix(vsc): missing extension name in error events

---

packages/vscode-extension/src/treeview/account/accountTreeViewProvider.ts

Azure account only shows "signed out" and "signed in" on UI to prevent forever signing in status.
Will restore until "Azure Account" extension has fixed this issue.
Related bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/14474430
E2E TEST: N/A

fix(vsc): remove Azure signing in status on UI

---

packages/vscode-extension/src/migration/migrationTool/ts/mappings.json

teams-js 1.x has changed the `registerChangeSettingsHandler` to `registerEnterSettingsHandler` and rollback.
Add mapping from `registerChangeSettingsHandler` to `microsoftTeams.pages.config.registerChangeConfigHandler`

fix(m365): add registerChangeSettingsHandler mapping

---

packages/dotnet-sdk/src/TeamsFx/Conversation/NotificationBot.cs
packages/dotnet-sdk/src/TeamsFx/Conversation/NotificationOptions.cs
templates/bot/csharp/notification-webapi/Controllers/BotController.cs.tpl
templates/bot/csharp/notification-webapi/Program.cs.tpl
templates/bot/csharp/notification-webapi/Properties/launchSettings.json.tpl

- Add env `TEAMSFX_NOTIFICATION_LOCALSTORE_DIR` for notification local storage to support Azure Functions. (`Environment.CurrentDirectory` has different behaviors on ASP.NET Core Web API and Azure Functions)
- Make `ConversationBot` part of `BotController` to ensure it's initialized on any activity.
- Fix some typos in template

chore: improve dotnet notification

---

packages/cli/tests/e2e/frontend/CanScaffoldDotNetProject.tests.ts

The default template for dotnet projects doesn't have Program.cs now.  Change the assertion to fix the case.

test: fix e2e test case for dotnet

---

packages/fx-core/src/common/local/microsoftTunnelingError.ts
packages/fx-core/src/common/local/microsoftTunnelingManager.ts
packages/fx-core/src/common/local/microsoftTunnelingService.ts
packages/fx-core/tests/common/local/microsoftTunnelingManager.test.ts
packages/vscode-extension/src/debug/microsoftTunnelingTask.ts

chore: use new login for tunneling

---

packages/fx-core/src/plugins/solution/fx-solution/debug/provisionLocal.ts
templates/bot/csharp/command-and-response/GettingStarted.txt
templates/bot/csharp/command-and-response/Properties/launchSettings.json.tpl
templates/bot/csharp/default/GettingStarted.txt
templates/bot/csharp/default/Properties/launchSettings.json.tpl
templates/bot/csharp/notification-webapi/GettingStarted.txt
templates/bot/csharp/notification-webapi/Properties/launchSettings.json.tpl

Distinguish dotnet bot local ports from the tab ones.
Following the [ASP.NET Core Web ports](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel/endpoints?view=aspnetcore-6.0) to use 5xxx for http and 7xxx for https.

chore: distinguish dotnet tab and bot local ports

---

packages/fx-core/src/common/local/microsoftTunnelingError.ts
packages/fx-core/src/common/local/microsoftTunnelingManager.ts
packages/fx-core/src/common/local/microsoftTunnelingService.ts
packages/fx-core/tests/common/local/microsoftTunnelingService.test.ts

Tunneling SDK uses `tunnel.accessTokens["host"/"connect"]` and `tunnel.ports` for `host.start()`.
- For the first time host start, we already passed `tokenScopes` and `includePorts` to `createTunnel` so it works. 
- For the second time host start, I forgot to set these properties for `getTunnel()`. It does not throw error and will cause HTTP timeout when actually sending request through the tunnel
Unit test passed locally. Tested second time local debug locally.

fix: fix a bug that cause second local debug to hang

---

templates/bot/csharp/command-and-response/ProjectName.csproj.tpl
templates/bot/csharp/notification-webapi/ProjectName.csproj.tpl

Update TeamsFx dotnet SDK to `0.5.0-rc` to use conversation SDK.

chore: update teamsfx sdk in command / notification bot template

---

packages/cli/src/cmds/preview/preview.ts
packages/fx-core/src/common/local/index.ts
packages/fx-core/src/common/local/tunnelingSettings.ts
packages/fx-core/src/plugins/solution/fx-solution/debug/provisionLocal.ts
packages/fx-core/src/plugins/solution/fx-solution/debug/util/tunneling.ts
packages/fx-core/tests/plugins/solution/debug/solution.debug.provisionLocal.test.ts
packages/vscode-extension/src/debug/depsChecker/vscodeHelper.ts
packages/vscode-extension/src/debug/teamsfxTaskProvider.ts
packages/vscode-extension/src/handlers.ts
packages/vscode-extension/src/utils/commonUtils.ts
packages/vscode-extension/test/unit/localdebug/depsChecker.test.ts

Fix bugs:
- `prerequisitesCheck.ngrok` is not checked when use Microsoft tunneling.
- ngrok is still installed when using Microsoft tunneling
vscode settings:
-`prerequisitesCheck.ngrok` => whether tunneling is enabled
-`tunneling` => Use MicrosoftTunneling or Ngrok
And then `inputs.tunnelingService` is set to none, microsoftTunneling or ngrok according to above vscode settings.
In core/solution, use `getTunnelingService(inputs)`. In vsc, use `getTunnelingServiceFromVSCodeSettings()`. Env variable is not used anymore.

fix: tunnel skip env checker & refactor settings

---

packages/vscode-extension/src/treeview/account/accountTreeViewProvider.ts

Root cause:
Sometimes Azure account item can show in spfx project if user start other operations before extension fully activated. This is because two actions executed at the same time and file locked by core. Thus the API call can't get correct result.
Fix:
Check SPFx folder structure in extension level to avoid concurrency issue.
Before:
E2E TEST: NA

fix: azure account ui shows for spfx project

---

packages/vscode-extension/package.json

Address this bug: 
[Bug 14473495](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/14473495): Command "Deploy Azure Active Directory app manifest" in spfx project is not hidden
E2E TEST: NA

fix: hide deploy aad manifest command in spfx project

---

packages/fx-core/src/plugins/resource/appstudio/utils/telemetry.ts

plugin.commonProperties is passed to sendTelemetry() method, and as a reference, the values will be altered.
So the success event may contain error properties, like:

fix: some success events with error properties

---

packages/vscode-extension/src/commonlib/azureLogin.ts
packages/vscode-extension/src/debug/commonUtils.ts
packages/vscode-extension/src/extension.ts
packages/vscode-extension/src/globalVariables.ts
packages/vscode-extension/src/handlers.ts
packages/vscode-extension/src/telemetry/extTelemetry.ts
packages/vscode-extension/src/treeview/account/subscriptionNode.ts
packages/vscode-extension/src/treeview/environmentTreeViewProvider.ts
packages/vscode-extension/src/utils/commonUtils.ts
packages/vscode-extension/test/unit/extension/commonUtils.test.ts
packages/vscode-extension/test/unit/extension/extTelemetry.test.ts
packages/vscode-extension/test/unit/extension/globalVariables.test.ts
packages/vscode-extension/test/unit/extension/handlers.test.ts

1. Move variables into `globalVariables.ts`.
2. Group & reorder registrations in `extension.ts:activate()`.
3. Turn `handler.ts:activate()` into synchronized function.
4. Refactor env tree to remove the data operation `reloadEnvironments()` during activation.
E2E TEST: N/A

refactor(vsc): reorganize activate()

---

templates/bot/csharp/command-and-response/.gitignore
templates/bot/csharp/notification-webapi/.gitignore

Fix [Bug 14583886](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/14583886): [VS] Should git ignore .vs folder in bot app.
Per discussion in the meeting, we will not ignore vs related items in our generated `.gitignore`.

chore(template): remove vs specific gitignore items for command/notification bot

---

packages/fx-core/src/common/tools.ts
packages/vscode-extension/package.json
packages/vscode-extension/src/extension.ts

Currently, even sso feature is not enabed, the command "deploy aad manifest" still exist in command palette.
E2E TEST: Will add test plan for this

fix: hide deploy aad manifest command when aad is not enabled

---

packages/fx-core/resource/package.nls.json
packages/fx-core/src/plugins/resource/aad/plugin.ts
packages/fx-core/src/plugins/solution/fx-solution/v2/deploy.ts

Currently, preview aad and deploy aad have different message when not provisioned:
This PR align these two messages:

perf(aad-manifest): align need provision message for deploying aad

---

packages/fx-core/src/plugins/resource/bot/v2/common.ts

Project created by Teams Toolkit older than v3.7 cannot be deployed by latest Teams Toolkit
E2E TEST: https://github.com/OfficeDev/TeamsFx/blob/54c1d932c536a8a63b00584e56196f5eb168dbfd/packages/cli/tests/e2e/bot/CanDeployToCustomizedRg.tests.ts#L37

fix(bot): set default host type for backward compatibility

---

packages/fx-core/src/common/projectSettingsHelper.ts
packages/fx-core/src/plugins/resource/aad/constants.ts
packages/fx-core/src/plugins/solution/fx-solution/v2/deploy.ts
packages/fx-core/src/plugins/solution/fx-solution/v2/getQuestions.ts
packages/vscode-extension/src/constants.ts
packages/vscode-extension/src/handlers.ts

Address this bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/14677206
Before this PR, there is no confirmation when deploy include aad: 
After this PR, there will be a confirmation message when deploy include aad (The confirmation message will only show when there are Azure resources to deploy):
Will add test plan for this

perf(aad-manifest): only show confirmation when there are Azure resources to deploy

---

packages/cli/src/cmds/config.ts
packages/cli/src/commonlib/common/cicdPlatformDetector.ts
packages/cli/src/commonlib/telemetry.ts
packages/cli/src/userSetttings.ts
packages/cli/tests/unit/telemetry/detectCICDPlatform.tests.ts

https://dev.azure.com/msazure/Microsoft%20Teams%20Extensibility/_workitems/edit/14611067
Detect which CI/CD platform Teams Toolkit CLI runs in by predefined env var in each platform.

chore: add telemetry to detect cicd platforms

---

packages/vscode-extension/package.json
packages/vscode-extension/src/extension.ts

Non-teamsfx project can also manage accounts.
Related bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/14714911
E2E TEST: N/A

fix(vsc): register azure account signin as internal command

---

templates/bot/csharp/command-and-response/Properties/launchSettings.json.tpl
templates/bot/csharp/default/Properties/launchSettings.json.tpl
templates/bot/csharp/notification-function-base/GettingStarted.txt
templates/bot/csharp/notification-function-base/ProjectName.csproj.tpl
templates/bot/csharp/notification-function-base/Properties/launchSettings.json.tpl
templates/bot/csharp/notification-webapi/GettingStarted.txt
templates/bot/csharp/notification-webapi/Properties/launchSettings.json.tpl

https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/14563789/
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/14705024/
- Comment out project-only launch profile to avoid f5 confusing
- Add *Windows Command Prompt* hint for `curl` to avoid host confusing
- Adjust func-hosted sdk version
**NO** Template Breaking Change.

chore: adjust settings for dotnet bot templates

---

packages/cli/tests/e2e/bot/ProvisionCommandAndResponseBot.tests.ts

E2E TEST: https://github.com/OfficeDev/TeamsFx/blob/187b185cd60cb481f1f4697a92be6355f2a94c53/packages/cli/tests/e2e/bot/ProvisionCommandAndResponseBot.tests.ts#L10

fix(e2e): add missing import for bot e2e test

---

packages/fx-core/src/common/local/localTelemetryReporter.ts
packages/vscode-extension/src/debug/commonUtils.ts
packages/vscode-extension/src/debug/localTelemetryReporter.ts
packages/vscode-extension/src/debug/teamsfxDebugProvider.ts
packages/vscode-extension/src/debug/teamsfxTaskHandler.ts
packages/vscode-extension/src/debug/teamsfxTaskProvider.ts
packages/vscode-extension/src/handlers.ts
packages/vscode-extension/src/telemetry/extTelemetryEvents.ts

- add debug-all/debug-all-start events
- wrap debug provider/task provider/pre-debug check with telemetry events
A success example:
An error example:
In this error case: debug-all will have error code

chore: send debug-all/debug-all-start

---

packages/vscode-extension/src/debug/commonUtils.ts
packages/vscode-extension/src/debug/localTelemetryReporter.ts
packages/vscode-extension/src/debug/teamsfxTaskHandler.ts
packages/vscode-extension/src/error.ts
packages/vscode-extension/src/telemetry/extTelemetryEvents.ts

- If some service fails before browser launching, local debug can stop now. And send 'debug-all' events.
For example, the 'Start Frontend' task fails, the debug session will stop.
[](https://user-images.githubusercontent.com/9698542/173991629-969dd34c-649f-454e-b3be-28496d532b40.png)
E2E TEST: https://github.com/OfficeDev/TeamsFx-UI-Test/blob/main/src/ui-test/localdebug/localdebug-tab.test.ts

fix: stop local debug if service failed before browser

---

packages/vscode-extension/src/treeview/account/subscriptionNode.ts

Related bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/14739456
E2E TEST: N/A

fix(vsc): refresh subscription node when it's empty

---

packages/vscode-extension/src/debug/prerequisitesHandler.ts
packages/vscode-extension/src/error.ts

Fix bugs
- All prereqs check account errors (like UserCancel) are sent as `PrerequsiteValidationError`. This PR makes these different errors distinguishable from telemetry.
- UserCancel was previously wrapped as SystemError `No M365 account login`. But it is not system error
test:

fix: prereqs check account error code
