OfficeDev/teams-toolkit

- templates/csharp/default-bot/Bot/EchoBot.cs.tpl
- templates/js/default-bot/teamsBot.js
- templates/ts/default-bot/teamsBot.ts
update ts/js echo bot template.
also fix https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25106988/?view=edit
> refactor: update echo bot template

- Localize/loc/cs/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/es/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/it/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/ja/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/ko/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/pt-BR/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/zh-Hans/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/zh-Hant/packages/fx-core/resource/package.nls.json.lcl
LEGO: Pull request from juno/hb_fd34cb3d-1ea5-4a7c-8a66-721a44a97af3_20230908144719169 to dev with localized lcls
> chore(localization): [LEGO] Pull request from juno/hb_fd34cb3d-1ea5-4a7c-8a66-721a44a97af3_20230908144719169 to dev

- Localize/loc/de/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/fr/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/pl/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/ru/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/tr/packages/fx-core/resource/package.nls.json.lcl
LEGO: Pull request from juno/hb_fd34cb3d-1ea5-4a7c-8a66-721a44a97af3_20230909144610496 to dev with localized lcls
> chore(localization): [LEGO] Pull request from juno/hb_fd34cb3d-1ea5-4a7c-8a66-721a44a97af3_20230909144610496 to dev

- packages/fx-core/src/question/other.ts
- packages/tests/src/e2e/README.md
- packages/tests/src/e2e/bot/BotHappyPathCommon.ts
- packages/tests/src/e2e/bot/CommandBotHappyPathCommon.ts
- packages/tests/src/e2e/bot/NotificationBotHappyPathCommon.ts
- packages/tests/src/e2e/bot/WorkflowBotHappyPathCommon.ts
- packages/tests/src/e2e/frontend/BasicTabHappyPath.tests.ts
- packages/tests/src/e2e/frontend/BlazorAppHappyPath.tests.ts
- packages/tests/src/e2e/frontend/CanDeployToCustomizedRg.tests.ts
- packages/tests/src/e2e/frontend/TestCreateTab.tests.ts
- packages/tests/src/e2e/m365/DebugOboTab.tests.ts
- packages/tests/src/e2e/samples/sampleCaseFactory.ts
- packages/tests/src/e2e/spfx/AddSPFxTabV3.tests.ts
- packages/tests/src/e2e/spfx/CreateSPFxProject.tests.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25124500
https://github.com/OfficeDev/TeamsFx/actions/runs/6144254095
> fix: e2e test for environment manager

- templates/ts/spfx-tab-import/.vscode/launch.json
- templates/ts/spfx-tab-import/src/README.md
- templates/ts/spfx-tab/.vscode/launch.json
- templates/ts/spfx-tab/src/README.md
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25076825
> refactor: rename hosted workbench to SharePoint workbench

- packages/fx-core/src/component/utils/ResourceGroupHelper.ts
- packages/fx-core/src/error/azure.ts
- packages/fx-core/src/error/deploy.ts
fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25136368
> fix: resource group error should not report requrest data in telemetry

- packages/fx-core/src/question/inputs/CreateProjectInputs.ts
- forgot to run gen:cli in PR https://github.com/OfficeDev/TeamsFx/pull/9871/files#diff-a94fabfb19e886033049652f0059cc716eb4d344f68dc8cdb65ef17f8612eb13
> fix: run gen:cli

- packages/vscode-extension/package-lock.json
- packages/vscode-extension/package.json
- packages/vscode-extension/src/commonlib/azureLogin.ts
- packages/vscode-extension/webpack.config.js
Related bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25124287
> fix(vsc): remove the dependency of keytar

- templates/csharp/copilot-plugin-existing-api/GettingStarted.md
- templates/csharp/copilot-plugin-existing-api/teamsapp.yml.tpl
- templates/csharp/copilot-plugin-from-oai-plugin/GettingStarted.md
- templates/csharp/copilot-plugin-from-oai-plugin/teamsapp.yml.tpl
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25123386
> fix(vs): copilot templates' readme and add extendToM365

- packages/fx-core/resource/package.nls.json
- packages/fx-core/src/component/driver/teamsApp/clients/appStudioClient.ts
- packages/fx-core/src/component/driver/teamsApp/errors.ts
- packages/fx-core/tests/component/driver/teamsApp/appstudioclient.test.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25106790
> fix: refine publsih error

- packages/cli/src/index.ts
fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25151747
> fix: hide deprecate warning for cli

- templates/csharp/ai-bot/GettingStarted.md
- templates/csharp/ai-bot/env/.env.dev.user
> refactor: update vs ai bot template readme

- packages/fx-core/src/component/driver/teamsApp/validateAppPackage.ts
- packages/fx-core/src/core/FxCore.ts
- packages/fx-core/src/core/telemetry.ts
1) Validate
```
[2023-09-13T11:01:39.476] [DEBUG] TelemTest - teamsApp/validateAppPackage {
'project-id': 'a279e353-3a8f-43ac-8ad9-ef212a103e80',
component: 'teamsAppvalidateAppPackage',
id: '7c3ff0f2-e1c7-452a-abee-550215f254c9',
version: '1.0.0',
capabilities: 'MessageExtension',
manifestVersion: 'devPreview',
isCopilotPlugin: true,
isSPFx: false,
'validation-errors': 'composeExtensions[0].composeExtensionType;composeExtensions[0].apiSpecificationFile;composeExtensions[0].commands[0].apiResponseRenderingTemplateFile;composeExtensions[0].commands[1].apiResponseRenderingTemplateFile;composeExtensions[0]',
success: 'no',
'error-code': 'AppStudioPlugin.ManifestValidationFailed',
'error-type': 'user',
'error-message': 'Teams Toolkit has completed checking your app package against validation …
```
> refactor: add telemetries for copilot actions

- packages/cli/package.json
- packages/cli/src/commands/engine.ts
- packages/cli/src/error.ts
- packages/cli/tests/unit/engine.tests.ts
- pnpm-lock.yaml
fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25154770
> fix: suggest similar command when misspelled

- packages/fx-core/src/component/error/componentError.ts
- packages/fx-core/tests/component/error/componentError.test.ts
fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25136255
> fix: fix error source contains slash

- Localize/loc/cs/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/cs/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/de/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/de/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/es/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/es/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/fr/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/fr/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/it/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/it/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/ja/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/ja/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/ko/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/ko/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/pl/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/pl/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/pt-BR/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/pt-BR/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/ru/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/tr/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/tr/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/zh-Hans/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/zh-Hans/packages/vscode-extension/package.nls.json.lcl
- Localize/loc/zh-Hant/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/zh-Hant/packages/vscode-extension/package.nls.json.lcl
LEGO: Pull request from juno/hb_fd34cb3d-1ea5-4a7c-8a66-721a44a97af3_20230913144606013 to dev with localized lcls
> chore(localization): [LEGO] Pull request from juno/hb_fd34cb3d-1ea5-4a7c-8a66-721a44a97af3_20230913144606013 to dev

- packages/fx-core/src/common/samples.ts
- packages/fx-core/tests/common/samples.test.ts
- packages/fx-core/tests/component/generator/generator.test.ts
- packages/vscode-extension/src/controls/sampleGallery/ISamples.ts
- packages/vscode-extension/src/controls/sampleGallery/sampleCard.tsx
- packages/vscode-extension/src/controls/sampleGallery/sampleDetailPage.tsx
Related task: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25104926
Related PR: https://github.com/OfficeDev/TeamsFx-Samples/pull/1026
Effect Preview:
> feat(vsc): show sample thumbnail in sample gallery

- Localize/loc/cs/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/de/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/es/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/fr/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/it/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/pt-BR/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/ru/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/tr/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/zh-Hans/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/zh-Hant/packages/fx-core/resource/package.nls.json.lcl
LEGO: Pull request from juno/hb_fd34cb3d-1ea5-4a7c-8a66-721a44a97af3_20230914144357797 to dev with localized lcls
> chore(localization): [LEGO] Pull request from juno/hb_fd34cb3d-1ea5-4a7c-8a66-721a44a97af3_20230914144357797 to dev

- packages/cli/src/error.ts
fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25154770
> fix: unknown command error string

- packages/cli/tests/unit/engine.tests.ts
- packages/fx-core/src/common/featureFlags.ts
- packages/fx-core/tests/common/featureFlags.test.ts
- packages/fx-core/tests/ui/qm.visitor.test.ts
fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25164547
> fix: enable CLI new UX feature flag

- packages/cli/src/prompts/customizedCheckboxPrompt.ts
- packages/cli/src/userInteraction.ts
- packages/cli/tests/unit/prompts/customizedCheckboxPrompt.tests.ts
- packages/fx-core/resource/package.nls.json
- packages/fx-core/src/component/generator/copilotPlugin/generator.ts
- packages/fx-core/src/question/create.ts
- packages/vscode-extension/src/qm/vsc_ui.ts
- show validation errors if multiSelect question
CLI example:
> fix: vsc/cli validation errors if multi select question

- Localize/loc/ja/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/ko/packages/fx-core/resource/package.nls.json.lcl
- Localize/loc/pl/packages/fx-core/resource/package.nls.json.lcl
LEGO: Pull request from juno/hb_fd34cb3d-1ea5-4a7c-8a66-721a44a97af3_20230915144323584 to dev with localized lcls
> chore(localization): [LEGO] Pull request from juno/hb_fd34cb3d-1ea5-4a7c-8a66-721a44a97af3_20230915144323584 to dev

- packages/fx-core/src/common/deps-checker/internal/testToolChecker.ts
- packages/fx-core/tests/common/deps-checker/testToolChecker.test.ts
> feat: check npm & node version in testToolChecker

- packages/fx-core/src/common/samples.ts
- packages/fx-core/tests/common/samples.test.ts
- packages/vscode-extension/src/controls/sampleGallery/ISamples.ts
- packages/vscode-extension/src/controls/sampleGallery/SampleGallery.tsx
- packages/vscode-extension/src/controls/webviewPanel.ts
Related PR: https://github.com/OfficeDev/TeamsFx/pull/9935
> fix(vsc): sample gallery catches exception

- packages/fx-core/src/component/driver/teamsApp/clients/appStudioClient.ts
- packages/fx-core/src/component/driver/teamsApp/errors.ts
- packages/fx-core/src/error/teamsApp.ts
- packages/fx-core/tests/component/driver/teamsApp/appstudioclient.test.ts
- packages/fx-core/tests/component/resource/botService/appStudioClient.test.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25106793
> refactor: add categories to error

- packages/fx-core/src/core/FxCore.ts
- packages/fx-core/tests/core/FxCore.test.ts
[Bug 25204270](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25204270): [API ME] Add another API throws error 
[Bug 25167036](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25167036): [API ME] Notification after adding another API is incorrect
> fix: add another API

- packages/tests/src/e2e/command/template.tests.ts
- packages/tests/src/utils/executor.ts
fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25204710
> fix: e2e test for 'teamsfx add' and 'teamsfx new sample'

- packages/fx-core/src/common/featureFlags.ts
Will merge after bits cut for Sept prerelease
> refactor: turn on API_COPILOT by default for Oct

- packages/cli/src/commands/models/validate.ts
fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25204710
> fix(cli): teamfx validate cmd have default value

- packages/fx-core/src/component/generator/generator.ts
fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25214937
> fix: fetch sample config

- packages/cli/src/commands/models/updateAadApp.ts
- packages/cli/src/commands/models/updateTeamsApp.ts
- packages/cli/tests/unit/commands.tests.ts
- packages/fx-core/src/question/inputs/CreateProjectInputs.ts
- packages/fx-core/src/question/options/DeployAadManifestOptions.ts
- packages/fx-core/src/question/options/PermissionGrantOptions.ts
- packages/fx-core/src/question/options/PermissionListOptions.ts
- packages/fx-core/src/question/options/PreviewTeamsAppOptions.ts
- packages/fx-core/src/question/options/SPFxAddWebpartOptions.ts
- packages/fx-core/src/question/options/SelectTeamsManifestOptions.ts
- packages/fx-core/src/question/options/ValidateTeamsAppOptions.ts
- packages/fx-core/src/question/other.ts
- packages/fx-core/tests/question/question.test.ts
- packages/tests/src/e2e/collaboration/Permission.tests.ts
- packages/tests/src/e2e/collaboration/PermissionSPFX.tests.ts
- packages/tests/src/e2e/upgrade/happyPath.tests.ts
fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25204710
> fix: teamsfx update teams-app and aad-app for e2e test

- packages/cli/src/commands/models/create.ts
- packages/cli/tests/unit/commands.tests.ts
- packages/fx-core/src/question/create.ts
- packages/fx-core/src/question/inputs/CreateProjectInputs.ts
- packages/fx-core/src/question/options/CreateProjectOptions.ts
- packages/fx-core/src/question/questionNames.ts
- packages/fx-core/tests/core/FxCore.test.ts
- packages/fx-core/tests/question/create.test.ts
[Bug 25190099](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25190099): [API ME] Support OpenAI Plugin Manifest File Path in addition to Domain
> fix: OpenAI plugin manifest name for CLI

- packages/tests/scripts/pvt.json
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25176353
> fix: update uitest script

- packages/fx-core/src/common/local/localEnvManager.ts
- packages/fx-core/tests/common/local/localEnvManager.test.ts
- packages/vscode-extension/src/debug/commonUtils.ts
- packages/vscode-extension/src/debug/teamsfxTaskHandler.ts
- packages/vscode-extension/src/telemetry/extTelemetryEvents.ts
> feat: send error log telemetry if testtool fails to start

- packages/tests/src/e2e/command/template.tests.ts
https://github.com/OfficeDev/TeamsFx/actions/runs/6257684113/job/16990481610
> fix: scaffold template e2e test

- packages/fx-core/src/component/generator/generator.ts
fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25214937
> fix: hotfix fetch sample config before access it

- packages/vscode-extension/src/handlers.ts
- packages/vscode-extension/src/utils/localizeUtils.ts
- packages/vscode-extension/test/extension/utils/localizeUtils.test.ts
- packages/vscode-extension/test/extension/utils/upgrade.test.ts
ADO: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25135952
> refactor: log locale for better troubleshooting

- packages/tests/src/e2e/upgrade/incoming-webhook-notification.tests.ts
e2e test: https://github.com/OfficeDev/TeamsFx/actions/runs/6269328212
> test: update incoming-webhook-notification

- docs/cli/user-manual.md
- packages/cli/package.json
- packages/cli/src/commands/models/permission.ts
- packages/cli/src/index.ts
- packages/tests/src/e2e/collaboration/Permission.tests.ts
- packages/tests/src/e2e/collaboration/PermissionSPFX.tests.ts
fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25202429
> fix(cli): name permission command

- packages/cli/src/commands/models/m365Sideloading.ts
- packages/cli/src/commands/models/m365Unacquire.ts
fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25202429
> fix: rename m365 command

- packages/fx-core/resource/package.nls.json
- packages/fx-core/src/question/create.ts
[Bug 25232140](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25232140): Update Scaffold String for ME to Indicate it works in Copilot
> fix: msg update for Copilot

- .github/workflows/all-versions-upgrade-test.yml
- packages/cli/tests/unit/helper.tests.ts
- packages/tests/src/commonlib/cliHelper.ts
- packages/tests/src/e2e/README.md
- packages/tests/src/e2e/command/template.tests.ts
- packages/tests/src/ui-test/cliHelper.ts
- packages/tests/src/utils/executor.ts
fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25240744
> fix: rename create sample cli

- packages/server/src/serverConnection.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25215906
> feat(server): support metaos preview command

- packages/fx-core/src/common/telemetry.ts
- packages/fx-core/src/component/resource/botService/appStudio/appStudioClient.ts
> refactor: add botid to telemetry property

- packages/fx-core/src/common/spec-parser/adaptiveCardGenerator.ts
- packages/fx-core/src/common/spec-parser/adaptiveCardWrapper.ts
- packages/fx-core/src/common/spec-parser/constants.ts
- packages/fx-core/src/common/spec-parser/interfaces.ts
- packages/fx-core/src/common/spec-parser/manifestUpdater.ts
- packages/fx-core/src/common/spec-parser/specParser.ts
- packages/fx-core/src/common/spec-parser/utils.ts
- packages/fx-core/tests/common/spec-parser/adaptiveCardWrapper.test.ts
- packages/fx-core/tests/common/spec-parser/manifestUpdater.test.ts
- packages/fx-core/tests/common/spec-parser/specParser.test.ts
- packages/fx-core/tests/common/spec-parser/utils.test.ts
1. Fix [Bug 25216657](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25216657): previewCardTemplate update
2. Fix [Bug 25242797](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25242797): Strange default manifest value generator for OpenAPI spec plugin
3. Add description in command
> perf(spec-parser): infer previewCardTemplate support

- packages/fx-core/src/component/generator/officeAddin/generator.ts
- packages/fx-core/tests/component/generator/officeAddinGenerator.test.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25239149
> fix: office addin with "No Options" as language

- packages/fx-core/src/core/FxCore.ts
bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25270961
> fix: fix question model for check permission

- packages/fx-core/src/common/spec-parser/adaptiveCardWrapper.ts
- packages/fx-core/src/common/spec-parser/interfaces.ts
- packages/fx-core/tests/common/spec-parser/adaptiveCardWrapper.test.ts
Update image property as below:
```json
"image": {
"url": "${image_url}",
"alt": "${if(name, name, 'N/A')}",
"$when": "${image_url != null}"
}
```
> perf(spec-parser): update previewTemplateCard image property

- packages/fx-core/src/component/generator/generator.ts
- packages/fx-core/src/component/generator/generatorAction.ts
- packages/fx-core/tests/component/generator/generator.test.ts
Reverts OfficeDev/TeamsFx#9972
> revert: "refactor: modify the logic to switch to local zip when remote zip processing fails"

- packages/tests/src/e2e/collaboration/Permission.tests.ts
- packages/tests/src/e2e/collaboration/PermissionSPFX.tests.ts
bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_sprints/taskboard/AuthAndData/Microsoft%20Teams%20Extensibility/Germanium/CY23Q4/2Wk/2Wk01%20(Sep%2024%20-%20Oct%2007)?workitem=25295742
success run: https://github.com/OfficeDev/TeamsFx/actions/runs/6333158118
> test: fix e2e for collaboration

- packages/vscode-extension/src/handlers.ts
fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25297820
> fix: hide error stack for vsc

- packages/tests/src/commonlib/cliHelper.ts
- packages/tests/src/e2e/upgrade/bot-sso-sample.tests.ts
- packages/tests/src/e2e/upgrade/incoming-webhook-notification.tests.ts
e2e case: https://github.com/OfficeDev/TeamsFx/actions/runs/6438849612
https://github.com/OfficeDev/TeamsFx/actions/runs/6438860408
> test: update e2e

- packages/fx-core/src/common/spec-parser/constants.ts
- templates/csharp/copilot-plugin-from-scratch/appPackage/responseTemplates/repair.json
- templates/js/copilot-plugin-from-scratch/appPackage/responseTemplates/repair.json
- templates/ts/copilot-plugin-from-scratch/appPackage/responseTemplates/repair.json
[Bug 25369190](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25369190): [API ME] update schema property in response templates
> fix: response template schema

- packages/vscode-extension/src/utils/localizeUtils.ts
- packages/vscode-extension/test/extension/utils/localizeUtils.test.ts
ADO: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25295682
> fix: error log displayed for en-us locale

- packages/cli/src/commands/models/create.ts
- packages/cli/tests/unit/commands.tests.ts
- packages/fx-core/src/question/create.ts
- packages/fx-core/src/question/options/CreateProjectOptions.ts
[Bug 25392108](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25392108): [API ME][CLI] Missing options when new --help
> fix: API ME cli help

- templates/js/copilot-plugin-from-scratch/README.md
- templates/ts/copilot-plugin-from-scratch/README.md
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25386102
> fix: updata API ME README files

- templates/ts/non-sso-tab/package.json.tpl
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25226915
> fix: fix basic tab deploy failed

- templates/common/copilot-plugin-existing-api/README.md
- templates/common/copilot-plugin-from-oai-plugin/README.md
related to https://github.com/OfficeDev/TeamsFx/pull/10093 applying same change to templates for existing API
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25386102
> fix: readme update

- templates/common/copilot-plugin-existing-api/appPackage/manifest.json.tpl
- templates/common/copilot-plugin-from-oai-plugin/appPackage/manifest.json.tpl
- templates/csharp/copilot-plugin-existing-api/appPackage/manifest.json.tpl
- templates/csharp/copilot-plugin-from-oai-plugin/appPackage/manifest.json.tpl
- templates/csharp/copilot-plugin-from-scratch/appPackage/manifest.json.tpl
- templates/js/copilot-plugin-from-scratch/appPackage/manifest.json.tpl
- templates/ts/copilot-plugin-from-scratch/appPackage/manifest.json.tpl
[Bug 25411522](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25411522): [AP ME]Update manifest schema to the new link in templates
> fix: manifest schema update

- packages/vscode-extension/src/qm/vsc_ui.ts
- packages/vscode-extension/test/extension/qm/vsc_ui.test.ts
Related bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25392383
> fix(vsc): loading quick pick flash when there's single option

- packages/fx-core/src/common/spec-parser/adaptiveCardGenerator.ts
- packages/fx-core/src/common/spec-parser/adaptiveCardWrapper.ts
- packages/fx-core/src/common/spec-parser/interfaces.ts
- packages/fx-core/src/common/spec-parser/utils.ts
- packages/fx-core/tests/common/spec-parser/adaptiveCardGenerator.test.ts
- packages/fx-core/tests/common/spec-parser/utils.test.ts
[Bug 25282960](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25282960): Infer and generate image block in adaptive card
> perf(spec-parser): infer and generate image block in adaptive card

- packages/vscode-extension/src/controls/Commands.ts
- packages/vscode-extension/src/controls/resources.tsx
- packages/vscode-extension/src/controls/sampleGallery/ISamples.ts
- packages/vscode-extension/src/controls/sampleGallery/SampleGallery.scss
- packages/vscode-extension/src/controls/sampleGallery/SampleGallery.tsx
- packages/vscode-extension/src/controls/sampleGallery/sampleFilter.scss
- packages/vscode-extension/src/controls/sampleGallery/sampleFilter.tsx
- packages/vscode-extension/src/controls/sampleGallery/sampleListItem.scss
- packages/vscode-extension/src/controls/sampleGallery/sampleListItem.tsx
- packages/vscode-extension/src/controls/webviewPanel.ts
- packages/vscode-extension/src/telemetry/extTelemetryEvents.ts
Related task: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25297805
Light Theme Effect:
Dark Theme Effect:
> feat: sample gallery UI update part 2 - sample list view

- packages/fx-core/src/core/FxCore.ts
fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25285568
> fix: add log output when env added

- packages/fx-core/src/component/driver/teamsApp/utils/ManifestUtils.ts
- packages/fx-core/src/component/utils/common.ts
fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25425932
> fix: accept empty string for env value

- packages/tests/package.json
- pnpm-lock.yaml
dev tunnel sdk has some breaking changes, use specific sdk version
> fix: use specific dev tunnel sdk version

- packages/fx-core/src/component/configManager/lifecycle.ts
- packages/fx-core/src/component/driver/teamsApp/utils/ManifestUtils.ts
- packages/fx-core/src/component/utils/common.ts
fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25425932
> fix: enable empty string env value

- templates/ts/spfx-tab-import/.vscode/extensions.json
- templates/ts/spfx-tab/package.json
ADO: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25297602
After:
> fix: start local server for spfx local preview

- packages/fx-core/src/component/coordinator/index.ts
- packages/fx-core/tests/component/coordinator/coordinator.provision.test.ts
fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25468455
> fix: make happy path for scenario without .env.local

- packages/fx-core/src/core/FxCore.ts
fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25476870
> fix: get app name contains placeholder

- templates/js/copilot-plugin-from-scratch/.funcignore
- templates/ts/copilot-plugin-from-scratch/.funcignore
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25479751
> fix: api me deploy issue

- .github/workflows/cd.yml
https://github.com/richardsimko/update-tag/issues/30
> ci: revert update tag for for cd run

- packages/tests/src/utils/executor.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25295561
Successful run: https://github.com/OfficeDev/TeamsFx/actions/runs/6506376759
> test: fix add spfx web part e2e test

- packages/fx-core/src/component/configManager/lifecycle.ts
- packages/fx-core/src/component/utils/common.ts
- packages/fx-core/tests/component/utils.test.ts
fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25496058
> fix: only APP_NAME_SUFFIX accepts empty string

- packages/dotnet-sdk/src/TeamsFx/Microsoft.TeamsFx.csproj
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_sprints/taskboard/Teams%20Extensibility%20E2E%20Team/Microsoft%20Teams%20Extensibility/Germanium/CY23Q4/2Wk/2Wk02%20(Oct%2008%20-%20Oct%2021)?workitem=25500624
> build: update dotnet sdk dependency

- packages/fx-core/src/question/create.ts
- packages/fx-core/tests/question/create.test.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25520239
> fix(vs): dotnet caps

- packages/cli/src/commands/common.ts
fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25202433
> fix: cli option string

- templates/csharp/copilot-plugin-existing-api/GettingStarted.md
- templates/csharp/copilot-plugin-existing-api/{{ProjectName}}.csproj.tpl
- templates/csharp/copilot-plugin-from-oai-plugin/GettingStarted.md
- templates/csharp/copilot-plugin-from-oai-plugin/{{ProjectName}}.csproj.tpl
- templates/csharp/copilot-plugin-from-scratch/GettingStarted.md
Related PR: https://github.com/OfficeDev/TeamsFx/pull/10158, https://github.com/OfficeDev/TeamsFx/pull/10106
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25476570
> fix(vs): api/bot me readme

- templates/js/copilot-plugin-from-scratch/.funcignore
- templates/js/copilot-plugin-from-scratch/.vscode/launch.json
- templates/ts/copilot-plugin-from-scratch/.funcignore
- templates/ts/copilot-plugin-from-scratch/.vscode/launch.json
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25506154
> fix: api me template optimization

- packages/sdk-react/src/useTeams.ts
- packages/sdk-react/src/useTeamsUserCredential.ts
- packages/sdk-react/test/useTeams.test.tsx
- packages/sdk-react/test/useTeamsUserCredential.test.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25397469
> feat: add loading parameter to useTeams

- packages/fx-core/src/component/developerPortalScaffoldUtils.ts
- packages/fx-core/tests/component/developerPortalScaffoldUtils.test.ts
- packages/manifest/src/manifest.ts
[Bug 25251499](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25251499): [VSC]Create a Teams app with features Group and channel added from Developer Portal Local debug get m365,unhadledError
> fix: groupchat

- templates/constraints/yml/actions/aadAppCreate.mustache
- templates/constraints/yml/actions/aadAppUpdate.mustache
- templates/constraints/yml/actions/azureStorageDeploy.mustache
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25532638
> fix: constraints ci

- packages/tests/src/e2e/multienv/TestRemoteHappyPath.tests.ts
- packages/tests/src/e2e/multienv/TestRemoteHappyPathSPFx.tests.ts
Update multi env e2e test cases.
https://github.com/OfficeDev/TeamsFx/actions/runs/6610595298
> refactor: e2e multi env

- templates/csharp/default-bot/infra/azure.parameters.json.tpl
- templates/csharp/link-unfurling/infra/azure.parameters.json.tpl
- templates/csharp/message-extension-action/infra/azure.parameters.json.tpl
- templates/csharp/message-extension-copilot/infra/azure.parameters.json.tpl
- templates/csharp/message-extension-search/infra/azure.parameters.json.tpl
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25578940/
> fix: rename resource group prefix of bot and me templates

- .github/workflows/env-checker-ci-pr.yml
- .github/workflows/env-checker-ci-schedule.yml
- packages/fx-core/tests/common/deps-checker/cases/dotnet.it.ts
- packages/fx-core/tests/common/deps-checker/cases/funcTool.it.ts
[Bug 25579359](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25579359): Deps Checker E2E test failed
> fix: fix deps checker ci build error

- packages/cli/src/commands/models/m365Sideloading.ts
- packages/cli/src/commands/models/m365Unacquire.ts
feat link: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25124858
> feat: m365 install/uninstall example

- packages/fx-core/src/component/driver/script/scriptDriver.ts
fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25590408
> fix: mask secret in logger

- templates/js/copilot-plugin-from-scratch/.vscode/tasks.json
- templates/ts/copilot-plugin-from-scratch/.vscode/tasks.json
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25591436
> fix: remove the unnecessary port

- templates/ts/spfx-tab/.vscode/launch.json
ADO: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25507867
> fix: add remote launch configurations in SPFx template

- .github/workflows/env-checker-ci-schedule.yml
- packages/fx-core/src/core/middleware/utils/debug/taskMigrator.ts
- packages/fx-core/tests/common/deps-checker/cases/funcTool.it.ts
- packages/fx-core/tests/core/middleware/testAssets/v3Migration/debug/V3.5.0-V4.0.6-tab-bot-func-node18/expected/app.local.yml
- packages/fx-core/tests/core/middleware/testAssets/v3Migration/debug/beforeV3.4.0-tab-bot-func-node18/expected/app.local.yml
- packages/fx-core/tests/core/middleware/testAssets/v3Migration/debug/transparent-notification-node18/expected/app.local.yml
- templates/constraints/yml/actions/devToolInstall.mustache
- templates/js/copilot-plugin-from-scratch/teamsapp.local.yml.tpl
- templates/js/notification-http-timer-trigger/teamsapp.local.yml.tpl
- templates/js/notification-http-trigger/teamsapp.local.yml.tpl
- templates/js/notification-timer-trigger/teamsapp.local.yml.tpl
- templates/js/sso-tab-with-obo-flow/teamsapp.local.yml.tpl
- templates/ts/copilot-plugin-from-scratch/teamsapp.local.yml.tpl
- templates/ts/notification-http-timer-trigger/teamsapp.local.yml.tpl
- templates/ts/notification-http-trigger/teamsapp.local.yml.tpl
- templates/ts/notification-timer-trigger/teamsapp.local.yml.tpl
- templates/ts/sso-tab-with-obo-flow/teamsapp.local.yml.tpl
[Bug 25563995](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25563995): node 20 - application can't be started for notification bot with azure function
Integration test: https://github.com/OfficeDev/TeamsFx/actions/runs/6624561849
> fix: upgrade azure function core tool to support node 20

- packages/fx-core/src/component/driver/teamsApp/clients/appStudioClient.ts
- packages/fx-core/src/component/driver/teamsApp/constants.ts
- packages/fx-core/src/component/driver/teamsApp/interfaces/ApiSecretRegistration.ts
- packages/fx-core/src/component/driver/teamsApp/interfaces/ApiSecretRegistrationClientSecret.ts
- packages/fx-core/tests/component/driver/teamsApp/appstudioclient.test.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25577741
> refactor: integrate with API Key registration APIs

- packages/fx-core/src/core/FxCore.ts
bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25591786/
> fix: fix vs add sso error

- packages/api/review/teamsfx-api.api.md
- packages/api/src/qm/ui.ts
- packages/fx-core/src/common/constants.ts
- packages/fx-core/src/common/featureFlags.ts
- packages/vscode-extension/package.nls.json
- packages/vscode-extension/src/constants.ts
- packages/vscode-extension/src/globalVariables.ts
- packages/vscode-extension/src/handlers.ts
- packages/vscode-extension/src/qm/vsc_ui.ts
- packages/vscode-extension/test/extension/handlers.test.ts
> feat: auto install dependencies after scaffolding/importing SPFx projects

- templates/csharp/copilot-plugin-existing-api/{{ProjectName}}.csproj.tpl
- templates/csharp/copilot-plugin-from-oai-plugin/{{ProjectName}}.csproj.tpl
- templates/csharp/copilot-plugin-from-scratch/{{ProjectName}}.csproj.tpl
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25628016
Related PR: https://devdiv.visualstudio.com/DevDiv/_git/TeamsFx/pullrequest/507462
> fix: copilot strings in API MEs

- packages/fx-core/resource/package.nls.json
- packages/fx-core/src/component/utils/ResourceGroupHelper.ts
- packages/fx-core/src/question/other.ts
Related task: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/15580575
Effect:
> feat(core): use recommended Azure regions

- packages/fx-core/src/component/generator/generator.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25640170
> fix: copilot string is in output log when creating project

- packages/fx-core/src/question/other.ts
- packages/fx-core/tests/question/question.test.ts
fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25602628
> fix: rename aad option name under feature flag

- packages/api/review/teamsfx-api.api.md
- packages/api/src/types.ts
- packages/fx-core/src/common/featureFlags.ts
- packages/fx-core/src/component/generator/copilotPlugin/generator.ts
- packages/fx-core/src/component/generator/generator.ts
- packages/fx-core/src/question/create.ts
- packages/fx-core/tests/component/generator/copilotPluginGenerator.test.ts
- packages/fx-core/tests/core/FxCore.test.ts
- templates/common/copilot-plugin-existing-api-api-key/teamsapp.yml.tpl
- Add api_key action in template.
- Fix E2E test https://github.com/OfficeDev/TeamsFx/actions/runs/6725596814/job/18281547775
TODO: add template constraint
> refactor: template update for api key

- packages/vscode-extension/src/controls/sampleGallery/SampleGallery.scss
- packages/vscode-extension/src/controls/sampleGallery/SampleGallery.tsx
- packages/vscode-extension/src/controls/sampleGallery/offlinePage.scss
- packages/vscode-extension/src/controls/sampleGallery/sampleCard.scss
- packages/vscode-extension/src/controls/sampleGallery/sampleFilter.scss
- packages/vscode-extension/src/controls/sampleGallery/sampleFilter.tsx
- packages/vscode-extension/src/controls/sampleGallery/sampleListItem.scss
- packages/vscode-extension/src/controls/sampleGallery/sampleListItem.tsx
Related task: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25298075
Effect preview:
> feat(vsc): redesign featured samples and responsive layout

- packages/fx-core/src/common/m365/packageService.ts
- packages/fx-core/tests/common/m365/packageService.test.ts
- templates/js/message-extension-copilot/.vscode/launch.json
- templates/js/message-extension-copilot/.vscode/tasks.json
- templates/ts/message-extension-copilot/.vscode/launch.json
- templates/ts/message-extension-copilot/.vscode/tasks.json
Workitem: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/24918417
- Update service endpoint to the latest one
- Add copilot check task to copilot template
E2E TEST: N/A
> feat: enable copilot access check

- templates/js/ai-bot/.vscode/launch.json.tpl
- templates/js/command-and-response/.vscode/launch.json.tpl
- templates/js/default-bot/.vscode/launch.json.tpl
- templates/js/notification-http-timer-trigger/.vscode/launch.json.tpl
- templates/js/notification-http-trigger/.vscode/launch.json.tpl
- templates/js/notification-restify/.vscode/launch.json.tpl
- templates/js/notification-timer-trigger/.vscode/launch.json.tpl
- templates/js/workflow/.vscode/launch.json.tpl
- templates/ts/ai-bot/.vscode/launch.json.tpl
- templates/ts/command-and-response/.vscode/launch.json.tpl
- templates/ts/default-bot/.vscode/launch.json.tpl
- templates/ts/notification-http-timer-trigger/.vscode/launch.json.tpl
- templates/ts/notification-http-trigger/.vscode/launch.json.tpl
- templates/ts/notification-restify/.vscode/launch.json.tpl
- templates/ts/notification-timer-trigger/.vscode/launch.json.tpl
- templates/ts/workflow/.vscode/launch.json.tpl
Remove comma to work around strict json check for ui test
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25697140
> fix: workaround ui test strict check

- packages/vscode-extension/.vscode/launch.json
Related task: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25722415
Make it easier to develop Teams Toolkit extension.
> fix: add sample config branch when local debugging

- templates/js/message-extension-copilot/package.json.tpl
- templates/ts/copilot-plugin-from-scratch/package.json.tpl
- templates/ts/message-extension-copilot/package.json.tpl
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25386097
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25593617
> fix: upgrade dependencies

- packages/tests/src/e2e/command/template.tests.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25663359
https://github.com/OfficeDev/TeamsFx/actions/runs/6779620099
> fix: sample e2e test

- packages/fx-core/resource/package.nls.json
- packages/fx-core/src/component/generator/copilotPlugin/generator.ts
- packages/fx-core/src/question/create.ts
- packages/fx-core/tests/question/create.test.ts
- fix path in action
- update placeholder if API KEY auth is enabled.
> refactor: API KEY auth update

- packages/fx-core/src/component/driver/teamsApp/teamsappMgr.ts
fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25743883
> fix: error component name for teamsapp management

- packages/cli/src/commands/models/teamsapp/doctor.ts
- packages/fx-core/src/common/local/localCertificateManager.ts
- packages/fx-core/tests/common/local/localCertificateManager.test.ts
fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25743898
> fix: not to install certification for doctor command

- .github/CODEOWNERS
- templates/common/copilot-plugin-existing-api-api-key/teamsapp.yml.tpl
- templates/constraints/yml/actions/apiKeyRegister.mustache
- templates/constraints/yml/templates/common/copilot-plugin-existing-api-api-key/teamsapp.yml.tpl.mustache
> refactor: template constraint for api me api key

- packages/fx-core/src/question/create.ts
fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25756246
> fix: not fetch remote sample config for static options

- templates/js/command-and-response/README.md.tpl
- templates/ts/command-and-response/README.md.tpl
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25755687/
> fix(template): unclosed section enableTestToolByDefault

- templates/constraints/yml/templates/csharp/copilot-plugin-existing-api-api-key/teamsapp.yml.tpl.mustache
- templates/csharp/copilot-plugin-existing-api-api-key/teamsapp.yml.tpl
https://github.com/OfficeDev/TeamsFx/pull/10286/files
> refactor(vs): api key template

- templates/csharp/sso-tab/{{ProjectName}}.csproj.tpl
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25757340/
> fix: vulnerability in Azure.Identity dependency

- packages/cli/src/commands/engine.ts
- packages/cli/src/userInteraction.ts
- packages/cli/tests/unit/ui.tests.ts
- packages/cli/tests/unit/ui2.tests.ts
fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25784565
> fix(cli): user interaction for non-interactive mode

- packages/cli/src/activate.ts
- packages/cli/tests/unit/engine.tests.ts
- packages/fx-core/src/common/featureFlags.ts
- packages/fx-core/src/ui/visitor.ts
- packages/fx-core/tests/common/featureFlags.test.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25785606
> refactor: remove cli new ux feature flag

- packages/tests/src/e2e/collaboration/Permission.tests.ts
fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25786409
> fix(tests): e2e test case for permission command

- packages/tests/src/utils/executor.ts
fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25818749
> fix: e2e test

- packages/cli/src/commands/models/m365Sideloading.ts
fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25772587
> fix: sideloading command help description

- packages/fx-core/src/component/utils/envUtil.ts
- packages/fx-core/tests/component/envUtil.test.ts
fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25772173
> fix: insert space before comment mark for dotenv serialize

- templates/js/sso-tab-with-obo-flow/package.json.tpl
- templates/ts/sso-tab-with-obo-flow/package.json.tpl
fix bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25786229
> fix(obo): fix cli preview error in obo template

- packages/cli/tests/unit/commands.tests.ts
- packages/fx-core/src/common/constants.ts
- packages/vscode-extension/src/utils/commonUtils.ts
refactor: rename Feature flag to DEVELOP_COPILOT_PLUGIN
> fix: rename feature flag to DEVELOP_COPILOT_PLUGIN

- packages/vscode-extension/src/controls/sampleGallery/SampleGallery.scss
- packages/vscode-extension/src/controls/sampleGallery/sampleCard.scss
- packages/vscode-extension/src/controls/sampleGallery/sampleFilter.scss
- packages/vscode-extension/src/controls/sampleGallery/sampleFilter.tsx
- packages/vscode-extension/src/controls/sampleGallery/sampleListItem.scss
Related bugs:
1. https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25784896
2. https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25784912
3. https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25784919
4. https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25784945
5. https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25784954
Effect:
> fix(vsc): sample gallery ui bugs

- packages/vscode-extension/src/controls/sampleGallery/ISamples.ts
- packages/vscode-extension/src/controls/sampleGallery/SampleGallery.tsx
- packages/vscode-extension/src/controls/sampleGallery/sampleFilter.tsx
Related bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25832846
> fix(vsc): sample gallery filters keep selection order

- packages/manifest/package.json
- packages/manifest/src/index.ts
- packages/manifest/test/index.test.ts
- pnpm-lock.yaml
fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25874856
> fix: remove axios dependency

- packages/fx-core/src/component/generator/officeAddin/helperMethods.ts
- packages/fx-core/tests/component/generator/officeAddinGenerator.test.ts
fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25874964
> fix: remove axios dependency in office addin generator

- packages/dotnet-sdk/src/TeamsFx.Test/Conversation/NotificationMiddlewareTest.cs
- packages/dotnet-sdk/src/TeamsFx/Conversation/NotificationMiddleware.cs
- packages/sdk/src/conversation/middlewares/notificationMiddleware.ts
- packages/sdk/test/unit/node/conversation/middleware.spec.ts
workitem: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25847218/
- Ignore non-general channel message activity
- UT added
E2E Test: N/A
> fix: notification sdk - non-general channel message

- packages/api/review/teamsfx-api.api.md
- packages/api/src/qm/question.ts
- packages/api/src/qm/ui.ts
- packages/cli/src/userInteraction.ts
- packages/cli/tests/unit/ui.tests.ts
- packages/fx-core/src/question/generator.ts
- packages/fx-core/src/ui/visitor.ts
- packages/fx-core/tests/core/utils.ts
- packages/fx-core/tests/plugins/resource/appstudio/helper.ts
- packages/fx-core/tests/plugins/resource/spfx/helper.ts
- packages/fx-core/tests/plugins/solution/util.ts
- packages/fx-core/tests/ui/qm.visitor.test.ts
- packages/server/src/apis.ts
- packages/server/src/providers/userInteraction.ts
- packages/server/src/utils.ts
- packages/server/tests/providers/userInteraction.test.ts
- packages/vscode-extension/src/qm/vsc_ui.ts
feat: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25874581
> feat: upgrade question model and ui to support confirm type

- packages/fx-core/src/common/m365/packageService.ts
- packages/fx-core/tests/common/m365/packageService.test.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25135989/
For http 400 when sideloading, handle as user error
E2E Test: N/A
> refactor: handle sideloading badrequest error

- packages/fx-core/src/component/utils/common.ts
- packages/fx-core/src/core/FxCore.ts
- packages/fx-core/tests/component/utils.test.ts
- packages/fx-core/tests/core/FxCore.test.ts
fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25915146
> fix: app name contains placeholder

- packages/cli/.vscode/launch.json
- packages/cli/src/commands/engine.ts
- packages/fx-core/src/common/projectTypeChecker.ts
- packages/fx-core/src/common/telemetry.ts
- packages/fx-core/src/core/FxCore.ts
- packages/fx-core/tests/common/projectTypeChecker.test.ts
- packages/fx-core/tests/core/FxCore.test.ts
fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25915159
> feat: check project type and send in telemetry in cli

- .github/scripts/get-dailydigest-dependencies.js
- .github/workflows/botbuilder-released.yml
- .github/workflows/sdk-e2e-test.yml
- .github/workflows/templates-dependencies-released.yml
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_dashboards/dashboard/a9d3c597-e398-49d2-a5d4-2c1b23ea0025
> feat: add dependency email

- templates/js/sso-tab-with-obo-flow/.vscode/tasks.json
- templates/ts/sso-tab-with-obo-flow/.vscode/tasks.json
bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_sprints/taskboard/AuthAndData/Microsoft%20Teams%20Extensibility/Germanium/CY23Q4/2Wk/2Wk04%20(Nov%2005%20-%20Nov%2018)?workitem=25786229
Previous pr will cause local debug failure in vsc due to backend service start twice.
> fix(template): fix obo template debug issue

- packages/cli/src/utils.ts
- packages/cli/tests/unit/utils.tests.ts
- packages/fx-core/src/common/samples.ts
- packages/fx-core/src/component/generator/generator.ts
- packages/fx-core/src/component/generator/utils.ts
- packages/fx-core/src/question/create.ts
- packages/fx-core/tests/common/samples.test.ts
- packages/fx-core/tests/component/generator/generator.test.ts
- packages/fx-core/tests/question/create.test.ts
- packages/vscode-extension/src/controls/webviewPanel.ts
related tasks:
1. https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25758250
> refactor(sample): unify interface

- packages/fx-core/src/common/projectTypeChecker.ts
- packages/fx-core/tests/common/projectTypeChecker.test.ts
detect whether the project is SPFx
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25929482
> feat: check spfx project type

- packages/cli/src/commonlib/m365LoginUserPassword.ts
Bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25858239
When user set CI_ENABLED=true, it doesn't goes to regional API, but hits global endpoint instead. Which will result in user cannot find updated content from Teams Developer Portal.
> fix: set region when CI_ENABLED

- packages/fx-core/src/core/FxCore.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_queries/edit/25931787/?triage=true
> fix: fix add sso in vs

- packages/vscode-extension/package.json
fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25861452
> fix: refine activation event

- templates/csharp/ai-bot/Properties/launchSettings.json
- templates/csharp/command-and-response/Properties/launchSettings.json
- templates/csharp/copilot-plugin-from-scratch/Properties/launchSettings.json
- templates/csharp/default-bot/Properties/launchSettings.json
- templates/csharp/link-unfurling/Properties/launchSettings.json
- templates/csharp/message-extension-action/Properties/launchSettings.json
- templates/csharp/message-extension-copilot/Properties/launchSettings.json
- templates/csharp/message-extension-search/Properties/launchSettings.json
- templates/csharp/message-extension/Properties/launchSettings.json
- templates/csharp/non-sso-tab/Properties/launchSettings.json
- templates/csharp/notification-http-timer-trigger/Properties/launchSettings.json
- templates/csharp/notification-http-trigger/Properties/launchSettings.json
- templates/csharp/notification-timer-trigger/Properties/launchSettings.json
- templates/csharp/notification-webapi/Properties/launchSettings.json
- templates/csharp/sso-tab/Properties/launchSettings.json
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25845955
> fix: LaunchUrl parameters placeholders in launchsettings.json are not consistent with teamsapp.yml file

- packages/tests/src/commonlib/frontendValidator.ts
- packages/tests/src/e2e/frontend/BlazorAppHappyPath.tests.ts
Fix axios issue since we have upgrade axios to 1.6.0 recently.
> test: fix axios header issue in e2e test

- packages/fx-core/resource/yaml-schema/v1.3/yaml.schema.json
- packages/fx-core/src/component/driver/script/scriptDriver.ts
- packages/fx-core/tests/component/driver/script/scriptDriver.test.ts
detect default shell for script driver
try to fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25951521
> perf: improve script driver

- packages/fx-core/src/common/spec-parser/specParser.ts
- packages/fx-core/tests/common/spec-parser/specParser.test.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25953170
> fix(apikey): load from env when domain contains placeholder

- packages/fx-core/src/component/generator/officeAddin/helperMethods.ts
fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25971699
> fix: office addin generator

- packages/fx-core/src/component/driver/teamsApp/validateAppPackage.ts
- packages/fx-core/tests/component/driver/teamsApp/validate.test.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25876326
Before:
After:
> fix: skip print out undefined succeed message

- packages/vscode-extension/src/controls/sampleGallery/sampleCard.scss
- packages/vscode-extension/src/controls/sampleGallery/sampleCard.tsx
Related bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25944496
> fix(vsc): remove favorite star on sample card

- packages/fx-core/package.json
- packages/fx-core/resource/package.nls.json
- packages/fx-core/src/common/deps-checker/depsChecker.ts
- packages/fx-core/src/common/deps-checker/internal/testToolChecker.ts
- packages/fx-core/src/common/deps-checker/internal/vxTestAppChecker.ts
- packages/fx-core/src/common/deps-checker/util/downloadHelper.ts
- packages/fx-core/tests/common/deps-checker/testToolChecker.test.ts
- pnpm-lock.yaml
> feat: support install & update binary version test tool

- packages/fx-core/resource/package.nls.json
Related bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/24965003/
> fix: suffix name in description

- packages/vscode-ui/package.json
- packages/vscode-ui/src/error.ts
- packages/vscode-ui/src/localize.ts
- packages/vscode-ui/src/validationUtils.ts
- packages/vscode-ui/src/visitor.ts
- packages/vscode-ui/tests/error.test.ts
- packages/vscode-ui/tests/qm.test.ts
- packages/vscode-ui/tests/validationUtils.test.ts
- pnpm-lock.yaml
vscode-ui package include question model codes
> refactor: copy question model code into vscode-ui

- packages/fx-core/src/core/middleware/projectMigratorV3.ts
- packages/fx-core/src/core/middleware/projectVersionChecker.ts
- packages/fx-core/tests/core/middleware/projectVersionChecker.test.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/24931765
> fix: upgrade button localization

- templates/js/ai-assistant-bot/.gitignore
- templates/js/ai-assistant-bot/.localConfigs.testTool
- templates/js/ai-assistant-bot/.vscode/launch.json.tpl
- templates/js/ai-assistant-bot/.vscode/tasks.json
- templates/js/ai-assistant-bot/.webappignore
- templates/js/ai-assistant-bot/README.md.tpl
- templates/js/ai-assistant-bot/env/.env.testtool
- templates/js/ai-assistant-bot/env/.env.testtool.user
- templates/js/ai-assistant-bot/package.json.tpl
- templates/js/ai-assistant-bot/teamsapp.testtool.yml
- templates/ts/ai-assistant-bot/.gitignore
- templates/ts/ai-assistant-bot/.localConfigs.testTool
- templates/ts/ai-assistant-bot/.vscode/launch.json.tpl
- templates/ts/ai-assistant-bot/.vscode/tasks.json
- templates/ts/ai-assistant-bot/.webappignore
- templates/ts/ai-assistant-bot/README.md.tpl
- templates/ts/ai-assistant-bot/env/.env.testtool
- templates/ts/ai-assistant-bot/env/.env.testtool.user
- templates/ts/ai-assistant-bot/package.json.tpl
- templates/ts/ai-assistant-bot/teamsapp.testtool.yml
work item: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/23787334
> feat(template): enable Debug in Test Tool for ai-assistant-bot

- packages/fx-core/src/component/driver/teamsApp/appStudio.ts
- packages/fx-core/src/component/driver/teamsApp/clients/appStudioClient.ts
- packages/fx-core/src/component/driver/teamsApp/utils/telemetry.ts
- packages/fx-core/tests/component/driver/teamsApp/appstudioclient.test.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/26022538
> refactor: add region telemetry properties

- packages/fx-core/src/component/driver/teamsApp/clients/appStudioClient.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/26047237
> refactor: do not fail-over to global endpoint for get 404

- packages/fx-core/src/question/create.ts
- templates/js/ai-bot/.vscode/launch.json.tpl
- templates/js/ai-bot/README.md.tpl
- templates/js/ai-bot/package.json.tpl
- templates/js/ai-bot/src/app.js
- templates/ts/ai-bot/README.md.tpl
- templates/ts/ai-bot/package.json.tpl
- templates/ts/ai-bot/src/app.ts
- update code to use latest teams-ai
- update README to match code
- upgrade teams-ai version
- add preview tag for test tool in launch.json
- remove preview tag for ai chat bot
Fix https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25846764.
> feat: update ai chat bot to use latest teams-ai

- templates/js/ai-assistant-bot/README.md.tpl
- templates/js/ai-assistant-bot/package.json.tpl
- templates/js/ai-assistant-bot/src/app.js
- templates/js/ai-assistant-bot/src/creator.js
- templates/ts/ai-assistant-bot/README.md.tpl
- templates/ts/ai-assistant-bot/package.json.tpl
- templates/ts/ai-assistant-bot/src/app.ts
- templates/ts/ai-assistant-bot/src/creator.ts
- update code to use latest teams-ai
- update README to match code
- upgrade teams-ai version
Fix https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25846764
> feat: upgrade ai assistant bot to use latest teams-ai

- packages/server/src/serverConnection.ts
- packages/server/tests/serverConnection.test.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/24918932/
Export copilot access check method in server, to be called in VS extension.
> feat: export copilt access check in server

- packages/vscode-extension/src/treeview/account/azureNode.ts
- packages/vscode-extension/src/treeview/account/m365Node.ts
Fix account tree view UX error.
> refactor: account tree view UX

- packages/fx-core/src/common/deps-checker/internal/testToolChecker.ts
> fix: test tool download repo

- templates/csharp/ai-assistant-bot/Program.cs.tpl
- templates/csharp/ai-assistant-bot/{{ProjectName}}.csproj.tpl
- templates/csharp/ai-bot/{{ProjectName}}.csproj.tpl
Fix https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/26151558
> fix: show .user files in solution view for C# AI templates

- packages/fx-core/src/core/FxCore.ts
- packages/fx-core/tests/core/FxCore.test.ts
bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/26162322/?view=edit
> fix(aad): fix bug in aad manifest update

- packages/vscode-extension/src/controls/sampleGallery/SampleGallery.tsx
Related bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/26175855
> fix(vsc): set gallery view as sample gallery default layout

- templates/csharp/ai-assistant-bot/Create-Assistant.ps1
- templates/csharp/ai-assistant-bot/GettingStarted.md
- templates/csharp/ai-assistant-bot/Program.cs.tpl
Fix https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/26177184
> fix: use powershell to create assistant in csharp assistant bot

- packages/dotnet-sdk/src/TeamsFx/Microsoft.TeamsFx.csproj
The changelog has already been updated: https://github.com/OfficeDev/TeamsFx/blob/dev/packages/dotnet-sdk/CHANGELOG.md
> fix: update the .NET SDK version to 2.4.0-rc

- packages/tests/src/commonlib/index.ts
- packages/tests/src/commonlib/staticSiteValidator.ts
- packages/tests/src/e2e/frontend/CanDeployToCustomizedRg.tests.ts
- packages/tests/src/e2e/frontend/TestCreateTab.tests.ts
- packages/tests/src/e2e/m365/DeployOboTab.tests.ts
- packages/tests/src/e2e/solution/SSOTabE2ETestWithAADManifestEnabled.tests.ts
E2E TEST: https://github.com/OfficeDev/TeamsFx/actions/runs/7245838674
> test: validate static site in e2e tests

- templates/csharp/ai-assistant-bot/{{ProjectName}}.csproj.tpl
- templates/csharp/ai-bot/{{ProjectName}}.csproj.tpl
- templates/csharp/command-and-response/{{ProjectName}}.csproj.tpl
- templates/csharp/default-bot/{{ProjectName}}.csproj.tpl
- templates/csharp/notification-http-timer-trigger/{{ProjectName}}.csproj.tpl
- templates/csharp/notification-http-trigger/{{ProjectName}}.csproj.tpl
- templates/csharp/notification-timer-trigger/{{ProjectName}}.csproj.tpl
- templates/csharp/notification-webapi/{{ProjectName}}.csproj.tpl
- templates/csharp/workflow/{{ProjectName}}.csproj.tpl
> fix: hide devTools from VS solution explorer view

- packages/fx-core/src/common/deps-checker/internal/testToolChecker.ts
> fix: lower check update interval

- templates/js/ai-assistant-bot/.vscode/launch.json.tpl
- templates/ts/ai-assistant-bot/.vscode/launch.json.tpl
Fix https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/26216250
> fix: remove trailing comma in assistant bot launch.json

- templates/csharp/ai-bot/GettingStarted.md.tpl
- add step to update model deployment name for azure openai
Fix https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/26216416
> fix: update csharp ai chat bot GettingStarted

- packages/tests/src/ui-test/localdebug/localdebug-aiassistant-bot-ts.test.ts
- packages/tests/src/ui-test/localdebug/localdebug-aiassistant-bot.test.ts
- packages/tests/src/ui-test/localdebug/localdebug-aichat-bot-ts.test.ts
- packages/tests/src/ui-test/localdebug/localdebug-aichat-bot.test.ts
- packages/tests/src/ui-test/remotedebug/remotedebug-aiassistant-bot-ts-win-only.test.ts
- packages/tests/src/ui-test/remotedebug/remotedebug-aiassistant-bot-win-only.test.ts
- packages/tests/src/ui-test/remotedebug/remotedebug-aichat-bot-ts-win-only.test.ts
- packages/tests/src/ui-test/remotedebug/remotedebug-aichat-bot-win-only.test.ts
- packages/tests/src/ui-test/treeview/treeviewContext.ts
- packages/tests/src/utils/playwrightOperation.ts
1. update ai bot test cases
2. update sample view test cases
> test: update ai bot test cases

- docs/cicd_insider/jenkins-cd-template.Jenkinsfile
- docs/cicd_insider/others-script-cd-template.sh
- packages/cli/src/commands/engine.ts
- packages/cli/src/commands/models/accountLoginAzure.ts
- packages/cli/src/commands/models/accountLoginM365.ts
- packages/cli/tests/unit/engine.tests.ts
fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/26241564
> fix: default none interactive for login command

- packages/dotnet-sdk/CHANGELOG.md
- packages/dotnet-sdk/src/TeamsFx/Microsoft.TeamsFx.csproj
- templates/csharp/command-and-response/{{ProjectName}}.csproj.tpl
- templates/csharp/notification-http-timer-trigger/{{ProjectName}}.csproj.tpl
- templates/csharp/notification-http-trigger/{{ProjectName}}.csproj.tpl
- templates/csharp/notification-timer-trigger/{{ProjectName}}.csproj.tpl
- templates/csharp/notification-webapi/{{ProjectName}}.csproj.tpl
- templates/csharp/workflow/{{ProjectName}}.csproj.tpl
work item: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/23787334
> feat: update .NET SDK version to 2.4.0 and bot template

- packages/vscode-extension/package.json
- packages/vscode-extension/src/controls/declarations.d.ts
- packages/vscode-extension/src/controls/sampleGallery/sampleDetailPage.tsx
- packages/vscode-extension/src/controls/webviewPanel.ts
- packages/vscode-extension/webpack.config.js
- pnpm-lock.yaml
Related bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/26255063
> fix(vsc): purify dom and check origin in sample gallery detail page

- templates/csharp/sso-tab-ssr/Components/Pages/Graph.razor
- templates/csharp/sso-tab/Components/Graph.razor
https://github.com/OfficeDev/TeamsFx/issues/10582
> fix: fix trim start issue

- templates/js/sso-tab-with-obo-flow/.vscode/tasks.json
- templates/js/sso-tab-with-obo-flow/package.json.tpl
- templates/ts/sso-tab-with-obo-flow/.vscode/tasks.json
- templates/ts/sso-tab-with-obo-flow/package.json.tpl
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/26242888/
> fix: obo tab frontend task won't stop after stopping debugging

- templates/csharp/copilot-plugin-from-scratch/appPackage/responseTemplates/repair.data.json
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/26259461
> fix: repair id cannot preview in ACP

- templates/csharp/ai-assistant-bot/infra/azure.parameters.json.tpl
Fix https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/26263424
> fix: add missing comma in c# ai assistant bot

- packages/fx-core/src/common/samples.ts
Related task: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25902491
> fix(core): rename sample stable branch

- .github/workflows/ui-test.yml
Related bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/26296971
Reference: https://yarnpkg.com/corepack
Validation test run: https://github.com/OfficeDev/TeamsFx/actions/runs/7394578544/job/20116202170
> fix(workflow): ui test action yarn error

- packages/fx-core/resource/package.nls.json
- packages/fx-core/src/common/jsonUtils.ts
- packages/fx-core/src/component/driver/aad/create.ts
- packages/fx-core/src/component/driver/aad/update.ts
- packages/fx-core/src/component/driver/apiKey/create.ts
- packages/fx-core/src/component/driver/botAadApp/create.ts
- packages/fx-core/src/component/driver/botFramework/createOrUpdateBot.ts
- packages/fx-core/src/component/driver/file/createOrUpdateEnvironmentFile.ts
- packages/fx-core/src/component/driver/file/createOrUpdateJsonFile.ts
- packages/fx-core/src/component/driver/m365/acquire.ts
- packages/fx-core/src/component/feature/collaboration.ts
- packages/fx-core/src/error/common.ts
- packages/fx-core/src/error/teamsApp.ts
- packages/fx-core/tests/component/driver/aad/update.test.ts
- packages/fx-core/tests/component/driver/botAadApp/create.test.ts
- packages/fx-core/tests/error/error.test.ts
fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/26255050
> fix: refine EAI_AGAIN error messasge

- packages/cli/src/commands/engine.ts
fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/26321132
> fix: cli exit code when error happends

- packages/fx-core/resource/yaml-schema/v1.4/yaml.schema.json
- packages/fx-core/resource/yaml-schema/yaml.schema.json
link: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/26322536
> feat: bump yaml schema v1.4

- packages/fx-core/src/component/configManager/validator.ts
fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/26322536
> fix: support v1.4 yaml schema

- templates/csharp/link-unfurling/appPackage/manifest.json.tpl
- templates/js/link-unfurling/appPackage/manifest.json.tpl
- templates/ts/link-unfurling/appPackage/manifest.json.tpl
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/26336137
> fix: add back search command

- templates/csharp/ai-assistant-bot/{{ProjectName}}.csproj.tpl
- templates/csharp/ai-bot/{{ProjectName}}.csproj.tpl
- templates/csharp/command-and-response/{{ProjectName}}.csproj.tpl
- templates/csharp/copilot-plugin-existing-api-api-key/{{ProjectName}}.csproj.tpl
- templates/csharp/copilot-plugin-existing-api/{{ProjectName}}.csproj.tpl
- templates/csharp/copilot-plugin-from-oai-plugin/{{ProjectName}}.csproj.tpl
- templates/csharp/copilot-plugin-from-scratch/{{ProjectName}}.csproj.tpl
- templates/csharp/default-bot/{{ProjectName}}.csproj.tpl
- templates/csharp/link-unfurling/{{ProjectName}}.csproj.tpl
- templates/csharp/message-extension-action/{{ProjectName}}.csproj.tpl
- templates/csharp/message-extension-copilot/{{ProjectName}}.csproj.tpl
- templates/csharp/message-extension-search/{{ProjectName}}.csproj.tpl
- templates/csharp/message-extension/{{ProjectName}}.csproj.tpl
- templates/csharp/non-sso-tab-ssr/{{ProjectName}}.csproj.tpl
- templates/csharp/non-sso-tab/{{ProjectName}}.csproj.tpl
- templates/csharp/notification-http-timer-trigger/{{ProjectName}}.csproj.tpl
- templates/csharp/notification-http-trigger/{{ProjectName}}.csproj.tpl
- templates/csharp/notification-timer-trigger/{{ProjectName}}.csproj.tpl
- templates/csharp/notification-webapi/{{ProjectName}}.csproj.tpl
- templates/csharp/sso-tab-ssr/{{ProjectName}}.csproj.tpl
- templates/csharp/sso-tab/{{ProjectName}}.csproj.tpl
- templates/csharp/workflow/{{ProjectName}}.csproj.tpl
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/26336773
> fix: configuration folder visibility of templates

- .github/workflows/e2e-test.yml
fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/26369819
> fix: fix e2e dotnet build error

- templates/constraints/yml/templates/js/dashboard-tab/teamsapp.yml.tpl.mustache
- templates/constraints/yml/templates/js/non-sso-tab-default-bot/teamsapp.yml.tpl.mustache
- templates/constraints/yml/templates/js/sso-tab-with-obo-flow/teamsapp.yml.tpl.mustache
- templates/constraints/yml/templates/ts/dashboard-tab/teamsapp.yml.tpl.mustache
- templates/constraints/yml/templates/ts/non-sso-tab-default-bot/teamsapp.yml.tpl.mustache
- templates/constraints/yml/templates/ts/sso-tab-with-obo-flow/teamsapp.yml.tpl.mustache
- templates/js/dashboard-tab/teamsapp.yml.tpl
- templates/js/non-sso-tab-default-bot/teamsapp.yml.tpl
- templates/js/sso-tab-with-obo-flow/teamsapp.yml.tpl
- templates/ts/dashboard-tab/teamsapp.yml.tpl
- templates/ts/non-sso-tab-default-bot/teamsapp.yml.tpl
- templates/ts/sso-tab-with-obo-flow/teamsapp.yml.tpl
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/26322536
> fix: change teams Yaml version to v1.4

- packages/tests/src/e2e/armDriver/jsonFormatAndMultipleDeployment.tests.ts
- packages/tests/src/e2e/upgrade/happyPath.tests.ts
armDriver case: https://github.com/OfficeDev/TeamsFx/actions/runs/7457234371
upgrade case: https://github.com/OfficeDev/TeamsFx/actions/runs/7458006534
> test: update case

- packages/fx-core/src/common/featureFlags.ts
> fix: enable test tool by default for preview version

- packages/tests/src/e2e/bot/CommandBotHappyPathCommon.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/26399650
> fix: fix e2e test missing env parameter

- templates/csharp/notification-http-timer-trigger-isolated/Program.cs.tpl
- templates/csharp/notification-http-timer-trigger-isolated/infra/azure.bicep
- templates/csharp/notification-http-trigger-isolated/Program.cs.tpl
- templates/csharp/notification-http-trigger-isolated/infra/azure.bicep
- templates/csharp/notification-timer-trigger-isolated/Program.cs.tpl
- templates/csharp/notification-timer-trigger-isolated/infra/azure.bicep
Move 'ConfigureFunctionsWebApplication' to the top to ensure that environment variables are added to the configuration.
Fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/26389561/
> fix: function remote

- packages/fx-core/src/common/m365/packageService.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/26418307
To support OAI plugin on CLI sideloading/unacquire
> fix: cli sideload supports oai

- templates/csharp/non-sso-tab-ssr/{{ProjectName}}.csproj.tpl
- templates/csharp/sso-tab-ssr/{{ProjectName}}.csproj.tpl
- templates/csharp/sso-tab/{{ProjectName}}.csproj.tpl
- templates/ts/non-sso-tab/package.json.tpl
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/26295929/
> fix: upgrade dependpencies for tab templates

- packages/fx-core/src/component/driver/teamsApp/clients/appStudioClient.ts
- packages/fx-core/src/component/driver/teamsApp/constants.ts
- packages/fx-core/tests/component/driver/teamsApp/appstudioclient.test.ts
feature link: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25990580
> feat: list and delete teams app in TDP

- packages/fx-core/src/component/driver/teamsApp/constants.ts
- packages/fx-core/src/component/resource/botService/appStudio/appStudioClient.ts
- packages/fx-core/tests/component/resource/botService/appStudioClient.test.ts
feature link: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25990580
> feat: list and delete bot registration

- packages/cli/src/commands/common.ts
- packages/cli/src/commands/models/deploy.ts
- packages/cli/src/commands/models/provision.ts
- packages/cli/src/commands/models/publish.ts
- packages/fx-core/src/component/middleware/envMW.ts
- packages/fx-core/tests/component/envUtil.test.ts
fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/26375160
> fix: ignore env file for CICD scenario

- packages/fx-core/src/common/tools.ts
- packages/fx-core/tests/common/tools.test.ts
Related bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/26437627
> fix(core): ignore user cancel error

- packages/fx-core/tests/component/coordinator/coordinator.create.test.ts
Add scaffold test case to improve test coverage.
> refactor: add scaffold test case

- packages/fx-core/src/component/coordinator/index.ts
- packages/fx-core/tests/component/coordinator/coordinator.deploy.test.ts
fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/26437650
> fix: deploy confirm will pop up for all actions in deploy lifecycle

- .github/actions/create-milestone/index.ts
- .github/actions/issue-milestoned/azdo.ts
- .github/actions/issue-milestoned/index.ts
Update the milestoned event for github issue: using the milestone sprint as the AZDO work item iteration.
> refactor: update milestoned issue 

- packages/fx-core/src/component/coordinator/index.ts
fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/26465278
> fix: no confirm for local debug (deploy)

- packages/fx-core/src/component/configManager/lifecycle.ts
- packages/fx-core/src/component/driver/middleware/addSWADeployTelemetry.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/26517299
> fix: fix swa telemetry

- packages/fx-core/src/component/driver/aad/utility/aadAppClient.ts
- packages/fx-core/tests/component/driver/aad/aadAppClient.test.ts
fix bug: 
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/26518069
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/26517705
> fix: fix log

- packages/fx-core/src/common/spec-parser/generateTeamsAiMaterial.ts
- templates/ts/teams-ai-bot/src/index.ts
- templates/ts/teams-ai-bot/src/utility.ts
bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_sprints/taskboard/AuthAndData/Microsoft%20Teams%20Extensibility/Germanium/CY24Q1/2Wk/2Wk09%20(Jan%2014%20-%20Jan%2027)?workitem=26530713
> perf: fix error handling

- templates/js/notification-http-timer-trigger/package.json.tpl
- templates/js/notification-http-trigger/package.json.tpl
- templates/js/notification-restify/package.json.tpl
- templates/js/notification-timer-trigger/package.json.tpl
- templates/ts/notification-http-timer-trigger/package.json.tpl
- templates/ts/notification-http-trigger/package.json.tpl
- templates/ts/notification-restify/package.json.tpl
- templates/ts/notification-timer-trigger/package.json.tpl
work item: [link](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/26546048/)
> fix: update sdk version of notification bot template

- templates/js/sso-tab-with-obo-flow/.vscode/launch.json
- templates/ts/sso-tab-with-obo-flow/.vscode/launch.json
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/26545826
> fix: debug menu don't close after close the browser

- packages/fx-core/src/common/wrappedAxiosClient.ts
For bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/26573625
This is brought by: https://github.com/OfficeDev/TeamsFx/pull/10709
> fix: provision failed

- .github/workflows/cd.yml
https://docs.opensource.microsoft.com/github/apps/permission-changes/
> ci: update cd permission since the permission-changes

- packages/vscode-extension/package.json
- packages/vscode-extension/src/utils/commonUtils.ts
- packages/vscode-extension/test/extension/commonUtils.test.ts
- packages/vscode-extension/test/extension/telemetry.test.ts
fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/26592411
> fix: regular expression performance in stack mask

- .github/scripts/fxcore-sync-up-version.js
- .github/scripts/pkg-version.sh
- .github/scripts/sync-version.js
1. separate template version update and useLocal flag update to two steps and do not commit useLocal flag.
2. auto update localVersion.
3. remove fs-extra deps
> ci: do not commit useLocal in template-config

- packages/cli/package.json
- packages/cli/pnpm-lock.yaml
- packages/cli/src/commands/engine.ts
- packages/cli/src/index.ts
fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/26609560
> fix: init core to make sure tools are preset for all commands

- templates/csharp/sso-tab-ssr/wwwroot/auth-end.html
- templates/csharp/sso-tab/wwwroot/auth-end.html
https://github.com/OfficeDev/TeamsFx/security/code-scanning/2244
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/26592388
> fix: mitigate prototype pollution in csharp templates

- packages/fx-core/src/component/resource/botService/appStudio/appStudioClient.ts
fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/26626908
> fix: list bot telemetry event name

- packages/spec-parser/.nycrc
- packages/spec-parser/package.json
> test: fix coverage = 0 bug

- packages/fx-core/src/common/local/packageJsonHelper.ts
- packages/fx-core/tests/common/local/packageJsonHelper.test.ts
- templates/js/sso-tab-with-obo-flow/package.json.tpl
- templates/ts/sso-tab-with-obo-flow/package.json.tpl
Fix https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/26611679
> fix(cli-preview): remove match dev script for run-command

- .github/workflows/spec-parser-cd.yml
on spec-parser branch:https://github.com/OfficeDev/TeamsFx/blob/spec-parser/.github/workflows/spec-parser-cd.yml
add this change for add cd on dev branch, otherwise this cd can not be triggered
> ci: add basic cd for spec parser

- packages/server/buildExe.js
- packages/server/package.json
- packages/server/pnpm-lock.yaml
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/26594302
> fix: use nodev18 to generate server

- packages/cli/src/constants.ts
fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/26639943
> fix: broken cli doc link

- packages/teams-agent/src/chat/agent.ts
- packages/teams-agent/src/chat/copilotInteractions.ts
- packages/teams-agent/src/subCommand/createSlashCommand.ts
- packages/teams-agent/src/subCommand/testCommand.ts
- packages/teams-agent/src/templateConfig.json
- packages/teams-agent/tsconfig.json
> test: add test command for LLM benchmark

- .github/workflows/docs.yml
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/26639943?src=WorkItemMention&src-action=artifact_link
> ci: improve the aka link checker

- packages/fx-core/templates/plugins/resource/aad/auth/V3/Enable SSO.txt
bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/26640397
> docs: update add sso txt

- packages/vscode-extension/src/controls/sampleGallery/SampleGallery.tsx
Related bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/26477812
> fix(vsc): show featured samples in full list

- packages/vscode-extension/src/extension.ts
Related bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/26664118
> fix: debug command registration

- packages/teams-agent/README.md
- packages/teams-agent/package.json
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/26515563
> fix: update teams agent name from poc to preview

- .github/workflows/docs.yml
This reverts commit a940dfebadb58bdfaf7ae091f17f102a9bcbdf48.
> revert: improve the aka link checker (#10834)

- packages/api/package.json
- packages/api/pnpm-lock.yaml
- packages/fx-core/package.json
- packages/fx-core/pnpm-lock.yaml
fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/26853166
> fix: update axios depedency

- templates/csharp/message-extension-copilot/appPackage/manifest.json.tpl
- templates/js/message-extension-copilot/appPackage/manifest.json.tpl
- templates/ts/message-extension-copilot/appPackage/manifest.json.tpl
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/26053684
> feat: add semantic descriptions

- templates/js/ai-bot/README.md.tpl
- templates/ts/ai-bot/README.md.tpl
work item: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/26856634
> fix: inconsistent description in AI Chat bot README

- packages/fx-core/src/component/generator/officeAddin/config/projectProperties.ts
- packages/fx-core/src/component/generator/officeAddin/config/projectsJsonData.ts
- packages/fx-core/src/component/generator/officeAddin/generator.ts
- packages/fx-core/src/component/generator/officeAddin/helperMethods.ts
- packages/fx-core/src/error/common.ts
- packages/fx-core/tests/component/generator/officeAddinGenerator.test.ts
- packages/vscode-extension/src/handlers.ts
fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/26858587
> fix: outlook addin generator error handling

- .github/workflows/ui-test.yml
refer to issue: https://github.com/actions/runner-images/issues/9313
> test: downgrade powershell to find certificate.

- .github/workflows/codeql-analysis.yml
https://github.com/github/codeql-action/issues/464
> ci: update codeql permission policy

- packages/fx-core/src/component/driver/deploy/azure/impl/AzureZipDeployImpl.ts
- packages/fx-core/src/error/deploy.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/26896950
> fix: improve error log type and telemetry

- packages/fx-core/src/component/coordinator/index.ts
- packages/fx-core/src/component/generator/officeAddin/config/projectsJsonData.ts
- packages/fx-core/src/component/generator/officeAddin/generator.ts
- packages/fx-core/src/question/create.ts
- packages/fx-core/src/question/inputs/CreateProjectInputs.ts
- packages/fx-core/src/question/options/CreateProjectOptions.ts
- packages/tests/src/e2e/scaffold/OfficeAddinScaffold.tests.ts
- packages/tests/src/utils/constants.ts
fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/26901244
> fix: office addin e2e flow

- packages/sdk/package.json
- packages/sdk/pnpm-lock.yaml
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/26943530
> fix: fix sdk vulnerability

- packages/fx-core/src/error/arm.ts
fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/26933290
> fix: deploy arm error

- packages/cli/package.json
- packages/cli/pnpm-lock.yaml
- packages/fx-core/package.json
- packages/fx-core/pnpm-lock.yaml
fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/26943527
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/26943517
> fix: fx-core and cli deps issues

- packages/sdk/pnpm-lock.yaml
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/26943530
> fix: fix sdk deps

- packages/fx-core/src/component/coordinator/index.ts
- packages/fx-core/src/component/generator/generator.ts
- packages/fx-core/src/component/generator/utils.ts
- packages/fx-core/tests/component/generator/generator.test.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/26356837
> feat: add llm related placehodlers in generator

- packages/vscode-extension/package.json
- packages/vscode-extension/pnpm-lock.yaml
Related bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/26943711
> fix(vsc): upgrade vscode-tas-client for axios issue

- templates/csharp/copilot-plugin-from-scratch-api-key/{{ProjectName}}.csproj.tpl
- templates/csharp/copilot-plugin-from-scratch/{{ProjectName}}.csproj.tpl
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/26961330
> fix: issue of function project name

- templates/csharp/sso-tab/Components/Welcome.razor
> fix: fix UI display problem caused by narrow browser window

- packages/fx-core/src/component/driver/teamsApp/createAppPackage.ts
- packages/fx-core/tests/component/driver/teamsApp/createAppPackage.test.ts
- packages/fx-core/tests/plugins/resource/appstudio/resources-multi-env/templates/appPackage/resources/ai-plugin.json
- packages/manifest/src/index.ts
- packages/manifest/src/pluginManifest.ts
- Add plugin manifest with the initial published version
- Update createAppPackage to include api spec.
> refactor: plugin manifest initial version

- packages/fx-core/src/common/projectTypeChecker.ts
- packages/fx-core/tests/common/projectTypeChecker.test.ts
fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/26965288
> fix: check project manifest file

- packages/cli/src/commonlib/azureLogin.ts
- packages/cli/src/commonlib/m365Login.ts
- packages/cli/src/userInteraction.ts
- packages/cli/tests/unit/ui.tests.ts
fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/26980818
> fix: retire ci enable variable

- packages/teams-agent/src/chat/agent.ts
- packages/teams-agent/src/chat/chatTypings/vscode.proposed.chatProvider.d.ts
- packages/teams-agent/src/chat/chatTypings/vscode.proposed.languageModels.d.ts
- packages/teams-agent/src/chat/copilotInteractions.ts
- packages/teams-agent/src/subCommand/codeToCloudSlashCommand.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/27002829
> feat: update ChatParticipant SDK to lastest version

- packages/teams-agent/package.json
- packages/teams-agent/src/chat/agent.ts
- packages/teams-agent/src/chat/chatTypings/vscode.proposed.chatParticipant.d.ts
- packages/teams-agent/src/chat/chatTypings/vscode.proposed.chatParticipantAdditions.d.ts
- packages/teams-agent/src/chat/slashCommands.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/27002829
> feat: update ChatParticipant SDK to latest version

- packages/adaptivecards-tools-sdk/package.json
- packages/adaptivecards-tools-sdk/pnpm-lock.yaml
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/27024552
> fix: update markdown-it version

- packages/fx-core/src/question/create.ts
- packages/fx-core/src/question/options/CreateProjectOptions.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/26356837
> fix: add preview tag and default value for custom copilot qm

- packages/fx-core/src/common/spec-parser/utils.ts
- packages/fx-core/tests/common/spec-parser/utils.test.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25973952
E2E Test: N/A
> fix(spec-parser): not allow res/req body has type other than json

- packages/teams-agent/src/chat/agent.ts
- packages/teams-agent/src/chat/slashCommands.ts
- packages/teams-agent/src/subCommand/codeToCloudSlashCommand.ts
- packages/teams-agent/src/subCommand/createSlashCommand.ts
- packages/teams-agent/src/subCommand/helpSlashCommand.ts
- packages/teams-agent/src/subCommand/nextStepSlashCommand.ts
- packages/teams-agent/src/subCommand/testCommand.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/27055586
The ChatResult only set the "metadata" attribute, self-defined attribute is not included
> fix: followups invalid

- templates/js/copilot-plugin-from-scratch-api-key/host.json
- templates/js/copilot-plugin-from-scratch-api-key/package.json.tpl
- templates/js/copilot-plugin-from-scratch/host.json
- templates/js/copilot-plugin-from-scratch/package.json.tpl
- templates/ts/copilot-plugin-from-scratch-api-key/host.json
- templates/ts/copilot-plugin-from-scratch-api-key/package.json.tpl
- templates/ts/copilot-plugin-from-scratch/host.json
- templates/ts/copilot-plugin-from-scratch/package.json.tpl
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/26961430
> fix: the code for azure functions can't be hot reloaded

- packages/tests/src/utils/constants.ts
Update related test according to PR: https://github.com/OfficeDev/TeamsFx/pull/10950
> test: update creating SPFx project command string

- packages/tests/src/e2e/collaboration/Permission.tests.ts
success run: https://github.com/OfficeDev/TeamsFx/actions/runs/8152114638
> test: fix e2e test for collaboration

- packages/fx-core/src/common/samples.ts
- packages/fx-core/src/component/generator/utils.ts
- packages/fx-core/tests/common/samples.test.ts
- packages/fx-core/tests/component/generator/generator.test.ts
- packages/vscode-extension/src/controls/sampleGallery/ISamples.ts
- packages/vscode-extension/src/controls/sampleGallery/sampleCard.tsx
Reverts OfficeDev/TeamsFx#10982
> Revert "fix(vsc): sample gallery support LFS image in GitHub rep"

- packages/tests/src/e2e/collaboration/PermissionSPFX.tests.ts
Success run: https://github.com/OfficeDev/TeamsFx/actions/runs/8152934569
> test: fix e2e test for collaboration spfx

- packages/fx-core/src/component/driver/aad/utility/aadAppClient.ts
- packages/fx-core/tests/component/driver/aad/aadAppClient.test.ts
Fix https://dev.azure.com/msazure/Microsoft%20Teams%20Extensibility/_workitems/edit/27071767
Cherry pick changes from https://github.com/OfficeDev/TeamsFx/pull/10907
> fix: credential invalid lifetime error when create AAD app

- packages/adaptivecards-tools-sdk/package.json
- packages/api/package.json
- pnpm-lock.yaml
fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/27043324
> fix: depedency issues

- templates/js/custom-copilot-assistant-assistants-api/src/app/actions.js
- templates/ts/custom-copilot-assistant-assistants-api/src/app/actions.ts
- templates/ts/custom-copilot-assistant-new/src/app/app.ts.tpl
- templates/ts/custom-copilot-basic/README.md.tpl
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/26356837
> fix: typos in custom copilot templates

- templates/js/dashboard-tab/README.md
- templates/js/message-extension-copilot/README.md
- templates/ts/dashboard-tab/README.md
- templates/ts/message-extension-copilot/README.md
[msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/26023634](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/26023634)
> feat: update screenshots to new Teams

- packages/fx-core/src/component/utils/envUtil.ts
fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/27092592
> fix: empty env file path in error messasge

- packages/fx-core/resource/package.nls.json
- packages/fx-core/src/question/create.ts
fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/27080215
> fix: outlook addin ga

- templates/constraints/yml/templates/ts/sso-tab-with-obo-flow/teamsapp.local.yml.tpl.mustache
- templates/ts/sso-tab-with-obo-flow/src/components/sample/EditCode.tsx
- templates/ts/sso-tab-with-obo-flow/teamsapp.local.yml.tpl
fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/27110117
> fix: fix entry point location error, remove redundant dotnet installer

- packages/fx-core/src/component/generator/copilotPlugin/generator.ts
- packages/fx-core/src/component/generator/copilotPlugin/helper.ts
- packages/fx-core/src/core/FxCore.ts
- packages/fx-core/tests/component/generator/copilotPluginGenerator.test.ts
- templates/common/api-plugin-existing-api/appPackage/manifest.json.tpl
- Integrate with spec-parser and generate a plugin
> refactor: integrate with spec-parser to generate for plugin

- .github/workflows/cd.yml
- packages/adaptivecards-tools-sdk/package.json
- packages/api/package.json
- packages/cli/package.json
- packages/fx-core/package.json
- packages/fx-core/src/common/templates-config.json
- packages/sdk-react/package.json
- packages/sdk/package.json
- packages/server/package.json
- packages/tests/package.json
- packages/vscode-extension/package.json
- packages/vscode-ui/package.json
- templates/js/command-and-response/package.json.tpl
- templates/js/notification-http-timer-trigger/package.json.tpl
- templates/js/notification-http-trigger/package.json.tpl
- templates/js/notification-restify/package.json.tpl
- templates/js/notification-timer-trigger/package.json.tpl
- templates/js/workflow/package.json.tpl
- templates/package.json
- templates/ts/command-and-response/package.json.tpl
- templates/ts/notification-http-timer-trigger/package.json.tpl
- templates/ts/notification-http-trigger/package.json.tpl
- templates/ts/notification-restify/package.json.tpl
- templates/ts/notification-timer-trigger/package.json.tpl
- templates/ts/workflow/package.json.tpl
This reverts commit b451148db0c8fea030373f55e358127c4b631fe1.
> ci: Revert "build(release): publish detail" and update permission in CD actions

- packages/adaptivecards-tools-sdk/package.json
- packages/api/package.json
- packages/cli/package.json
- packages/fx-core/package.json
- packages/fx-core/src/common/templates-config.json
- packages/sdk-react/package.json
- packages/sdk/package.json
- packages/server/package.json
- packages/tests/package.json
- packages/vscode-extension/CHANGELOG.md
- packages/vscode-extension/package.json
- packages/vscode-ui/package.json
- templates/js/command-and-response/package.json.tpl
- templates/js/notification-http-timer-trigger/package.json.tpl
- templates/js/notification-http-trigger/package.json.tpl
- templates/js/notification-restify/package.json.tpl
- templates/js/notification-timer-trigger/package.json.tpl
- templates/js/workflow/package.json.tpl
- templates/package.json
- templates/ts/command-and-response/package.json.tpl
- templates/ts/notification-http-timer-trigger/package.json.tpl
- templates/ts/notification-http-trigger/package.json.tpl
- templates/ts/notification-restify/package.json.tpl
- templates/ts/notification-timer-trigger/package.json.tpl
- templates/ts/workflow/package.json.tpl
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/27163852/?view=edit
> fix: fix typo in changelog

- packages/cli/src/commands/common.ts
- packages/cli/src/commands/engine.ts
- packages/cli/src/commands/models/deploy.ts
- packages/cli/tests/unit/commands.tests.ts
- packages/fx-core/src/component/utils/pathUtils.ts
- packages/fx-core/src/core/middleware/projectSettingsLoader.ts
- packages/fx-core/tests/component/envUtil.test.ts
feature: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/27131199
> feat(cli): customized yaml file for `teamsapp deploy` command

- packages/cli/README.md
fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/27179338
> fix: cli broken link in readme

- packages/fx-core/src/component/coordinator/index.ts
- templates/js/api-plugin-from-scratch/README.md
- templates/ts/api-plugin-from-scratch/README.md
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/27000310
- Replace the target template for the copilot plugin from scratch scenario.
- Update the README.md.
> feat: the UI part for the API Plugin template

- templates/csharp/message-extension-copilot/GettingStarted.md
- templates/js/message-extension-copilot/README.md
- templates/ts/message-extension-copilot/README.md
Specify in the readme file to toggle the ME app from the plugins list to improve the accuracy of Copilot calling the plugin.
> docs: update README.md for the Bot ME template

- templates/js/custom-copilot-assistant-new/README.md.tpl
- templates/js/custom-copilot-basic/README.md.tpl
- templates/ts/custom-copilot-assistant-assistants-api/package.json.tpl
- templates/ts/custom-copilot-assistant-new/README.md.tpl
- templates/ts/custom-copilot-assistant-new/package.json.tpl
- templates/ts/custom-copilot-basic/README.md.tpl
- templates/ts/custom-copilot-basic/package.json.tpl
- add openai dependency in package.json as a workaround for teams-ai error
- fix typo in readme
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/27193889
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/27195105/
> fix: custom copilot templates

- packages/fx-core/src/common/constants.ts
- packages/fx-core/src/common/samples.ts
- packages/fx-core/tests/common/samples.test.ts
- packages/fx-core/tests/question/create.test.ts
fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/27226399
> fix: revert sample provider

- packages/vscode-extension/src/commonlib/azureLogin.ts
Add azure sign out notification 'Got it' button.
Fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/27229909/
> fix: add azure signout notification got it button

- packages/fx-core/src/component/generator/copilotPlugin/helper.ts
- packages/fx-core/src/component/generator/generator.ts
- packages/fx-core/src/core/FxCore.ts
- packages/fx-core/tests/core/FxCore.test.ts
- packages/server/src/serverConnection.ts
- packages/server/tests/serverConnection.test.ts
- support for add API in VS [Task 27072638](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/27072638): VS add an API - server
- add telemetry for Apis count asked by @SLdragon  [Task 27213883](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/27213883)
: Add telemetry to include all api count and valid api count when list
> refactor: copilot plugin add API 

- packages/vscode-extension/package.nls.json
- packages/vscode-extension/src/debug/taskTerminal/officeDevTerminal.ts
- packages/vscode-extension/src/officeDevHandlers.ts
- packages/vscode-extension/test/extension/officeDevHandler.test.ts
1. split different task to separate terminal
2. add color to npm install command
3. change some tip messages.
> fix: split different task to separate terminal

- packages/cli/src/spinner.ts
- packages/cli/tests/unit/spinner.tests.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/27092892
> fix: spinner cursor

- packages/vscode-extension/src/controls/sampleGallery/sampleCard.tsx
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/27194270
> fix: update sample gallery image url

- templates/csharp/non-sso-tab-ssr/Components/App.razor.tpl
- templates/csharp/non-sso-tab-ssr/Components/Pages/Hello.razor
- templates/csharp/non-sso-tab-ssr/Components/Pages/TabConfig.razor
- templates/csharp/non-sso-tab/Pages/TabConfig.razor
- templates/csharp/sso-tab-ssr/Components/App.razor.tpl
- templates/csharp/sso-tab-ssr/Components/Pages/TabConfig.razor
- templates/csharp/sso-tab-ssr/Components/Pages/Welcome.razor
- templates/csharp/sso-tab/Pages/TabConfig.razor
git issue: https://github.com/OfficeDev/TeamsFx/issues/11142
Making the `Interactive Server` as the default mode globally.
> fix: fix .net8 Teams TabConfig save button never registered

- .github/workflows/lint-pr.yml
> ci: yaml lint check max line over 100

- packages/fx-core/src/component/driver/apiKey/create.ts
- packages/fx-core/src/component/driver/apiKey/interface/createApiKeyArgs.ts
- packages/fx-core/tests/component/driver/apiKey/create.test.ts
TODO: will update schema after update action is ready.
> perf(apikey): add new input for apiKet/register

- .github/CODEOWNERS
1. clean up code owners and sort by file path
2. add office add-in code owners (delegate by huajie and ning tang)
> refactor: code owner

- templates/js/sso-tab-with-obo-flow/api/package.json
- templates/ts/sso-tab-with-obo-flow/README.md
- templates/ts/sso-tab-with-obo-flow/package.json.tpl
- templates/ts/sso-tab-with-obo-flow/src/components/sample/AzureFunctions.tsx
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/27110117/?view=edit
> fix: fix ts templates source code location and stable the NODE version

- .github/workflows/lint-pr.yml
add WXO AZDO ticket pattern in title checker
> ci: add wxp azdo domain

- packages/vscode-extension/package.json
- packages/vscode-extension/src/chat/consts.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/27300662
fix breaking change of GH Copilot SDK 0325
> fix: fix breaking change 0325

- packages/fx-core/src/common/featureFlags.ts
- [PM Spec](https://microsoft.sharepoint.com/:w:/t/OfficePlatform/EQTzlom9CSFGgAOIro3-sDsBTsmVkXxz6IWCUoJVLp6L9w?e=vW0Dla)
- [ADO Link](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/27130363)
> feat: force the feature OfficeAddin to close[MetaOS]

- packages/cli/package.json
- packages/fx-core/package.json
- packages/fx-core/src/common/templates-config.json
- packages/server/package.json
- packages/tests/package.json
- packages/vscode-extension/package.json
- templates/package.json
This reverts commit eadc6837864fff013af66edce9fbe6a43812fa82.
> build: revert version change

- packages/fx-core/src/common/telemetry.ts
- packages/fx-core/src/component/driver/aad/permissions/index.ts
- packages/fx-core/src/component/utils/metadataGraphPermssion.ts
- packages/fx-core/src/component/utils/metadataRscPermission.ts
- packages/fx-core/src/component/utils/metadataUtil.ts
- packages/fx-core/tests/component/util/metadataGraphPermissionUtil.test.ts
- packages/fx-core/tests/component/util/metadataRscPermissionUtil.test.ts
feat: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/27273820
> feat(permission): rsc and aad permission metadata telemetry

- packages/vscode-extension/src/chat/commands/nextstep/condition.ts
- packages/vscode-extension/src/chat/commands/nextstep/status.ts
- packages/vscode-extension/src/chat/commands/nextstep/types.ts
- packages/vscode-extension/src/commandController.ts
- packages/vscode-extension/src/debug/localTelemetryReporter.ts
- packages/vscode-extension/src/utils/projectStatusUtils.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/27057528
> feat: save debug status to local file

- packages/vscode-extension/src/chat/commands/nextstep/status.ts
- packages/vscode-extension/src/debug/localTelemetryReporter.ts
- packages/vscode-extension/src/utils/projectStatusUtils.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/27057541
> fix: use extension to do credential check

- packages/cli/src/commands/common.ts
- packages/cli/src/commands/models/teamsapp/validate.ts
- packages/cli/src/resource/commands.json
- packages/fx-core/src/component/driver/teamsApp/teamsappMgr.ts
- packages/fx-core/src/component/driver/teamsApp/validateTestCases.ts
- packages/fx-core/tests/component/driver/teamsApp/validate.test.ts
Add new option for validate:
ADO: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/17499574
> feat(cli): add validate option

- packages/vscode-extension/src/chat/commands/create/createCommandHandler.ts
- packages/vscode-extension/src/chat/commands/nextstep/nextstepCommandHandler.ts
- packages/vscode-extension/src/chat/commands/nextstep/status.ts
- packages/vscode-extension/src/chat/handlers.ts
- packages/vscode-extension/src/chat/telemetry.ts
- packages/vscode-extension/src/constants.ts
- packages/vscode-extension/src/extension.ts
- packages/vscode-extension/src/handlers.ts
- packages/vscode-extension/src/telemetry/extTelemetryEvents.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/27315104
> feat: record request id with correlation id for clicking the button in chat response

- packages/fx-core/src/component/driver/teamsApp/createAppPackage.ts
- packages/fx-core/src/component/driver/teamsApp/utils/telemetry.ts
- packages/fx-core/tests/component/driver/teamsApp/createAppPackage.test.ts
- packages/fx-core/tests/plugins/resource/appstudio/resources-multi-env/templates/appPackage/resources/ai-plugin.json
- build zip with files containing placeholders
E2E: https://github.com/OfficeDev/TeamsFx/actions/runs/8461506143/job/23181498967
> refactor: build zip if plugin with placeholders

- packages/fx-core/src/question/create.ts
- packages/fx-core/src/question/inputs/CreateProjectInputs.ts
fix: create project static options
> fix: create project static options

- packages/fx-core/resource/package.nls.json
- packages/fx-core/src/component/driver/aad/error/aadManifestError.ts
- packages/fx-core/src/component/driver/aad/utility/aadManifestHelper.ts
- packages/fx-core/tests/component/driver/aad/aadManifestHelper.test.ts
Fix [Bug 27212810](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/27212810): BI: unhandled error for build aad manifest
> perf: fix unknown error when update aad

- packages/fx-core/src/common/featureFlags.ts
refactor: disable create office xml addin
> refactor: disable create office xml addin

- packages/vscode-extension/src/chat/prompts.ts
fix: update QA prompt
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/26624635
> fix: update QA prompt

- packages/vscode-extension/src/chat/commands/create/createCommandHandler.ts
- packages/vscode-extension/src/chat/commands/nextstep/nextstepCommandHandler.ts
- packages/vscode-extension/src/chat/consts.ts
- packages/vscode-extension/src/chat/handlers.ts
- packages/vscode-extension/src/chat/telemetry.ts
- packages/vscode-extension/src/extension.ts
- packages/vscode-extension/src/telemetry/extTelemetryEvents.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/27385011
> feat: extend telemetry for teams participant

- templates/constraints/yml/actions/apiKeyUpdate.mustache
- templates/constraints/yml/templates/js/copilot-plugin-from-scratch-api-key/teamsapp.local.yml.tpl.mustache
- templates/constraints/yml/templates/js/copilot-plugin-from-scratch-api-key/teamsapp.yml.tpl.mustache
- templates/constraints/yml/templates/ts/copilot-plugin-from-scratch-api-key/teamsapp.local.yml.tpl.mustache
- templates/constraints/yml/templates/ts/copilot-plugin-from-scratch-api-key/teamsapp.yml.tpl.mustache
- templates/csharp/copilot-plugin-from-scratch-api-key/Repair.cs.tpl
- templates/csharp/copilot-plugin-from-scratch-api-key/appPackage/apiSpecificationFile/repair.yml
- templates/csharp/copilot-plugin-from-scratch-api-key/appPackage/manifest.json.tpl
- templates/csharp/copilot-plugin-from-scratch-api-key/teamsapp.local.yml.tpl
- templates/csharp/copilot-plugin-from-scratch-api-key/teamsapp.yml.tpl
- templates/js/copilot-plugin-from-scratch-api-key/appPackage/apiSpecificationFile/repair.yml
- templates/js/copilot-plugin-from-scratch-api-key/appPackage/manifest.json.tpl
- templates/js/copilot-plugin-from-scratch-api-key/src/functions/repair.js
- templates/js/copilot-plugin-from-scratch-api-key/teamsapp.local.yml.tpl
- templates/js/copilot-plugin-from-scratch-api-key/teamsapp.yml.tpl
- templates/ts/copilot-plugin-from-scratch-api-key/appPackage/apiSpecificationFile/repair.yml
- templates/ts/copilot-plugin-from-scratch-api-key/appPackage/manifest.json.tpl
- templates/ts/copilot-plugin-from-scratch-api-key/src/functions/repair.ts
- templates/ts/copilot-plugin-from-scratch-api-key/teamsapp.local.yml.tpl
- templates/ts/copilot-plugin-from-scratch-api-key/teamsapp.yml.tpl
- Add a new apiKey/update action in yaml files.
- Replace the API key auth in API specification files with the bearer token auth.
> refactor: update the API key template based on the latest design

- packages/fx-core/src/question/inputs/CreateProjectInputs.ts
fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/27423689
> fix: ci error

- packages/vscode-extension/package.nls.json
fix: update teams agent qa default message
> fix: update teams agent qa default message

- packages/fx-core/src/common/featureFlags.ts
- packages/fx-core/src/component/generator/officeAddin/generator.ts
- packages/fx-core/src/component/generator/officeXMLAddin/projectConfig.ts
- packages/fx-core/src/question/create.ts
- packages/fx-core/src/question/inputs/CreateProjectInputs.ts
- packages/fx-core/src/question/options/CreateProjectOptions.ts
- packages/fx-core/tests/component/generator/officeAddinGenerator.test.ts
- packages/fx-core/tests/question/create.test.ts
- [PM Spec](https://microsoft.sharepoint.com/:w:/t/OfficePlatform/EQTzlom9CSFGgAOIro3-sDsBTsmVkXxz6IWCUoJVLp6L9w?e=vW0Dla)
- [ADO Link](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/27130363)
When isOfficeJSONAddinEnabled(default false) is true:
> feat: office content add-in[MetaOS]

- packages/vscode-extension/package.nls.json
- packages/vscode-extension/src/chat/commands/nextstep/condition.ts
- packages/vscode-extension/src/chat/commands/nextstep/nextstepCommandHandler.ts
- packages/vscode-extension/src/chat/commands/nextstep/steps.ts
- packages/vscode-extension/src/chat/telemetry.ts
- packages/vscode-extension/src/telemetry/extTelemetryEvents.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/27057532
> fix: string and unsupport prompt in next step

- packages/vscode-extension/src/chat/commands/nextstep/helper.ts
- packages/vscode-extension/src/chat/commands/nextstep/status.ts
- packages/vscode-extension/src/utils/projectStatusUtils.ts
- packages/vscode-extension/test/chat/commands/nextstep/condition.test.ts
- packages/vscode-extension/test/chat/commands/nextstep/nextstepCommandHandler.test.ts
- packages/vscode-extension/test/chat/commands/nextstep/status.test.ts
- packages/vscode-extension/test/chat/commands/nextstep/steps.test.ts
add tests for `packages/vscode-extension/src/chat/commands/nextstep`
> test: add unit tests and refactor for ut

- packages/vscode-extension/test/chat/telemetry.test.ts
- packages/vscode-extension/test/chat/tokenizer.test.ts
- packages/vscode-extension/test/chat/utils.test.ts
- packages/vscode-extension/test/mocks/vsc/chat.ts
- packages/vscode-extension/test/mocks/vscode-mock.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/27426431
* The test case `tokenLength` and `tokenize` of `Tokenizer` will take about 500ms beacuse of token computing.
> test: add unit test for chat telemetry

- packages/cli/src/userInteraction.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/27459566
> fix: missing default value in input prompt

- packages/fx-core/src/component/driver/teamsApp/createAppPackage.ts
- packages/fx-core/src/component/driver/teamsApp/utils/ManifestUtils.ts
- packages/fx-core/tests/component/driver/teamsApp/createAppPackage.test.ts
- packages/fx-core/tests/component/driver/teamsApp/pluginManifestUtils.test.ts
- packages/fx-core/tests/component/generator/copilotPluginGenerator.test.ts
- packages/fx-core/tests/core/FxCore.test.ts
- packages/manifest/src/index.ts
- packages/manifest/src/manifest.ts
- packages/spec-parser/src/constants.ts
- packages/spec-parser/src/manifestUpdater.ts
- packages/spec-parser/test/manifestUpdater.test.ts
- packages/vscode-extension/test/extension/codeLensProvider.test.ts
- templates/csharp/api-plugin-from-scratch/appPackage/manifest.json.tpl
- templates/csharp/api-plugin-from-scratch/{{ProjectName}}.csproj.tpl
- templates/js/api-plugin-from-scratch/appPackage/manifest.json.tpl
- templates/ts/api-plugin-from-scratch/appPackage/manifest.json.tpl
- update manifest based on latest fix on manifest schema
> refactor: manifest fix

- packages/spec-parser/src/manifestUpdater.ts
- packages/spec-parser/test/manifestUpdater.test.ts
[Bug 27424666](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/27424666): [spec-parser] GenerateForCopilot will overwrite other runtimes in plugin manifest
> perf(spec-parser): update runtime if plugin file exists

- templates/js/link-unfurling/README.md.tpl
- templates/js/message-extension-action/README.md.tpl
- templates/js/message-extension/README.md.tpl
- templates/ts/link-unfurling/README.md.tpl
- templates/ts/message-extension-action/README.md.tpl
- templates/ts/message-extension/README.md.tpl
Update READMEs for ME templates that support test tool. Apply this PR to other ME templates https://github.com/OfficeDev/TeamsFx/pull/11292
> feat: update other ME templates for test tool

- templates/common/api-plugin-existing-api/README.md
- templates/common/api-plugin-existing-api/teamsapp.yml.tpl
- templates/constraints/yml/templates/common/api-plugin-existing-api/teamsapp.yml.tpl.mustache
- templates/constraints/yml/templates/csharp/api-plugin-existing-api/teamsapp.yml.tpl.mustache
- templates/constraints/yml/templates/csharp/api-plugin-from-scratch/teamsapp.local.yml.tpl.mustache
- templates/constraints/yml/templates/csharp/api-plugin-from-scratch/teamsapp.yml.tpl.mustache
- templates/constraints/yml/templates/js/api-plugin-from-scratch/teamsapp.local.yml.tpl.mustache
- templates/constraints/yml/templates/js/api-plugin-from-scratch/teamsapp.yml.tpl.mustache
- templates/constraints/yml/templates/ts/api-plugin-from-scratch/teamsapp.local.yml.tpl.mustache
- templates/csharp/api-plugin-existing-api/GettingStarted.md
- templates/csharp/api-plugin-existing-api/teamsapp.yml.tpl
- templates/js/api-plugin-from-scratch/README.md
- templates/js/api-plugin-from-scratch/teamsapp.local.yml.tpl
- templates/js/api-plugin-from-scratch/teamsapp.yml.tpl
- templates/ts/api-plugin-from-scratch/README.md
- templates/ts/api-plugin-from-scratch/teamsapp.local.yml.tpl
- templates/ts/api-plugin-from-scratch/teamsapp.yml.tpl
- remove validate actions
- fix issues in readme
> fix: copilot plugin template for prerelease

- packages/vscode-extension/src/chat/commands/create/templateMetadata.json
Related bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/27480162
> fix(chat): template metadata

- packages/fx-core/resource/package.nls.json
- packages/fx-core/src/core/FxCore.ts
- packages/fx-core/tests/core/FxCore.test.ts
- confirm with user before adding apis
> fix: confirm before adding API

- packages/api/package.json
- packages/api/pnpm-lock.yaml
- packages/fx-core/package.json
- packages/fx-core/pnpm-lock.yaml
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/27552482
> build: eslint deps upgrade

- templates/ts/custom-copilot-assistant-new/infra/azure.bicep.tpl
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/26356837
> fix: missing deployment name in ai-agent-new template

- templates/js/sso-tab-with-obo-flow/package.json.tpl
- templates/ts/ai-assistant-bot/package.json.tpl
- templates/ts/ai-bot/package.json.tpl
- templates/ts/command-and-response/package.json.tpl
- templates/ts/custom-copilot-assistant-assistants-api/package.json.tpl
- templates/ts/custom-copilot-assistant-new/package.json.tpl
- templates/ts/custom-copilot-basic/package.json.tpl
- templates/ts/custom-copilot-rag-custom-api/package.json.tpl
- templates/ts/dashboard-tab/package.json.tpl
- templates/ts/default-bot-message-extension/package.json.tpl
- templates/ts/default-bot/package.json.tpl
- templates/ts/link-unfurling/package.json.tpl
- templates/ts/m365-message-extension/package.json.tpl
- templates/ts/message-extension-action/package.json.tpl
- templates/ts/message-extension/package.json.tpl
- templates/ts/non-sso-tab-default-bot/bot/package.json.tpl
- templates/ts/non-sso-tab-default-bot/tab/package.json.tpl
- templates/ts/notification-restify/package.json.tpl
- templates/ts/sso-tab-with-obo-flow/package.json.tpl
- templates/ts/workflow/package.json.tpl
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/27383658
> fix: update types/node version

- packages/vscode-extension/src/chat/commands/nextstep/condition.ts
- packages/vscode-extension/src/chat/commands/nextstep/status.ts
- packages/vscode-extension/src/chat/commands/nextstep/steps.ts
- packages/vscode-extension/src/chat/commands/nextstep/types.ts
- packages/vscode-extension/test/chat/commands/nextstep/condition.test.ts
- packages/vscode-extension/test/chat/commands/nextstep/status.test.ts
- packages/vscode-extension/test/chat/commands/nextstep/steps.test.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/27570563
> fix: remove prerequisites

- packages/manifest/src/pluginManifest.ts
> refactor: plugin manifest

- packages/fx-core/src/core/FxCore.ts
- packages/fx-core/tests/core/FxCore.test.ts
- packages/server/package.json
- packages/server/src/apis.ts
- packages/server/src/serverConnection.ts
VS: [Pull Request 542963](https://devdiv.visualstudio.com/DevDiv/_git/TeamsFx/pullrequest/542963): refactor: show info bar if api(s) is added successfully
> refactor: show infobar if api is added successfully in vs

- packages/vscode-extension/src/chat/consts.ts
- packages/vscode-extension/src/chat/telemetry.ts
> fix: remove unused package

- packages/fx-core/src/error/common.ts
fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/27601127
> fix: assemble error

- templates/python/custom-copilot-rag-azure-ai-search/.vscode/launch.json.tpl
- templates/python/custom-copilot-rag-azure-ai-search/src/azure_ai_search_data_source.py.tpl
- templates/python/custom-copilot-rag-azure-ai-search/src/indexers/setup.py.tpl
- templates/python/custom-copilot-rag-azure-ai-search/src/prompts/chat/config.json
- templates/python/custom-copilot-rag-customize/.vscode/launch.json.tpl
workitem:
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/27589484
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/27600034
E2E TEST: N/A
> fix: bad local debug entries, object names and model name

- packages/vscode-extension/src/chat/api/vscode.proposed.chatParticipant.d.ts
- packages/vscode-extension/src/chat/api/vscode.proposed.chatProvider.d.ts
- packages/vscode-extension/src/chat/api/vscode.proposed.chatVariableResolver.d.ts
- packages/vscode-extension/src/chat/api/vscode.proposed.languageModels.d.ts
> fix: fix linter

- packages/vscode-extension/test/chat/tokenizer.test.ts
> fix: fix teams participant ut

- packages/fx-core/src/common/constants.ts
- packages/fx-core/src/common/featureFlags.ts
- packages/fx-core/src/question/create.ts
- packages/vscode-extension/package.json
fix: solve conflict with other feature
> fix: solve conflict with other feature

- templates/js/custom-copilot-rag-custom-api/README.md.tpl
- templates/ts/custom-copilot-rag-custom-api/README.md.tpl
bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/27588303/?view=edit
> docs: update broken hyperlink in readme

- packages/fx-core/resource/package.nls.json
- packages/fx-core/src/common/constants.ts
- packages/fx-core/src/common/featureFlags.ts
- packages/fx-core/src/component/driver/apiKey/create.ts
- packages/fx-core/src/component/driver/apiKey/utility/utility.ts
- packages/fx-core/src/component/generator/copilotPlugin/generator.ts
- packages/fx-core/src/component/generator/copilotPlugin/helper.ts
- packages/fx-core/src/core/FxCore.ts
- packages/fx-core/src/question/create.ts
- packages/fx-core/tests/common/featureFlags.test.ts
- packages/fx-core/tests/core/FxCore.test.ts
- packages/fx-core/tests/question/create.test.ts
[Bug 27601109](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/27601109): Remove api key feature flag for sme
> perf: remove api key and multiple parameters feature flag

- packages/vscode-extension/src/chat/consts.ts
> fix: remove help command

- packages/fx-core/src/component/middleware/questionMW.ts
- packages/fx-core/tests/component/driver/apiKey/create.test.ts
bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/27603842
> fix: fix question model for undfined error

- packages/fx-core/src/component/driver/apiKey/update.ts
bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_sprints/taskboard/AuthAndData/Microsoft%20Teams%20Extensibility/Dilithium/CY24Q2/2Wk/2Wk01%20(Apr%2007%20-%20Apr%2020)?workitem=27629063
> fix(apikey): fix hang issue for apikey update

- templates/common/api-plugin-existing-api/README.md
- templates/js/api-plugin-from-scratch/README.md
- templates/ts/api-plugin-from-scratch/README.md
[Bug 27656384](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/27656384): update readme content for copilot plugin
> fix: copilot plugin readme

- templates/js/non-sso-tab-default-bot/infra/azure.parameters.json.tpl
[Bug 27656401](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/27656401): [Pre-Release]multiple features added from Developer Portal project using existing bot provison failed
> fix: azure parameter error in tab-bot template

- .azure-pipelines/apiscan.yml
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/27588266
> ci: azdo api scan pipeline update

- packages/fx-core/src/component/utils/metadataRscPermission.ts
- packages/fx-core/tests/component/util/metadataRscPermissionUtil.test.ts
fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/27674213
> fix(telemetry): rsc metadata

- templates/python/custom-copilot-rag-azure-ai-search/src/indexers/get_data.py
- templates/python/custom-copilot-rag-azure-ai-search/src/indexers/setup.py.tpl
workitem: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/27658305
For better error messages:
> fix: bad env loading

- packages/tests/src/commonlib/constants.ts
- packages/tests/src/commonlib/containeraAppValidator.ts
- packages/tests/src/commonlib/index.ts
- packages/tests/src/commonlib/utilities.ts
- packages/tests/src/e2e/samples/ProvisionBotSSODocker.tests.ts
- packages/tests/src/e2e/samples/sampleCaseFactory.ts
- packages/tests/src/utils/constants.ts
- packages/tests/src/utils/env.ts
- packages/tests/src/utils/executor.ts
Successful workflow:
https://github.com/OfficeDev/TeamsFx/actions/runs/8642767495
> test: Add e2e test support for contianer app

- packages/fx-core/src/component/generator/copilotPlugin/generator.ts
- packages/fx-core/src/component/generator/copilotPlugin/helper.ts
- packages/fx-core/src/core/FxCore.ts
- packages/fx-core/src/index.ts
- packages/vscode-extension/src/handlers.ts
- packages/vscode-extension/test/extension/handlers.test.ts
several fixes:
- warning message after scaffolding for copilot plugin [Task 27690422](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/27690422): warning message for copilot plugin after scaffolding
- allow all HTTP methods [Bug 27676636](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/27676636): Allow patch and delete method in spec for type b copilot
- enable generating response semantics
> fix: copilot plugin improvement

- packages/tests/src/e2e/bot/ProvisionAiBotForPython.tests.ts
- packages/tests/src/e2e/bot/ProvisionAiSearchBotForPython.tests.ts
- packages/tests/src/e2e/bot/ProvisionBasicRAGBotForPython.tests.ts
- packages/tests/src/e2e/caseFactory.ts
- packages/tests/src/utils/constants.ts
workitem: 
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/27551399
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/27551403
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/27454388
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/27454412
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/27178092
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/27178104
> refactor: add e2e tests for custom copilot python templates provision test

- packages/vscode-extension/src/chat/prompts.ts
fix: fix prompt typo in chat agent
> fix: fix prompt typo in chat agent

- packages/vscode-extension/package.json
- packages/vscode-extension/src/chat/api/vscode.proposed.chatParticipant.d.ts
- packages/vscode-extension/src/chat/api/vscode.proposed.chatParticipantAdditions.d.ts
- packages/vscode-extension/src/chat/api/vscode.proposed.chatProvider.d.ts
- packages/vscode-extension/src/chat/api/vscode.proposed.languageModels.d.ts
- packages/vscode-extension/src/chat/commands/create/createCommandHandler.ts
- packages/vscode-extension/src/chat/commands/create/helper.ts
- packages/vscode-extension/src/chat/commands/create/templateMetadata.json
- packages/vscode-extension/src/chat/prompts.ts
- packages/vscode-extension/test/chat/handlers.test.ts
- packages/vscode-extension/test/mocks/vsc/chat.ts
- packages/vscode-extension/test/mocks/vscode-mock.ts
1. Use gpt-4 when matching.
2. Improve prompts to match sample and template.
3. Update Chat APIs.
Related work item: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/27586721
> feat(chat): improve matching prompts and logic

- templates/csharp/sso-tab-ssr/{{ProjectName}}.csproj.tpl
- templates/csharp/sso-tab/{{ProjectName}}.csproj.tpl
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/27696319
> fix: sso tab vulnerabilities

- packages/sdk-react/package.json
- packages/sdk-react/pnpm-lock.yaml
- packages/sdk/package.json
- packages/sdk/pnpm-lock.yaml
- templates/js/dashboard-tab/package.json.tpl
- templates/js/non-sso-tab-default-bot/tab/package.json.tpl
- templates/js/sso-tab-with-obo-flow/package.json.tpl
- templates/ts/dashboard-tab/package.json.tpl
- templates/ts/non-sso-tab-default-bot/tab/package.json.tpl
- templates/ts/sso-tab-with-obo-flow/package.json.tpl
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/27569164
> build: update teams-js dependency

- packages/vscode-extension/src/chat/commands/nextstep/nextstepCommandHandler.ts
- packages/vscode-extension/src/chat/commands/nextstep/steps.ts
- packages/vscode-extension/src/chat/prompts.ts
- packages/vscode-extension/test/chat/commands/nextstep/steps.test.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/27587244
Try once:
Try twice:
> fix: next step prompt and strings

- packages/dotnet-sdk/src/TeamsFx/Credential/TeamsUserCredential.cs
- packages/dotnet-sdk/src/TeamsFx/Microsoft.TeamsFx.csproj
- templates/csharp/non-sso-tab-ssr/Interop/InteropModuleBase.cs.tpl
- templates/csharp/non-sso-tab/Interop/InteropModuleBase.cs.tpl
- templates/csharp/sso-tab-ssr/Interop/InteropModuleBase.cs.tpl
- templates/csharp/sso-tab-ssr/wwwroot/auth-end.html
- templates/csharp/sso-tab-ssr/wwwroot/auth-start.html
- templates/csharp/sso-tab-ssr/{{ProjectName}}.csproj.tpl
- templates/csharp/sso-tab/Interop/InteropModuleBase.cs.tpl
- templates/csharp/sso-tab/wwwroot/auth-end.html
- templates/csharp/sso-tab/wwwroot/auth-start.html
- templates/csharp/sso-tab/{{ProjectName}}.csproj.tpl
https://devblogs.microsoft.com/microsoft365dev/action-required-ensure-your-microsoft-teams-apps-are-ready-for-upcoming-domain-changes/
> build: update dotnet-sdk & templates teams-js dependency

- packages/manifest/src/copilotGptManifest.ts
> refactor: copilot GPT manifest update

- packages/spec-parser/src/constants.ts
- packages/spec-parser/src/utils.ts
- packages/spec-parser/test/specParser.test.ts
[Bug 27750414](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/27750414): Fix spec parser cannot parse api with auth in spec root
> perf(spec-parser): fix root auth in spec is ignored issue, update error msg

- packages/vscode-extension/src/chat/commands/nextstep/steps.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/27588718
> docs: use short links instead of long links

- packages/vscode-extension/src/chat/commands/nextstep/steps.ts
- packages/vscode-extension/src/chat/handlers.ts
- packages/vscode-extension/src/handlers.ts
- packages/vscode-extension/test/chat/handlers.test.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/27587453
https://microsoftapc-my.sharepoint.com/:v:/g/personal/zhiyou_microsoft_com/ERSqpgjuuUtJtI4NDcje-N4BBRuimxm5__sLLJnGvPn9cA?e=Pj5QLO
> fix(chat): move create from followup to command

- packages/api/review/teamsfx-api.api.md
- packages/api/src/generator.ts
- packages/api/src/index.ts
- packages/api/src/types.ts
- packages/fx-core/src/component/generator/templates/templateGenerator.ts
- packages/fx-core/src/core/FxCore.ts
- packages/fx-core/src/index.ts
- packages/fx-core/tests/core/FxCore.create.test.ts
Define API contract for Generator and expose an API in FxCore to agent code to create project by customized generator.
> refactor: create project by customized generator

- .github/CODEOWNERS
- packages/vscode-extension/src/debug/officeTaskHandler.ts
- packages/vscode-extension/src/debug/teamsfxTaskHandler.ts
- packages/vscode-extension/src/extension.ts
Record the local debug success/failure in .fx/projectStatus.json. It would be used in the nextStep for Office GitHub Agent project.
> fix: record localdebug status

- packages/fx-core/src/common/m365/packageService.ts
- packages/fx-core/tests/common/m365/packageService.test.ts
fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/27695673
Refine error message:
> fix: refine m365 package service error message

- packages/api/review/teamsfx-api.api.md
- packages/api/src/types.ts
- packages/fx-core/src/component/generator/copilotPlugin/generator.ts
- packages/fx-core/src/component/generator/copilotPlugin/helper.ts
- packages/fx-core/src/question/create.ts
- packages/fx-core/tests/component/generator/copilotPluginGenerator.test.ts
- packages/fx-core/tests/question/create.test.ts
- VS: https://devdiv.visualstudio.com/DevDiv/_git/TeamsFx/pullrequest/546606?path=/src/TeamsFx/TeamsFx.VisualStudio/ViewModels/Wizards/CopilotWizardViewModel.cs
> fix: scaffolding from API spec with auth

- packages/fx-core/package.json
- packages/fx-core/pnpm-lock.yaml
fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/27820964
> fix: upgrade office-addin-project to 0.8.1

- packages/tests/src/commonlib/constants.ts
- packages/tests/src/commonlib/containeraAppValidator.ts
- packages/tests/src/commonlib/utilities.ts
- packages/tests/src/e2e/samples/ProvisionTabDocker.tests.ts
- packages/tests/src/e2e/samples/sampleCaseFactory.ts
- packages/tests/src/utils/constants.ts
Here is the successful workflow:
https://github.com/OfficeDev/TeamsFx/actions/runs/8829835162
> test: add hello-world-tab docker sample e2e test

- packages/fx-core/package.json
- packages/fx-core/pnpm-lock.yaml
fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/27820964
> fix: upgrade office-addin-manifest@1.13.1

- packages/vscode-extension/src/chat/commands/nextstep/steps.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/27851466
> docs: change join-m365-dev-account link

- templates/python/custom-copilot-assistant-new/.vscode/launch.json.tpl
- templates/python/custom-copilot-basic/.vscode/launch.json.tpl
- templates/python/custom-copilot-rag-azure-ai-search/.vscode/launch.json.tpl
- templates/python/custom-copilot-rag-customize/.vscode/launch.json.tpl
workitem: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/27863219
E2E TEST: N/A
> fix: delete extra comma in launch.json file

- packages/fx-core/src/core/FxCore.ts
TODO: [Task 27854428](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/27854428): string review
> refactor: update string

- packages/sdk/package.json
- packages/sdk/pnpm-lock.yaml
Related issue: https://dev.azure.com/mseng/VSIoT/_componentGovernance/721/alert/189933?typeId=297727
> fix(sdk): upgrade dependency

- templates/csharp/api-plugin-from-scratch/Repairs.cs.tpl
- templates/csharp/api-plugin-from-scratch/appPackage/ai-plugin.json.tpl
- templates/csharp/api-plugin-from-scratch/appPackage/apiSpecificationFile/repair.yml
- templates/js/api-plugin-from-scratch/README.md
- templates/js/api-plugin-from-scratch/appPackage/ai-plugin.json.tpl
- templates/js/api-plugin-from-scratch/appPackage/apiSpecificationFile/repair.yml
- templates/js/api-plugin-from-scratch/src/functions/repairs.js
- templates/ts/api-plugin-from-scratch/README.md
- templates/ts/api-plugin-from-scratch/appPackage/ai-plugin.json.tpl
- templates/ts/api-plugin-from-scratch/appPackage/apiSpecificationFile/repair.yml
- templates/ts/api-plugin-from-scratch/src/functions/repairs.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/27939007
> fix: update API paths and descriptions for repairs

- .github/workflows/cd_trigger.yml
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/27957808
> cd: use webhook to call azdo pipeline instead of PAT

- packages/fx-core/src/common/m365/launchHelper.ts
- packages/fx-core/src/common/m365/packageService.ts
- packages/manifest/src/index.ts
[Bug 27955157](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/27955157): Preview would fail if selected host is outlook/m365 if Gpts
> fix: CLI preview

- packages/api/package.json
fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/27982329
> fix: bump api version

- .github/workflows/cd.yml
- packages/vscode-extension/src/extension.ts
Related bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/27996002
> fix: disable proposed APIs in stable releases

- packages/vscode-extension/package.json
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_sprints/taskboard/AuthAndData/Microsoft%20Teams%20Extensibility/Dilithium/CY24Q2/2Wk/2Wk03%20(May%2005%20-%20May%2018)?workitem=27957613
> ci: lint rule update

- templates/python/custom-copilot-assistant-new/.vscode/launch.json
- templates/python/custom-copilot-assistant-new/teamsapp.local.yml.tpl
- templates/python/custom-copilot-assistant-new/teamsapp.yml.tpl
- templates/python/custom-copilot-basic/.vscode/launch.json
- templates/python/custom-copilot-basic/teamsapp.local.yml.tpl
- templates/python/custom-copilot-basic/teamsapp.yml.tpl
- templates/python/custom-copilot-rag-azure-ai-search/.vscode/launch.json
- templates/python/custom-copilot-rag-azure-ai-search/teamsapp.local.yml.tpl
- templates/python/custom-copilot-rag-azure-ai-search/teamsapp.yml.tpl
- templates/python/custom-copilot-rag-customize/.vscode/launch.json
- templates/python/custom-copilot-rag-customize/teamsapp.local.yml.tpl
- templates/python/custom-copilot-rag-customize/teamsapp.yml.tpl
workitem: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/27894013
E2E TEST: N/A
> fix: hot fix for Python templates to remove Test Tool from the default debug choice

- templates/common/copilot-gpt-basic/appPackage/manifest.json.tpl
- templates/csharp/api-plugin-from-scratch/appPackage/manifest.json.tpl
- templates/js/api-plugin-from-scratch/appPackage/manifest.json.tpl
- templates/js/copilot-gpt-from-scratch-plugin/appPackage/manifest.json.tpl
- templates/ts/api-plugin-from-scratch/appPackage/manifest.json.tpl
- templates/ts/copilot-gpt-from-scratch-plugin/appPackage/manifest.json.tpl
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/27979938
> fix: update copilotExtensions in manifest.json.tpl files

- templates/python/custom-copilot-assistant-new/.vscode/launch.json.tpl
- templates/python/custom-copilot-assistant-new/teamsapp.local.yml.tpl
- templates/python/custom-copilot-assistant-new/teamsapp.yml.tpl
- templates/python/custom-copilot-basic/.vscode/launch.json.tpl
- templates/python/custom-copilot-basic/teamsapp.local.yml.tpl
- templates/python/custom-copilot-basic/teamsapp.yml.tpl
- templates/python/custom-copilot-rag-azure-ai-search/.vscode/launch.json.tpl
- templates/python/custom-copilot-rag-azure-ai-search/teamsapp.local.yml.tpl
- templates/python/custom-copilot-rag-azure-ai-search/teamsapp.yml.tpl
- templates/python/custom-copilot-rag-customize/.vscode/launch.json.tpl
- templates/python/custom-copilot-rag-customize/teamsapp.local.yml.tpl
- templates/python/custom-copilot-rag-customize/teamsapp.yml.tpl
Reverts OfficeDev/TeamsFx#11554
> Revert "fix: hot fix for Python templates to remove Test Tool from the default debug choice"

- .github/CODEOWNERS
- packages/manifest/pluginManifestSchema.json
- schemas/declarativeCopilotSchema.json
- schemas/pluginSchema.json
This PR is for the task to keep the schema in TTK in temporarily in [Feature 27957104](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/27957104): Add validation for GPT related schemas
> feat: add schema in TTK repo for validation

- schemas/pluginSchema.json
- remove deprecated for now to avoid warning shown in VSC
> perf: schema update

- templates/js/copilot-gpt-from-scratch-plugin/appPackage/manifest.json.tpl
- templates/ts/copilot-gpt-from-scratch-plugin/appPackage/manifest.json.tpl
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/28041964
> fix: update the manifest in declarative copilot templates

- schemas/declarativeCopilotSchema.json
Updating the dc schema to the latest
> fix: updating dc schema

- packages/vscode-extension/package.nls.json
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/27996684
> fix: teams agent description

- packages/spec-parser/src/constants.ts
- packages/spec-parser/test/manifestUpdater.test.ts
- templates/common/copilot-gpt-basic/appPackage/declarativeCopilot.json.tpl
- templates/js/api-plugin-from-scratch/appPackage/ai-plugin.json.tpl
- templates/js/copilot-gpt-from-scratch-plugin/appPackage/ai-plugin.json.tpl
- templates/js/copilot-gpt-from-scratch-plugin/appPackage/repairDeclarativeCopilot.json.tpl
- templates/ts/api-plugin-from-scratch/appPackage/ai-plugin.json.tpl
- templates/ts/copilot-gpt-from-scratch-plugin/appPackage/ai-plugin.json.tpl
- templates/ts/copilot-gpt-from-scratch-plugin/appPackage/repairDeclarativeCopilot.json.tpl
- cherry-pick from https://github.com/OfficeDev/TeamsFx/pull/11591
- add commit to fix UT
[Bug 28053011](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/28053011): update schema url for plugin and declarative Copilot.
> fix: update schema url

- templates/js/api-plugin-from-scratch/README.md
- templates/js/copilot-gpt-from-scratch-plugin/README.md
- templates/python/custom-copilot-assistant-new/README.md.tpl
- templates/python/custom-copilot-basic/README.md.tpl
- templates/python/custom-copilot-rag-azure-ai-search/README.md.tpl
- templates/python/custom-copilot-rag-customize/README.md.tpl
- templates/ts/api-plugin-from-scratch/README.md
- templates/ts/copilot-gpt-from-scratch-plugin/README.md
fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/28053231
> fix: cli broken link

- packages/vscode-extension/.eslintignore
- packages/vscode-extension/src/chat/api/vscode.proposed.chatParticipant.d.ts
- packages/vscode-extension/src/chat/api/vscode.proposed.chatParticipantAdditions.d.ts
- packages/vscode-extension/src/chat/api/vscode.proposed.chatProvider.d.ts
- packages/vscode-extension/src/chat/api/vscode.proposed.chatVariableResolver.d.ts
- packages/vscode-extension/src/chat/api/vscode.proposed.languageModelSystem.d.ts
- packages/vscode-extension/src/chat/api/vscode.proposed.languageModels.d.ts
- packages/vscode-extension/src/chat/utils.ts
- packages/vscode-extension/test/chat/handlers.test.ts
- packages/vscode-extension/test/chat/utils.test.ts
- packages/vscode-extension/test/mocks/vsc/chat.ts
- packages/vscode-extension/test/mocks/vscode-mock.ts
- packages/vscode-extension/test/officeChat/handlers.test.ts
- packages/vscode-extension/test/officeChat/mocks/localTuning/utilFunctions.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/28055324
> fix: proposed api breaking changes

- templates/python/custom-copilot-assistant-new/README.md.tpl
- templates/python/custom-copilot-basic/README.md.tpl
- templates/python/custom-copilot-rag-azure-ai-search/README.md.tpl
- templates/python/custom-copilot-rag-customize/README.md.tpl
workitem: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/28042833
> fix: more specific description of known issue

- templates/js/custom-copilot-rag-microsoft365/src/public/auth-end.html
- templates/ts/custom-copilot-rag-microsoft365/src/public/auth-end.html
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/27300222
> build: upgrade teams-js

- packages/fx-core/src/component/coordinator/index.ts
fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/28106330
> fix: duplicated provision summary log

- packages/tests/src/commonlib/appStudioValidator.ts
- packages/tests/src/commonlib/botValidator.ts
- packages/tests/src/commonlib/containeraAppValidator.ts
- packages/tests/src/commonlib/frontendValidator.ts
- packages/tests/src/commonlib/functionValidator.ts
- packages/tests/src/commonlib/keyVaultValidator.ts
- packages/tests/src/commonlib/simpleAuthValidator.ts
- packages/tests/src/e2e/commonUtils.ts
- packages/tests/src/e2e/commonUtils.ts.back
- packages/tests/src/e2e/frontend/BlazorAppHappyPath.tests.ts
fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/28131819
> fix: e2e compile error

- packages/vscode-extension/src/officeChat/commands/create/officeTemplateMetadata.json
- packages/vscode-extension/src/officeChat/commands/nextStep/condition.ts
- packages/vscode-extension/src/officeChat/commands/nextStep/officeNextstepCommandHandler.ts
- packages/vscode-extension/src/officeChat/commands/nextStep/officeSteps.ts
- packages/vscode-extension/src/officeChat/officePrompts.ts
- packages/vscode-extension/test/officeChat/commands/nextstep/condition.test.ts
- packages/vscode-extension/test/officeChat/commands/nextstep/officeSteps.test.ts
fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/28134662/
> fix: fix office gh extension breaks

- packages/vscode-extension/src/officeChat/commands/create/helper.ts
- packages/vscode-extension/src/officeChat/common/skills/projectCreator.ts
- packages/vscode-extension/test/officeChat/commands/create/helper.test.ts
fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/28131819
> fix: fix cf creation failure

- templates/python/custom-copilot-rag-azure-ai-search/README.md.tpl
workitem: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/28105557
> docs: add new section to wiki and readme doc

- templates/ts/api-message-extension-sso/.vscode/launch.json
- templates/ts/api-message-extension-sso/README.md
- templates/ts/copilot-plugin-from-scratch-api-key/.vscode/launch.json
- templates/ts/copilot-plugin-from-scratch-api-key/README.md
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/28133154
> fix: the launch url of API ME templates

- templates/python/custom-copilot-assistant-new/.vscode/launch.json
- templates/python/custom-copilot-assistant-new/teamsapp.local.yml.tpl
- templates/python/custom-copilot-assistant-new/teamsapp.yml.tpl
- templates/python/custom-copilot-basic/.vscode/launch.json
- templates/python/custom-copilot-basic/teamsapp.local.yml.tpl
- templates/python/custom-copilot-basic/teamsapp.yml.tpl
- templates/python/custom-copilot-rag-azure-ai-search/.vscode/launch.json
- templates/python/custom-copilot-rag-azure-ai-search/teamsapp.local.yml.tpl
- templates/python/custom-copilot-rag-azure-ai-search/teamsapp.yml.tpl
- templates/python/custom-copilot-rag-customize/.vscode/launch.json
- templates/python/custom-copilot-rag-customize/teamsapp.local.yml.tpl
- templates/python/custom-copilot-rag-customize/teamsapp.yml.tpl
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/28150299
> build: reapply the patch for main

- templates/common/api-plugin-existing-api/README.md.tpl
- templates/common/copilot-gpt-basic/README.md
- templates/common/copilot-plugin-existing-api-api-key/README.md
- templates/common/copilot-plugin-existing-api/README.md.tpl
- templates/common/copilot-plugin-from-oai-plugin/README.md
- templates/csharp/api-message-extension-sso/GettingStarted.md
- templates/csharp/api-plugin-existing-api/GettingStarted.md.tpl
- templates/csharp/api-plugin-from-scratch/GettingStarted.md
- templates/csharp/copilot-plugin-existing-api-api-key/GettingStarted.md
- templates/csharp/copilot-plugin-existing-api/GettingStarted.md.tpl
- templates/csharp/copilot-plugin-from-oai-plugin/GettingStarted.md
- templates/csharp/copilot-plugin-from-scratch-api-key/GettingStarted.md
- templates/csharp/copilot-plugin-from-scratch/GettingStarted.md
- templates/js/api-message-extension-sso/README.md
- templates/js/api-plugin-from-scratch/README.md
- templates/js/copilot-gpt-from-scratch-plugin/README.md
- templates/js/copilot-plugin-from-scratch-api-key/README.md
- templates/js/copilot-plugin-from-scratch/README.md
- templates/ts/api-message-extension-sso/README.md
- templates/ts/api-plugin-from-scratch/README.md
- templates/ts/copilot-gpt-from-scratch-plugin/README.md
- templates/ts/copilot-plugin-from-scratch-api-key/README.md
- templates/ts/copilot-plugin-from-scratch/README.md
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/28164792
> perf: update copilot/sme template to switch to new Teams

- packages/vscode-extension/src/chat/commands/create/createCommandHandler.ts
- packages/vscode-extension/src/chat/commands/nextstep/nextstepCommandHandler.ts
- packages/vscode-extension/src/chat/prompts.ts
- packages/vscode-extension/src/officeChat/commands/create/officeCreateCommandHandler.ts
- packages/vscode-extension/src/officeChat/officePrompts.ts
> fix(vsc): activation failure

- packages/fx-core/src/common/templates-config.json
- packages/vscode-extension/package.json
- templates/package.json
Change the version number to match the publish.
> build: reversion for release

- templates/ts/api-message-extension-sso/.vscode/launch.json
- templates/ts/api-message-extension-sso/README.md
- templates/ts/copilot-plugin-from-scratch-api-key/.vscode/launch.json
- templates/ts/copilot-plugin-from-scratch-api-key/README.md
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/28133154
> fix: update launch URLs

- packages/vscode-extension/src/extension.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/28202147
> fix: hide chat pariticipant entries

- packages/fx-core/src/component/generator/generatorAction.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/28133154
> fix: wrong template url

- packages/fx-core/src/component/generator/copilotPlugin/helper.ts
- packages/fx-core/src/core/FxCore.ts
- packages/fx-core/tests/core/FxCore.test.ts
- packages/spec-parser/src/manifestUpdater.ts
- packages/spec-parser/test/manifestUpdater.test.ts
Cherry pick fix from dev to main: https://github.com/OfficeDev/teams-toolkit/pull/11671
> perf(spec-parser): fix issue that OperationOnlyContainsOptionalParam doesn't display

- packages/fx-core/src/question/create.ts
- packages/fx-core/tests/question/create.test.ts
[Bug 28165940](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/28165940): Hide "Create" from Create New when GitHub Copilot Chat is not enabled
- if disabled
> fix: hide group name

- packages/fx-core/src/common/m365/launchHelper.ts
- packages/manifest/src/index.ts
- packages/manifest/src/manifest.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/28133154
> fix: launch the api ME with AAD auth template using manifest

- .github/workflows/vscode-marketplace.yml
related issue: https://github.com/Azure/login/issues/447
> ci: update publish ci

- packages/cli/src/cmds/preview/constants.ts
- packages/fx-core/src/core/environmentName.ts
- packages/fx-core/src/core/middleware/utils/v3MigrationUtils.ts
- packages/fx-core/tests/core/middleware/migration/migrationUtilsV3.test.ts
- packages/vscode-extension/media/itp/itp.md
- packages/vscode-extension/package.json
- packages/vscode-extension/src/chat/commands/nextstep/steps.ts
- packages/vscode-extension/src/controls/Survey.tsx
- packages/vscode-extension/src/controls/webviewDocs/accountHelp.tsx
- packages/vscode-extension/src/controls/webviewDocs/functionBasedNotificationBot.tsx
- packages/vscode-extension/src/controls/webviewDocs/restifyServerNotificationBot.tsx
- packages/vscode-extension/src/controls/webviewDocs/workflowBot.tsx
- packages/vscode-extension/src/debug/constants.ts
- packages/vscode-extension/test/chat/commands/nextstep/steps.test.ts
- packages/vscode-extension/test/extension/handlers.test.ts
[Bug 27674009](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/27674009): [Pre-Release]"learn more" not updated to "get more info" in some strings
> refactor: update "learn more"

- templates/js/non-sso-tab/appPackage/manifest.json.tpl
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/28252478
> fix: a typo in manifest.json.tpl

- packages/fx-core/src/component/generator/spfx/depsChecker/generatorChecker.ts
- packages/fx-core/src/error/common.ts
fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/28251701
> fix: add source for npm install error

- packages/fx-core/src/component/generator/copilotPlugin/helper.ts
- packages/spec-parser/src/adaptiveCardGenerator.ts
- packages/spec-parser/src/utils.ts
- packages/spec-parser/test/adaptiveCardGenerator.test.ts
bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_sprints/taskboard/AuthAndData/Microsoft%20Teams%20Extensibility/Dilithium/CY24Q2/2Wk/2Wk04%20(May%2019%20-%20Jun%2001)?workitem=28240624
> fix(spec parser): fix multiple media bug

- packages/fx-core/src/component/driver/script/scriptDriver.ts
- packages/fx-core/src/component/utils/charsetUtils.ts
- packages/fx-core/tests/component/driver/script/scriptDriver.test.ts
fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/28175767
> fix: charset for azure deploy cli

- packages/cli/src/prompts/utils.ts
Fix issue that user cannot scroll down
- if pageSize >= chocies.length, set pageStart to 0.
- otherwise, slide the page window.
new app
new sample
> fix(cli): cannot scroll down 

- packages/fx-core/src/component/generator/utils.ts
- packages/fx-core/tests/component/generator/generator.test.ts
fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/28290825
> fix: new generator

- templates/js/sso-tab-with-obo-flow/appPackage/manifest.json.tpl
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/28288765
> fix: update the manifest version

- packages/cli/src/telemetry/cliTelemetryEvents.ts
- packages/fx-core/src/common/telemetry.ts
- packages/fx-core/src/common/wrappedAxiosClient.ts
- packages/fx-core/src/component/driver/arm/util/bicepChecker.ts
- packages/fx-core/src/component/driver/middleware/addSWADeployTelemetry.ts
- packages/fx-core/src/component/driver/middleware/addStartAndEndTelemetry.ts
- packages/fx-core/src/component/driver/teamsApp/utils/telemetry.ts
- packages/fx-core/src/component/feature/sso.ts
- packages/fx-core/src/component/generator/spfx/utils/constants.ts
- packages/fx-core/src/component/generator/spfx/utils/telemetry-helper.ts
- packages/fx-core/src/component/middleware/actionExecutionMW.ts
- packages/fx-core/src/component/resource/botService/constants.ts
- packages/fx-core/src/component/telemetry.ts
- packages/fx-core/src/component/utils/depsChecker/common.ts
- packages/fx-core/src/component/utils/teamsFxTelemetryReporter.ts
- packages/fx-core/src/core/FxCore.ts
- packages/fx-core/src/core/telemetry.ts
- packages/fx-core/tests/component/driver/aad/create.test.ts
- packages/fx-core/tests/component/driver/aad/update.test.ts
- packages/fx-core/tests/component/middleware/middleware.test.ts
- packages/vscode-extension/src/telemetry/extTelemetryEvents.ts
- packages/vscode-extension/test/extension/handlers.test.ts
1. fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/28314530
2. unify telemetry property shared keys and values
> fix: renew error message property and unify telemetry property keys

- templates/python/custom-copilot-assistant-assistants-api/src/requirements.txt
- templates/python/custom-copilot-assistant-new/src/bot.py.tpl
- templates/python/custom-copilot-assistant-new/src/requirements.txt
- templates/python/custom-copilot-basic/src/requirements.txt
- templates/python/custom-copilot-rag-azure-ai-search/src/requirements.txt
- templates/python/custom-copilot-rag-customize/src/requirements.txt
workitem:
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/28347260
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/28370609
> fix: upgrade teams-ai and remove bad codes

- packages/fx-core/src/component/deps-checker/constant/helpLink.ts
- packages/fx-core/src/component/deps-checker/internal/vxTestAppChecker.ts
- packages/fx-core/src/core/environmentName.ts
work item:
* https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/28370264/
* https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/28370313/
> fix: remove useless aka link

- packages/fx-core/src/component/utils/envUtil.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/28357001
> fix: consistant env name regex

- templates/js/api-plugin-from-scratch-bearer/.vscode/tasks.json
- templates/js/api-plugin-from-scratch-oauth/.vscode/tasks.json
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/28384066
> fix: del "Watch backend" task in js template

- templates/csharp/sso-tab-ssr/appPackage/manifest.json.tpl
- templates/csharp/sso-tab-ssr/infra/azure.bicep
- templates/csharp/sso-tab-ssr/teamsapp.local.yml.tpl
- templates/csharp/sso-tab/appPackage/manifest.json.tpl
- templates/csharp/sso-tab/infra/azure.bicep
- templates/csharp/sso-tab/teamsapp.local.yml.tpl
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/28289208/
> fix: update TAB_HOSTNAME in manifest and local config files

- packages/fx-core/src/component/generator/copilotPlugin/helper.ts
- packages/spec-parser/src/specParser.ts
- packages/spec-parser/test/specParser.test.ts
https://github.com/OfficeDev/teams-toolkit/issues/11790
> perf(spec-parser): fix AC gen issue due to special chars in operationId

- packages/fx-core/src/common/constants.ts
https://dev.azure.com/msazure/Microsoft%20Teams%20Extensibility/_workitems/edit/28370365
> refactor: clean up unused aka link

- packages/tests/src/e2e/m365/DeployLinkUnfurling.tests.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/28398183
> test: remove check for bot id for linkunfurling e2e test

- packages/cli/src/commands/engine.ts
- packages/cli/tests/unit/engine.tests.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/28374462
> fix: cli missing telemetry

- packages/fx-core/src/component/m365/constants.ts
- packages/fx-core/src/component/m365/launchHelper.ts
- packages/fx-core/tests/component/m365/launchHelper.test.ts
[Task 28434489](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/28434489): Launch Copilot if outlook/office
> feat: launch copilot in outlook/office

- packages/vscode-extension/src/officeChat/common/planner.ts
- packages/vscode-extension/src/officeChat/common/skills/codeGenerator.ts
- packages/vscode-extension/src/officeChat/common/skills/codeIssueCorrector.ts
- packages/vscode-extension/src/officeChat/common/telemetryConsts.ts
- packages/vscode-extension/src/officeChat/consts.ts
- packages/vscode-extension/src/officeChat/officePrompts.ts
- packages/vscode-extension/test/officeChat/common/planner.test.ts
- packages/vscode-extension/test/officeChat/common/skills/codeGenerator.test.ts
- packages/vscode-extension/test/officeChat/common/skills/codeIssueCorrector.test.ts
Made some internal code flow tuning changes, reduce the average code generation time from 58 seconds to 35 seconds.
> refactor: Performance improvement in Office copilot chat agent.

- templates/csharp/empty/README.md.tpl
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/28395963
> fix: gettingstarted typo

- packages/tests/src/ui-test/localdebug/localdebug-obo-tab-ts.test.ts
- packages/tests/src/ui-test/localdebug/localdebug-obo-tab.test.ts
- packages/tests/src/ui-test/localdebug/localdebugContext.ts
- packages/tests/src/utils/playwrightOperation.ts
1. update the outlook app preview url
2. update timer trigger bot validation
> test: update the outlook app preview url

- packages/tests/src/ui-test/migration/sample-org-user-search-connector/sample-org-user-search-connector-debug-upgrade-debug.test.ts
- packages/tests/src/ui-test/migration/sample-org-user-search-connector/sample-org-user-search-connector-provision-upgrade-provision-debug.test.ts
- packages/tests/src/ui-test/migration/sample-org-user-search-connector/sample-org-user-search-connector-upgrade-debug.test.ts
- packages/tests/src/ui-test/migration/sample-org-user-search-connector/sample-org-user-search-connector-upgrade-provision-debug.test.ts
- packages/tests/src/ui-test/samples/sample-localdebug-dashboard.test.ts
- packages/tests/src/ui-test/samples/sample-localdebug-hello-world-tab-outlook.test.ts
- packages/tests/src/ui-test/samples/sample-localdebug-hello-world-tab-with-backend.test.ts
- packages/tests/src/ui-test/samples/sample-localdebug-query-org.test.ts
- packages/tests/src/ui-test/samples/sample-localdebug-todo-list-with-m365.test.ts
- packages/tests/src/ui-test/samples/sample-remotedebug-query-org.test.ts
- packages/tests/src/ui-test/samples/sample-remotedebug-todo-list-with-m365.test.ts
- packages/tests/src/utils/playwrightOperation.ts
fix samples: 
- sample-localdebug-todo-list-with-m365 
- sample-localdebug-dashboard
- sample-localdebug-hello-world-tab-outlook 
- sample-localdebug-query-org
- sample-localdebug-hello-world-tab-with-backend
> test: fix can\'t find sample page element

- packages/vscode-extension/package.json
- packages/vscode-extension/src/extension.ts
- packages/vscode-extension/src/handlers.ts
- packages/vscode-extension/src/handlers/lifecycleHandlers.ts
- packages/vscode-extension/test/extension/handlers.test.ts
- packages/vscode-extension/test/handlers/lifecycleHandlers.test.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/28471788
> refactor: move create new project handler to seperate file

- templates/csharp/api-plugin-from-scratch-bearer/teamsapp.yml.tpl
- templates/csharp/api-plugin-from-scratch-oauth/teamsapp.local.yml.tpl
- templates/csharp/api-plugin-from-scratch-oauth/teamsapp.yml.tpl
- templates/csharp/api-plugin-from-scratch/teamsapp.local.yml.tpl
- templates/csharp/api-plugin-from-scratch/teamsapp.yml.tpl
[Bug 28482557](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/28482557): [VS]Prepare Teams App Dependencies failed for Copilot Plugin from Scratch with none auth project
> fix: remove validation action

- templates/csharp/sso-tab-ssr/{{ProjectName}}.csproj.tpl
- templates/csharp/sso-tab/{{ProjectName}}.csproj.tpl
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/28517168
> fix(vs-template): upgrade Azure.Identity to avoid vulnerabilities

- packages/tests/src/e2e/frontend/BlazorAppHappyPath.tests.ts
https://github.com/OfficeDev/teams-toolkit/actions/runs/9609789961
> test: update test case since template updated

- templates/csharp/api-plugin-from-scratch-bearer/env/.env.dev.user
- templates/csharp/api-plugin-from-scratch-bearer/env/.env.local.user
- templates/csharp/api-plugin-from-scratch/Repairs.cs.tpl
p0 bug fix:
1. https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/28484156
2. https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/28500700
> fix: fix copilot plugin template p0 BUG

- templates/csharp/api-plugin-from-scratch-bearer/teamsapp.yml.tpl
- templates/csharp/api-plugin-from-scratch-oauth/teamsapp.yml.tpl
- templates/csharp/api-plugin-from-scratch/teamsapp.yml.tpl
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/28529887/
> fix: deploy issue in TypeB template

- templates/csharp/api-plugin-from-scratch-bearer/appPackage/ai-plugin.json.tpl
- templates/csharp/api-plugin-from-scratch-bearer/env/.env.dev.user
- templates/csharp/api-plugin-from-scratch-bearer/env/.env.local.user
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/28553234
> fix: fix JSON format in the copilot plugin API key template

- packages/vscode-extension/src/handlers/officeDevHandlers.ts
- packages/vscode-extension/test/handlers/officeDevHandler.test.ts
Removed auto popup install dependency.
> fix: remove auto popup install dependency

- packages/fx-core/src/common/telemetry.ts
- packages/fx-core/src/common/wrappedAxiosClient.ts
- packages/fx-core/tests/common/wrappedAxiosClient.test.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/28600294
> fix: mos api telemetry

- packages/tests/src/e2e/bot/ProvisionAppServiceNotificationBot.tests.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/28602199
> test: fix e2e test number link

- .github/actions/setup-project/action.yml
- .github/workflows/cd.yml
- .github/workflows/e2e-test.yml
- .github/workflows/env-checker-ci-pr.yml
- .github/workflows/env-checker-ci-schedule.yml
- .github/workflows/rerun.yml
- .github/workflows/templates-ci.yml
- .github/workflows/ui-test.yml
https://github.com/pnpm/action-setup/issues/135
> ci: upgrade pnpm setup to v4

- .github/workflows/ui-test.yml
- packages/tests/scripts/pvt.json
- packages/tests/src/ui-test/localdebug/localdebug-aiassistant-bot-ts.test.ts
- packages/tests/src/ui-test/localdebug/localdebug-aichat-bot-py.test.ts
- packages/tests/src/ui-test/localdebug/localdebug-aichat-bot-ts.test.ts
- packages/tests/src/ui-test/localdebug/localdebug-bot-ts.test.ts
- packages/tests/src/ui-test/localdebug/localdebug-command-and-response-ts.test.ts
- packages/tests/src/ui-test/localdebug/localdebug-dashboard-tab-ts.test.ts
- packages/tests/src/ui-test/localdebug/localdebug-dashboard-tab.test.ts
- packages/tests/src/ui-test/localdebug/localdebug-link-unfurling-ts.test.ts
- packages/tests/src/ui-test/localdebug/localdebug-msg-newapi-apikey-ts.test.ts
- packages/tests/src/ui-test/localdebug/localdebug-msg-newapi-ts.test.ts
- packages/tests/src/ui-test/localdebug/localdebug-msg-ts.test.ts
- packages/tests/src/ui-test/localdebug/localdebug-msgsa-ts.test.ts
- packages/tests/src/ui-test/localdebug/localdebug-notification-func-timertrigger-ts.test.ts
- packages/tests/src/ui-test/localdebug/localdebug-notification-func-ts.test.ts
- packages/tests/src/ui-test/localdebug/localdebug-notification-restify-ts.test.ts
- packages/tests/src/ui-test/localdebug/localdebug-notification-timertrigger-ts.test.ts
- packages/tests/src/ui-test/localdebug/localdebug-obo-tab-ts.test.ts
- packages/tests/src/ui-test/localdebug/localdebug-spfx-minimal.test.ts
- packages/tests/src/ui-test/localdebug/localdebug-spfx-none.test.ts
- packages/tests/src/ui-test/localdebug/localdebug-spfx.test.ts
- packages/tests/src/ui-test/localdebug/localdebug-tab-nosso-ts.test.ts
- packages/tests/src/ui-test/localdebug/localdebug-workflow-bot-ts.test.ts
- packages/tests/src/ui-test/localdebug/localdebugContext.ts
- packages/tests/src/ui-test/remotedebug/remotedebug-spfxreact-import-multiple.test.ts
- packages/tests/src/utils/commonUtils.ts
1. remote debug test: import multiple SPFx web part
2. support more options for local debug
> test: import multiple SPFx web part

- templates/csharp/workflow/Config.cs.tpl
- templates/csharp/workflow/Program.cs.tpl
- templates/csharp/workflow/appsettings.Development.json
- templates/csharp/workflow/appsettings.json
- templates/csharp/workflow/infra/azure.bicep
- templates/csharp/workflow/infra/azure.parameters.json.tpl
- templates/csharp/workflow/infra/botRegistration/azurebot.bicep
- templates/csharp/workflow/teamsapp.local.yml.tpl
- templates/csharp/workflow/teamsapp.yml.tpl
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/28584802
> feat: update c# workflow templates to msi

- packages/cli/src/commonlib/m365Login.ts
- packages/cli/src/commonlib/m365LoginUserPassword.ts
fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/28641303
> fix: support m365 non-interactive login

- packages/tests/src/e2e/bot/ProvisionWorkflowBot.dotnet.dotnet.tests.ts
Automate workflow bot test plan:
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/28629530
> test: add e2e test for dotnot workflow bot

- packages/cli/src/commonlib/m365Login.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/28666118
> fix: m365 token provider selection logic

- packages/fx-core/src/component/generator/officeAddin/generator.ts
- packages/fx-core/tests/component/generator/officeAddinGenerator.test.ts
fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/28694159
> fix: office add-in webpack config

- packages/fx-core/src/component/generator/officeAddin/generator.ts
- packages/fx-core/tests/component/generator/officeAddinGenerator.test.ts
fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/28693952
> fix: missing readme for outlook add-in

- templates/js/dashboard-tab/README.md
- templates/js/default-bot/README.md.tpl
- templates/js/m365-message-extension/README.md.tpl
- templates/js/message-extension-action/README.md.tpl
- templates/js/message-extension-copilot/README.md.tpl
- templates/js/message-extension/README.md.tpl
- templates/js/non-sso-tab/README.md
- templates/js/sso-tab-with-obo-flow/README.md
- templates/ts/dashboard-tab/README.md
- templates/ts/default-bot/README.md.tpl
- templates/ts/m365-message-extension/README.md.tpl
- templates/ts/message-extension-action/README.md.tpl
- templates/ts/message-extension-copilot/README.md.tpl
- templates/ts/message-extension/README.md.tpl
- templates/ts/non-sso-tab/README.md
- templates/ts/sso-tab-with-obo-flow/README.md
Bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/28707719?src=WorkItemMention&src-action=artifact_link
> docs: update Preview the app on mobile clients link

- packages/vscode-extension/test/officeChat/utils.test.ts
> test: fix office-addin test

- packages/vscode-extension/src/handlers/openLinkHandlers.ts
Related bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/28738498
> fix(vsc): help link

- templates/csharp/notification-http-timer-trigger-isolated/infra/azure.bicep
- templates/csharp/notification-http-timer-trigger/infra/azure.bicep
- templates/csharp/notification-http-trigger-isolated/infra/azure.bicep
- templates/csharp/notification-http-trigger/infra/azure.bicep
- templates/csharp/notification-timer-trigger-isolated/infra/azure.bicep
- templates/csharp/notification-timer-trigger/infra/azure.bicep
- templates/js/copilot-plugin-from-scratch-api-key/infra/azure.parameters.json.tpl
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/28752642
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/28752429
> fix: fix templates error

- packages/tests/src/utils/executor.ts
success test case: https://github.com/OfficeDev/teams-toolkit/actions/runs/9986236595
> test: del az login cli validation

- packages/vscode-extension/package.json
Npm script used by vscode:prepublish.
> fix(vsc): missing package script

- packages/dotnet-sdk/CHANGELOG.md
- packages/dotnet-sdk/src/TeamsFx/Microsoft.TeamsFx.csproj
https://github.com/OfficeDev/teams-toolkit/issues/11677
> fix: update botbuilder dependencies

- .github/workflows/ui-test.yml
- packages/tests/README.md
1. use latest stable version of vscode
2. remove proposed api which is not in use now
> test: use latest stable vscode version

- packages/fx-core/src/common/featureFlags.ts
- packages/fx-core/src/component/developerPortalScaffoldUtils.ts
- packages/fx-core/src/component/driver/teamsApp/constants.ts
- packages/fx-core/src/component/driver/teamsApp/utils/ManifestUtils.ts
- packages/fx-core/tests/component/driver/teamsApp/constants.test.ts
- packages/fx-core/tests/component/driver/teamsApp/manifestUtils.test.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/28754104
> fix: groupchat compatibility

- packages/cli/src/commands/engine.ts
- packages/fx-core/src/common/correlator.ts
- packages/fx-core/tests/common/correlator.test.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/28383940/
> fix: missing correlator id

- packages/vscode-extension/test/mocks/vsc/extHostedTypes.ts
- packages/vscode-extension/test/mocks/vsc/index.ts
- packages/vscode-ui/package.json
- packages/vscode-ui/pnpm-lock.yaml
- packages/vscode-ui/tests/mocks/vsc/extHostedTypes.ts
- packages/vscode-ui/tests/mocks/vsc/index.ts
Related bugs:
1. https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/28823900
2. https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/28823903
3. https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/28823907
4. https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/28823911
> fix: incomplete sanitization

- packages/tests/scripts/pvt.json
- packages/tests/src/ui-test/localdebug/localdebug-chatdata-customize-js-openai.test.ts
- packages/tests/src/ui-test/localdebug/localdebug-chatdata-customize-py-openai.test.ts
- packages/tests/src/ui-test/localdebug/localdebug-chatdata-customize-ts-openai.test.ts
- packages/tests/src/ui-test/localdebug/localdebugContext.ts
- packages/tests/src/utils/env.ts
for task https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/28809982/
> test: add localdebug testcase for open ai

- packages/fx-core/src/common/stringUtils.ts
- packages/fx-core/src/component/driver/middleware/addSWADeployTelemetry.ts
- packages/fx-core/src/component/driver/script/scriptDriver.ts
- packages/fx-core/tests/component/util/envUtils.test.ts
- packages/fx-core/tests/component/util/stringUtils.test.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/28842735
> fix: mask secret for progress title of script action

- packages/sdk/package.json
- packages/sdk/pnpm-lock.yaml
- packages/sdk/test/e2e/node/apiKeyProvider.spec.ts
- packages/sdk/test/e2e/node/bearerTokenAuthProvider.spec.ts
bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/28823892
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/28823910
> test: fix codeql alerts in sdk e2e test

- packages/sdk/test/e2e/node/basicAuthProvider.spec.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/28823908
Success SDK E2E test: https://github.com/OfficeDev/teams-toolkit/actions/runs/10158433477/job/28090486777
> fix: sdk e2e codeql warning

- packages/adaptivecards-tools-sdk/README.md
- packages/adaptivecards-tools-sdk/src/AdaptiveCard.tsx
- packages/adaptivecards-tools-sdk/src/AdaptiveCards.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/28807677
> feat: mark adaptivecards-tools apis as deprecated

- packages/vscode-extension/src/handlers/openLinkHandlers.ts
Related bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/28738498
> fix(vsc): lifecycle link

- packages/fx-core/src/component/generator/officeAddin/generator.ts
- packages/fx-core/tests/component/generator/officeAddinGenerator.test.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/28823902
> fix: shell command injection

- packages/fx-core/tests/component/deps-checker/testToolChecker.test.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/28823906
> fix: incomplete sanitization CodeQL Warning

- .github/workflows/e2e-test.yml
workitem: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/28888483
reference: https://github.com/openai/evals/issues/918
> fix: upgrade pip when setup

- .github/workflows/e2e-test.yml
workitem: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/28888483
> fix: need to upgrade pip when setup python

- packages/fx-core/package.json
- packages/fx-core/pnpm-lock.yaml
- packages/fx-core/src/component/deps-checker/util/cpUtils.ts
- packages/fx-core/src/component/local/localCertificateManager.ts
- packages/fx-core/src/component/local/process.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/28823894
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/28823895
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/28823896
> fix: command injection of CodeQL warning

- packages/fx-core/src/component/driver/script/scriptDriver.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/28967958
> refactor: clean test code

- packages/fx-core/src/component/generator/apiSpec/helper.ts
- packages/fx-core/tests/component/generator/copilotGenerator.test.ts
bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/28957038
> fix(custom api): add json path for custom api generator

- packages/tests/src/e2e/customcopilotbot/ProvisionCustomCopilotAgentAssistantsApiBotForPythonUsingAZOAI.tests.ts
- packages/tests/src/e2e/debug/DebugCustomCopilotAgentAssistantsApiBotForPython.tests.ts
- packages/tests/src/e2e/debug/DebugCustomCopilotAgentNewBotForPython.tests.ts
workitem: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/28967850
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/28957868
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/28957869
> test: add e2e for custom-copilot-agent-assistant-api using azure openai

- packages/fx-core/src/common/featureFlags.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/28970311
> feat: enable async app validation

- packages/fx-core/src/component/driver/script/scriptDriver.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/29002901
> fix: script driver not output script content

- packages/fx-core/src/component/generator/apiSpec/helper.ts
bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/29004014
> perf: update generator for json path

- packages/sdk/package.json
- packages/sdk/pnpm-lock.yaml
- packages/sdk/src/conversation/messageBuilder.ts
- packages/sdk/test/unit/node/conversation/messageBuilder.spec.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/28807684
> feat: remove adaptivecard tools dependency in teamsfx

- packages/fx-core/src/component/deps-checker/util/cpUtils.ts
bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_sprints/taskboard/Teams%20Extensibility%20E2E%20Team/Microsoft%20Teams%20Extensibility/Dilithium/CY24Q3/2Wk/2Wk09%20(Jul%2028%20-%20Aug%2010)?workitem=29002807
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/29002807
> fix: local debug command execute failed

- templates/js/ai-assistant-bot/src/app.js
- templates/js/ai-bot/src/app.js
- templates/js/custom-copilot-assistant-assistants-api/src/app/app.js
- templates/js/custom-copilot-assistant-new/src/app/app.js.tpl
- templates/js/custom-copilot-basic/src/app/app.js.tpl
- templates/js/custom-copilot-rag-azure-ai-search/src/app/app.js.tpl
- templates/js/custom-copilot-rag-custom-api/src/app/app.js.tpl
- templates/js/custom-copilot-rag-customize/src/app/app.js.tpl
- templates/js/custom-copilot-rag-microsoft365/src/app/app.js.tpl
- templates/ts/ai-assistant-bot/src/app.ts
- templates/ts/ai-bot/src/app.ts
- templates/ts/custom-copilot-assistant-assistants-api/src/app/app.ts
- templates/ts/custom-copilot-assistant-new/src/app/app.ts.tpl
- templates/ts/custom-copilot-basic/src/app/app.ts.tpl
- templates/ts/custom-copilot-rag-azure-ai-search/src/app/app.ts.tpl
- templates/ts/custom-copilot-rag-custom-api/src/app/app.ts.tpl
- templates/ts/custom-copilot-rag-customize/src/app/app.ts.tpl
- templates/ts/custom-copilot-rag-microsoft365/src/app/app.ts.tpl
Upgrade ai bot template (ts/js version)
Special characters such as slash (/), mustn't be prefixed to bot commands. [Mandatory Fix]
Welcome message must auto trigger on app install in a personal scope. If the bot doesn't send a welcome message in a personal scope, the user is lead to a dead-end. If the app doesn't include a complex configuration workflow, it's optional for the developer to trigger a welcome message in the channel or group chat scope. [Mandatory Fix]
> fix: upgrade ai bot ts/js template based on Teams store policy

- templates/csharp/ai-assistant-bot/Program.cs.tpl
- templates/csharp/ai-bot/Program.cs.tpl
Upgrade ai bot template (csharp version)
Special characters such as slash (/), mustn't be prefixed to bot commands. [Mandatory Fix]
Welcome message must auto trigger on app install in a personal scope. If the bot doesn't send a welcome message in a personal scope, the user is lead to a dead-end. If the app doesn't include a complex configuration workflow, it's optional for the developer to trigger a welcome message in the channel or group chat scope. [Mandatory Fix]
> fix: upgrade ai bot csharp template based on Teams store policy

- packages/fx-core/src/component/driver/arm/deployImpl.ts
- packages/fx-core/src/component/driver/deploy/azure/azureStaticWebAppGetDeploymentTokenDriver.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/28629021
> feat: add user agent info during ARM deploy and get SWA' deploy token

- templates/csharp/api-plugin-from-scratch-bearer/README.md
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/29015321
> fix: fix copilot plugin template readme

- .github/CODEOWNERS
add code owners for custom copilot templates in csharp
> refactor: update codeowner

- packages/fx-core/src/component/generator/apiSpec/helper.ts
- templates/python/custom-copilot-rag-custom-api/src/bot.py.tpl
bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_sprints/taskboard/AuthAndData/Microsoft%20Teams%20Extensibility/Dilithium/CY24Q3/2Wk/2Wk09%20(Jul%2028%20-%20Aug%2010)?workitem=29033812
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_sprints/taskboard/AuthAndData/Microsoft%20Teams%20Extensibility/Dilithium/CY24Q3/2Wk/2Wk09%20(Jul%2028%20-%20Aug%2010)?workitem=29033787
> fix: fix bug in ai generator python template

- packages/fx-core/src/client/teamsDevPortalClient.ts
- packages/fx-core/src/common/wrappedAxiosClient.ts
- packages/fx-core/src/component/driver/teamsApp/clients/appStudioClient.ts
- packages/fx-core/src/component/driver/teamsApp/constants.ts
- packages/fx-core/tests/common/wrappedAxiosClient.test.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/26863341
> refactor: app validation metrics

- packages/vscode-extension/syntaxes/teamsfx-toolkit-output.tmLanguage
validation error with multiple lines:
summary still correct:
> refactor: multi-line error color

- packages/fx-core/src/common/telemetry.ts
- packages/fx-core/src/error/script.ts
- packages/fx-core/tests/common/telemetry.test.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/29034406
> fix: collect script error details in telemetry

- templates/python/custom-copilot-rag-custom-api/.vscode/launch.json
- templates/python/custom-copilot-rag-custom-api/.vscode/tasks.json
bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_sprints/taskboard/AuthAndData/Microsoft%20Teams%20Extensibility/Dilithium/CY24Q3/2Wk/2Wk09%20(Jul%2028%20-%20Aug%2010)?workitem=29049677
> fix: update launch file for ai generator python template

- packages/fx-core/resource/package.nls.json
bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/29047290
> fix(collaboration): fix typo

- templates/common/api-plugin-existing-api/.vscode/launch.json.tpl
- templates/common/copilot-gpt-basic/.vscode/launch.json
- templates/common/copilot-gpt-basic/appPackage/declarativeCopilot.json.tpl
- templates/csharp/copilot-gpt-from-scratch-plugin/.{{NewProjectTypeName}}/launchSettings.json.tpl
- templates/csharp/copilot-gpt-from-scratch-plugin/Properties/launchSettings.json.tpl
- templates/csharp/copilot-gpt-from-scratch-plugin/teamsapp.local.yml.tpl
- templates/js/api-plugin-from-scratch-bearer/.vscode/launch.json.tpl
- templates/js/api-plugin-from-scratch-bearer/appPackage/repairDeclarativeCopilot.json.tpl
- templates/js/api-plugin-from-scratch-oauth/.vscode/launch.json.tpl
- templates/js/api-plugin-from-scratch-oauth/appPackage/repairDeclarativeCopilot.json.tpl
- templates/js/api-plugin-from-scratch/.vscode/launch.json.tpl
- templates/js/api-plugin-from-scratch/appPackage/repairDeclarativeCopilot.json.tpl
- templates/js/copilot-gpt-from-scratch-plugin/.vscode/launch.json
- templates/ts/api-plugin-from-scratch-bearer/.vscode/launch.json.tpl
- templates/ts/api-plugin-from-scratch-bearer/appPackage/repairDeclarativeCopilot.json.tpl
- templates/ts/api-plugin-from-scratch-oauth/.vscode/launch.json.tpl
- templates/ts/api-plugin-from-scratch-oauth/appPackage/repairDeclarativeCopilot.json.tpl
- templates/ts/api-plugin-from-scratch/.vscode/launch.json.tpl
- templates/ts/api-plugin-from-scratch/appPackage/repairDeclarativeCopilot.json.tpl
- templates/ts/copilot-gpt-from-scratch-plugin/.vscode/launch.json
[Bug 29053006](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/29053006): [Declarative Copilot Template] Description/Instruction improvement
> fix: dc template instruction/description

- packages/fx-core/src/component/generator/templates/templateReplaceMap.ts
- packages/fx-core/tests/component/generator/generator.test.ts
Fix https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/29064769
> fix: encrypt keys when scaffolding custom copilots

- packages/fx-core/src/common/stringUtils.ts
fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/29093412
> fix: entropy calculation for secret detect

- packages/fx-core/src/component/generator/templates/templateReplaceMap.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/29064769
> fix: avoid encrypting empty ai key

- templates/csharp/ai-assistant-bot/.{{NewProjectTypeName}}/.gitignore
- templates/csharp/ai-bot/.{{NewProjectTypeName}}/.gitignore
- templates/csharp/api-message-extension-sso/.{{NewProjectTypeName}}/.gitignore
- templates/csharp/api-plugin-from-scratch-bearer/.{{NewProjectTypeName}}/.gitignore
- templates/csharp/api-plugin-from-scratch-oauth/.{{NewProjectTypeName}}/.gitignore
- templates/csharp/api-plugin-from-scratch/.{{NewProjectTypeName}}/.gitignore
- templates/csharp/command-and-response/.{{NewProjectTypeName}}/.gitignore
- templates/csharp/copilot-gpt-from-scratch-plugin/.{{NewProjectTypeName}}/.gitignore
- templates/csharp/copilot-plugin-from-scratch-api-key/.{{NewProjectTypeName}}/.gitignore
- templates/csharp/copilot-plugin-from-scratch/.{{NewProjectTypeName}}/.gitignore
- templates/csharp/default-bot/.{{NewProjectTypeName}}/.gitignore
- templates/csharp/link-unfurling/.{{NewProjectTypeName}}/.gitignore
- templates/csharp/message-extension-action/.{{NewProjectTypeName}}/.gitignore
- templates/csharp/message-extension-copilot/.{{NewProjectTypeName}}/.gitignore
- templates/csharp/message-extension-search/.{{NewProjectTypeName}}/.gitignore
- templates/csharp/message-extension/.{{NewProjectTypeName}}/.gitignore
- templates/csharp/non-sso-tab-ssr/.{{NewProjectTypeName}}/.gitignore
- templates/csharp/non-sso-tab/.{{NewProjectTypeName}}/.gitignore
- templates/csharp/notification-http-timer-trigger-isolated/.{{NewProjectTypeName}}/.gitignore
- templates/csharp/notification-http-timer-trigger/.{{NewProjectTypeName}}/.gitignore
- templates/csharp/notification-http-trigger-isolated/.{{NewProjectTypeName}}/.gitignore
- templates/csharp/notification-http-trigger/.{{NewProjectTypeName}}/.gitignore
- templates/csharp/notification-timer-trigger-isolated/.{{NewProjectTypeName}}/.gitignore
- templates/csharp/notification-timer-trigger/.{{NewProjectTypeName}}/.gitignore
- templates/csharp/notification-webapi/.{{NewProjectTypeName}}/.gitignore
- templates/csharp/sso-tab-ssr/.{{NewProjectTypeName}}/.gitignore
- templates/csharp/sso-tab/.{{NewProjectTypeName}}/.gitignore
- templates/csharp/workflow/.{{NewProjectTypeName}}/.gitignore
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/28542264
> fix(template): add gitignore files to CSharp ttkproj

- templates/csharp/custom-copilot-basic/Program.cs.tpl
Fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/29179317
> fix: update template

- packages/fx-core/resource/package.nls.json
Related bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/29167327
Effect:
> fix: ui string

- templates/ts/custom-copilot-rag-custom-api/src/app/app.ts.tpl
bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_sprints/taskboard/AuthAndData/Microsoft%20Teams%20Extensibility/Dilithium/CY24Q3/2Wk/2Wk10%20(Aug%2011%20-%20Aug%2024)?workitem=29178877
> fix(template): fix custom api template

- templates/python/custom-copilot-assistant-assistants-api/README.md.tpl
- templates/python/custom-copilot-assistant-assistants-api/src/utils/creator.py.tpl
- templates/python/custom-copilot-rag-azure-ai-search/README.md.tpl
- templates/python/custom-copilot-rag-azure-ai-search/src/indexers/delete.py
- templates/python/custom-copilot-rag-azure-ai-search/src/indexers/setup.py.tpl
workitem: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/29178873
> fix: let users input key in command parameters when trigger scripts

- templates/ts/custom-copilot-rag-microsoft365/src/app/app.ts.tpl
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/29207967
> fix: fix RAG-M365 ts template app.ts

- packages/fx-core/src/question/other.ts
- packages/fx-core/tests/core/FxCore.test.ts
- packages/vscode-extension/src/handlers/manifestHandlers.ts
- packages/vscode-extension/src/telemetry/extTelemetry.ts
- packages/vscode-extension/src/telemetry/extTelemetryEvents.ts
- packages/vscode-extension/test/extTelemetry/extTelemetry.test.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/27586844
> refactor: sync manifest's telemetry and question model

- packages/fx-core/src/common/wrappedAxiosClient.ts
- packages/fx-core/src/component/constant/commonConstant.ts
- packages/fx-core/src/component/driver/teamsApp/constants.ts
- packages/fx-core/tests/common/wrappedAxiosClient.test.ts
ADO: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/29227787
> fix: appstudio api telemetry url property

- packages/sdk/package.json
- packages/sdk/pnpm-lock.yaml
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/29242936
> fix: fix axios vulnerability

- packages/api/package.json
- packages/api/pnpm-lock.yaml
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/29242943
> fix: remove axios for api package

- packages/fx-core/resource/package.nls.json
- packages/fx-core/src/component/driver/aad/create.ts
- packages/fx-core/src/component/driver/aad/error/missingServiceManagamentReferenceError.ts
- packages/fx-core/src/component/driver/aad/utility/constants.ts
- packages/fx-core/src/component/driver/botAadApp/create.ts
- packages/fx-core/tests/component/driver/aad/create.test.ts
- packages/fx-core/tests/component/driver/botAadApp/create.test.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/28970426
> feat: enforce service management reference for certain tenant

- packages/adaptivecards-tools-sdk/package.json
- packages/adaptivecards-tools-sdk/pnpm-lock.yaml
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/29242949
> fix: upgrade fast-xml-parser dependency

- templates/common/api-plugin-existing-api/appPackage/declarativeCopilot.json.tpl
- templates/common/copilot-gpt-basic/appPackage/declarativeCopilot.json.tpl
- templates/csharp/copilot-gpt-basic/appPackage/declarativeCopilot.json.tpl
- templates/csharp/copilot-gpt-from-scratch-plugin/appPackage/repairDeclarativeCopilot.json.tpl
- templates/js/api-plugin-from-scratch-bearer/appPackage/repairDeclarativeCopilot.json.tpl
- templates/js/api-plugin-from-scratch-oauth/appPackage/repairDeclarativeCopilot.json.tpl
- templates/js/api-plugin-from-scratch/appPackage/repairDeclarativeCopilot.json.tpl
- templates/js/copilot-gpt-from-scratch-plugin/appPackage/repairDeclarativeCopilot.json.tpl
- templates/ts/api-plugin-from-scratch-bearer/appPackage/repairDeclarativeCopilot.json.tpl
- templates/ts/api-plugin-from-scratch-oauth/appPackage/repairDeclarativeCopilot.json.tpl
- templates/ts/api-plugin-from-scratch/appPackage/repairDeclarativeCopilot.json.tpl
- templates/ts/copilot-gpt-from-scratch-plugin/appPackage/repairDeclarativeCopilot.json.tpl
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/29227630
> fix: update the DC schema

- templates/ts/sso-tab-with-obo-flow/api/tsconfig.json
- templates/ts/sso-tab-with-obo-flow/package.json.tpl
BUG: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/29256520
The reason I added the ajv dependency is that without it, I encounter the following error during startup:
> fix: fix sso-tab

- templates/js/custom-copilot-assistant-assistants-api/appPackage/manifest.json.tpl
- templates/js/custom-copilot-assistant-assistants-api/src/app/app.js.tpl
- templates/js/custom-copilot-assistant-new/appPackage/manifest.json.tpl
- templates/js/custom-copilot-assistant-new/src/app/app.js.tpl
- templates/js/custom-copilot-basic/appPackage/manifest.json.tpl
- templates/js/custom-copilot-basic/src/app/app.js.tpl
- templates/js/custom-copilot-rag-azure-ai-search/appPackage/manifest.json.tpl
- templates/js/custom-copilot-rag-azure-ai-search/src/app/app.js.tpl
- templates/js/custom-copilot-rag-custom-api/appPackage/manifest.json.tpl
- templates/js/custom-copilot-rag-custom-api/src/app/app.js.tpl
- templates/js/custom-copilot-rag-customize/appPackage/manifest.json.tpl
- templates/js/custom-copilot-rag-customize/src/app/app.js.tpl
- templates/js/custom-copilot-rag-microsoft365/appPackage/manifest.json.tpl
- templates/js/custom-copilot-rag-microsoft365/src/app/app.js.tpl
- templates/ts/custom-copilot-assistant-assistants-api/appPackage/manifest.json.tpl
- templates/ts/custom-copilot-assistant-assistants-api/src/app/app.ts.tpl
- templates/ts/custom-copilot-assistant-new/appPackage/manifest.json.tpl
- templates/ts/custom-copilot-assistant-new/src/app/app.ts.tpl
- templates/ts/custom-copilot-basic/appPackage/manifest.json.tpl
- templates/ts/custom-copilot-basic/src/app/app.ts.tpl
- templates/ts/custom-copilot-rag-azure-ai-search/appPackage/manifest.json.tpl
- templates/ts/custom-copilot-rag-azure-ai-search/src/app/app.ts.tpl
- templates/ts/custom-copilot-rag-custom-api/appPackage/manifest.json.tpl
- templates/ts/custom-copilot-rag-custom-api/src/app/app.ts.tpl
- templates/ts/custom-copilot-rag-customize/appPackage/manifest.json.tpl
- templates/ts/custom-copilot-rag-customize/src/app/app.ts.tpl
- templates/ts/custom-copilot-rag-microsoft365/appPackage/manifest.json.tpl
- templates/ts/custom-copilot-rag-microsoft365/src/app/app.ts.tpl
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/29180531/
> feat: CEC in M365 Copilot: enable feedbackloop and zero prompt(TS&JS)

- packages/tests/src/ui-test/telemetry/telemetry@open-vscode.test.ts
success run: https://github.com/OfficeDev/teams-toolkit/actions/runs/10713089583
bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/29318554
> test: fix ui test for telemetry

- templates/js/custom-copilot-rag-azure-ai-search/package.json.tpl
- templates/js/custom-copilot-rag-customize/package.json.tpl
- templates/js/custom-copilot-rag-microsoft365/package.json.tpl
- templates/ts/custom-copilot-assistant-assistants-api/package.json.tpl
- templates/ts/custom-copilot-assistant-new/package.json.tpl
- templates/ts/custom-copilot-basic/package.json.tpl
- templates/ts/custom-copilot-rag-azure-ai-search/package.json.tpl
- templates/ts/custom-copilot-rag-customize/package.json.tpl
- templates/ts/custom-copilot-rag-microsoft365/package.json.tpl
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/29318575
> fix: remove conflict dependency from rag templates

- packages/fx-core/src/component/generator/apiSpec/generator.ts
- packages/fx-core/tests/component/generator/apiSpecGenerator.test.ts
bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_sprints/taskboard/AuthAndData/Microsoft%20Teams%20Extensibility/Dilithium/CY24Q3/2Wk/2Wk11%20(Aug%2025%20-%20Sep%2007)?workitem=29332484
> fix(kiota): add auth actions in yaml files

- packages/api/src/types.ts
- packages/fx-core/src/component/constants.ts
- packages/fx-core/src/component/coordinator/index.ts
- packages/fx-core/src/index.ts
- packages/fx-core/src/question/create.ts
- packages/fx-core/tests/component/coordinator/coordinator.create.test.ts
- packages/fx-core/tests/question/create.test.ts
- packages/vscode-extension/package.nls.json
- packages/vscode-extension/src/handlers/createPluginWithManifestHandler.ts
- packages/vscode-extension/src/handlers/lifecycleHandlers.ts
- packages/vscode-extension/test/handlers/createPluginWithManifestHandler.test.ts
- packages/vscode-extension/test/handlers/lifecycleHandlers.test.ts
bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_sprints/taskboard/AuthAndData/Microsoft%20Teams%20Extensibility/Dilithium/CY24Q3/2Wk/2Wk11%20(Aug%2025%20-%20Sep%2007)?workitem=29332431
> perf(kiota): add dc support for kiota integration

- packages/vscode-extension/package.json
- packages/vscode-extension/src/chat/prompts.ts
- packages/vscode-extension/src/extension.ts
- packages/vscode-extension/test/chat/utils.test.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/29306950
> refactor: remove teams chat participant

- templates/js/non-sso-tab-default-bot/teamsapp.yml.tpl
[Bug 29362842](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/29362842): [VSC]create tab+msg+bot project from Developer Portal deploy failed
> fix: tab-bot template deploy

- packages/fx-core/src/common/featureFlags.ts
- packages/fx-core/src/question/constants.ts
- packages/fx-core/src/question/create.ts
- packages/fx-core/tests/question/create.test.ts
- packages/vscode-extension/package.json
- packages/vscode-extension/src/controls/webviewPanel.ts
- packages/vscode-extension/src/extension.ts
- packages/vscode-extension/src/treeview/treeViewManager.ts
- packages/vscode-extension/src/utils/projectStatusUtils.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/29307029
> refactor: change feature flag of chat participant ui entries

- packages/vscode-extension/package.json
- packages/vscode-extension/package.nls.json
- packages/vscode-extension/src/config.ts
- packages/vscode-extension/src/constants.ts
- packages/vscode-extension/src/handlers/lifecycleHandlers.ts
- packages/vscode-extension/test/handlers/lifecycleHandlers.test.ts
bug: bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_sprints/taskboard/AuthAndData/Microsoft%20Teams%20Extensibility/Dilithium/CY24Q3/2Wk/2Wk11%20(Aug%2025%20-%20Sep%2007)?workitem=29361484
> perf(kiota): add version check and vsc setting for kiota

- packages/vscode-extension/package.json
bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_sprints/taskboard/AuthAndData/Microsoft%20Teams%20Extensibility/Dilithium/CY24Q3/2Wk/2Wk11%20(Aug%2025%20-%20Sep%2007)?workitem=29397062
> docs(kiota): update message

- templates/js/api-plugin-from-scratch-bearer/src/functions/repair.js
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/29362349
> fix: fix api-key template always return empty

- packages/fx-core/src/common/featureFlags.ts
- packages/fx-core/src/component/generator/officeAddin/generator.ts
- packages/fx-core/src/question/constants.ts
- packages/fx-core/src/question/create.ts
- packages/fx-core/tests/question/create.test.ts
PM Spec [Here](https://microsoft.sharepoint.com/:w:/t/OfficePlatform/ESc9-gy6-ANOsKdGNfOm4hkBgh6fnjuQ9sezP7bpEHWB2w?e=JhfKqS)
> chore: add logic for support single meta os taskpane create option

- .github/workflows/e2e-test.yml
> fix: e2e sync to testplan

- packages/vscode-extension/src/extension.ts
- packages/vscode-extension/src/globalVariables.ts
- packages/vscode-extension/src/manifestListener.ts
- packages/vscode-extension/src/telemetry/extTelemetryEvents.ts
- packages/vscode-extension/src/treeview/treeViewManager.ts
- packages/vscode-extension/src/utils/fileSystemWatcher.ts
- packages/vscode-extension/test/extension/globalVariables.test.ts
- packages/vscode-extension/test/handlers/manifestListener.test.ts
- packages/vscode-extension/test/treeview/treeViewManager.test.ts
- packages/vscode-extension/test/utils/fileSystemWatcher.test.ts
- refresh isDeclarativeCopilot to update development tree view 5 seconds after user saving manifest.json
> perf: refresh add plugin treeview item

- templates/js/custom-copilot-rag-azure-ai-search/src/app/app.js.tpl
- templates/js/custom-copilot-rag-azure-ai-search/src/app/azureAISearchDataSource.js.tpl
- templates/js/custom-copilot-rag-azure-ai-search/src/app/customSayCommand.js
- templates/js/custom-copilot-rag-azure-ai-search/src/prompts/chat/skprompt.txt
- templates/js/custom-copilot-rag-customize/src/app/app.js.tpl
- templates/js/custom-copilot-rag-customize/src/app/customSayCommand.js
- templates/js/custom-copilot-rag-customize/src/app/myDataSource.js.tpl
- templates/js/custom-copilot-rag-customize/src/prompts/chat/skprompt.txt
- templates/js/custom-copilot-rag-microsoft365/src/app/app.js.tpl
- templates/js/custom-copilot-rag-microsoft365/src/app/customSayCommand.js
- templates/js/custom-copilot-rag-microsoft365/src/app/graphDataSource.js.tpl
- templates/js/custom-copilot-rag-microsoft365/src/prompts/chat/skprompt.txt
- templates/ts/custom-copilot-rag-azure-ai-search/src/app/app.ts.tpl
- templates/ts/custom-copilot-rag-azure-ai-search/src/app/azureAISearchDataSource.ts.tpl
- templates/ts/custom-copilot-rag-azure-ai-search/src/app/customSayCommand.ts
- templates/ts/custom-copilot-rag-azure-ai-search/src/prompts/chat/skprompt.txt
- templates/ts/custom-copilot-rag-customize/src/app/app.ts.tpl
- templates/ts/custom-copilot-rag-customize/src/app/customSayCommand.ts
- templates/ts/custom-copilot-rag-customize/src/app/myDataSource.ts.tpl
- templates/ts/custom-copilot-rag-customize/src/prompts/chat/skprompt.txt
- templates/ts/custom-copilot-rag-microsoft365/src/app/app.ts.tpl
- templates/ts/custom-copilot-rag-microsoft365/src/app/customSayCommand.ts
- templates/ts/custom-copilot-rag-microsoft365/src/app/graphDataSource.ts.tpl
- templates/ts/custom-copilot-rag-microsoft365/src/prompts/chat/skprompt.txt
implement citation in rag ts&js template
feature: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/29180531/
> feat: CEC in M365 Copilot: implement citation in rag ts&js template

- packages/fx-core/src/component/generator/officeAddin/generator.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/29428372
> fix: outlook addin use release branch

- packages/tests/src/e2e/upgrade/happyPath.tests.ts
https://github.com/OfficeDev/teams-toolkit/actions/runs/10839411152/job/30082600099
> refactor: update e2e

- packages/fx-core/resource/package.nls.json
- one more change updating "copilot" to "agent"
> refactor: string update

- templates/js/api-message-extension-sso/.vscode/launch.json
- templates/js/api-message-extension-sso/.vscode/tasks.json
- templates/js/api-plugin-from-scratch-bearer/.vscode/launch.json.tpl
- templates/js/api-plugin-from-scratch-bearer/.vscode/tasks.json.tpl
- templates/js/api-plugin-from-scratch-oauth/.vscode/launch.json.tpl
- templates/js/api-plugin-from-scratch-oauth/.vscode/tasks.json.tpl
- templates/js/api-plugin-from-scratch/.vscode/launch.json.tpl
- templates/js/api-plugin-from-scratch/.vscode/tasks.json.tpl
- templates/ts/api-message-extension-sso/.vscode/launch.json
- templates/ts/api-message-extension-sso/.vscode/tasks.json
- templates/ts/api-plugin-from-scratch-bearer/.vscode/launch.json.tpl
- templates/ts/api-plugin-from-scratch-bearer/.vscode/tasks.json.tpl
- templates/ts/api-plugin-from-scratch-oauth/.vscode/launch.json.tpl
- templates/ts/api-plugin-from-scratch-oauth/.vscode/tasks.json.tpl
- templates/ts/api-plugin-from-scratch/.vscode/launch.json.tpl
- templates/ts/api-plugin-from-scratch/.vscode/tasks.json.tpl
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_dashboards/dashboard/4612d3f0-93ed-44d3-8874-dcca9ce280d9
> fix: API plugin & API-ME-SSO debug in Teams(Desktop) not work

- templates/python/custom-copilot-basic/appPackage/manifest.json.tpl
- templates/python/custom-copilot-basic/src/bot.py.tpl
- templates/python/custom-copilot-basic/src/requirements.txt
workitem: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/29270840
Adding feedback_loop and zero-prompt
sync with: https://github.com/OfficeDev/teams-toolkit/pull/12326
> feat: add new bot UX to CEC basic chat

- packages/vscode-extension/src/extension.ts
bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_sprints/taskboard/AuthAndData/Microsoft%20Teams%20Extensibility/Dilithium/CY24Q3/2Wk/2Wk12%20(Sep%2008%20-%20Sep%2021)?workitem=29507769
> fix(kiota): fix missing correlationId in telemetry

- templates/csharp/api-plugin-from-scratch-oauth/aad.manifest.json.tpl
- templates/csharp/api-plugin-from-scratch-oauth/infra/azure.bicep.tpl
- templates/js/api-plugin-from-scratch-oauth/aad.manifest.json.tpl
- templates/js/api-plugin-from-scratch-oauth/infra/azure.bicep.tpl
- templates/ts/api-plugin-from-scratch-oauth/aad.manifest.json.tpl
- templates/ts/api-plugin-from-scratch-oauth/infra/azure.bicep.tpl
- Update the redirect URL for AAD.
- Add the AllowedClientApplications configuration for AAD.
> refactor: update the API Plugin AAD template

- templates/ts/sso-tab-with-obo-flow/api/tsconfig.json
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_sprints/taskboard/Compute%20Team/Microsoft%20Teams%20Extensibility/Dilithium/CY24Q3/2Wk/2Wk12%20(Sep%2008%20-%20Sep%2021)?workitem=29507818
> hotfix: fix sso-tab template

- packages/fx-core/resource/package.nls.json
- packages/fx-core/src/question/constants.ts
workitem: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/29449641
> feat: add works in multi platform label for CEAs

- packages/vscode-extension/src/controls/sampleGallery/sampleDetailPage.tsx
- packages/vscode-extension/src/controls/sampleGallery/sampleFilter.tsx
- packages/vscode-extension/src/controls/webviewPanel.ts
Related bug:
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/29506332
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/29506467
> fix: accessibility improvement on sample gallery

- templates/ts/sso-tab-with-obo-flow/api/tsconfig.json
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/29507818
> fix: fix sso-tab template

- templates/ts/ai-assistant-bot/tsconfig.json
- templates/ts/ai-bot/tsconfig.json
- templates/ts/command-and-response/tsconfig.json
- templates/ts/custom-copilot-assistant-assistants-api/tsconfig.json
- templates/ts/custom-copilot-assistant-new/tsconfig.json
- templates/ts/custom-copilot-basic/tsconfig.json
- templates/ts/custom-copilot-rag-azure-ai-search/tsconfig.json
- templates/ts/custom-copilot-rag-custom-api/tsconfig.json
- templates/ts/custom-copilot-rag-customize/tsconfig.json
- templates/ts/custom-copilot-rag-microsoft365/tsconfig.json
- templates/ts/default-bot-message-extension/tsconfig.json
- templates/ts/default-bot/tsconfig.json
- templates/ts/link-unfurling/tsconfig.json
- templates/ts/m365-message-extension/tsconfig.json
- templates/ts/message-extension-action/tsconfig.json
- templates/ts/message-extension-copilot/tsconfig.json
- templates/ts/message-extension/tsconfig.json
- templates/ts/non-sso-tab-default-bot/bot/tsconfig.json
- templates/ts/notification-http-timer-trigger/tsconfig.json
- templates/ts/notification-http-trigger/tsconfig.json
- templates/ts/notification-restify/tsconfig.json
- templates/ts/notification-timer-trigger/tsconfig.json
- templates/ts/workflow/tsconfig.json
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/29551664
> fix: add moduleResolution section to templates tsconfig file

- templates/ts/custom-copilot-assistant-assistants-api/tsconfig.json
- templates/ts/custom-copilot-assistant-new/tsconfig.json
- templates/ts/custom-copilot-basic/tsconfig.json
- templates/ts/custom-copilot-rag-azure-ai-search/tsconfig.json
- templates/ts/custom-copilot-rag-custom-api/tsconfig.json
- templates/ts/custom-copilot-rag-customize/tsconfig.json
- templates/ts/custom-copilot-rag-microsoft365/tsconfig.json
- templates/ts/message-extension-copilot/package.json.tpl
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/29551664
> fix: fix ts templates

- packages/fx-core/src/component/generator/apiSpec/helper.ts
- packages/fx-core/tests/component/generator/apiSpecGenerator.test.ts
bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_sprints/taskboard/AuthAndData/Microsoft%20Teams%20Extensibility/Dilithium/CY24Q3/2Wk/2Wk12%20(Sep%2008%20-%20Sep%2021)?workitem=29579699
> fix: remove spec auth support for VS

- templates/js/custom-copilot-assistant-assistants-api/src/app/app.js.tpl
- templates/js/custom-copilot-assistant-new/src/app/app.js.tpl
- templates/js/custom-copilot-basic/src/app/app.js.tpl
- templates/js/custom-copilot-rag-azure-ai-search/src/app/app.js.tpl
- templates/js/custom-copilot-rag-customize/src/app/app.js.tpl
- templates/js/custom-copilot-rag-microsoft365/src/app/app.js.tpl
- templates/ts/custom-copilot-assistant-assistants-api/src/app/app.ts.tpl
- templates/ts/custom-copilot-assistant-new/src/app/app.ts.tpl
- templates/ts/custom-copilot-basic/src/app/app.ts.tpl
- templates/ts/custom-copilot-rag-azure-ai-search/src/app/app.ts.tpl
- templates/ts/custom-copilot-rag-customize/src/app/app.ts.tpl
- templates/ts/custom-copilot-rag-microsoft365/src/app/app.ts.tpl
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/29180531/
> feat: CEC in M365 Copilot: remove Welcome Message in copilot templates (TS&JS) 

- packages/fx-core/src/component/coordinator/index.ts
- packages/fx-core/src/component/driver/teamsApp/utils/ManifestUtils.ts
- packages/fx-core/tests/component/coordinator/coordinator.create.test.ts
- packages/fx-core/tests/component/driver/teamsApp/manifestUtils.test.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/29597424
> fix: trim manifest short name

- packages/fx-core/src/component/generator/spfx/depsChecker/generatorChecker.ts
- packages/fx-core/src/component/generator/spfx/depsChecker/yoChecker.ts
- packages/fx-core/src/component/generator/spfx/spfxGenerator.ts
- packages/fx-core/src/component/generator/spfx/utils/utils.ts
- packages/fx-core/tests/component/generator/spfxGenerator.test.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/29549170/?view=edit
> fix: create SPFx project fail

- packages/fx-core/src/component/driver/teamsApp/clients/appStudioClient.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/29597088
> fix: remove axios timeout

- packages/fx-core/package.json
- packages/server/package.json
- packages/spec-parser/package.json
We will use bate release in next VS release process.
> build: rollback version after RC release

- templates/ts/custom-copilot-assistant-assistants-api/package.json.tpl
- templates/ts/custom-copilot-assistant-new/package.json.tpl
- templates/ts/custom-copilot-basic/package.json.tpl
- templates/ts/custom-copilot-rag-azure-ai-search/package.json.tpl
- templates/ts/custom-copilot-rag-custom-api/package.json.tpl
- templates/ts/custom-copilot-rag-customize/package.json.tpl
- templates/ts/custom-copilot-rag-microsoft365/package.json.tpl
Hotfix: https://dev.azure.com/msazure/Microsoft%20Teams%20Extensibility/_workitems/edit/29628374
> fix: custom copilot ts templates

- packages/fx-core/src/common/projectTypeChecker.ts
- packages/fx-core/src/component/driver/teamsApp/createAppPackage.ts
- packages/fx-core/src/component/driver/teamsApp/utils/CopilotGptManifestUtils.ts
- packages/fx-core/src/component/driver/teamsApp/utils/ManifestUtils.ts
- packages/fx-core/src/component/driver/teamsApp/validate.ts
- packages/fx-core/src/core/FxCore.ts
- packages/fx-core/tests/common/projectTypeChecker.test.ts
- packages/fx-core/tests/component/driver/teamsApp/copilotGptManifest.test.ts
- packages/fx-core/tests/component/driver/teamsApp/createAppPackage.test.ts
- packages/fx-core/tests/component/driver/teamsApp/manifestUtils.test.ts
- packages/fx-core/tests/component/driver/teamsApp/validate.test.ts
- packages/fx-core/tests/core/FxCore.test.ts
- packages/fx-core/tests/plugins/resource/appstudio/resources-multi-env/templates/appPackage/de.json
- packages/manifest/src/index.ts
- packages/manifest/src/manifest.ts
- packages/vscode-extension/src/utils/autoOpenHelper.ts
- packages/vscode-extension/test/utils/autoOpenHelper.test.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/29627957/?view=edit
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/29597112
> fix: copilot agents renaming - 5.9 prerelease

- packages/fx-core/src/component/generator/apiSpec/helper.ts
- packages/fx-core/tests/component/generator/apiSpecGenerator.test.ts
bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/29644889
> fix: remove spec auth support for VS plugin

- packages/fx-core/src/component/generator/officeAddin/generator.ts
- packages/fx-core/tests/component/generator/officeAddinGenerator.test.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/29792240
> fix: reset env after import outlook addin

- packages/spec-parser/src/constants.ts
- templates/common/api-plugin-existing-api/appPackage/declarativeAgent.json.tpl
- templates/common/copilot-gpt-basic/appPackage/declarativeAgent.json.tpl
- templates/csharp/api-plugin-from-scratch-bearer/appPackage/ai-plugin.json.tpl
- templates/csharp/api-plugin-from-scratch-oauth/appPackage/ai-plugin.dev.json.tpl
- templates/csharp/api-plugin-from-scratch-oauth/appPackage/ai-plugin.local.json.tpl
- templates/csharp/api-plugin-from-scratch/appPackage/ai-plugin.json.tpl
- templates/csharp/copilot-gpt-basic/appPackage/declarativeAgent.json.tpl
- templates/csharp/copilot-gpt-from-scratch-plugin/appPackage/ai-plugin.json.tpl
- templates/csharp/copilot-gpt-from-scratch-plugin/appPackage/repairDeclarativeAgent.json.tpl
- templates/js/api-plugin-from-scratch-bearer/appPackage/ai-plugin.json.tpl
- templates/js/api-plugin-from-scratch-bearer/appPackage/repairDeclarativeAgent.json.tpl
- templates/js/api-plugin-from-scratch-oauth/appPackage/ai-plugin.dev.json.tpl
- templates/js/api-plugin-from-scratch-oauth/appPackage/ai-plugin.local.json.tpl
- templates/js/api-plugin-from-scratch-oauth/appPackage/repairDeclarativeAgent.json.tpl
- templates/js/api-plugin-from-scratch/appPackage/ai-plugin.json.tpl
- templates/js/api-plugin-from-scratch/appPackage/repairDeclarativeAgent.json.tpl
- templates/js/copilot-gpt-from-scratch-plugin/appPackage/ai-plugin.json.tpl
- templates/js/copilot-gpt-from-scratch-plugin/appPackage/repairDeclarativeAgent.json.tpl
- templates/ts/api-plugin-from-scratch-bearer/appPackage/ai-plugin.json.tpl
- templates/ts/api-plugin-from-scratch-bearer/appPackage/repairDeclarativeAgent.json.tpl
- templates/ts/api-plugin-from-scratch-oauth/appPackage/ai-plugin.dev.json.tpl
- templates/ts/api-plugin-from-scratch-oauth/appPackage/ai-plugin.local.json.tpl
- templates/ts/api-plugin-from-scratch-oauth/appPackage/repairDeclarativeAgent.json.tpl
- templates/ts/api-plugin-from-scratch/appPackage/ai-plugin.json.tpl
- templates/ts/api-plugin-from-scratch/appPackage/repairDeclarativeAgent.json.tpl
- templates/ts/copilot-gpt-from-scratch-plugin/appPackage/ai-plugin.json.tpl
- templates/ts/copilot-gpt-from-scratch-plugin/appPackage/repairDeclarativeAgent.json.tpl
Cherry pick https://github.com/OfficeDev/teams-toolkit/pull/12425
> refactor: update the schema url for copilot extensions

- templates/csharp/api-message-extension-sso/appPackage/apiSpecificationFile/repair.yml
- templates/csharp/api-plugin-from-scratch-oauth/appPackage/apiSpecificationFile/repair.dev.yml.tpl
- templates/csharp/api-plugin-from-scratch-oauth/infra/azure.bicep.tpl
- templates/csharp/api-plugin-from-scratch-oauth/infra/azure.parameters.json.tpl
- templates/csharp/copilot-plugin-from-scratch-api-key/appPackage/apiSpecificationFile/repair.yml
- templates/csharp/copilot-plugin-from-scratch/appPackage/apiSpecificationFile/repair.yml
- templates/js/api-message-extension-sso/appPackage/apiSpecificationFile/repair.yml
- templates/js/api-message-extension-sso/src/functions/repair.js
- templates/js/api-plugin-from-scratch-oauth/appPackage/apiSpecificationFile/repair.dev.yml.tpl
- templates/js/api-plugin-from-scratch-oauth/infra/azure.bicep.tpl
- templates/js/api-plugin-from-scratch-oauth/infra/azure.parameters.json.tpl
- templates/js/copilot-plugin-from-scratch-api-key/appPackage/apiSpecificationFile/repair.yml
- templates/js/copilot-plugin-from-scratch-api-key/src/functions/repair.js
- templates/js/copilot-plugin-from-scratch/appPackage/apiSpecificationFile/repair.yml
- templates/js/copilot-plugin-from-scratch/src/functions/repair.js
- templates/ts/api-message-extension-sso/appPackage/apiSpecificationFile/repair.yml
- templates/ts/api-message-extension-sso/src/functions/repair.ts
- templates/ts/api-plugin-from-scratch-oauth/appPackage/apiSpecificationFile/repair.dev.yml.tpl
- templates/ts/api-plugin-from-scratch-oauth/infra/azure.bicep.tpl
- templates/ts/api-plugin-from-scratch-oauth/infra/azure.parameters.json.tpl
- templates/ts/copilot-plugin-from-scratch-api-key/appPackage/apiSpecificationFile/repair.yml
- templates/ts/copilot-plugin-from-scratch-api-key/src/functions/repair.ts
- templates/ts/copilot-plugin-from-scratch/appPackage/apiSpecificationFile/repair.yml
- templates/ts/copilot-plugin-from-scratch/src/functions/repair.ts
Fix the following bugs:
- https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/29662018
- https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/29723679
- https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/29723705
> fix: a few issues in the API ME and API plugin templates

- templates/csharp/ai-assistant-bot/{{ProjectName}}.csproj.tpl
- templates/csharp/ai-bot/{{ProjectName}}.csproj.tpl
- templates/csharp/command-and-response/{{ProjectName}}.csproj.tpl
- templates/csharp/custom-copilot-assistant-assistants-api/{{ProjectName}}.csproj.tpl
- templates/csharp/custom-copilot-assistant-new/{{ProjectName}}.csproj.tpl
- templates/csharp/custom-copilot-basic/{{ProjectName}}.csproj.tpl
- templates/csharp/custom-copilot-rag-azure-ai-search/{{ProjectName}}.csproj.tpl
- templates/csharp/custom-copilot-rag-custom-api/{{ProjectName}}.csproj.tpl
- templates/csharp/custom-copilot-rag-customize/{{ProjectName}}.csproj.tpl
- templates/csharp/non-sso-tab-ssr/{{ProjectName}}.csproj.tpl
- templates/csharp/non-sso-tab/{{ProjectName}}.csproj.tpl
- templates/csharp/notification-http-timer-trigger-isolated/{{ProjectName}}.csproj.tpl
- templates/csharp/notification-http-timer-trigger/{{ProjectName}}.csproj.tpl
- templates/csharp/notification-http-trigger-isolated/{{ProjectName}}.csproj.tpl
- templates/csharp/notification-http-trigger/{{ProjectName}}.csproj.tpl
- templates/csharp/notification-timer-trigger-isolated/{{ProjectName}}.csproj.tpl
- templates/csharp/notification-timer-trigger/{{ProjectName}}.csproj.tpl
- templates/csharp/notification-webapi/{{ProjectName}}.csproj.tpl
- templates/csharp/sso-tab-ssr/{{ProjectName}}.csproj.tpl
- templates/csharp/sso-tab/{{ProjectName}}.csproj.tpl
- templates/csharp/workflow/{{ProjectName}}.csproj.tpl
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/29860268
> fix: csharp templates package version

- packages/fx-core/src/question/constants.ts
[Bug 29905867](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/29905867): Add preview tag for declarative agent
> fix: add preview tag

- packages/cli/package.json
- packages/fx-core/package.json
- packages/fx-core/src/common/templates-config.json
- packages/server/package.json
- packages/tests/package.json
- @microsoft/teamsapp-cli@3.0.3
- @microsoft/teamsfx-core@2.0.10
- @microsoft/teamsfx-server@2.0.9
- @microsoft/teamsfx-test@0.0.7
- ms-teams-vscode-extension@5.8.2
- templates@4.2.4
> build(release): publish detail

- packages/fx-core/src/question/constants.ts
This reverts commit 51384c8fe1f11cced94b496961a265fafe7b6fba.
> build: revert "fix: add previe w tag"

- templates/js/api-plugin-from-scratch-bearer/README.md.tpl
- templates/js/api-plugin-from-scratch-oauth/README.md.tpl
- templates/js/api-plugin-from-scratch/README.md.tpl
- templates/ts/api-plugin-from-scratch-bearer/README.md.tpl
- templates/ts/api-plugin-from-scratch-oauth/README.md.tpl
- templates/ts/api-plugin-from-scratch/README.md.tpl
[Bug 29919208](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/29919208): [VSC] Copilot Agent API Plugin readme debug commend need update
> fix: update the README file in API Plugin templates

- templates/js/api-plugin-from-scratch-bearer/README.md.tpl
- templates/js/api-plugin-from-scratch-oauth/README.md.tpl
- templates/js/api-plugin-from-scratch/README.md.tpl
- templates/ts/api-plugin-from-scratch-bearer/README.md.tpl
- templates/ts/api-plugin-from-scratch-oauth/README.md.tpl
- templates/ts/api-plugin-from-scratch/README.md.tpl
[Bug 29919208](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/29919208): [VSC] Copilot Agent API Plugin readme debug commend need update
> fix: the readme issue in DA templates

- packages/fx-core/src/component/driver/teamsApp/utils/ManifestUtils.ts
- packages/fx-core/tests/component/driver/teamsApp/manifestUtils.test.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/29888446
> fix: return manifest file directory if in root

- templates/js/sso-tab-with-obo-flow/teamsapp.yml.tpl
- templates/ts/sso-tab-with-obo-flow/teamsapp.yml.tpl
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_sprints/taskboard/Compute%20Team/Microsoft%20Teams%20Extensibility/Selenium/CY24Q4/2Wk/2Wk02%20(Oct%2020%20-%20Nov%2002)?workitem=29870695
> fix: correct vite variable names

- templates/csharp/notification-http-timer-trigger-isolated/.{{NewProjectTypeName}}/README.md.tpl
- templates/csharp/notification-http-timer-trigger-isolated/README.md.tpl
- templates/csharp/notification-http-timer-trigger/.{{NewProjectTypeName}}/README.md.tpl
- templates/csharp/notification-http-timer-trigger/README.md.tpl
- templates/csharp/notification-http-trigger-isolated/.{{NewProjectTypeName}}/README.md.tpl
- templates/csharp/notification-http-trigger-isolated/README.md.tpl
- templates/csharp/notification-http-trigger/.{{NewProjectTypeName}}/README.md.tpl
- templates/csharp/notification-http-trigger/README.md.tpl
- templates/csharp/notification-timer-trigger-isolated/.{{NewProjectTypeName}}/README.md.tpl
- templates/csharp/notification-timer-trigger-isolated/README.md.tpl
- templates/csharp/notification-timer-trigger/.{{NewProjectTypeName}}/README.md.tpl
- templates/csharp/notification-timer-trigger/README.md.tpl
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/29988780
Ensure the **\<endpoint\>** text shown correctly in markdown preview.
> fix: correct placeholder in readme

- packages/fx-core/src/client/teamsDevPortalClient.ts
- packages/fx-core/tests/client/tdpClient.test.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/30003221
> fix: handle undenfine error

- packages/fx-core/src/component/utils/ResourceGroupHelper.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/30032873
> feat: check resource error handling

- templates/js/custom-copilot-assistant-assistants-api/package.json.tpl
- templates/js/custom-copilot-assistant-new/package.json.tpl
- templates/js/custom-copilot-assistant-new/src/app/app.js.tpl
- templates/js/custom-copilot-basic/package.json.tpl
- templates/js/custom-copilot-basic/src/app/app.js.tpl
- templates/js/custom-copilot-rag-azure-ai-search/package.json.tpl
- templates/js/custom-copilot-rag-azure-ai-search/src/app/app.js.tpl
- templates/js/custom-copilot-rag-customize/package.json.tpl
- templates/js/custom-copilot-rag-customize/src/app/app.js.tpl
- templates/js/custom-copilot-rag-microsoft365/package.json.tpl
- templates/js/custom-copilot-rag-microsoft365/src/app/app.js.tpl
- templates/ts/custom-copilot-assistant-assistants-api/package.json.tpl
- templates/ts/custom-copilot-assistant-new/package.json.tpl
- templates/ts/custom-copilot-assistant-new/src/app/app.ts.tpl
- templates/ts/custom-copilot-basic/package.json.tpl
- templates/ts/custom-copilot-basic/src/app/app.ts.tpl
- templates/ts/custom-copilot-rag-azure-ai-search/package.json.tpl
- templates/ts/custom-copilot-rag-azure-ai-search/src/app/app.ts.tpl
- templates/ts/custom-copilot-rag-customize/package.json.tpl
- templates/ts/custom-copilot-rag-customize/src/app/app.ts.tpl
- templates/ts/custom-copilot-rag-microsoft365/package.json.tpl
- templates/ts/custom-copilot-rag-microsoft365/src/app/app.ts.tpl
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/29180531/
> feat: enable stream for CEA(js/ts)

- packages/vscode-extension/src/extension.ts
bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_sprints/taskboard/AuthAndData/Microsoft%20Teams%20Extensibility/Selenium/CY24Q4/2Wk/2Wk02%20(Oct%2020%20-%20Nov%2002)?workitem=30045547
> fix(kiota): fix createPluginWithManifest no input error

- packages/vscode-extension/package.json
- packages/vscode-extension/pnpm-lock.yaml
Related bug:
1. https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/30003305
2. https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/30003313
> fix(vsc): upgrade path-to-regexp and body-parser

- templates/python/custom-copilot-basic/src/bot.py.tpl
workitem: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/30046150
> fix: fix bad import in CEA basic PY template

- packages/cli/package.json
- packages/cli/pnpm-lock.yaml
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/30046352
> fix: cli cd error

- packages/fx-core/src/question/constants.ts
- packages/fx-core/tests/component/generator/generator.test.ts
workitem: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/30044764
> refactor: modify work in M365 tag for CEA templates

- templates/python/custom-copilot-assistant-assistants-api/.vscode/launch.json.tpl
- templates/python/custom-copilot-assistant-new/.vscode/launch.json.tpl
- templates/python/custom-copilot-basic/.vscode/launch.json.tpl
- templates/python/custom-copilot-rag-azure-ai-search/.vscode/launch.json.tpl
- templates/python/custom-copilot-rag-custom-api/.vscode/launch.json.tpl
- templates/python/custom-copilot-rag-customize/.vscode/launch.json.tpl
workitem: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/30046739/
> refactor: change launch group and launch option name

- templates/js/custom-copilot-assistant-assistants-api/.vscode/launch.json.tpl
- templates/js/custom-copilot-assistant-new/.vscode/launch.json.tpl
- templates/js/custom-copilot-basic/.vscode/launch.json.tpl
- templates/js/custom-copilot-rag-azure-ai-search/.vscode/launch.json.tpl
- templates/js/custom-copilot-rag-customize/.vscode/launch.json.tpl
- templates/js/custom-copilot-rag-microsoft365/.vscode/launch.json.tpl
- templates/ts/custom-copilot-assistant-assistants-api/.vscode/launch.json.tpl
- templates/ts/custom-copilot-assistant-new/.vscode/launch.json.tpl
- templates/ts/custom-copilot-basic/.vscode/launch.json.tpl
- templates/ts/custom-copilot-rag-azure-ai-search/.vscode/launch.json.tpl
- templates/ts/custom-copilot-rag-customize/.vscode/launch.json.tpl
- templates/ts/custom-copilot-rag-microsoft365/.vscode/launch.json.tpl
1.update "Preview in Copilot" to "Debug in Copilot"
2.update group, combine local and remote
> refactor: update lanuch group in CEA(js/ts)

- packages/fx-core/src/component/generator/templates/templateNames.ts
- packages/vscode-extension/src/controls/PanelType.ts
- packages/vscode-extension/src/controls/index.tsx
- packages/vscode-extension/src/controls/webviewDocs/expressServerNotificationBot.tsx
- packages/vscode-extension/src/controls/webviewDocs/workflowBot.tsx
- packages/vscode-extension/src/controls/webviewPanel.ts
- packages/vscode-extension/src/handlers/readmeHandlers.ts
- packages/vscode-extension/test/handlers/readmeHandlers.test.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/30057931
> feat: update webview docs for notification express bot

- templates/ts/custom-copilot-rag-custom-api/package.json.tpl
- templates/ts/default-bot-message-extension/package.json.tpl
- templates/ts/m365-message-extension/package.json.tpl
- templates/ts/message-extension-action/package.json.tpl
- templates/ts/message-extension-copilot/package.json.tpl
- templates/ts/message-extension/package.json.tpl
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/30059405
> fix: update templates dependencies

- packages/fx-core/src/component/driver/script/scriptDriver.ts
- packages/fx-core/tests/component/driver/script/scriptDriver.test.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/24368119
> fix: dotnet script encoding

- packages/fx-core/src/component/driver/teamsApp/utils/CopilotGptManifestUtils.ts
- packages/fx-core/src/component/driver/teamsApp/utils/PluginManifestUtils.ts
- packages/fx-core/src/component/generator/apiSpec/generator.ts
- packages/fx-core/src/core/FxCore.ts
- packages/fx-core/tests/component/driver/teamsApp/copilotGptManifest.test.ts
- packages/fx-core/tests/component/driver/teamsApp/pluginManifestUtils.test.ts
- packages/fx-core/tests/component/generator/apiSpecGenerator.test.ts
- packages/fx-core/tests/core/FxCore.test.ts
> perf: update folder structure for kiota projects

- templates/js/non-sso-tab/package.json.tpl
- templates/js/non-sso-tab/src/app.js
- templates/ts/non-sso-tab/package.json.tpl
- templates/ts/non-sso-tab/src/app.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_sprints/taskboard/Compute%20Team/Microsoft%20Teams%20Extensibility/Selenium/CY24Q4/2Wk/2Wk02%20(Oct%2020%20-%20Nov%2002)?workitem=30017112
> fix: migrate restify to express for non-sso-tab

- packages/cli/package.json
- packages/cli/pnpm-lock.yaml
- packages/cli/src/userInteraction.ts
- packages/cli/tests/unit/ui.tests.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/27092892
https://github.com/user-attachments/assets/0f9eb4aa-5c70-441b-98c9-704485aab204
> fix: cli flickering

- packages/vscode-extension/src/debug/depsChecker/common.ts
- packages/vscode-extension/src/debug/localTelemetryReporter.ts
- packages/vscode-extension/src/globalVariables.ts
- packages/vscode-extension/test/utils/globalVars.test.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/30112986
> fix: add temetry data for terminate process in local debugging process

- packages/fx-core/templates/plugins/resource/aad/auth/bot/README.md
- templates/js/custom-copilot-rag-microsoft365/src/index.js
- templates/ts/custom-copilot-rag-microsoft365/src/index.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/30115167
> fix: fix express sso templates

- packages/fx-core/projectPath/devTools/.testTool.installInfo.json
- packages/fx-core/src/component/driver/teamsApp/utils/ManifestUtils.ts
- packages/fx-core/tests/component/driver/teamsApp/manifestUtils.test.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/30129984
> fix: fix cases of sample with no manifest

- packages/fx-core/resource/package.nls.json
- packages/fx-core/src/component/configManager/actionInjector.ts
- packages/fx-core/src/component/generator/apiSpec/helper.ts
- packages/fx-core/src/core/FxCore.ts
- packages/fx-core/tests/component/configManager/actionInjector.test.ts
- packages/fx-core/tests/component/generator/apiSpecGenerator.test.ts
- packages/fx-core/tests/core/FxCore.test.ts
[Bug 29949492](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/29949492): add plugin will not update teamsapp.yml to add auth actions
> fix: add plugin if from Api spec

- templates/python/custom-copilot-assistant-assistants-api/src/bot.py.tpl
- templates/python/custom-copilot-assistant-new/src/bot.py.tpl
- templates/python/custom-copilot-rag-azure-ai-search/src/bot.py.tpl
- templates/python/custom-copilot-rag-customize/src/bot.py.tpl
workitem: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/30136938
> refactor: add feedback loop for Python RAG&Agent CEAs

- packages/vscode-extension/package.json
- packages/vscode-extension/pnpm-lock.yaml
- packages/vscode-extension/src/debug/teamsfxTaskHandler.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/30131116
> fix: kill process tree after debug termination

- templates/csharp/api-plugin-from-scratch-bearer/appPackage/ai-plugin.json.tpl
- templates/csharp/api-plugin-from-scratch-oauth/appPackage/ai-plugin.dev.json.tpl
- templates/csharp/api-plugin-from-scratch-oauth/appPackage/ai-plugin.local.json.tpl
- templates/csharp/api-plugin-from-scratch/appPackage/ai-plugin.json.tpl
- templates/csharp/copilot-gpt-from-scratch-plugin/appPackage/ai-plugin.json.tpl
- templates/js/api-plugin-from-scratch-bearer/appPackage/ai-plugin.json.tpl
- templates/js/api-plugin-from-scratch/appPackage/ai-plugin.json.tpl
- templates/ts/api-plugin-from-scratch-bearer/appPackage/ai-plugin.json.tpl
- templates/ts/api-plugin-from-scratch/appPackage/ai-plugin.json.tpl
[Bug 29875350](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/29875350): Improve our declarative agent + plugin template AC rendering
> fix: remove unused properties from plugin templates

- packages/vscode-extension/package.json
- packages/vscode-extension/pnpm-lock.yaml
- packages/vscode-extension/src/debug/teamsfxTaskHandler.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/30131116
> fix(hotfix): kill process tree after debug terminate

- packages/vscode-extension/src/debug/teamsfxTaskHandler.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/30076176
> fix: end local debug session after sending event

- templates/js/api-message-extension-sso/.tours/custom-token-validation-without-using-Easy-Auth.tour
- templates/js/api-message-extension-sso/.vscode/extensions.json
- templates/js/api-message-extension-sso/README.md
- templates/js/api-message-extension-sso/aad.manifest.json.tpl
- templates/js/api-message-extension-sso/package.json.tpl
- templates/js/api-message-extension-sso/src/functions/middleware/authMiddleware.js
- templates/js/api-message-extension-sso/src/functions/middleware/config.js
- templates/js/api-message-extension-sso/src/functions/middleware/tokenCacheWrapper.js
- templates/js/api-message-extension-sso/src/functions/middleware/tokenValidator.js
- templates/js/api-message-extension-sso/src/functions/middleware/utils.js
- templates/js/api-message-extension-sso/src/functions/repair.js
- templates/js/api-message-extension-sso/teamsapp.local.yml.tpl
- templates/ts/api-message-extension-sso/.tours/custom-token-validation-without-using-Easy-Auth.tour
- templates/ts/api-message-extension-sso/.vscode/extensions.json
- templates/ts/api-message-extension-sso/README.md
- templates/ts/api-message-extension-sso/aad.manifest.json.tpl
- templates/ts/api-message-extension-sso/package.json.tpl
- templates/ts/api-message-extension-sso/src/functions/middleware/authMiddleware.ts
- templates/ts/api-message-extension-sso/src/functions/middleware/config.ts
- templates/ts/api-message-extension-sso/src/functions/middleware/tokenCacheWrapper.ts
- templates/ts/api-message-extension-sso/src/functions/middleware/tokenValidator.ts
- templates/ts/api-message-extension-sso/src/functions/middleware/utils.ts
- templates/ts/api-message-extension-sso/src/functions/repair.ts
- templates/ts/api-message-extension-sso/teamsapp.local.yml.tpl
[Feature 28582442](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/28582442): Add authentication to the local runtime for API ME/Type B with AAD/OAuth templates
Code Tour steps:
1. Step 1
2. Step 2
3. Step 3
4. Step 4
5. Step 5
> feat: local authentication support for API ME with AAD templates

- packages/fx-core/src/component/driver/oauth/update.ts
bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/30175466
> fix(oauth): fix sso support in oauth update action

- templates/python/custom-copilot-rag-azure-ai-search/README.md.tpl
- templates/python/custom-copilot-rag-azure-ai-search/src/indexers/setup.py.tpl
workitem: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/30176448
It is better to make this change, rather than in-readme instruction workaround.
> fix: add new parameter to set index correct

- templates/csharp/api-plugin-from-scratch-bearer/RepairData.cs.tpl
- templates/csharp/api-plugin-from-scratch-oauth/RepairData.cs.tpl
- templates/csharp/api-plugin-from-scratch/RepairData.cs.tpl
- templates/csharp/copilot-gpt-from-scratch-plugin/RepairData.cs.tpl
- templates/js/api-plugin-from-scratch-bearer/src/repairsData.json
- templates/js/api-plugin-from-scratch-oauth/appPackage/ai-plugin.json.tpl
- templates/js/api-plugin-from-scratch-oauth/src/repairsData.json
- templates/js/api-plugin-from-scratch/src/repairsData.json
- templates/js/copilot-gpt-from-scratch-plugin/src/repairsData.json
- templates/ts/api-plugin-from-scratch-bearer/src/repairsData.json
- templates/ts/api-plugin-from-scratch-oauth/appPackage/ai-plugin.json.tpl
- templates/ts/api-plugin-from-scratch-oauth/src/repairsData.json
- templates/ts/api-plugin-from-scratch/src/repairsData.json
- templates/ts/copilot-gpt-from-scratch-plugin/src/repairsData.json
[Bug 29875350](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/29875350): Improve our declarative agent + plugin template AC rendering
> fix: adaptive card rendering in DA templates

- templates/js/api-plugin-from-scratch-bearer/README.md.tpl
- templates/js/api-plugin-from-scratch-bearer/package.json.tpl
- templates/js/api-plugin-from-scratch-oauth/README.md.tpl
- templates/js/api-plugin-from-scratch-oauth/package.json.tpl
- templates/js/api-plugin-from-scratch/README.md.tpl
- templates/js/api-plugin-from-scratch/package.json.tpl
- templates/js/copilot-gpt-from-scratch-plugin/README.md
- templates/js/copilot-gpt-from-scratch-plugin/package.json.tpl
- templates/js/non-sso-tab/README.md
- templates/ts/api-plugin-from-scratch-bearer/README.md.tpl
- templates/ts/api-plugin-from-scratch-bearer/package.json.tpl
- templates/ts/api-plugin-from-scratch-oauth/README.md.tpl
- templates/ts/api-plugin-from-scratch-oauth/package.json.tpl
- templates/ts/api-plugin-from-scratch/README.md.tpl
- templates/ts/api-plugin-from-scratch/package.json.tpl
- templates/ts/copilot-gpt-from-scratch-plugin/README.md
- templates/ts/copilot-gpt-from-scratch-plugin/package.json.tpl
- templates/ts/non-sso-tab/README.md
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/30173387
> fix: upgrade nodejs to 20 for non-sso-tab & copilot agent

- templates/csharp/custom-copilot-assistant-assistants-api/{{ProjectName}}.csproj.tpl
- templates/csharp/custom-copilot-assistant-new/{{ProjectName}}.csproj.tpl
- templates/csharp/custom-copilot-basic/{{ProjectName}}.csproj.tpl
- templates/csharp/custom-copilot-rag-azure-ai-search/{{ProjectName}}.csproj.tpl
- templates/csharp/custom-copilot-rag-custom-api/{{ProjectName}}.csproj.tpl
- templates/csharp/custom-copilot-rag-customize/{{ProjectName}}.csproj.tpl
- templates/csharp/custom-copilot-rag-microsoft365/{{ProjectName}}.csproj.tpl
https://dev.azure.com/msazure/Microsoft%20Teams%20Extensibility/_workitems/edit/29988673
> refactor: update packages

- packages/spec-parser/src/manifestUpdater.ts
- packages/spec-parser/src/utils.ts
- packages/spec-parser/test/manifestUpdater.test.ts
- packages/spec-parser/test/utils.test.ts
[Bug 30188342](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/30188342): Declarative agent confirmation feature caused undefined issue
> fix(da): fix declarative agent confirmation undefined issue

- packages/vscode-extension/src/handlers/openLinkHandlers.ts
Related bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/30201397
> fix: sidebar document button handler

- packages/cli/src/commands/engine.ts
- packages/cli/src/commands/models/m365Sideloading.ts
- packages/cli/src/commands/models/m365Unacquire.ts
- packages/cli/src/telemetry/cliTelemetryEvents.ts
- packages/fx-core/src/common/secretmasker/masker.ts
- packages/fx-core/src/common/stringUtils.ts
- packages/fx-core/tests/common/secretMasker.test.ts
fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/30201013
> fix: telemetry event and property should not contains number

- templates/js/custom-copilot-rag-custom-api/appPackage/manifest.json.tpl
- templates/python/custom-copilot-rag-custom-api/appPackage/manifest.json.tpl
- templates/ts/custom-copilot-rag-custom-api/appPackage/manifest.json.tpl
[Bug 30215818](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/30215818): ManifestValidationFailed: missing required property 'commands' for Custom Copilot Rag Custom Api
> fix: manifest validation error for ai generator

- packages/api/src/qm/question.ts
- packages/api/src/qm/ui.ts
- packages/cli/src/userInteraction.ts
- packages/cli/tests/unit/engine.tests.ts
- packages/cli/tests/unit/ui2.tests.ts
- packages/vscode-extension/src/debug/depsChecker/common.ts
- packages/vscode-ui/src/ui.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/30215762
> fix: improve process loading ux for termination of process in debug

- packages/fx-core/src/component/driver/teamsApp/teamsappMgr.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/30224303
> fix(cli): name package output manifest file by input env

- templates/csharp/command-and-response/README.md.tpl
- templates/csharp/default-bot/README.md.tpl
- templates/csharp/link-unfurling/README.md.tpl
- templates/csharp/message-extension-action/README.md.tpl
- templates/csharp/message-extension-search/README.md.tpl
- templates/csharp/message-extension/README.md.tpl
- templates/csharp/notification-http-timer-trigger-isolated/README.md.tpl
- templates/csharp/notification-http-timer-trigger/README.md.tpl
- templates/csharp/notification-http-trigger-isolated/README.md.tpl
- templates/csharp/notification-http-trigger/README.md.tpl
- templates/csharp/notification-timer-trigger-isolated/README.md.tpl
- templates/csharp/notification-timer-trigger/README.md.tpl
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/30205907
> fix: add debug in teams in c# bot templates readme

- packages/manifest/src/pluginManifest.ts
- packages/spec-parser/src/manifestUpdater.ts
- packages/spec-parser/test/manifestUpdater.test.ts
- templates/csharp/api-plugin-from-scratch-bearer/appPackage/ai-plugin.json.tpl
- templates/csharp/api-plugin-from-scratch-oauth/appPackage/ai-plugin.dev.json.tpl
- templates/csharp/api-plugin-from-scratch-oauth/appPackage/ai-plugin.local.json.tpl
- templates/csharp/api-plugin-from-scratch/appPackage/ai-plugin.json.tpl
- templates/csharp/copilot-gpt-from-scratch-plugin/appPackage/ai-plugin.json.tpl
- templates/js/api-plugin-from-scratch-bearer/appPackage/ai-plugin.json.tpl
- templates/js/api-plugin-from-scratch-oauth/appPackage/ai-plugin.json.tpl
- templates/js/api-plugin-from-scratch/appPackage/ai-plugin.json.tpl
- templates/ts/api-plugin-from-scratch-bearer/appPackage/ai-plugin.json.tpl
- templates/ts/api-plugin-from-scratch-oauth/appPackage/ai-plugin.json.tpl
- templates/ts/api-plugin-from-scratch/appPackage/ai-plugin.json.tpl
[Bug 30149042](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/30149042): Update DA and Plugin Schema
> fix: remove the localization setting from plugin manifest files

- packages/fx-core/src/component/configManager/actionInjector.ts
- packages/fx-core/tests/component/configManager/actionInjector.test.ts
- packages/fx-core/tests/core/FxCore.test.ts
bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_sprints/taskboard/AuthAndData/Microsoft%20Teams%20Extensibility/Selenium/CY24Q4/2Wk/2Wk03%20(Nov%2003%20-%20Nov%2016)?workitem=30233674
> fix: fix inject auth action

- packages/spec-parser/src/constants.ts
- templates/common/api-plugin-existing-api/appPackage/declarativeAgent.json.tpl
- templates/common/copilot-gpt-basic/appPackage/declarativeAgent.json.tpl
- templates/csharp/api-plugin-from-scratch-bearer/appPackage/ai-plugin.json.tpl
- templates/csharp/api-plugin-from-scratch-oauth/appPackage/ai-plugin.dev.json.tpl
- templates/csharp/api-plugin-from-scratch-oauth/appPackage/ai-plugin.local.json.tpl
- templates/csharp/api-plugin-from-scratch/appPackage/ai-plugin.json.tpl
- templates/csharp/copilot-gpt-basic/appPackage/declarativeAgent.json.tpl
- templates/csharp/copilot-gpt-from-scratch-plugin/appPackage/ai-plugin.json.tpl
- templates/csharp/copilot-gpt-from-scratch-plugin/appPackage/repairDeclarativeAgent.json.tpl
- templates/js/api-plugin-from-scratch-bearer/appPackage/ai-plugin.json.tpl
- templates/js/api-plugin-from-scratch-bearer/appPackage/repairDeclarativeAgent.json.tpl
- templates/js/api-plugin-from-scratch-oauth/appPackage/ai-plugin.json.tpl
- templates/js/api-plugin-from-scratch-oauth/appPackage/repairDeclarativeAgent.json.tpl
- templates/js/api-plugin-from-scratch/appPackage/ai-plugin.json.tpl
- templates/js/api-plugin-from-scratch/appPackage/repairDeclarativeAgent.json.tpl
- templates/js/copilot-gpt-from-scratch-plugin/appPackage/ai-plugin.json.tpl
- templates/js/copilot-gpt-from-scratch-plugin/appPackage/repairDeclarativeAgent.json.tpl
- templates/ts/api-plugin-from-scratch-bearer/appPackage/ai-plugin.json.tpl
- templates/ts/api-plugin-from-scratch-bearer/appPackage/repairDeclarativeAgent.json.tpl
- templates/ts/api-plugin-from-scratch-oauth/appPackage/ai-plugin.json.tpl
- templates/ts/api-plugin-from-scratch-oauth/appPackage/repairDeclarativeAgent.json.tpl
- templates/ts/api-plugin-from-scratch/appPackage/ai-plugin.json.tpl
- templates/ts/api-plugin-from-scratch/appPackage/repairDeclarativeAgent.json.tpl
- templates/ts/copilot-gpt-from-scratch-plugin/appPackage/ai-plugin.json.tpl
- templates/ts/copilot-gpt-from-scratch-plugin/appPackage/repairDeclarativeAgent.json.tpl
[Bug 30149042](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/30149042): Update DA and Plugin Schema
> fix: update DA & plugin schema urls

- packages/spec-parser/src/manifestUpdater.ts
- packages/spec-parser/test/manifestUpdater.test.ts
- templates/common/api-plugin-existing-api/appPackage/declarativeAgent.json.tpl
- templates/common/copilot-gpt-basic/appPackage/declarativeAgent.json.tpl
- templates/csharp/api-plugin-from-scratch-bearer/appPackage/ai-plugin.json.tpl
- templates/csharp/api-plugin-from-scratch-oauth/appPackage/ai-plugin.dev.json.tpl
- templates/csharp/api-plugin-from-scratch-oauth/appPackage/ai-plugin.local.json.tpl
- templates/csharp/api-plugin-from-scratch/appPackage/ai-plugin.json.tpl
- templates/csharp/copilot-gpt-basic/appPackage/declarativeAgent.json.tpl
- templates/csharp/copilot-gpt-from-scratch-plugin/appPackage/ai-plugin.json.tpl
- templates/csharp/copilot-gpt-from-scratch-plugin/appPackage/repairDeclarativeAgent.json.tpl
- templates/js/api-plugin-from-scratch-bearer/appPackage/ai-plugin.json.tpl
- templates/js/api-plugin-from-scratch-bearer/appPackage/repairDeclarativeAgent.json.tpl
- templates/js/api-plugin-from-scratch-oauth/appPackage/ai-plugin.json.tpl
- templates/js/api-plugin-from-scratch-oauth/appPackage/repairDeclarativeAgent.json.tpl
- templates/js/api-plugin-from-scratch/appPackage/ai-plugin.json.tpl
- templates/js/api-plugin-from-scratch/appPackage/repairDeclarativeAgent.json.tpl
- templates/js/copilot-gpt-from-scratch-plugin/appPackage/ai-plugin.json.tpl
- templates/js/copilot-gpt-from-scratch-plugin/appPackage/repairDeclarativeAgent.json.tpl
- templates/ts/api-plugin-from-scratch-bearer/appPackage/ai-plugin.json.tpl
- templates/ts/api-plugin-from-scratch-bearer/appPackage/repairDeclarativeAgent.json.tpl
- templates/ts/api-plugin-from-scratch-oauth/appPackage/ai-plugin.json.tpl
- templates/ts/api-plugin-from-scratch-oauth/appPackage/repairDeclarativeAgent.json.tpl
- templates/ts/api-plugin-from-scratch/appPackage/ai-plugin.json.tpl
- templates/ts/api-plugin-from-scratch/appPackage/repairDeclarativeAgent.json.tpl
- templates/ts/copilot-gpt-from-scratch-plugin/appPackage/ai-plugin.json.tpl
- templates/ts/copilot-gpt-from-scratch-plugin/appPackage/repairDeclarativeAgent.json.tpl
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/30282509
> fix: update schema version

- templates/js/custom-copilot-assistant-assistants-api/.vscode/launch.json.tpl
- templates/js/custom-copilot-assistant-new/.vscode/launch.json.tpl
- templates/js/custom-copilot-basic/.vscode/launch.json.tpl
- templates/js/custom-copilot-rag-azure-ai-search/.vscode/launch.json.tpl
- templates/js/custom-copilot-rag-customize/.vscode/launch.json.tpl
- templates/js/custom-copilot-rag-microsoft365/.vscode/launch.json.tpl
- templates/ts/custom-copilot-assistant-assistants-api/.vscode/launch.json.tpl
- templates/ts/custom-copilot-assistant-new/.vscode/launch.json.tpl
- templates/ts/custom-copilot-basic/.vscode/launch.json.tpl
- templates/ts/custom-copilot-rag-azure-ai-search/.vscode/launch.json.tpl
- templates/ts/custom-copilot-rag-customize/.vscode/launch.json.tpl
- templates/ts/custom-copilot-rag-microsoft365/.vscode/launch.json.tpl
fix bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/30232352
> fix: add "cascadeTerminateToConfigurations" for CEA js/ts template

- packages/fx-core/src/core/FxCore.ts
bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_sprints/taskboard/AuthAndData/Microsoft%20Teams%20Extensibility/Selenium/CY24Q4/2Wk/2Wk04%20(Nov%2017%20-%20Nov%2030)?workitem=30295784
> fix(kiota): skip generating spec and plugin manifest

- packages/vscode-extension/package.nls.json
- packages/vscode-extension/src/handlers/accounts/switchTenantHandler.ts
Enhancement: show progress bar when switching tenant to avoid long time waiting without indication
ADO: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/30046117
> feat: show progress bar when switching is not finished

- packages/fx-core/src/component/generator/apiSpec/generator.ts
bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/30306898
> fix(kiota): fix spec path when generating auth actions

- packages/tests/src/e2e/m365/DebugM365MessageExtension.tests.ts
- packages/tests/src/e2e/m365/DeployM365MessageExtension.tests.ts
Fix https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/30332336
> fix: message extension e2e cases

- packages/vscode-extension/package.json
- packages/vscode-extension/pnpm-lock.yaml
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/30334079
> fix: upgrade dev-tunnel-ssh-tcp to 3.12.5

- packages/vscode-extension/src/commonlib/codeFlowLogin.ts
ADO: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/30091371
> feat: login with specified tenant id in codespace

- packages/fx-core/resource/yaml-schema/yaml.schema.json
- packages/fx-core/src/component/driver/oauth/create.ts
- packages/fx-core/src/component/driver/oauth/interface/createOauthOutputs.ts
- packages/fx-core/src/component/driver/teamsApp/interfaces/OauthConfigurationId.ts
- packages/fx-core/tests/component/driver/oauth/create.test.ts
bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/30310193?src=WorkItemMention&src-action=artifact_link
> fix(oauth): add app id uri in oauth register action

- packages/vscode-extension/src/debug/depsChecker/common.ts
- packages/vscode-extension/src/utils/processUtil.ts
- packages/vscode-extension/test/utils/processUtil.test.ts
* fix: silent kill process
* fix: wait some time before recheck port
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/30344887
> fix(hotfix): kill process silently (#12790)

- templates/js/dashboard-tab/vite.config.js
- templates/js/sso-tab-with-obo-flow/vite.config.js
- templates/ts/dashboard-tab/vite.config.ts
- templates/ts/sso-tab-with-obo-flow/vite.config.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/30341980
> fix: fix sso-tab & tab dashboard

- packages/vscode-extension/package.nls.json
[Bug 30356685](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/30356685): [VSC][UX]Is the first letter of help here lowercase or uppercase?
> refactor: de-capitalize string

- templates/common/copilot-gpt-basic/README.md
- templates/js/api-plugin-from-scratch-bearer/README.md.tpl
- templates/js/api-plugin-from-scratch-oauth/README.md.tpl
- templates/js/api-plugin-from-scratch/README.md.tpl
- templates/js/copilot-gpt-from-scratch-plugin/README.md
- templates/ts/api-plugin-from-scratch-bearer/README.md.tpl
- templates/ts/api-plugin-from-scratch-oauth/README.md.tpl
- templates/ts/api-plugin-from-scratch/README.md.tpl
- templates/ts/copilot-gpt-from-scratch-plugin/README.md
Fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/30160523
> docs: update DA Readme

- packages/fx-core/resource/yaml-schema/v1.7/yaml.schema.json
- packages/fx-core/resource/yaml-schema/yaml.schema.json
- packages/fx-core/src/component/driver/oauth/create.ts
- packages/fx-core/src/component/driver/oauth/interface/updateOauthArgs.ts
- packages/fx-core/src/component/driver/oauth/update.ts
- packages/fx-core/src/component/driver/oauth/utility/utility.ts
- packages/fx-core/src/component/driver/teamsApp/interfaces/OauthRegistration.ts
- packages/fx-core/tests/component/driver/oauth/update.test.ts
[Bug 30344993](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/30344993): [VSC]Debug again for Declarative project Microsoft Entra will get error：oauth/update failed
> fix: sso oauth registration update issue

- packages/vscode-extension/src/debug/depsChecker/common.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/30344887
> fix(hotfix): return cancel error when user select nothing for terminating process

- .github/workflows/e2e-test.yml
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/30371065
> ci: run cli version with specific runtime version

- templates/js/api-plugin-from-scratch-oauth/aad.manifest.json.tpl
- templates/js/api-plugin-from-scratch-oauth/teamsapp.local.yml.tpl
- templates/js/api-plugin-from-scratch-oauth/teamsapp.yml.tpl
- templates/ts/api-plugin-from-scratch-oauth/aad.manifest.json.tpl
- templates/ts/api-plugin-from-scratch-oauth/teamsapp.local.yml.tpl
- templates/ts/api-plugin-from-scratch-oauth/teamsapp.yml.tpl
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/30310193
> fix: add application id uri to DA templates with AAD authentication

- packages/api/package.json
- packages/fx-core/package.json
- packages/fx-core/src/common/templates-config.json
- packages/manifest/package.json
- packages/server/package.json
- packages/spec-parser/package.json
- templates/package.json
rollback this version changes in this commit https://github.com/OfficeDev/teams-toolkit/pull/12787
> build: rollback rc version

- packages/sdk-react/package.json
- packages/sdk/package.json
- templates/js/command-and-response/package.json.tpl
- templates/js/dashboard-tab/package.json.tpl
- templates/js/non-sso-tab-default-bot/tab/package.json.tpl
- templates/js/notification-express/package.json.tpl
- templates/js/notification-http-timer-trigger/package.json.tpl
- templates/js/notification-http-trigger/package.json.tpl
- templates/js/notification-timer-trigger/package.json.tpl
- templates/js/sso-tab-with-obo-flow/package.json.tpl
- templates/js/workflow/package.json.tpl
- templates/ts/command-and-response/package.json.tpl
- templates/ts/dashboard-tab/package.json.tpl
- templates/ts/non-sso-tab-default-bot/tab/package.json.tpl
- templates/ts/notification-express/package.json.tpl
- templates/ts/notification-http-timer-trigger/package.json.tpl
- templates/ts/notification-http-trigger/package.json.tpl
- templates/ts/notification-timer-trigger/package.json.tpl
- templates/ts/sso-tab-with-obo-flow/package.json.tpl
- templates/ts/workflow/package.json.tpl
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/30371065
https://github.com/OfficeDev/teams-toolkit/actions/runs/12113439432/job/33768485602
> test: fix e2e test case get error pkg

- templates/csharp/empty/appPackage/manifest.json.tpl
- templates/ts/office-addin/appPackage/manifest.json.tpl
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/30378613
> feat: upgrade templates
